### PR TITLE
Sonarr v3: fix for service setup

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

Amends https://github.com/SynoCommunity/spksrc/pull/5591 to update service setup `GROUP` variable to exclude DSM7 (deprecated in DSM7).

### CODE REVIEW

**Comment by mreid-tt** [comment]
@hgy59, when this bug fix is published please un-publish Sonarr v3 (Version 20221216-21) to avoid future use.

**Comment by mreid-tt** [comment]
@th0ma7, @publicarray any chance you guys could assist in getting this published? As it is basically a bug fix to the last release, once the cache servers are updated the previous v20221216-21 can be removed.

**Comment by hgy59** [comment]
@mreid-tt the first run of this package fails. It displays `Value cannot be null. Parameter name: returnLabel` in the web ui

extract from the nzbdrone.log:
```

2023-02-18 08:02:34.3|Info|LanguageProfileService|Setting up default language profiles
2023-02-18 08:02:35.4|Warn|MonoDebugCheck|Mono is not running with --debug switch
2023-02-18 08:02:39.3|Fatal|SonarrErrorPipeline|Request Failed. GET /api/v3/qualityprofile

[v3.0.9.1549] System.ArgumentNullException: Value cannot be null.
Parameter name: returnLabel
  at System.Dynamic.DynamicMetaObjectBinder.Bind (System.Object[] args, System.Collections.ObjectModel.ReadOnlyCollection`1[T] parameters, System.Linq.Expressions.LabelTarget returnLabel) [0x00190] in <9b1717c0b27f441d9bbfb7d67acd2995>:0
  at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T] (System.Runtime.CompilerServices.CallSite`1[T] site, System.Object[] args) [0x00019] in <9b1717c0b27f441d9bbfb7d67acd2995>:0
  at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3) [0x00115] in <9b1717c0b27f441d9bbfb7d67acd2995>:0
  at Nancy.Responses.Negotiation.DefaultResponseNegotiator+<GetCompatibleHeaders>d__8.MoveNext () [0x0011d] in <e31b230dbd29407fadcc55713e0bbd0f>:0
  at System.Collections.Generic.LargeArrayBuilder`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] items) [0x0005e] in <9b1717c0b27f441d9bbfb7d67acd2995>:0
  at System.Collections.Generic.EnumerableHelpers.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source) [0x00033] in <9b1717c0b27f441d9bbfb7d67acd2995>:0
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <9b1717c0b27f441d9bbfb7d67acd2995>:0
  at Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse (System.Object routeResult, Nancy.NancyContext context) [0x00202] in <e31b230dbd29407fadcc55713e0bbd0f>:0
  at Nancy.Routing.DefaultRouteInvoker+<Invoke>d__2.MoveNext () [0x0011a] in <e31b230dbd29407fadcc55713e0bbd0f>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <0a602cfb3cda43519f373bc4aed57f39>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <0a602cfb3cda43519f373bc4aed57f39>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <0a602cfb3cda43519f373bc4aed57f39>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <0a602cfb3cda43519f373bc4aed57f39>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <0a602cfb3cda43519f373bc4aed57f39>:0
  at Nancy.Routing.DefaultRequestDispatcher+<Dispatch>d__5.MoveNext () [0x002b7] in <e31b230dbd29407fadcc55713e0bbd0f>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <0a602cfb3cda43519f373bc4aed57f39>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <0a602cfb3cda43519f373bc4aed57f39>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <0a602cfb3cda43519f373bc4aed57f39>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <0a602cfb3cda43519f373bc4aed57f39>:0
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <0a602cfb3cda43519f373bc4aed57f39>:0
  at Nancy.NancyEngine+<InvokeRequestLifeCycle>d__22.MoveNext () [0x0011d] in <e31b230dbd29407fadcc55713e0bbd0f>:0
```

After stopping and starting sonarr v3 in DSM package manager, is successfully runs.

I have already uploaded version 20230217-22, but not activated. Shall I delete this?

**Comment by mreid-tt** [comment]
@hgy59, welcome back! thanks for the feedback. I've just re-run a clean install on DSM6 and DSM7 and the installs come up clean:
* DSM 6.2.4 nzbdrone.log - https://pastebin.com/JtvcCB9L
* DSM 7.1.1 nzbdrone.log - https://pastebin.com/7dpF5pQN

Can you give me some more details on your setup? For my tests I used:

DSM6: nzbdrone 20230212-22, mono 5.20.1.34-18
DSM7: nzbdrone 20230212-22, mono 5.20.1.34-19 ([unpublished](https://github.com/SynoCommunity/spksrc/actions/runs/4158324234) from #5604)

For your test, was the first run was a clean install or was it an upgrade from a previous version? I'd really like to be able to re-create the issue on my end.

I also noted that you said version 20230217-22, the build on this PR is version 20230212-22. Can you link me to your build so I can use the same `.SPK` files?

**Comment by hgy59** [comment]
@mreid-tt 20230217-22 is available on the download page (it is not yet activated to be visible in DSM package center).

Clean install of  20230217-22 shows the error on my DS218 (aarch64-6.1).
Clean install of  20221216-21 does not have this error.

**Comment by mreid-tt** [comment]
@hgy59, thanks for that. I've just done a re-install using v20230217-22 on my (VirtualDSM) DS916+ (x64-6.1) and the results are the same. I've also taken a look into the [6.1 rtd1296](https://packages.synocommunity.com/nzbdrone/22/nzbdrone.v22.f15047%5Brtd1296-armada37xx%5D.spk) and the [aarch64-6.1](https://github.com/SynoCommunity/spksrc/suites/10929744435/artifacts/552725998) packages and besides the expected difference in the INFO and syno_signature.asc files, only a minor difference in the package.tgz was present (though the decompressed contents were identical).

I can't think of a way to resolve this. Perhaps a package rebuild?

**Comment by mreid-tt** [comment]
> @mreid-tt the first run of this package fails. It displays `Value cannot be null. Parameter name: returnLabel` in the web ui

Could this be an issue with Mono? The only other place I've been able to find a similar error is https://github.com/mono/mono/issues/16770 and https://github.com/linuxserver/docker-sonarr/issues/72. While these are not identical, I'd be curious as to your Mono setup.

**Comment by hgy59** [comment]
oops, sorry, forget to mention: Installed mono is `5.8.0.108-11`

are we ready to define  `SPK_DEPENDS = "mono>=5.20"` ?

**Comment by mreid-tt** [comment]
I've re-run a clean install on my DSM6 setup using mono 5.8.0.108-11 but I could not recreate the error. Did it happen consistently on clean install (more than once)? 

As for the upgraded requirements for mono, you previously indicated in https://github.com/SynoCommunity/spksrc/pull/5515#discussion_r1047752572:

> there are issues with 5.20 and aarch64 on DSM 6 (built with DSM 6 toolchain)

I'd be happy to change the requirements since within Sonarr v3, the following error is seen: `Currently installed Mono version 5.8.0.108 is no longer supported. Please upgrade Mono to version 5.20.`
Has the situation with this changed?

**Comment by mreid-tt** [comment]
> `Value cannot be null. Parameter name: returnLabel`

This error is also very unique as I can't seem to find any reference on the Internet for `returnLabel` in an error. If I expand my search parameters I come across some Microsoft scripting documentation for '[CallSiteBinder](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callsitebinder.bind?view=netframework-4.6)' that says:

> **returnLabel**	[LabelTarget](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.labeltarget?view=netframework-4.6)
A LabelTarget used to return the result of the dynamic binding.

I don't know if this sheds any light on the issue but there was not much to be found on this particular error.

**Comment by mreid-tt** [comment]
@hgy59, I believe that across all the changes in the three PRs between v20221216-21 and v20230217-22 there would not be an issue within Sonarr v3 itself contributing to the first run error you cited. My vote would be to activate it. We can also approve and release the new Mono in #5604 which resolves the certificate validation errors since the community has been waiting on this for a while.

**Comment by mreid-tt** [comment]
@hgy59, as it's been a couple days I am wondering if the cache servers have been fully updated? If so, gentle reminder to de-activate Version 20221216-21.

**Comment by hgy59** [comment]
My diskstations still show version 20221216-21 in the package center, so I will wait another day (can't remember at which time I activated the packages in the repo. Upload was on 2023-02-18 06:45 UTC)

**Comment by hgy59** [comment]
> @hgy59, as it's been a couple days I am wondering if the cache servers have been fully updated? If so, gentle reminder to de-activate Version 20221216-21.

done.

**Pull request merged**
