### PR TITLE
feat: Update fish to 3.3.1

### PR DESCRIPTION
**Pull request by etcusrvar**
_Motivation:_  Update fish to 3.3.1

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Review by ymartin59 — APPROVED** [review]

**Review by hgy59 — COMMENTED** [review]
is this really "gold" linker or just "old" linker?

**Comment by publicarray** [comment]
@hgy59 I know yes really :rofl:, I've not heard about it before until my earlier encounter with the same issue here: https://github.com/SynoCommunity/spksrc/pull/4494#issuecomment-817045003

If you need proof: See the patch file:

`if ("${LD_VERSION}" MATCHES "GNU gold")`

`set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fuse-ld=gold")`

https://en.wikipedia.org/wiki/Gold_(linker)

**Comment by etcusrvar** [comment]
Since we're removing the gold linker stuff from a patch named ...remove-gold-linker..., wouldn't it make sense to remove the patch file entirely?
Are the `add_compile_options...` and `source_group...` lines really needed?

**Comment by publicarray** [comment]
No, The patch removes the lines from the cmake file in the fish source code. The lines begin with -. If they where + then we would add lines.

**Comment by publicarray** [comment]
Those two lines give context about where in the source the patch should be applied. The file was auto generated.

**Pull request merged**
