### PR TITLE
version bump brotli to v1.1.0

### PR DESCRIPTION
**Pull request by zyrill**
## Description

Updated brotli lib from v1.0.9 to v1.1.0

For changes, see official release notes: https://github.com/google/brotli/releases/tag/v1.1.0

## Checklist

* [ ] Build rule `all-supported` completed successfully
* [ ] New installation of package completed successfully
* [ ] Package upgrade completed successfully (Manually install the package again)
* [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
* [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

* [ ] Bug fix
* [ ] New Package
* [x] Package update
* [ ] Includes small framework changes
* [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
@zyrill PLEASE avoid such pull requests (#6109, #6110, #6111, #6112) !
Those are not "package updates" since with packages we mean spk (Synology Package).

Your PRs are like "library updates" and affect multiple packages.
If there are no security issues (or package updates that require updated dependencies) there is no reason to update anything.

**Comment by hgy59** [comment]
@th0ma7 can we update the development guides to avoid such unrelated PRs?

Those are such a waist of resources (github build resources and maintainer time).

**Comment by zyrill** [comment]
> @zyrill PLEASE avoid such pull requests (#6109, #6110, #6111, #6112, #6113, #6114, #6115, #6116, #6117, #6118, #6119, #6120, #6121) ! Those are not "package updates" since with packages we mean spk (Synology Package).
> 
> Your PRs are like "library updates" and affect multiple packages. If there are no security issues (or package updates that require updated dependencies) there is no reason to update anything.

I thought I was helping. Apologies.

**Comment by hgy59** [comment]
@zyrill, one reason for the poor quality of such PRs is the lack of updating the `PLIST` files.

If updated libraries change the (version part) of the target file name(s), the PLIST files must reflect these changes.
However, if a PR also contains changed packages that depend on updated libraries, they would fail if the PLIST files do not reflect the change.

**Comment by mreid-tt** [comment]
> @zyrill PLEASE avoid such pull requests (#6109, #6110, #6111, #6112, #6113, #6114, #6115, #6116, #6117, #6118, #6119, #6120, #6121) ! Those are not "package updates" since with packages we mean spk (Synology Package).

> @zyrill, one reason for the poor quality of such PRs is the lack of updating the `PLIST` files.
> 
> If updated libraries change the (version part) of the target file name(s), the PLIST files must reflect these changes. However, if a PR also contains changed packages that depend on updated libraries, they would fail if the PLIST files do not reflect the change.

@hgy59, should all these PRs be closed or should they be consolidated (perhaps into a single PR?) with corrected `PLIST` files as you have indicated? Not sure what is the recommended way forward for these.

**Comment by th0ma7** [comment]
Really they should all be closed and our documentation updated to explain right use cases when proposing a PR.

**Pull request closed without merging**
