### PR TITLE
Sonarr runs mono with debug flag

### PR DESCRIPTION
**Pull request by maxrogers**
Changed so that mono runs in debug mode to assist Sonarr devs when troubleshooting issues (adds line numbers to logging.)

### CODE REVIEW

**Comment by Diaoul** [comment]
@Dr-Bean: Can you publish?
@maxrogers: please register to https://synocommunity.com/register so I can grant you publish permissions

**Comment by Dr-Bean** [comment]
Will do, should be uploaded later today.
It would probably make sense to set up a buildbot sometime in the future...

**Comment by Dr-Bean** [comment]
Sonarr-20150213-5 has been published.

**Comment by maxrogers** [comment]
@Diaoul I registered as maxrogers. Thanks!

**Comment by Diaoul** [comment]
@maxrogers: you should be able to publish next versions of mono & nzbdrone (sonarr)
See https://synocommunity.com/admin/

**Comment by maxrogers** [comment]
@Diaoul, awesome. Thanks! I created my API key. Is there any documentation or guidance on publishing packages to spksrc repo?

**Comment by cytec** [comment]
@maxrogers afiak not but if i remember that right:

1. run make setup in main dir (spksrc)
2. Insert api key in local.mk
3. compile and publish package  (make publish-arch-xyz)

3rd step should be autocompletable via tab

**Comment by Dr-Bean** [comment]
Yep, that's right. Check out [spk.mk](https://github.com/SynoCommunity/spksrc/blob/develop/mk/spksrc.spk.mk#L310) for the available rules. There's a bit of explanation on what each rule does.

`all-archs-latest`, and the equivalent publishing rule, `publish-all-archs-latest` are probably the most sensible rules to use when e.g. a updated package should be built/released.
For Mono and Sonarr, that rule will attempt (and then skip) a lot of the available combinations, but that doesn't matter too much.

**Pull request merged**
