### PR TITLE
ffmpeg-videostation: divert ffmpeg to SynoCommunity version

### PR DESCRIPTION
**Pull request by ymartin59**
_Motivation:_  Ease use of SynoCommunity ffmpeg version in VideoSation.
_Linked issues:_  #2952

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
@th0ma7 I quickly build this for me to test ffmpeg patches... as I have some mkv VideoStation fails to play too.

**Comment by th0ma7** [comment]
Good, have a look at my latest `-18` build in my github repo.
I think I have nailed most of the issues but ffmpeg is a heck of a beast.
What mainly missing are testing files everyone could use for proper testing along with various ways of testing things out, with and without videostation.

**Comment by kc6108** [comment]
`main 10` wouldn't be found it's `Main 10`. It's also 7 characters long, so IGNORE should be changed to IGNORED perhaps.

**Comment by th0ma7** [comment]
Along with a move or copy of `libsynovte.so-BACKUP` into it's original place in `stop_daemon ()`

**Comment by ymartin59** [comment]
@th0ma7 Your sed proposal is a concise good idea I will give it a try

**Comment by th0ma7** [comment]
Maybie also appropriate to use a wrapper instead of symlinks such as:
https://gist.github.com/BenjaminPoncet/bbef9edc1d0800528813e75c1669e57e

**Comment by th0ma7** [comment]
Created a new wrapper that does fix the spawning of multiple ffmpeg processes:
https://github.com/th0ma7/synology/blob/master/VideoStation/ffmpeg
I'll have it tested by the community and if working out well then we could include it to this package.

**Comment by th0ma7** [comment]
Totally untested but I had a few ideas I wanted to share.  Thoughts?

**Pull request closed without merging**
