### PR TITLE
synocli-file: update rmlint to support reflink

### LINKED ISSUE #5459: synocli-file: rmlint is not complied with blkid , no reflink support
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

synocli-file

### Package Version

v2.7-17

### Device Model

DS1821+

### Device Architecture

x86_64

### Firmware Version

DSM 7.1-42661 Update 4

### What happened?

Run rmlint with the options to reflink duplicate file on btrfs volumes

```
$ rmlint -c "sh:handler=clone,reflink"
WARNING: reflink will not be emitted: please compile with blkid and gio-unix-2.0.
```

### Reproduction steps

```bash
1. install synocli-file
2. run rmlint with reflink handler
3. error not compiled with blkid
```

### Install Log

```log
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin preinst
2022/05/02 23:22:14	Begin reload_inst_variables
2022/05/02 23:22:14	End reload_inst_variables
2022/05/02 23:22:14	Begin initialize_variables
2022/05/02 23:22:14	End initialize_variables
2022/05/02 23:22:14	===> Step preinst. USER= GROUP= SHARE_PATH=
2022/05/02 23:22:14	install synocli-file 2.5-13 End preinst ret=[0]
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin /bin/mkdir -p /volume1/@appstore/synocli-file
2022/05/02 23:22:14	install synocli-file 2.5-13 End /bin/mkdir -p /volume1/@appstore/synocli-file ret=[0]
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin /bin/rm -rf /volume1/@appstore/synocli-file
2022/05/02 23:22:14	install synocli-file 2.5-13 End /bin/rm -rf /volume1/@appstore/synocli-file ret=[0]
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin /bin/mv -f /volume1/@tmp/pkginstall/extract.TEXv9w/package /volume1/@appstore/synocli-file
2022/05/02 23:22:14	install synocli-file 2.5-13 End /bin/mv -f /volume1/@tmp/pkginstall/extract.TEXv9w/package /volume1/@appstore/synocli-file ret=[0]
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin /bin/rm -rf /var/packages/synocli-file
2022/05/02 23:22:14	install synocli-file 2.5-13 End /bin/rm -rf /var/packages/synocli-file ret=[0]
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin /bin/mkdir -p /var/packages/synocli-file
2022/05/02 23:22:14	install synocli-file 2.5-13 End /bin/mkdir -p /var/packages/synocli-file ret=[0]
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin /bin/touch /var/packages/synocli-file/installing
2022/05/02 23:22:14	install synocli-file 2.5-13 End /bin/touch /var/packages/synocli-file/installing ret=[0]
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin /bin/mv -f /volume1/@tmp/pkginstall/extract.TEXv9w/INFO /var/packages/synocli-file/INFO
2022/05/02 23:22:14	install synocli-file 2.5-13 End /bin/mv -f /volume1/@tmp/pkginstall/extract.TEXv9w/INFO /var/packages/synocli-file/INFO ret=[0]
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin /bin/rm -rf /var/packages/synocli-file/scripts
2022/05/02 23:22:14	install synocli-file 2.5-13 End /bin/rm -rf /var/packages/synocli-file/scripts ret=[0]
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin /bin/mv -f /volume1/@tmp/pkginstall/extract.TEXv9w/scripts /var/packages/synocli-file/scripts
2022/05/02 23:22:14	install synocli-file 2.5-13 End /bin/mv -f /volume1/@tmp/pkginstall/extract.TEXv9w/scripts /var/packages/synocli-file/scripts ret=[0]
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin /bin/rm -rf /var/packages/synocli-file/WIZARD_UIFILES
2022/05/02 23:22:14	install synocli-file 2.5-13 End /bin/rm -rf /var/packages/synocli-file/WIZARD_UIFILES ret=[0]
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin /bin/mv -f /volume1/@tmp/pkginstall/extract.TEXv9w/WIZARD_UIFILES /var/packages/synocli-file/WIZARD_UIFILES
2022/05/02 23:22:14	install synocli-file 2.5-13 End /bin/mv -f /volume1/@tmp/pkginstall/extract.TEXv9w/WIZARD_UIFILES /var/packages/synocli-file/WIZARD_UIFILES ret=[0]
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin /bin/rm -rf /var/packages/synocli-file/conf
2022/05/02 23:22:14	install synocli-file 2.5-13 End /bin/rm -rf /var/packages/synocli-file/conf ret=[0]
2022/05/02 23:22:14	install synocli-file 2.5-13 Begin /bin/mv -f /volume1/@tmp/pkginstall/extract.TEXv9w/conf /var/packages/synocli-file/conf
2022/05/02 23:22:14	install synocli-file 2.5-13 End /bin/mv -f /volume1/@tmp/pkginstall/extract.TEXv9w/conf /var/packages/synocli-file/conf ret=[0]
2022/05/02 23:22:15	install synocli-file 2.5-13 Begin postinst
2022/05/02 23:22:15	Begin reload_inst_variables
2022/05/02 23:22:15	End reload_inst_variables
2022/05/02 23:22:15	Begin initialize_variables
2022/05/02 23:22:15	End initialize_variables
2022/05/02 23:22:15	===> Step postinst. USER= GROUP= SHARE_PATH=
2022/05/02 23:22:15	Begin save_wizard_variables
2022/05/02 23:22:15	End save_wizard_variables
2022/05/02 23:22:15	Begin syno_sync_var_folder
2022/05/02 23:22:15	End syno_sync_var_folder
2022/05/02 23:22:15	Begin service_postinst
2022/05/02 23:22:15	End service_postinst
2022/05/02 23:22:15	install synocli-file 2.5-13 End postinst ret=[0]
2022/05/02 23:22:17	install synocli-file 2.5-13 Begin start-stop-status start
2022/05/02 23:22:17	install synocli-file 2.5-13 End start-stop-status start ret=[0]
2022/05/12 20:27:52	(system) trigger synocli-file 2.5-13 Begin start-stop-status stop
2022/05/12 20:27:52	(system) trigger synocli-file 2.5-13 End start-stop-status stop ret=[0]
2022/05/12 20:29:08	(system) trigger synocli-file 2.5-13 Begin start-stop-status start
2022/05/12 20:29:08	(system) trigger synocli-file 2.5-13 End start-stop-status start ret=[0]
2022/05/24 21:08:18	(system) trigger synocli-file 2.5-13 Begin start-stop-status stop
2022/05/24 21:08:18	(system) trigger synocli-file 2.5-13 End start-stop-status stop ret=[0]
2022/07/07 13:43:00	(system) trigger synocli-file 2.5-13 Begin start-stop-status start
2022/07/07 13:43:00	(system) trigger synocli-file 2.5-13 End start-stop-status start ret=[0]
2022/07/07 21:09:33	(system) trigger synocli-file 2.5-13 Begin start-stop-status stop
2022/07/07 21:09:33	(system) trigger synocli-file 2.5-13 End start-stop-status stop ret=[0]
2022/07/07 21:12:18	(system) trigger synocli-file 2.5-13 Begin start-stop-status start
2022/07/07 21:12:19	(system) trigger synocli-file 2.5-13 End start-stop-status start ret=[0]
2022/07/07 21:21:16	upgrade synocli-file 2.5-13 Begin start-stop-status stop
2022/07/07 21:21:16	upgrade synocli-file 2.5-13 End start-stop-status stop ret=[0]
2022/07/07 21:21:16	upgrade synocli-file 2.5-13 Begin preupgrade
2022/07/07 21:21:16	Begin reload_inst_variables
2022/07/07 21:21:16	End reload_inst_variables
2022/07/07 21:21:16	Begin initialize_variables
2022/07/07 21:21:16	End initialize_variables
2022/07/07 21:21:16	===> Step preupgrade. USER= GROUP= SHARE_PATH=
2022/07/07 21:21:16	upgrade synocli-file 2.5-13 End preupgrade ret=[0]
2022/07/07 21:21:16	upgrade synocli-file 2.5-13 Begin preuninst
2022/07/07 21:21:16	Begin reload_inst_variables
2022/07/07 21:21:16	End reload_inst_variables
2022/07/07 21:21:16	Begin initialize_variables
2022/07/07 21:21:16	End initialize_variables
2022/07/07 21:21:16	===> Step preuninst. USER= GROUP= SHARE_PATH=
2022/07/07 21:21:16	upgrade synocli-file 2.5-13 End preuninst ret=[0]
2022/07/07 21:21:17	upgrade synocli-file 2.5-13 Begin /bin/rm -rf /volume1/@appstore/synocli-file
2022/07/07 21:21:18	upgrade synocli-file 2.5-13 End /bin/rm -rf /volume1/@appstore/synocli-file ret=[0]
2022/07/07 21:21:18	upgrade synocli-file 2.5-13 Begin /bin/rm -rf /volume1/@apptemp/synocli-file
2022/07/07 21:21:18	upgrade synocli-file 2.5-13 End /bin/rm -rf /volume1/@apptemp/synocli-file ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.5-13 Begin postuninst
2022/07/07 21:21:19	Begin reload_inst_variables
2022/07/07 21:21:19	End reload_inst_variables
2022/07/07 21:21:19	Begin initialize_variables
2022/07/07 21:21:19	End initialize_variables
2022/07/07 21:21:19	===> Step postuninst. USER= GROUP= SHARE_PATH=
2022/07/07 21:21:19	upgrade synocli-file 2.5-13 End postuninst ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin preinst
2022/07/07 21:21:19	Begin reload_inst_variables
2022/07/07 21:21:19	End reload_inst_variables
2022/07/07 21:21:19	Begin initialize_variables
2022/07/07 21:21:19	End initialize_variables
2022/07/07 21:21:19	===> Step preinst. USER= GROUP= SHARE_PATH=
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End preinst ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin /bin/mkdir -p /volume1/@appstore/synocli-file -m 755
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End /bin/mkdir -p /volume1/@appstore/synocli-file -m 755 ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin /bin/rm -rf /volume1/@appstore/synocli-file
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End /bin/rm -rf /volume1/@appstore/synocli-file ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin /bin/mv -f /volume1/@tmp/synopkg/install.7MoFM2/package /volume1/@appstore/synocli-file
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End /bin/mv -f /volume1/@tmp/synopkg/install.7MoFM2/package /volume1/@appstore/synocli-file ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin /bin/rm -rf /var/packages/synocli-file
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End /bin/rm -rf /var/packages/synocli-file ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin /bin/mkdir -p /var/packages/synocli-file -m 755
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End /bin/mkdir -p /var/packages/synocli-file -m 755 ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin /bin/touch /var/packages/synocli-file/installing
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End /bin/touch /var/packages/synocli-file/installing ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin /bin/mv -f /volume1/@tmp/synopkg/install.7MoFM2/INFO /var/packages/synocli-file/INFO
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End /bin/mv -f /volume1/@tmp/synopkg/install.7MoFM2/INFO /var/packages/synocli-file/INFO ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin /bin/rm -rf /var/packages/synocli-file/scripts
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End /bin/rm -rf /var/packages/synocli-file/scripts ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin /bin/mv -f /volume1/@tmp/synopkg/install.7MoFM2/scripts /var/packages/synocli-file/scripts
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End /bin/mv -f /volume1/@tmp/synopkg/install.7MoFM2/scripts /var/packages/synocli-file/scripts ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin /bin/rm -rf /var/packages/synocli-file/WIZARD_UIFILES
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End /bin/rm -rf /var/packages/synocli-file/WIZARD_UIFILES ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin /bin/mv -f /volume1/@tmp/synopkg/install.7MoFM2/WIZARD_UIFILES /var/packages/synocli-file/WIZARD_UIFILES
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End /bin/mv -f /volume1/@tmp/synopkg/install.7MoFM2/WIZARD_UIFILES /var/packages/synocli-file/WIZARD_UIFILES ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin /bin/rm -rf /var/packages/synocli-file/conf
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End /bin/rm -rf /var/packages/synocli-file/conf ret=[0]
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 Begin /bin/mv -f /volume1/@tmp/synopkg/install.7MoFM2/conf /var/packages/synocli-file/conf
2022/07/07 21:21:19	upgrade synocli-file 2.6-16 End /bin/mv -f /volume1/@tmp/synopkg/install.7MoFM2/conf /var/packages/synocli-file/conf ret=[0]
2022/07/07 21:21:20	upgrade synocli-file 2.6-16 Begin postinst
2022/07/07 21:21:20	Begin reload_inst_variables
2022/07/07 21:21:20	End reload_inst_variables
2022/07/07 21:21:20	Begin initialize_variables
2022/07/07 21:21:20	End initialize_variables
2022/07/07 21:21:20	===> Step postinst. USER= GROUP= SHARE_PATH=
2022/07/07 21:21:20	Begin save_wizard_variables
2022/07/07 21:21:20	End save_wizard_variables
2022/07/07 21:21:20	Begin syno_sync_var_folder
2022/07/07 21:21:20	End syno_sync_var_folder
2022/07/07 21:21:20	Begin service_postinst
2022/07/07 21:21:20	End service_postinst
2022/07/07 21:21:20	upgrade synocli-file 2.6-16 End postinst ret=[0]
2022/07/07 21:21:20	upgrade synocli-file 2.6-16 Begin postupgrade
2022/07/07 21:21:20	Begin reload_inst_variables
2022/07/07 21:21:20	End reload_inst_variables
2022/07/07 21:21:20	Begin initialize_variables
2022/07/07 21:21:20	End initialize_variables
2022/07/07 21:21:20	===> Step postupgrade. USER= GROUP= SHARE_PATH=
2022/07/07 21:21:20	Begin syno_sync_var_folder
2022/07/07 21:21:20	End syno_sync_var_folder
2022/07/07 21:21:20	upgrade synocli-file 2.6-16 End postupgrade ret=[0]
2022/07/07 21:21:20	upgrade synocli-file 2.6-16 Begin start-stop-status start
2022/07/07 21:21:20	upgrade synocli-file 2.6-16 End start-stop-status start ret=[0]
2022/07/09 21:49:37	(system) trigger synocli-file 2.6-16 Begin start-stop-status stop
2022/07/09 21:49:37	(system) trigger synocli-file 2.6-16 End start-stop-status stop ret=[0]
2022/07/11 16:28:20	(system) trigger synocli-file 2.6-16 Begin start-stop-status start
2022/07/11 16:28:20	(system) trigger synocli-file 2.6-16 End start-stop-status start ret=[0]
2022/07/13 11:58:12	(system) trigger synocli-file 2.6-16 Begin start-stop-status start
2022/07/13 11:58:12	(system) trigger synocli-file 2.6-16 End start-stop-status start ret=[0]
2022/07/14 20:09:40	(system) trigger synocli-file 2.6-16 Begin start-stop-status stop
2022/07/14 20:09:40	(system) trigger synocli-file 2.6-16 End start-stop-status stop ret=[0]
2022/07/14 20:10:58	(system) trigger synocli-file 2.6-16 Begin start-stop-status start
2022/07/14 20:10:58	(system) trigger synocli-file 2.6-16 End start-stop-status start ret=[0]
2022/08/08 23:19:20	(system) trigger synocli-file 2.6-16 Begin start-stop-status stop
2022/08/08 23:19:20	(system) trigger synocli-file 2.6-16 End start-stop-status stop ret=[0]
2022/08/10 00:00:15	(system) trigger synocli-file 2.6-16 Begin start-stop-status start
2022/08/10 00:00:15	(system) trigger synocli-file 2.6-16 End start-stop-status start ret=[0]
2022/08/18 22:50:41	(system) trigger synocli-file 2.6-16 Begin start-stop-status stop
2022/08/18 22:50:41	(system) trigger synocli-file 2.6-16 End start-stop-status stop ret=[0]
2022/09/02 17:11:47	(system) trigger synocli-file 2.6-16 Begin start-stop-status start
2022/09/02 17:11:47	(system) trigger synocli-file 2.6-16 End start-stop-status start ret=[0]
2022/09/07 22:03:22	(system) trigger synocli-file 2.6-16 Begin start-stop-status stop
2022/09/07 22:03:22	(system) trigger synocli-file 2.6-16 End start-stop-status stop ret=[0]
2022/09/07 22:06:17	(system) trigger synocli-file 2.6-16 Begin start-stop-status start
2022/09/07 22:06:17	(system) trigger synocli-file 2.6-16 End start-stop-status start ret=[0]
2022/09/07 22:08:53	upgrade synocli-file 2.6-16 Begin start-stop-status stop
2022/09/07 22:08:53	upgrade synocli-file 2.6-16 End start-stop-status stop ret=[0]
2022/09/07 22:08:54	upgrade synocli-file 2.6-16 Begin preupgrade
2022/09/07 22:08:54	Begin reload_inst_variables
2022/09/07 22:08:54	End reload_inst_variables
2022/09/07 22:08:54	Begin initialize_variables
2022/09/07 22:08:54	End initialize_variables
2022/09/07 22:08:54	===> Step preupgrade. USER= GROUP= SHARE_PATH=
2022/09/07 22:08:54	upgrade synocli-file 2.6-16 End preupgrade ret=[0]
2022/09/07 22:08:54	upgrade synocli-file 2.6-16 Begin preuninst
2022/09/07 22:08:54	Begin reload_inst_variables
2022/09/07 22:08:54	End reload_inst_variables
2022/09/07 22:08:54	Begin initialize_variables
2022/09/07 22:08:54	End initialize_variables
2022/09/07 22:08:54	===> Step preuninst. USER= GROUP= SHARE_PATH=
2022/09/07 22:08:54	upgrade synocli-file 2.6-16 End preuninst ret=[0]
2022/09/07 22:08:54	upgrade synocli-file 2.6-16 Begin /bin/rm -rf /volume1/@appstore/synocli-file
2022/09/07 22:08:55	upgrade synocli-file 2.6-16 End /bin/rm -rf /volume1/@appstore/synocli-file ret=[0]
2022/09/07 22:08:55	upgrade synocli-file 2.6-16 Begin /bin/rm -rf /volume1/@apptemp/synocli-file
2022/09/07 22:08:55	upgrade synocli-file 2.6-16 End /bin/rm -rf /volume1/@apptemp/synocli-file ret=[0]
2022/09/07 22:08:55	upgrade synocli-file 2.6-16 Begin postuninst
2022/09/07 22:08:55	Begin reload_inst_variables
2022/09/07 22:08:55	End reload_inst_variables
2022/09/07 22:08:55	Begin initialize_variables
2022/09/07 22:08:55	End initialize_variables
2022/09/07 22:08:55	===> Step postuninst. USER= GROUP= SHARE_PATH=
2022/09/07 22:08:55	upgrade synocli-file 2.6-16 End postuninst ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin preinst
2022/09/07 22:08:56	Begin reload_inst_variables
2022/09/07 22:08:56	End reload_inst_variables
2022/09/07 22:08:56	Begin initialize_variables
2022/09/07 22:08:56	End initialize_variables
2022/09/07 22:08:56	===> Step preinst. USER= GROUP= SHARE_PATH=
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End preinst ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin /bin/mkdir -p /volume1/@appstore/synocli-file -m 755
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End /bin/mkdir -p /volume1/@appstore/synocli-file -m 755 ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin /bin/rm -rf /volume1/@appstore/synocli-file
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End /bin/rm -rf /volume1/@appstore/synocli-file ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin /bin/mv -f /volume1/@tmp/synopkg/install.bMOGev/package /volume1/@appstore/synocli-file
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End /bin/mv -f /volume1/@tmp/synopkg/install.bMOGev/package /volume1/@appstore/synocli-file ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin /bin/rm -rf /var/packages/synocli-file
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End /bin/rm -rf /var/packages/synocli-file ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin /bin/mkdir -p /var/packages/synocli-file -m 755
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End /bin/mkdir -p /var/packages/synocli-file -m 755 ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin /bin/touch /var/packages/synocli-file/installing
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End /bin/touch /var/packages/synocli-file/installing ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin /bin/mv -f /volume1/@tmp/synopkg/install.bMOGev/INFO /var/packages/synocli-file/INFO
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End /bin/mv -f /volume1/@tmp/synopkg/install.bMOGev/INFO /var/packages/synocli-file/INFO ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin /bin/rm -rf /var/packages/synocli-file/scripts
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End /bin/rm -rf /var/packages/synocli-file/scripts ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin /bin/mv -f /volume1/@tmp/synopkg/install.bMOGev/scripts /var/packages/synocli-file/scripts
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End /bin/mv -f /volume1/@tmp/synopkg/install.bMOGev/scripts /var/packages/synocli-file/scripts ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin /bin/rm -rf /var/packages/synocli-file/WIZARD_UIFILES
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End /bin/rm -rf /var/packages/synocli-file/WIZARD_UIFILES ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin /bin/mv -f /volume1/@tmp/synopkg/install.bMOGev/WIZARD_UIFILES /var/packages/synocli-file/WIZARD_UIFILES
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End /bin/mv -f /volume1/@tmp/synopkg/install.bMOGev/WIZARD_UIFILES /var/packages/synocli-file/WIZARD_UIFILES ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin /bin/rm -rf /var/packages/synocli-file/conf
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End /bin/rm -rf /var/packages/synocli-file/conf ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin /bin/mv -f /volume1/@tmp/synopkg/install.bMOGev/conf /var/packages/synocli-file/conf
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 End /bin/mv -f /volume1/@tmp/synopkg/install.bMOGev/conf /var/packages/synocli-file/conf ret=[0]
2022/09/07 22:08:56	upgrade synocli-file 2.7-17 Begin postinst
2022/09/07 22:08:56	Begin reload_inst_variables
2022/09/07 22:08:56	End reload_inst_variables
2022/09/07 22:08:56	Begin initialize_variables
2022/09/07 22:08:56	End initialize_variables
2022/09/07 22:08:56	===> Step postinst. USER= GROUP= SHARE_PATH=
2022/09/07 22:08:56	Begin save_wizard_variables
2022/09/07 22:08:56	End save_wizard_variables
2022/09/07 22:08:56	Begin syno_sync_var_folder
2022/09/07 22:08:57	End syno_sync_var_folder
2022/09/07 22:08:57	Begin service_postinst
2022/09/07 22:08:57	End service_postinst
2022/09/07 22:08:57	upgrade synocli-file 2.7-17 End postinst ret=[0]
2022/09/07 22:08:57	upgrade synocli-file 2.7-17 Begin postupgrade
2022/09/07 22:08:57	Begin reload_inst_variables
2022/09/07 22:08:57	End reload_inst_variables
2022/09/07 22:08:57	Begin initialize_variables
2022/09/07 22:08:57	End initialize_variables
2022/09/07 22:08:57	===> Step postupgrade. USER= GROUP= SHARE_PATH=
2022/09/07 22:08:57	Begin syno_sync_var_folder
2022/09/07 22:08:57	End syno_sync_var_folder
2022/09/07 22:08:57	upgrade synocli-file 2.7-17 End postupgrade ret=[0]
2022/09/07 22:08:57	upgrade synocli-file 2.7-17 Begin start-stop-status start
2022/09/07 22:08:57	upgrade synocli-file 2.7-17 End start-stop-status start ret=[0]
2022/10/06 15:05:46	(system) trigger synocli-file 2.7-17 Begin start-stop-status stop
2022/10/06 15:05:46	(system) trigger synocli-file 2.7-17 End start-stop-status stop ret=[0]
2022/10/06 15:08:53	(system) trigger synocli-file 2.7-17 Begin start-stop-status start
2022/10/06 15:08:53	(system) trigger synocli-file 2.7-17 End start-stop-status start ret=[0]
```

### Service Log

_No response_

### Other Logs

_No response_

### PR DESCRIPTION
**Pull request by hgy59**
## Description

- add libblkid to support reflink in rmlint (option to Optimize non-rotational disks)
- add libelf to support to "Find non-stripped binaries" with rmlint

- since the build environment was update to debian bullseye (#5441) we need to update cross/file to the same version

Fixes #5459

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by hgy59** [comment]
currently build of synocli-file fails due to #5463

**Comment by t-rutter** [comment]
Hi @hgy59
I've tested building from your branch hgy59:update_rmlint and manually applied patch for #5463 by @th0ma7 .

The build completes and packages the .spk , when I test on my DS-1821 . rmlint --version shows the new version 2.10.1 .
But when trying to use the handlers 'clone' or 'relink' I'm still getting
```
WARNING: reflink will not be emitted: please compile with blkid and gio-unix-2.0.
```

**Comment by hgy59** [comment]
> WARNING: reflink will not be emitted: please compile with blkid and gio-unix-2.0.

can you please check whether `compiled with:` contains `+mounts` ?
The warning is only displayed when one of the options `HAVE_BLKID` and `HAVE_GIO_UNIX` is missing and mounts is only active when both are definded.

```
rmlint --version
version 2.10.1 compiled: Oct 21 2022 at [16:12:32] "Ludicrous Lemur" (rev 79c294ee)
compiled with: +mounts -nonstripped +fiemap +sha512 +bigfiles +intl -replay +xattr +btrfs-support

rmlint was written by Christopher <sahib> Pahl and Daniel <SeeSpotRun> Thomas.
The code at https://github.com/sahib/rmlint is licensed under the terms of the GPLv3.

```

```c++
    } features[] = {{.name = "mounts",         .enabled = HAVE_BLKID & HAVE_GIO_UNIX},
                    {.name = "nonstripped",    .enabled = HAVE_LIBELF},
                    {.name = "fiemap",         .enabled = HAVE_FIEMAP},
                    {.name = "sha512",         .enabled = HAVE_SHA512},
                    {.name = "bigfiles",       .enabled = HAVE_BIGFILES},
                    {.name = "intl",           .enabled = HAVE_LIBINTL},
                    {.name = "replay",         .enabled = HAVE_JSON_GLIB},
                    {.name = "xattr",          .enabled = HAVE_XATTR},
                    {.name = "btrfs-support",  .enabled = HAVE_BTRFS_H},
                    {.name = NULL,             .enabled = 0}};
    /* clang-format on */
```

So now only the `replay` feature is disabled, as we build without glib-json.


_BTW: to build a package for rmlint only you can build it in spksrc/diyspk/rmlint (diyspk = do it yourself spk). That is much faster and does not need the rust patch_

**Comment by t-rutter** [comment]
Thanks @hgy59 
I built diyspk/rmlint as suggested instead of the full spk/synocli-file .
And `rmlint -c sh:handler:clone` and handler:reflink are now working 🥳 

Hopefully your PR can be included into the next release of synocli-file

Also I made a patch for rmlint/lib/format/sh.c.in as upstream the original code actually has the checks for reflink warning commented out, Please feel free to use
```002-sh-reflink-handler-warning.patch
--- lib/formats/sh.c.in.orig    2020-06-13 19:12:45.000000000 +0930
+++ lib/formats/sh.c.in 2022-10-27 22:22:57.623108880 +1030
@@ -218,9 +218,9 @@
 };
 
 static void rm_sh_warn_if_reflink_not_compiled_in(void) {
-#if !HAVE_BLKID || !HAVE_GIO_UNIX
+  if(!HAVE_BLKID || !HAVE_GIO_UNIX) {
     g_printerr("\n%sWARNING:%s reflink will not be emitted: please compile with blkid and gio-unix-2.0.\n", YELLOW, RESET);
-#endif
+  }
 }
 
 static void rm_sh_parse_handlers(RmFmtHandlerShScript *self, const char *handler_cfg) {
```

**Comment by hgy59** [comment]
@t-rutter reading your patch i doubt that there is an error in the source code.
Please regard that `#if !HAVE_BLKID || !HAVE_GIO_UNIX` it not commented out, but `#if` and `#endif` are a c preprocessing directives.
The WARNING output is removed at compile time if the condition evaluates to 0.

**Comment by hgy59** [comment]
> I built diyspk/rmlint as suggested instead of the full spk/synocli-file .
> And `rmlint -c sh:handler:clone` and handler:reflink are now working 

@t-rutter 
Just found that in the context of synocli-file package, libblkid is missing.
This is caused by two packages compiling util-linux from source (cross/libuuid and cross/libblkid). After util-linux is compiled for libuuid the second build (for libblkid) is ignored, as the build folder is the same.
_I am working on it..._

**Pull request merged**
