### PR TITLE
Fix patch to match pillow-5.3.0 to allow build

### PR DESCRIPTION
**Pull request by chickenandpork**
_Motivation:_ Fix Pillow build
_Linked issues:_ #3617 

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

Build of all-supported ongoing; Upgrade and new install not applicable as this is the fix for a build that was probably released in #3529

-- boilerplate -- (sorry)

I've been granted permission by my employer to contribute to spksrc without risk of IP confusion. I am required to explicitly write that my contribution to this project is solely in my personal capacity, and I am not conveying any rights to any intellectual property of any third parties.

### CODE REVIEW

**Comment by chickenandpork** [comment]
If accepted, this PR can be merged with #3613 to reduce load on CI/CD resources

**Comment by chickenandpork** [comment]
Hey, neat... libsodium-1.0.15 is no longer available.  Awesomesauce.  Forced-bump that one.

bzip2 also isn't where it's expected; I know it's a bit clowny, but let's just get this built and argue whether the original install line needs to go.

This builds for `arch-88f6281-6.1` so I'll build `all-supported` overnight.

**Comment by ymartin59** [comment]
@chickenandpork Thanks. I am preparing Python 3 upgrade with your PRs.

**Comment by chickenandpork** [comment]
python build still ongoing; successfully built `python-2.7` for `88f6281`, `aarch64`, `alpine`, `armada370`, `armada375`, `armada38x`, armadaxp`, comcerto2k' over the last 13 hrs

**Comment by chickenandpork** [comment]
`all-supported` completed after nearly 24 hours.  I really need to speed up that build time for recurring builds!

This patch seems OK, and can be applied independently to get us back to the ability to build that we lost.

**go go go**   :)

**Comment by ymartin59** [comment]
@chickenandpork May you please confirm this PR is incompatible with #3529?

**Comment by chickenandpork** [comment]
@ymartin59 should be compatible with #3529; This was built on top of recent `SynoCommunity/spksrc/master` into which #3529 was already merged.  I think #3529 bumped the version of `cross/pillow` 4.0.0 => 5.3.0 without updating the patch.  I assume it wasn't caught at the time because #3529 focused on `python3` and might not have built `python` to test (`python3` doesn't use `cross/pillow`).  I think therefore that this fixes an error in #3529 so it's not only compatible, but urgent. 

I found the error because i use a quick tool to check what dependencies are affected by a change to  a component.

#3620: **Compatible; Unrelated; helps**Unrelated to #3620 but #3620 should help it build a bit faster; #3620 should be compatible and can be merged with, before, or after.

I know you merge a bunch of things at once, so most other PRs are:

#3613: **Compatible; Dependency; helps**: Helps #3613 to build: #3613 will build `python3` but reveals the issue in `python`; this patch will help #3613 build, but build was broken before #3613, perhaps at the point `libsodium-1.0.15` was withdrawn.  #3613 is therefore dependent on this patch but only as a victim of the broken patch.  #3613 can merge with or after this patch, but before, will fail `python` builds now.

#3562: **Compatible, unrelated; helps**: Unrelated with #3562 ; #3562 will build with or without, but should be compatible

**Comment by ymartin59** [comment]
@chickenandpork Thanks for details.

**Pull request merged**
