### PR TITLE
cloudflared: update to 2024.8.2

### LINKED ISSUE #6184: [Package Feature Request]  Cloudflare Tunnel option
### Software Name

Cloudflare Tunnel

### Brief Description

Cloudflared connects to IPv4 edge by default. There's an option _--edge-ip-version auto_ that will pick IPv4 or IPv6 depending on available networks on the running machine.

Is it possible to have this option by default when running the Cloudflare Tunnel package https://synocommunity.com/package/cloudflared?

More information: https://github.com/cloudflare/cloudflared/issues/842#issuecomment-1358156950

### Website

https://www.cloudflare.com

### Documentation

https://github.com/cloudflare/cloudflared/issues/842#issuecomment-1358156950

### Build/Installation documentation

N/A

### Source code

N/A

### OpenSource License

MIT

### Other License

_No response_

### PR DESCRIPTION
**Pull request by karasevm**
## Description

1. Update to 2024.8.2
2. Switch from passing the token to using a config file
3. Add advanced options to the installation wizard (Resolves #6184)
<details>
<summary>New options screenshot</summary>

</details>

2024.8.2
- 2024-08-05 TUN-8583: change final directory of artifacts
- 2024-08-05 TUN-8585: Avoid creating GH client when dry-run is true

2024.7.3
- 2024-07-31 TUN-8546: Fix final artifacts paths

2024.7.2
- 2024-07-17 TUN-8546: rework MacOS build script

2024.7.1
- 2024-07-16 TUN-8543: use -p flag to create intermediate directories

2024.7.0
- 2024-07-05 TUN-8520: add macos arm64 build
- 2024-07-05 TUN-8523: refactor makefile and cfsetup
- 2024-07-02 TUN-8504: Use pre-installed python version instead of downloading it on Windows builds
- 2024-06-26 TUN-8489: Add default noop logger for capnprpc
- 2024-06-25 TUN-8487: Add user-agent for quick-tunnel requests
- 2023-12-12 TUN-8057: cloudflared uses new PQ curve ID

2024.6.1
- 2024-06-12 TUN-8461: Don't log Failed to send session payload if the error is EOF
- 2024-06-07 TUN-8456: Update quic-go to 0.45 and collect mtu and congestion control metrics
- 2024-06-06 TUN-8452: Add flag to control QUIC stream-level flow control limit
- 2024-06-06 TUN-8451: Log QUIC flow control frames and transport parameters received
- 2024-06-05 TUN-8449: Add flag to control QUIC connection-level flow control limit and increase default to 30MB

Upstream changelog: https://github.com/cloudflare/cloudflared/blob/master/RELEASE_NOTES

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
NB: don't forget to update the [wiki page](https://github.com/SynoCommunity/spksrc/wiki/cloudflared)

**Comment by karasevm** [comment]
@hgy59 Done

**Comment by freitasm** [comment]
Hi folks. When will this be available through DSM for update/install?

**Comment by IngmarStein** [comment]
Is anything blocking this PR or is it ready to go?

**Review by th0ma7 — APPROVED** [review]
LGTM

**Comment by th0ma7** [comment]
@karasevm I assume you may not have publishing authorizations?  If so, want me to publish this?

**Comment by karasevm** [comment]
@th0ma7 Yes, please, go ahead

**Comment by th0ma7** [comment]
now published, and thnx for your contribution @karasevm!
https://synocommunity.com/package/cloudflared

**Pull request merged**
