### PR TITLE
Radarr: Update to v5.12.2.9335

### LINKED ISSUE #6309: Radarr: update is failing (version `GLIBC_2.27' not found)
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

Radarr

### Package Version

5.14.0.9383

### Device Model

Synology DS414

### Device Architecture

ARMv7

### Firmware Version

7.1.1-42962 Update 5

### What happened?

Launching the update from within Radarr is failing

### Reproduction steps

1. Launch update from within Radarr

### Install Log

```log
2024-11-07 09:40:50.6|Info|InstallUpdateService|Downloading update 5.14.0.9383
2024-11-07 09:41:02.7|Info|InstallUpdateService|Verifying update package
2024-11-07 09:41:04.3|Info|InstallUpdateService|Update package verified successfully
2024-11-07 09:41:04.3|Info|InstallUpdateService|Extracting Update package
2024-11-07 09:41:37.5|Info|InstallUpdateService|Update package extracted successfully
2024-11-07 09:41:37.6|Info|BackupService|Starting Backup
2024-11-07 09:41:43.1|Info|InstallUpdateService|Preparing client
2024-11-07 09:41:48.4|Info|InstallUpdateService|Starting update client /volume1/@apptemp/radarr/radarr_update/Radarr.Update
2024-11-07 09:41:48.4|Info|InstallUpdateService|Radarr will restart shortly.
2024-11-07 09:41:48.9|Error|Radarr.Update|Failed to load /volume1/@apptemp/radarr/radarr_update/libcoreclr.so, error: /lib/libm.so.6: version `GLIBC_2.27' not found (required by /volume1/@apptemp/radarr/radarr_update/libcoreclr.so)
```

### Service Log

_No response_

### Other Logs

_No response_

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This PR includes the following changes:

1. Update Radarr to v5.12.2.9335 (.NET 6.0.32 compatible with ARMv7)
2. Include build for Alpine4k (#6103)

Fixes # 

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by mreid-tt** [comment]
hey @hgy59, I've tried the build but it fails to run under DSM 6 from a clean install. I get in the service log:
```
Fri Nov  8 09:18:31 -04 2024
Starting radarr command env HOME=/volume1/@appstore/radarr/var LD_LIBRARY_PATH=/volume1/@appstore/radarr/lib /volume1/@appstore/radarr/share/Radarr/bin/Radarr -nobrowser -data=/volume1/@appstore/radarr/var/.config/Radarr
/volume1/@appstore/radarr/share/Radarr/bin/Radarr: relocation error: /volume1/@appstore/radarr/lib/libpthread.so.0: symbol __tunable_get_val, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
radarr is not running
```

**Comment by mreid-tt** [comment]
@hgy59, I'll update the changelog but the solution you proposed by adding `cross/glibc` to all archs is causing the package to break. Any thoughts on this?

**Comment by hgy59** [comment]
> @hgy59, I'll update the changelog but the solution you proposed by adding `cross/glibc` to all archs is causing the package to break. Any thoughts on this?

does it work on DSM 6 without cross/glibc?

**Comment by mreid-tt** [comment]
> does it work on DSM 6 without cross/glibc?

Yes it did previously. The log I supplied for an upgrade of the published package using the built in updater to the same version was successful. I can build a clean install to test but I don't expect the results will be different.

I came across these but it's a bit beyond my expertise:
* https://stackoverflow.com/questions/49245547/version-glibc-private-not-defined-in-file-ld-linux-x86-64-so-2
* https://unix.stackexchange.com/questions/367597/almost-no-commands-working-relocation-error-symbol-getrlimit-version-glibc

**Comment by hgy59** [comment]
If Radarr v5.14.0.9383 runs on DSM 6 without cross/glibc we should add glibc for DSM >= 7 only.

But I doubt that it will run on DSM 7.1.
unfortunately cross/glibc has an autogenerated PLIST file, so it is not obvious which libraries come from it.
If it contains libc.so.6 it might be an issue that some dependencies use this from the package library path an other from the system library path.

If /var/packages/radarr/target/lib has any libc.* file (links and content) you might try to delete those to fix it.

**Comment by hgy59** [comment]
I guess my last proposal does not work and the radarr package has to be restricted to DSM 7.2.

Unfortunately we do not have any chance to limit packages that use the package internal updater to limit updates to a specific version (the last version before it breaks).

**Comment by hgy59** [comment]
@mreid-tt and we do not have any package the needs cross/glibc* so far...

So I guess it is not possible to bring your own version of glibc with a package.

**Pull request merged**
