### PR TITLE
ffsync: update to 1.8.0

### PR DESCRIPTION
**Pull request by ymartin59**
_Motivation:_  Update, DMS 6 support, fix uninstall mysql password issue
_Linked issues:_  #3124

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
@hgy59 I am fighting to get it build but there is little hope, even my Debian testing is in trouble to build.
At least I have created a useful target to spare time when designing requirements file, you may be interested in: https://github.com/SynoCommunity/spksrc/pull/3849/commits/74f57a7c4bd2389450c8199b5362acb8b3f1369f

**Comment by ymartin59** [comment]
@hgy59 According to info I found in ffsync forum, there was no plan to update ffsync to Python 3.... My idea was to keep it stuck to latest Python 2 package...

**Comment by hgy59** [comment]
> 
> 
> @hgy59 According to info I found in ffsync forum, there was no plan to update ffsync to Python 3.... My idea was to keep it stuck to latest Python 2 package...

But where comes the `venusian==3.0.0` dependency from in requirements.txt? This package requires Python3. 
This found, I thought ffsynch must be compatible with python3.

**Comment by hgy59** [comment]
@ymartin59 I am reverting to py2 now...

**Comment by hgy59** [comment]
@ymartin59 for any reason the cross build of python wheels is broken for python 2 now.
cryptography cannot be built when listed in requirements.txt due to libffi.so.7 not found.
When I add cross/cryptograpy as package dependency it builds without error, but the wheel is not copied to the share/wheelhouse ....
maybe this is related to #3956 but I have no idea how to fix it.

**Comment by th0ma7** [comment]
I gave it a shot and went a long way ahead in getting it to install all python dependencies until I figure that syncsever is python2 only and is expected to be replaced by a rust version (pending for a release since quite a while now).

Should we just remove `ffsync` entirely?

**Comment by hgy59** [comment]
> Should we just remove `ffsync` entirely?

Despite this is the last python2 package we support, I would like to keep this, until the rust version will be available in the (far ?) future.

ffsync is a cool solution and without this spk, you need a Diskstation model that supports docker to use it.

The only task that is still open is the database integration.

**Comment by hgy59** [comment]
> @hgy59 I am fighting to get it build but there is little hope, even my Debian testing is in trouble to build. At least I have created a useful target to spare time when designing requirements file, you may be interested in: [74f57a7](https://github.com/SynoCommunity/spksrc/commit/74f57a7c4bd2389450c8199b5362acb8b3f1369f)

@th0ma7 is the `clean-wheel` target something that we should regard in your wheel creation redesign - or is this contained in the `spkclean` target anyway?

**Comment by th0ma7** [comment]
I'll give it another shot at ensuring it build OK using the new framework using python2 then.  Will leave the database integration for someone else though.  Note that it seems the rust version is now available https://github.com/mozilla-services/syncstorage-rs

Yeah, the `clean-wheel` is rather interesting and "almost" covered into `spkclean`.  I'll try to extract it from here and implement it into another PR (and/or adjust `spkclean`).

**Comment by mreid-tt** [comment]
@ymartin59, the original Firefox Sync Server, as outlined in its [source repository](https://github.com/mozilla-services/syncserver), is no longer under active maintenance. It has undergone redevelopment in Rust and is now hosted in a new repository named [Syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs). The imminent release, linked to the Pull Request [5942](https://github.com/SynoCommunity/spksrc/pull/5942) within the SynoCommunity/spksrc repository, is slated to replace all preceding versions of the package due to their deprecated functionality.

Could we kindly request the closure of this Pull Request upon the release of ours?

**Pull request closed without merging**
