### PR TITLE
Docker image: add zlib1g-dev:i386 required by some toolchains

### PR DESCRIPTION
**Pull request by ymartin59**
_Motivation:_ there is no reason not to provide it by default for powerpc toolchains to work

### CODE REVIEW

**Comment by Dr-Bean** [comment]
This particular addition is _only_ needed for Evansport-4.x afaik.
DSM4.3 and older toolchains are getting more and more legacy, to a level that adding this entry as a default is simply overkill. People who need this dep can install it themselves.

See also https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#which-dsm-versions-do-you-support.

**Comment by Dr-Bean** [comment]
...not just Evansport, my bad :) But legacy arches nonetheless...;)

**Comment by ymartin59** [comment]
Comparing time I wasted to understand why some archs failed to any impact of adding theses 3 or 4 small packages (as far as I remember) to get it work "by default"... I find such patch relevant enough to create that PR.

**Comment by ymartin59** [comment]
To add facts, these architectures requires `zlib1g-dev:i386`
evansport-5.1
evansport-5.0
comcerto2k-5.1
comcerto2k-5.0

Here is the exact list of added packages (not sure but small, max 1 MiB of packages...)
* gcc-4.9-base:i386 4.9.2-10
* libgcc1:i386 1:4.9.2-10
* libc6:i386 2.19-18+deb8u7
* libc-bin:amd64 2.19-18+deb8u7
* zlib1g:i386 1:1.2.8.dfsg-2+b1
* libc6-i686:i386 2.19-18+deb8u7
* linux-libc-dev:i386 3.16.39-1
* libc6-dev:i386 2.19-18+deb8u7
* zlib1g-dev:i386 1:1.2.8.dfsg-2+b1
* libc-bin:amd64 2.19-18+deb8u7

**Pull request closed without merging**
