### PR TITLE
Move back qoriq rust to native folder

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

Move bac qoriq rust to native folder

Relates to #6133 

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [ ] Package update
- [x] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
@th0ma7 are you sure you want to do this?

IMHO it is not worth any effort since we have a working solution.

**Comment by th0ma7** [comment]
> IMHO it is not worth any effort since we have a working solution.

@hgy59 I thought it's what you had in mind from previous exchanges (may have misunderstood).  Now that qoriq toolchain isn't being cached anymore, rust-qoriq will end-up being re-installed, always.  Thus, in theory, it makes no difference for it to be in `toolchain` or `native`.

But I'm totally fine by any option, feel free at parking this one down for a bit, or just close & discard it (or merge, whatever you're ok with)?  At least we'll have kept a trace in case we need to reconvene.  And again, thnx for the fix :+1:

**Comment by hgy59** [comment]
> @hgy59 I thought it's what you had in mind from previous exchanges (may have misunderstood). Now that qoriq toolchain isn't being cached anymore, rust-qoriq will end-up being re-installed, always. Thus, in theory, it makes no difference for it to be in `toolchain` or `native`.

When I saw that all other rust installation is done in the other toolchains, I found that rust installation is bound to the toolchains. And we must force the installation of rust by deletion of .rustc_done in build.sh
```sh
# Remove rust toolchain status file to enfore re-installing cargo/rust
# This fixes isees on github-action where toolchain caching omits the
# actual installation state of cargo/rust within the distrib folder
rm -f toolchain/syno-${GH_ARCH}/work/.rustc_done
```

And I guess it will never be possible to cache the rust installation.

**Comment by th0ma7** [comment]
> When I saw that all other rust installation is done in the other toolchains, I found that rust installation is bound to the toolchains. And we must force the installation of rust by deletion of .rustc_done in build.sh
> 
> ```shell
> # Remove rust toolchain status file to enfore re-installing cargo/rust
> # This fixes isees on github-action where toolchain caching omits the
> # actual installation state of cargo/rust within the distrib folder
> rm -f toolchain/syno-${GH_ARCH}/work/.rustc_done
> ```

I hadn't noticed that change in your PR #6133 ... [searching...]  Found!  Oh, that came from here #5582.  I didn't remembered that at all.
 
> And I guess it will never be possible to cache the rust installation.

Actually, besides qoriq, if we whish we probably could cache `distrib/cargo|rustup` which would (from what I recollect, to be tested), make the rustup reinstall to say that we're already good and using the correct version, no need to reinstall neither the host tools or the toolchains.

Quick testing output:
```
===>  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
info: downloading installer
warning: it looks like you have an existing installation of Rust at:
warning: /home/spksrc/kernel-fix/spksrc/distrib/cargo/bin
warning: It is recommended that rustup be the primary Rust installation.
warning: Otherwise you may have confusion unless you are careful with your PATH
warning: If you are sure that you want both rustup and your already installed Rust
warning: then please reply `y' or `yes' or set RUSTUP_INIT_SKIP_PATH_CHECK to yes
warning: or pass `-y' to ignore all ignorable checks.
error: cannot install while Rust is installed
warning: continuing (because the -y flag is set and the error is ignorable)
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.78.0 (9b00956e5 2024-04-29)


Rust is installed now. Great!
```

**Comment by hgy59** [comment]
outdated

**Pull request closed without merging**
