### PR TITLE
synocli-file: add detox and rmlint

### PR DESCRIPTION
**Pull request by ymartin59**
Update Docker image to Debian buster for scons

_Motivation:_  Get synocli-file ready to publish
_Linked issues:_  #3482 #3250

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
@hgy59 nano fails to find ncursew6-config in `install`, looks like pkg-config files are not generated properly
Was probably working before because Debian host version was the same as cross-compiled version... now I have updated to Debian duster and identify "ncurses" is not properly detected as compiled in `install`.

**Comment by hgy59** [comment]
> 
> 
> @hgy59 nano fails to find ncursew6-config in `install`, looks like pkg-config files are not generated properly
> Was probably working before because Debian host version was the same as cross-compiled version... now I have updated to Debian buster and identify "ncurses" is not properly detected as compiled in `install`.

I can reproduce this, nano build does find neither ncurses nor ncursesw when built with a spksrc-docker-image based on debian:10-slim.

Tried with libncurses-dev installed and both (libncurses-dev  and ncurses-dev) installed with no success.

**Comment by hgy59** [comment]
It's a reported bug in ncurses
[Debian Bug report logs - #933053](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933053)
Therefore the build of synocli-file will fail on debian 10. Please use an build environment with debian 9 until this is fixed.

**Comment by hgy59** [comment]
While testing with builds on debian 10 host, the version of 'file' haunted me, so I will push another fix with native version for file.
Does nano build with your changes here?

**Comment by ymartin59** [comment]
I have fixed ncurses and nano compilation and increase `file` version too.

**Comment by hgy59** [comment]
Looks good to me

**Comment by ymartin59** [comment]
@hgy59 OK "Approval" would have been far enough - to notice I have not checked "all-supported" compilation yet...

**Pull request merged**
