### PR TITLE
php-7.3: Provide up to date PHP version

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

Current provided 7.3 version of PHP from Synology is 7.3.3 while some script require updated version:
```
Error: You are using an unsupported PHP version (PHP 7.3.3).
MediaWiki 1.35 needs PHP 7.3.16 or higher (and not 7.4.0 - 7.4.2).

Check if you might have a newer PHP executable with a different name.
```
This package is in hope to solve this issue.

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [x] New Package
- [ ] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
@hgy59 I wonder what you think of this.  Either providing a SynoCommunity PHP package OR keeping it under the DIY area?  While at it I could probably create a 8.x package using latest 8.2.6... It also need not to conflict with official Synology packages.

**Comment by hgy59** [comment]
as mediawiki is a package provided by synology it is theire responsibility to update the dependencies.

But
Either on DSM 6 and on DSM 7 the mediawiki package of synology depends on PHP 7.4
I have not a clue where the error `MediaWiki 1.35 needs PHP 7.3.16 or higher (and not 7.4.0 - 7.4.2).` comes from.

**Comment by th0ma7** [comment]
> as mediawiki is a package provided by synology it is theire responsibility to update the dependencies.
> 
> But Either on DSM 6 and on DSM 7 the mediawiki package of synology depends on PHP 7.4 I have not a clue where the error `MediaWiki 1.35 needs PHP 7.3.16 or higher (and not 7.4.0 - 7.4.2).` comes from.

This comes from me trying to update my own password on my mediawiki:
```
php ./maintenance/changePassword.php --user=<user> --password=<passwd>
```
It hapens that default php is of version 7.3.3 but package is up to date... which in turn solved my issue:
```
var/packages/PHP7.3/target/usr/local/bin/php73 --version
PHP 7.3.33 (cli) (built: Mar 16 2022 11:34:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.33, Copyright (c) 1998-2018 Zend Technologies
```
Making me dubious that providing our own package as much value...

**Comment by hgy59** [comment]
> Making me dubious that providing our own package as much value...

A SynoCommunity package for php will not be used by mediawiki. It can solve the issue for manually executed php scripts but not for the package itself (that works with php 7.4)
Still an issue that should be reported to Synology or mediawiki project (as ./maintenance/changePassword.php does not run with php 7.4).

If the ./maintenance/changePassword.php runs with php 7.4.30 (the current php 7.4 of synology) this issue could be solved by uninstall of the php 7.3 package (or making php 7.4 the default php). This is then no issue at all, except that the default php is 7.3 and not 7.4.

**Comment by hgy59** [comment]
@th0ma7 synology released yesterday DSM 7.2 and the PHP 7.3 package in DSM 7.2 has PHP Version 7.3.33.

**Comment by th0ma7** [comment]
Closing as not needed, thnx for your feedbacks and finding @hgy59

**Pull request closed without merging**
