### PR TITLE
minio: update and allow custom environment variables

### LINKED ISSUE #5107: Support for environment-only settings for minio
The minio package as built from here works quite well for most use-cases, but I've come to the point where I need it to support vhost-style buckets. This can be done in minio by [exporting the right environment variable when starting it](https://docs.min.io/docs/minio-server-configuration-guide.html);
```console
export MINIO_DOMAIN=mydomain.com
minio server /data
```

The package has no way - that I can find - to add such an export though, at least not in any way that won't be overwritten on the next upgrade.

### PR DESCRIPTION
**Pull request by hgy59**
## Description

- update minio to 2022-02-01T18-00-14Z
- introduce var/environment-variables file for custom server configuration

Fixes #5107

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
please @fgma can you have a look at this?

**Comment by hgy59** [comment]
I have tested this with the example
```bash
export MINIO_DOMAIN=mydomain.com
```

and the downloaded diagnostic.json contains:
```json
    "info": {
      "mode": "online",
      "domain": [
        "mydomain.com"
      ],

```

**Review by ymartin59 — APPROVED** [review]

**Comment by fgma** [comment]
Sorry, I did not have the time to test it yet. Just had a look at the changes which look ok to me.

**Comment by hgy59** [comment]
@ananace is this all you are asking for in #5122?

**Comment by ananace** [comment]
Certainly seems that way, yep. Thanks for looking at it.

**Pull request merged**
