### PR TITLE
Created a package to install sickbeard-mp4-automator from mdhiggins. …

### PR DESCRIPTION
**Pull request by phtagn**
…Currently the package refers to a fork of sickbeard-mp4automator that contains a workaround for a bug on the verification of SSL certificates that generates an error when Sickbeard is set up with SSL. If mdhiggins accepts the workaround or fixes it, I'll modify the git address to refer directly to his project. I've tested it on my NAS, and it works fine. I am willing to get more testers though.

### CODE REVIEW

**Comment by Safihre** [comment]
@dlorch Is this still relevant and are you still interested in getting this package into SynoCommunity?

Please let us know, otherwise we will close this PR at some point to get a better overview of active work-in-progress.

**Comment by dlorch** [comment]
@Safihre not my PR :-)

**Comment by Safihre** [comment]
Oops! @phtagn I meant :p

**Comment by hgy59** [comment]
closed due to inactivity

**Pull request closed without merging**
