### PR TITLE
version bump pngquant to v2.18.0

### PR DESCRIPTION
**Pull request by zyrill**
## Description

Updated pngquant from v2.17.0 to v2.18.0

TODO: switch to most up to date version based in rust, see https://lib.rs/crates/pngquant

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
dependency to tvheadend package

**Comment by zyrill** [comment]
> dependency to tvheadend package



> dependency to tvheadend package

tvheadend is quite a heavyweight, isn't it? I started working on it and a) a lot of deps are outdated and b) some builds (like intel-vaapi-driver) seem to be broken. I'll continue working on it and see how far I get. Should I add the commit with all the work on tvheadend here?

**Comment by hgy59** [comment]
> I started working on tvheadend and the intel-vaapi-driver dependency seems to be broken:

@zyrill thanks for this logs. It is an issue, that gcc in the DSM 7.2 toolchain fails, but DSM 7.1 toolchain succeeds.
You can just build for DSM 7.1 (and it will run on DSM 7.2 too).

In https://github.com/SynoCommunity/spksrc/pull/6101#issuecomment-2137605435 I mentioned that I couldn't remember a packate that fails to build for DSM 7.2. You helped my aged memory 😆

**Comment by hgy59** [comment]
@zyrill pngquant is not updated to v2.18.0 with #6143

If you want to update the tvheadend package, I propose to cooperate with the maintainer @th0ma7.

**Comment by th0ma7** [comment]
@zyrill tvheadend on its own isn't too bad to update but I normally do that in conjunction with ffmpeg, which is a large beast.  @hgy59 I wanted to clear-up kernel, python (and now rust) before returning to package updates but this one has been lagging since quite a while so I'll switch on that for the next little while.

**Comment by hgy59** [comment]
> TODO: switch to most up to date version based in rust, see https://lib.rs/crates/pngquant

I have a working solution for pngquant 3.0.3 but it is very tricky
- pngquant 3 needs rust build
- the issue building pngquant 3.0.3 was lacking imagequant-sys source (linked submodule not contained in pngquant archive)
- fixed the submodule issue with a cross/libimagequant-source package that gets linked into the submodule folder when building pngquant
- pngquant 3 fails to build when cross/zlib is built before (linking error). This can be fixed by depending on cross/zlib-ng, but works only, when cross/zlib is not already build by any other dependency like cross/libpng
  - this leads to ugly dependency order
  - this is not a problem with prebuilt ffmpeg (since we avoid to reuse zlib)
  - we already had a zlib issue with cross/bat, but this is gone with an update (#6052)

I could provide a separate PR for this...

**Comment by hgy59** [comment]
> I could provide a separate PR for this...

done with #6147

**Comment by hgy59** [comment]
> @zyrill tvheadend on its own isn't too bad to update but I normally do that in conjunction with ffmpeg, which is a large beast. @hgy59 I wanted to clear-up kernel, python (and now rust) before returning to package updates but this one has been lagging since quite a while so I'll switch on that for the next little while.

As mentioned [here](https://tvheadend.org/p/downloads) tvheadend 4.4 is expected to be avalable soon (was planned for Q1 2024).

> The latest 'stable' release (v4.2.8) was released in January 2019 and is now showing its age. As there are no plans for another v4.2 maintenance release and there is no direct upgrade path from v4.2 to v4.3/v4.4 we recommend all new installs use the current v4.3 'development' releases. These have been in a reliable state for several years and will soon become the new v4.4 stable release (eta in Q1/2024).)

**Comment by zyrill** [comment]
I'll defer to @th0ma7 's expertise... Thanks for all the support!

**Pull request closed without merging**
