### PR TITLE
tvheadend: fix ppc patch compilation

### PR DESCRIPTION
**Pull request by ymartin59**
Fix created to compile and publish for ppc/qoriq

### CODE REVIEW

**Comment by ymartin59** [comment]
@th0ma7 For information, when publishing tvheadend, I had to create this fix on ppc patch

**Comment by th0ma7** [comment]
@ymartin59 I'm surprised I haven't noticed this...
I recall seying a post from someone else in the group proposing that `make all--supported` exit on error... that would have caught my attention.
Good catch btw.

Also really important to note, any new release of TVH needs to be compiled against the new set of patches for ffmpeg.  Otherwise they will block in a few areas when using ffmpeg due to previous port of synology patches.

**Comment by hgy59** [comment]
@ymartin59 may be we move ppc853x to unsupported archs?
Failed to compile tvheadend:
```
...
Building src/webui/static/intl/tvh.zh-Hans.js.gz
WEBUI std finished
make[5]: Leaving directory '/spksrc/spk/tvheadend/work-ppc853x-5.2/tvheadend-git221c29b40b1e53ae09a69d9458442dd4fea665f5'
make -f Makefile.webui WEBUI=debug compile-debug
make[5]: Entering directory '/spksrc/spk/tvheadend/work-ppc853x-5.2/tvheadend-git221c29b40b1e53ae09a69d9458442dd4fea665f5'
WEBUI debug finished
make[5]: Leaving directory '/spksrc/spk/tvheadend/work-ppc853x-5.2/tvheadend-git221c29b40b1e53ae09a69d9458442dd4fea665f5'
make[4]: Leaving directory '/spksrc/spk/tvheadend/work-ppc853x-5.2/tvheadend-git221c29b40b1e53ae09a69d9458442dd4fea665f5'
CC              src/version.o
cc1: error: unrecognized command line option "-Wno-stringop-truncation"
cc1: error: unrecognized command line option "-Wno-stringop-overflow"
make[3]: *** [Makefile:717: /spksrc/spk/tvheadend/work-ppc853x-5.2/tvheadend
```

**Comment by ymartin59** [comment]
@hgy59 In fact ppc853x is already considered as "unsupported" as I no longer build packages for this arch. So it makes sense to remove it from the supported list in Makefiles.

**Pull request merged**
