### PR TITLE
Monit updated to 5.17.1

### PR DESCRIPTION
**Pull request by schumi2004**

### CODE REVIEW

**Comment by schumi2004** [comment]
When merged issue https://github.com/SynoCommunity/spksrc/issues/2163 can be closed.

**Comment by cytec** [comment]
lgtm \cc @Dr-Bean

**Comment by Dr-Bean** [comment]
LGTM2 ;) @schumi2004: Just to confirm, no issues with running the package on your NAS?

**Comment by schumi2004** [comment]
@Dr-Bean runs just fine
http://imgur.com/yCzJAmD

**Comment by cytec** [comment]
monit has been updated on the repo!

**Comment by schumi2004** [comment]
That's for later ;)
Thanks for helping out.

**Pull request merged**
