### PR TITLE
Update sonarr 3.0.5 => 3.0.9

### PR DESCRIPTION
**Pull request by smaarn**
## Description

Just to keep up to date with latest version released of Sonarr.

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [x] ~~Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created~~

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by Safihre** [comment]
But why? The internal updater will just update it after the install?

**Comment by smaarn** [comment]
Closing as redundant with internal updater and not adding any value besides.

**Comment by bakerboy448** [comment]
> But why? The internal updater will just update it after the install?

Incorrect.

This PR is needed just like the other starr apps.

users who reinstall are required to manually purge appdata via ssh.  Why does the SynoCommunity require this manual work around in lieu of updating the base app images?

why is there suddenly an urge to no longer update the Starr apps to latest stables when historically that has never been the case?

**Comment by bakerboy448** [comment]
Correction to the above. Due to this bug
https://github.com/SynoCommunity/spksrc/issues/5450

any users that reinstall sonarr MUST manually purge their appdata via ssh as uninstalling and purging will not.

additionally, if users don't enable auto update - and I don't believe the synology package does either - then sonarr would not autoupdate on install as claimed. It also does not appear update_required is set by the Syno sonarr package.  Thus Sonarr will absolutely never update on startup as claimed either.

**Comment by smaarn** [comment]
@bakerboy448 if I'm reading you right this means I should be reopening this PR, did I get it right ?

**Comment by bakerboy448** [comment]
correct @smaarn  :)

thanks for finally doing what SynoComm has not done since 3/27/2021

**Comment by Safihre** [comment]
You seem to have quite some frustration with SynoCommunity.. We are just some people trying to do our best in our free time to work through the challenges posed by the Synology platform, all the different cpu architectures and cross compiling problems. There are a large number of packages that we attempt to support, but we can only do so much.. (I say "we", but I'm only a very small contributor). 

To your points:
There is no sudden urge to not update the Arr apps, historically we generally only updated the base versions when we updated something in the SynoCommunity framework or the scripts to start/stop the app. Otherwise we left them to auto update and that worked well for quite a few years.  
Releasing a new package every time there's a new version would take too much time and also disk space on our server. 
It seems DSM 7 introduced some new problems, like the AppData problem.
So let's try to fix that indeed. 
If additionally we need to configure auto update better, let's also do that. I am pretty sure that when I maintained the Sonarr package here a few years ago, auto update was enabled by default. If that changed, we should update accordingly.

So, let's fix the core problems.

**Comment by bakerboy448** [comment]
> You seem to have quite some frustration with SynoCommunity.

because apps are continually not updated causing users headaches even though issues have been reported for years and then PRs that reduce user headaches are closed or ignored even though other apps have been updated in the same manner.  And the uninstall methods leave data behind requiring manual complex repairs for users, most synology users have no idea what terminal is nor how to use it.

The \*Arrs for years have never had auto update enabled by default.

We'll see how long it takes for the apps to be updated and if your words actually match your actions. So far continually PRs to update the apps have been closed or otherwise ignored.

**Comment by mreid-tt** [comment]
hey @bakerboy448, looking at the comment on Sonarr not auto-updating after the package is installed, is there a separate issue or pull request for this? if not would you mind creating one as you seem to have a good understanding of the problem.

**Pull request closed without merging**
