### PR TITLE
aria2: update to v1.37.0

### PR DESCRIPTION
**Pull request by hgy59**
## Description

This is a new package, it was never published before.
- update aria2 package and remove beta flag
- avoid shortcut in DSM UI
- hard code invariant settings in aria2.conf
- adjust port range since port 6881 is used by Synology "BiTorrent"
- configure enable-color=false to suppress color codes in certain log entries
- avoid packaging of place holder files and create required files on installation
- update installation wizard
  - remove obsolete text "Aria2 Settings"
  - use password field for rpc-secret and remove default value
  - fix regex for rpc-secret (allow special characters)
  - use combobox for file-allocation and log-level
- add all used ports to firewall ports
- drop dependency of gnutls to fix runtime crash on aarch64

Fixes # 

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] New Package
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
@cnrat I know, it is a long time ago, since you provided the aria2 package in #3275.
In your PR we finally added the aria2c command to the `synocli-net` package - where it is still available for manual execution.

I now updated your former code to have an aria2 package that provides installation as a service.
And I just finished the ariang package provided by @vitkabele to have a web UI for aria2 too.

In ariang I was able to connect to the aria2 service, but only with the `WebSocket` protocol. 
The connection with http protocol was not possible, neither with GET nor POST Methods.
This will be worth a note on a page in our wiki.

**Comment by hgy59** [comment]
There is an issue when running on aarch64 with DSM 6.2.4:

aria2  terminates without logging any error when starting a download.
The latests logs with activated debug level are:
```
2024-04-07 18:38:39.142387 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x50f4420]: CERTIFICATE (11) was received. Length 3687[3687], frag offset 0, frag length: 3687, sequence: 0
2024-04-07 18:38:39.142415 [DEBUG] [Platform.cc:88] GnuTLS: <3> ASSERT: buffers.c[get_last_packet]:1177
2024-04-07 18:38:39.142442 [DEBUG] [Platform.cc:88] GnuTLS: <3> ASSERT: buffers.c[_gnutls_handshake_io_recv_int]:1428
2024-04-07 18:38:39.142470 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x50f4420]: parsing certificate message
2024-04-07 18:38:39.142508 [DEBUG] [Platform.cc:88] GnuTLS: <4> Found OCSP response on cert 0
2024-04-07 18:38:39.142541 [DEBUG] [Platform.cc:88] GnuTLS: <3> ASSERT: buffers.c[get_last_packet]:1186
2024-04-07 18:38:39.142572 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x50f4420]: SSL 3.3 Application Data packet received. Epoch 1, length: 281
2024-04-07 18:38:39.142597 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x50f4420]: Expected Packet Handshake(22)
2024-04-07 18:38:39.142620 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x50f4420]: Received Packet Application Data(23) with length: 281
2024-04-07 18:38:39.142668 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x50f4420]: Decrypted Packet[2] Handshake(22) with length: 264
2024-04-07 18:38:39.142699 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x50f4420]: CERTIFICATE VERIFY (15) was received. Length 260[260], frag offset 0, frag length: 260, sequence: 0
2024-04-07 18:38:39.142728 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x50f4420]: Parsing certificate verify
2024-04-07 18:38:39.143900 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x50f4420]: verifying TLS 1.3 handshake data using RSA-PSS-RSAE-SHA256
```

We already faced SSL issues on 64-bit ARM (aarch64, ARMv8).

Can anybody test the aria2 package built by github on aarch64 on DSM 7+?

**Comment by hgy59** [comment]
The download on a very limitted 32-bit ARM system works (DS-115j with DSM 7.1)
The aarch64 system that fails above is DS-218 with DSM 6.2.4

working armv7-7.1 (armada370):
```
2024-04-07 18:50:59.567513 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x4151b378]: CERTIFICATE (11) was received. Length 3687[3687], frag offset 0, frag length: 3687, sequence: 0
2024-04-07 18:50:59.567592 [DEBUG] [Platform.cc:88] GnuTLS: <3> ASSERT: buffers.c[get_last_packet]:1177
2024-04-07 18:50:59.567672 [DEBUG] [Platform.cc:88] GnuTLS: <3> ASSERT: buffers.c[_gnutls_handshake_io_recv_int]:1428
2024-04-07 18:50:59.567777 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x4151b378]: parsing certificate message
2024-04-07 18:50:59.567887 [DEBUG] [Platform.cc:88] GnuTLS: <4> Found OCSP response on cert 0
2024-04-07 18:50:59.567982 [DEBUG] [Platform.cc:88] GnuTLS: <3> ASSERT: buffers.c[get_last_packet]:1186
2024-04-07 18:50:59.568082 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: SSL 3.3 Application Data packet received. Epoch 1, length: 281
2024-04-07 18:50:59.568149 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Expected Packet Handshake(22)
2024-04-07 18:50:59.568212 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Received Packet Application Data(23) with length: 281
2024-04-07 18:50:59.568403 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Decrypted Packet[2] Handshake(22) with length: 264
2024-04-07 18:50:59.568487 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x4151b378]: CERTIFICATE VERIFY (15) was received. Length 260[260], frag offset 0, frag length: 260, sequence: 0
2024-04-07 18:50:59.568566 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x4151b378]: Parsing certificate verify
2024-04-07 18:50:59.572551 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x4151b378]: verifying TLS 1.3 handshake data using RSA-PSS-RSAE-SHA256
2024-04-07 18:50:59.574903 [DEBUG] [Platform.cc:88] GnuTLS: <3> ASSERT: buffers.c[get_last_packet]:1186
2024-04-07 18:50:59.575054 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: SSL 3.3 Application Data packet received. Epoch 1, length: 53
2024-04-07 18:50:59.575295 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Expected Packet Handshake(22)
2024-04-07 18:50:59.575378 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Received Packet Application Data(23) with length: 53
2024-04-07 18:50:59.575545 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Decrypted Packet[3] Handshake(22) with length: 36
2024-04-07 18:50:59.575641 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x4151b378]: FINISHED (20) was received. Length 32[32], frag offset 0, frag length: 32, sequence: 0
2024-04-07 18:50:59.575727 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x4151b378]: parsing finished
2024-04-07 18:50:59.576098 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x4151b378]: sending finished
2024-04-07 18:50:59.576182 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x4151b378]: FINISHED was queued [36 bytes]
2024-04-07 18:50:59.577160 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Preparing Packet Handshake(22) with length: 36 and min pad: 0
2024-04-07 18:50:59.577388 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Sent Packet[1] Handshake(22) in epoch 1 and length: 58
2024-04-07 18:50:59.577868 [DEBUG] [Platform.cc:88] GnuTLS: <3> ASSERT: constate.c[_gnutls_epoch_get]:967
2024-04-07 18:50:59.577954 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Allocating epoch #2
2024-04-07 18:50:59.578242 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Initializing epoch #2
2024-04-07 18:50:59.578887 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Epoch #2 ready
2024-04-07 18:50:59.578965 [DEBUG] [Platform.cc:88] GnuTLS: <4> HSK[0x4151b378]: TLS 1.3 re-key with cipher suite: GNUTLS_AES_128_GCM_SHA256
2024-04-07 18:50:59.579053 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Start of epoch cleanup
2024-04-07 18:50:59.579118 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Epoch #0 freed
2024-04-07 18:50:59.579181 [DEBUG] [Platform.cc:88] GnuTLS: <5> REC[0x4151b378]: Epoch #1 freed
```

**Comment by cnrat** [comment]
> @cnrat I know, it is a long time ago, since you provided the aria2 package in #3275. In your PR we finally added the aria2c command to the `synocli-net` package - where it is still available for manual execution.
> 
> I now updated your former code to have an aria2 package that provides installation as a service. And I just finished the ariang package provided by @vitkabele to have a web UI for aria2 too.
> 
> In ariang I was able to connect to the aria2 service, but only with the `WebSocket` protocol. The connection with http protocol was not possible, neither with GET nor POST Methods. This will be worth a note on a page in our wiki.

I am deeply moved and almost speechless. To be honest, seeing your comment feels like Frieren standing before a statue of Himmel—I never realized that a small piece of code I compiled in 2018 would be nurtured and evolved by this amazing community for over six years.

It’s incredibly touching to see that aria2 has grown from a simple package into a full-fledged service with AriaNg integration. Thank you and everyone else for keeping the fire burning while I was away.

Since I have been "out of the party" for a long time and haven't contributed to its recent growth, I believe it is only fair that the MAINTAINER field reflects the people who truly care for it now.

Please update `MAINTAINER = cnrat` to the current active maintainers or the SynoCommunity team.

I am honored to have been the one to plant the seed. Seeing it become a sturdy tree under your care is the best reward I could ever imagine.

Best regards, cnrat

**Pull request merged**
