### PR TITLE
Add ipq806x architecture for SRM 1.1

### PR DESCRIPTION
**Pull request by publicarray**
_Motivation:_ Make it easier to get started and build for the RT2600ac Router (ipq806x).
_Related issues:_ #2951

Not sure if this is wanted due to it being listed as [No longer recieving packages updates](https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model#models-no-longer-recieving-packages-updates). But I thought a pull request at least gives visibility and can help people if they want to do it themselves.

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
@publicarray I agree to include SRM support...
@hgy59 May you please check if binaries produced for `ipq806x` arch may be "aggregated" together the same way with virtual `x64`?

**Comment by hgy59** [comment]
@ymartin59 I don't think that `ipq806x` arch can be aggregated. 
Synology provides different packages for `ipq806x` (and `northstarplus`) too, and does not merge it with other ARMv7 packages.

**Comment by Safihre** [comment]
I was the one that listed it as `No longer recieving packages updates.` because we didn't support it at the time. Sorry for that bad wording, probably good to support it now.
Looks good to me.

**Comment by publicarray** [comment]
@Safihre I think the wording is fine :) because technically the only way to get packages onto the SRM is to manually select and upload a spk file. Sadly there is no way to add "Package Sources" onto the SRM. I just wasn't sure if the project would support toolchains that could not be used via "Package Sources"

**Pull request merged**
