### PR TITLE
update jellyfin 10.8.1

### PR DESCRIPTION
**Pull request by stevenliuit**
## Description
update jellyfin 10.8.1
update dotnet 6.0.301

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by publicarray** [comment]
Nice work, Thanks for your contribution. I would like to have .NET 6 be fixed for non x64 platforms. See #5315 The DSM libs are too old for the new .NET versions.

@ta264 has been working on a chroot/bubblewrap/light wrapper to make *arr packages run with .NET 6: https://github.com/Servarr/spksrc/commits/master

**Comment by ta264** [comment]
I think the bubblewrap workaround is good for the everything but armada370. I tried to compile a version that would support that cpu but didn't manage. I think that (and therefore the ds213j) is dead for .NET apps. Otherwise I think all arm platforms are working in my packages.  If you're happy with the approach @publicarray I can start making some merge requests here

**Comment by stevenliuit** [comment]
> 



> I think the bubblewrap workaround is good for the everything but armada370. I tried to compile a version that would support that cpu but didn't manage. I think that (and therefore the ds213j) is dead for .NET apps. Otherwise I think all arm platforms are working in my packages. If you're happy with the approach @publicarray I can start making some merge requests here

No problem, I think @publicarray's idea is pretty cool.

**Comment by publicarray** [comment]
> No problem, I think @publicarray's idea is pretty cool.
> 

I really can't take any credit for this, it's all @ta264's excellent work and idea. 

@ta264

Yea thanks, I acknowledge that ideally it is Synology who should fix we can wait an eternity until that happens. I think bubblewrap is the best way forward, it should also help in the future when who knows what DSM update will break something again. Thanks again for working on this it's the best we have and I welcome any PRs you want to merge.

I can also make you a member if this will make things easier for your packages. (I also respect if you want to start hosting your own but this would make it easier for existing users)

@hgy59 Any thoughts or objections?

**Comment by stevenliuit** [comment]
> > No problem, I think @publicarray's idea is pretty cool.
> 
> I really can't take any credit for this, it's all @ta264's excellent work and idea.
> 
> @ta264
> 
> Yea thanks, I acknowledge that ideally it is Synology who should fix it , but we would wait an eternity until that happens. I think bubblewrap is the best way forward, it should also help in the future when who knows what DSM update will break something again. Thanks again for working on this it's the best we have and I welcome any PRs you want to merge.
> 
> I can also make you a member if this will make things easier for your packages. (I also respect if you want to start hosting your own but this would make it easier for existing users)
> 
> @hgy59 Any thoughts or objections?

The jellyfin official website has updated the version of dotnet in 10.8.1
#7984 [@crobibero] Upgrade to dotnet 6.0.6, update remaining dependencies
this url: https://github.com/jellyfin/jellyfin/pull/7984

update list:
https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.6/6.0.6.md
Also updates
SkiaSharp
SkiaSharp.NativeAssets.Linux
Sharpcompress

**Comment by stevenliuit** [comment]
@publicarray Can we get a first release? @ta264 hasn't committed the code yet.

**Comment by publicarray** [comment]
Continued here: #5382

**Pull request closed without merging**
