### PR TITLE
Upgrade Beets to v1.4.9 #3743

### PR DESCRIPTION
**Pull request by joelvaneenwyk**
_Motivation:_  Upgrade Beets to v1.4.9 
_Linked issues:_  #3743 

### Checklist
- [x] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by joelvaneenwyk** [comment]
@ymartin59 if you have a chance to review this that'd be great. I'm new to this so have not yet done the last step of installing the package on my NAS but the rest works within my Docker image.

**Comment by hgy59** [comment]
@ymartin59 can we update beets to use python3?

**Comment by ymartin59** [comment]
@joelvaneenwyk Thanks for contribution
@hgy59 Of course, please update beets to use Python 3, I have just merged #3833 with 3.6.10 which seems ready to run applications.

**Comment by ymartin59** [comment]
Superseeded by #3906

**Pull request closed without merging**
