### PR TITLE
[DSM 5] Update OctoPrint to 1.3.2

### PR DESCRIPTION
**Pull request by markbastiaans**
_Motivation:_ OctoPrint is in need of a new version. I'll update this PR as I make progress.
_Linked issues:_ I aim to make the package DSM6 compatible (#2661) and solve #2386 and #2599. 

### Checklist
- [x] Update SPK to 1.3.2
- [x] Fix `netifaces` issue for some archs
- [x] Cleanup
- [x] Squash commits
- [x] Build rule `arch-evansport` completed successfully
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by markbastiaans** [comment]
So far so good on `evansport` and DSM5.2. As-is, this PR should make things work on DSM5.2 again.

@Dr-Bean great work on the new wheel approach! It really makes maintaining Python packages a lot easier to do.

Some questions before I continue:
- Regarding the clean-up, do you have a preference for a separate cross package for OctoPrint, or should it be merged with the SPK? Patching is not required anymore.
- Regarding DSM6, any pointers / similar packages I can take a look at to make things work? I'll have to do it flying blind for the moment since my own NAS is still on 5.2.
- Also, do you prefer DSM6 compatibility in a separate PR?

**Comment by Dr-Bean** [comment]
If Octoprint can be built directly as a wheel (looks like it: no patches, no build-time dependencies), then the cross package should be removed. You can add the download site directly to the requirements file if I'm not mistaken.

DSM6 compatibility for Octoprint was added into the `dsm6` branch, see this commit: https://github.com/SynoCommunity/spksrc/commit/be04bd9ab4ef1dfd099f6ea7e813fd05cfb642e3. The changes for DSM6 for Octoprint are probably complete, but if you find out anything missing, open a PR against the `dsm6` branch.

The current version of `netifaces` is somewhat buggy for the Synology toolchains. As far as I can tell, you'll want to pin it to 0.10.4: 0.10.5 builds a wheel, it also installs, but it doesn't actually work for mutiple arches.

**Comment by tareko** [comment]
I was looking at the https://github.com/SynoCommunity/spksrc/commit/be04bd9ab4ef1dfd099f6ea7e813fd05cfb642e3 commit. Before I go and try to compile this myself, am I understanding correctly that there is now an octoprint version that works on dsm6? If so, how could I access it?

Thank you,

tarek : )

**Comment by markbastiaans** [comment]
@tareko the DSM6 branch doesn't have my changes yet. I'll open up a separate PR for DSM6 once I finish up and get this one merged.

**Comment by markbastiaans** [comment]
I can confirm that fixing `netifaces` works for nearly all supported architectures on DSM5.2. Unfortunately I can't get `monaco` and `armada38x` to build on my build environment. It would be great if someone could check those.

**Comment by markbastiaans** [comment]
So I've looked at the DSM6 version for Octoprint and merging this change should be as easy as some selective cherry-picking. I'll get on it once I'll have some spare time and my dev machine at hand.

**Comment by Careless** [comment]
@markbastiaans any progress or time to take a look at this at all, lately?

**Comment by Careless** [comment]
@markbastiaans 

any progress?

how do I get Octoprint 1.3.4 to run on DSM6.0? 

anyone?

**Pull request closed without merging**
