### PR TITLE
arch-geminilake: Add DSM 6.2.2 toolchain and kernel

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  Follow-up on a request to Synology to make accessible the `geminilake` arch toolchain & kernel sources.

Also, following a discussion with @ymartin59 it now also includes:
* all DSM 6.2 and 6.2.2 toolchain & kernels for all compatible arches
* fake DSM 6.2 arches for `purley` and `geminilake` to circumvent limitation of the publishing api (max 3 chars. for version)

Lastly, due to URL change for toolchain on sourceforge.net:
* Update & tested all DSM 5.2, 6.1, 6.2, 6.2.2
* Bulk changed <= DSM 5.1

_Linked issues:_  #4075, #4070, #4065, #4063, #4044, #3999
_Associated PR:_ #3787

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

**NOTE:** Currently pending `geminilake` kernel sources, discussion with Synology on-going.

### CODE REVIEW

**Comment by th0ma7** [comment]
@ymartin59 next steps are adding/completing the DSM-6.2 for API compatibility (not just `purley` and `geminilake`) and bulk change all other pre-DSM-5.2 toolchain configs.  Overall toolchain & kernel for DSM-5.2, 6.1 and 6.2.2 are now fully tested.  Also, I've added a TC_KERNEL variable for future kernel related work and fixed `mk/spksrc.kernel-modules.mk` so the built kernel version really matches Synology's version (e.g. through `mk/spksrc.kernel-modules.mk` add '`+`' sign to `EXTRAVERSION` variable).

Any additional thoughts before I move along with next changes?

**Comment by th0ma7** [comment]
@ymartin59 it is now ready for a good review as this is trivial but rather large.  I manually tried many many of them, and **all** of DSM 5.2+ up to 6.2.2.

Synology's reshuffling of directories online makes me believe DSM 6.2.3 will be made available shortly to fill in the gap for missing kernel files for `geminilake` as I requested, or better yet, a DSM7-beta, who knows?  If that's the case then it could end-up going into another PR.  At least this one if fixing the current issue.

**Comment by th0ma7** [comment]
> It would have been possible to collect many lines of variable settings and "myFix" target in per architecture and/or per major version common files (for instance `toolchains/common-x64.mk`) to discard copy-paste pattern and ease future maintenance.

@ymartin59 actually perhaps a change directly in the `mk/spksrc.tc.mk` would be more appropriate as most of them do have a `myFix`.  At least the most common one could be there such as the `chmod`.  I'll have a look at it in the weeks ahead and come back with a proposal.

On that note, what's the intent of the `find` command in the `myFix`?  I ask because `purley` didn't had any and I only included the `chmod` as it was needed but left aside the `find` command.  Lack of having it would it create build or runtime issues afterwards (e.g. thinking of `purley` `ffmpeg` package I've uploaded yesterday that I can't really test)?

On a somewhat similar note I also intent to move `cross/ds.evansport` to a new directory structure called `spksrc/toolkit` with probably a `mk/spksrc.tk.mk` helper... What do you think of that?

**Comment by ymartin59** [comment]
As far as I understand "myFix", it fixes ownership, group and access rights on file extracted from toolchain .tar.xz where (probably) Unix permissions are (sometimes/often) mangled if created from a non-Unix system and quickly published without control...
My opinion is whatever toolchain is correct or not, we should apply fix-logic - notice that when run in our docker on macOS is in trouble according many reports - that "fix" would also make sense there.
My idea of `toolchains/common-x64.mk` is to collect common variables for `x64` and avoid some many replicated lines.

**Pull request merged**
