### PR TITLE
Gogs v0.9.97

### PR DESCRIPTION
**Pull request by torrentalle**
This feaure add [Gogs ](https://gogs.io/)package. Gogs is a self-hosted Git service written in Go which is very easy to get running and has low system usage as well. It aspires to be the easiest, fastest, and most painless way to set up a self-hosted Git service.

### Checklist
- [x] Build rule `all-supported` completed successfully. See [Travis build](https://travis-ci.org/torrentalle/spksrc/builds/315074251)
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

Tested on platforns:
  - DSM-6.0 arch evansport
  - DSM 5.2 on  XPEnology (x64)

### CODE REVIEW

**Comment by torrentalle** [comment]
This resolves #1522, and resolves #1344

**Comment by cytec** [comment]
I've added some comments... please note i've only skimmed through this quickly and it's pretty early so i may have missed some things... besides that, i have some more general things i'd like to adress:

im not really used to glide and have to say that i've never used it before... but i used godeps and if that is anyhow similar (which it looks for me) why not install glide via `go get ...` and then in building run something like `$(RUN) glide install` which should do basically the same as adding a new make file and stuff like that but would keep the Makefile more spksrc like... if that won't work for some reason please tell me, but afaik it should...

also either use `PKG_DOWNLOAD_METHOD` to directly checkout from git (see: https://github.com/SynoCommunity/spksrc/blob/master/cross/rtmpdump/Makefile#L3-L6) or use `PKG_DIST_FILE` (i think that's the correct one) to have a name that's not only the version (see: https://github.com/SynoCommunity/spksrc/blob/master/cross/tesseract-ocr/Makefile#L5)

maybe @Dr-Bean will have a look too

**Comment by torrentalle** [comment]
I took these design decisions to solve some these problems:

The command `go get` always download the latest compatible version for each dependencies; this behavior causes non predictable builds, all build would be different. 

When I try to use dependency manager provided by Gogs project ([Glide](https://glide.sh/) or [GoPM](https://github.com/gpmgo/gopm)), I cannot install the dependencies without forcing dependency update, there are unresolved releases. In this case I have the same problem, all builds will be non predictable.

To solve this problem, I decided to parse the `glide.lock` file to generate corresponding Gihub URL's, to ensure that all builds from the dame package version will be equals.

This decision had consequences, each dependency must me extracted in a specific directory based on the package name. For this reason I don't use the provided extract methods, it's easier extract a package to a custom path than parse package name to extract the corresponding location.

I decided to implement this solution creating a new Makefile [`prepare-glide.mk`](https://github.com/torrentalle/spksrc/blob/gogs/cross/gogs/prepare-glide.mk) to make it reusable by other go projects.

All other ideas to solve this design problem are appreciated.

**Comment by torrentalle** [comment]
Merged with current `master` branch and updated [Travis build link](https://travis-ci.org/torrentalle/spksrc/builds/315074251)

**Pull request closed without merging**
