### PR TITLE
NZBget: update package for DSM 7

### LINKED ISSUE #4304: [Question] How do I create a package for NZBGET on DSM7 for my DS220j
Hi,

I would like to help building/updating packages, but it's not clear to me how I can build a package, like NZBGET, for DSM7 for my DS220j.

I saw the toolchain folders, which go to 6.2.3. Can I simply add 7.0 and create a Makefile accordingly?

Does anyone have any suggestions?

Thanks :-)

### LINKED ISSUE #4814: NZBGet - CONSTANTLY - fails to pack!
###  
_Package Name:_ nzbget
_Package Version:_ 20210607 -2

_NAS Model:_ DS1817
_NAS Architecture:_ Alpine
_DSM version:_ DSM 6.2.3-25426 Update 3

### Expected behavior Unpack via par or without par and eather way  with unrar
Tell us what should happen

### Actual behavior Constantly reports errors which manual inspection proves incorrect and SABNZBD processes each download without ANY problem
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

### Setup
_Package Name:_ 
_Package Version:_ 

_NAS Model:_ 
_NAS Architecture:_ 
_DSM version:_ 

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
_1._ 
_2._ 
_3._ 

#### Package log
_Installer log: find logfile `/var/log/packages/{package}.log`, for DSM<6: `/var/packages/{package}/target/var/{package}_installer.log` and protocol in Package Center.
You find service log and other log files in `/var/packages/{package}/target/var`.
_
```
Insert the package log(s) here
```
#### Other logs
_E.g. `/var/log/messages` or `/var/log/synopkg.log`_
```
Insert log here
```

### PR DESCRIPTION
**Pull request by hgy59**
_Motivation:_  This package needs update for shared folder creation for DSM 7
_Linked issues:_  probably fixes #4814, #4765, #4524. closes #4304, #4271

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### Remarks
https://github.com/SynoCommunity/spksrc/issues/4524#issuecomment-983288508
https://github.com/SynoCommunity/spksrc/issues/4524#issuecomment-990796764

We still have to solve permission issues...

### CODE REVIEW

**Comment by Safihre** [comment]
What permissions issues are there? Are they different from sabnzbd for example? Since for that one we already made a DSM 7 version.

**Comment by hgy59** [comment]
> What permissions issues are there? Are they different from sabnzbd for example? Since for that one we already made a DSM 7 version.

This were the nzbget.log i got:
```
Fri Dec 10 23:27:57 CET 2021
Starting nzbget command /volume1/@appstore/nzbget/bin/nzbget -c /volume1/@appdata/nzbget/nzbget.conf -o WebDir=/volume1/@appstore/nzbget/bin/webui -o LockFile=/volume1/@appdata/nzbget/nzbget.pid -D
Fri Dec 10 23:27:57 2021        INFO    nzbget 21.1 daemon-mode
Sat Dec 11 00:25:27 2021        DETAIL  Downloading nzbget version info
Sat Dec 11 00:25:27 2021        DETAIL  URL http://nzbget.net/info/nzbget-version.json?nocache=1639178728178 redirected to https://nzbget.net/info/nzbget-version.json?nocache=1639178728178
Sat Dec 11 00:25:27 2021        ERROR   TLS certificate verification failed for nzbget.net: certificate has expired. For more info visit http://nzbget.net/certificate-verification
Sat Dec 11 10:23:32 2021        ERROR   Could not move file /volume1/downloads/tmp/nzb-1.tmp to /volume1/downloads/nzb/:
Sat Dec 11 10:27:17 2021        ERROR   Could not move file /volume1/downloads/tmp/nzb-2.tmp to /volume1/downloads/nzb/:
Sat Dec 11 11:37:01 2021        DETAIL  Downloading nzbget version info
Sat Dec 11 11:37:01 2021        DETAIL  URL http://nzbget.net/info/nzbget-version.json?nocache=1639219020490 redirected to https://nzbget.net/info/nzbget-version.json?nocache=1639219020490
Sat Dec 11 11:37:01 2021        ERROR   TLS certificate verification failed for nzbget.net: certificate has expired. For more info visit http://nzbget.net/certificate-verification
```

But now i have done a new installation on DSM 7 with a new downloads share and everithiny looks ok.

So this is ready to merge!

**Comment by terafin** [comment]
@hgy59 - you rock, do you take donations? :)  Is there a way to manually pull down this package? (or how long until it's available in the main package set?)

**Comment by hgy59** [comment]
> @hgy59 - you rock, do you take donations? :) Is there a way to manually pull down this package? (or how long until it's available in the main package set?)

I already have local builds to publish, but currently the synocommunity.com admin backend is down ;-) so I cannot publish.
But you can download the packages built by github action [here](https://github.com/SynoCommunity/spksrc/actions/runs/1602312953)
Select artifacts - packages and download the packages.zip (you can download only the archive with all packages of a build action).
Then extract and manually install the spk for your diskstation (see [package architectures](https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures) under generic arch of your diskstation model to find the matching spk).

**Comment by terafin** [comment]
@hgy59 Thank you sir :)

**Comment by hgy59** [comment]
> @hgy59 - you rock, do you take donations?

I don't have currently a personal "by me a coffee" button, but you find sponsor links on the start page of this github project.
SynoCommunity needs always some money for the hosting of https://synocommunity.com.

**Comment by terafin** [comment]
@hgy59 Thank you!

**Comment by McEnnes** [comment]
@hgy59 Thank you very much! I did download the packages and it is probably me, but i have a DS718+ and i do not understand witch pachage is suitable for this machine.

**Comment by sammyke007** [comment]
> @hgy59 Thank you very much! I did download the packages and it is probably me, but i have a DS718+ and i do not understand witch pachage is suitable for this machine. Maybe i should use the noarch package, but that one is not there.

You need the "x86_64" arch, so nzbget_x64-6.1_20211220-28.spk if you run DSM 6.x or nzbget_x64-7.0_20211220-28.spk if you run DSM 7.

**Comment by inspectah88** [comment]
Thank you so much @hgy59 , I have been waiting for this update for ages! <3
Do I have to uninstall the old version first?
I get an "Couldn´t repair NZBGet" error when trying to manually install the package.
I have a DS216+II and use nzbget_x64-7.0_20211220-28.spk

**Comment by hgy59** [comment]
> Edit: Did a standard uninstall (keep files) and manual spk reinstall and everything was still there (history, config etc.).
> Tested and everything works. :)

We still have troubles updating packages on DSM7 that were originally installed on DSM6 (and this is hard to analyze).
Good to know you got it working.

**Comment by hgy59** [comment]
finally successfully published (with the help of #5012)

**Comment by flappy81** [comment]
Are the LE SSL cert issues still relevant? If so is it fixed in this version?

**Comment by Maeur1** [comment]
Testing some SSL base news servers, I seem to get the following error: 

image

Is this a known issue/has a workaround?

**Pull request merged**
