### PR TITLE
Dsm7 packages update jellyfin 10.8.0

### PR DESCRIPTION
**Pull request by stevenliuit**
update dotnet 6.0.300 verion
update jellyfin 10.8.0

### CODE REVIEW

**Comment by hgy59** [comment]
@stevenliuit welcome to this community and thank you for providing this PR.

Thanks for taking maintainer ownership for jellyfin package as @publicarray has less spare time available.

Some reviewer considerations:

- please revert the changes on zsh package related files (jellyfin is independent of zsh)
- please remove the build*.log file (never add build log files to the respository)
- please revert the removal of native/erlang as this will break the build of packages depending on erlang

**Comment by stevenliuit** [comment]
> 



> @stevenliuit welcome to this community and thank you for providing this PR.
> 
> Thanks for taking maintainer ownership for jellyfin package as @publicarray has less spare time available.
> 
> Some reviewer considerations:
> 
> * please revert the changes on zsh package related files (jellyfin is independent of zsh)
> * please remove the build*.log file (never add build log files to the respository)
> * please revert the removal of native/erlang as this will break the build of packages depending on erlang

It is possible that erlang was caused by my misoperation. At that time, I made a mistake in order to upgrade dotnet 6.0.
The first submission, thank you for pointing out the maze.

**Comment by publicarray** [comment]
I tried using your PR, but it is made from the wrong branch, please use the SynoCommunity/master branch for all PRs

**Comment by publicarray** [comment]
We have a guide here: https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#pull-requests

**Comment by stevenliuit** [comment]
> We have a guide here: https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#pull-requests
Thanks, I will study the documentation seriously.

**Pull request closed without merging**
