### PR TITLE
service.mk: Fix integer comparison with null string

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  Found a bug related to shell integer comparison in default startup scripts.
_Linked issues:_  N/A

### Checklist
- [ ] N/A

### CODE REVIEW

**Comment by th0ma7** [comment]
Hit the following bug while playing with faisibility to convert `rutorrent` to generic installer (indirectly relates PR #4234).

While doing the following:
```
# ./start-stop-status start
./service-setup: line 6: [: : integer expression expected
Starting  ...
./start-stop-status: line 29: [: : integer expression expected
```
It appears that the code checks if value is not null **and** lower than 6 (for prior to DSM6 version) such as:
```
[ -n "${SYNOPKG_DSM_VERSION_MAJOR}" -a "$SYNOPKG_DSM_VERSION_MAJOR" -lt 6 ]
```
The issue is that the entire condition `[ ]` gets evaluated as a whole thus the second condition will generate an error if length of string is 0.  The following attempts to fix this as the first condition will not pass thus second will not be checked:
```
[ -n "${SYNOPKG_DSM_VERSION_MAJOR}" ] && [ "$SYNOPKG_DSM_VERSION_MAJOR" -lt 6 ]
```

**Comment by ymartin59** [comment]
This is not a bug but a "feature". Please review doc about command line usage: https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#how-to-query-package-status-or-start-it-from-command-line
"&&" is only Bash but not Sh. "-a" is used so that script runs on both DSM 5 (sh probably dash) and DSM 6 (bash).

**Comment by th0ma7** [comment]
Then it really is broken as both tests cannot be evaluated within a single `[ ]` : if the first one fails, the second will still get evaluated and thus generate an error.

Another view on things is to process them as strings using case which would solve that.  I'll try to propose another approach then.

**Comment by th0ma7** [comment]
New approach tries to alleviate that using `case` which also opens the door to future changes due to DSM7 if any.
Also in `spksrc.service.start-stop-status` a `-n` test was done against `${USER}` while it isn't being used it the code below.

Converting:
```
if [ -n "$${SYNOPKG_DSM_VERSION_MAJOR}" -a "$${SYNOPKG_DSM_VERSION_MAJOR}" -lt 6 ]; then ...; else ... ;
```
to:
```
case $${SYNOPKG_DSM_VERSION_MAJOR} in [12345] ) ...  ;; * ) ... ;; esac
```

**Comment by ymartin59** [comment]
Again, script is designed to run from Package Center or `synopkg` context only  https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions#how-to-query-package-status-or-start-it-from-command-line
I find no  "relevant" way of "fixing" it as it may impact on package files (logs, permissions)... except if we officially discard DSM 5 support from framework

**Comment by th0ma7** [comment]
@ymartin59 honestly I'm OK at simply closing the issue and fully agree on the context how the code should be called.

Although, independently from how the script is being invoked, the `if` statement is fundamentally broken.  The reason it works is that when being properly called the `${SYNOPKG_DSM_VERSION_MAJOR}` variable is never `null` thus it passes the test.

**Pull request closed without merging**
