### PR TITLE
DAR Disk ARchive

### PR DESCRIPTION
**Pull request by spacifici**
_Motivation:_ adding DAR, the Disk ARchive. dar is a shell command that backs up from a single file to a whole filesystems, taking care of hard links, Extended Attributes, sparse files, MacOS's file forks, any inode type (including Solaris Door inodes), etc.

### Checklist
- [X] Build rule `all-supported` completed successfully
- [X] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
Thanks for contributing. This tool is probably interested for future "SynoCli disk" package: https://github.com/SynoCommunity/spksrc/issues/3251

**Comment by spacifici** [comment]
It doesn't seem a bad idea, do you need help with #3251? Maybe later I will have time to draft something out.

**Comment by Safihre** [comment]
We would really like help with #3251! :)

**Comment by hgy59** [comment]
@spacifici thanks again for your great work.
DAR is now integrated into synocli-disk and available as single package under /diyspk/dar.

**Pull request closed without merging**
