### PR TITLE
Update SABnzbd packages to 1.2.1

### PR DESCRIPTION
**Pull request by Safihre**
### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by KaraokeStu** [comment]
Building and publishing both sabnzbd and sabnzbd-testing now

**Comment by Safihre** [comment]
@KaraokeStu I just released [2.0.0Alpha1](https://github.com/sabnzbd/sabnzbd/releases/tag/2.0.0Alpha1), which works with our new `sabyenc` [C-module from pip](https://pypi.python.org/pypi/sabyenc).
Could you maybe incorporate this for `sabnzbd-testing`? 
Without having a Synology NAS myself I can't test it :)

**Comment by KaraokeStu** [comment]
Yeah no problem - are you able to submit a PR for 2.0.0Alpha1, or are you after getting me to do the legwork? ;)

**Comment by Safihre** [comment]
Yeah... Kind of 👼 
I tried once to setup the development environment, but it was so much packages and setup I didn't set it up completly.

**Comment by KaraokeStu** [comment]
I'll see what I can do tomorrow

**Comment by KaraokeStu** [comment]
Just test compiling sabnzbd-testing now @Safihre 

Can you confirm there are no breaking changes and/or config changes I need to worry about?
Also, are there any new dependencies to handle the new sabyenc module?

**Comment by Safihre** [comment]
No changes, the `sabyenc` module is a C-module so it will need to be able to compile.

**Comment by KaraokeStu** [comment]
Yeah, having fun with that now - my first attempt at a wheels cross-compile ;)

**Comment by KaraokeStu** [comment]
OK @Safihre I've got it all building, and as far as I can see it is installing the wheels correctly, however the app is still showing the following two log lines, which is confusing me:

```
SABYenc module... NOT found! Expecting v2.7.0 - https://sabnzbd.org/sabyenc
WARNING 27/02/2017 16:59 SABnzbd was started with encoding ANSI_X3.4-1968, this should be UTF-8. Expect problems with Unicoded file and directory names in downloads.
```

**Comment by KaraokeStu** [comment]
OK @Safihre got the sabyenc installed now 👍 

So now, what's the best way to deal with this pesky line?

`2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)] [ANSI_X3.4-1968]`

**Comment by Safihre** [comment]
You can set the encoding when starting it: https://github.com/sabnzbd/sabnzbd/issues/831

**Comment by KaraokeStu** [comment]
I'm not sure this is right... Here is the output of my locale:

``
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8
``

**Comment by Safihre** [comment]
Could be the way python was compiled or how the console was started. We heard this before. 

But how about adding that `env LANG=UTF-8 python xxxx `?

**Comment by KaraokeStu** [comment]
I'll check on my compiler locale

**Comment by KaraokeStu** [comment]
I've checked all of the locale settings on both the target and the compiler and it is showing UTF-8, even running python via the same command shell that SAB uses to start (and running under the same user)

`su - apps -c '/usr/local/sabnzbd-testing/env/bin/python -c "import locale ; print locale.getpreferredencoding() "'
`

And that outputs:
`UTF-8`

**Comment by Safihre** [comment]
@KaraokeStu Could it be that this is how the `dsm-control.sh` is run? Not as UTF8?
https://github.com/SynoCommunity/spksrc/blob/master/spk/sabnzbd-testing/src/dsm-control.sh
Because that one starts the daemon.

**Comment by KaraokeStu** [comment]
I've tweaked a test script in the same folder to run that version of python:

```
#!/bin/sh

# Package
PACKAGE="sabnzbd-testing"
DNAME="Python Locale Test"

# Others
INSTALL_DIR="/usr/local/${PACKAGE}"
PYTHON_DIR="/usr/local/python"
PATH="${INSTALL_DIR}/bin:${INSTALL_DIR}/env/bin:${PYTHON_DIR}/bin:${PATH}"
USER="apps"
PYTHON="${INSTALL_DIR}/env/bin/python"
SABNZBD="-c 'import locale ; print locale.getpreferredencoding()'"


start_daemon ()
{
    su ${USER} -c "PATH=${PATH} ${PYTHON} ${SABNZBD}"
}

case $1 in
    start)
            echo Starting ${DNAME} ...
            start_daemon
            exit $?
        ;;
esac

```

The weird thing is when I run `./test start`, I get the following output:

`Starting Python Locale Test ...
UTF-8`

**Comment by KaraokeStu** [comment]
ok, just did another check and if I start and stop from the command line via the script, it works fine - it seems that DSM is running the script under a different locale. @Dr-Bean have we heard of this happening before?

**Comment by Safihre** [comment]
Just add LANG=UTF-8 after/before the PATH=x doesn't work?

**Pull request merged**
