### PR TITLE
Update Lidarr to v0.8.0.2042

### PR DESCRIPTION
**Pull request by houndtt**
_Motivation:_  The in-app update to v0.8.0.2041 caused a startup issue. This amended PR is to move to v0.8.0.2042 which addresses this critical issue and re-base the package at the new version
_Linked issues:_  Resolves issue https://github.com/SynoCommunity/spksrc/issues/4409

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by houndtt** [comment]
While the package built successfully, neither an upgrade nor new installation is able to start the package successfully after installation.

**Upgrade Logs**

#### Package logs
_Check Package Center or `/usr/local/{package}/var/`_

_`lidarr_install.log`_
```
Wed Jan 27 08:46:57 AST 2021
===> Step preupgrade. USER=lidarr GROUP=sc-download SHARE_PATH=
Invoke service_preupgrade
Installed Lidarr Binary: 0.7.2.1878
Requested Lidarr Binary: 0.8.0.2041
[REPLACING] Installed Lidarr Binary
Wed Jan 27 08:46:58 AST 2021
===> Step preuninst. USER=lidarr GROUP=sc-download SHARE_PATH=
Wed Jan 27 08:46:59 AST 2021
===> Step postuninst. USER=lidarr GROUP=sc-download SHARE_PATH=
Wed Jan 27 08:47:01 AST 2021
===> Step preinst. USER=lidarr GROUP=sc-download SHARE_PATH=
Wed Jan 27 08:47:06 AST 2021
===> Step postinst. USER=lidarr GROUP=sc-download SHARE_PATH=
Installing service configuration /var/packages/lidarr/conf/lidarr.sc
Invoke service_postinst
Granting 'sc-lidarr' unix ownership on /volume1/@appstore/lidarr/var/.config
Granting 'sc-lidarr' unix ownership on /volume1/@appstore/lidarr/var
Wed Jan 27 08:47:07 AST 2021
===> Step postupgrade. USER=lidarr GROUP=sc-download SHARE_PATH=
Granting 'sc-lidarr' unix ownership on /volume1/@appstore/lidarr/var
Invoke service_postupgrade
Granting 'sc-lidarr' unix ownership on /volume1/@appstore/lidarr/var/.config
```
_`lidarr.log`_
``` 
Wed Jan 27 08:48:05 AST 2021
Starting lidarr command env PATH=/var/packages/mono/target/bin:/volume1/@appstore/lidarr/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appstore/lidarr/var LD_LIBRARY_PATH=/volume1/@appstore/lidarr/lib /var/packages/mono/target/bin/mono /volume1/@appstore/lidarr/share/Lidarr/Lidarr.exe 
NLog Exception: System.TypeInitializationException: The type initializer for 'NzbDrone.Common.EnvironmentInfo.OsInfo' threw an exception. ---> System.ComponentModel.Win32Exception: ApplicationName='ldd', CommandLine='/bin/ls', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0029f] in <c5f4e317158343a5916a953327f92540>:0 
  at System.Diagnostics.Process.Start () [0x0003a] in <c5f4e317158343a5916a953327f92540>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at NzbDrone.Common.EnvironmentInfo.OsInfo.RunAndCapture (System.String filename, System.String args) [0x00042] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.EnvironmentInfo.OsInfo.IsMusl () [0x00000] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.EnvironmentInfo.OsInfo.GetPosixFlavour () [0x0002e] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.EnvironmentInfo.OsInfo..cctor () [0x0002f] in <aa5eca47159443369c49058533a9ee93>:0 
   --- End of inner exception stack trace ---
  at NzbDrone.Common.EnvironmentInfo.AppFolderInfo..ctor (NzbDrone.Common.EnvironmentInfo.IStartupContext startupContext) [0x0000e] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.Instrumentation.NzbDroneLogger.Register (NzbDrone.Common.EnvironmentInfo.IStartupContext startupContext, System.Boolean updateApp, System.Boolean inConsole) [0x0001d] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Console.ConsoleApp.Main (System.String[] args) [0x00007] in <cae74d518fbb4f17a295aea976658133>:0 


EPIC FAIL! System.TypeInitializationException: The type initializer for 'NzbDrone.Common.EnvironmentInfo.OsInfo' threw an exception. ---> System.ComponentModel.Win32Exception: ApplicationName='ldd', CommandLine='/bin/ls', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0029f] in <c5f4e317158343a5916a953327f92540>:0 
  at System.Diagnostics.Process.Start () [0x0003a] in <c5f4e317158343a5916a953327f92540>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at NzbDrone.Common.EnvironmentInfo.OsInfo.RunAndCapture (System.String filename, System.String args) [0x00042] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.EnvironmentInfo.OsInfo.IsMusl () [0x00000] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.EnvironmentInfo.OsInfo.GetPosixFlavour () [0x0002e] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.EnvironmentInfo.OsInfo..cctor () [0x0002f] in <aa5eca47159443369c49058533a9ee93>:0 
   --- End of inner exception stack trace ---
  at NzbDrone.Common.EnvironmentInfo.AppFolderInfo..ctor (NzbDrone.Common.EnvironmentInfo.IStartupContext startupContext) [0x0000e] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.Instrumentation.NzbDroneLogger.Register (NzbDrone.Common.EnvironmentInfo.IStartupContext startupContext, System.Boolean updateApp, System.Boolean inConsole) [0x0001d] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Console.ConsoleApp.Main (System.String[] args) [0x00027] in <cae74d518fbb4f17a295aea976658133>:0 
Press enter to exit...
```
#### Other logs
_`/var/log/synopkg.log`_
```
2021/01/27 08:46:54	upgrade lidarr: begin to stop version 20200921-5
2021/01/27 08:46:54	upgrade lidarr 20200921-5 Begin start-stop-status stop
2021/01/27 08:46:55	upgrade lidarr 20200921-5 End start-stop-status stop ret=[0]
2021/01/27 08:46:56	upgrade lidarr 20200921-5 Begin unload apparmor
2021/01/27 08:46:56	upgrade lidarr 20200921-5 End unload apparmor ret=[0]
2021/01/27 08:46:56	upgrade lidarr: stop version 20200921-5 successfully, result 0
2021/01/27 08:46:57	upgrade lidarr 20200921-5 Begin preupgrade
2021/01/27 08:46:58	upgrade lidarr 20200921-5 End preupgrade ret=[0]
2021/01/27 08:46:58	upgrade lidarr 20200921-5 Begin preuninst
2021/01/27 08:46:58	upgrade lidarr 20200921-5 End preuninst ret=[0]
2021/01/27 08:46:59	upgrade lidarr 20200921-5 Begin /bin/rm -rf /volume1/@appstore/lidarr
2021/01/27 08:46:59	upgrade lidarr 20200921-5 End /bin/rm -rf /volume1/@appstore/lidarr ret=[0]
2021/01/27 08:46:59	upgrade lidarr 20200921-5 Begin postuninst
2021/01/27 08:46:59	upgrade lidarr 20200921-5 End postuninst ret=[0]
2021/01/27 08:46:59	upgrade lidarr: Uninstall 20200921-5 successfully
2021/01/27 08:47:01	upgrade lidarr 20210127-6 Begin preinst
2021/01/27 08:47:01	upgrade lidarr 20210127-6 End preinst ret=[0]
2021/01/27 08:47:01	upgrade lidarr 20210127-6 Begin /bin/rm -rf /volume1/@appstore/lidarr
2021/01/27 08:47:01	upgrade lidarr 20210127-6 End /bin/rm -rf /volume1/@appstore/lidarr ret=[0]
2021/01/27 08:47:01	upgrade lidarr 20210127-6 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/lidarr
2021/01/27 08:47:01	upgrade lidarr 20210127-6 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/lidarr ret=[0]
2021/01/27 08:47:03	upgrade lidarr 20210127-6 Begin /bin/mkdir -p /var/packages/lidarr
2021/01/27 08:47:03	upgrade lidarr 20210127-6 End /bin/mkdir -p /var/packages/lidarr ret=[0]
2021/01/27 08:47:03	upgrade lidarr 20210127-6 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/lidarr/INFO
2021/01/27 08:47:03	upgrade lidarr 20210127-6 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/lidarr/INFO ret=[0]
2021/01/27 08:47:03	upgrade lidarr 20210127-6 Begin /bin/rm -rf /var/packages/lidarr/scripts
2021/01/27 08:47:03	upgrade lidarr 20210127-6 End /bin/rm -rf /var/packages/lidarr/scripts ret=[0]
2021/01/27 08:47:03	upgrade lidarr 20210127-6 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/lidarr/scripts
2021/01/27 08:47:03	upgrade lidarr 20210127-6 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/lidarr/scripts ret=[0]
2021/01/27 08:47:03	upgrade lidarr 20210127-6 Begin /bin/rm -rf /var/packages/lidarr/WIZARD_UIFILES
2021/01/27 08:47:03	upgrade lidarr 20210127-6 End /bin/rm -rf /var/packages/lidarr/WIZARD_UIFILES ret=[0]
2021/01/27 08:47:03	upgrade lidarr 20210127-6 Begin /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/lidarr/WIZARD_UIFILES
2021/01/27 08:47:03	upgrade lidarr 20210127-6 End /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/lidarr/WIZARD_UIFILES ret=[0]
2021/01/27 08:47:03	upgrade lidarr 20210127-6 Begin /bin/rm -rf /var/packages/lidarr/conf
2021/01/27 08:47:03	upgrade lidarr 20210127-6 End /bin/rm -rf /var/packages/lidarr/conf ret=[0]
2021/01/27 08:47:03	upgrade lidarr 20210127-6 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/lidarr/conf
2021/01/27 08:47:03	upgrade lidarr 20210127-6 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/lidarr/conf ret=[0]
2021/01/27 08:47:06	upgrade lidarr 20210127-6 Begin postinst
2021/01/27 08:47:07	upgrade lidarr 20210127-6 End postinst ret=[0]
2021/01/27 08:47:07	upgrade lidarr 20210127-6 Begin postupgrade
2021/01/27 08:47:07	upgrade lidarr 20210127-6 End postupgrade ret=[0]
2021/01/27 08:47:07	upgrade lidarr: begin to start version 20210127-6
2021/01/27 08:47:08	upgrade lidarr 20210127-6 Begin pre-load apparmor
2021/01/27 08:47:08	upgrade lidarr 20210127-6 End pre-load apparmor ret=[0]
2021/01/27 08:47:09	upgrade lidarr 20210127-6 Begin start-stop-status start
2021/01/27 08:47:29	upgrade lidarr 20210127-6 End start-stop-status start ret=[1]
2021/01/27 08:47:30	(system) trigger lidarr 20210127-6 Begin start-stop-status stop
2021/01/27 08:47:30	(system) trigger lidarr 20210127-6 End start-stop-status stop ret=[0]
2021/01/27 08:47:30	(system) trigger lidarr 20210127-6 Begin unload apparmor
2021/01/27 08:47:30	(system) trigger lidarr 20210127-6 End unload apparmor ret=[0]
2021/01/27 08:47:30	stop lidarr: begin to stop version 20210127-6
2021/01/27 08:47:31	stop lidarr: stop version 20210127-6 successfully, result 0
2021/01/27 08:47:31	upgrade lidarr: start version 20210127-6 failed, result 272
2021/01/27 08:47:31	upgrade lidarr from 20200921-5 to 20210127-6 successfully
2021/01/27 08:47:31	upgrade lidarr 20210127-6 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2021/01/27 08:47:31	upgrade lidarr 20210127-6 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2021/01/27 08:47:32	install lidarr: begin to start version 20210127-6
2021/01/27 08:47:34	install lidarr 20210127-6 Begin pre-load apparmor
2021/01/27 08:47:34	install lidarr 20210127-6 End pre-load apparmor ret=[0]
2021/01/27 08:47:34	install lidarr 20210127-6 Begin start-stop-status start
2021/01/27 08:47:54	install lidarr 20210127-6 End start-stop-status start ret=[1]
2021/01/27 08:47:54	(system) trigger lidarr 20210127-6 Begin start-stop-status stop
2021/01/27 08:47:54	(system) trigger lidarr 20210127-6 End start-stop-status stop ret=[0]
2021/01/27 08:47:55	(system) trigger lidarr 20210127-6 Begin unload apparmor
2021/01/27 08:47:55	(system) trigger lidarr 20210127-6 End unload apparmor ret=[0]
2021/01/27 08:47:55	stop lidarr: begin to stop version 20210127-6
2021/01/27 08:47:55	stop lidarr: stop version 20210127-6 successfully, result 0
2021/01/27 08:47:55	install lidarr: start version 20210127-6 failed, result 272
2021/01/27 08:48:03	start lidarr: begin to start version 20210127-6
2021/01/27 08:48:04	start lidarr 20210127-6 Begin pre-load apparmor
2021/01/27 08:48:04	start lidarr 20210127-6 End pre-load apparmor ret=[0]
2021/01/27 08:48:05	start lidarr 20210127-6 Begin start-stop-status start
2021/01/27 08:48:25	start lidarr 20210127-6 End start-stop-status start ret=[1]
2021/01/27 08:48:26	(system) trigger lidarr 20210127-6 Begin start-stop-status stop
2021/01/27 08:48:26	(system) trigger lidarr 20210127-6 End start-stop-status stop ret=[0]
2021/01/27 08:48:27	(system) trigger lidarr 20210127-6 Begin unload apparmor
2021/01/27 08:48:27	(system) trigger lidarr 20210127-6 End unload apparmor ret=[0]
2021/01/27 08:48:27	stop lidarr: begin to stop version 20210127-6
2021/01/27 08:48:29	stop lidarr: stop version 20210127-6 successfully, result 0
2021/01/27 08:48:29	start lidarr: start version 20210127-6 failed, result 272
```


**New Install Logs**

#### Package logs
_Check Package Center or `/usr/local/{package}/var/`_

_`lidarr_install.log`_
```
Wed Jan 27 08:53:15 AST 2021
===> Step preuninst. USER=lidarr GROUP=sc-download SHARE_PATH=
Removing service configuration lidarr.sc
Wed Jan 27 08:53:16 AST 2021
===> Step postuninst. USER=lidarr GROUP=sc-download SHARE_PATH=
Removing user sc-lidarr
Wed Jan 27 08:53:47 AST 2021
===> Step preinst. USER=lidarr GROUP=sc-download SHARE_PATH=
Wed Jan 27 08:53:50 AST 2021
===> Step postinst. USER=lidarr GROUP=sc-download SHARE_PATH=
Installing service configuration /var/packages/lidarr/conf/lidarr.sc
Adding 'sc-lidarr' to 'sc-download'
Group Name: [sc-download]
Group Type: [AUTH_LOCAL]
Group ID:   [65536]
Group Members: 
0:[sc-radarr]
1:[sc-nzbdrone]
2:[sc-lidarr]
Invoke service_postinst
Granting 'sc-lidarr' unix ownership on /volume1/@appstore/lidarr/var/.config
```
_`lidarr.log`_
``` 
Wed Jan 27 08:53:52 AST 2021
Starting lidarr command env PATH=/var/packages/mono/target/bin:/volume1/@appstore/lidarr/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appstore/lidarr/var LD_LIBRARY_PATH=/volume1/@appstore/lidarr/lib /var/packages/mono/target/bin/mono /volume1/@appstore/lidarr/share/Lidarr/Lidarr.exe 
NLog Exception: System.TypeInitializationException: The type initializer for 'NzbDrone.Common.EnvironmentInfo.OsInfo' threw an exception. ---> System.ComponentModel.Win32Exception: ApplicationName='ldd', CommandLine='/bin/ls', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0029f] in <c5f4e317158343a5916a953327f92540>:0 
  at System.Diagnostics.Process.Start () [0x0003a] in <c5f4e317158343a5916a953327f92540>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at NzbDrone.Common.EnvironmentInfo.OsInfo.RunAndCapture (System.String filename, System.String args) [0x00042] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.EnvironmentInfo.OsInfo.IsMusl () [0x00000] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.EnvironmentInfo.OsInfo.GetPosixFlavour () [0x0002e] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.EnvironmentInfo.OsInfo..cctor () [0x0002f] in <aa5eca47159443369c49058533a9ee93>:0 
   --- End of inner exception stack trace ---
  at NzbDrone.Common.EnvironmentInfo.AppFolderInfo..ctor (NzbDrone.Common.EnvironmentInfo.IStartupContext startupContext) [0x0000e] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.Instrumentation.NzbDroneLogger.Register (NzbDrone.Common.EnvironmentInfo.IStartupContext startupContext, System.Boolean updateApp, System.Boolean inConsole) [0x0001d] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Console.ConsoleApp.Main (System.String[] args) [0x00007] in <cae74d518fbb4f17a295aea976658133>:0 


EPIC FAIL! System.TypeInitializationException: The type initializer for 'NzbDrone.Common.EnvironmentInfo.OsInfo' threw an exception. ---> System.ComponentModel.Win32Exception: ApplicationName='ldd', CommandLine='/bin/ls', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0029f] in <c5f4e317158343a5916a953327f92540>:0 
  at System.Diagnostics.Process.Start () [0x0003a] in <c5f4e317158343a5916a953327f92540>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at NzbDrone.Common.EnvironmentInfo.OsInfo.RunAndCapture (System.String filename, System.String args) [0x00042] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.EnvironmentInfo.OsInfo.IsMusl () [0x00000] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.EnvironmentInfo.OsInfo.GetPosixFlavour () [0x0002e] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.EnvironmentInfo.OsInfo..cctor () [0x0002f] in <aa5eca47159443369c49058533a9ee93>:0 
   --- End of inner exception stack trace ---
  at NzbDrone.Common.EnvironmentInfo.AppFolderInfo..ctor (NzbDrone.Common.EnvironmentInfo.IStartupContext startupContext) [0x0000e] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Common.Instrumentation.NzbDroneLogger.Register (NzbDrone.Common.EnvironmentInfo.IStartupContext startupContext, System.Boolean updateApp, System.Boolean inConsole) [0x0001d] in <aa5eca47159443369c49058533a9ee93>:0 
  at NzbDrone.Console.ConsoleApp.Main (System.String[] args) [0x00027] in <cae74d518fbb4f17a295aea976658133>:0 
Press enter to exit...
```
#### Other logs
_`/var/log/synopkg.log`_
```
2021/01/27 08:53:47	install lidarr 20210127-6 Begin preinst
2021/01/27 08:53:47	install lidarr 20210127-6 End preinst ret=[0]
2021/01/27 08:53:47	install lidarr 20210127-6 Begin /bin/rm -rf /volume1/@appstore/lidarr
2021/01/27 08:53:47	install lidarr 20210127-6 End /bin/rm -rf /volume1/@appstore/lidarr ret=[0]
2021/01/27 08:53:47	install lidarr 20210127-6 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/lidarr
2021/01/27 08:53:47	install lidarr 20210127-6 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/lidarr ret=[0]
2021/01/27 08:53:47	install lidarr 20210127-6 Begin /bin/rm -rf /var/packages/lidarr
2021/01/27 08:53:47	install lidarr 20210127-6 End /bin/rm -rf /var/packages/lidarr ret=[0]
2021/01/27 08:53:48	install lidarr 20210127-6 Begin /bin/mkdir -p /var/packages/lidarr
2021/01/27 08:53:48	install lidarr 20210127-6 End /bin/mkdir -p /var/packages/lidarr ret=[0]
2021/01/27 08:53:48	install lidarr 20210127-6 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/lidarr/INFO
2021/01/27 08:53:48	install lidarr 20210127-6 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/lidarr/INFO ret=[0]
2021/01/27 08:53:48	install lidarr 20210127-6 Begin /bin/rm -rf /var/packages/lidarr/scripts
2021/01/27 08:53:48	install lidarr 20210127-6 End /bin/rm -rf /var/packages/lidarr/scripts ret=[0]
2021/01/27 08:53:48	install lidarr 20210127-6 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/lidarr/scripts
2021/01/27 08:53:48	install lidarr 20210127-6 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/lidarr/scripts ret=[0]
2021/01/27 08:53:48	install lidarr 20210127-6 Begin /bin/rm -rf /var/packages/lidarr/WIZARD_UIFILES
2021/01/27 08:53:48	install lidarr 20210127-6 End /bin/rm -rf /var/packages/lidarr/WIZARD_UIFILES ret=[0]
2021/01/27 08:53:48	install lidarr 20210127-6 Begin /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/lidarr/WIZARD_UIFILES
2021/01/27 08:53:48	install lidarr 20210127-6 End /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/lidarr/WIZARD_UIFILES ret=[0]
2021/01/27 08:53:48	install lidarr 20210127-6 Begin /bin/rm -rf /var/packages/lidarr/conf
2021/01/27 08:53:48	install lidarr 20210127-6 End /bin/rm -rf /var/packages/lidarr/conf ret=[0]
2021/01/27 08:53:48	install lidarr 20210127-6 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/lidarr/conf
2021/01/27 08:53:48	install lidarr 20210127-6 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/lidarr/conf ret=[0]
2021/01/27 08:53:50	install lidarr 20210127-6 Begin postinst
2021/01/27 08:53:51	install lidarr 20210127-6 End postinst ret=[0]
2021/01/27 08:53:51	install lidarr 20210127-6 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2021/01/27 08:53:51	install lidarr 20210127-6 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2021/01/27 08:53:51	install lidarr 20210127-6 successfully
2021/01/27 08:53:52	install lidarr: begin to start version 20210127-6
2021/01/27 08:53:52	install lidarr 20210127-6 Begin pre-load apparmor
2021/01/27 08:53:52	install lidarr 20210127-6 End pre-load apparmor ret=[0]
2021/01/27 08:53:52	install lidarr 20210127-6 Begin start-stop-status start
2021/01/27 08:54:13	install lidarr 20210127-6 End start-stop-status start ret=[1]
2021/01/27 08:54:13	(system) trigger lidarr 20210127-6 Begin start-stop-status stop
2021/01/27 08:54:13	(system) trigger lidarr 20210127-6 End start-stop-status stop ret=[0]
2021/01/27 08:54:13	(system) trigger lidarr 20210127-6 Begin unload apparmor
2021/01/27 08:54:13	(system) trigger lidarr 20210127-6 End unload apparmor ret=[0]
2021/01/27 08:54:14	stop lidarr: begin to stop version 20210127-6
2021/01/27 08:54:14	stop lidarr: stop version 20210127-6 successfully, result 0
2021/01/27 08:54:14	install lidarr: start version 20210127-6 failed, result 272
```

**Comment by houndtt** [comment]
The PR has been updated to incorporate the fix https://github.com/lidarr/Lidarr/commit/3fcd8af697e6570ba79851dfe58c071982d3ab30.

**Review by publicarray — APPROVED** [review]
I'm not sure of the impact, but It was only a 3-day window before the fixed version was released. New users get updated to v0.8.0.2042 by the auto updater anyway. But this is a nice version bump and in case there are users stuck on v0.8.0.2041 this can't hurt. :+1:

**Comment by publicarray** [comment]
In the future can you always make a fresh branch from master? There is a major change, the `toolchains` folder was renamed to `toolchain` Thanks.

**Pull request merged**
