### PR TITLE
Update mono

### PR DESCRIPTION
**Pull request by hgy59**
_Motivation:_  Update to the latest (final?) Mono 5 release
_Linked issues:_  #3755

### Checklist
- [x] Build rule `all-supported` completed successfully (ppc arches not supported)
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully
- [x] Update dependent packages (jackett, sonarr, radarr, lidarr) for arch-88f6281

### CODE REVIEW

**Comment by ymartin59** [comment]
@hgy59 Thanks. Do you know if this update allows to run application packages with re-build of theses?

**Comment by hgy59** [comment]
@ymartin59 I am not sure whether I understand your question. 
I now have built jackett, lidarr, radarr and sonarr (nzbdrone) on this branch.
The installation on DS218+ (x64) and DS115j (armada370) succeeded and the applications are running (web pages are accessible).
On DS15j only jackett was running just after the installation ([x] Execute after installation). The other packages needed a second (or third) try to run sucessfully. Maybe this is due limited resources - weak CPU, only 256MB RAM, the resource monitor shows 100% CPU load for the whole installation duration.
Since I have no use case for this packages I have no idea whether the memory leak issue of sonarr/radarr is resolved with this build (#3470).

Anything else to validate?

**Comment by Stanzilla** [comment]
Got a test build somewhere?

**Comment by hgy59** [comment]
Just uploaded some archs to https://github.com/hgy59/spksrc/releases/tag/mono_v5.20-pre

**Comment by Stanzilla** [comment]
Hrm, crashes Sonarr for me:

```
Mon Feb  3 21:48:32 CET 2020
Starting nzbdrone command env PATH=/usr/local/mono/bin:/volume1/@appstore/nzbdrone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appstore/nzbdrone/var LD_LIBRARY_PATH=/volume1/@appstore/nzbdrone/lib /usr/local/mono/bin/mono /volume1/@appstore/nzbdrone/share/Sonarr/Sonarr.exe 
 r4_conv_to_r8 R47 <- R44
* Assertion: should not be reached at decompose.c:1891


=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
/proc/self/maps:
00010000-00369000 r-xp 00000000 fd:00 13548      /volume1/@appstore/mono/bin/mono-sgen
00378000-0037f000 rwxp 00358000 fd:00 13548      /volume1/@appstore/mono/bin/mono-sgen
0037f000-004f7000 rwxp 00000000 00:00 0          [heap]
40000000-40020000 r-xp 00000000 09:00 4614       /usr/lib/ld-2.15.so
40020000-40023000 rwxp 00000000 00:00 0 
40023000-40024000 r-xp 00000000 00:00 0 
40024000-40025000 ---p 00000000 00:00 0 
40025000-40026000 rwxs 00000000 00:10 72100      /dev/shm/mono.17908
40026000-4002f000 rwxp 00000000 00:00 0 
4002f000-40030000 r-xp 0001f000 09:00 4614       /usr/lib/ld-2.15.so
40030000-40031000 rwxp 00020000 09:00 4614       /usr/lib/ld-2.15.so
40031000-400c9000 r-xp 00000000 09:00 4743       /usr/lib/libm-2.15.so
400c9000-400d8000 ---p 00098000 09:00 4743       /usr/lib/libm-2.15.so
400d8000-400d9000 r-xp 00097000 09:00 4743       /usr/lib/libm-2.15.so
400d9000-400da000 rwxp 00098000 09:00 4743       /usr/lib/libm-2.15.so
400da000-400e0000 r-xp 00000000 09:00 3120       /usr/lib/librt-2.15.so
400e0000-400ef000 ---p 00006000 09:00 3120       /usr/lib/librt-2.15.so
400ef000-400f0000 r-xp 00005000 09:00 3120       /usr/lib/librt-2.15.so
400f0000-400f1000 rwxp 00006000 09:00 3120       /usr/lib/librt-2.15.so
400f1000-400f5000 r-xp 00000000 09:00 3121       /usr/lib/libdl-2.15.so
400f5000-40104000 ---p 00004000 09:00 3121       /usr/lib/libdl-2.15.so
40104000-40105000 r-xp 00003000 09:00 3121       /usr/lib/libdl-2.15.so
40105000-40106000 rwxp 00004000 09:00 3121       /usr/lib/libdl-2.15.so
40106000-4011b000 r-xp 00000000 09:00 1397       /usr/lib/libpthread-2.15.so
4011b000-4012b000 ---p 00015000 09:00 1397       /usr/lib/libpthread-2.15.so
```

**Comment by hgy59** [comment]
@Stanzilla did you try what they give as fix?
use `MONO_ENV_OPTIONS='-O=-aot,-float32'` on the command line before the `mono` command

**Comment by Stanzilla** [comment]
> @Stanzilla did you try what they give as fix?
> use `MONO_ENV_OPTIONS='-O=-aot,-float32'` on the command line before the `mono` command

image

**Comment by hgy59** [comment]
Please try this command line:
```
PATH=/usr/local/mono/bin:/volume1/@appstore/nzbdrone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appstore/nzbdrone/var LD_LIBRARY_PATH=/volume1/@appstore/nzbdrone/lib MONO_ENV_OPTIONS='-O=-aot,-float32' /usr/local/mono/bin/mono /volume1/@appstore/nzbdrone/share/Sonarr/Sonarr.exe 
```

**Comment by Stanzilla** [comment]
> Please try this command line:
> 
> ```
> PATH=/usr/local/mono/bin:/volume1/@appstore/nzbdrone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appstore/nzbdrone/var LD_LIBRARY_PATH=/volume1/@appstore/nzbdrone/lib MONO_ENV_OPTIONS='-O=-aot,-float32' /usr/local/mono/bin/mono /volume1/@appstore/nzbdrone/share/Sonarr/Sonarr.exe 
> ```

That seems to do the trick! Any way to work this into the startup scripts for Jackett and Sonarr without creating a package myself?

**Comment by Stanzilla** [comment]
This might be a release blocker though https://github.com/Jackett/Jackett/issues/7084

**Comment by hgy59** [comment]
Updated jacket, radarr, lidarr and sonarr packages for `arch-88f6281` are available here too:
https://github.com/hgy59/spksrc/releases/tag/mono_v5.20-pre

**Comment by Stanzilla** [comment]
Does Jackett work for you then? It certainly sounded like it shouldn't from what their dev said?

**Comment by hgy59** [comment]
I tested jackett on DS218+. The status is running and the web page is working AFAI can estimate (I am not a jackett user).

**Comment by Stanzilla** [comment]
The app itself works fine, just none of the network requests do, try an update check for example.

**Comment by hgy59** [comment]
When I press `Check for updates` I get ` Updater triggered see log for details..`
When I press `View logs` I get a new window with a log of server logs.
When I press `Apply server settings` I get `Redirecting you to complete configuration update..`
And I can add an indexer and Test is successful.

**Comment by Stanzilla** [comment]
Hrm. Weird.

**Comment by hgy59** [comment]
Please verify the log file `/var/packages/jackett/target/var/jacket.log`
You must find a line with `Info Environment variable MONO_ENV_OPTIONS is present` just after Info Starting Jacket ...

**Comment by Stanzilla** [comment]
it is there, otherwise it would not even start, yet any network request fails with 

```
02-04 01:59:36 Error Jackett.Common.IndexerException: Exception (nyaasi): /volume1/@appstore/mono/lib/../lib/libmono-btls-shared.so ---> System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: SecureChannelFailure (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.DllNotFoundException: /volume1/@appstore/mono/lib/../lib/libmono-btls-shared.so
  at (wrapper managed-to-native) Mono.Btls.MonoBtlsSslCtx.mono_btls_ssl_ctx_new()
  at Mono.Btls.MonoBtlsSslCtx..ctor () [0x00000] in <c5f4e317158343a5916a953327f92540>:0 
  at Mono.Btls.MonoBtlsContext.InitializeConnection () [0x00000] in <c5f4e317158343a5916a953327f92540>:0 
  at Mono.Btls.MonoBtlsContext.StartHandshake () [0x00000] in <c5f4e317158343a5916a953327f92540>:0 
  at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x0007e] in <c5f4e317158343a5916a953327f92540>:0 
  at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
  at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <c5f4e317158343a5916a953327f92540>:0 
  at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000ff] in <c5f4e317158343a5916a953327f92540>:0 
  at Mono.Net.Security.AsyncProtocolRequest.StartOperation (System.Threading.CancellationToken cancellationToken) [0x0008b] in <c5f4e317158343a5916a953327f92540>:0 
```

which I think it's a different issue.

**Comment by hgy59** [comment]
Just uninstalled version 0.12.1669.0 and installed v0.11.43.0.
It gives me the note `Your version of Jackett v0.11.43.0 is very old. Multiple indexers are likely to fail when using an old version. Update to the latest version of Jackett.`
But the tests work as posted for the current version.

This is all done with DS218+ that has arch-x64 (apollolake).

**Comment by hgy59** [comment]
And I installed Jackett v0.11.43.0 on my DS115j (armada370) with very limitted resources.
It installs fine and after some time, the package is in state `running`.
Sometimes the web page was not reachable. But finally it did an update to the latest version in the background.
And all tests run successfully.

**Comment by Letrab** [comment]
Like to test it on my DS214+ (Armadaxp).
Thanks!

**Comment by hgy59** [comment]
@Letrab just added the alpine and all armada releases of mono to:
https://github.com/hgy59/spksrc/releases/tag/mono_v5.20-pre

**Comment by ymartin59** [comment]
Hello @hgy59 What is this status PR? As far as I understand, I should build and publish all related applications packages too, correct?

**Comment by Stanzilla** [comment]
I'm still hoping that someone else can reproduce the connection issues, that would be a dealbreaker then

**Comment by hgy59** [comment]
@ymartin59 in my opignion we could update mono alone, as it is more a framework than a library to link against.
As the comparision table on https://www.mono-project.com/docs/about-mono/versioning/ shows, there are no differences in the core parts `msbuild` and `Roslyn C# Compiler` in Mono 5.16, 5.18 and 5.20, so I do not expect compatibility issues.
In other words: this is an update of the runtime, not the build system.

Therefore there is no need to rebuild the dependent packages.
For sure there is no need to increase the Version of Mono in SPK_DEPENDS of these packages!

But I am unsure about the issue of @Stanzilla. I suppose this is related to a single synology arch and occures with mono 5.16, 5.18 and 5.20.

**Comment by hgy59** [comment]
@Letrab did you succeed to install and use Jacket on armadaxp?

**Comment by Letrab** [comment]
Just installed it over a 5.18 install with running Radarr and Sonarr. 

Restarted Sonarr and Radarr manually after install and it's running fine on 5.20 now!
As well my Jackett works again, which was not functioning (starting) before! So in favor of merging this PR!

**Comment by curro88** [comment]
I've been trying to upgrade Mono for a while but whenever I upgrade (I've tried versions 5.18 or 5.20) Sonarr can't be executed.

I've attached the logs to see if anyone can help me. 
[mono.v5.08_nzbdrone-install.log](https://github.com/SynoCommunity/spksrc/files/4401453/mono.v5.08_nzbdrone-install.log)
[mono.v5.08_nzbdrone.log](https://github.com/SynoCommunity/spksrc/files/4401454/mono.v5.08_nzbdrone.log)
[mono.v5.20_nzbdrone-install.log](https://github.com/SynoCommunity/spksrc/files/4401455/mono.v5.20_nzbdrone-install.log)
[mono.v5.20_nzbdrone.log](https://github.com/SynoCommunity/spksrc/files/4401456/mono.v5.20_nzbdrone.log)

My NAS is a Synology DS213 (88f6282).

**Comment by hgy59** [comment]
@curro88 for the updated mono you have to modify the start command for armv5 archs (88f628x) as described above:
```
PATH=/usr/local/mono/bin:/volume1/@appstore/nzbdrone/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin HOME=/volume1/@appstore/nzbdrone/var LD_LIBRARY_PATH=/volume1/@appstore/nzbdrone/lib MONO_ENV_OPTIONS='-O=-aot,-float32' /usr/local/mono/bin/mono /volume1/@appstore/nzbdrone/share/Sonarr/Sonarr.exe

For now, you have to modify the start script yourself after installation.
We should incorporate this in the spk build for sonarr and jackett (an may be for radarr and lidarr too).

**Comment by curro88** [comment]
Thanks @hgy59. I’ve done some research and I think that the file I have to modify is `service-setup which is on `/var/package/nzbdrone/scripts`, I’m correct? If so, the thing is that I’m not sure where and what I need to modify to add the code you mentioned :)

**Comment by hgy59** [comment]
@curro88 sorry for my false information given to you. 
When you install the prerelease package from my github repo (https://github.com/hgy59/spksrc/releases/tag/mono_v5.20-pre)
you will get the script installed that has the armv5/88f682x bugfix included.

If you don't want to install this package, you can extract the service-setup script from the spk (extract with 7-zip or tar)

Or insert the following code in the service-setup script (as you have found this on your diskstation), between the lines starting with `MONO_PATH=` and `SERVICE_COMMAND=`
```
# workaround for mono bug with armv5 (https://github.com/mono/mono/issues/12537)
if [ "$SYNOPKG_DSM_ARCH" == "88f8621" -o "$SYNOPKG_DSM_ARCH" == "88f8622" ]; then
    MONO="MONO_ENV_OPTIONS='-O=-aot,-float32' ${MONO_PATH}/mono"
fi
```

**Comment by Stanzilla** [comment]
Even with that workaround in place, jackett fails with

```
Wed Apr  1 01:16:02 CEST 2020
Starting jackett command  
Starting Jackett as user sc-jackett
 r4_conv_to_r8 R47 <- R44
* Assertion: should not be reached at decompose.c:1891
```

**Comment by curro88** [comment]
> @curro88 sorry for my false information given to you.
> When you install the prerelease package from my github repo (https://github.com/hgy59/spksrc/releases/tag/mono_v5.20-pre)
> you will get the script installed that has the armv5/88f682x bugfix included.

The packages I've installed are the ones from your repo so I don't understand why I cannot execute Sonarr after install it.

**Comment by Letrab** [comment]
@hgy59 

The if condition is not hit

`if [ "$SYNOPKG_DSM_ARCH" == "88f8621" -o "$SYNOPKG_DSM_ARCH" == "88f8622" ]; then`

88f8622 iso 88f6282 😃 . Typos? Same for 88f8621 should be 88f6281 ? 😉

**Comment by Stanzilla** [comment]
Hah, that would explain it :D

**Comment by hgy59** [comment]
@Letrab, @Stanzilla you are right (shame on me, dyslexia)

I have updated the prerelease packages.

**Comment by curro88** [comment]
I‘ve tried to change the name of the processors as it says @Letrab but Sonarr is still not executed so I would like to try the new @hgy59 prerelease packages to see if It’s work but If I go to `https://github.com/hgy59/spksrc/releases/tag/mono_v5.20-pre` last update is from Feb 3.

**Comment by curro88** [comment]
> I‘ve tried to change the name of the processors as it says @Letrab but Sonarr is still not executed so I would like to try the new @hgy59 prerelease packages to see if It’s work but If I go to your repo (https://github.com/hgy59/spksrc/releases/tag/mono_v5.20-pre) last update is from Feb 3.

It’s working!!!

**Comment by curro88** [comment]
After restoring my Sonarr backup and letting it update my entire library, I realized that nothing works, i.e. it can't find any torrents or Sonarr updates or anything. I've tried downgrading Mono to SynoCommunity 5.18 package and the same but when I've downgrade to SynoCommunity 5.08 package everything back to normal.

I've attached the log after a clean install of @hgy59 Mono 5.20 and @Safihre Sonarr v3:
[sonarr.txt](https://github.com/SynoCommunity/spksrc/files/4422516/sonarr.txt)

PS: By the way... thanks to all of you guys!!

**Comment by Stanzilla** [comment]
That's what I mentioned above, the apps are not able to establish network connections with this version of mono.

**Comment by ymartin59** [comment]
@hgy59 As publishing all these packages, I would take the opportunity of upgrading Jackett package to latest version. It should still work on Mono according to my readings.

**Comment by ymartin59** [comment]
@hgy59 FYI I am working on Jackett update.

**Comment by ymartin59** [comment]
Everything published!

**Comment by Stanzilla** [comment]
Tested again with the published version, mono apps still can't establish network connections here.

**Comment by richyboy1980** [comment]
@hgy59 Is there a Mono 5.20 update available for the SynologyDS418j (rtd1293)?

**Comment by hgy59** [comment]
@richyboy1980 as for rtd1296 you can use the generic aarch64 (=arm64) package available with my Mono 5.20 pre releases.
But there are known issues with Mono (> 5.8.0) for arm64 cpus.

**Comment by richyboy1980** [comment]
@hgy59 would you mind posting me a link? I've been looking for days and have not had any luck

**Comment by hgy59** [comment]
@richyboy1980 sorry, just deleted my prerelease 30 minutes ago....
unfortunately since the server migration the direct links to download packages on https://synocommunity.com/package/mono are gone (@ymartin59: will we support the download links for packages again?).

But, when you configured https://packages.synocommunity.com as package source in the package center of your diskstation *AND* enabled packages from `Synology and trusted publishers` then you should see the synocommunity packages incl. mono 5.20.
Unfortunately the updated `easy install` section on https://synocommunity.com with screenshots and the __https__ address is missing on the new server too.

**Comment by richyboy1980** [comment]
@hgy59 The latest version showing in the Community tab in packages is the 5.8 version currently installed. No latest version is showing

**Comment by hgy59** [comment]
Here we go again, I have created a new version and uploaded to the recreated pre-release
You find it here (only aarch64 for now, it took 45 minutes to build)
https://github.com/hgy59/spksrc/releases/edit/mono_v5.20-pre

**Comment by richyboy1980** [comment]
Thanks for that @hgy59 but the link just takes me to my own home page. Sorry to be a pain in the backside!

**Comment by hgy59** [comment]
fixed

**Comment by richyboy1980** [comment]
downloaded and installed. The only issue is Sonarr update page gives the error "Failed to fetch updates". Is this a known issue?

**Comment by Stanzilla** [comment]
> Tested again with the published version, mono apps still can't establish network connections here.

Yep.

**Comment by richyboy1980** [comment]
@Stanzilla So manual update is the future for now?

**Comment by Stanzilla** [comment]
Dunno, nothing works for me with the new mono version, had to stop using it.

**Comment by richyboy1980** [comment]
@Stanzilla Which version of mono are you using, 5.8?

**Comment by Stanzilla** [comment]
Yea

**Comment by richyboy1980** [comment]
@Stanzilla any chance of a link to the updates on GitHub? I found the 3.0.3.750 version but I'm sure there is another but I am struggling to find it

**Comment by Stanzilla** [comment]
I installed it from the package manager in DSM when it was there

**Comment by richyboy1980** [comment]
Ah ok. The package manager is only showing v2 at the moment

**Comment by ymartin59** [comment]
Publish CheckList
- [ ] mono
- [ ] jackett
- [ ] lidarr
- [ ] radarr
- [ ] sonar

**Comment by ymartin59** [comment]
@hgy59 Mono and related applications for `aarch64` have been disabled because of a runtime failure but I do not remember what it was about. What is the current status?

**Comment by hgy59** [comment]
> 
> @hgy59 Mono and related applications for `aarch64` have been disabled because of a runtime failure but I do not remember what it was about. What is the current status?

You find the most arguments in  #3666

On this mono issue https://github.com/mono/mono/issues/8648 @directhex states that he have up supporting mono for arm64 (for debian 8 only) due to the brocken arm64 support of gcc 4.

So this might be fixed when synology (some day in the future?) will support arm64 toolchain with GCC version >= 5.

**Pull request merged**
