### PR TITLE
Domoticz2563

### PR DESCRIPTION
**Pull request by gkroone**
PR to upgrade Domoticz to latest stable revision and add openzwave support.

Note: this version of Domoticz depends on a recent snapshot version of openzwave, which has limitted retention on the upstream site, so I had to move to a newer revision of openzwave source, which was not yet fully tested.
Note2: this version of Domoticz moves all user-specific data to $INSTALL-DIR/var during upgrade from SPK versions 6 and lower.
Note3: some issues have been reported with compatibility with octoprint package, but no further details were given.

This is a continuation of PR: https://github.com/Decipher/spksrc/pull/1 against another PR: https://github.com/SynoCommunity/spksrc/pull/1612

The code was tested by multiple users on multiple archs here: https://github.com/SynoCommunity/spksrc/issues/1478

### CODE REVIEW

**Comment by gkroone** [comment]
Looks like something going wrong with PR #1766 where there's files changed which I did not touch..

I did not do anything with  cross/sabnzbd tesseract or PyLoad.. 

Still kind of new to git etc, any advice on way forward would be welcome...

**Comment by gkroone** [comment]
@Dr-Bean, @Diaoul, I beleive I fixed the issues with sabnzbd tesseract and pyload in this PR. still I don't understsand why there's comments regarding those packages in this PR. should I close the PR and re-submit a new one?

**Comment by Diaoul** [comment]
I suggest you backup your work, delete your fork, create a new one and copy back your changes. Then you can submit a PR again it'll be clean.

**Comment by gkroone** [comment]
New PR created: https://github.com/SynoCommunity/spksrc/pull/1769
closing this one.

**Pull request closed without merging**
