### PR TITLE
New package:  jupp editor

### PR DESCRIPTION
**Pull request by hboetes**
_Motivation:_ Add the Jupp package, an editor which supports various known user interfaces, like pico, emacs, joe, start etc

### Checklist
- :heavy_check_mark: Build rule `all-supported` completed successfully
- :heavy_check_mark: Package upgrade completed successfully
- :heavy_check_mark: New installation of package completed successfully
- :heavy_check_mark: Package removal completed successfully

### CODE REVIEW

**Comment by hboetes** [comment]
I hope this doesn’t get too messy.

**Comment by KaraokeStu** [comment]
Could you squash this into one commit to make it easier to see what's going on?

**Comment by hboetes** [comment]
Now that would be nice indeed… Lets see if I can do that. Might take a few days.

**Comment by hboetes** [comment]
OK, that was not so hard, here’s how I did it:
```
git log # to see how many commits I have to undo
git reset –soft HEAD~12 # so 12 commits in total
git commit -o ../spk/jupp ../../cross/jupp/ # Only commit my changes
git branch # to see on which branch I am
git push origin +jupp-master # To get the right commit
```

**Comment by KaraokeStu** [comment]
Excellent.

Do you fancy writing a quick wiki entry regarding how to squash?  - I'm sure it would have been useful for me when I first started here! 

In the meantime, I'll get this reviewed ready for merging!

**Comment by hboetes** [comment]
Where did you upload the squashing wiki entry?

**Comment by KaraokeStu** [comment]
Wiki Entry here:
https://github.com/SynoCommunity/spksrc/wiki/Squashing-GIT-Commits

**Comment by KaraokeStu** [comment]
@hboetes Currently cannot publish as jupp mirror seems to be down

**Comment by KaraokeStu** [comment]
@hboetes Temporarily downloading from HTTP rather than HTTPS and now building.

**Comment by hboetes** [comment]
Ah right, I forgot about that, Thorsten set up his server so that HTTPS only works over IPv6. It's his weird sense of humour. Please remove the s, I'm not behind my laptop and won't be until much later.

**Pull request merged**
