### PR TITLE
kernel: Add DSM-6.2.4 kernels

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

After multiple requests Synology finaly released DSM-6.2.4 source code!!!  Interestingly the kernel source code are on the new synology server but the toolchains stayed on sourceforge.  We can probably expect all new release to be on the new server.

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [ ] Package update
- [x] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by Safihre** [comment]
Can we not get rid of all the other 6.2 ones? Why do we need to keep those?
Same for the toolchains.

**Comment by hgy59** [comment]
> Can we not get rid of all the other 6.2 ones? Why do we need to keep those? Same for the toolchains.

As those need very little resources - one Makefile and one digests file (< 600 Bytes) per arch and version, I have no problem to keep all toolchains and kernels in our repo.
Regard it as documentation of what synology provides to download.

**Comment by Safihre** [comment]
Why are there so many more of 6.2.X than of the other ones?

**Comment by th0ma7** [comment]
Simply because synology ended-up switching their numbering schema ... and there where many security issues as well (Meltdown/Spectre/L1TF) that needed backporting to various kernels while not really updating anything else in the DSM OS.

**Pull request merged**
