### PR TITLE
[WIP] ffmpeg Q1-2021 update

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  Regular round of dependency updates, mostly related to Intel vaapi hardware acceleration
_Linked issues:_  N/A

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### Issues
- [x] `aarch64` build error on `svt-av1` starting with version 0.8.6: https://github.com/AOMediaCodec/SVT-AV1/issues/1674
- [x] `libass` now requires `harfbuzz` which in turns requires c++11 support
- [x] `ffmpeg` disable `libass` support for ARMv5 due to lacking c++11 support
- [x] `libicu` build failure on `hi3535` - Thnx to the perfect timing of @smaarn for providing the fix https://github.com/SynoCommunity/spksrc/commit/d9205aeb26aa71dd69f87419163e6f68ce584a55
- [x] `libvpx` enforce `-std=c++0x` for ARMv5

### CODE REVIEW

**Review by ymartin59 — APPROVED** [review]

**Comment by th0ma7** [comment]
@ymartin59 @publicarray @smaarn @hgy59 I'm considering making this my last release for DSM6 and would really much release a first DSM7 release while at it.  How far are we to accomplish that?

**Comment by publicarray** [comment]
I would hold off publishing until the dsm7 branch is reviewed and merged.

**Comment by th0ma7** [comment]
@publicarray thnx for the heads-up.  Any idea at this point when this can happen?

**Comment by publicarray** [comment]
I've just created the PR :point_right:  #4395
 :smiley:

**Comment by tekadvice** [comment]
Any way for a noob like me to install ffmpeg on dsm 7?

**Comment by publicarray** [comment]
@tekadvice try a pre-release version here: https://seby.io/download/synology-7.0

**Comment by ymartin59** [comment]
@th0ma7 Please take care to commit message content when merging

**Pull request merged**
