### PR TITLE
pyLoad: new package

### PR DESCRIPTION
**Pull request by kmarty**
Reopen #1024

### CODE REVIEW

**Comment by Diaoul** [comment]
LGTM, maybe could be nicer with a better database init part but I think this is good as is.
@Dr-Bean ?

**Comment by Dr-Bean** [comment]
Yeah, was thinking about that. I might take another stab at it when I have a bit more time (getting Expect or an alternative to run correctly). I guess that can be postponed until a future database update comes along.

**Comment by Dr-Bean** [comment]
Merged with https://github.com/SynoCommunity/spksrc/commit/9a3457a41beaa715e8c9a3017da9e3a1cdbf2a52. A couple of changes were done after merging, including these: https://github.com/SynoCommunity/spksrc/commit/2dcfc5b8b5fe46ea4937ac1e4145777fb9bcdeb1.

Thanks for the addition :) I'll publish when I can, it's still building here.

**Comment by Dr-Bean** [comment]
Pyload 0.4.9-1 has been published on the repository.

**Pull request merged**
