### PR TITLE
Synocli file: add iconv

### LINKED ISSUE #5319: Add iconv to the SynoCli File Tools package.
### Software Name

SynoCli/iconv

### Brief Description

The iconv program converts the encoding of characters in inputfile from one coded character set to another.

### Website

https://linux.die.net/man/1/iconv

### Documentation

https://linux.die.net/man/1/iconv

### Build/Installation documentation

https://github.com/processone/iconv

### Source code

https://github.com/processone/iconv

### OpenSource License

Apache

### Other License

_No response_

### PR DESCRIPTION
**Pull request by hgy59**
## Description

Add iconv tool to synocli-file

Closes #5319

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
@BaukeZwart you can download the packages built by github action under "Checks - Build - Artifacts" for manual installation.

**Comment by BaukeZwart** [comment]
Installed the build, going to test the script I have that uses iconv asap.
Thanks again for the fast response.

**Comment by BaukeZwart** [comment]
Unfortunately, it doesn't work for my script.
Running ` iconv -f utf-8 -t ascii//TRANSLIT`, trows this error:
```Error: near line 1: near "ackstr": syntax error```

**Comment by hgy59** [comment]
So far I found, that two version of iconv exist.
one is `Written by Ulrich Drepper` and the other one `Written by Bruno Haible`. The second one is the one I included for now. The other one is from glibc that I did not find source code for - but it is contained in the synology toolchains in binary format, so it could be added from there into to package.

```
iconv --version
iconv (crosstool-NG 1.20.0) 2.20-2014.11
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Ulrich Drepper.
```

```
iconv --version
iconv (GNU libiconv 1.17)
Copyright (C) 2000-2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Bruno Haible.
```

the first one works as you expected:
```
echo abc ß α € àḃç | iconv   -f UTF-8 -t ASCII//TRANSLIT
abc ss ? EUR abc
```

the second one needs an extra parameter to substitute unconvertible Unicode characters
and a small difference is in ``à => `a``
```
echo abc ß α € àḃç | iconv -f UTF-8 --unicode-subst=? -t ASCII//TRANSLIT
abc ss ? EUR `abc
```

@BaukeZwart does your use case work with unconvertible character substitution (you can even ignore such characters with the parameter `-c`)?
Or shall I use the synology toolchain version of iconv for the package?

**Comment by BaukeZwart** [comment]
> @BaukeZwart just switched to the other one as it does not even need compilation.

Super, this last build is working great

**Pull request merged**
