### PR TITLE
Added OpenJDK 11 plus dependencies for DSM7

### PR DESCRIPTION
**Pull request by arnebjarne**
_Motivation:_  Java is missing since Java 8 package has not been updated for ages. Here is my Java 11 suggestion based on OpenJDK.
_Linked issues:_  https://github.com/SynoCommunity/spksrc/issues/4773

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by arnebjarne** [comment]
Hmm 

2021-08-12T23:47:35.8699436Z hg clone -r jdk-11.0.12+7 https://hg.openjdk.java.net/jdk-updates/jdk11u
2021-08-13T01:00:09.8857591Z adding changesets
2021-08-13T01:00:09.8858645Z adding manifests
2021-08-13T01:00:09.8859234Z adding file changes
2021-08-13T01:00:09.8859959Z added 54271 changesets with 455189 changes to 180686 files
2021-08-13T01:00:18.4738887Z (warning: large working directory being used without fsmonitor enabled; enable fsmonitor to improve performance; see "hg help -e fsmonitor")
2021-08-13T01:00:18.4740123Z new changesets fd16c54261b3:f412f2537f15
2021-08-13T01:00:18.4741784Z updating to branch default
2021-08-13T01:00:38.9070785Z 67765 files updated, 0 files merged, 0 files removed, 0 files unresolved
2021-08-13T01:01:10.0857898Z ===>  Verifying files for java-11-openjdk
2021-08-13T01:01:10.0874205Z ===>    Checking sha1sum of file java-11-openjdk-rjdk-11.0.12+7.tar.gz
2021-08-13T01:01:10.4468006Z ===>      Wrong sha1sum for file java-11-openjdk-rjdk-11.0.12+7.tar.gz
2021-08-13T01:01:10.4482829Z ===>      Renamed as java-11-openjdk-rjdk-11.0.12+7.tar.gz.wrong
2021-08-13T01:01:10.4489856Z ===>      Download cookie removed to trigger the download again
2021-08-13T01:01:10.4497114Z make[1]: *** [../../mk/spksrc.checksum.mk:42: checksum_target] Error 1
2021-08-13T01:01:10.4498534Z make[1]: Leaving directory '/github/workspace/cross/java-11-openjdk'
2021-08-13T01:01:10.4501892Z make: *** [../../mk/spksrc.depend.mk:51: depend_target] Error 2
2021-08-13T01:01:10.4510070Z make: Leaving directory '/github/workspace/spk/java-11-openjdk'

Looks like I have added a wrong sha1. I will double check it now.

**Comment by arnebjarne** [comment]
I see the problem:

 make digests
===>  Downloading files for java-11-openjdk
hg clone -r jdk-11.0.12+7 https://hg.openjdk.java.net/jdk-updates/jdk11u
adding changesets
adding manifests
adding file changes
added 54271 changesets with 455189 changes to 180686 files
new changesets fd16c54261b3:f412f2537f15
updating to branch default
67765 files updated, 0 files merged, 0 files removed, 0 files unresolved
===>  Generating digests for java-11-openjdk
bjarne@synology-spksrc:~/fork/spksrc/cross/java-11-openjdk$ cat digests
java-11-openjdk-rjdk-11.0.12+7.tar.gz SHA1 023e1ce01ba49422164ae304890dc44546ed7451
java-11-openjdk-rjdk-11.0.12+7.tar.gz SHA256 bbe1787b040376a5b21b9d07acac3d3d830a7d2179ef07e1eecc57fac69f1e13
java-11-openjdk-rjdk-11.0.12+7.tar.gz MD5 2af462a0edcd256b81920ab0eeb9de54
bjarne@synology-spksrc:~/fork/spksrc/cross/java-11-openjdk$ cat digests.old
java-11-openjdk-rjdk-11.0.12+7.tar.gz SHA1 e3bbd012b76795843ce83555068c671b614c44d2
java-11-openjdk-rjdk-11.0.12+7.tar.gz SHA256 d599457440dc5f296865a8aa4540390c30b4ec2903e3f8549866145068adf43d
java-11-openjdk-rjdk-11.0.12+7.tar.gz MD5 1c85262727790fcc1f62840f4a53557c


though the https://hg.openjdk.java.net/jdk-updates/jdk11u
is unchanged, the checksum changes.

I have removed the digest file. Hopefully the build system will accept that?

**Comment by hgy59** [comment]
> Looks like I have added a wrong sha1. I will double check it now.

No, you clone a hg repo, so the downloaded archive may differ in content for each download.

**Comment by arnebjarne** [comment]
> > Looks like I have added a wrong sha1. I will double check it now.
> 
> No, you clone a hg repo, so the downloaded archive may differ in content for each download.

Will the build system accept a package without a digests ?

**Comment by hgy59** [comment]
> ill the build system accept a package without a digests ?

just define `CHECKSUM_TARGET = nop` in the cross/{package}/Makefile to disable digests validation.

**Pull request closed without merging**
