### PR TITLE
Add TvHeadend-Testing with TvHeadend version 3.9.512

### PR DESCRIPTION
**Pull request by jdierkse**
This experimental package can be used to test the latest version of TvHeadend.
It can be installed alongside the regular TvHeadend install.

### CODE REVIEW

**Comment by jdierkse** [comment]
I've just added the 3.9.2334 version to syno.dierkse.nl (including alpine, avoton, armada375 and x64)

**Comment by Smiggel** [comment]
Works excellent. Upgraded and no problems here.

**Comment by steef84** [comment]
Somehow .2334 seems to crash on qoriq at least least 2 times last day for me. Latest DSM5.1. Will revert to older one to see is problem still exist.

**Comment by brugh** [comment]
i have DSM5.0 running on x64 but 2334 fails to start. looking at the start-stop script it stops when it's looking for hdhomerun in /proc/devices which is not there. the previous version ran perfectly, this one needs some tweaking but i dont know what to tweak.

**Comment by jdierkse** [comment]
I am building a new version (3.9.2345) with the HDHomeRun stuff in the startup script removed, as it is now built-in.

**Comment by Vlaves** [comment]
Hello together,
first I like to thank you, jdierkse, for that great package. It is working really good on my synology DS214play.
But I have on question and I don't know if it was already asked. I guess it was, but couldn't find anything.
Would it be possible to have optional use of the ffmpeg delivered with the Synology, at least on the "play"-Models, so we could here use in that case hardware transcoding?

Thanks for any information regarding this and this great package.

Regards
Vlaves

**Comment by akide** [comment]
Hi, I installed jdierkse tvheadend on my DS415play but don't work for me.
I previously installed and uninstalled tvheadend from synocommunity repository but now I can't install any version.
Maybe some file is mistakenly left installed.
Could you tell me which folders tvheadend use and what files should I remove? In this way I could check if anything has been installed and clearing it through winscp.
Thank you

**Comment by ingm4r** [comment]
I also installed tvheadend-testing from jdierkse on my ds 415play. But I've got a lot of continuity errors on the log file when streaming IPTV to clients. On the clients the streams stutter and are full of artefacts. So a way to use the hardware of the Play-versions would be nice.

**Comment by teufelschultz** [comment]
Hello,

Unfortunately I have no idea how I spksrc using the latest version of tvheadend compile for my NAS and pack . Unfortunately can also find any instructions for spksrc . Can any one help me? I need the current version of the DS414 ( arch = armadaxp ) .

LG
Robert

**Comment by schumi2004** [comment]
Running latest version but looks like i found some memory leak. Normal use it's using around 10MB and suddenly after a period of time it goes sky high (110MB) until it's restarted by Monit.

**Comment by samukas** [comment]
Also having lots of problems with the latest version, my Syno becomes unresponsive from outside the network. Not sure which version I should downgrade to, or if there's a new one maybe with a fix?

**Comment by jdierkse** [comment]
Building a new version ATM, 3.9.2479

**Comment by akide** [comment]
Regard to the problem explained in some post above, please could someone tell me which folders tvheadend use and what files should I remove to clear my old installation? In this way I could check if some file is wrongly remained on my NAS.
Thank you.

**Comment by Marty56** [comment]
I do not understand the structure of the website http://syno.dierkse.nl
First of all: It seems that the most recent build are somewhere in the middle of this endless page.
Also it seems that some dumb computer algorithm has generated this site, repeating the same description all over again.
And also reading "simple to use and easy to setup" sounds like trying to make fun of the brave alpha testers using this piece of code.
A change log is referenced but there is not link, so to me this is pretty meaningless.

**Comment by jdierkse** [comment]
@Marty56 you *could* also just use syno.dierkse.nl as a synology package source as described earlier in this thread, you would have known that if you had cared enough to read the thread.
The site has a large selection of different versions of tvheadend-testing, but if you're bother by the layout, you're welcome to build and distribute it all for yourself.

**Comment by Smiggel** [comment]
@jdierkse Too bad there are no thumbs up button github.

**Comment by jdierkse** [comment]
@akide perhaps there is something left in /var/packages/tvheadend-testing?

**Comment by akide** [comment]
@jdierkse I solved it by changing the value in the applications settings/general/trust level from Synology inc and trusted publishers to any publisher.
Now I have another problem :-(
Tvheadend not recognize my usb tuner pctv292e (in dvb inputs/ tv adapters i don't see anything)
The old synocommunity Tvheadend 3.4.27-6 worked fine with this adapter.
Why with this new version doesn't work?

**Comment by Smiggel** [comment]
What is the best way to downgrade? Since I upgraded to the latest version, I have problems with XBMC and TVHeadend. I can not delete recordings anymore and can not watch a live stream anymore. Manually load the older version is the best way to downgrade?

**Comment by schumi2004** [comment]
@Smiggel manual load older version is the way to go yes.
Keep in mind, depending on the version you want to downgrade, is that you maybe need to remove some files for HDHHomerun (if using) and redo config.

**Comment by Smiggel** [comment]
@schumi2004 Seems like I do not have to downgrade after all. 

I was having a problem with streaming to XBMC using OpenElec. Seems there was problem with 5.0.2 and my Pi updated to it. My license was overwritten. I thought it was because of the last TVHeadend update, because it upgraded both the same day. :-)

**Comment by schumi2004** [comment]
Today suddenly my (HDHomerun) adapters are gone. Anyone else seen this before and has a solution to fix it?

**Comment by Smiggel** [comment]
Hmmm, strange. I run the latest build from Dierkse and I haven't got this problem. It runs all pretty stable so far.

**Comment by schumi2004** [comment]
How stable is running TVHeadend on DSM 5.1 (and OSCam if in use) these days?

**Comment by Smiggel** [comment]
@schumi2004 I don't have OSCam. But when it comes to Tvheadend it runs excellent. Never have a problem. Use it daily for recording and live TV. No issues with it at all.

**Comment by nurtext** [comment]
@schumi2004 I'm running Tvheadend 3.9.2043~g0b2e072 (compiled by myself) in combination with Oscam for weeks now.

**Comment by jdierkse** [comment]
I'm running 3.9.2304 from syno.dierkse.nl for quite some time on DSM 5.1
Not a single issue. There are newer versions on syno.dierkse.nl, but I haven't taken the time to upgrade yet.

**Comment by akide** [comment]
@jdierkse Tvheadend not recognize my usb tuner pctv292e (in dvb inputs/ tv adapters i don't see anything)
The old synocommunity Tvheadend 3.4.27-6 worked fine with this adapter.
Why with this new version doesn't work?

**Comment by schumi2004** [comment]
Thanks all, runs perfect in DSM 5.1. But now i wanted to update to latest version and it seems to fail upgrading. Anyone else having the same?

**Comment by Smiggel** [comment]
I have been updating for a long time. Never had a problem. Not sure from what version you are trying to upgrade?

**Comment by schumi2004** [comment]
Version 3.9.2514-1. Trying to get some logging now.

**Comment by Smiggel** [comment]
Running 3.9.2514 here and have no issues...

**Comment by schumi2004** [comment]
naamloos
Can't seem to find proper log also. Any suggestions?

**Comment by Smiggel** [comment]
Hmmm ok. Seems strange.Only thing I can think of is uninstall the separate HDHomerun package from Dierkse and remove the old version of TVHeadend and install the new one. New package has the HDHomerun driver in it. :+1:

**Comment by schumi2004** [comment]
Probably not the correct place but does anyone have webgrabplus running on his Synology ?
Trying to get it running here but doesn't seem to work, i do have mono installed.

**Comment by Smiggel** [comment]
@schumi2004 Nope, sorry. Don't have that running here.

Anyone here running the latest beta version yet?

**Comment by Marty56** [comment]
I had version 3.9.2479 installed which worked somehow (some recordings did not work due to Error 1, what ever this is). I tried to upgrade to latest version, but when starting this version, I got CPU 100% blocked by bzip2 endlessly not stopping. So I had to step back to version 3.9.2479 and lost all settings and had to reenter all MUXs etc..
Still pretty much prototype stuff and also the combination with Kodi cannot be used really productively.

**Comment by Smiggel** [comment]
@marty76 prototype stuff? It's working really awesome. I always upgrade to the latest version that is compiled by Dierkse. I never have an issue with it.

Also it works excellent with Kodi. I use it for 2 years now in combination with first XBMC and now Kodi (Openelec on Raspberry Pi). Never have an issue.

**Comment by beralt** [comment]
Regarding the whole unstable experience: please note that the version being tested here is indeed the unstable version. And while the releases by jdierkse are usually pretty stable, it still uses the unstable version of TVHeadend. 

So when you experience issues you have two options: upgrade to a newer version and hope that your issue was fixed, or downgrade.

**Comment by andersTVH** [comment]
Hi marty56

Your problem relates to the process of upgrading. If you move all your
recordings before upgrading. Then you have solved the issue. The upgrade
process takes a backup of the previous installation including recordings!!
Enjoy 😃

Den torsdag den 19. marts 2015 skrev Marty56 <notifications@github.com>:

> I had version 3.9.2479 installed which worked somehow (some recordings did
> not work due to Error 1, what ever this is). I tried to upgrade to latest
> version, but when starting this version, I got CPU 100% blocked by bzip2
> endlessly not stopping. So I had to step back to version 3.9.2479 and lost
> all settings and had to reenter all MUXs etc..
> Still pretty much prototype stuff and also the combination with Kodi
> cannot be used really productively.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SynoCommunity/spksrc/pull/931#issuecomment-83349671>.
>


-- 

Mvh
Anders Fage-Pedersen

**Comment by Marty56** [comment]
Hi andersTVH,

Thanks for this hint. I will try your tip. 
Do you also have an idea what the recording error "1" means?

regards

Martin

**Comment by andersTVH** [comment]
Hi Martin

No, sorry
Have you tried to Google it?

Regards
Anders

Den 19/03/2015 kl. 18.48 skrev Marty56 <notifications@github.com>:

**Comment by Mr-MarQuez** [comment]
I also posted this in another thread but unfortunately didn't received any feedback i'm trying here.

i'm experiencing some strange problems regarding timeshift on my DS214play (DSM 5.1-5022 Update 4). When I start the tvheadend 3.9.2525-1 service timeshift is working without a problem, but when I then stop live tv and start it again I get an error in the logs that the buffer is full.

DiskStation> tail -f tvheadend.log | grep timeshift
2015-02-22 18:55:45.440 [ DEBUG]:htsp: using timeshift buffer (60 mins)
2015-02-22 18:58:54.370 [ DEBUG]:timeshift: ts 0 remove /volumeUSB1/usbshare/buffer/0/tvh-7
2015-02-22 18:58:54.370 [ DEBUG]:timeshift: ts 0 remove /volumeUSB1/usbshare/buffer/0/tvh-8
2015-02-22 18:58:54.370 [ DEBUG]:timeshift: ts 0 remove /volumeUSB1/usbshare/buffer/0/tvh-9
2015-02-22 18:58:55.842 [ DEBUG]:timeshift: ts 0 remove /volumeUSB1/usbshare/buffer/0/tvh-10
2015-02-22 18:59:20.408 [ DEBUG]:htsp: using timeshift buffer (60 mins)
2015-02-22 18:59:21.353 [ DEBUG]:timeshift: ts 1 buffer full
2015-02-22 19:00:30.684 [ DEBUG]:htsp: using timeshift buffer (60 mins)
2015-02-22 19:00:31.673 [ DEBUG]:timeshift: ts 2 buffer full

My config for timeshift is currently like shown below but i tried already all possibilities which are possible.

{
"enabled": 1,
"ondemand": 0,
"path": "/volumeUSB1/usbshare",
"unlimited_period": 0,
"max_period": 3600,
"unlimited_size": 1,
"max_size": 1808,
"ram_size": 0,
"ram_only": 0
}

Does someone else experience the same problem or am i'm the only one who is experiencing this issue on a DS214play?

**Comment by Mr-MarQuez** [comment]
Issue seems to be fixed in the latest version 3.9.2656-1 :)

**Comment by Marty56** [comment]
@Mr-MarQuez, I cannot confirm this. In my installation the bug is remaining.

Additionally I notice that the EPG is 2 h ahead of time. I guess the operator to compensate summertime shift needs a multiply by "-1".

**Comment by Marty56** [comment]
The EPG was a user error. I had not clicked the EIT check box.

**Comment by Mr-MarQuez** [comment]
@Marty56, I didn't do anything special when I upgraded. So I have no idea why it's working for me but not for you. Does the log tell the same as I posted? Maybe try if a fresh install to see if that helps.

**Comment by schumi2004** [comment]
@jdierkse could you update your package to the latest version (or with atleast this commit in it https://tvheadend.org/projects/tvheadend/repository/revisions/ab258685f4c7f1d0696d7947d07f44119bf19b9b) ?
Or is spksrc mainstream now?

**Comment by jdierkse** [comment]
I'll update the repo today.


On Sun, 10 May 2015 13:22:51 +0200, schumi2004 <notifications@github.com>  
wrote:

>
> @jdierkse could you update your package to the latest version (or with  
> atleast this commit in it  
> https://tvheadend.org/projects/tvheadend/repository/>revisions/ab258685f4c7f1d0696d7947d07f44119bf19b9b)  
> ?
> Or is spksrc mainstream now?
>
> —
> Reply to this email directly or view it on GitHub.



--

**Comment by Marty56** [comment]
Hi 

did anyone tried tvheadend with the latest Synology DSM version 5.2?

**Comment by Smiggel** [comment]
Yep. Runs excellent. No problems here.

**Comment by Marty56** [comment]
@Smiggel: Thanks for the reply. So I will now dare to update. Keeping my fingers crossed

**Comment by tvheadendisnice** [comment]
I'll give the update 5.2 a go as well - will let you know

**Comment by tvheadendisnice** [comment]
Running on DSM 5.2 now - Seems fine! on Syno DS214+ - works fine via xbmc for instance

**Comment by Marty56** [comment]
Still running 2656. Also this version is running fine on DSM 5.2

**Comment by MortUK** [comment]
Is there a build for the latest Synology Ds215j.?

it uses the Arm 375 processor.. I've tried the build for the Armada370 and armadaxp but my NAS refuses it.. :o(

**Comment by helio58** [comment]
Hi I m running a ds415play have tvheadend 3.9.2851-1 just updated.
Notice that I m not able to stream via browser (safari) Is there a way to revert to 3.9.2851?
Was not hable via paketcenter on sinology.
Thanks

**Comment by CircleCode** [comment]
@jdierkse do you work on any public repo to generate your builds (I had a look at jdierkse/spksrc but it doesn't seem updated since 7 months while you have updated your build not so long ago)

**Comment by m4tt075** [comment]
@jdierkse Related question: It seems the THV team (perexg to be specific) have created new branches now, 4.0.x for "semi-stable / beta" versions supposed to lead to a new stable version and 4.1.x as "master"/"testing" for ongoing development. Any chance you can build the semi-stable 4.0.x versions and put them on your syno.dierkse.nl server too?

**Comment by jdierkse** [comment]
@MortUK, @m4tt075 on it.
@helio58 streaming from the browser will always use ffmpeg on the NAS to transcode the live stream, probably this is not working well enough on your NAS. I'm currently not aware of any options to turn off transcoding in the browser.
@CircleCode I'll try to update my repo after successfully building 4.1.x, but unfortunately I'm very busy.

**Comment by CircleCode** [comment]
@jdierkse no problem, I was just wondering, but the fact that you're working on a 4.1 build is a very good news (and the fact that you can eventually upgrade your public repo with this is another great news).
another question : how do you determine your build numbers? (in fact, my first question about public repo was to know exactly which commit is included in each of your releases: I was not able to find it based on your build numbers so I wanted to see which commit is targeted in your spksrc repo, but without ay success since it was not up to date)

Ah, and… Thanks for this amazing work :-)

**Comment by jdierkse** [comment]
@CircleCode I use https://tvheadend.org/builds/tvheadend to detremine the GIT revision and build number.

**Comment by CircleCode** [comment]
@jdierkse so just to be sure, your build number is the build id from https://tvheadend.org/builds/tvheadend, right?

**Comment by jdierkse** [comment]
@CircleCode No, I use the version number as version tag for the tvheadend builds. (latest is 4.1.95)

**Comment by CircleCode** [comment]
@jdierkse ok, thanks (and sorry for the noise)

**Comment by jdierkse** [comment]
@MortUK @m4tt075 @CircleCode: 4.1.95 is up on syno.dierkse.nl, also for armada375.

**Comment by helio58** [comment]
@jdierkse , just update to 4.1.95 working great even browser streaming and low cpu THANKS

**Comment by m4tt075** [comment]
@jdierkse
Excellent. Having tried to cross-compile TVH myself and failing miserably I sincerely appreciate what you are doing for us Synology users out there! Thank You!  :-)

**Comment by Smiggel** [comment]
Upgraded to 4.1.95 but it doesn't seem to work well with Kodi now. Kodi tvheadend addon does no longer index the tv channels, epg etc.

Anyone else here who has this problem?

**Comment by Marty56** [comment]
Hi Smiggel,
I am still on version 3.x. 
In the change log it was reported that
1. the UI has changed
2. plus the Pause bug is fixed.

Question: I found the UI in version 3.x really terrible and very convoluted and only by chance I got it working already after I was already ready to give up (took about 5-6 hours to figure it out).
So I am afraid, since the update will not keep my configuration, that I will again fail with the configuration. What is your experience on this?

Also with respect to 2. Is this working now in combination with Kodi 14.2 ?

Cheers Martin

**Comment by Smiggel** [comment]
@Marty56 

The ui works fine for me. I use 4.1.95 and it runs just fine. No problems anymore. Use it in combination with Kodi 5.0 beta. Only problem I had after upgrading to 4.1.95 is that Kodi would not index the channels anymore. I had to remove the tv database and let Kodi make a new one. After that it works fine.

**Comment by Marty56** [comment]
@Smiggel 
Thanks for the reply.
If the Pause bug is really working, I will do the hustle of upgrading and redoing the configuration work.
Could you please confirm also this point.
By working I mean that a Pause let's say of  about 10 minutes is working.

Thank you for your support.

**Comment by Smiggel** [comment]
@marty56 i am watching tv now for about 15 minutes after having paused the TV for about 15 minutes. It seems the bug finally fixed. Before it did not work for me either. Now it does.

**Comment by Marty56** [comment]
@Smiggel,
Thanks for trying it and providing this feedback.

**Comment by wellus** [comment]
Has anyone seen this issue?
On DSM 5.1 5055
TVheadend-Testing hangs, i then proceed to stop the app and start it again.  In the logs i get:
"9981 - HTTP server (web interface) 9982 - HTSP server (Streaming protocol) are currently in use."

I have left it for hours to try and see if there is a service trying to kill ports 9981 9982 but no matter what i do the the only fix is to restart DSM.

I am running Xpenology 5.1 5055
I have amended the security details to accept all package certs.

Any ideas?

Thanks
N

**Comment by nurtext** [comment]
@jdierkse Me again ;) Could you please update your spksrc-repository with working code for tvheadend-testing 4.x releases? Thanks in advace :)

**Comment by nurtext** [comment]
Can't get tvheadend to compile without propper patches:
```
src/service.c: In function 'service_destroy':
src/service.c:860: error: expected expression before 'else'

src/service.c: In function 'service_create0':
src/service.c:916: error: expected expression before 'else'

I was hoping someone could provide them…

**Comment by helio58** [comment]
Using 4.1.95-1 Live tv works well with kodi and (I use iOS) TvhClient.
I m having problem with the recordings. Using mkv.

Not all records but some don't play in the TvhClient, In kodi works.But the ones that don't work in TvhClient i m experience same stuttering now and then.

Recording in ts works great (why I use mkv is that I get the subtitles)

**Comment by nurtext** [comment]
@jdierkse I almost got it. I fixed a few bugs in tvheadend regarding cross-compilation and made a PR for the master-tree as well as release/4.0. They'll make your cc-patches for `TAILQ_EMPTY` directives and missing curly bracket for `if/else` obsolete. Hope they get accepted. 

One last thing I can't get managed: How are you dealing with epoll in tvhpoll.c?

**Comment by jdierkse** [comment]
@nurtext I'm having some issue with committing my changes, as my git repo is out of date, and I haven't had the time yet to update.
As for the tvhpoll.c; ppc853x and qoriq don't have epoll_create1, so for these arch's I've added patches that replace ```if ((fd = epoll_create1(EPOLL_CLOEXEC)) < 0) {``` to ```if ((fd = epoll_create(1)) < 0) {```

**Comment by nurtext** [comment]
@jdierkse Thanks! Seems that bromolow doesn't have epoll_create1 too. FYI perexg from tvheadend sorted out that at least some of the TAILQ macros are wrong, let's hope we can fix as many issues to use less patches during cross compilation…

**Comment by jdierkse** [comment]
@nurtext Thanks, it's indeed nice to have less patches specifically for our Synology configs!
As for Bromolow, I don't have any poll patch for this arch, and it is build successfully. What's the compilation error you're getting?

**Comment by nurtext** [comment]
@jdierkse 
```
CC              src/tvhpoll.o
src/tvhpoll.c: In function 'tvhpoll_create':
src/tvhpoll.c:73: warning: implicit declaration of function 'epoll_create1'
src/tvhpoll.c:73: error: 'EPOLL_CLOEXEC' undeclared (first use in this function)
src/tvhpoll.c:73: error: (Each undeclared identifier is reported only once
src/tvhpoll.c:73: error: for each function it appears in.)
make[3]: *** [/home/vagrant/spksrc/spk/tvheadend/work-bromolow/tvheadend-4.0.5/build.linux/src/tvhpoll.o] Fehler 1
make[3]: Leaving directory `/home/vagrant/spksrc/spk/tvheadend/work-bromolow/tvheadend-4.0.5'
make[2]: *** [compile_target] Fehler 2
make[2]: Leaving directory `/home/vagrant/spksrc/cross/tvheadend'
make[1]: *** [depend_target] Fehler 2
make[1]: Leaving directory `/home/vagrant/spksrc/spk/tvheadend'
make: [arch-bromolow] Fehler 2 (ignoriert)
```

**Comment by jdierkse** [comment]
@nurtext perhaps we're not using the same version of the cross compilers or libraries, are you compiling for DSM-5.1?

**Comment by nurtext** [comment]
@jdierkse Tried to cross compile against 4.3, 5.0 and 5.1 as well. Same result. Using latest spksrc (master)

**Comment by jdierkse** [comment]
@nurtext I'm updating my spksrc now, I'll see whether I'll run into the same issues. If so we'll need to add the same patch to bromolow.
Once I've updated my spksrc, I'll also update tvheadend-testing in the spksrc repo.

**Comment by nurtext** [comment]
@jdierkse Okay. I'll keep you posted in regards of the tvheadend-patches I've submitted.

**Comment by jdierkse** [comment]
@nurtext I've updated my repo (finally... o_O)
I'm now attempting to re-build 4.1.163 with this new repo-state, and I'll make changes where necessary and commit them asap.

**Comment by freddysmith1** [comment]
this might be a dumb question but just got a hdhomerun connect  hooked it up to ds415+ with tvheadend    it can see the two adaptors but doesnt stream anything...  did i miss something setting it up or?    using dsm 5.2 update 2

**Comment by Smiggel** [comment]
You have to setup your television provider and let it scan for services. Then you can map the channels.

**Comment by freddysmith1** [comment]
@smiggel  it doesnt find any channels to map    playtv works fine  just not hdhomerun

**Comment by Smiggel** [comment]
@freddysmith1 dus you setup your tv provider in tv headend?

**Comment by freddysmith1** [comment]
@smiggel   all good mate  finally got it workin  i had to  enable disable it 10 times then it started working

**Comment by Smiggel** [comment]
@freddysmith1 Good to hear. Good luck.

**Comment by MZman** [comment]
@jdierkse Hi i have problem with your new package, i can not run it, so i must roll back to the old version

**Comment by freddysmith1** [comment]
@MZman  your not getting a  could not run error aswell when you try to start the service in synology app store?

**Comment by MZman** [comment]
@freddysmith1 i can install it but if i want to run in the package store, i get an error it stops

**Comment by jdierkse** [comment]
@MZman can you please post the error that's being reported in the tvheadend.log file?

**Comment by MZman** [comment]
@jdierkse I have no log file.
All I get is feedback as a pop-up, the folder is no trace of the log.

**Comment by MZman** [comment]
@jdierkse  i have test it again but no log file

**Comment by freddysmith1** [comment]
im just trying to extract the log file from mine  i also have the same problem

**Comment by freddysmith1** [comment]
@jdierkse   just tried getting my log and the exact same  no errors at all

**Comment by Smiggel** [comment]
Same issue here. I did not see the posts here. I just updated and now I can not start the package anymore. Log is empty.

**Comment by MZman** [comment]
Change the info file in /var/packages/tvheadend-testing/ give a lower version number and install the the version

**Comment by m4tt075** [comment]
Yep. Seems 4.1.304 wasn't stable when run as a service. See: [#hts log] (http://colabti.org/irclogger/irclogger_log/hts?date=2015-06-25)
Should be fixed in current master, i.e. from 4.1.305 on. Better to wait for newer builds.

**Comment by Smiggel** [comment]
@MZman Where do i find this file exactly? I don't see it in the location you pointed out to.

**Comment by jdierkse** [comment]
Building 4.1.309 ATM.

**Comment by MZman** [comment]
@Smiggel Go to /var/packages/tvheadend-testing/INFO with vi
And change
version="4.1.245-1"

**Comment by m4tt075** [comment]
@jdierkse 
May I ask whether you have any plans to cross-compile the 4.0.x "beta" versions to make them more accessible to Synology users? I'm asking because the 4.0.x versions are supposed to become the new "stable", which would then replace the old 3.4 in the official SynoCommunity repo I suppose.
Right now the 4.0.x betas and 4.1.x alphas are still relatively close, so it is probably not so much of an issue, but as 4.1 and 4.0 are diverging it might be good for the TVH development team (perexg essentially) to have some "beta" testers too.

I know this might be additional hassle for you but wanted to ask. Grateful for what you are doing already! Either way...

**Comment by jdierkse** [comment]
@m4tt075 That's a good point, I'll look into this this weekend. I might have to make two separate packages though to offer a choice between 4.0 and 4.1.

**Comment by m4tt075** [comment]
@jdierkse That would be absolutely brilliant! We could run testing and betas in parallel, having fun AND keeping the wifes happy...  :-)

**Comment by Smiggel** [comment]
@MZman Thanks for the tip! It worked. I was able to install the latest the previous version now the was working ok, except for the EPG.

**Comment by Dr-Bean** [comment]
@jdierkse Can you open a new PR to update the current package (and possibly add a `-testing` package, seeing where the discussion above is going) at some point? 
This PR was closed automatically because of the move to the `master` branch, but we probably don't want to see that continuing in perpetuity ;)

**Comment by Smiggel** [comment]
4.1.309 can be started again. That version works.

**Comment by Vlaves** [comment]
@jdierkse: Sometimes when I update the Package it is not able to login in again. Then I need to reinstall. This only happens if I add at the Access Control an entry with "*" which could be used to also authenticate to tvheadend without username and password. Is it possible while doing an update to save the "authentication" and "password" folders and to restore them, after the update? I don't know if this could help. Thanks for ur support here :)

**Comment by freddysmith1** [comment]
anyone having trouble with latest testing version  .322   lost a tv channel  removed the network and readded it  now it finds no channels,  works in version before this

**Comment by jdierkse** [comment]
@m4tt075 I've added the TVHeadend-4.0 package to my repo.
This is built from the 4.0 branch, and is less bleeding-edge than the -testing package.
I have not tested this package in any way, but I expect it to work just fine.

**Comment by mbisanz** [comment]
@freddysmith1 had the same issue with 4.1.322, trying the 4.0 branch now. Thanks,@jdierkse, for your effort.

**Comment by m4tt075** [comment]
@jdierkse Thanks so much! Will test soon...
There might be an issue with the tagging / versioning though. Looks different in the 4.0.x and 4.1.x branches. See [here](https://github.com/tvheadend/tvheadend/releases). Am not sure whether your 4.0.1 spk corresponds to the actual 4.0.1 or the (most recent) 4.0.5 beta.

**Comment by freddysmith1** [comment]
just installed  tvheadend 4.0  and it wont run on synology ds415+ 
heres the log file 
http://pastebin.com/MiBkAvUA

**Comment by jdierkse** [comment]
@m4tt075, It's actually 4.0.5 plus some extra changes, sorry about that, forgot to update the version number.
@freddysmith1, It looks like a permissions issue, can you check that the tvheadend-4.0 user exists, and owns the /var/packages/tvheadend-4.0/target location and everything in it?

**Comment by mattiasdh** [comment]
@freddysmith1 I can confirm this on DS414 (armadaxp architecture), same [  ERROR]:spawn: /bin/tar: ./accesscontrol/1: Cannot open: Permission denied
Tried default (blank "admin") login and pass, and setting my own - same error. 401 Unauthorized on login screen..
@jdierkse - my linux skills are way too limited for that, can I test another version where this error might be fixed? If so, which one?
Thanks in advance!

**Comment by freddysmith1** [comment]
Glad to see im not the only one with this problem,  ive tried afew different things but couldnt work it out  @mattiasdh   @jdierkse

**Comment by m4tt075** [comment]
@jdierkse No need to be sorry for anything. I have no clue how you guys are managing all this stuff next to your day jobs. Many thanks for clarifying!

@freddysmith1 @mattiasdh Can only test on the weekend, but if you want you can try the following:

ssh into your DS. Once you are in, enter
> cat /etc/group

If there is a row starting with "tvheadend-4.0" in the output, the correct user should exist, if not it doesn't -> Report back
If there is a row starting with "tvheadend-testing" instead, please let us know whether you installed the tvheadened-testing package prior or in addition to tvheadend-4.0 and report this here too. Then, enter
> stat /var/packages/tvheadend-4.0/target/

Check the bracket after "Uid" to see who owns this directory (should be "tvheadend-4.0") -> Report back what you see

> stat /var/packages/tvheadend-4.0/target/*

will then give you the owners of the subdirectories. Please report too.

This should answer @jdierkse's questions...

**Comment by m4tt075** [comment]
@jdierkse Couldn't wait so ran a quick(!) test tonight:
Same as with my predecessors.
The user "tvheadend-4.0" is created and appears in /etc/group, /etc/passwd, but *not* in /etc/shadow (unlike "tvheadend-testing", which does)
/var/packages/tvheadend-4.0/target/ is owned by "root", not "tvheadend-4.0"
The ownership of the  "var" subdirectory is correct ("tvheadend-4.0"), all other subdirectories are owned by "root" again.
Not sure but the "." in the username seems to screw up "chown" commands as it interprets the "." like ":" to separate owner from group. But not familiar with busybox to be honest.

**Comment by jdierkse** [comment]
@m4tt075 I think your point on the username might be valid.
I've started a new build of the 4.0.5 version, and changed the user to tvheadend-4_0

**Comment by Diaoul** [comment]
Please reopen a PR against master so we can discuss the code quality. This is not a forum but a bug tracker.
Also in that new PR, name the user tvheadend-testing for consistency and avoid hardcoding the version number in username.
Further discussion will be done there. I lock the PR.

**Pull request closed without merging**
