### PR TITLE
Update dnscrypt-proxy to 2.0.19

### PR DESCRIPTION
**Pull request by publicarray**
_Motivation:_ There was an issue when wget could fail and write a 0 byte file. wget could fail when the device had dnscrypt-proxy configured as it's main DNS without fallback. During a package upgrade/reinstall wget could not resolve the domain name for `raw.githubusercontent.com`
Also remove an unnecessary chmod (it's a no op)

_Linked issues:_ Fixes https://github.com/SynoCommunity/spksrc/issues/3468#issuecomment-431942059

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
Wouldn't be preferable to download file from Makefile and include it once and for all users in package itself...

**Comment by publicarray** [comment]
I not fond of downloading any file from within make. Having the file in git gives us version control and create deterministic builds. I've includes the files in the package here: https://github.com/SynoCommunity/spksrc/tree/master/spk/dnscrypt-proxy/src/offline-cache

**Comment by ymartin59** [comment]
@publicarray Does it make sense to copy that files from original upstream release (https://github.com/jedisct1/dnscrypt-proxy/blob/master/utils/generate-domains-blacklists/) ?
May you please fix "cross/dnscrypt-proxy" Makefile and digests to include package name in downloaded archive to avoid collision. You may set `PKG_DIST_FILE = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)`

**Comment by publicarray** [comment]
@ymartin59 yes it does sorry I missed that they are included in the git archive. I'm sill leaving the offline-cache folder for the server lists. Those 2 files (`public-resolvers.md` and `public-resolvers.md.minisig`) are automatically updated when `dnscrypt-proxy` considers the files out of date.

**Comment by publicarray** [comment]
@ymartin59 Sorry for the mess above. Do you think this can finally be published? 🙏

**Comment by ymartin59** [comment]
Hello. Yes I think so. But at the moment, I work on python3+borgbackup+homeassistant+armada37xx...

**Comment by publicarray** [comment]
Thanks no worries

**Comment by ymartin59** [comment]
@publicarray Publish is pending because of troubles with spkreo. Your package is really complex but you did a great improvement with go compilation preventing multiple downloads.

A proposal for next update: try to reuse https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.service.privilege-startasroot with additional Makefile variables - even without SERVICE_EXE for start-stop-daemon script: https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.service.mk#L156 maybe with SERVICE_USER = root as I guess there is no benefit to create non-privilege user for dnscrypt-proxy

**Comment by publicarray** [comment]
> Your package is really complex
No objections from me. At the start I was not aware of the subtle differences between the DSM and RSM. Also I wanted the package to work with dnsmasq (DHCP server). Next add a GUI and help files... and here we are.

>  guess there is no benefit to create non-privilege user for dnscrypt-proxy

It is true that dnscrypt-proxy starts as root because it binds to a privileged port (unless port 53 is already in use). After the files are read and the sockets are opened the process (by the default that I have set) will drop privilege to the `${EFF_USER}` user.

**Comment by publicarray** [comment]
@ymartin59 Isn't having the `SERVICE_EXE` variable the trigger to get the `spksrc.service.privilege-startasroot` permission file?

**Comment by ymartin59** [comment]
Correct but it replaces start-stop-status script too, so that SERVICE_EXE is passed as argument to busybox start-stop-daemon

**Comment by publicarray** [comment]
🎉  Thank you for publishing the package! 🎉

---

I gave it a go but the service can't start. It exits with something like `start-stop-daemon can not be found`

```diff
- CONF_DIR = src/conf
+ SERVICE_EXE = $${SYNOPKG_PKGDEST}/bin/dnscrypt-proxy
+ SERVICE_OPTIONS = --config $${SYNOPKG_PKGDEST}/var/dnscrypt-proxy.toml --pidfile $${PID_FILE}
```

**Pull request merged**
