### PR TITLE
Update go to 1.23.3

### PR DESCRIPTION
**Pull request by IngmarStein**
## Description

Changelog here: https://go.dev/doc/devel/release

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by IngmarStein** [comment]
CC @hgy59 as you've previously bumped Go in #6207

**Comment by hgy59** [comment]
@IngmarStein please do not upgrade minio.
There is much more to do since it has mandatory changes and needs a package migration concept. (see #5549 and #5555)

If minio fails to build with go 1.23, we must solve the minio migration first and hold back the go update (or update go to 1.22.7 only).

cc @fgma

**Comment by IngmarStein** [comment]
@hgy59 I see. Maybe the old minio build can be patched for go 1.23 like this: https://github.com/bettercap/bettercap/pull/1107

**Comment by hgy59** [comment]
> @hgy59 I see. Maybe the old minio build can be patched for go 1.23 like this: [bettercap/bettercap#1107](https://github.com/bettercap/bettercap/pull/1107)

I don't see any need for Go 1.23 yet, but the completion of #5555 is long overdue.

**Comment by IngmarStein** [comment]
@hgy59 I've updated this PR to patch minio to build with go 1.23 instead of updating it. The patch is the result of running `go get -u golang.org/x/net && go mod tidy`. Up to you if you want to wait for #5555 instead.

**Comment by IngmarStein** [comment]
This PR has been updated for Go 1.23.2.

**Comment by IngmarStein** [comment]
This PR has been updated for Go 1.23.3.

**Comment by hgy59** [comment]
@IngmarStein please help to bring #5555 forward.
We do not want to update go before #5555 is solved.

**Pull request closed without merging**
