### PR TITLE
SiCKRAGE - Generic Service approach

### PR DESCRIPTION
**Pull request by Safihre**
### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by Safihre** [comment]
For backwards compatibility I guess these (`sonarr/sickrage/couchpotato`) should all be `sc-media`.. 
Still kinda strange, since they clearly couple to `sc-download` packages.
I will change this.

**Comment by ymartin59** [comment]
I also wonder what are expected usage of these two distinct groups `sc-media` and `sc-download`. A quick usage inventory in packages should help to guess a policy and then fix those that do not match.

**Comment by ymartin59** [comment]
I have to submit a french translation too

**Comment by Safihre** [comment]
It seems `sc-media` was assigned to packages doing something with media files, regardless if they came from download providers.
It's too late to change now, because if previous version of any of these packages (Sonarr/CouchPotato/Sickrage/etc) was already installed, switching to `sc-download` would not allow these packages to access the files they manages before anymore. Bit annoying and not so user friendly situation, both cases actually..

**Comment by Safihre** [comment]
Added `sickbeard-custom` to this one. It's 98% the identical code.
Minus the `requirements` installation of SickRage that is not needed for SickBeard.

**Pull request merged**
