### PR TITLE
Fix make exit status

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

This PR address the issue with the exit code on error.  
1. There are corner-cases where builds does not exit with proper exit error signal. After further looking into it this appear to be due to the tee pipe where the exit code is from the later command. The way to properly handle this is through the `${PIPESTATUS[0]}` using `bash` shell variable which provides the output from the first command from the pipe sequence.
2. In extra to that, all instances of `-@$(MAKE)` have been replaced with `@$(MAKE)` to allow passing errors
3. Additional github-action success test is being used to confirm that the resulting package has been created or not.

Part of #5095 PR split.

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [ ] New Package
- [ ] Package update
- [x] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
@hgy59 for your review.  This is a follow-up of our discussion at https://github.com/SynoCommunity/spksrc/pull/5095#discussion_r806118186 where I ended-up finding a method to fix the underlying issue.

**Review by hgy59 — APPROVED** [review]
LGTM
and +1 for splitting into dedicated PR.

**Comment by th0ma7** [comment]
Thnx for your review, much appreciated, this ended-up being way too intrusive otherwise.

**Comment by hgy59** [comment]
@th0ma7 just found a side effect of this PR.
when you run `make all-supported` the build is now cancelled at the first UNSUPPORTED_ARCH.
Do you have any idea how to ingore errors when running `make all-supported`?

- an UNSUPPORTED_ARCH must terminate the build for the current arch, but the build must continue with the next arch.

**Comment by th0ma7** [comment]
Yup, good catch.  I'll investigate.

**Pull request merged**
