### PR TITLE
cloudflared: fix package

### PR DESCRIPTION
**Pull request by hgy59**
## Description

follow up to #5734
- remove DSM_UI_DIR to avoid creation of unused icon files
- escape () in package description

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix

### CODE REVIEW

**Comment by hgy59** [comment]
@karasevm I wanted to publish #5734, but then I found some issues.

As of the name _cloudflared_ (d like daemon) I found that this package runs a service.
Is cloudflared a service running on port 7844?

If so, we must define the SERVICE_PORT for this package.

**Comment by hgy59** [comment]
@karasevm to document my suggested chanes I added a dedicated commit.

additionally we have to document the used port (7844) on our wiki page, to avoid use of this port by new packages (see https://github.com/SynoCommunity/spksrc/wiki/SynoCommunity-Used-Ports).

**Comment by hgy59** [comment]
> 7844 is the outbound destination port. The main idea behind tunnels is that you don't need to receive any incoming connections, which allows it to work in networks with firewalls and NATs.

@karasevm thanks for clarification

> - DNS-DoH proxy that is disabled by default but, if explicitly enabled without custom port specified, will try to use port 53

As port 53 is a privileged one, this needs root to be executed, so keep disabled by default.

**Comment by karasevm** [comment]
@hgy59 The token is just a base64 encoded JSON with account number, tunnel UUID, and tunnel secret. I'm not sure if the length varies, in my case it is always 185 chars. I suppose setting the `minLength` to 150 and checking that it is valid base64 should cover most cases.

```json
"validator": {
    "minLength": 150,
    "regex": {
        "expr": "/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=|[A-Za-z0-9+\/]{4})$/",
        "errorText": "Not a valid token."
    }
}
```

**Comment by hgy59** [comment]
@karasevm I see some warnings and errors in cloudflared.log

```
2023-06-01T15:22:04Z WRN The user running cloudflared process has a GID (group ID) that is not within ping_group_range. You might need to add that user to a group within that range, or instead update the range to encompass a group the user is already in by modifying /proc/sys/net/ipv4/ping_group_range. Otherwise cloudflared will not be able to ping this network error="Group ID 207066 is not between ping group 1 to 0"
2023-06-01T15:22:04Z WRN ICMP proxy feature is disabled error="cannot create ICMPv4 proxy: Group ID 207066 is not between ping group 1 to 0 nor ICMPv6 proxy: socket: permission denied"
...
2023/06/01 17:22:04 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 832 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.
```

As I see those on DSM 6 and DSM 7 I suppose it simply can be ignored.
Or do we need further investigation?

**Pull request merged**
