### PR TITLE
cleanup vim

### LINKED ISSUE #3910: Update vim package
Packaged vim version is quite old. Any chance to update it to latest version and promote the package from beta to main channel?

### PR DESCRIPTION
**Pull request by hgy59**
_Motivation:_  Catch up on cleanup - the great update was done by @lwfitzgerald in #4030
_Linked issues:_  closes #3910

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully (need to sign some vim packages to install from the synocommunity repo).
- [x] New installation of package completed successfully

### Remarks
- remove beta (#3910)
- use generic installer and symlink creation
- include links to vimdiff, view and more
- move CHANELOG to spk-makefile

### CODE REVIEW

**Review by lwfitzgerald — APPROVED** [review]

**Comment by Hochiss** [comment]
Dears, firstly apologize if off-topic, but i really want to clean vim @  DS412+. because I found multiple versions there and alot settings are not justified.

Just I installed vim 8.2 via SynoCommunity source, found at /volume1/@appstore/vim, but it has not replaced my old vim at /usr/bin (which vim), and I found vim at /usr/share/vim/:
`vim/74` no bin inside
`vimfiles`

I have been searching for e.g. `/etc/vim/vimrc`, but I found only `/etc/vimrc` (not standard as e.g. in ubuntu), yet `vimrc` can be found `etc.defaults`, all these seems quite chaotic...

would you please help to cleanup vim, thanks! /BR

**Comment by hgy59** [comment]
@Hochiss no synocommunity package is designed to replace any software that is part of the DSM (i.e. the software provided by synology).
- with `which vim` you will always get the vim of DSM in `/usr/bin/vim` (except for very old DSM versions that came without vim)
- any DSM thirdparty package that wants to link executables to a folder in the `$PATH` must use /usr/local/bin or /usr/local/sbin for the links. As `/usr/bin` is located prior than /usr/local/bin in `$PATH` (similar for sbin) thirdparty commands without distinct names will not be executed without full qualified path.
- the current synocommunity vim package creates an additional link `/usr/local/bin/vim82` and you can use this one.
  ```
  $ ls -l $(which vim82)
  lrwxrwxrwx 1 root root 35 Nov  9 18:26 /usr/local/bin/vim82 -> /volume1/@appstore/vim/bin/vim-utf8
  ```

@Hochiss please tell us whether there are still troubles with the Vim 8.2-3 package to find its resources (`vimfiles` or `vimrc` ?).

**Comment by hgy59** [comment]
## HINT
You find all created links in the package install logfile at /var/packages/vim/target/var/vim_install.log.

```
===> Step postinst. USER= GROUP= SHARE_PATH=
Invoke service_create_links
create link: /usr/local/bin/view -> /volume1/@appstore/vim/bin/view
create link: /usr/local/bin/vimdiff -> /volume1/@appstore/vim/bin/vimdiff
create link: /usr/local/bin/rvim -> /volume1/@appstore/vim/bin/rvim
create link: /usr/local/bin/rview -> /volume1/@appstore/vim/bin/rview
create link: /usr/local/bin/vimtutor -> /volume1/@appstore/vim/bin/vimtutor
create link: /usr/local/bin/vim -> /volume1/@appstore/vim/bin/vim-utf8
create link: /usr/local/bin/vim82 -> /volume1/@appstore/vim/bin/vim-utf8
Mon Nov  9 18:27:00 CET 2020
===> Step postupgrade. USER= GROUP= SHARE_PATH=
```

**Comment by Hochiss** [comment]
> @Hochiss no synocommunity package is designed to replace any software that is part of the DSM (i.e. the software provided by synology).

`vim` is N/A in SynoNAS originally.

> ...
> @Hochiss please tell us whether there are still troubles with the Vim 8.2-3 package to find its resources (`vimfiles` or `vimrc` ?).

@hgy59: many thanks for your fast response. Indeed vim82 is linked as you mentioned. but `which vi ` and `which vim` still linked to `/usr/bin/vim`, there `vim` is not linked to anywhere(i.e. standalone)! 

Yes still problem with the settings: ( PS: install.log shows nothing on env/settings)

- I cannot find system `vimrc`, which should be found at `/etc/vim/vimrc` right?, and
- I guess $VIMRUNTIME should also in `env`? 
- How does `vim82` (via SynoCommunity  installed) organize these settings? and 
- anything needs user to setup  `~/.vimrc` & `~/vim/` e.g. the syntax   & color? 

Not sure what Synology's '/etc.defaults/vimrc` does anything.

**Comment by hgy59** [comment]
> `vim` is N/A in SynoNAS originally.

Sorry, but you are wrong with this. As `/bin/vim` is an executable program and not a link, this is installed in the base system of your NAS. It is not from a Synology nor a from third party installable package.

For the other open questions I am sorry, but I have no idea about vim and its resource management. 
This package is for advanced users only who can solve such issues by their own - or maybe can help to approve the package.

Maybe  @lwfitzgerald can help further, as he enhanced the vim package in  #4030.

**Comment by lwfitzgerald** [comment]
Hi @Hochiss, I think your questions can be answered by:

1. Looking at `vim82 --version`:
    ```
     system vimrc file: "$VIM/vimrc"
       user vimrc file: "$HOME/.vimrc"
   2nd user vimrc file: "~/.vim/vimrc"
        user exrc file: "$HOME/.exrc"
         defaults file: "$VIMRUNTIME/defaults.vim"
    fall-back for $VIM: "/var/packages/vim/target/share/vim"
   ```
2. Starting `vim82` and using `:echo $var` to print the variables:
    ```
    :echo $VIM
    /var/packages/vim/target/share/vim
    ```
    ```
    :echo $VIMRUNTIME
    /var/packages/vim/target/share/vim/vim82
    ```

**Pull request merged**
