### PR TITLE
Fix tt-rss re-installation

### PR DESCRIPTION
**Pull request by saschpe**
_Motivation:_ When the package is re-installed the installer shouldn't choke on
already existing MariaDB user and database. Instead those should be
re-used to safe the user from dumping and re-importing their tables.

### Checklist
- [] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by saschpe** [comment]
ping

**Comment by Safihre** [comment]
@saschpe I have no clue why nobody looked at this! Are you still interested in helping with this?
What platforms did you test this on? DSM5 and/or 6?

**Comment by saschpe** [comment]
6

**Comment by saschpe** [comment]
I moved to Docker meanwhile...

**Pull request closed without merging**
