### PR TITLE
synocli-file: add pixz

### PR DESCRIPTION
**Pull request by dotysan**
Starting over from scratch after I completely bungled #6075.

### CODE REVIEW

**Comment by dotysan** [comment]
Not sure what I'm doing wrong here. Tried disabling hi3535-6.2.4 with:
```
UNSUPPORTED_ARCHS = $(ARMv7L_ARCHS)
```
to no avail.

**Comment by hgy59** [comment]
> Not sure what I'm doing wrong here. Tried disabling hi3535-6.2.4 with:
> 
> ```
> UNSUPPORTED_ARCHS = $(ARMv7L_ARCHS)
> ```
> 
> to no avail.

don't worry about ARMv7L_ARCHS.
it fails to build `cross/fd_8.7.0` due to newer rust version (see #6145).

**Comment by hgy59** [comment]
@dotysan my review is embedded in the two commits...
A final commit to remove `native/autoconf` is ready.

Still pending is the question whether we should use a newer code base for pixz, referenced by git commit hash.
If you are ok with the official version 1.0.7, we should remove the commented variant in cross/pixz/Makefile.

(or we can wait for an answer to your question in https://github.com/vasi/pixz/issues/116)

**Comment by hgy59** [comment]
@dotysan I have now merged you PR into #6288.

I don't think we get https://github.com/vasi/pixz/issues/116 answered, so soon an update of synocli-file with your work will be ready.

I took eveyting except the obsolete `native/autoconf`.

**Pull request closed without merging**
