### PR TITLE
ffmpeg dsm6 fixes and misc updates

### LINKED ISSUE #5710: FFmpeg 4: "Exited with code 1" on Jellyfin transcode
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

ffmpeg 4.4.3

### Package Version

4.4.3-48

### Device Model

VirtualDSM (DS916+)

### Device Architecture

x86_64

### Firmware Version

6.2.4-25556 Update 6

### What happened?

With a fresh install of ffmpeg 4.4.3 and Jellyfin 10.8.10, on attempting to stream a video, I get the following error:

```
FFmpeg exited with code 1
```

### Reproduction steps

1. Install ffmpeg 4.4.3
2. Install Jellyfin 10.8.10
3. Login and setup media library
4. Play video in browser

### Install Log

```log
N/A
```

### Service Log

```log
Jellyfin service log:

[19:24:38] [ERR] [13] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
[19:24:38] [ERR] [25] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /videos/b2316185-4e85-b991-8357-548394a0935b/hls1/main/0.ts.
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Int64 runtimeTicks, Int64 actualSegmentLengthTicks, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
   at lambda_method1454(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### Other Logs

```log
FFmpeg.DirectStream-* log:

file:/volume1/video/TV Series/Obi-Wan Kenobi/Season 01/Obi-Wan Kenobi - 1x01 - Part I.mkv: Permission denied

[hls @ 0x2229380] Failed to open file '/volume1/@appstore/jellyfin/var/data/transcodes/b46e5a714f6a6f394b119975c45f9d2b0.ts'
av_interleaved_write_frame(): Permission denied
```

```log
ffmpeg permissions:

$ ls -all  /var/packages/ffmpeg/target/bin/ffmpeg
-rwsr-xr-x 1 sc-ffmpeg ffmpeg 270104 Mar 28 23:14 /var/packages/ffmpeg/target/bin/ffmpeg

$ sudo -u sc-ffmpeg touch /volume1/@appstore/jellyfin/var/data/transcodes/test
touch: cannot touch ‘/volume1/@appstore/jellyfin/var/data/transcodes/test’: Permission denied
```

### Known Workaround

```bash
$ sudo chmod u-s+x /var/packages/ffmpeg/target/bin/ffmpeg
$ sudo chmod u-s+x /var/packages/ffmpeg/target/bin/vainfo
```

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

ffmpeg dsm6 fixes and misc updates:
- Fix DSM6 permissions
- Update ffmpeg4 to 4.4.4
- Update ffmpeg5 to 5.1.3
- Import ffmpeg4 Synology patches to ffmpeg5-6
- Update Intel Media Driver 2023Q1 Release (DSM7 only)

Fixes #5710, #5445 and https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/issues/66

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
@AlexPresso FYI

**Comment by mreid-tt** [comment]
@th0ma7, would this fix the issue? I don't see any modifications for the `service-setup.sh` files which would change the executing user or at least bring consistency between the versions.

**Comment by th0ma7** [comment]
> @th0ma7, would this fix the issue? I don't see any modifications for the `service-setup.sh` files which would change the executing user or at least bring consistency between the versions.

Nope, returning to have files being owned by root for DSM6 like previous behaviour.  Although I'm ok at testing other options if you have a few cycles.

**Comment by mreid-tt** [comment]
> @mreid-tt Nope, returning to have files being owned by root for DSM6 like previous behaviour. Although I'm ok at testing other options if you have a few cycles and a DSM6 intel gpu based NAS?

Sure, happy to help test. I have a DS916+ so hopefully that is compatible.

My main point was that while the path in ffmpeg v4 pointed to the correct directories, v5 and v6 did not in the `service-setup.sh` script for these versions. As such, this was just a nudge to get them consistent as part of this PR for testing.

**Comment by th0ma7** [comment]
Gotcha!  Will fix that, thnx.
Btw, by any chance, any good with C ?
Issue with webm patch failing at build time.  I may have to drop it entirely thua removing seek time option.

**Comment by th0ma7** [comment]
@nyanmisaka wondering, would you have a few spare cycles to look over older ffmpeg 4.4 patches?  I originally ported them mostly as-is from prior synology sources but I believe some of them may be (or not) of value to jellyfin such as seek time patches.

My C is pretty much rotten... Would you (or someone else from the jellyfin project?) have time to look over them and assist on porting them over to v5-v6 of ffmpeg?  Even better if some of it would be integrated into jellyfin's upstream tree.  Help would be much welcomed.  Thnx in advance.

**Comment by th0ma7** [comment]
> Where did those patches come from? [patchwork.ffmpeg.org](https://patchwork.ffmpeg.org/) or the internal tickets of synology?

I had extracted them manually from Synology provided source code of older ffmpeg.

> It's best to leave them as is if they can be successfully compiled.

Most of them can with one exception:  `0103-SYNO-videostation-webm-seek-time.patch`

A pair of eye from someone skilled in C and ffmpeg source code in particular would be helpful in order to fix that patch in particular as it has other usages with VideoStation for instance.  And (pushing my luck for a bit), by extension, looking at the other patches (`0100-0103` and `0110-0113`) to confirm they both make sense and are worth keeping would really be awesome :)

**Comment by mreid-tt** [comment]
@th0ma7, just a note that this build seems to also include the `tvheadend` package.

**Comment by th0ma7** [comment]
> just a note that this build seems to also include the `tvheadend` package.

@mreid-tt this is the way :)  As `cross/ffmpeg5` got changed it trigerred building it's direct dependency (i.e. `tvheadend`).  With the latest commit now also updating `cross/ffmpeg4`, `chromaprint` and `comskip` should normally be built as well.

**Comment by hgy59** [comment]
@th0ma7 I propose to use `ffmpeg 5` and `ffmpeg 6` as `DISPLAY_NAME` instead of `DISPLAY_NAME = ffmpeg $(SPK_VERS)`

The display name sould correspond with the package and not change on every update.

**Pull request merged**
