### PR TITLE
Add Docker DSM and update digests of 6.1 toolchains

### PR DESCRIPTION
**Pull request by ymartin59**
_Motivation:_ Produce package for target platform "Docker DSM" as `dockerx64`
_Linked issues:_ #2866

I have already built `nano` and `transmission` packages from `dsm6` branch. Still looking for a proper way to test generated packages - for the moment, I submit them to beta-testers

### CODE REVIEW

**Comment by m4tt075** [comment]
Cherry-picked this to my TVH development branch. Builds fine despite all dependencies, including your new `ffmpeg-3.3.3` cross package...

**Comment by ymartin59** [comment]
@m4tt075 Thank you for testing. Have you deployed produced package on Docker DSM too ?

**Comment by m4tt075** [comment]
@ymartin59 Nope. I don't have a Docker DSM. But happy to make the compiled package available if anybody is interested in testing. Just let me know...

**Comment by lennvilardi** [comment]
I can test Transmission if you want

**Comment by ymartin59** [comment]
Here it is: 
[transmission_dockerx64-6.1_2.92-12.spk.zip](https://github.com/SynoCommunity/spksrc/files/1327306/transmission_dockerx64-6.1_2.92-12.spk.zip)

**Comment by ymartin59** [comment]
@hgy59 Hello. As our toolchain expert, may you please investigate if `dockerx64` architecture may be included into `syno-x64-6.1` or if there is a risk to produce troubles ?

**Pull request merged**
