### PR TITLE
DNSCrypt Proxy GUI

### PR DESCRIPTION
**Pull request by publicarray**
_Motivation:_ This PR builds on top of #3265 and adds a basic user interface to modify preferences. I would welcome someone who has DSM 6.0 to test this, as I've only confirmed everything is working on the RT2600ac.
_Linked issues:_ #3265

### Checklist
- [x] Build rule `all-supported` completed successfully (Except PPC Architectures)
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by publicarray** [comment]
@ymartin59 @Safihre I hope you don't mind but I'm thinking of asking synology to make this an official package.

**Comment by Safihre** [comment]
Always worth a try 👍

**Comment by publicarray** [comment]
Thanks, I've send them an email 🤞

**Comment by publicarray** [comment]
@ymartin59
> @publicarray Correct. I propose you rebase #3296 (and do some squashing) to ease that second PR review. I propose to publish all-in-one when ready.

The Rebase is done :) I can squash and edit history if you want but I fail to see the value of doing so if like the previous PRs, this PR is [Squashed and merged](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits).

**Comment by publicarray** [comment]
@ymartin59 Not sure if you get notified on force pushes but I've got it down to 4 commits.

**Comment by ymartin59** [comment]
@publicarray I cannot say... for sure I am notified about too many things from here... As the moment I work on Python ARM support. When done, I come back to test and publish your dnscrypt package.

**Comment by Safihre** [comment]
Cool, want to test this soon on my device and maybe we can use it for other things too.

**Comment by publicarray** [comment]
Sweet! That was quick.
@Safihre Yea eventually I'm planing on making the UI a separate package, The main problem to tackle is to make it universal but still keep it secure.
One way I though of is that package developers will need to set permissions for their files so the web server / cgi script can read/write to them. And an inbuilt list of valid file locations that needs to be updated for new packages (but only show the ones where a file is already on disk) to avoid modification of unknown files / and malicious uses.

**Comment by publicarray** [comment]
@Safihre Hi, the editor is now a stand alone app. https://github.com/publicarray/synoedit. I still need to clean up the code a lot 🛠

**Pull request merged**
