### PR TITLE
Updated NZBGet to version 17.0

### PR DESCRIPTION
**Pull request by KaraokeStu**
Updated to the latest version as per requested here:
https://github.com/SynoCommunity/spksrc/issues/2420

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully
- [x] Confirmed no configuration changes

### CODE REVIEW

**Comment by evaryont** [comment]
I think the changelog in `spk/nzbget/Makefile` should be updated? The changes in v17 is bigger than just updating a library for security reasons.

**Comment by KaraokeStu** [comment]
The general standard is just to include the actual changes in the package, not the software itself - for that you should look at the referenced website

**Comment by evaryont** [comment]
Sure, I figured that was the case. I guess then instead the second line
could be replaced with a URL/link? Just being pedantic in the end though.
Thanks for making the PR!

**Comment by DaftHonk** [comment]
When I try to compile for cedarview-6.0 I receive the following error when configuring nzbget:
```
checking for ncurses... no
configure: error: "ncurses library not found"
../../mk/spksrc.configure.mk:50: recipe for target 'configure_target' failed
```
ncurses-6.0 built correctly in the work directory and libncurses5-dev is installed on my system (ubuntu 16.04 x64).

Also, only 6.0 TCs should support as previous toolchains do not have the required level of GCC (>=4.9); did you successfully compile for any 5.2 toolchains?

**Comment by KaraokeStu** [comment]
Closed as @DaftHonk states, this requires GCC 4.9 or 5.0, which is not currently enabled - we may be able to build it as a cross binary, but not right now!

**Pull request closed without merging**
