### PR TITLE
[WIP] Python 2.7 fixes

### PR DESCRIPTION
**Pull request by m4tt075**
### Motivation
Cross-compilation of python-2.7 fails. This is an atempt to fix this. Currently WIP. Don't merge!

### Linked issues
#2819 

### Status
- Compilation of cryptography module failed with `cffi.api.CDefError: cannot parse "typedef int __dotdotdot__  time_t;"`: Fixed by updaing `cffi` cross package to `1.10.0`
- Source for cross-package `libsodium 1.0.13` cannot be found: Deprecated, fixed by updating cross package to `1.0.15`
- Stripping `lib/python2.7/lib-dynload/*.so` fails.

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by m4tt075** [comment]
@ymartin59 The stripping fails, because the `lib-dynload` folder does not contain any `*.so` files. I don't know whether they should be there and are missing or whether the corresponding stripping entry can just be removed from the `PLIST` file. Any insights appreciated...

**Comment by Safihre** [comment]
While you are doing this, maybe you can also update python itself to 2.7.14 (https://github.com/SynoCommunity/spksrc/issues/2918).
And maybe also setuptools and wheels `cross` packages?

**Comment by m4tt075** [comment]
@Safihre I have just tried, but those updates introduce additional issues as the existing patches don't apply anymore. The python configuration files have changed significantly. The code is complex and I don't understand it well enough to know what needs to be adapted. Sorry...

**Comment by Safihre** [comment]
@m4tt075 Ah, seems we are doing double work. Maybe you saw I managed to get it compiled by hustling a number of modules around?

@ymartin59 Maybe you can make 1 big "DSM6 progress issue" with a checklist? What steps need to be taken and in what order to get things up and running?
To me it seems first your service-support, then get the website to support DSM6 and then we can start modifying packages 1 by 1? Is that correct?
I really want to help but would help to have a plan so we can all do our part :)

**Comment by m4tt075** [comment]
@Safihre Yes, I saw it, and believe you have made way more progress than I did. Do you want to PR your changes? I'd be happy to close my PR here and focus on the DSM6 integration again instead. 

W.r.t. your question to @ymartin59, this is exactly what he has done. Just check the "Projects" tab at the top of this page and you should see it.

**Comment by Safihre** [comment]
My implementation is lacking testing. Similar to your approach I just identified which modules failed and excluded those. This is of course not a solution for the long term. 
I think that to properly help this project I should setup my own DSM VM's instead of just messing around with Travis building. I noticed me compiling packages for DSM 6.1 using Travis might be counter productive and I would like to be of real help instead :) I hope to have time to setup these VM's soon!

**Comment by m4tt075** [comment]
@Safihre I have made exactly the same experience you just went through. Setting up a testing VM certainly makes sense. I'm sure your help is appreciated, whenever you are ready and able to contribute.  :)

**Comment by Safihre** [comment]
So now I am a bit stuck. Maybe @BenjV you know this.
While compiling Python it fails to compile `ctypes` due to this error:
```
In file included from /spksrc/spk/sabnzbd/work-bromolow-6.1/Python-2.7.13/Modules/_ctypes/libffi/src/closures.c:119:0:
/spksrc/spk/sabnzbd/work-bromolow-6.1/Python-2.7.13/Modules/_ctypes/libffi/src/dlmalloc.c:1454:35: error: ‘__PTHREAD_SPINS’ undeclared here (not in a function)
 static MLOCK_T magic_init_mutex = PTHREAD_MUTEX_INITIALIZER;
```
Isn't this something the Synology toolchain environment should provide?

**Comment by Safihre** [comment]
I just can't get it to work. Who knows a lot about compilers? @cytec @Dr-Bean 
There is something different about the DSM6 toolchains, whatever I do it keeps failing to build `_ctypes` due failing to build `libffi`.
I checked the command that compiles `_ctypes` and it's identical between DSM5.2 and DSM6 tool-chains. So something in the update of GCC or glibc breaks the build.. But where to start?

**Comment by ymartin59** [comment]
As Synology publish GPL sources they have used to build NAS, and python is delivered, I would have expected to find "patches" sources at https://sourceforge.net/projects/dsgpl/files/Synology%20NAS%20GPL%20Source/15047branch/x64-source/
But it is not the case... Probably Python is not GPL but BSD and so they do not bother to publish modified sources as license does not compell to do so.

**Comment by Safihre** [comment]
Updating to Python 2.7.14 fixed it!
It also includes support for cross-compiling so we don't need those patches anymore.
Now `cross/python` compiles 💯 
On to `spk/python`!

**Comment by ymartin59** [comment]
Will be superseed by #3060

**Comment by m4tt075** [comment]
Thanks much, @Safihre . Closing as superseeded.

**Pull request closed without merging**
