### PR TITLE
SABnzbd 2.2.0Beta2

### PR DESCRIPTION
**Pull request by Safihre**

### CODE REVIEW

**Comment by Safihre** [comment]
@ymartin59 @KaraokeStu There is a security vulnerability in `unrar` from before 5.5.0 Beta 4.
I can submit a PR with new digests, but since I don't have a Synology NAS or a build-system I can't test it. Maybe one of you could do that and push the update?

**Comment by KaraokeStu** [comment]
It all depends on what the security vulnerability is, however I'm not certain that we want to get around it by switching to a beta version.

Any thoughts on waiting for 5.5 stable?

**Comment by Safihre** [comment]
Yeah that's also what we do, wait for the stable. Probably best here to.

**Comment by KaraokeStu** [comment]
I'll merge this request - feel free to open an issue to update to unrar 5.5 once it is available

**Pull request merged**
