### PR TITLE
zsh: provide variant with statically linked modules

### PR DESCRIPTION
**Pull request by agross**
_Motivation:_
As discussed in #2449, some zsh users need zsh modules to use their scripts. I, for example, would like to use my zsh plugin manager [zplug](https://github.com/zplug/zplug). zplug requires the `zsh/system` and `zsh/regex` modules which are not available in the existing zsh package.

The zsh Makefile (the one shipping with zsh itself) detects that dynamic loading is not supported for the target arch and hence will be compiled without any modules except the ones linked statically by default. So, I propose the addition of a second `zsh-static` package (this one), [providing statically linked zsh modules](https://github.com/zsh-users/zsh/commit/626c580148a58d92515c04df607eaa06d86f15f9#L85). Zsh processes with static modules have a higher memory footprint, hence the addition of a new package instead of modifying the existing package.

The `zsh-static` package tries to reuse as much Makefile logic as possible from the `zsh` package. This is my first GNU make patch, so feedback is very welcome.

I was not able to make the new `zsh-static` package conflict with the existing `zsh` package, please see #2893 and advise what I should do (I will amend the submitted commit).

Please note that this PR also includes the update to zsh 5.4.1 (#2889).

_Linked issues:_
#2449, #2893, #2889

### Checklist
- [x] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
Hello.
Thank you for investigating this old issue. Your proposal is interesting.
It looks like you used symbolic links to refer to files from `zsh-static` to `zsh`

I propose the following alternate way, that is more in `spksrc` philosophy:
- no need for a `cross/zsh-static`
- control dynamic/static build thanks to Make variable in `cross/zsh`
- `spk/zsh-static` depends on `cross/zsh` (so no need to replicate `PLIST` and `digests`)

May you please give it a try ? It should reduce copy/paste to minimal in my opinion.
Best regards

**Comment by agross** [comment]
Hi @ymartin59,

Thanks for the hints.

> control dynamic/static build thanks to Make variable in cross/zsh

Do you mean I should add `POST_CONFIGURE_TARGET` etc. conditionally in `cross/zsh` like this?

```Makefile
ifndef ZSH_STATIC
POST_CONFIGURE_TARGET = link-zsh-modules
...
endif
```

...where `ZSH_STATIC` is set in `spk/zsh-static` and unset in `spk/zsh`?

**Comment by ymartin59** [comment]
Hello. It looks like a good idea to me, yes... if it works properly, we remove a copy of `cross/zsh`, what I would appreciate as maintainer.

**Comment by agross** [comment]
@ymartin59 I updated the PR and I hope I could fulfull your suggestions.

The only standing issue now is how I can make `zsh-static` conflict with `zsh`. (#2893)

**Comment by ymartin59** [comment]
Is that really necessary ? Usually each package has its own "sandbox" as `/usr/local/${PKG_NAME}`... if you do not enforce both to have same prefix, the only "conflict" concerns `/usr/local/bin/zsh` link...
So I would say, if someone decides to install both... well, last install wins its place under sunset at `/usr/local/bin/zsh`.
What do you think about it ?

**Comment by agross** [comment]
Well, I thought the maintainers here would care. I don't know bother because I probably will never install the non-static version. One could also argue that zsh users know what they're doing.

**Comment by ymartin59** [comment]
That is what I did... By the way, I am interested in answering your question about `SPK_CONFLICT`...

**Comment by ymartin59** [comment]
@agross Sorry I did use "rebase and merge" on my PR... as a result, you have to rebase your branch to discard my "duplicated" commit. May you please do that ?

**Comment by agross** [comment]
Done!

**Comment by ymartin59** [comment]
Thanks.

**Comment by ymartin59** [comment]
Packages published

**Comment by agross** [comment]
👍

**Comment by agross** [comment]
@ymartin59 Any ideas when the new/updated packages will show up in the feed? https://packages.synocommunity.com/ returns Bad Request for me. zsh is still at 5.3.1 and zsh (with modules) doesn't show up in DSM. (I pressed refresh several times over the last couple of days.)

**Comment by ymartin59** [comment]
Hello. No idea what may be wrong - it is OK on my DSM (evansport). What is your arch and DSM version ?

**Comment by agross** [comment]
Avoton and latest.

I found a package source monitoring project somewhere and it listed synocommunity as offline. Are you sure that Bad Request is an OK state for the feed page?

**Comment by ymartin59** [comment]
I have just "right now" installed zsh-static on my system. I guess you looked at http://dottoremoe.com/synomon/ But repository is online and usable: https://synocommunity.com/package/zsh-static

**Comment by agross** [comment]
Yes, it was synomon I was referring to. For me the classic zsh package is still at 5.3.1. After I removed the package source, all the SynoCommunity remain displayed and appear to be installable despite failing any installation attempts. WTF?

**Comment by agross** [comment]
Removed the source, verified that all SC packages are no longer displayed (which took a while), readded the SC source, now zsh is at 5.3.1 and the modules variant is still missing. The last thing I'm going to try is reboot the damn DSM.

**Comment by agross** [comment]
A reboot didn't fix it. Using `tcpdump` and the non-HTTPs package source at `http://packages.synocommunity.com/` I found that my DSM requests `http://packages.synocommunity.com/?package_update_channel=beta&unique=synology_avoton_2415%2B&build=15152&language=enu&major=6&micro=3&arch=avoton&minor=1&timezone=Amsterdam&nano=4` to get the package list.

This list only contains `zsh 5.3.1-4`, could you please test that in your browser?

**Comment by ymartin59** [comment]
Dammed ! "avoton" and other x86_64 architectures fail to publish on repository and I missed error message. Fix available #2914. Packages should be visible now.

**Comment by agross** [comment]
Confirmed. Many thanks!

**Pull request merged**
