### PR TITLE
Updated SABnzbd to 1.1.0

### PR DESCRIPTION
**Pull request by KaraokeStu**
_Motivation:_ Explain here what the reason for the pull request is.
_Linked issues:_ Optionally, add links to existing issues or other PR's

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by KaraokeStu** [comment]
While synocommunity publishing is on hold, please add  http://syno.karaokestu.co.uk to your package sources - I've just set it up

**Comment by cytec** [comment]
Publishing is not on hold... it's more like that most Packages wont work with DSM 6 as they are right now...

**Comment by KaraokeStu** [comment]
@cytec Thanks for the update on that, this is a temporary solution for those still running 5.x

**Comment by Diaoul** [comment]
@KaraokeStu: I just censored the link as it was advertised with wrong reasons and can be misleading.
I see no problem with updating packages for DSM 5.x in SynoCommunity.

If you're willing to contribute (and I see you are with your PRs) I can grant you publish permissions on SynoCommunity's repository and spksrc for DSM 5.x maintenance but please do not spread links and packages. This greatly hurts backward compatibility and make maintenance and support a hell.

**Comment by KaraokeStu** [comment]
Thanks @Diaoul - sorry I hadn't heard much in over a month, so was worried things were going a bit stale - I'm happy to continue contributing on the packages that I use and test lots (mainly things like CouchPotato, SABnzbd, Deluge, HeadPhones, Sonarr, LazyLibrarian) and also others that I have a reasonable understanding of (Mosquitto, NZBGet, Jackett)

**Comment by Diaoul** [comment]
Drop me a mail I'll send the credentials over for the repo.

**Comment by Safihre** [comment]
Thanks guys! 👍  We (SABnzbd) got some questions when Synology packages would be updated. Now I can tell them at least for DSM5 it is!

**Comment by KaraokeStu** [comment]
Hi @Safihre I'll keep an eye on the latest versions and keep both our release and beta versions up to date within a few days.

**Pull request merged**
