### PR TITLE
update jellyfin 10.9.7

### PR DESCRIPTION
**Pull request by stevenliuit**
update jellyfin to 10.9.7 version

## Description

update jellyfin to 10.9.7 version

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by stevenliuit** [comment]
> @hgy59 would you be able to assist with the review and publishing of this update?

@mreid-tt The version will be updated after one to two weeks of stabilization, so don't worry.

**Comment by stevenliuit** [comment]
> @hgy59 would you be able to assist with the review and publishing of this update?

If you are in a hurry, you can compile and install it yourself.

**Comment by mreid-tt** [comment]
> > @hgy59 would you be able to assist with the review and publishing of this update?
> 
> If you are in a hurry, you can compile and install it yourself.

Thanks but this was not for me as I don't use Jellyfin. I noted the following on the Discord support channel:

> Hi, 10.9.6 of jellyfin is resulting in this bug (https://github.com/jellyfin/jellyfin-media-player/issues/683). Any plans to release the latest version 

In response another user pointed to this PR and suggested that the user download from the builds section. Of course that won't work because of the min DSM requirement, so I thought I'd ask on their behalf. If it's not yet ready to go perhaps you can flag this PR as a draft or mark as WIP.

**Comment by stevenliuit** [comment]
hgy59 has already responded to this question in the previous PR. I remember you also participated in the discussion. hgy59 also clearly responded to the time of merging PR. This has nothing to do with me. Please understand.
Please see the description of how to address: https://github.com/SynoCommunity/spksrc/pull/6101#issuecomment-2154311998
If you don't understand, please don't ask again, thank you.

**Comment by stevenliuit** [comment]
> > > @hgy59 would you be able to assist with the review and publishing of this update?
> > 
> > 
> > @mreid-tt The version will be updated after one to two weeks of stabilization, so don't worry.
> > If you are in a hurry, you can compile and install it yourself.
> 
> Thanks but this was not for me as I don't use Jellyfin. I noted the following on the Discord support channel:
> 
> > Hi, 10.9.6 of jellyfin is resulting in this bug ([jellyfin/jellyfin-media-player#683](https://github.com/jellyfin/jellyfin-media-player/issues/683)). Any plans to release the latest version
> 
> In response another user pointed to this PR and suggested that the user download from the builds section. Of course that won't work because of the min DSM requirement, so I thought I'd ask on their behalf. If it's not yet ready to go perhaps you can convert this PR to a draft or label as WIP.

hgy59 has already responded to this question in the previous PR. I remember you also participated in the discussion. hgy59 also clearly responded to the time of merging PR. This has nothing to do with me. Please understand.
Please see the description of how to address: https://github.com/SynoCommunity/spksrc/pull/6101#issuecomment-2154311998
If you don't understand, please don't ask again, thank you.

**Comment by JK-MS1** [comment]
Hello,
I tried to install the 10.9.7-15 package on my DS923+ NAS.
The package installed FFmpeg 6, then stopped without further installation.
Since then it doesn't appear as "Installed" but rather as "Install", but nothing happens after downloading, if I click on the button again.

Any idea how to find the cause?

**Comment by mreid-tt** [comment]
@JK-MS1 sometimes packages do not show all error messages in the UI. This is something we have reported to Synology to try to address. You can investigate further by:
1. Downloading the package for your NAS (https://synocommunity.com/package/jellyfin) and manually installing it. This often shows additional information
2. Examine the install logs generated by packages (requires SSH into your NAS)

**Comment by JK-MS1** [comment]
@mreid-tt 
Yes manually installing it have showed a error :)

Port 8096 already in use :)

I think I have to uninstall emby before testing Jellyfin :) haha.. 
Thank for your help

**Pull request merged**
