### PR TITLE
Update SABnzbd-testing to 1.2.1Beta1

### PR DESCRIPTION
**Pull request by Safihre**
_Motivation:_ Update SABnzbd-testing to 1.2.1Beta1

### Checklist
- [] Build rule `all-supported` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

### CODE REVIEW

**Comment by KaraokeStu** [comment]
LGTM

**Comment by KaraokeStu** [comment]
Published

**Comment by Safihre** [comment]
@KaraokeStu @Dr-Bean 
We would like to upgrade the par2cmdline version to the [multithreaded one](https://github.com/jkansanen/par2cmdline-mt).
On my desktop I can simply run these commands after downloading the `src`: https://github.com/jkansanen/par2cmdline-mt/archive/v0.6.14-mt1.tar.gz
```
aclocal
automake --add-missing
autoconf
./configure
make
make install
```
What would be a similar set of commands for a package here?
I looked at the `unrar` package, would it be as simple as that?

Since SAB is the only one using the par2cmdline package, it seems just upgrading that one should be safe enough.

**Comment by Safihre** [comment]
Oops, should have read the documentation. WIll go and try to figure it out myself first!

**Comment by KaraokeStu** [comment]
Hi, we will want to update the par2 cross package to use the MT source - I'll take a look at that for you

**Comment by KaraokeStu** [comment]
Do we want par2cmdline-mt or par2cmdline-tbb?

**Comment by Safihre** [comment]
Aaah great!
TBB is faster, but par2cmdline-mt is much much easier to install, because TBB requires the Intel Thread Building Blocks (TBB 😃) and this package is often not available or doesn't compile well on non-x86.

**Comment by KaraokeStu** [comment]
OK, I'll take a look at getting that compiling. @Dr-Bean Any objections to upgrading par2cmdline to par2cmdline-mt?

**Comment by Dr-Bean** [comment]
No, assuming the `-mt` source compiles/works fine for current arches.
We'll probably want to set up a new package though, right? If the current one is only used for sabnzbd, might as well rename the existing package (append `-mt` in all the right places, presumably). That enables us to re-add the original one in case we need it for some other SPK in the future.

**Comment by KaraokeStu** [comment]
ok, I'll add a new -mt package and update sabnzbd to pull that cross instead :)

**Comment by Safihre** [comment]
So since it uses the same command `par2`, it will just overwrite the older `par2` link on install?

**Pull request merged**
