### PR TITLE
open-vm-tools, tinyproxy, imapfilter, optware-ng, strace, toolchain, syno-cedarview-6.0

### PR DESCRIPTION
**Pull request by gits68**
_Motivation:_
spk open-vm-tools 10.0.7 (depends libtirpc 0.2.5 libmspack 0.5alpha libdnet 1.11)
spk tinyproxy 1.8.3
imapfilter 2.6.7 (depends lua 5.3.3)
optware-ng 6.8 (aka ipkg-ng)
strace 4.11
toolchains/syno-cedarview-6.0
kernel/syno-cedarview-6.0 (7274 vanished from dsgpl, but I still have the archive :)
_Linked issues:_ none
### Checklist
- [] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by The-MAD-Virus** [comment]
+1 for optware-ng, it's the only alternative to debian chroot for DS413 user

**Comment by KaraokeStu** [comment]
I think this is best held off until we have full DSM 6 support and toolchains in Master

**Comment by Dr-Bean** [comment]
Thanks, but unfortunately, this PR can't be merged. Please split off the individual SPK additions into their own PR: it makes it far easier to review and comment on a limited changeset.

Also, a PR to add toolchains should be complete, as in: including all toolchains and kernels for a particular DSM version, not just one arch. On that note, it looks like Synology still hasn't (re)published the GPL sources for DSM6... :(

**Comment by gits68** [comment]
well, split off the individual SPK additions into their own PR ?

**Pull request closed without merging**
