### PR TITLE
synocli-net update and openssh: fix for older kernel versions #5556

### LINKED ISSUE #5556: synocli-net : getentropy failed
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

synocli-net

### Package Version

2.2-15

### Device Model

DS1813+

### Device Architecture

x86_64

### Firmware Version

DSM 7.1.1-42962 Update 3

### What happened?

Hi,
I just upgraded my DS1813+ from DSM 6.2 to 7.1 and I am using autossh.
Since this migration I have an error: getentropy failed
`user@NAS:~$ autossh -M 0 -L 80:192.168.x.x:80 -p 2023 user@toto.dyndns.me`
`getentropy failed`

I thought the upgrade caused problems but I tried with my DS115 and I have the same issue in DSM 7.1.
I tried with root but same issue.

The `ssh-agent`  command gives the same response.

I have no error with the same ssh command.

Do you have an idea ?

### Reproduction steps

```bash
1.autossh -M 0 -L 80:192.168.x.x:80 -p 2023 user@toto.dyndns.me
2.ssh-agent
3.
...
```

### Install Log

```log
2023/01/09 18:00:00     install synocli-net 2.2-15 Begin preinst
2023/01/09 18:00:00     Begin reload_inst_variables
2023/01/09 18:00:00     End reload_inst_variables
2023/01/09 18:00:00     Begin initialize_variables
2023/01/09 18:00:00     End initialize_variables
2023/01/09 18:00:00     ===> Step preinst. USER= GROUP= SHARE_PATH=
2023/01/09 18:00:00     install synocli-net 2.2-15 End preinst ret=[0]
2023/01/09 18:00:02     install synocli-net 2.2-15 Begin /bin/mkdir -p /volume1/@appstore/synocli-net -m 755
2023/01/09 18:00:02     install synocli-net 2.2-15 End /bin/mkdir -p /volume1/@appstore/synocli-net -m 755 ret=[0]
2023/01/09 18:00:02     install synocli-net 2.2-15 Begin /bin/rm -rf /volume1/@appstore/synocli-net
2023/01/09 18:00:02     install synocli-net 2.2-15 End /bin/rm -rf /volume1/@appstore/synocli-net ret=[0]
2023/01/09 18:00:02     install synocli-net 2.2-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/package /volume
1/@appstore/synocli-net
2023/01/09 18:00:02     install synocli-net 2.2-15 End /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/package /volume1/
@appstore/synocli-net ret=[0]
2023/01/09 18:00:02     install synocli-net 2.2-15 Begin /bin/rm -rf /var/packages/synocli-net
2023/01/09 18:00:02     install synocli-net 2.2-15 End /bin/rm -rf /var/packages/synocli-net ret=[0]
2023/01/09 18:00:02     install synocli-net 2.2-15 Begin /bin/mkdir -p /var/packages/synocli-net -m 755
2023/01/09 18:00:02     install synocli-net 2.2-15 End /bin/mkdir -p /var/packages/synocli-net -m 755 ret=[0]
2023/01/09 18:00:02     install synocli-net 2.2-15 Begin /bin/touch /var/packages/synocli-net/installing
2023/01/09 18:00:02     install synocli-net 2.2-15 End /bin/touch /var/packages/synocli-net/installing ret=[0]
2023/01/09 18:00:02     install synocli-net 2.2-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/INFO /var/packa
ges/synocli-net/INFO
2023/01/09 18:00:02     install synocli-net 2.2-15 End /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/INFO /var/package
s/synocli-net/INFO ret=[0]
2023/01/09 18:00:02     install synocli-net 2.2-15 Begin /bin/rm -rf /var/packages/synocli-net/scripts
2023/01/09 18:00:02     install synocli-net 2.2-15 End /bin/rm -rf /var/packages/synocli-net/scripts ret=[0]
2023/01/09 18:00:02     install synocli-net 2.2-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/scripts /var/pa
ckages/synocli-net/scripts
2023/01/09 18:00:02     install synocli-net 2.2-15 End /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/scripts /var/pack
ages/synocli-net/scripts ret=[0]
2023/01/09 18:00:02     install synocli-net 2.2-15 Begin /bin/rm -rf /var/packages/synocli-net/WIZARD_UIFILES
2023/01/09 18:00:02     install synocli-net 2.2-15 End /bin/rm -rf /var/packages/synocli-net/WIZARD_UIFILES ret=[0]
2023/01/09 18:00:02     install synocli-net 2.2-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/WIZARD_UIFILES
/var/packages/synocli-net/WIZARD_UIFILES
2023/01/09 18:00:02     install synocli-net 2.2-15 End /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/WIZARD_UIFILES /v
ar/packages/synocli-net/WIZARD_UIFILES ret=[0]
2023/01/09 18:00:02     install synocli-net 2.2-15 Begin /bin/rm -rf /var/packages/synocli-net/conf
2023/01/09 18:00:02     install synocli-net 2.2-15 End /bin/rm -rf /var/packages/synocli-net/conf ret=[0]
2023/01/09 18:00:02     install synocli-net 2.2-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/conf /var/packa
ges/synocli-net/conf
2023/01/09 18:00:02     install synocli-net 2.2-15 End /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/conf /var/package
s/synocli-net/conf ret=[0]
2023/01/09 18:00:13     install synocli-net 2.2-15 Begin postinst
2023/01/09 18:00:13     Begin reload_inst_variables
2023/01/09 18:00:13     End reload_inst_variables
2023/01/09 18:00:13     Begin initialize_variables
2023/01/09 18:00:13     End initialize_variables
2023/01/09 18:00:13     ===> Step postinst. USER= GROUP= SHARE_PATH=
2023/01/09 18:00:13     Begin save_wizard_variables
2023/01/09 18:00:13     End save_wizard_variables
2023/01/09 18:00:13     Begin syno_sync_var_folder
2023/01/09 18:00:13     End syno_sync_var_folder
2023/01/09 18:00:13     install synocli-net 2.2-15 End postinst ret=[0]
2023/01/09 18:00:17     install synocli-net 2.2-15 Begin start-stop-status start
2023/01/09 18:00:17     install synocli-net 2.2-15 End start-stop-status start ret=[0]
```

### Service Log

```log
does not exist
```

### Other Logs

```log
message :
2023-01-09T21:00:46+01:00 NAS autossh[27643]: ssh exited prematurely with status 255; autossh exiting
synopkg.log :
2023/01/09 17:58:00 download synocli-net https://packages.synocommunity.com/synocli-net/15/synocli-net.v15.f41890%5Balpine-alpine4k-armada370-armada375-armada38x-armadaxp-m
onaco%5D.spk?arch=armada375&build=42962 End download
2023/01/09 17:58:09 Use default volume to install, volume=[/volume1]
2023/01/09 17:59:50 Use default volume to install, volume=[/volume1]
2023/01/09 18:00:00 Use default volume to install, volume=[/volume1]
2023/01/09 18:00:00 install synocli-net 2.2-15 Begin preinst
2023/01/09 18:00:00 install synocli-net 2.2-15 End preinst ret=[0]
2023/01/09 18:00:02 install synocli-net 2.2-15 Begin /bin/mkdir -p /volume1/@appstore/synocli-net -m 755
2023/01/09 18:00:02 install synocli-net 2.2-15 End /bin/mkdir -p /volume1/@appstore/synocli-net -m 755 ret=[0]
2023/01/09 18:00:02 install synocli-net 2.2-15 Begin /bin/rm -rf /volume1/@appstore/synocli-net
2023/01/09 18:00:02 install synocli-net 2.2-15 End /bin/rm -rf /volume1/@appstore/synocli-net ret=[0]
2023/01/09 18:00:02 install synocli-net 2.2-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/package /volume1/@appstore/synocli-net
2023/01/09 18:00:02 install synocli-net 2.2-15 End /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/package /volume1/@appstore/synocli-net ret=[0]
2023/01/09 18:00:02 install synocli-net 2.2-15 Begin /bin/rm -rf /var/packages/synocli-net
2023/01/09 18:00:02 install synocli-net 2.2-15 End /bin/rm -rf /var/packages/synocli-net ret=[0]
2023/01/09 18:00:02 install synocli-net 2.2-15 Begin /bin/mkdir -p /var/packages/synocli-net -m 755
2023/01/09 18:00:02 install synocli-net 2.2-15 End /bin/mkdir -p /var/packages/synocli-net -m 755 ret=[0]
2023/01/09 18:00:02 install synocli-net 2.2-15 Begin /bin/touch /var/packages/synocli-net/installing
2023/01/09 18:00:02 install synocli-net 2.2-15 End /bin/touch /var/packages/synocli-net/installing ret=[0]
2023/01/09 18:00:02 install synocli-net 2.2-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/INFO /var/packages/synocli-net/INFO
2023/01/09 18:00:02 install synocli-net 2.2-15 End /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/INFO /var/packages/synocli-net/INFO ret=[0]
2023/01/09 18:00:02 install synocli-net 2.2-15 Begin /bin/rm -rf /var/packages/synocli-net/scripts
2023/01/09 18:00:02 install synocli-net 2.2-15 End /bin/rm -rf /var/packages/synocli-net/scripts ret=[0]
2023/01/09 18:00:02 install synocli-net 2.2-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/scripts /var/packages/synocli-net/scripts
2023/01/09 18:00:02 install synocli-net 2.2-15 End /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/scripts /var/packages/synocli-net/scripts ret=[0]
2023/01/09 18:00:02 install synocli-net 2.2-15 Begin /bin/rm -rf /var/packages/synocli-net/WIZARD_UIFILES
2023/01/09 18:00:02 install synocli-net 2.2-15 End /bin/rm -rf /var/packages/synocli-net/WIZARD_UIFILES ret=[0]
2023/01/09 18:00:02 install synocli-net 2.2-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/WIZARD_UIFILES /var/packages/synocli-net/WIZARD_UIFILES
2023/01/09 18:00:02 install synocli-net 2.2-15 End /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/WIZARD_UIFILES /var/packages/synocli-net/WIZARD_UIFILES ret=[0]
2023/01/09 18:00:02 install synocli-net 2.2-15 Begin /bin/rm -rf /var/packages/synocli-net/conf
2023/01/09 18:00:02 install synocli-net 2.2-15 End /bin/rm -rf /var/packages/synocli-net/conf ret=[0]
2023/01/09 18:00:02 install synocli-net 2.2-15 Begin /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/conf /var/packages/synocli-net/conf
2023/01/09 18:00:02 install synocli-net 2.2-15 End /bin/mv -f /volume1/@tmp/synopkg/install.SqODgB/conf /var/packages/synocli-net/conf ret=[0]
2023/01/09 18:00:05 Acquire systemd-unit for synocli-net when 0x0001 (ready)
2023/01/09 18:00:05 Acquire systemd-unit for synocli-net when 0x0001 (done)
2023/01/09 18:00:13 install synocli-net 2.2-15 Begin postinst
2023/01/09 18:00:13 install synocli-net 2.2-15 End postinst ret=[0]
2023/01/09 18:00:14 install synocli-net: begin to start version 2.2-15
2023/01/09 18:00:15 Acquire usr-local-linker for synocli-net when 0x0001 (ready)
2023/01/09 18:00:15 Acquire usr-local-linker for synocli-net when 0x0001 (done)
2023/01/09 18:00:17 install synocli-net 2.2-15 Begin start-stop-status start
2023/01/09 18:00:17 install synocli-net 2.2-15 End start-stop-status start ret=[0]
2023/01/09 18:00:25 install synocli-net: start version 2.2-15 successfully, result 0
2023/01/09 18:00:26 install synocli-net 2.2-15 successfully
```

### PR DESCRIPTION
**Pull request by hgy59**
## Description

reported in #5556 there is a problem with autossh on DSM 7

- disable use of system getentropy function

Fixes #5556

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)

### Type of change

- [x] Bug fix

### CODE REVIEW

**Comment by egerlach** [comment]
I've tested the artifacts from this PR and they work fine on my DS1513+ with DSM 7.1.

**Review by th0ma7 — COMMENTED** [review]
IMO this should use $(TC_KERNEL)

**Comment by hgy59** [comment]
> IMO this should use $(TC_KERNEL)

I think it is not worth to build autossh as TCVERSION/Kernel specific packages (and to extract it from synocli-net package).
It is sufficient to avoid to use the respecitve kernel function(s).

**Comment by hgy59** [comment]
@egerlach can you please re-test autossh with the update of openssh to v9.3p1 when you have a time slot available?

**Pull request merged**
