### PR TITLE
Update Tvheadend to 4.2.7 (maintenance release)

### PR DESCRIPTION
**Pull request by m4tt075**
### Motivation
- Update `Tvheadend` to 4.2.7 (latest maintenance release)
- Update `libhdhomerun` cross package to 20180817 (latest release) 
- Deactivate default logging functionality to allow NAS to hibernate 
- Remove `dvb-apps` dependency and cross package (now obsolete)
- Enable `pcre2` option via addition of new cross package

### Linked issues
#3476 

### Checklist
- [x] Build rule `all-supported` completed successfully with `6.1` and `6.2` toolchains (except `northstarplus`)
- [ ] Package upgrade completed successfully
- [x] New installation of package completed successfully (on `XPE 6.1`)

### CODE REVIEW

**Comment by m4tt075** [comment]
Cross compilation all green: https://travis-ci.org/m4tt075/spksrc/builds/441390679
6.1/6.2 test builds here: https://github.com/m4tt075/spksrc/releases/tag/tvh-4.2.7-1
Testing and collection of user feedback via #3476, comments on the code here, please.

**Comment by ymartin59** [comment]
@m4tt075 You can reduce list of packages produced by travis, as "x64" includes many of them... You can look at https://synocommunity.com/package/deluge for instance where "broadwelllnk" is included in same 6.1 package... It will save cpu, time, power, storage... even if it requires to explain users to grab "x64" when concerned.

**Comment by m4tt075** [comment]
@ymartin59 118 test build downloads as of now. No reports of regressions. Looking good as far as I'm concerned. Please take another look and merge / publish as you deem appropriate...

**Comment by ymartin59** [comment]
I propose to remove "beta" flag in next version so.

**Comment by m4tt075** [comment]
@ymartin59 Gee, thought we had removed that some versions ago already. Sure. If there is still time to fix it before publishing, please just remove it. I'll be travelling for the next 1.5 weeks with very limited internet access...

**Pull request merged**
