### PR TITLE
Use shallow clone when including NZBGet tools

### PR DESCRIPTION
**Pull request by Safihre**
This lowers the size of the NZBGet SPK from 30MB to 14MB.
We could also just do this `git clone` during installation script, then the package would shrink to only a few MB.
But it would add the `git` dependency. Is that worth it?

### CODE REVIEW

**Review by hgy59 — COMMENTED** [review]
@Safihre are you using this package?

I am unsure about the installed scripts.
As those are python scripts, we probably have to make this package dependent on the Python (3.10) package?
Or we could search for available python at installation time. But this would not add package dependency to nzbget and the found python could be uninstalled and break the nzbget scripts.

I suppose that at least we have to add python to the path for nzbget and fix the shebang in the python scripts as `#!/usr/bin/env python` might not work.

Instead of cloning the script repos we could take the files only.
This is easy for GetScripts as all scripts are in one folder (and we can drop .gitignore)
But for nzbToMedia there is a folder structure with lib and other folders. One folder contains windows binaries that I am sure we can ignore, and getffmpeg.sh will not run on diskstation devices.
By taking the script files only (and removing win and test folders and some other files of nzbToMedia) the final spk size is shrinking to less than 8MB.

**Comment by Safihre** [comment]
@hgy59 No, I don't use this package, but around 5 years ago I created the current version that `wget` the installer instead of compiling it.
But these scripts were included like this even before that, more than 7 years ago: https://github.com/SynoCommunity/spksrc/blame/master/spk/nzbget/Makefile#L39
So, if it hasn't been a problem since then... why try to fix it now?
I do know that NZBGet allows you to specify which Python to use from the configuration, so maybe people use that.

In any case, I just noticed it when inspecting the `nzbget.spk` and I was surprised by the huge size even though it doesn't include the installer itself.

**Comment by Safihre** [comment]
@hgy59 I just tested, and it just works out of the box. Seems it's just using the Synology Python.
I also found that NZBGet installer includes 7zip and unrar, so we don't even need to include those.

What changes of the ones you suggested do you want to include?

**Comment by hgy59** [comment]
@Safihre the current build fails, because there are no dependencies anymore to be added to the package.
to fix this, overwrite the copy_target in `spk/nzbget/Makefile` with:
```
COPY_TARGET = nop
```

_this must not be defined with my solution, where the scripts come from cross packages_

my proposal reduces the spk size from currently 11.5MB to 5.6MB

**Comment by hgy59** [comment]
> But these scripts were included like this even before that, more than 7 years ago: https://github.com/SynoCommunity/spksrc/blame/master/spk/nzbget/Makefile#L39

cool, didn't see/use the _Blame_ button before...

**Comment by Safihre** [comment]
@hgy59 I investigated more.
`nzbToMedia` includes an auto-update mechanism based on git. So if we use the `cross` approach, it would break. We could add `SPK_DEPENDS = "git"`, but since not all users of NZBGet use `nzbToMedia` it's maybe overkill.

So, I converted this to a `norach` since there's no more binaries. 
Seems enough for now, if you agree?

**Comment by hgy59** [comment]
> We could add `SPK_DEPENDS = "git"`, but since not all users of NZBGet use `nzbToMedia` it's maybe overkill.

We don't need `SPK_DEPENDS = "git"`, when the synocommunity package `git` is installed, git is found in the path.
So it is a _soft_ dependency for those who want to use the autoupdate of `nzbToMedia`.

**Review by hgy59 — APPROVED** [review]
LGTM

**Pull request merged**
