### PR TITLE
Update Sonarr version to v0.2.0.1504

### PR DESCRIPTION
**Pull request by mike10010100**
_Motivation:_  Updating Sonarr version to v0.2.0.1504

In the process of building all-supported, not sure how to test package upgrade and new installation, please advise.

### Checklist
- [x] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by Safihre** [comment]
What is the point of this? It can just auto-update itself?

**Comment by mike10010100** [comment]
I was under the impression that Syno packages required updates to be made through the synology package manager. I've had an instance in the past where self-updating with Sonarr/Radarr ended up with them being in a bad state. If this is not the case, then I'll go ahead and close this.

**Comment by Safihre** [comment]
No, the packages support auto-updating so we only provide the base here and then it updates from there.
If something is wrong with the base, we can update. But so far for Sonar v2 it has never been needed.

**Comment by mike10010100** [comment]
Oh man, my bad, this is updating radarr's version, but I'll give the self-update a try. It just seemed like Sonarr had been updated to a newer package version in the synocommunity repo, so I figured the same needed to be done with radarr.

**Pull request closed without merging**
