### PR TITLE
[TVH] Fix URL in DSM Web GUI

### PR DESCRIPTION
**Pull request by m4tt075**
_Motivation:_ Users report issues with URL in DSM Web GUI
_Linked issues:_ #2764 

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by m4tt075** [comment]
@ymartin59: I compared the config file with the latest Syncthing package. The only relevant difference I have spotted was the missing protocol specification which I'm adding here.

**Comment by ymartin59** [comment]
@m4tt075 Have you reproduced issue ? Do you want me to build and package for testing ?

**Comment by m4tt075** [comment]
@ymartin59: Yes, and yes, please, if you could do that...

**Comment by m4tt075** [comment]
@ymartin59 : I'm closing this PR and will open another one with this fix, plus the pngquant fix, so we can tackle both problems at once.

**Pull request closed without merging**
