### PR TITLE
framework: new docker image based on Debian Stretch

### PR DESCRIPTION
**Pull request by ymartin59**
_Motivation:_ Get recent Meson to build recent fuse for sshfs (synocli-net)

Docker image is far lighter that previous one on Jessie because I discarded most documentation tooling (mainly latex) with `--no-install-recommends`

### CODE REVIEW

**Comment by ymartin59** [comment]
Mercurial built with that image.

**Comment by ymartin59** [comment]
@m4tt075 I am interested in feedback about this new docker image - if you may run it for your future local builds (ffmpeg, tvendhead...)

**Comment by m4tt075** [comment]
Oh yes. And this is most likely what I'd need to meet the `CMake 3.1+` dependency in #3575. Unfortunately, I can't use Docker locally and test this, but is there a `docker pull` command to tell travis to pull this dockerfile instead of  from `synocommunity/spksrc`?

**Comment by ymartin59** [comment]
I am intrigued about "I can't use Docker locally"... Is there any way I may help about it?

You may use "docker build -t synocommunity/spksrc:stretch - < Dockerfile" command to create image "spksrc:stretch" BUT I hope travis may have some caching mechanism to avoid building that 700 MiB image each time...

**Comment by ymartin59** [comment]
If I understand well, you run Linux in Virtual Box - so there is no technical reason why you may not install "docker" package in your Linux distribution to test that image.

**Comment by ymartin59** [comment]
... ffmpeg is building - I guess it means a "OK" for this image ... but I guess I have to request @Diaoul for grants to push a new image into Docker Hub.

**Comment by Diaoul** [comment]
I'll look into it this evening.

**Comment by Diaoul** [comment]
If this gets merged the image will automatically be published on Docker Hub as it is an automated build. Do you need both images?

**Comment by ymartin59** [comment]
If there is a way to tag current "jessie", we may keep access to it from Travis. By the way I can rebuild it for local use.
Thank you for help.
Yves

**Comment by Diaoul** [comment]
It seems it's not possible to tag from Docker Hub. Give me your Docker id here or by email, I'll grant you permission.

**Pull request merged**
