### PR TITLE
Add Letsencrypt command available to generate SSL certificate

### PR DESCRIPTION
**Pull request by lexyan**
Letsencrypt available for Synology, successfully tested on DS214play.
Need to stop Webserver before using command.
I use it like this in this script :
[renewSSL.sh.txt](https://github.com/SynoCommunity/spksrc/files/67811/renewSSL.sh.txt)

### CODE REVIEW

**Comment by AustinSaintAubin** [comment]
You might find the following useful in creating your app.
My script if very much in beta but would help you in making something that would require less user intervention.

I have created a script that works with a docker container ([dockette/letsencrypt](https://hub.docker.com/r/dockette/letsencrypt/)) to create the certs.
It does not require that the web servers go offline; it does restart the web service after it installs the new cert.

Process for using Lets Encrypt:

  1. ./  # Run script to setup for LetEncrypt AUTH. (Script will pause for you so you can run docker)
  2. Configure & run the Docker Container ([dockette/letsencrypt](https://hub.docker.com/r/dockette/letsencrypt/))
    - I have tested this container, others might work just as well.
    - VOLUME: /web/.well-known/acme-challenge /var/www/acme-certs/.well-known/acme-challenge [RW]
    - VOLUME: /docker/letsencrypt/certs /var/www/certs [RW]
    - ENVIRONMENT: DOMAINS = mydomain.com www.mydoamin.com nas.mydomain.com (all of these domains point to my Sinology NAS in Web Services or NAS Login)
    - ENVIRONMENT: EMAIL = your.email@emailserver.com
    - PORTS: DOES NOT MATTER... you will be making the volumes in docker to your sinology web services. Docker container will not be connected to over network for auth.
  3. Finish running script in step #1.

letsencrypt-synology_TEST.sh
```
#!/bin/sh
# RUN COMMAND: ./letsencrypt-synology_TEST.sh
# DATE: 20/12/2015

# Notes:
# Redirect to HTTPS while ignoring .well-known/acme-challenge for redirects
RewriteCond %{SERVER_PORT} 80
RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/?
RewriteRule ^(.*)$ https://%{SERVER_NAME}/$1 [R=301,L]
# - - - - - - - - - - - - - - - - - - -
# User Defined Varables

# Dynamic Varables
external_host_ip=$(/bin/get_key_value /etc/synoinfo.conf external_host_ip)
letsencrypt_certs_directory="/volume1/docker/letsencrypt/certs/$external_host_ip"
httpd_vhost_conf_user_file="/etc/httpd/sites-enabled-user/httpd-vhost.conf-user"
httpd_ssl_vhost_conf_user_file="/etc/httpd/sites-enabled-user/httpd-ssl-vhost.conf-user"
httpd_ssl_vhost_conf_user_domains="$(grep "ServerName" "$httpd_ssl_vhost_conf_user_file" | cut -d ' ' -f 2)"  # Get domains in httpd-ssl-vhost.conf-user
httpd_ssl_vhost_conf_user_domains=$(echo $httpd_ssl_vhost_conf_user_domains|tr -d '\n')  # Remove Carriage Returns

# Download and Setup LetsEncrypt Client
# cd /volume1/active_system/letsencrypt
# #wget https://github.com/letsencrypt/letsencrypt/archive/v0.1.1.zip
# git clone https://github.com/letsencrypt/letsencrypt
# cd letsencrypt

# Setup "well-known" challenge redirects for HTTPS Web Services
echo "ALL Domains: $external_host_ip $httpd_ssl_vhost_conf_user_domains"
echo "NAS Domain: $external_host_ip"
echo "Web Service Domains: $httpd_ssl_vhost_conf_user_domains"

# Check if Redirect for /.well-known/acme-challenge is in httpd-ssl-vhost.conf-user, if not, then add it.
if grep -q "Alias /.well-known/acme-challenge" "$httpd_ssl_vhost_conf_user_file"; then
    echo "Redirect found, no need to edit: $httpd_ssl_vhost_conf_user_file"
else
    echo "Redirect NOT found in: $httpd_ssl_vhost_conf_user_file"
    echo "Writing Redirect for /.well-known/acme-challenge in: $httpd_ssl_vhost_conf_user_file"

    # Adding Redirect for /.well-known/acme-challenge is in httpd-ssl-vhost.conf-user for each domain found.
#     sed -i -e "/\ServerName*/a Redirect 301 /.well-known/acme-challenge http://$external_host_ip/.well-known/acme-challenge" /etc/httpd/sites-enabled-user/httpd-ssl-vhost.conf-user
    sed -i -e "/\ServerName*/a Alias /.well-known/acme-challenge /var/services/web/.well-known/acme-challenge" /etc/httpd/sites-enabled-user/httpd-ssl-vhost.conf-user
    cat /etc/httpd/sites-enabled-user/httpd-ssl-vhost.conf-user
fi

# Check if Redirect for /.well-known/acme-challenge is in httpd-vhost.conf-user, if not, then add it.
if grep -q "Alias /.well-known/acme-challenge" "$httpd_vhost_conf_user_file"; then
    echo "Redirect found, no need to edit: $httpd_vhost_conf_user_file"
else
    echo "Redirect NOT found in: $httpd_vhost_conf_user_file"
    echo "Writing Redirect for /.well-known/acme-challenge in: $httpd_vhost_conf_user_file"

    # Adding Redirect for /.well-known/acme-challenge is in httpd-vhost.conf-user for each domain found.
#     sed -i -e "/\ServerName*/a Redirect 301 /.well-known/acme-challenge http://$external_host_ip/.well-known/acme-challenge" /etc/httpd/sites-enabled-user/httpd-vhost.conf-user
    sed -i -e "/\ServerName*/a Alias /.well-known/acme-challenge /var/services/web/.well-known/acme-challenge" /etc/httpd/sites-enabled-user/httpd-vhost.conf-user
    cat /etc/httpd/sites-enabled-user/httpd-vhost.conf-user
fi


# System httpd
#cat /etc/init/httpd-sys.conf
#cat /etc/httpd/conf/httpd.conf-sys


# Run Docker Contained LetsEncrypt
echo "[ Running LetsEncrypt Docker Container ]"
# http://blog.pavelsklenar.com/how-to-install-and-use-docker-on-synology/
# docker pull dockette/letsencrypt  # pull / update docker image
# docker
# docker
# docker

echo "PLEASE CONFIGURE & RUN YOUR DOCKER CONTAINER [MANUALLY] NOW"
read -p "Press [ENTER] key to continue script..."



# Certicate Backup/Copy Fuction
file_backup_copy() {
	echo "~ - - - - - - - - - - - - - - - - - - - ~"

	# Create Backup
	echo "Creating Backup: $2.bak"
	cp "$2" "$2.bak"

	# Output Destination
	echo "Current File: $2"
	cat "$2"

	# Copy Source to Dest
	echo "Coping Source to Destination: ($1) -> ($2)"
	cp "$1" "$2"

	# Output Destination / As is Overwriten by Source
	echo "Current File: $2"
	cat "$2"

	echo "-----------------------------------------"
}

# SSL Systen
sslcrtdir="/usr/syno/etc/ssl/ssl.crt"
sslcsrdir="/usr/syno/etc/ssl/ssl.csr"
sslkeydir="/usr/syno/etc/ssl/ssl.key"
sslcadir="/usr/syno/etc/ssl/ssl.intercrt"

# Server Key
echo "[ Copying LetsEncrypt Server Key ]"
file_backup_copy "$letsencrypt_certs_directory/privkey.pem" "$sslkeydir/server.key"

# Server Cert
#openssl x509 -inform PEM -in /usr/syno/etc/ssl/ssl.crt/server.crt  -text
echo "[ Copying LetsEncrypt Server Cert ]"
file_backup_copy "$letsencrypt_certs_directory/cert.pem" "$sslcrtdir/server.crt"

# CA Cert (CHAIN)
echo "[ Copying LetsEncrypt CA Cert ]"
file_backup_copy "$letsencrypt_certs_directory/chain.pem" "$sslcadir/server-ca.crt"


# Set Permisions
chmod 755 $sslcrtdir
chmod 755 $sslcsrdir
chmod 700 $sslkeydir
chmod 777 $sslcadir
chmod 400 $sslcrtdir/*
chmod 400 $sslcsrdir/*
chmod 400 $sslkeydir/*
chmod 777 $sslcadir/*

# Restart Web Services
# DEBUG: ls /etc/init/
# DEBUG: cat /var/log/upstart/httpd-user.log
/sbin/initctl stop httpd-user
/sbin/initctl start httpd-user

/sbin/initctl stop httpd-sys
/sbin/initctl start httpd-sys

/sbin/initctl webdav-httpd-ssl stop
/sbin/initctl webdav-httpd-ssl start
```

**Comment by lexyan** [comment]
That's great if you can install Docker on your NAS, but it's not available on mine.

**Comment by AustinSaintAubin** [comment]
My point was for you to use sections of the script to make your package more functional. Like having it install the new cert and restart web services.

**Comment by lexyan** [comment]
Thank's AustinSaintAubin,
I rewrite your script to not use Docker
It works for me but need test from others
	
	#!/bin/sh
	# RUN COMMAND: ./letsencrypt-synology_TEST.sh
	# DATE: 22/12/2015

	# Notes:
	# Redirect to HTTPS while ignoring .well-known/acme-challenge for redirects
	#RewriteCond %{SERVER_PORT} 80
	#RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/?
	#RewriteRule ^(.*)$ https://%{SERVER_NAME}/$1 [R=301,L]
	# - - - - - - - - - - - - - - - - - - -
	# User Defined Varables
	lea_cmd="/usr/local/letsencrypt/env/bin/letsencrypt"
	lea_opt="certonly -t  --expand --agree-tos --rsa-key-size 4096 --webroot  "

	# Dynamic Varables
	external_host_ip=$(/bin/get_key_value /etc/synoinfo.conf external_host_ip)

	httpd_vhost_conf_user_file="/etc/httpd/sites-enabled-user/httpd-vhost.conf-user"
	httpd_ssl_vhost_conf_user_file="/etc/httpd/sites-enabled-user/httpd-ssl-vhost.conf-user"
	httpd_ssl_vhost_conf_user_domains="$(grep "ServerName" "$httpd_ssl_vhost_conf_user_file" | sed -e 's/^[[:space:]]*//' | cut -d ' ' -f 2)"  # Get domains in httpd-ssl-vhost.conf-user
	httpd_ssl_vhost_conf_user_domains="$external_host_ip www.$external_host_ip $httpd_ssl_vhost_conf_user_domains"
	httpd_ssl_vhost_conf_user_domains=$(echo $httpd_ssl_vhost_conf_user_domains|tr -d '\n')  # Remove Carriage Returns
	letsencrypt_user_domains="-d $external_host_ip -d $external_host_ip"

	# Test if vhost are accessible from outside
	for host in $httpd_ssl_vhost_conf_user_domains
	do
	echo "Testing $host"
	nslookup $host
	# Host found in dns
	if [ $? -eq 0 ]
	then
		#Add it to the list of host
		letsencrypt_user_domains="$letsencrypt_user_domains -d $host"
	fi
	done

	letsencrypt_certs_directory="/volume1/letsencrypt/certs/$external_host_ip"
	#letsencrypt_user_domains=$(grep "ServerName" "$httpd_ssl_vhost_conf_user_file" | sed -e 's/^[[:space:]]*//' | cut -d ' ' -f 2 | sed -e 's/^/ -d /' | tr -d '\n') # Add -d in front of each host and Remove Carriage Returns
	lea_opt=$(echo $lea_opt --email admin@$external_host_ip --webroot-path /var/services/web $letsencrypt_user_domains --config-dir $letsencrypt_certs_directory --work-dir $letsencrypt_certs_directory --logs-dir $letsencrypt_certs_directory)


	# Download and Setup LetsEncrypt Client
	# cd /volume1/active_system/letsencrypt
	# #wget https://github.com/letsencrypt/letsencrypt/archive/v0.1.1.zip
	# git clone https://github.com/letsencrypt/letsencrypt
	# cd letsencrypt

	# Setup "well-known" challenge redirects for HTTPS Web Services
	echo "ALL Domains: $external_host_ip $httpd_ssl_vhost_conf_user_domains"
	echo "NAS Domain: $external_host_ip"
	echo "Web Service Domains: $httpd_ssl_vhost_conf_user_domains"

	# Check if Redirect for /.well-known/acme-challenge is in httpd-ssl-vhost.conf-user, if not, then add it.
	if grep -q "Alias /.well-known/acme-challenge" "$httpd_ssl_vhost_conf_user_file"; then
		echo "Redirect found, no need to edit: $httpd_ssl_vhost_conf_user_file"
	else
		echo "Redirect NOT found in: $httpd_ssl_vhost_conf_user_file"
		echo "Writing Redirect for /.well-known/acme-challenge in: $httpd_ssl_vhost_conf_user_file"

		# Adding Redirect for /.well-known/acme-challenge is in httpd-ssl-vhost.conf-user for each domain found.
	#     sed -i -e "/\ServerName*/a Redirect 301 /.well-known/acme-challenge http://$external_host_ip/.well-known/acme-challenge" /etc/httpd/sites-enabled-user/httpd-ssl-vhost.conf-user
		sed -i -e "/\ServerName*/a Alias /.well-known/acme-challenge /var/services/web/.well-known/acme-challenge" /etc/httpd/sites-enabled-user/httpd-ssl-vhost.conf-user
		sed -i -e "/\ServerName*/a ProxyPass /.well-known/acme-challenge ! " /etc/httpd/sites-enabled-user/httpd-ssl-vhost.conf-user
		cat /etc/httpd/sites-enabled-user/httpd-ssl-vhost.conf-user
		modified=1
	fi

	# Check if Redirect for /.well-known/acme-challenge is in httpd-vhost.conf-user, if not, then add it.
	if grep -q "Alias /.well-known/acme-challenge" "$httpd_vhost_conf_user_file"; then
		echo "Redirect found, no need to edit: $httpd_vhost_conf_user_file"
	else
		echo "Redirect NOT found in: $httpd_vhost_conf_user_file"
		echo "Writing Redirect for /.well-known/acme-challenge in: $httpd_vhost_conf_user_file"

		# Adding Redirect for /.well-known/acme-challenge is in httpd-vhost.conf-user for each domain found.
	#     sed -i -e "/\ServerName*/a Redirect 301 /.well-known/acme-challenge http://$external_host_ip/.well-known/acme-challenge" /etc/httpd/sites-enabled-user/httpd-vhost.conf-user
		sed -i -e "/\ServerName*/a Alias /.well-known/acme-challenge /var/services/web/.well-known/acme-challenge" /etc/httpd/sites-enabled-user/httpd-vhost.conf-user
		sed -i -e "/\ServerName*/a ProxyPass /.well-known/acme-challenge ! " /etc/httpd/sites-enabled-user/httpd-vhost.conf-user
		cat /etc/httpd/sites-enabled-user/httpd-vhost.conf-user
		modified=1
	fi

	# configuration files have been modified so we need to restart the webserver for user
	if [ -n "$modified" ]
	/sbin/initctl stop httpd-user
	/sbin/initctl start httpd-user
	fi


	# System httpd
	#cat /etc/init/httpd-sys.conf
	#cat /etc/httpd/conf/httpd.conf-sys

	# we create the destination directory if it not exist
	mkdir -p "$letsencrypt_certs_directory"

	$lea_cmd $lea_opt

	# Run Docker Contained LetsEncrypt
	#echo "[ Running LetsEncrypt Docker Container ]"
	# http://blog.pavelsklenar.com/how-to-install-and-use-docker-on-synology/
	# docker pull dockette/letsencrypt  # pull / update docker image
	# docker
	# docker
	# docker

	#echo "PLEASE CONFIGURE & RUN YOUR DOCKER CONTAINER [MANUALLY] NOW"
	#read -p "Press [ENTER] key to continue script..."



	# Certicate Backup/Copy Fuction
	file_backup_copy() {
		echo "~ - - - - - - - - - - - - - - - - - - - ~"

		# Create Backup
		echo "Creating Backup: $2.bak"
		cp "$2" "$2.bak"

		# Output Destination
		echo "Current File: $2"
		cat "$2"

		# Copy Source to Dest
		echo "Coping Source to Destination: ($1) -> ($2)"
		cp "$1" "$2"

		# Output Destination / As is Overwriten by Source
		echo "Current File: $2"
		cat "$2"

		echo "-----------------------------------------"
	}

	# SSL Systen
	sslcrtdir="/usr/syno/etc/ssl/ssl.crt"
	sslcsrdir="/usr/syno/etc/ssl/ssl.csr"
	sslkeydir="/usr/syno/etc/ssl/ssl.key"
	sslcadir="/usr/syno/etc/ssl/ssl.intercrt"

	# Server Key
	echo "[ Copying LetsEncrypt Server Key ]"
	file_backup_copy "$letsencrypt_certs_directory/privkey.pem" "$sslkeydir/server.key"

	# Server Cert
	#openssl x509 -inform PEM -in /usr/syno/etc/ssl/ssl.crt/server.crt  -text
	echo "[ Copying LetsEncrypt Server Cert ]"
	file_backup_copy "$letsencrypt_certs_directory/cert.pem" "$sslcrtdir/server.crt"

	# CA Cert (CHAIN)
	echo "[ Copying LetsEncrypt CA Cert ]"
	file_backup_copy "$letsencrypt_certs_directory/chain.pem" "$sslcadir/server-ca.crt"


	# Set Permisions
	chmod 755 $sslcrtdir
	chmod 755 $sslcsrdir
	chmod 700 $sslkeydir
	chmod 777 $sslcadir
	chmod 400 $sslcrtdir/*
	chmod 400 $sslcsrdir/*
	chmod 400 $sslkeydir/*
	chmod 777 $sslcadir/*

	# Restart Web Services
	# DEBUG: ls /etc/init/
	# DEBUG: cat /var/log/upstart/httpd-user.log
	/sbin/initctl stop httpd-user
	/sbin/initctl start httpd-user

	/sbin/initctl stop httpd-sys
	/sbin/initctl start httpd-sys

	/sbin/initctl webdav-httpd-ssl stop
	/sbin/initctl webdav-httpd-ssl start

**Comment by AustinSaintAubin** [comment]
Glad it was useful. Look forward to your app.

**Comment by Anaximelis** [comment]
Building the package i ran always in error building 'cffi'
<pre><code>Processing setuptools-19.1.1-py2.7.egg
Removing /spksrc/native/python/work-native/install/usr/local/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg
Copying setuptools-19.1.1-py2.7.egg to /spksrc/native/python/work-native/install/usr/local/lib/python2.7/site-packages
setuptools 19.1.1 is already the active version in easy-install.pth
Installing easy_install script to /spksrc/native/python/work-native/install/usr/local/bin
Installing easy_install-2.7 script to /spksrc/native/python/work-native/install/usr/local/bin

Installed /spksrc/native/python/work-native/install/usr/local/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg
Processing dependencies for setuptools==19.1.1
Finished processing dependencies for setuptools==19.1.1
--2015-12-22 17:59:24--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 185.31.17.175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|185.31.17.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1412744 (1.3M) [text/x-python]
Saving to: `STDOUT'

100%[=====================================================================================================================>] 1,412,744    671K/s   in 2.1s

2015-12-22 17:59:27 (671 KB/s) - written to stdout [1412744/1412744]

Requirement already up-to-date: pip in /spksrc/native/python/work-native/install/usr/local/lib/python2.7/site-packages
Collecting cffi==1.3.1
  Using cached cffi-1.3.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pycparser in ./work-native/install/usr/local/lib/python2.7/site-packages (from cffi==1.3.1)
Building wheels for collected packages: cffi
  Running setup.py bdist_wheel for cffi
  Complete output from command /spksrc/native/python/work-native/install/usr/local/bin/python -c "import setuptools;__file__='/tmp/pip-build-ldwh3f/cffi/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmppeUvOppip-wheel-:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/cffi
  copying cffi/gc_weakref.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/recompiler.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/_cffi_include.h -> build/lib.linux-x86_64-2.7/cffi
  copying cffi/parse_c_type.h -> build/lib.linux-x86_64-2.7/cffi
  running build_ext
  building '_cffi_backend' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/c
  /spksrc/toolchains/syno-evansport-5.2/work/i686-pc-linux-gnu/bin/i686-pc-linux-gnu-gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/spksrc/spk/letsencrypt/work-evansport-5.2/install//usr/local/letsencrypt/include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/spksrc/spk/letsencrypt/work-evansport-5.2/install//usr/local/letsencrypt/include -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/spksrc/native/python/work-native/install/usr/local/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
  In file included from /spksrc/native/python/work-native/install/usr/local/include/python2.7/Python.h:58:0,
                   from c/_cffi_backend.c:2:
  /spksrc/native/python/work-native/install/usr/local/include/python2.7/pyport.h:886:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
  compilation terminated.
  error: command '/spksrc/toolchains/syno-evansport-5.2/work/i686-pc-linux-gnu/bin/i686-pc-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cffi
Failed to build cffi
</code></pre>

**Comment by lexyan** [comment]
@Anaximelis : You need to compile native/python alone before trying to compile packages depending on.

**Comment by Anaximelis** [comment]
Ok. Setup a new docker container and compiled the package for my DS214play (evansport). Package seems to be ok but on calling '/usr/local/letsencrypt/env/bin/letsencrypt' there is an error:
<pre>
 cli_handler = cli_handler_factory(args, level, fmt)
  File "/usr/local/letsencrypt/env/lib/python2.7/site-packages/letsencrypt/cli.py", line 1265, in _cli_log_handler
    handler = log.DialogHandler()
  File "/usr/local/letsencrypt/env/lib/python2.7/site-packages/letsencrypt/log.py", line 29, in __init__
    self.d = dialog.Dialog() if d is None else d
  File "/usr/local/letsencrypt/env/lib/python2.7/site-packages/dialog.py", line 1013, in __init__
    self._dialog_prg = _path_to_executable(dialog)
  File "/usr/local/letsencrypt/env/lib/python2.7/site-packages/dialog.py", line 477, in _path_to_executable
    "can't find the executable for the dialog-like "
ExecutableNotFound
</pre>

**Comment by lexyan** [comment]
You can't start the GUI from the command line, try to invoke letsencrypt command with '-t' arg

**Comment by Anaximelis** [comment]
<pre>
 -t, --text            Use the text output instead of the curses UI.
                        (default: False)
</pre>
good idea :).

On DSM 6.0 the apache2 files are no longer stored in '/etc/httpd/' so i can`t test the script. Webstation is now a app.

Tomorrow ich will compile it for my older DS213 and test.

**Comment by lexyan** [comment]
When the DSM6 source wil lbe released, i'll modify the requirement to add WebStation and correct the path for the files.

The script is just here to automate the process but you can invoke the command from the command line. type 'letsencrypt -t help' to see available parameters

**Comment by lexyan** [comment]
I just compile it for DS213 => https://www.dropbox.com/s/n2dlupnp4evhrzr/letsencrypt_88f6281-5.2_0.1.1-1.spk?dl=0

**Comment by Anaximelis** [comment]
Letsencrypt is running well. 
For my test system a HP Gen8 with XPenoBoot (bromolow) i had made some changes on [letsencrypt-synology.sh](https://github.com/Anaximelis/spksrc/blob/master/spk/letsencrypt/src/letsencrypt-synology.sh) script.

**Comment by Anaximelis** [comment]
Nice work.

I have made a few thoughts.
1. I think to renew the cert the client must run again. Somebody knows a way to add conjobs by setup?
2. A GUI would be fine. The developerhandbook says php with admin login-check is possible. My PHP skill is even better then bash. Will test the possibility.
3. A Backupoption for the certs by deinstalling package is needed.
4. Does the letsencrypt client send a exitcode? Stop the script if the server auth faild.

**Comment by Anaximelis** [comment]
Synology added LetsEncrypt Support in DSM 6.0-7274 (Beta). They don`t have autodetect for used hostnames but the core is running.
I worked on a legancy GUI for the package. No i can throw it in the garbage.

**Comment by Diaoul** [comment]
That is somewhat an unexpected feature of DSM 6.0. I wish Synology would communicate more on the topic...

**Comment by JvdW** [comment]
I downloaded and test this on my DS214play with DSM-5.2 and had to modify the script a little.
If external_host_ip is set then it is put into the letsencrypt commandline and it will error on that, an ip address isn't a fqdn according to letsencrypt :-)
That same variable is also used to create the directory under /volume1/letsencrypt/data and since the certs are in $fqdn it won't copy them over.
Maybe its my configuration of my DS thats 'wrong' but it works now.

**Comment by ymartin59** [comment]
@KaraokeStu Completely outdated. Please close.

**Pull request closed without merging**
