### PR TITLE
Update Jackett to 0.10.589

### PR DESCRIPTION
**Pull request by favoretti**
_Motivation:_ Update Jackett to the latest version. A lot of trackers are updated since the version that's currently available.
_Linked issues:_ Optionally, add links to existing issues or other PR's

### Checklist
- [x] Build rule `all-supported` completed successfully (currently running, will report as it completes, x64 is successful)
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
Which version of Mono have you used for your tests?

**Comment by m4tt075** [comment]
Also, why could you not use the internal upgrade function of the pacakge, that you can reach via the web-interface? Did it fail? If so, how?

**Comment by favoretti** [comment]
> Also, why could you not use the internal upgrade function of the pacakge, that you can reach via the web-interface? Did it fail? If so, how?

It just didn't do anything. it logged the fact that there was a new version and sat there quietly.

**Comment by favoretti** [comment]
> Which version of Mono have you used for your tests?

root@keeper:/volume1/@appstore/nzbdrone# /usr/local/mono/bin/mono --version
Mono JIT compiler version 5.8.0.108 (tarball Sat Feb 24 09:55:00 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

**Comment by favoretti** [comment]
`all-supported` was successful. Took a while, since I've never built all the toolchains.

**Comment by m4tt075** [comment]
@favoretti Thanks for your contribution! I can confirm that my existing `Jackett` installation broke as well. I've not been able to run it or upgrade it internally. I can confirm that at least all supported 6.1 and 6.2 toolchains build successfully. I've been able to cleanly install your package on my XPE6.1 test system and upgrade it internally to the latest release again. Code changes are straight-forward and look good.
Please just fix the package version counting, and this is ready to go in.

**Comment by favoretti** [comment]
@m4tt075 Fixed. Thanks!

**Comment by m4tt075** [comment]
@ymartin59 I'd like to offer stepping up, merging and publishing "straight-forward" package upgrades, like this one, in the future. Would that be ok for you? And if so, could you let me know how to publish? I've no idea how to do that currently...

**Comment by ymartin59** [comment]
@m4tt075 Of course, already did it with Safhire, that is opportunity for me to write processes in wiki...

**Comment by m4tt075** [comment]
Thanks, both. Will publish as soon as I'll learn how to do it...

**Comment by rp4k** [comment]
I have beta packages enabled but I still don't see jackett at all  I see other betas in the community repo.  why am I having this weird issue. I did a full restart and I removed the community repo and reinstalled it and ticked the box for betas.  this is really weird.

**Pull request merged**
