### PR TITLE
update ffmpeg to 5.0.2

### PR DESCRIPTION
**Pull request by mxwi**
## Description

update ffmpeg to 5.0.2

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
Hi @mxwi thnx for initiating this.  Although bare with me, while being indeed overdue this will require a lot more attention than you might anticipate... :
1. It requires a strategy pertaining to building : `comskip`, `chromaprint`, `tvheadend` depends upon building with FFMPEG4 and are not compatible with newer FFMPEG5 due to removal of deprecated API.  This means it requires a new directory specific for ffmpeg5 while keeping the older ffmpeg4 as dependency for incompatible packages.
2. It also requires a strategy pertaining to naming: either we leave `ffmpeg` as is or force-rename to `ffmpeg4` (along with adapting all dependent packages).  Which then allows adding either a new `ffmpeg` or `ffmpeg5` package online.
3. There are tons of patches for `ffpmeg4` which brought greater alignment with both Synology and Jellyfin and others.  These will require an in-depth review... Or strategically we restart from close to scratch, food for thoughts I guess.

Having said that, I was planning on it once `tvheadend` would be migrated to ffmpeg5 but work is still unfinised https://github.com/tvheadend/tvheadend/pull/1460.   Considering `jellyfin` it may be a good idea to start planning for a ffmpeg5 release anyhow.

**Comment by mxwi** [comment]
ok - then maybe this is out of my scope. I am new with collaborating with git and discover many new things. Maybe I was to quick with this, sorry.

**Comment by nyanmisaka** [comment]
Hi @th0ma7 It would be better to add a new package `ffmpeg5` as each FFmpeg major release can make breaking changes. As for `chromaprint`, they have updated to support FFmpeg 5.x in this [commit](https://github.com/acoustid/chromaprint/pull/120).

We renamed the new deb package to `jellyfin-ffmpeg5` to ensure compatibility. There are tons of improvements in terms of the hardware transcoding in our patches, as well as the newly supported Dolby Vision to SDR tone-mapping.

**Comment by th0ma7** [comment]
And there where patches for tvheadend metged yesterday for stopping using deprecated APIs but I don't think it is yet conplete (nor there was a new release published for chromaprint).

Timing is probably right to initiate work on this but it's a really large codebase and will require many cycles to get through.

I'll see what i can do in the weeks ahead to rearrange the code in preparation for both ffmpeg4 and 5.

**Comment by th0ma7** [comment]
Superseeded by #5620

**Pull request closed without merging**
