### PR TITLE
Update Gitea to v1.16.6

### PR DESCRIPTION
**Pull request by Wuszek**
## Description

Keep gitea up to date - v1.16.6

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created
- [x] Package upgrade completed successfully -> [https://github.com/Wuszek/spksrc/actions/runs/2202225909](https://github.com/Wuszek/spksrc/actions/runs/2202225909)

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by Wuszek** [comment]
Was there any sagnificant changes in pipelines or framework? This simple update should work like always, but instead it broke package during update.

**Comment by th0ma7** [comment]
There where a few changes but they shouldn't have impacted updates.  I just tested a bunch of packages and it worked out with no problems.  Having more details to share?

**Comment by Wuszek** [comment]
@th0ma7 sure, whatever you want, just give me some hints:

here we have synopgk.log from /var/log/

```
2022/04/21 15:57:27	upgrade gitea: begin to stop version 1.16.5-4
2022/04/21 15:57:27	upgrade gitea 1.16.5-4 Begin start-stop-status stop
2022/04/21 15:57:30	upgrade gitea 1.16.5-4 End start-stop-status stop ret=[0]
2022/04/21 15:57:30	upgrade gitea 1.16.5-4 Begin unload apparmor
2022/04/21 15:57:30	upgrade gitea 1.16.5-4 End unload apparmor ret=[0]
2022/04/21 15:57:30	upgrade gitea: stop version 1.16.5-4 successfully, result 0
2022/04/21 15:57:30	upgrade gitea 1.16.5-4 Begin preupgrade
2022/04/21 15:58:20	upgrade gitea 1.16.5-4 End preupgrade ret=[0]
2022/04/21 15:58:20	upgrade gitea 1.16.5-4 Begin preuninst
2022/04/21 15:58:20	upgrade gitea 1.16.5-4 End preuninst ret=[0]
2022/04/21 15:58:20	upgrade gitea 1.16.5-4 Begin /bin/rm -rf /volume1/@appstore/gitea
2022/04/21 15:58:27	upgrade gitea 1.16.5-4 End /bin/rm -rf /volume1/@appstore/gitea ret=[0]
2022/04/21 15:58:27	upgrade gitea 1.16.5-4 Begin postuninst
2022/04/21 15:58:27	upgrade gitea 1.16.5-4 End postuninst ret=[0]
2022/04/21 15:58:28	upgrade gitea: Uninstall 1.16.5-4 successfully
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 Begin preinst
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 End preinst ret=[0]
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 Begin /bin/rm -rf /volume1/@appstore/gitea
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 End /bin/rm -rf /volume1/@appstore/gitea ret=[0]
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/gitea
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/gitea ret=[0]
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 Begin /bin/mkdir -p /var/packages/gitea
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 End /bin/mkdir -p /var/packages/gitea ret=[0]
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/gitea/INFO
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/gitea/INFO ret=[0]
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 Begin /bin/rm -rf /var/packages/gitea/scripts
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 End /bin/rm -rf /var/packages/gitea/scripts ret=[0]
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/gitea/scripts
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/gitea/scripts ret=[0]
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 Begin /bin/rm -rf /var/packages/gitea/WIZARD_UIFILES
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 End /bin/rm -rf /var/packages/gitea/WIZARD_UIFILES ret=[0]
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/gitea/WIZARD_UIFILES
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 End /bin/mv -f /volume1/@tmp/pkginstall/WIZARD_UIFILES /var/packages/gitea/WIZARD_UIFILES ret=[0]
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 Begin /bin/rm -rf /var/packages/gitea/conf
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 End /bin/rm -rf /var/packages/gitea/conf ret=[0]
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/gitea/conf
2022/04/21 15:58:29	upgrade gitea 1.16.6-5 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/gitea/conf ret=[0]
2022/04/21 15:58:30	upgrade gitea 1.16.6-5 Begin postinst
2022/04/21 15:58:30	upgrade gitea 1.16.6-5 End postinst ret=[0]
2022/04/21 15:58:30	upgrade gitea 1.16.6-5 Begin postupgrade
2022/04/21 15:58:31	upgrade gitea 1.16.6-5 End postupgrade ret=[0]
2022/04/21 15:58:31	upgrade gitea from 1.16.5-4 to 1.16.6-5 failed
2022/04/21 15:58:31	upgrade gitea 1.16.6-5 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2022/04/21 15:58:31	upgrade gitea 1.16.6-5 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
```

**Comment by Wuszek** [comment]
/var/log/packages/gitea.log
it seems, that there was a problem with /volume1/git folder
indeed, I have one in this location (it has repos for gitea) but there was never any problem with this
```
2022/04/21 16:22:28	===> Step postinst. USER=gitea GROUP= SHARE_PATH=/volume1/git
2022/04/21 16:22:28	Begin save_wizard_variables
2022/04/21 16:22:28	End save_wizard_variables
2022/04/21 16:22:28	Configuring /volume1/git
2022/04/21 16:22:31	Error: share create failed.[0xE700 share_create.c:113]
2022/04/21 16:22:31	Lastest SynoErr=[share_db_get.c:31]
2022/04/21 16:22:31	SYNOShareGet failed. synoerr=[0x1400]
2022/04/21 16:22:31	Begin service_postinst
2022/04/21 16:22:31	End service_postinst
```

**Comment by Wuszek** [comment]
Ok, I made it work. The problem was me, not the package.

I did restore my backup some time ago, and didnt change permissions and ownership of shared folder /volume1/git

Once I changed everything to:
```
sudo chown -R sc-gitea: git/
sudo chmod -R 755 git/
```
it upgraded and works fine.

**Comment by th0ma7** [comment]
Glad it turns out all right, good catch!

**Comment by Wuszek** [comment]
@publicarray, @th0ma7 or other maintainer, could you merge? :)

**Review by th0ma7 — APPROVED** [review]

**Comment by publicarray** [comment]
@Wuszek would you like to become a maintainer?

**Comment by Wuszek** [comment]
@publicarray well, I could try and start from keeping Gitea up to date :)

**Comment by szonov** [comment]
Hello everybody, I have DSM 7 and found one thing with installing gitea from synocommunity package.

It works nice except git clone/push over ssh. After small investigation I found a reason, it can be usefull.
SC gitea in requirements has Git version from synocommunity package. But debugging ssh clone shows me that gitea can not find "git-receive-pack" or "git-upload-pack", which really exists after installing sc git, and placed in /usr/local/bin.
By some reasons (do not know why) sc gitea do not see  it. If I additionally install Synology's Git Server package  gitea's git clone/push over ssh starts to work. Synology's Git Server link their git binaries to /usr/bin and looks like sc gitea see it.
Since sc git has more actual version than synology's git version I just removed Synology's Git Server and make links `cd /usr/bin && ln -s /var/packages/git/target/bin/git* .`. After this  git over ssh start to work and used latest git binary.

My recommendations for everyone who installing this package to DSM 7 and trying to get working git over ssh

1. add sc-gitea user to administrators group (manual edit /etc/group). It is required since DSM 7 limits ssh to only users from this group
2. give appropriate shell to sc-gitea user (manual edit /etc/passwd). replace `/sbin/nologin` to for example `/bin/sh` for sc-gitea
3. link git binaries to /usr/bin directory `cd /usr/bin && ln -s /var/packages/git/target/bin/git* .`

thank you

**Comment by efussi** [comment]
@szonov I am not using ssh, but looking at https://github.com/SynoCommunity/spksrc/pull/5028#issuecomment-1008334103 and https://github.com/SynoCommunity/spksrc/pull/5071 I think it would be good to have the ssh setup documented somewhere. Or better yet, have Gitea install set it up for yo. Maybe through an option in the installer -- not sure what's possible here.

**Pull request merged**
