### PR TITLE
bottom: Update from version 0.6.8 to 0.8.0

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

The objective of this PR is to test rustc targets using an existing package.

Relates to #5284 in particular https://github.com/SynoCommunity/spksrc/pull/5284/files#r1117684182

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
@hgy59 in order to reproduce your issue I've recreated my container from scratch to ensure there isn't any pollution.  Now I'm updating a native rust package to see if all works all-right.

On my container all looks good and builds just fine (e.g. downloads proper rust targets as expected).

Are you able to replicate the issue with other rust cross packages?

**Comment by hgy59** [comment]
> Are you able to replicate the issue with other rust cross packages?

This fixes the build of vaultwarden and all diyspk that depend on rust (dua bat dutree exa fd ripgrep sd)
✅

**Comment by th0ma7** [comment]
awesome, glad to know it fixes your issue.
Want me to include the fix in this small PR so you then rebase against master?

**Comment by hgy59** [comment]
> Want me to include the fix in this small PR so you then rebase against master?

yes, please...

**Pull request merged**
