### PR TITLE
python: 2.7.15 update with dependencies

### PR DESCRIPTION
**Pull request by ymartin59**
_Motivation:_ Publish for aarch64 and vulnerability fixes
_Linked issues:_ #3546

### Checklist
- [] Build rule `all-supported` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

### CODE REVIEW

**Comment by Safihre** [comment]
Cool. Was just about to push a new SABnzbd update so this would be a nice fit!

**Comment by Safihre** [comment]
So what is going wrong here? I tried to build it on Travis but getting some download-error.

**Comment by ymartin59** [comment]
Hello. Sorry I forgot to comment status: build fails on "cryptography" wheel, probably because of versions mismatch in requirements.

**Comment by Safihre** [comment]
Pushed libsodium update, since listed version [was no longer available](https://download.libsodium.org/libsodium/releases/). Continue testing on now, got a new VM set up.

**Comment by ymartin59** [comment]
Thanks. Sorry but I am busy on FFmpeg v4 at the moment.

**Comment by Safihre** [comment]
Seems we are having the exact same problem @Diaoul had 5 years ago: https://github.com/pyca/cryptography/issues/1325
But I don't really understand the solution.. Should we go back to having `cryptography` as a `cross` maybe? Or just keep it at the older version, if that works?

**Comment by Safihre** [comment]
@ymartin59 I can confirm that lowering the `cryptography` version (and the rest in that section of `requirements.txt`) back to what they were for 2.7.14 fixes the compile.
I would suggest to just go back to those versions.

**Comment by ymartin59** [comment]
Hum. Something is strange - I have just clean "native/python" and "spk/python" and package has just been built properly `arch-x64-6.1`. Maybe the cryptography error comes from having left previous version compiled in "native/python"...

**Comment by Safihre** [comment]
It's the 32bit archs that fail to build.

**Comment by ymartin59** [comment]
I wonder if option would be to restore cross/cryptography removed recently https://github.com/SynoCommunity/spksrc/commit/6a071f8c24e2d067041fa4c362387668dfae9d46

**Comment by Safihre** [comment]
With the old requirements file I'm able to build all archs it seems. But can't test them all because for some reason it can't get all the sources when I run it on Travis. Maybe some source is blocking Travis..

**Comment by Safihre** [comment]
It seems Travis switched to some special NAT, resulting in the rotating of the external IP's of the build VM **during** the building: https://twitter.com/travisci/status/1085214062152159232

That's probably why the build process is failing with these download-errors. (CC @m4tt075)

**Comment by ymartin59** [comment]
@Safihre may you please push your additional commit on my PR here - you have permissions granted I guess - I recommend "hub" to checkout PR: https://hub.github.com/ then it cannot be easier.

**Comment by ymartin59** [comment]
@Safihre in fact it is also easy to cherry-pick commit from your branch...

**Comment by ymartin59** [comment]
I have been told it may be useless to "rebuild" python in each package only to build wheels for application requirements (what spksrc does right now) and that "crossenv" is a tool designed for such usage. Have you heard about it?
As far as I understand, when this python update will be ready, there is a high chance that all applications have to be rebuilt and pubilshed again, right?

**Comment by ymartin59** [comment]
OK, first steps. Compilation of "cryptography" wheel fails for ARMv8 (aarch64), I am investigating.

About "crossenv", proposal concerns "home assistant" - and probably "borgbackup" and "beets" can take benefits for it (when moved to python3)

**Comment by Safihre** [comment]
@ymartin59 any luck with `aarch64`?

**Comment by ymartin59** [comment]
@Safihre Sorry I am busy on framework refactoring #3595 to get ffmpeg and company published.

**Comment by ymartin59** [comment]
@chickenandpork May I request your help to achieve this PR? I do not understand why recent cryptography wheel no longer builds on ARM platforms and I am stuck here. Thank you in advance

**Comment by Safihre** [comment]
It does build on some ARM platforms, just not all..

**Comment by Safihre** [comment]
@chickenandpork are you looking into this or should I give it a try over the weekend?

**Comment by chickenandpork** [comment]
I’m not sure the problem, but I’ll have time I think around 06:00UTC (11 hrs from now).  If I’m going to get time to look, it tends to be 0600Z daily for a few hours

**Comment by chickenandpork** [comment]
Manually did a similar patch, trying builds now to see what it looks like.  I don't think I'll be able to debug the failure until tomorrow.

I'm worried about a few related changes we'll need: for example, because the `requirements.txt` has exact version matches (ie `virtualenv==16.1.0` not `virtualenv>=16`) that anything requiring `python` will need to have compatible `requirements.txt` or else `pip` will complain.

Eventually, might need to change the bare minimum of wheels versions, merge/ship that, and try after to bump versions across the board (ie bump all virtualenvs at once).  Dunno.

I'll still need to build after as well with my detection for all affected SPKs.  Dependencies sneak in, and there will probably be a number of SPKs that depend on `python`

**Comment by Safihre** [comment]
Since we make a virtualenv for each Python application within the SPK, the different versions listed in requirements don't need to clash.
The reason for the set version is because we need to list both the package and the dependencies, since we go around the regular pip system. And each new build of the python SPK should produce reproducible SPK's

**Comment by chickenandpork** [comment]
Thanks.  I’ve worked in embedded so I’m aware of why to use exact versions; my concern was mismatched exact versions, but I’d forgotten about virtualenv isolation.  Oops . :(  I kinda do that with containerd now :-/  (pre-k8s world)

**Comment by chickenandpork** [comment]
I've got builds running slowly since last night, so far it's built:
```
python_x64-6.1_2.7.15-20.spk
python_avoton-6.1_2.7.15-20.spk
python_88f6281-6.1_2.7.15-20.spk
python_aarch64-6.1_2.7.15-20.spk
python_alpine-6.1_2.7.15-20.spk
python_armada370-6.1_2.7.15-20.spk
python_armada375-6.1_2.7.15-20.spk
python_armada38x-6.1_2.7.15-20.spk
```

Where did you get the failure?  This is with a hand-done approximation of @ymartin59 's hard work, but it's not yet failing.

**Comment by Safihre** [comment]
Continuing in #3628

**Pull request closed without merging**
