### PR TITLE
Borgbackup v1.2.0 update

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  Progressing towards releasing borgbackup using python310.
_Linked issues:_  https://github.com/SynoCommunity/spksrc/commit/72866f653fcff3f6862a417545a070f618c2d907#diff-7b228d5ca562f5bc3b0ebfbbe98d851ed882feab3721fbb04b57ad844256eb78
_Upstream issue:_ https://github.com/borgbackup/borg/issues/6105

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by hgy59** [comment]
@th0ma7  AFAIU you can remove `cross/borgbackup` with this PR.

**Comment by th0ma7** [comment]
> AFAIU you can remove `cross/borgbackup` with this PR.

@hgy59 It's my intent but I'm waiting to confirm if PPC build can be sorted out upstream first https://github.com/borgbackup/borg/issues/6105.

**Comment by th0ma7** [comment]
@sunlei I've applied your 1.2.0 update patches over to my PR.  Can you test this and confirm it works as expected?

**Comment by th0ma7** [comment]
@hgy59 have you noticed a change of behavior recently with github archive packages?  It seems that md5sum|sha*sum varies at every downloads when using the usual url while using `archive/refs/tags` works as expected?  See fixes for `rnm` and `jpcre2` above.

**Comment by th0ma7** [comment]
Basic testing on `x64-7.0`, `armv7-7.0` and `armv5-6.1`
```
root@DSM7:/var/packages/borgbackup# /usr/local/bin/borg
borg       borgmatic  
root@DSM7:/var/packages/borgbackup# /usr/local/bin/borgmatic --version
1.5.23
```

**Pull request merged**
