### PR TITLE
Added `flexget` to the path since it now runs daemon only.

### PR DESCRIPTION
**Pull request by sebask**
This makes working with flexget from the cli a little bit easier.

### CODE REVIEW

**Comment by Dr-Bean** [comment]
We're probably not going to merge this, sorry. You can add the Flexget directory to PATH yourself:
```
PATH=/your/new/dir:$PATH
export PATH
```

**Comment by sebask** [comment]
Okay no problem. Just wondering, why?

**Comment by Diaoul** [comment]
Because /usr/local is shared within the whole system and this might result in conflicts. It is tolerated for CLI only packages to provide a symlink in /usr/local/bin but for packages with a GUI this is not necessary.

**Comment by Dr-Bean** [comment]
What @Diaoul said. To add to that: Even though the flexget package currently does not have a webui, that's not to say it won't return (eventually). That obviously won't occur with pure CLI-based applications.

I'll close the PR, but nonetheless thanks for your input :)

**Comment by sebask** [comment]
@Diaoul @Dr-Bean I agree, it makes a lot of sense. Thanks for sharing!

**Pull request closed without merging**
