### PR TITLE
cross-cc.mk: Fix slowness since previous fix

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

cross-cc.mk: Fix slowness noticed by @mreid-tt since previous fix

Fixes https://github.com/SynoCommunity/spksrc/pull/5995#issuecomment-1914757879

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [ ] Package update
- [x] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by mreid-tt** [comment]
> Initial testing seems to demonstrate it works well, do you mind confirming on your end before I merge?

Umm, given that I only build on GitHub testing would be difficult. My understanding is that I would need to rebase to the current master and then import your commit to be able to test it. Is this correct?

**Comment by mreid-tt** [comment]
@th0ma7, I did the rebase I suggested above and merged in your PR but so far the "Evaluating dependencies" is running for over 10 minutes which is unusual. Will continue to monitor at: https://github.com/SynoCommunity/spksrc/pull/5992/checks

**Comment by th0ma7** [comment]
wow, that took 1h59mins... this is odd.  Let me revisit this.

**Comment by mreid-tt** [comment]
> @mreid-tt do you have previous runs we can check on?

You can take a look at the previous successful builds which were all a few minutes until 2-3 days ago:
https://github.com/SynoCommunity/spksrc/actions/workflows/build.yml?query=is%3Asuccess+branch%3Afengoffice-update

**Comment by mreid-tt** [comment]
@th0ma7, thanks much for this. I have rebased my open PR #5992 and can confirm that the "Evaluate dependencies" step is back to taking the expected time (3m 24s on the last run).

**Comment by th0ma7** [comment]
Superseeded with https://github.com/SynoCommunity/spksrc/pull/6002

**Pull request closed without merging**
