### PR TITLE
[Help wanted] ruTorrent - Generic Service approach

### PR DESCRIPTION
**Pull request by Safihre**
I thought I could convert this package, but I need help. The changes between DSM5 and 6 in WebStation workings are still a mystery to me and I am not sure if I even want to dive into this.

If anyone wants to help me to figure out what is needed to get it to work I am happy to implement the code. In this issue (#2215) they have some information already that should get things rolling.
Problems I identified:

- [ ] Need somehow to force dependency on Web-Station and the PHP package (is Apache also needed?).
- [ ] I think the package-user needs to be added to `http` group, not 100% sure.
- [ ] Figure out what config-files need to be edited to add the `open_basedir`.
- [ ] Figure out the process to restart after the changes are made.
- [ ] Don't break anything on DSM5.

As mentioned above: I can help and do parts of the implementation, just need to know how to do it.

_Linked issues:_ #3062 #3016 #2805  #2766 #2751 #2392 #2240 #2215 #2206
 
### Checklist
- [] Build rule `all-supported` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

### CODE REVIEW

**Comment by Johnito** [comment]
Hello,

The rutorrent package is special : the user has to achieve several steps within DSM to make the package actually work. Do not forget the very same steps have to be achieved  **with the original syncommunity package**. If you do not do this, rutorrent will not work. This has nothing to do with your own compilation.

1) **Both official 'PHP7' and 'Apache HTTP Server 2.4' packages need to be installed.
2) The PHP profile created in webstation needs to have **curl** and **sockets** extensions checked in order for all rutorrent plugins to work (those are not checked by default).
3) A line needs to be added in /usr/local/etc/apache24/conf/httpd24.conf : _LoadModule auth_basic_module modules/mod_auth_basic.so (i do not know why, probably to be able to protect access)
4) open_basedir has to be personnalised indeed : /var/services/tmp:/var/services/web:/**usr/local/rutorrent:/volume1/mydownloadfolder**
5) The http group needs to have writing/reading rights on the folder rutorrent will use.

When everything is done, Apache HTTP Server 2.4 has to be stopped, and relaunched. This package is a real pain in the *** to configure but this is definitely worth it in my opnion since this client is by far the most performant and powerfull you can install on a Synology NAS. IMO, the only advanced setting here is editing httpd24.conf. If this can be done when installing, this would be a plus.

I'm at your disposal for any infos or tests.

**Comment by Safihre** [comment]
@Johnito Wow, that's a lot of steps. For actual decent package, this should all be automated during install.
I hope we can do 1 via the package's `INFO` file.
Is there a way to somehow locate the config-file and force the requirements you mention in 2?
3 we should be able to do with the info in #2215.
4 and 5 we should be able to do during install.

**Comment by Johnito** [comment]
If 3/4/5 can be automated, this already will be a huge improvement over the current package.

About the PHP thing, I am not sure i found the right setting file at all. The file having the required settings is obviously related to the PHP profile used by DSM/WebStation. I only found these three files ...

- /etc/php/php.ini
- /usr/local/etc/php70/php.ini
- /usr/local/etc/php70/php-fpm.conf

... but none seem to actually reflect the checked extensions in the Webstation PHP profile. etc/php/php.ini lists a few extensions, but they do not seem to be the ones i checked myself or i do not get it :

`[PHP]
engine = On
short_open_tag = On
asp_tags = Off
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
serialize_precision = 17
disable_functions =
disable_classes =
zend.enable_gc = On
expose_php = Off
max_execution_time = 240
max_input_time = 60
memory_limit = 128M
error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
display_startup_errors = Off
log_errors = On
log_errors_max_len = 1024
ignore_repeated_errors = Off
ignore_repeated_source = Off
report_memleaks = On
track_errors = Off
html_errors = Off
variables_order = "GPCS"
request_order = "GP"
register_argc_argv = Off
auto_globals_jit = On
post_max_size = 32M
default_mimetype = "text/html"
default_charset = "UTF-8"
include_path = "."
extension_dir = "/usr/lib/php/modules"
sys_temp_dir = "/var/services/tmp"
enable_dl = Off
file_uploads = On
upload_tmp_dir = "/var/services/tmp"
upload_max_filesize = 32M
max_file_uploads = 20
allow_url_fopen = On
allow_url_include = Off
default_socket_timeout = 60

extension = bcmath.so
extension = bz2.so
extension = curl.so
extension = iconv.so
extension = ldap.so
extension = mcrypt.so
extension = openssl.so
extension = pdo_sqlite.so
extension = posix.so
extension = phar.so
extension = shmop.so
extension = sockets.so
extension = sqlite3.so
extension = zip.so

extension = syno_compiler.so

[CLI Server]
cli_server.color = On

[Date]
date.timezone = Europe/Amsterdam

[Phar]
phar.readonly = Off

[mail function]
sendmail_path = /usr/bin/ssmtp -t
mail.add_x_header = On

[SQL]
sql.safe_mode = Off

[bcmath]
bcmath.scale = 0

[Session]
session.save_handler = files
session.save_path = "/var/services/tmp"
session.use_cookies = 1
session.use_only_cookies = 0
session.name = PHPSESSID
session.auto_start = 0
session.cookie_lifetime = 0
session.cookie_path = /
session.cookie_domain =
session.cookie_httponly =
session.serialize_handler = php
session.gc_probability = 1
session.gc_divisor = 1000
session.gc_maxlifetime = 1440
session.bug_compat_42 = Off
session.bug_compat_warn = Off
session.referer_check =
session.entropy_length = 0
session.cache_limiter = nocache
session.cache_expire = 180
session.use_trans_sid = 0
session.hash_function = 0
session.hash_bits_per_character = 5
url_rewriter.tags = "a=href,area=href,frame=src,input=src,form=fakeentry"
session.upload_progress.enabled = On
session.upload_progress.cleanup = On
session.upload_progress.prefix = "upload_progress_"
session.upload_progress.name = "PHP_SESSION_UPLOAD_PROGRESS"
session.upload_progress.freq = "1%"
session.upload_progress.min_freq = "1"
`

**Comment by Safihre** [comment]
I see here in PR #2591 that there is a way to force dependency on Web Station and PHP, good to know.

**Comment by ymartin59** [comment]
@Safihre OK for you if I go on with this?

**Comment by Safihre** [comment]
Sure, I tried a bit but didn't like the way this package would need to have hard code all these paths.
Or many manual steps of the user.

**Comment by ywyha** [comment]
你好，我的DS218J无法使用rutorrent，好郁闷，我看不懂英文。
Hello, my DS218J can not use rutorrent, so depressed, I do not understand English.

**Comment by lordvalium** [comment]
Can i help to accelerate the request in any way?

**Comment by ymartin59** [comment]
I find too complex at the moment. I am learning PHP application publication with simpler bicbucstriim package first before looking at ruTurrent

**Comment by lordvalium** [comment]
@ymartin59 what do you mean with too complex? To port that package?

**Comment by lordvalium** [comment]
looking forward on ruTorrent :)

**Comment by bolhaskutya** [comment]
Me too!

**Comment by ymartin59** [comment]
Review if following patch should be included too: #3110

**Comment by Safihre** [comment]
In 2 years I didn't make any progress so will close this. Probably somebody has to start from scratch..

**Comment by ymartin59** [comment]
@Safihre I prefer to go on from your work. I got it locally to work on it... later...

**Pull request closed without merging**
