### PR TITLE
Shairport Airplay Receiver

### PR DESCRIPTION
**Pull request by lost-carrier**
Hi there,

this is my first try to build a Synology package.

Since I have some AirPlay-enabled iDevices in use, as well as a Synology hooked via a USB soundcard to my amp, I wanted to use the storage as an AirPlay receiver. Synology provides various Apps that would stream TO AirPlay receivers, but nothing that would make the NAS act as an AirPlay receiver.

Luckly there's a project called "ShairPort" around (well, it's even @ github: https://github.com/abrasive/shairport). So I compiled shairport using your crosscompile framework. Works fine with on my DS1512+. However, there are some known issues:

1. shairport currently runs as root. I've tried to use a "shairport" user, but the /dev/snd and alsa-config are a bit messed-up in the DSM, so I could not allow any other user than root to play back via alsa without messing around with chgrp and chmod in /dev/snd/. Suggestions welcome.

2. avahi-deamon has to support avahi-publish and dbus. Did not apply any of that stuff http://blog.elsdoerfer.name/2011/05/15/shairport-on-synology-nas/ suggests and it runs fine on my box. However: no guaranty it will run on every box. Beta testers welcome.

3. the icon I used is from http://gnarld.com/how-to-use-airplay-with-your-ipad-2-iphone-4s-apple-tv/ - hope there's no copyright issue... (...graphically gifted contributions welcome. ;-) )

Cheers,
Losty

### CODE REVIEW

**Comment by lost-carrier** [comment]
@altimac great, thanks! Do you know a (similar easy) way to fix it to 16bit?

**Comment by altimac** [comment]
AFAIK it is already 16bit. What makes you think it is not 16b ?

**Comment by lost-carrier** [comment]
My M-DAC shows 24-bits in it's display. Depending on the soundcard?

**Comment by altimac** [comment]
And of course your source music file is 16 bits?
My DAC shows the sample frequency in facade, but not the bit wide value. I thought it was 16bits because Airplay protocol force 16b.

Also, remember that bit wideness is not very important (at least from 16 to 24b) since most of the time the gap is padded with zeros, whereas sampling freq is a major problem (upsampling is generally very bad as it creates harmonics).

**Comment by lost-carrier** [comment]
Hi everyone,

I just compiled and uploaded a new version "1.1.1-2" to http://home.losty.ch/webfilebrowser/share/shairport-goes-diskstation?key=d97c1ef3 .

It's compiled against the latest sources from SynoCommunity and includes @altimac 's suggestion. (It will report as 44.1KHz instead of 48kHz).

Don't be worried about the -5.1 following you architecture. The SynoCommunity project obviously included the DSM version into the arch-tag.

Cheers,
Losty

**Comment by colamage** [comment]
Have you looked at Shairport-sync? Don't know the necessary parts to run it but it works on Raspbian. Maybe it's possible to compile it for DSM? I've been trying to compile some stuff myself but never got any results, just a lot if missing output (this for Telldus-core).

**Comment by altimac** [comment]
Unfortunately 1.1.1-2 still generate cracklings at 44.1 Khz on my DS213 (but my DAC correctly displays 44.1)
It can NOT hear cracklings at 48Khz, but then it can't be considered an audiophile system since it requires upsampling from 44.1 (source is my iPhone) to 48Khz.

Again, the problem relies on alsa / alsa config, or (I doubt it) on the DS hardware itself.
I now also have a DS411j at my disposal. I'll try and report here.

**Comment by The-MAD-Virus** [comment]
damn my DS413 is curse ...

```bash
Starting Shairport a642a9f
Listening for connections.
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM default
FATAL: Alsa initialization failed: unable to open pcm device: No such file or directory

Shutting down...
```

**Comment by altimac** [comment]
Are you also running Audio Station? it is also needed (probably to configure the hardware?)

**Comment by tougher** [comment]
Thanks a billion for this package @lost-carrier ! My coworkers loves to be able to play DJs in the office :-D

**Comment by The-MAD-Virus** [comment]
@altimac in fact we still need to lunch "Audio Station". I'll check audio quality when in come back home.

@lost-carrier be the way thanks for your job to make it works for every one !

**Comment by The-MAD-Virus** [comment]
Yeah !!! it works ! no more distortion. Thanks again @lost-carrier

**Comment by altimac** [comment]
@The-MAD-Virus pardon my ignorance, where did you get the shairport log?
It immediately stop publishing the service as soon as I connect to it on my DS411j (works on my DS213 but with cracklings)

**Comment by colamage** [comment]
@altimac start it via ssh by  "./shairport -v".

**Comment by altimac** [comment]
Rebooting the DS fixed the problem. Thanks.
Unfortunately I still hear cracklings at 44.1Khz on my DS411j. 
Note that the 411j hardware is very similar to the DS213 :-(

**Comment by lost-carrier** [comment]
@tougher great to hear, thanks! Can you tell me what hardware you're running - just for my compatibility list @ https://www.evernote.com/shard/s198/sh/598561fd-5bed-4546-94b9-d2e3ed07fca6/7d2c3d24c2863824ceacfc871fad1091

**Comment by lost-carrier** [comment]
@The-MAD-Virus Thanks! For V1.1.1-2 we also have to thank @altimac a lot! Too bad it's still not working for him...

**Comment by lost-carrier** [comment]
@altimac Hm... that's strange. When you changed the setting in the alsa.conf yourself - did it work then? To be honest, I suspect something with the soundcard or its configuration. Can you try copying the Alsa configuration from Audio Station if that one is working for you. Also you can try experimenting with the following CLI options of the shairport binary...

```
Options for output alsa:
    -d output-device    set the output device [default*|...]
    -t mixer-type       set the mixer type [software*|hardware]
    -m mixer-device     set the mixer device ['output-device'*|...]
    -c mixer-control    set the mixer control [Master*|...]
    -i mixer-index      set the mixer index [0*|...]
    *) default option
```

I'm happy to include more generic settings in the package.

Although 44.1kHz is clearly the better choice for music, my DAC worked fine (without cracklings) for both settings (44.1kHz and 48kHz). Is there some other DAC you could try?

**Comment by lost-carrier** [comment]
@gruntpartystyle & @colamage sorry for getting back to you that late, but I just stumbled across another CLI option of shairport:

```
    -b FILL             set how full the buffer must be before audio output
                        starts. This value is in frames; default 220
```

...is that what you meant? Probably you can try to add some "-b 20" to /var/packages/shairport/scripts/start-stop-status . I agree it would make sense to have this configurable. I definitely have to find out someday how to make those bloody Synology configuration menus... ;-)

**Comment by gruntpartystyle** [comment]
Sounds like. Would be worth a shot. I try after work, too.

**Comment by tougher** [comment]
@lost-carrier We are using a DS213+ (FREESCALE QorIQ P1022). The sound card followed along with a portable Minidisc player!! It reports itself as `MD-Port DG2 MiniDisc Interface - Xitel` dmesg says `generic-usb 0003:09EF:0101.0001: input,hiddev104: USB HID v1.00 Device [XITEL MD-PORT AN1] on usb-0002:05:00.0-4/input2`
Shairport has been running without issues since I've installed v1.1.1 3 weeks ago :+1:

**Comment by gruntpartystyle** [comment]
So, I can confirm the change has direct influence on the delay. I changed from 220 to 55, which is from 2s to 0.5s. Works. maybe I will go even further down.

$SHAIRPORT --daemon --pidfile="$PID_FILE" --log=$SYNOPKG_TEMP_LOGFILE -b 55

**Comment by thunfischbrot** [comment]
Why not merge this pull request? Shairport is a very useful utility to have. Judging from the feedback in this thread and my own experience it seems to work quite well!

**Comment by Dr-Bean** [comment]
All open PR's were closed automatically when the develop branch was renamed to master. So, best to rebase the changes and open a new PR against the master branch, so we can review and go from there.

**Comment by lost-carrier** [comment]
...just if anyone is still subscribed only to this PR: Shairport is now available thru Synocommunity! https://synocommunity.com/package/shairport-sync

**Comment by colamage** [comment]
Long time no see! Thought i try this out again. Anyway, tried to change the name of the player/broadcast name, both by the advised above method (start-stop-status) and by navigating to "/shairport-sync/etc/shairport-sync.conf" but there seem to be no such file. Do i just create one or is there someplace else to change the name?

**Comment by lost-carrier** [comment]
All "shairport" stuff is more or less outdated. I'd recommend to use the synocommunity-package "shairport-sync". There is no shairport-sync.conf included, yet. That one is coming with the next release, which is about to be merged. So, with the current version, replacing...
```
start-stop-daemon -S -q -m -b -p ${PID_FILE} -x ${DAEMON} -- --port=${PORT} 2> /dev/null
```
...with...
```
start-stop-daemon -S -q -m -b -p ${PID_FILE} -x ${DAEMON} -- --port=${PORT} -a "MyFancyName" 2> /dev/null
```
...in the `start-stop-status` should do. Does it?

**Comment by colamage** [comment]
Yes i saw the package in the synocommunity repo with the added -sync (thats why i had to try it again).  Went on rambling back and forth with what ever i could find documented at first :) And yes it did the trick!
 I first tried with 
>start-stop-deamon -S -q -m -b -p -a "Dev name" ${PID_FILE} -x ${DAEMON} -- --port=${PORT} 2> /dev/null

but after that i couldn't start the package.

**Comment by lost-carrier** [comment]
@coImage new version has been merged now. ...includes that shairport-sync.conf. ;-)

**Comment by colamage** [comment]
Sorry for continuously bumping here but the .conf file seem to make no difference. I´ve only made a couple of lines
>general = {
  name = "Silly name";
};

Ive rebooted the nas, started and stopped the package, reinstalled it and so on.

**Pull request closed without merging**
