### PR TITLE
Python 3.10.12 and 3.11.4 update

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

Python 3.10.12 and 3.11.4 update

Fixes n/a

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
@hgy59 this will require a second pair of eye... Overall this PR is relatively trivial besides:
1. the regular testing of newer wheels requiring a changes here and there
2. a new patch for armv5 for py311 otherwise causing static_assert undefined errors
3. along with a few tentative fixes for `mariadb-connector-c` update which requires `-std=gnu99` on GCC <= 5.0

The real hit here is `openssl3`.  I've adjusted **ALL** python31* dependencies to use it starting from now.  I'm thinking python is probably a good segway to enforce switching to newer openssl... Although this may be too brutal and require thinking things thru a bit more?  Your thoughts on this would be welcomed.

**Comment by th0ma7** [comment]
@hgy59 friendly reminder that your thoughts on `openssl3` would be appreciated.  thnx in advance.

**Comment by hgy59** [comment]
> The real hit here is `openssl3`. I've adjusted **ALL** python31* dependencies to use it starting from now. I'm thinking python is probably a good segway to enforce switching to newer openssl... Although this may be too brutal and require thinking things thru a bit more? Your thoughts on this would be welcomed.

Recently I tried to build mosquitto with openssl3 as the dependencies are cross/libwebsockets and cross/cjson only and do not touch other packages.
Unfortunately there is a build error on cross/openssl3 for aarch64-6.2.4.
I hope we can fix this and find some other packages with just a few dependencies to avoid an all or nothing migration to openssl3.

**Comment by th0ma7** [comment]
> > The real hit here is `openssl3`. I've adjusted **ALL** python31* dependencies to use it starting from now. I'm thinking python is probably a good segway to enforce switching to newer openssl... Although this may be too brutal and require thinking things thru a bit more? Your thoughts on this would be welcomed.
> 
> Recently I tried to build mosquitto with openssl3 as the dependencies are cross/libwebsockets and cross/cjson only and do not touch other packages.
> Unfortunately there is a build error on cross/openssl3 for aarch64-6.2.4.
> I hope we can fix this and find some other packages with just a few dependencies to avoid an all or nothing migration to openssl3.

@hgy59 look at my commits, i did solved that by disabling asm on that specific arch and version

**Comment by hgy59** [comment]
> > > The real hit here is `openssl3`. I've adjusted **ALL** python31* dependencies to use it starting from now. I'm thinking python is probably a good segway to enforce switching to newer openssl... Although this may be too brutal and require thinking things thru a bit more? Your thoughts on this would be welcomed.
> > 
> > 
> > Recently I tried to build mosquitto with openssl3 as the dependencies are cross/libwebsockets and cross/cjson only and do not touch other packages.
> > Unfortunately there is a build error on cross/openssl3 for aarch64-6.2.4.
> > I hope we can fix this and find some other packages with just a few dependencies to avoid an all or nothing migration to openssl3.
> 
> @hgy59 look at my commits, i did solved that by disabling asm on that specific arch and version

There is a patch for aarch64 with older compilers, it is for 6.1 only and must be applied for 6.2.4 too. No need to disable asm.

**Comment by th0ma7** [comment]
@hgy59 I just saw your PR.  Let me rebase against master and undo that change related to asm.

Otherwise, are you ok with initiating openssl3 migration starting with this pr?

**Comment by hgy59** [comment]
@th0ma7 I have started a build (one arch only) of all packages with all cross/openssl references updated to cross/openssl3.
This will give a picture of the issues to expect (but it takes some time to complete)...
The github build action is not usable for this, as we get timeouts, like in this PR.

**Comment by th0ma7** [comment]
> I have started a build (one arch only) of all packages with all cross/openssl references updated to cross/openssl3. This will give a picture of the issues to expect (but it takes some time to complete)... The github build action is not usable for this, as we get timeouts, like in this PR.

@hgy59 ok, let me know what comes out of it.  On my end I have succesfully tested python builds on x86_64 + deluge #5801 and all looks good AFAIK.  And indeed github action won't be of any help...  But let me know if you intend to merge something to master and need to rebase against it and revert what may be superseeded by your PR if any.

**Comment by th0ma7** [comment]
@hgy59 interestingly armv5 github-action was able to fully complete with no errors which gives a nice idea of the situation.

**Comment by Safihre** [comment]
So, now what? :)

**Comment by hgy59** [comment]
> @hgy59 need assistance with openssl3, or advice/review so i can I merge as is or preferably proceed with reverting to older openssl?

my openssl build tests didn't find large show stoppers. One is the erlang/rabbitmq/ejabberd set of packages (that I already started to migrate with #5813 and #5814. 
AFAICR there is ympd that needs an update too (but is already on #5652)
(sorry, I am out for vacation and don't have access to my dev env.)

I think you can go forward with python and openssl3

Just found out that openssl 3.1.1 is not an LTS version and will expire on 14th March 2025
There is Openssl 3.0 (currently 3.0.9) that is LTS and supported until  7th September 2026.

I would continue with 3.1.1 if you don't mind.

**Comment by th0ma7** [comment]
> my openssl build tests didn't find large show stoppers. One is the erlang/rabbitmq/ejabberd set of packages (that I already started to migrate with #5813 and #5814. AFAICR there is ympd that needs an update too (but is already on #5652) (sorry, I am out for vacation and don't have access to my dev env.)
> 
> I think you can go forward with python and openssl3

Will do.

> Just found out that openssl 3.1.1 is not an LTS version and will expire on 14th March 2025 There is Openssl 3.0 (currently 3.0.9) that is LTS and supported until 7th September 2026.
> 
> I would continue with 3.1.1 if you don't mind.

I tend to agree with that as well.

**Comment by mreid-tt** [comment]
@th0ma7, is this published already?

**Comment by th0ma7** [comment]
@mreid-tt yup, done yesterday

**Comment by hogi1200** [comment]
@th0ma7, @hgy59 
i just installed the latest python311 package, but it **broke** my **sickchill** package (version 20230627-8).
sickchill doesn't start anymore and shows this error 
`ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory`

It looks like this is related to the change in OpenSSL version. Could you kindly check it please.

My system: MARVELL Armada 385 88F6820, DSM 6.2.4-25556 Update 7
Full error log: 
```XXX@NAS:/volume1/@appstore/sickchill/env/bin$ ./sickchill  
Traceback (most recent call last):  
  File "/volume1/@appstore/sickchill/env/bin/./sickchill", line 5, in <module>  
    from SickChill import main  
  File "/volume1/@appstore/sickchill/env/lib/python3.11/site-packages/SickChill.py", line 14, in <module>  
    import sickchill.start  
  File "/volume1/@appstore/sickchill/env/lib/python3.11/site-packages/sickchill/__init__.py", line 5, in <module>  
    from .show.indexers import indexer, ShowIndexer  
  File "/volume1/@appstore/sickchill/env/lib/python3.11/site-packages/sickchill/show/indexers/__init__.py", line 1, in <module>  
    from .handler import ShowIndexer  
  File "/volume1/@appstore/sickchill/env/lib/python3.11/site-packages/sickchill/show/indexers/handler.py", line 3, in <module>  
    from sickchill import logger, settings  
  File "/volume1/@appstore/sickchill/env/lib/python3.11/site-packages/sickchill/logger.py", line 12, in <module>  
    from github import InputFileContent  
  File "/volume1/@appstore/sickchill/env/lib/python3.11/site-packages/github/__init__.py", line 58, in <module>  
    from github.GithubIntegration import GithubIntegration  
  File "/volume1/@appstore/sickchill/env/lib/python3.11/site-packages/github/GithubIntegration.py", line 4, in <module>  
    import jwt  
  File "/volume1/@appstore/sickchill/env/lib/python3.11/site-packages/jwt/__init__.py", line 1, in <module>  
    from .api_jwk import PyJWK, PyJWKSet  
  File "/volume1/@appstore/sickchill/env/lib/python3.11/site-packages/jwt/api_jwk.py", line 6, in <module>  
    from .algorithms import get_default_algorithms  
  File "/volume1/@appstore/sickchill/env/lib/python3.11/site-packages/jwt/algorithms.py", line 6, in <module>  
    from .utils import (  
  File "/volume1/@appstore/sickchill/env/lib/python3.11/site-packages/jwt/utils.py", line 7, in <module>  
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve  
  File "/volume1/@appstore/sickchill/env/lib/python3.11/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 10, in <module>  
    from cryptography.hazmat._oid import ObjectIdentifier  
  File "/volume1/@appstore/sickchill/env/lib/python3.11/site-packages/cryptography/hazmat/_oid.py", line 7, in <module>  
    from cryptography.hazmat.bindings._rust import (  
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by mreid-tt** [comment]
This almost sounds like parts of the build is still referring to `openssl` which does have a `libssl.so.1.1` as seen in:
https://github.com/SynoCommunity/spksrc/blob/304aa5322952bb5241c5886b8f646184c1f7d2c1/cross/openssl/PLIST#L8
As compared to `openssl3` which does not seem to have this line in its [PLIST](https://github.com/SynoCommunity/spksrc/blob/master/cross/openssl3/PLIST).

**Comment by th0ma7** [comment]
This really is somothing obvious I should have cought in my testing :disappointed: 

@hogi1200 can you test out resulting package from PR #5818 and see if this fixes your issue?

@mreid-tt I've disabled the packages online in the meantime to avoid receving too many of theses issues all over the place.

@hgy59 I'll test things further with my proposed change and see if this fixes things.  Otherwise I'll revert the `openssl3` portion entirely so we can review how we want to tackle migration later on after summer vacations.

**Comment by th0ma7** [comment]
@hogi1200 my initiatial testing shows that my proposed fix does solves things.  I suggest you install the resulting package corresponding to your NAS arch from the github-action build here (once completed) https://github.com/SynoCommunity/spksrc/actions/runs/5630487543 to confirm issue is confirmed to be solved for you.

**Comment by th0ma7** [comment]
@hogi1200 updated python packages should now be available online for you to download and install manuall or pending next update within your package center.  Please let it know it issue is still hapening.

**Comment by hogi1200** [comment]
@th0ma7 
thanks for the quick fix. I installed python311_armv7-6.2.4_3.11.4-6.spk from https://github.com/SynoCommunity/spksrc/actions/runs/5631924879#artifacts and sickchill is working normally again. 👍

**Pull request merged**
