### PR TITLE
Updated release and testing SABnzbd packages to 1.0.2

### PR DESCRIPTION
**Pull request by KaraokeStu**
Since there is no "testing" version at the moment, I've updated to the latest release

### CODE REVIEW

**Comment by KaraokeStu** [comment]
Tested building all platforms - PASSED
Tested bromolow build on DSM 5.2 - PASSED

**Comment by Dr-Bean** [comment]
Thanks. Could you clean up the PR to remove the first commit? E.g. squash to one commit for SABnzbd, and one commit for SABnzbd-testing and force-push (or split up the PR's).
Have you checked that the config file doesn't need updating?

**Comment by Dr-Bean** [comment]
@KaraokeStu Were you still planning to create a new PR?

**Comment by kraades** [comment]
Any idea why SABnzbd is still on 0.7.20-14? No updates available....

I'm on a DS716+ (braswell) on the latest DSM 6.

**Comment by cytec** [comment]
@kraades afaik there was no newer version released so everything is as it should be :)

**Comment by Safihre** [comment]
Sabnzbd dev here: users are reporting that in their package managers that the package keeps reporting 0.7.20-14 (like @kraades), while the stable  package was updated to 1.0.0 already weeks ago (see pr #2201) 
What could be going wrong?

**Comment by cytec** [comment]
@Safihre like i said above, the package was updated and merged but not published... i think @Dr-Bean mentioned that already in the PR you linked (https://github.com/SynoCommunity/spksrc/pull/2201#issuecomment-202289099)

**Comment by Safihre** [comment]
Aaah sorry I didn't catch this. So someone needs to verify the working of it? Or some of the dependencies tare broken?

**Comment by cytec** [comment]
i think it should work on DSM 5 but DSM 6 introduced some changes and that breaks a lot of SPK's... i don't know if anyone has verified/tested that it's working for DSM 5 yet

**Comment by Safihre** [comment]
We had a number of users that just manually upgraded the package by overwriting the dir with the new Tar file (since no change in dependencies). On DSM 5 and 6.
So it clearly works, but what's the official way of confirming it and getting it published?  :) 

Also

**Comment by cytec** [comment]
Generally the best way is to provide feedback in some way when it is working (thats what the `-testing` Packages are ment for) i don't know exactly why the Package was not published and what has to be fixed as i didn't do anything on that Package. Maybe @Dr-Bean or @Diaoul can say something on that part

**Comment by Eldinnie** [comment]
So I've updated the package from DSM, And now Sab actually doesn't work at all anymore.
The skinis not updated, None of the buttons work. I have warnings about permissions. So in general, it starts, but has the same user trouble as the testing and all other apps have on 6.0.

So now after updating the stable package I have no working sab at all.

Performed 0.7 to 1.0.3-16 from DSM interface.
DS212+

**Comment by KaraokeStu** [comment]
As pointed out by @cytec in the comment before yours, the issue with this and many other packages in DSM 6 is related to the adduser problem https://github.com/SynoCommunity/spksrc/issues/2216

**Comment by Eldinnie** [comment]
I know, but breaking a working package with an update was not what I was expecting, I've updated other packeges since on DSM 6.0 without breaking functionality.

**Pull request closed without merging**
