### PR TITLE
DSM7.0: add kernel and toolchain

### PR DESCRIPTION
**Pull request by erdoukki**
## Description

WIP - DSM7.0: add kernel and toolchain for armada37xx

add DSM >= 7.0 in mk/spksrc.kernel-flags.mk
fix URL for DSM 7.0 kernel and toolchain
add kernel for syno-armada37xx-7.0
add toolchain for syno-armada37xx-7.0

Signed-off-by: Kerma Gérald <gandalf@gk2.net>

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [ ] Package update
- [x] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
This is really interesting!
How where you able to find this new download URL?
And do you know if DSM-6.2.4 and 7.0.1 are also available (can't browse the directory tree online)?

**Comment by th0ma7** [comment]
@erdoukki having a few additions for other atchs, mind if I add to your PR?

**Comment by erdoukki** [comment]
> This is really interesting!
> How where you able to find this new download URL?
> And do you know if DSM-6.2.4 and 7.0.1 are also available (can't browse the directory tree online)?

Thanks !

> EDIT: Just found, it is possible to browse from https://archive.synology.com/download/ToolChain/Synology%20NAS%20GPL%20Source/7.0-41890

So you get your answer. ;-)
I was looking backward from downloading the PAC file for latest firmware.
Then I discover this directory.
It hosts only 7.0.0.
latest 7.0.1 build 42218 is still missing.

> @erdoukki having a few additions for other atchs, mind if I add to your PR?

@th0ma7 please, fell free to add more !
It is why I have share this discover, and made this PR.

I am just discovering Synology DSM with a DS120j, and using DSM 7.0.1.
I have some issues with elevation, which looks like impossible since 7.0.
Also documented capabilities do not work !
```
gege@synologynas:/$ uname -ar
Linux synologynas 4.4.180+ #42218 SMP Mon Oct 18 19:15:40 CST 2021 aarch64 GNU/Linux synology_armada37xx_ds120j
```

**Comment by th0ma7** [comment]
Can you please grant me access to your PR so I can push a few updates?

**Comment by erdoukki** [comment]
sure... I am looking how...

**Comment by th0ma7** [comment]
still denied... btw, feel free to switch to discord.  I'll be able to provide you with some pointers for building kernel modules

**Comment by th0ma7** [comment]
@erdoukki thnx for your first contribution, much appreciated!

**Comment by erdoukki** [comment]
@th0ma7 you're welcome !
And also thanks for the great work on spksrc...

**Pull request merged**
