### PR TITLE
Update SABnzbd to 2.3.7

### PR DESCRIPTION
**Pull request by Safihre**
I also build it with Python 2.7.15 (#3552) and that also worked: https://travis-ci.org/Safihre/spksrc/builds/471791725

### Checklist
- [x] Build rule `all-supported` completed successfully: https://travis-ci.org/Safihre/spksrc/builds/471791364
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
Is there any synology specific package bug fix or improvement to include?

**Comment by Safihre** [comment]
No, just SABnzbd internals.

**Comment by Safihre** [comment]
Want to wait for the Python update or can I merge/publish it? :)

**Comment by ymartin59** [comment]
Python update is stuck on "cryptography" module - if you have time to have a look on it - I would appreciate. As I am almost sure that all python 2.7 based packages have to be re-published (and re-tested), my idea is to wait for python to be ready before processing all applications.

**Comment by nj** [comment]
@Safihre You properly need to re-run Travis, after the update - as the mentioned seems to be th previous one (version 2.3.6).

**Comment by ymartin59** [comment]
@Safihre Is it possible to build and run with Python 2.7.14 ?

**Comment by Safihre** [comment]
Sadly it seems to[ fail to build](https://travis-ci.org/Safihre/spksrc) now after I rebased on `master`. Have to spin up my VM and investigate.

**Comment by nj** [comment]
@Safihre Might be related to 471d4f1, as according to the failed job it states the following:
```
tar: bin/unrar: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
chmod: cannot access '/spksrc/spk/sabnzbd/work-x64-6.1/staging/bin/unrar': No such file or directory
```

So changing https://github.com/SynoCommunity/spksrc/blob/db4d1c4/cross/sabnzbd/Makefile#L22-L23 might do the trick.

**Comment by nj** [comment]
`myInstall` properly should be renamed to `sabnzbd_install`, to use new (?) practise.

**Comment by Safihre** [comment]
Great..
Could also just be the change to `cross/unrar` in that commit since the error seems to that its unable to find the `unrar` output anymore.

**Comment by ymartin59** [comment]
My fault - I have reverted my "rude" clean up... Many application "install" targets do not follow GNU guidelines...

**Comment by nj** [comment]
@ymartin59 well "rude" or not, it's properly would be better to get moving towards GNU guidelines if possible 😉 But properly would solve the case for now.

**Comment by Safihre** [comment]
That [fixed it](https://travis-ci.org/Safihre/spksrc/builds/497877674)!

**Comment by Safihre** [comment]
In the case of `cross/sabnzbd` it does need to be `STAGING_INSTALL_PREFIX` otherwise it doesn't get included in the final SPK.

**Comment by Safihre** [comment]
Great! 💯 👍

**Pull request merged**
