### PR TITLE
[branch dsm6] update nzbget-test to version 18

### PR DESCRIPTION
**Pull request by scelestic**
_Motivation:_ update the nzbget-testing package in branch dsm6 to latest 18 final release
_Linked issues:_ this should be tested on other platforms and checked if we have all new options available in the web interface.

### Checklist
- [] Build rule `arch-armadaxp` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

### CODE REVIEW

**Comment by KaraokeStu** [comment]
Can you confirm that you've managed to get this built successfully, as DSM 5.x doesn't support C++ 14 and DSM 6.x is still only GCC 4.9.

Please see https://github.com/SynoCommunity/spksrc/issues/2185

**Comment by scelestic** [comment]
Can confirm it builds and the package is functional. When looking in the config.log I do see it did define HAVE_CXX14, also looking at this bug report it seems gcc 4.9 should be able to support it : [https://github.com/nzbget/nzbget/issues/142]

**Comment by KaraokeStu** [comment]
@scelestic Great stuff - have you had a chance to test on DSM 5.x?

**Comment by scelestic** [comment]
I did not test it before but with the 5.2 toolchain it fails to compile because C++14 is missing, it is still using gcc 4.6.4 so that makes sense. I guess nzbget 18 will be DSM 6.x+

**Comment by ymartin59** [comment]
Please please do not submit PR to `dsm6` branch which does not concern specifically DSM 6.x support.

Procedure consists in regularly merging from `master` to `dsm6`. So to avoid conflicts, packages have to be submitted only to `master`.

Either rewind your PR on `master` only, or wait for me to do so, as someone requested nzbget for DSM 6.1 #2880

**Comment by bidorffOL** [comment]
I just retrieved this PR and I was wondering if there was any reason for the port to have been moved from the default 6789 to 9876 ?

**Comment by scelestic** [comment]
Looks like you're right, the port for nzbget-testing is 9876  and the package nzbget uses 6789.

I based my changes on the nzbget-testing package while not using -testing code and later when I renamed that back I never even thought about the control port. Feel free to change it to whatever you like, I don't think this pull request will be used.

**Comment by bidorffOL** [comment]
I just saw that, I'll try to PR a cross version of NZBGet this week that can be published in the `master` (i.e. NZBGet 16.4 for DSM 5.x and NZBGet 19.1 for DSM 6.x).

**Pull request closed without merging**
