### PR TITLE
dnscrypt-proxy: update to 2.0.44

### PR DESCRIPTION
**Pull request by publicarray**

### CODE REVIEW

**Comment by publicarray** [comment]
fixes https://github.com/publicarray/spksrc/issues/14

**Comment by publicarray** [comment]
The failing tests are unsupported architectures

**Comment by hgy59** [comment]
> 
> 
> The failing tests are unsupported architectures

This is fixed with 45bc7ff5ef32c39f2784cca485b30d59d8a02425

**Comment by ymartin59** [comment]
@publicarray So please rebase to confirm with latest github actions.

**Comment by publicarray** [comment]
Sorry, I have very little time at the moment. Thanks for merging anyway.

**Pull request merged**
