### PR TITLE
Lint and fix json files

### PR DESCRIPTION
**Pull request by publicarray**
_Motivation:_  Fix invalid json

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by publicarray** [comment]
Current output:

<details>
<pre>
spk/syncthing/src/wizard/upgrade_uifile
spk/syncthing/src/wizard/upgrade_uifile_fre
spk/syncthing/src/wizard/install_uifile
spk/syncthing/src/wizard/install_uifile_fre
spk/rutorrent/src/app/config
spk/rutorrent/src/wizard/upgrade_uifile_enu
spk/rutorrent/src/wizard/upgrade_uifile
spk/rutorrent/src/wizard/install_uifile_enu
spk/rutorrent/src/wizard/install_uifile
spk/rutorrent/src/wizard/install_uifile_fre
spk/nzbmegasearch/src/app/config
spk/subliminal/src/app/config
spk/subliminal/src/wizard/upgrade_uifile_enu
spk/subliminal/src/wizard/upgrade_uifile
spk/subliminal/src/wizard/install_uifile_enu
spk/subliminal/src/wizard/install_uifile
spk/fengoffice/src/app/config
spk/fengoffice/src/wizard/install_uifile_enu
spk/fengoffice/src/wizard/uninstall_uifile_enu
spk/fengoffice/src/wizard/uninstall_uifile
spk/fengoffice/src/wizard/install_uifile
spk/gentoo-chroot/src/app/config
spk/plexpy-custom/src/wizard/install_uifile
spk/plexpy-custom/src/wizard/install_uifile_fre
spk/wallabag/src/app/config
spk/wallabag/src/wizard/uninstall_uifile
spk/wallabag/src/wizard/install_uifile
spk/jappix/src/app/config
spk/adminer/src/app/config
spk/adminer/src/wizard/upgrade_uifile
spk/adminer/src/wizard/install_uifile
spk/dnscrypt-proxy/src/wizard/install_uifile
spk/dnscrypt-proxy/src/wizard/install_uifile_fre
spk/headphones-custom/src/wizard/upgrade_uifile
spk/headphones-custom/src/wizard/upgrade_uifile_fre
spk/headphones-custom/src/wizard/install_uifile
spk/headphones-custom/src/wizard/install_uifile_fre
spk/saltpad/src/app/config
spk/selfoss/src/app/config
spk/selfoss/src/wizard/install_uifile_enu
spk/selfoss/src/wizard/uninstall_uifile_enu
spk/selfoss/src/wizard/uninstall_uifile
spk/selfoss/src/wizard/install_uifile
spk/selfoss/src/wizard/install_uifile_fre
spk/selfoss/src/wizard/uninstall_uifile_fre
spk/nzbget-testing/src/wizard/upgrade_uifile
spk/nzbget-testing/src/wizard/upgrade_uifile_fre
spk/nzbget-testing/src/wizard/install_uifile
spk/nzbget-testing/src/wizard/install_uifile_fre
spk/sickrage/src/wizard/upgrade_uifile
spk/sickrage/src/wizard/install_uifile
spk/cops/src/app/config
spk/cops/src/wizard/install_uifile_enu
spk/cops/src/wizard/install_uifile
spk/cops/src/wizard/install_uifile_fre
spk/lazylibrarian/src/wizard/upgrade_uifile
spk/lazylibrarian/src/wizard/upgrade_uifile_fre
spk/lazylibrarian/src/wizard/install_uifile
spk/lazylibrarian/src/wizard/install_uifile_fre
spk/bicbucstriim/src/app/config
spk/roundcube/src/app/config
spk/roundcube/src/wizard/install_uifile_enu
spk/roundcube/src/wizard/uninstall_uifile_enu
spk/roundcube/src/wizard/uninstall_uifile
spk/roundcube/src/wizard/install_uifile
spk/deluge/src/wizard/upgrade_uifile
spk/deluge/src/wizard/upgrade_uifile_fre
spk/deluge/src/wizard/install_uifile
spk/deluge/src/wizard/install_uifile_fre
spk/horde/src/app/config
spk/horde/src/wizard/install_uifile_enu
spk/horde/src/wizard/uninstall_uifile_enu
spk/horde/src/wizard/uninstall_uifile
spk/horde/src/wizard/install_uifile
spk/owncloud/src/app/config
spk/owncloud/src/wizard/install_uifile_enu
spk/owncloud/src/wizard/uninstall_uifile_enu
spk/owncloud/src/wizard/uninstall_uifile
spk/owncloud/src/wizard/install_uifile
spk/owncloud/src/wizard/install_uifile_fre
spk/owncloud/src/wizard/uninstall_uifile_fre
spk/demoservice/src/wizard/install_uifile
spk/demoservice/src/wizard/install_uifile_fre
spk/couchpotatoserver/src/wizard/upgrade_uifile
spk/couchpotatoserver/src/wizard/upgrade_uifile_fre
spk/couchpotatoserver/src/wizard/install_uifile
spk/couchpotatoserver/src/wizard/install_uifile_fre
spk/museek-plus/src/wizard/install_uifile_enu
spk/museek-plus/src/wizard/install_uifile
spk/museek-plus/src/wizard/install_uifile_fre
spk/git-server/src/app/config
spk/git-server/src/wizard/install_uifile_enu
spk/git-server/src/wizard/install_uifile
spk/ps3netsrv/src/wizard/install_uifile_rus
spk/ps3netsrv/src/wizard/install_uifile
spk/ps3netsrv/src/wizard/install_uifile_fre
spk/full-text-rss/src/app/config
spk/sabnzbd/src/wizard/upgrade_uifile
spk/sabnzbd/src/wizard/upgrade_uifile_fre
spk/sabnzbd/src/wizard/install_uifile
spk/sabnzbd/src/wizard/install_uifile_fre
spk/headphones/src/wizard/upgrade_uifile
spk/headphones/src/wizard/upgrade_uifile_fre
spk/headphones/src/wizard/install_uifile
spk/headphones/src/wizard/install_uifile_fre
spk/minio/src/wizard/install_uifile
spk/radarr/src/wizard/upgrade_uifile
spk/radarr/src/wizard/upgrade_uifile_fre
spk/radarr/src/wizard/install_uifile
spk/radarr/src/wizard/install_uifile_fre
spk/dante-sockd/src/wizard/install_uifile
spk/dante-sockd/src/wizard/install_uifile_fre
spk/umurmur/src/app/config
spk/memcached/src/app/config
spk/octoprint/src/app/config
spk/pyload/src/app/config
spk/pyload/src/wizard/upgrade_uifile_enu
spk/pyload/src/wizard/upgrade_uifile
spk/pyload/src/wizard/install_uifile_enu
spk/pyload/src/wizard/install_uifile
spk/domoticz/src/app/config
spk/oscam/src/app/config
spk/mylar/src/wizard/upgrade_uifile
spk/mylar/src/wizard/upgrade_uifile_fre
spk/mylar/src/wizard/install_uifile
spk/mylar/src/wizard/install_uifile_fre
spk/debian-chroot/src/app/config
spk/couchpotatoserver-custom/src/wizard/upgrade_uifile
spk/couchpotatoserver-custom/src/wizard/upgrade_uifile_fre
spk/couchpotatoserver-custom/src/wizard/install_uifile
spk/maraschino/src/app/config
spk/bitlbee/src/wizard/install_uifile_enu
spk/bitlbee/src/wizard/install_uifile
spk/bitlbee/src/wizard/install_uifile_fre
spk/monit/src/app/config
spk/monit/src/wizard/install_uifile
spk/htpcmanager/src/app/config
spk/htpcmanager/src/wizard/upgrade_uifile_enu
spk/htpcmanager/src/wizard/upgrade_uifile
spk/htpcmanager/src/wizard/install_uifile_enu
spk/htpcmanager/src/wizard/install_uifile
spk/htpcmanager/src/wizard/install_uifile_fre
spk/icecast/WIZARD_UIFILES/install_uifile
spk/icecast/src/app/config
spk/transmission/src/settings.json
spk/transmission/src/settings.json: line 4, col 29, found: 'INVALID' - expected: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['.
spk/transmission/src/wizard/upgrade_uifile
spk/transmission/src/wizard/upgrade_uifile_fre
spk/transmission/src/wizard/install_uifile
spk/transmission/src/wizard/install_uifile_fre
spk/lidarr/src/wizard/upgrade_uifile
spk/lidarr/src/wizard/upgrade_uifile_fre
spk/lidarr/src/wizard/install_uifile
spk/lidarr/src/wizard/install_uifile_fre
spk/tvheadend/src/app/config
spk/tvheadend/src/wizard/upgrade_uifile
spk/tvheadend/src/wizard/upgrade_uifile_fre
spk/tvheadend/src/wizard/install_uifile
spk/tvheadend/src/wizard/install_uifile_fre
spk/tvheadend/src/passwd.json
spk/tvheadend/src/accesscontrol.json
spk/plexivity/src/app/config
spk/sickbeard-custom/src/wizard/upgrade_uifile
spk/sickbeard-custom/src/wizard/upgrade_uifile_fre
spk/sickbeard-custom/src/wizard/install_uifile
spk/sickbeard-custom/src/wizard/install_uifile_fre
spk/nzbget/src/wizard/upgrade_uifile
spk/nzbget/src/wizard/upgrade_uifile_fre
spk/nzbget/src/wizard/install_uifile
spk/nzbget/src/wizard/install_uifile_fre
spk/flexget/src/wizard/upgrade_uifile_enu
spk/flexget/src/wizard/upgrade_uifile
spk/flexget/src/wizard/install_uifile_enu
spk/flexget/src/wizard/install_uifile
spk/ffsync/src/wizard/install_uifile_enu
spk/ffsync/src/wizard/uninstall_uifile_enu
spk/ffsync/src/wizard/uninstall_uifile
spk/ffsync/src/wizard/install_uifile
spk/darkstat/src/app/config
spk/squidguard/src/app/config
spk/sonarr/src/wizard/upgrade_uifile
spk/sonarr/src/wizard/upgrade_uifile_fre
spk/sonarr/src/wizard/install_uifile
spk/sonarr/src/wizard/install_uifile_fre
spk/hassio/src/wizard/uninstall_uifile
spk/hassio/src/hassio.json
spk/znc/src/wizard/install_uifile_enu
spk/znc/src/wizard/install_uifile
spk/znc/src/wizard/install_uifile_fre
spk/jackett/src/app/config
spk/tt-rss/src/app/config
spk/tt-rss/src/wizard/install_uifile_enu
spk/tt-rss/src/wizard/uninstall_uifile_enu
spk/tt-rss/src/wizard/uninstall_uifile
spk/tt-rss/src/wizard/install_uifile
spk/tt-rss/src/wizard/install_uifile_fre
spk/tt-rss/src/wizard/uninstall_uifile_fre
spk/haproxy/src/app/config
spk/haproxy/src/wizard/install_uifile_enu
spk/haproxy/src/wizard/install_uifile
spk/haproxy/src/wizard/install_uifile_fre
spk/ejabberd/src/app/config
spk/ejabberd/src/wizard/install_uifile_enu
spk/ejabberd/src/wizard/install_uifile
spk/mantisbt/src/app/config
spk/mantisbt/src/wizard/install_uifile_enu
spk/mantisbt/src/wizard/uninstall_uifile_enu
spk/mantisbt/src/wizard/uninstall_uifile
spk/mantisbt/src/wizard/install_uifile
</pre>
</details>

`gfind` because I'm on macOS and It's faster without docker. 

The `spk/transmission/src/settings.json` file has it's boolean variables replaced.
 
Off topic but for macOS I now launch docker volume with `delegated` to speed-up disk I/O significantly with the downside that disk actions take some time to sync between host and container.
 
`docker run --name spksrc --rm -it -v (pwd):/spksrc:delegated synocommunity/spksrc:latest /bin/bash`

**Comment by hgy59** [comment]
@publicarray as this is a one time manual job I am not sure, whether it is worth to create a makefile rule and to install node package manager and jsonlint into the development docker image.

We could create a lint makefile rule, but I would avoid the installation of npm and jsonlint into the docker image. So `make jsonlint` will run on the host system only and not inside of spksrc container. An appropriate error message should be shown when jsonlint is not available.

And I would prefer to rename the Makefile target to `jsonlint` as we may introduce other linting/validation targets for other file types.

**Comment by publicarray** [comment]
@hgy59  Thanks, I've modified it and I think having a generic lint command for all future lints is even better. I disagree with this being a on time job though, I think it should be done as part of the package build process or before a package is published, ideally via a CI

**Comment by hgy59** [comment]
@publicarray please can you explain how jsonlint works here?
Does it put an error and terminates or does it repair the invalid files?
It would lead to conflicts to modify source files, but checking for correct syntax without modification would fit into CI.

**Comment by publicarray** [comment]
Yea sure, it just prints errors and terminates

**Comment by publicarray** [comment]
Actually I need to remove the -i flag for that statement to be true

**Pull request merged**
