### PR TITLE
Add Tcl 8.6.6 package

### PR DESCRIPTION
**Pull request by eelcohuininga**
Hi,

This is my first package created with spksrc. This package is [Tcl 8.6.6](https://tcl.tk/), which stands for Tool Command Language. I've been using this application for years on my Synology, and Ive finally decided to create a real package using the spksrc toolkit. It's been tested on a DS213+ (qoriq) and a DS214+ (armadaxp) and it works fine for me. It should work on any other architecture as well, but if there are any problems, please let me know.
You can do a simple test by installing the package, and then open a PuTTy shell and start /usr/local/bin/tclsh and type:
`info patchlevel`
It should return 8.6.6, which is the version of Tcl.

### CODE REVIEW

**Comment by KaraokeStu** [comment]
Hi, could you please squash these into a single commit ready for me to merge?

**Comment by eelcohuininga** [comment]
Thanks for reviewing the code. Both commits should be squashed now. I'm kinda new to GitHub so please let me know if you run into any problems.

**Comment by eelcohuininga** [comment]
Thanks for the merge. How can the Tcl package be published on the https://www.synocommunity.com/packages site, and in the DSM package center?

BTW I've temoprarily published the packages for testing purposes at https://github.com/eelcohuininga/synotcl

**Comment by KaraokeStu** [comment]
Hi, please can you remove the link to the published packages - it makes things awkward when testing and maintaining. I'm just speaking to @Diaoul to sort out getting the correct access to publish to the repository for you

**Comment by eelcohuininga** [comment]
Ok thanks, I'll remove it!

**Pull request merged**
