### PR TITLE
update minio to 2022-04-01T03-41-39Z

### PR DESCRIPTION
**Pull request by fgma**
## Description

Update minio to 2022-04-01T03-41-39Z

Please merge after https://github.com/SynoCommunity/spksrc/pull/5152

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by fgma** [comment]
Minio received multiple updates while the go update is pending. Just let me update this PR to include the latest minio release after go 1.18 support is merged.

**Comment by fgma** [comment]
Ready for review/merge

**Comment by alexanderharm** [comment]
@fgma 
Any chance of MinIO becoming compatible with DSMv7?

**Comment by fgma** [comment]
@hgy59 :thumbsup:

**Pull request merged**
