### PR TITLE
Update SABnzbd to 4.3.3

### PR DESCRIPTION
**Pull request by Safihre**
## Description

Update SABnzbd to 4.3.3

Fixes: #6223

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [ ] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by Safihre** [comment]
@th0ma7 Here are the changes.
Nothing special at all, just xz and SABnzbd.
This will forcefully build all xz deps packages, so please check the links that I provided in my other comment to the SABnzbd specific build.

**Comment by th0ma7** [comment]
Is it now fixed for you after rebasing?

**Comment by Safihre** [comment]
It seems so! However, I'm on vacation for the next 2 weeks without access to my Synology to test the build. 
Will merge once I get to test the upgrade and fresh install paths, just to be sure.

PS: Any chance on Python 3.12 and dropping 3.10, or is there a major blocker for that? I'm not active enough, apologies!

**Comment by th0ma7** [comment]
Yup, there's one major blocker: pip and crossenv.  It requires the ability to build a crossenv per wheel, not for all but a few, which is new.  As some wheels requires older vs newer pip versions and now have conflicting crossenv dependencies.  It's a mess.  I have a preliminary pr for that bit it isn't working just yet.

**Comment by Safihre** [comment]
🫣 sounds like a lot of possibilities for problems.

**Comment by Safihre** [comment]
@th0ma7 @hgy59 I deleted a couple of old version of `sabnzbd` from the server (using the admin). 
Only kept the last DSM 5 version and the version before removing arm5 support.

**Pull request merged**
