### PR TITLE
Dotnet runtime: Update to v6.0.14

### LINKED ISSUE #5315: Segmentation fault (core dumped) .net
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

.net runtime 6

### Package Version

 dotnet-runtime 6.0.4-1

### Device Model

ds213j

### Device Architecture

ARMv7 - armada370

### Firmware Version

DSM 6.2.4-25556 Update 6

### What happened?

Hi, 
After installing ,net 6.0 runtime on my DS213J I receive this error message when launc dotnet commadn on SSH console

https://synocommunity.com/package/dotnet-runtime

My DSM version in Full DSM version:DSM 6.2.4-25556 Update 6

### Reproduction steps

```bash
1.Install package https://synocommunity.com/package/dotnet-runtime
2.run dotnet command on terminal
3.
...
```

### Install Log

```log
2022/06/15 22:34:58     install dotnet-runtime 6.0.4-1 Begin preinst
2022/06/15 22:34:59     Begin reload_inst_variables
2022/06/15 22:34:59     End reload_inst_variables
2022/06/15 22:34:59     Begin initialize_variables
2022/06/15 22:34:59     End initialize_variables
2022/06/15 22:34:59     ===> Step preinst. USER= GROUP= SHARE_PATH=
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End preinst ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/rm -rf /volume1/@appstore/dotnet-runtime
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End /bin/rm -rf /volume1/@appstore/dotnet-runtime ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/dotnet-runtime
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/dotnet-runtime ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/rm -rf /var/packages/dotnet-runtime
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End /bin/rm -rf /var/packages/dotnet-runtime ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/mkdir -p /var/packages/dotnet-runtime
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End /bin/mkdir -p /var/packages/dotnet-runtime ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/dotnet-runtime/INFO
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/dotnet-runtime/INFO ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/rm -rf /var/packages/dotnet-runtime/scripts
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End /bin/rm -rf /var/packages/dotnet-runtime/scripts ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/dotnet-runtime/scripts
2022/06/15 22:35:00     install dotnet-runtime 6.0.4-1 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/dotnet-runtime/scripts ret=[0]
2022/06/15 22:35:00     install dotnet-runtime 6.0.4-1 Begin /bin/rm -rf /var/packages/dotnet-runtime/conf
2022/06/15 22:35:00     install dotnet-runtime 6.0.4-1 End /bin/rm -rf /var/packages/dotnet-runtime/conf ret=[0]
2022/06/15 22:35:00     install dotnet-runtime 6.0.4-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/dotnet-runtime/conf
2022/06/15 22:35:00     install dotnet-runtime 6.0.4-1 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/dotnet-runtime/conf ret=[0]
2022/06/15 22:35:01     install dotnet-runtime 6.0.4-1 Begin postinst
2022/06/15 22:35:01     Begin reload_inst_variables
2022/06/15 22:35:01     End reload_inst_variables
2022/06/15 22:35:01     Begin initialize_variables
2022/06/15 22:35:01     End initialize_variables
2022/06/15 22:35:01     ===> Step postinst. USER= GROUP= SHARE_PATH=
2022/06/15 22:35:01     Begin save_wizard_variables
2022/06/15 22:35:01     End save_wizard_variables
2022/06/15 22:35:01     install dotnet-runtime 6.0.4-1 End postinst ret=[0]
2022/06/15 22:35:05     install dotnet-runtime 6.0.4-1 Begin start-stop-status start
2022/06/15 22:35:05     install dotnet-runtime 6.0.4-1 End start-stop-status start ret=[0]
2022/06/15 22:35:06     install dotnet-runtime 6.0.4-1 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2022/06/15 22:35:06     install dotnet-runtime 6.0.4-1 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2022/06/15 22:38:41     (system) trigger dotnet-runtime 6.0.4-1 Begin start-stop-status stop
2022/06/15 22:38:41     (system) trigger dotnet-runtime 6.0.4-1 End start-stop-status stop ret=[0]
2022/06/15 22:43:00     (system) trigger dotnet-runtime 6.0.4-1 Begin start-stop-status start
2022/06/15 22:43:00     (system) trigger dotnet-runtime 6.0.4-1 End start-stop-status start ret=[0]
```

### Service Log

```log
admin@DiskStation213j:/var/packages/dotnet-runtime/var$ dir
total 8
drwxr-xr-x 2 root root 4096 Jun 15 22:35 .
drwxr-xr-x 9 root root 4096 Jun 15 22:35 ..
```

### Other Logs

```log
2022/06/15 22:34:58     install dotnet-runtime 6.0.4-1 Begin preinst
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End preinst ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/rm -rf /volume1/@appstore/dotnet-runtime
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End /bin/rm -rf /volume1/@appstore/dotnet-runtime ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/dotnet-runtime
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End /bin/mv -f /volume1/@tmp/pkginstall/package /volume1/@appstore/dotnet-runtime ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/rm -rf /var/packages/dotnet-runtime
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End /bin/rm -rf /var/packages/dotnet-runtime ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/mkdir -p /var/packages/dotnet-runtime
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End /bin/mkdir -p /var/packages/dotnet-runtime ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/dotnet-runtime/INFO
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End /bin/mv -f /volume1/@tmp/pkginstall/INFO /var/packages/dotnet-runtime/INFO ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/rm -rf /var/packages/dotnet-runtime/scripts
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 End /bin/rm -rf /var/packages/dotnet-runtime/scripts ret=[0]
2022/06/15 22:34:59     install dotnet-runtime 6.0.4-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/dotnet-runtime/scripts
2022/06/15 22:35:00     install dotnet-runtime 6.0.4-1 End /bin/mv -f /volume1/@tmp/pkginstall/scripts /var/packages/dotnet-runtime/scripts ret=[0]
2022/06/15 22:35:00     install dotnet-runtime 6.0.4-1 Begin /bin/rm -rf /var/packages/dotnet-runtime/conf
2022/06/15 22:35:00     install dotnet-runtime 6.0.4-1 End /bin/rm -rf /var/packages/dotnet-runtime/conf ret=[0]
2022/06/15 22:35:00     install dotnet-runtime 6.0.4-1 Begin /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/dotnet-runtime/conf
2022/06/15 22:35:00     install dotnet-runtime 6.0.4-1 End /bin/mv -f /volume1/@tmp/pkginstall/conf /var/packages/dotnet-runtime/conf ret=[0]
2022/06/15 22:35:01     install dotnet-runtime 6.0.4-1 Begin postinst
2022/06/15 22:35:01     install dotnet-runtime 6.0.4-1 End postinst ret=[0]
2022/06/15 22:35:03     install dotnet-runtime: begin to start version 6.0.4-1
2022/06/15 22:35:05     install dotnet-runtime 6.0.4-1 Begin pre-load apparmor
2022/06/15 22:35:05     install dotnet-runtime 6.0.4-1 End pre-load apparmor ret=[0]
2022/06/15 22:35:05     install dotnet-runtime 6.0.4-1 Begin start-stop-status start
2022/06/15 22:35:05     install dotnet-runtime 6.0.4-1 End start-stop-status start ret=[0]
2022/06/15 22:35:06     install dotnet-runtime: start version 6.0.4-1 successfully, result 0
2022/06/15 22:35:06     install dotnet-runtime 6.0.4-1 Begin /bin/rm -rf /volume1/@tmp/pkginstall
2022/06/15 22:35:06     install dotnet-runtime 6.0.4-1 End /bin/rm -rf /volume1/@tmp/pkginstall ret=[0]
2022/06/15 22:35:06     install dotnet-runtime 6.0.4-1 successfully
2022/06/15 22:38:40     (system) trigger SynoFinder 1.5.2-0323 Begin start-stop-status stop
2022/06/15 22:38:40     (system) trigger LogCenter 1.1.10-0151 Begin start-stop-status stop
2022/06/15 22:38:40     (system) trigger OAuthService 1.0.4-0031 Begin start-stop-status stop
2022/06/15 22:38:40     (system) trigger HyperBackup 2.2.9-1520 Begin start-stop-status stop
2022/06/15 22:38:40     (system) trigger StorageAnalyzer 2.0.1-0214 Begin start-stop-status stop
2022/06/15 22:38:41     (system) trigger TextEditor 1.2.3-0029 Begin start-stop-status stop
2022/06/15 22:38:41     (system) trigger dotnet-runtime 6.0.4-1 Begin start-stop-status stop
2022/06/15 22:38:41     (system) trigger PythonModule 0115 Begin start-stop-status stop
2022/06/15 22:38:41     (system) trigger dotnet-runtime 6.0.4-1 End start-stop-status stop ret=[0]
2022/06/15 22:38:41     (system) trigger TextEditor 1.2.3-0029 End start-stop-status stop ret=[0]
2022/06/15 22:38:41     (system) trigger py3k 3.8.6-0154 Begin start-stop-status stop
2022/06/15 22:38:41     (system) trigger PythonModule 0115 End start-stop-status stop ret=[0]
2022/06/15 22:38:41     (system) trigger FileStation 1.2.8-0293 Begin start-stop-status stop
2022/06/15 22:38:41     (system) trigger py3k 3.8.6-0154 End start-stop-status stop ret=[0]
2022/06/15 22:38:41     (system) trigger dotnet-runtime 6.0.4-1 Begin unload apparmor
2022/06/15 22:38:41     (system) trigger TextEditor 1.2.3-0029 Begin unload apparmor
2022/06/15 22:38:41     (system) trigger AntiVirus 1.4.9-2804 Begin start-stop-status stop
2022/06/15 22:38:42     (system) trigger PythonModule 0115 Begin unload apparmor
2022/06/15 22:38:42     (system) trigger py3k 3.8.6-0154 Begin unload apparmor
2022/06/15 22:38:42     (system) trigger HyperBackupVault 2.2.9-1520 Begin start-stop-status stop
2022/06/15 22:38:42     (system) trigger DownloadStation 3.8.16-3566 Begin start-stop-status stop
2022/06/15 22:38:42     (system) trigger dotnet-runtime 6.0.4-1 End unload apparmor ret=[0]
2022/06/15 22:38:42     (system) trigger AudioStation 6.5.6-3377 Begin start-stop-status stop
2022/06/15 22:38:42     (system) trigger MediaServer 1.8.4-2884 Begin start-stop-status stop
2022/06/15 22:38:42     (system) trigger PythonModule 0115 End unload apparmor ret=[0]
2022/06/15 22:38:43     (system) trigger py3k 3.8.6-0154 End unload apparmor ret=[0]
2022/06/15 22:38:44     (system) trigger FileStation 1.2.8-0293 End start-stop-status stop ret=[0]
2022/06/15 22:38:45     (system) trigger FileStation 1.2.8-0293 Begin unload apparmor
2022/06/15 22:38:46     (system) trigger TextEditor 1.2.3-0029 End unload apparmor ret=[0]
2022/06/15 22:38:46     (system) trigger MediaServer 1.8.4-2884 End start-stop-status stop ret=[0]
2022/06/15 22:38:48     (system) trigger StorageAnalyzer 2.0.1-0214 End start-stop-status stop ret=[0]
2022/06/15 22:38:48     (system) trigger StorageAnalyzer 2.0.1-0214 Begin unload apparmor
2022/06/15 22:38:48     (system) trigger MediaServer 1.8.4-2884 Begin unload apparmor
2022/06/15 22:38:49     (system) trigger StorageAnalyzer 2.0.1-0214 End unload apparmor ret=[0]
2022/06/15 22:38:49     (system) trigger OAuthService 1.0.4-0031 End start-stop-status stop ret=[0]
2022/06/15 22:38:49     (system) trigger OAuthService 1.0.4-0031 Begin unload apparmor
2022/06/15 22:38:50     (system) trigger SynoFinder 1.5.2-0323 End start-stop-status stop ret=[0]
2022/06/15 22:38:50     (system) trigger SynoFinder 1.5.2-0323 Begin unload apparmor
2022/06/15 22:38:51     (system) trigger OAuthService 1.0.4-0031 End unload apparmor ret=[0]
2022/06/15 22:38:51     (system) trigger DownloadStation 3.8.16-3566 End start-stop-status stop ret=[0]
2022/06/15 22:38:52     (system) trigger LogCenter 1.1.10-0151 End start-stop-status stop ret=[0]
2022/06/15 22:38:55     (system) trigger DownloadStation 3.8.16-3566 Begin unload apparmor
2022/06/15 22:38:55     (system) trigger LogCenter 1.1.10-0151 Begin unload apparmor
2022/06/15 22:39:00     (system) trigger AntiVirus 1.4.9-2804 End start-stop-status stop ret=[0]
2022/06/15 22:39:00     (system) trigger HyperBackup 2.2.9-1520 End start-stop-status stop ret=[0]
2022/06/15 22:39:00     (system) trigger AntiVirus 1.4.9-2804 Begin unload apparmor
2022/06/15 22:39:03     (system) trigger HyperBackupVault 2.2.9-1520 End start-stop-status stop ret=[0]
2022/06/15 22:39:03     (system) trigger HyperBackupVault 2.2.9-1520 Begin unload apparmor
2022/06/15 22:39:03     (system) trigger AudioStation 6.5.6-3377 End start-stop-status stop ret=[0]
2022/06/15 22:39:07     (system) trigger AudioStation 6.5.6-3377 Begin unload apparmor
2022/06/15 22:39:08     (system) trigger HyperBackup 2.2.9-1520 Begin unload apparmor
2022/06/15 22:39:20     (system) trigger MediaServer 1.8.4-2884 End unload apparmor ret=[0]
2022/06/15 22:39:21     (system) trigger LogCenter 1.1.10-0151 End unload apparmor ret=[0]
2022/06/15 22:39:21     (system) trigger SynoFinder 1.5.2-0323 End unload apparmor ret=[0]
2022/06/15 22:39:21     (system) trigger HyperBackupVault 2.2.9-1520 End unload apparmor ret=[0]
2022/06/15 22:39:21     (system) trigger AntiVirus 1.4.9-2804 End unload apparmor ret=[0]
2022/06/15 22:39:22     (system) trigger FileStation 1.2.8-0293 End unload apparmor ret=[0]
2022/06/15 22:39:22     (system) trigger HyperBackup 2.2.9-1520 End unload apparmor ret=[0]
2022/06/15 22:39:22     (system) trigger CodecPack 1.0.1-0025 Begin start-stop-status stop
2022/06/15 22:39:22     (system) trigger CodecPack 1.0.1-0025 End start-stop-status stop ret=[0]
2022/06/15 22:39:22     (system) trigger DownloadStation 3.8.16-3566 End unload apparmor ret=[0]
2022/06/15 22:39:22     (system) trigger CodecPack 1.0.1-0025 Begin unload apparmor
2022/06/15 22:39:22     (system) trigger CodecPack 1.0.1-0025 End unload apparmor ret=[0]
2022/06/15 22:39:22     (system) trigger AudioStation 6.5.6-3377 End unload apparmor ret=[0]
2022/06/15 22:42:57     (system) trigger OAuthService 1.0.4-0031 Begin pre-load apparmor
2022/06/15 22:42:57     (system) trigger HyperBackup 2.2.9-1520 Begin pre-load apparmor
2022/06/15 22:42:57     (system) trigger AntiVirus 1.4.9-2804 Begin pre-load apparmor
2022/06/15 22:42:57     (system) trigger dotnet-runtime 6.0.4-1 Begin pre-load apparmor
2022/06/15 22:42:57     (system) trigger TextEditor 1.2.3-0029 Begin pre-load apparmor
2022/06/15 22:42:57     (system) trigger SynoFinder 1.5.2-0323 Begin pre-load apparmor
2022/06/15 22:42:57     (system) trigger StorageAnalyzer 2.0.1-0214 Begin pre-load apparmor
2022/06/15 22:42:57     (system) trigger FileStation 1.2.8-0293 Begin pre-load apparmor
2022/06/15 22:42:57     (system) trigger CodecPack 1.0.1-0025 Begin pre-load apparmor
2022/06/15 22:42:57     (system) trigger PythonModule 0115 Begin pre-load apparmor
2022/06/15 22:42:57     (system) trigger HyperBackupVault 2.2.9-1520 Begin pre-load apparmor
2022/06/15 22:42:57     (system) trigger py3k 3.8.6-0154 Begin pre-load apparmor
2022/06/15 22:42:57     (system) trigger LogCenter 1.1.10-0151 Begin pre-load apparmor
2022/06/15 22:42:58     (system) trigger AudioStation 6.5.6-3377 Begin pre-load apparmor
2022/06/15 22:42:58     (system) trigger DownloadStation 3.8.16-3566 Begin pre-load apparmor
2022/06/15 22:42:59     (system) trigger CodecPack 1.0.1-0025 End pre-load apparmor ret=[0]
2022/06/15 22:42:59     (system) trigger HyperBackup 2.2.9-1520 End pre-load apparmor ret=[0]
2022/06/15 22:42:59     (system) trigger StorageAnalyzer 2.0.1-0214 End pre-load apparmor ret=[0]
2022/06/15 22:42:59     (system) trigger py3k 3.8.6-0154 End pre-load apparmor ret=[0]
2022/06/15 22:42:59     (system) trigger PythonModule 0115 End pre-load apparmor ret=[0]
2022/06/15 22:42:59     (system) trigger dotnet-runtime 6.0.4-1 End pre-load apparmor ret=[0]
2022/06/15 22:42:59     (system) trigger LogCenter 1.1.10-0151 End pre-load apparmor ret=[0]
2022/06/15 22:42:59     (system) trigger CodecPack 1.0.1-0025 Begin start-stop-status start
2022/06/15 22:43:00     (system) trigger py3k 3.8.6-0154 Begin start-stop-status start
2022/06/15 22:43:00     (system) trigger StorageAnalyzer 2.0.1-0214 Begin start-stop-status start
2022/06/15 22:43:00     (system) trigger dotnet-runtime 6.0.4-1 Begin start-stop-status start
2022/06/15 22:43:00     (system) trigger PythonModule 0115 Begin start-stop-status start
2022/06/15 22:43:00     (system) trigger CodecPack 1.0.1-0025 End start-stop-status start ret=[0]
2022/06/15 22:43:00     (system) trigger py3k 3.8.6-0154 End start-stop-status start ret=[0]
2022/06/15 22:43:00     (system) trigger LogCenter 1.1.10-0151 Begin start-stop-status start
2022/06/15 22:43:00     (system) trigger dotnet-runtime 6.0.4-1 End start-stop-status start ret=[0]
2022/06/15 22:43:02     (system) trigger OAuthService 1.0.4-0031 End pre-load apparmor ret=[0]
2022/06/15 22:43:03     (system) trigger OAuthService 1.0.4-0031 Begin start-stop-status start
2022/06/15 22:43:04     (system) trigger TextEditor 1.2.3-0029 End pre-load apparmor ret=[0]
2022/06/15 22:43:04     (system) trigger HyperBackupVault 2.2.9-1520 End pre-load apparmor ret=[0]
2022/06/15 22:43:04     (system) trigger AntiVirus 1.4.9-2804 End pre-load apparmor ret=[0]
2022/06/15 22:43:04     (system) trigger SynoFinder 1.5.2-0323 End pre-load apparmor ret=[0]
2022/06/15 22:43:05     (system) trigger TextEditor 1.2.3-0029 Begin start-stop-status start
2022/06/15 22:43:05     (system) trigger AntiVirus 1.4.9-2804 Begin start-stop-status start
2022/06/15 22:43:05     (system) trigger TextEditor 1.2.3-0029 End start-stop-status start ret=[0]
2022/06/15 22:43:05     (system) trigger FileStation 1.2.8-0293 End pre-load apparmor ret=[0]
2022/06/15 22:43:05     (system) trigger SynoFinder 1.5.2-0323 Begin start-stop-status start
2022/06/15 22:43:06     (system) trigger HyperBackupVault 2.2.9-1520 Begin start-stop-status start
2022/06/15 22:43:07     (system) trigger HyperBackupVault 2.2.9-1520 End start-stop-status start ret=[0]
2022/06/15 22:43:07     (system) trigger FileStation 1.2.8-0293 Begin start-stop-status start
2022/06/15 22:43:09     (system) trigger PythonModule 0115 End start-stop-status start ret=[0]
2022/06/15 22:43:11     (system) trigger StorageAnalyzer 2.0.1-0214 End start-stop-status start ret=[0]
2022/06/15 22:43:13     (system) trigger LogCenter 1.1.10-0151 End start-stop-status start ret=[0]
2022/06/15 22:43:15     (system) trigger MediaServer 1.8.4-2884 Begin pre-load apparmor
2022/06/15 22:43:17     (system) trigger OAuthService 1.0.4-0031 End start-stop-status start ret=[0]
2022/06/15 22:43:26     (system) trigger HyperBackup 2.2.9-1520 Begin start-stop-status start
2022/06/15 22:43:27     (system) trigger FileStation 1.2.8-0293 End start-stop-status start ret=[0]
2022/06/15 22:43:35     (system) trigger HyperBackup 2.2.9-1520 End start-stop-status start ret=[0]
2022/06/15 22:44:11     (system) trigger AntiVirus 1.4.9-2804 End start-stop-status start ret=[0]
2022/06/15 22:44:33     (system) trigger SynoFinder 1.5.2-0323 End start-stop-status start ret=[0]
2022/06/15 22:44:41     (system) trigger AudioStation 6.5.6-3377 End pre-load apparmor ret=[0]
2022/06/15 22:44:41     (system) trigger DownloadStation 3.8.16-3566 End pre-load apparmor ret=[0]
2022/06/15 22:44:41     (system) trigger MediaServer 1.8.4-2884 End pre-load apparmor ret=[0]
2022/06/15 22:44:42     (system) trigger DownloadStation 3.8.16-3566 Begin start-stop-status start
2022/06/15 22:44:42     (system) trigger MediaServer 1.8.4-2884 Begin start-stop-status start
2022/06/15 22:44:43     (system) trigger AudioStation 6.5.6-3377 Begin start-stop-status start
2022/06/15 22:44:48     (system) trigger MediaServer 1.8.4-2884 End start-stop-status start ret=[0]
2022/06/15 22:44:58     (system) trigger DownloadStation 3.8.16-3566 End start-stop-status start ret=[0]
2022/06/15 22:44:58     (system) trigger AudioStation 6.5.6-3377 End start-stop-status start ret=[0]
```

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This PR contains the following:

1. Update to dotnet-runtime v6.0.14 (security patches)
2. Refinement of unsupported armv7 archs

Follow up of #5301 and #5574
Fixes #5315

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [x] Package update

### CODE REVIEW

**Comment by mreid-tt** [comment]
@hgy59, I've created an update to dotNET runtime for your review as the package maintainer. Once there are no issues and the package is published, I would recommend un-publishing v6.0.12-3 from the repository to remove the incompatible combination of ARMv7 archs and DSM6.

**Comment by mreid-tt** [comment]
@hgy59, I've done some basic testing of this under DSM7 as follows:
* Clean install log -- https://pastebin.com/fE69HqLa
* Upgrade install log -- https://pastebin.com/ynyfF2WY

As for functional testing, I checked that the runtime environment was working via:
```
$ dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.14
  Architecture: x64
  Commit:       2a90daa2cc

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [/volume1/@appstore/dotnet-runtime/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [/volume1/@appstore/dotnet-runtime/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```
The above result was the same for clean install as well as upgrade install. If there are other test you'd like me to run let me know.

**Comment by mreid-tt** [comment]
@hgy59, is this good to merge?

**Review by hgy59 — APPROVED** [review]
LGTM

**Pull request merged**
