### PR TITLE
Mono: Removed beta flag & redundancy

### PR DESCRIPTION
**Pull request by maxrogers**

### CODE REVIEW

**Comment by Dr-Bean** [comment]
Maybe see if #1557 and #1558 can be addressed too?

**Comment by maxrogers** [comment]
@Dr-Bean, haha thanks! I made those fixes and squashed

**Comment by Diaoul** [comment]
I'll give it a shot but I think it should work just fine :)

**Comment by Dr-Bean** [comment]
Okay, just to be sure: after building the Mono package, test it too (before publishing)
On one of my devices, the current Mono package on the repo works with Sonarr just fine. After installing the package I just built, Sonarr won't start anymore, without any indication as to why. That might be my build environment or that device, but it's strange to say the least.

**Comment by Dr-Bean** [comment]
Oh. #1609? :D

**Comment by maxrogers** [comment]
Yeah, sorry. I tested it and saw that it ran appropriately. However, I didn't test actually running a program that needed libraries (sonarr.) I will make sure to do that next time!

**Comment by Dr-Bean** [comment]
Sure, I was not putting any blame you at all. I'm in the process of rebuilding my build/test environment, so it's hard to pinpoint a cause. Anyway, building (again...;)) as we speak. I'll merge when I can confirm the fix :)

**Comment by maxrogers** [comment]
Awesome! And I will publish once you confirm and merge. Fun stuff! Thanks @Dr-Bean

**Pull request merged**
