### PR TITLE
Update Maintainer in package INFO file

### PR DESCRIPTION
**Pull request by hgy59**
## Description

Link maintainer_url to github user when applicable
User github user name of maintainer when applicable

## Checklist

- [x] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [ ] Package update
- [x] Includes small framework changes
- [x] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
just updated the wiki https://github.com/SynoCommunity/spksrc/wiki/Makefile-variables

**Comment by th0ma7** [comment]
LGTM.  Anything we can do about `MAINTAINER = SynoCommunity`, probably not?

**Review by th0ma7 — APPROVED** [review]

**Comment by th0ma7** [comment]
I also updated the https://github.com/SynoCommunity/spksrc/wiki/Update-Policy which refered to `MAINTAINER_URL` variable.  Not sure but there may be a need for additional adjustments in that page?!

**Comment by hgy59** [comment]
> I also updated the https://github.com/SynoCommunity/spksrc/wiki/Update-Policy which refered to `MAINTAINER_URL` variable. Not sure but there may be a need for additional adjustments in that page?!

On this page there was no problem as defining `MAINTAINER_URL ?=` does nothing, but it is better to abandon `MAINTAINER_URL`  from local.mk.

We could omit  `MAINTAINER ?=` too, as it does nothing. `make synocommunity-setup` (used in GH build action) still sets default maintainer with  `MAINTAINER ?= SynoCommunity`.
As IMHO we always want a package to define a maintainer (even `SynoCommunity`), we could remove `MAINTAINER` from local.mk.

**Comment by th0ma7** [comment]
Sounds good!

**Comment by th0ma7** [comment]
I've removed `MAINTAINER` as well from the page..

**Pull request merged**
