### PR TITLE
couchpotatoserver-custom : Update dsm-control.sh

### PR DESCRIPTION
**Pull request by simenon**
Fixes startup script to use sudo instead of su for DSM 6.0 and higher.

### CODE REVIEW

**Comment by Dr-Bean** [comment]
See https://github.com/SynoCommunity/spksrc/pull/2230#issuecomment-205181130.

Fore future reference, please add the package name in the title and add a description that fits the changes.

**Comment by Dr-Bean** [comment]
I meant the actual comment :)

>This probably won't be merged. Using su or sudo isn't the issue here, it's the way users are created that causs the bulk of the issues.

>Besides that, this doesn't scale: there are several packages that (still) won't work with this approach, and we're not going to implement fixes on a package-by-package basis.

**Comment by simenon** [comment]
I have read the actual comment. And i can agree that it does not scale. However if you want to run the process under a user, you'll have to use su (or sudo in newer DSM 6+). 

I can not think of a better solution to solve the problem then just fixing the start-stop script for couchpotato. As the rest of the permissions and user creation are in my opinion correct.

At this point this is the only working solution to get couchpotato to run under DSM6. 

If u have a better solution to tackle it, i'll gladly try to help out.

**Comment by Dr-Bean** [comment]
https://github.com/SynoCommunity/spksrc/issues/2216.

**Comment by simenon** [comment]
@Dr-Bean #2216 relates to creating users, and not running a process under a certain users. This fix #2241 implies running a proces under a certain user (The change from su DSM5 to sudo DSM6)

**Comment by Dr-Bean** [comment]
The point is that if users are created in a way that DSM6 supports, there's no reason to switch from `su` to `sudo`. This PR is not a fix, but a workaround that only applies to certain conditions.

**Comment by simenon** [comment]
Given that if you can create a valid user, then there is no problem, and all works fine. Verified

Personally i prefer to have no login shell for these kind of pkg users, and as such i kinda have to alter the su command to include a shell, or just run sudo. Personally I prefer to use sudo instead of su, And since we have sudo nowadays, we can use it ...

Closing this.

**Comment by Dr-Bean** [comment]
As the other issue shows, DSM6 provides a way to create system users without a valid shell (that can subsequently be passed on via `su -s`, or whatever the switch is to pass on a shell), so that should cover your preference at least in part.
The current method via busybox was always a workaround, seeing as Synology didn't provide a viable way to create a system user with a valid shell. Feel free to contribute to the other issue if you can/want to help out.

**Pull request closed without merging**
