### PR TITLE
ffmpeg: Add dash demuxer support (requires libxml2)

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  Add support for DASH Demuxing
_Linked issues:_  #4639

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by th0ma7** [comment]
@publicarray quick question for you, I have noticed ` failed: Connection timed out.` happening lately and I am wondering if this is momentarily of due to the recent parallel build merge?

Another thought I had: could we cache the download files instead of re-downloading always?  Not that this fixes the issue but would reduce github-action compile time and avoid theses?

**Comment by publicarray** [comment]
>happening lately and I am wondering if this is momentarily of due to the recent parallel build merge?

I have no idea what is causing it. Maybe GitHub has a new rate limiting system?

Regarding caching `/distrib` I'm sure this will course more issues than it solves (old files, unclean builds etc). Rather I would like to propose to download the files only once per run. At the moment every architecture run downloads the same file. To implement that we would need to know which files to download before we run make (not sure if this is possible).

**Comment by th0ma7** [comment]
>  To implement that we would need to know which files to download before we run make (not sure if this is possible).

Well, that should be easy, no?  There already is a `make dependency-list` which currently allows building `native` first for instance.  There could be a call such as `make download-all-supported` to download everything needed for all supported archs... Would that suffice for you?

**Comment by arnebjarne** [comment]
> 
> 
> > To implement that we would need to know which files to download before we run make (not sure if this is possible).
> 
> Well, that should be easy, no? There already is a `make dependency-list` which currently allows building `native` first for instance. There could be a call such as `make download-all-supported` to download everything needed for all supported archs... Would that suffice for you?

I guess a simple bash
```
test -f PACKAGE
```


> 
> 
> > happening lately and I am wondering if this is momentarily of due to the recent parallel build merge?
> 
> I have no idea what is causing it. Maybe GitHub has a new rate limiting system?
> 
> Regarding caching `/distrib` I'm sure this will course more issues than it solves (old files, unclean builds etc). Rather I would like to propose to download the files only once per workflow run. At the moment every architecture run downloads the same file. To implement that we would need to know which files to download before we run make (not sure if this is possible).

>Regarding caching /distrib

As long as you check the file against the digest checksum, caching ./distrub should be safe IMHO.

**Comment by th0ma7** [comment]
> > Regarding caching /distrib
> 
> As long as you check the file against the digest checksum, caching ./distrib should be safe IMHO.

Actaully, you're right.  As all builds start with validation of the digests we're in theory good to go and `distrib/*` and its sub-directory could be entirely cached, reducing download significantly and, again, make the build faster.

**Comment by arnebjarne** [comment]
> 
> 
> > > Regarding caching /distrib
> > 
> > 
> > As long as you check the file against the digest checksum, caching ./distrib should be safe IMHO.
> 
> Actaully, you're right. As all builds start with validation of the digests we're in theory good to go and `distrib/*` and its sub-directory could be entirely cached, reducing download significantly and, again, make the build faster.

I am not well trained in Git :) but itsnt there something about git submodules?
( https://git-scm.com/book/en/v2/Git-Tools-Submodules )
ie

i git clone https://github.com/SynoCommunity/spksrc
and get an empty ./distrib by default (to safe download time).

but if i do 
git clone --recurse-submodules https://github.com/SynoCommunity/spksrc
it could download all packages in https://github.com/SynoCommunity/spksrc/distrib
?

and i guess the github build thing have a direct access to the files via their infrastructure 

Just an idea.
BR,
Bjarne

**Comment by hgy59** [comment]
> and i guess the github build thing have a direct access to the files via their infrastructure

No this does not work as you expect, no files in the distrib folder are under source control.

**Comment by hgy59** [comment]
> As long as you check the file against the digest checksum, caching ./distrib should be safe IMHO.

To avoid deadlocks for the (rare) case of digests change for equal file name I like the idea to cache the download files within a workflow only.

**Comment by th0ma7** [comment]
@hgy59 duno if it is due to your latest changes but builds are now all ok!

**Pull request merged**
