### PR TITLE
Ntop

### PR DESCRIPTION
**Pull request by cytec**
finally got ntopng working

### CODE REVIEW

**Comment by nickbroon** [comment]
Ntop 2.0 was released a few days ago, might be worth trying to update to that.

**Comment by ardenee** [comment]
Hi, please forgive my ignorance, but I can't seem to get this going on my ds2411+ with DSM 6 beta 2.

It installs and says it's running but there is no shortcut, and the command ntopng is unknown to the shell. Nothing is listening on port 3000 etc, very little in the way of documentation, some pointers would be helpful! Thanks!

**Comment by cytec** [comment]
have not tested with DSM 6 so there may be some errors because of that..
ntop gets installed in `/usr/local/ntop/bin/ntop` maybe try use that binary to start it

**Comment by KaraokeStu** [comment]
Hi, please could you rebase and confirm this all still works ok - I'm trying to clean up old pull requests.

If I don't hear anything by 31st July 2017, I will close the PR.

Thanks,

Stuart

**Comment by ymartin59** [comment]
@cytec @KaraokeStu Moreover I would like commit 6d9b2e221864d8d54d18d4131f0cecbeb0dad100 to have a more explicit message like "Add ntop dependencies: json-c, luajit, rrdtool"

**Comment by KaraokeStu** [comment]
Is it worth closing and reopening a new pr?

**Comment by ymartin59** [comment]
@KaraokeStu  I do not think so  @cytec only has to do interactive rebase to edit commit message and this PR will be updated after its push

**Comment by cytec** [comment]
Im getting to this, but i think that'll might not be before the 31st July...

**Comment by hgy59** [comment]
I did not succeed to rebase this PR.
@cytec, @ymartin59 is there any chance to rebase this PR to the current upstream? The provided link to use the command line did not work for me. May be there is a better tutorial somewhere?

I have a current working version of `ntopng` based on this PR and I would like to integrate it here. Otherwise I will have to create a new PR.

**Pull request closed without merging**
