### PR TITLE
Update SABnzbd and SABnzbd testing to 2.3.0 Final

### PR DESCRIPTION
**Pull request by Safihre**
_Motivation:_ Update SABnzbd and SABnzbd testing to 2.3.0 Final
_Linked issues:_ None

### Checklist
- [x] Build rule `all-supported` completed successfully: https://travis-ci.org/Safihre/spksrc/builds/278104479

And of course also needs #2923.

### CODE REVIEW

**Comment by Safihre** [comment]
Here you wrote you wanted separate PR's: https://github.com/SynoCommunity/spksrc/pull/2905#issuecomment-329255124
But now you say you want it in 1 PR, so here you go!

**Comment by ymartin59** [comment]
It even make sense to include par2cmdline update here as it is mentioned in changelog.

**Comment by ymartin59** [comment]
I requested a "single-commit PR" because the PR #2905 contains 4 commits, and most annoying: some of them replace changes introduced by others.
So all changes in a single commit is "the best" option, but a clean set of commit (for instance one commit for each dependency) is also acceptable

**Comment by Safihre** [comment]
> and most annoying: some of them replace changes introduced by others.

What are you talking about? What changes by others?

**Comment by ymartin59** [comment]
3 different upstream versions referred in PR commit list: https://github.com/SynoCommunity/spksrc/pull/2905/commits
So it means each one changed Makefile with alpha1, alpha2, rc1... Probably you will find git "commit --amend" and "rebase --interactive" as an interesting way to submit "single-comit PR": https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by Safihre** [comment]
I guess I just misunderstood you before. I am very well aware how to rebase, just did not know that's what you wanted.

**Pull request merged**
