### PR TITLE
Fix bazarr build to use PLIST.auto

### PR DESCRIPTION
**Pull request by smaarn**
_Motivation:_  bazarr was no longer packaged properly

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by th0ma7** [comment]
I was about to look at this based on @smaarn comment https://github.com/SynoCommunity/spksrc/pull/4998#issuecomment-1003697487 and I believe this is exactly what is need for fixing #4998.

One thing I noticed (and I believe unrelated to PLIST.auto) is that it included python PLIST while marked as `BUILD_DEPENDS` wheras I thought it would discard it from the package.

**Comment by hgy59** [comment]
> I was about to look at this based on @smaarn comment [#4998 (comment)](https://github.com/SynoCommunity/spksrc/pull/4998#issuecomment-1003697487) and I believe this is exactly what is need for fixing #4998.
> 
> One thing I noticed (and I believe unrelated to PLIST.auto) is that it included python PLIST while marked as `BUILD_DEPENDS` wheras I thought it would discard it from the package.

If it is a PLIST related issue, this might be caused by #5018.
I fixed this by removing `*` from PLIST files in another PR.

**Comment by th0ma7** [comment]
> > I was about to look at this based on @smaarn comment [#4998 (comment)](https://github.com/SynoCommunity/spksrc/pull/4998#issuecomment-1003697487) and I believe this is exactly what is need for fixing #4998.
> > One thing I noticed (and I believe unrelated to PLIST.auto) is that it included python PLIST while marked as `BUILD_DEPENDS` wheras I thought it would discard it from the package.
> 
> If it is a PLIST related issue, this might be caused by #5018. I fixed this by removing `*` from PLIST files in another PR.

AFAIK the changes you made looked good to me and quickly looking at things I believe its unrelated.
I've quickly drafted an issue #5039 to track it aside from this PR as totally unrelated to this specifically.

@smaarn I believe this PR is good for a merge.

**Review by th0ma7 — APPROVED** [review]

**Comment by smaarn** [comment]
> I was about to look at this based on @smaarn comment [#4998 (comment)](https://github.com/SynoCommunity/spksrc/pull/4998#issuecomment-1003697487) and I believe this is exactly what is need for fixing #4998.
> 
> One thing I noticed (and I believe unrelated to PLIST.auto) is that it included python PLIST while marked as `BUILD_DEPENDS` wheras I thought it would discard it from the package.

Indeed I saw the issue where it was also taking into account everything which was only in first file and not added. I believe this should be fixed by this PR.

**Comment by th0ma7** [comment]
> Indeed I saw the issue where it was also taking into account everything which was only in first file and not added. I believe this should be fixed by this PR.

@smaarn good catch!  Tested against #4998 and running smoothly!

**Review by th0ma7 — APPROVED** [review]

**Pull request merged**
