### PR TITLE
Update ps3netsrv

### PR DESCRIPTION
**Pull request by The-MAD-Virus**
_Motivation:_  update to the latest available version.
_Linked issues:_  #3744

I need help to make it clean.

### Checklist
- [x] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by hgy59** [comment]
@The-MAD-Virus, as I lerned in https://github.com/aldostools/webMAN-MOD/issues/252 the old polarssl library is used and will not be updated.

So I would propose to create a polarssl cross package for ps3netsrv only, due following reasons
- the ps3netsrv build will fail, if cross/polarssl would be updated
- other (future) packages depending on polarssl of a different version can not use this

Here is a patch that will add such a polarssl version named `cross/ps3netsrv-libpolarssl`
- the package is called ps3netsrv-libpolarssl since only the (static) library is created and it is for ps3netsrv only
- it uses Makefile.linux instead of Makefile to build the library
- Makefile.linux is patched to find the location of the cross compiled polarsssl library
- only libpolarssl.a is exported in PLIST since this is the only dependency of ps3netsrv

The patch is based on the current master (commit 4cf516f84b30f2c6c1ff6bc269dd49fa06b77353)
With this version I succressfully built all-supported archs (except northstarplus and hi3535 due "Toolchain 1.x is lower than required version in Makefile 5.0")

I did not test the installation on a diskstation since I do not own any PS3.
hope you succeed with this update.


[ps3netsrv.patch.zip](https://github.com/SynoCommunity/spksrc/files/3464285/ps3netsrv.patch.zip)

PS: the patch is created with git diff (and not with git format-patch) so you can apply it with:
`patch -p1  -i ps3netsrv.patch`
in the working directory

**Comment by hgy59** [comment]
@The-MAD-Virus forget about the patch I created just before this post.
There is a much simpler solution already mentioned in https://github.com/aldostools/webMAN-MOD/issues/252 by @mwkroening (execute `make -C polarssl-1.3.2/library` first)

This can be done by a pre_compile rule, so the final Makefile of /cross/ps3netsrv looks like this:

```
PKG_NAME = ps3netsrv
PKG_VERS = 1.47.25
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://github.com/aldostools/webMAN-MOD/archive
PKG_DIST_FILE = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIR = webMAN-MOD-$(PKG_VERS)/_Projects_/$(PKG_NAME)

DEPENDS = 

HOMEPAGE = https://github.com/aldostools/webMAN-MOD
COMMENT = Allows PS3 content to be loaded from network
LICENSE = GPL

GNU_CONFIGURE = 1
CONFIGURE_ARGS =

CONFIGURE_TARGET = nop
INSTALL_TARGET = ps3netsrv_install

PRE_COMPILE_TARGET = ps3netsrv_pre_compile
COMPILE_MAKE_OPTIONS = -f Makefile.linux

include ../../mk/spksrc.cross-cc.mk

.PNONY: ps3netsrv_pre_compile
ps3netsrv_pre_compile:
		@$(RUN) $(MAKE) -C polarssl-1.3.2/library

.PHONY: ps3netsrv_install
ps3netsrv_install:
		@mkdir -p $(STAGING_INSTALL_PREFIX)/bin
		@install -m 755 $(WORK_DIR)/$(PKG_DIR)/$(PKG_NAME) $(STAGING_INSTALL_PREFIX)/bin/
```

This compiles successfully without any additional cross package for polarssl

**Comment by The-MAD-Virus** [comment]
perfect i'll try this tomorrow.

**Comment by mwkroening** [comment]
I reworked `ps3netsrv` in https://github.com/aldostools/webMAN-MOD/pull/253 to support `mbed TLS` and use the modern `Meson Build system` instead of `Make`. With some adjustments the changes have been merged.

See [`aldostools/webMAN-MOD/_Projects_/ps3netsrv/README.md`](https://github.com/aldostools/webMAN-MOD/blob/master/_Projects_/ps3netsrv/README.md) for details on how to build it. It should work with the latest version of `PolarSSL` now known as `mbed TLS`.

**Comment by ymartin59** [comment]
Notice `PLIST` file is used for copying files to `staging` so that they are included in package. Not the place for a static `.a` file...

**Comment by ymartin59** [comment]
@The-MAD-Virus Looks like `cross/polarssl` is lacking in PR. What is your status about it?

**Comment by hgy59** [comment]
@ymartin59 there is no need off cross/polarssl. The source needed to build polarssl is already contained in source package of ps3netsrv. And a makefile too. See my posting above (of 3 Aug 2019)

**Comment by The-MAD-Virus** [comment]
@ymartin59 I'm just waiting for [aldostools/webMAN-MOD](https://github.com/aldostools/webMAN-MOD) to releases there new version. because they drop using ```polarssl``` for the new ```mbed TLS``` library.

**Comment by ymartin59** [comment]
@The-MAD-Virus What is status for this draft PR?

**Comment by The-MAD-Virus** [comment]
@ymartin59 still waiting for the new release or is it ok to use there master/dev repository ?

**Comment by ymartin59** [comment]
@The-MAD-Virus It may be possible to package "release candidate" with "fake" version number, before next planned - for instance "4.3.99rc1" when "4.4.0" is pending - and to refer sources with Git hash.

**Pull request merged**
