### PR TITLE
Fixing invalid port in Radarr package

### PR DESCRIPTION
**Pull request by KaraokeStu**
_Motivation:_ Updated to update the ports on Radarr to 8310 and 8311
_Linked issues:_ Should fix https://github.com/SynoCommunity/spksrc/issues/2652

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by ressu** [comment]
Thanks. Never found the time to do the tests, bit overwhelmed with other stuff at the moment.

**Comment by KaraokeStu** [comment]
No problem @ressu , thanks for creating the package in the first place!

I help where I can!

**Comment by MostDefiantly** [comment]
I am able to install this now, thank you everyone for the effort to get it working.

**Comment by SuperDOS** [comment]
hmm it won't start, any ideas which logs to look for why?

**Comment by M0UL** [comment]
this has not updated the port  for my radarr config. but it says it has updated the port in dsm. but it was stil using the previous defautl port.

**Comment by KaraokeStu** [comment]
Hi, the port is not updated as part of an upgrade (it leaves your config file intact), however it does set it correctly on new installs

**Comment by SuperDOS** [comment]
Noticed this, had to remove and reinstall it, was a bit confusing how to restore the backup but finally managed to find where the DB should reside. :)

**Comment by KaraokeStu** [comment]
It's a beta version, but as a general rule we don't update port numbers our config entries as part of an upgrade. Many people use non standard ports too

**Comment by ressu** [comment]
Also changing port configuration during upgrades causes more issues than it fixes. The only side effect at the moment is that the link doesn't immediately work.

On the other hand, updating the port during upgrade causes integrations to fail and will most likely confuse the user that is already used a different port. Then there is the matter of user set custom ports, we would need to detect whether the port is still the default port or not and we have no way of knowing if the user has manually set the port back to the old default etc etc.

So yeah, beta package and a good policy in general.

**Pull request merged**
