### PR TITLE
Update Gitea to v1.22.0

### PR DESCRIPTION
**Pull request by wkobiela**
## Description

Fixes # 

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by wkobiela** [comment]
```
Gitea requires Go 1.22 or greater to build.
```

**Comment by hgy59** [comment]
In #6094 I already found that using go1.22 with `CGO_ENABLED = 1` fails to build gitea for ARMv5. 
Without CGO, gitea successfully builds for all archs.

Somewhere found a note that CGO is required for sqlite3.
But a short test without CGO was successful on x64 arch.

**Comment by hgy59** [comment]
@wkobiela as #6094 is now merged, you can continue with the gitea update.
I propose to mark gitea unsupported for ARMv5 archs.

**Comment by wkobiela** [comment]
Checks passed, need to test it tho, will do it later on x64 dsm7.1 VM

**Comment by hgy59** [comment]
There is still an open issue for ARMv5 in https://github.com/golang/go/issues/65290

But for gitea the errors a not exactly the same as mentioned there:
```
# runtime/cgo
gcc_libinit.c: In function '_cgo_wait_runtime_init_done':
gcc_libinit.c:44:2: error: implicit declaration of function '__atomic_load_n' [-Werror=implicit-function-declaration]
gcc_libinit.c:44:47: error: '__ATOMIC_CONSUME' undeclared (first use in this function)
gcc_libinit.c:44:47: note: each undeclared identifier is reported only once for each function it appears in
gcc_libinit.c:71:3: error: implicit declaration of function '__atomic_store_n' [-Werror=implicit-function-declaration]
gcc_libinit.c:71:46: error: '__ATOMIC_RELEASE' undeclared (first use in this function)
gcc_libinit.c: In function 'x_cgo_notify_runtime_init_done':
gcc_libinit.c:122:42: error: '__ATOMIC_RELEASE' undeclared (first use in this function)
gcc_libinit.c: In function 'x_cgo_set_context_function':
gcc_libinit.c:130:51: error: '__ATOMIC_RELEASE' undeclared (first use in this function)
gcc_libinit.c: In function '_cgo_get_context_function':
gcc_libinit.c:135:48: error: '__ATOMIC_CONSUME' undeclared (first use in this function)
gcc_libinit.c:136:1: error: control reaches end of non-void function [-Werror=return-type]
cc1: all warnings being treated as errors
```

**Comment by hgy59** [comment]
The dependency of libatomic in gco runtime was introduced by the commit https://go-review.googlesource.com/c/go/+/505455.

We could create a `native/go-no-libatomic` with reverted changes in `src/runtime/cgo/gcc_libinit.c` of this commit, to build gitea for ARMv5.
Affected models are: DS213air, DS213, DS413j, DS112, DS112+, DS212, DS212+, RS212, RS812, DS212j, DS112j, DS111, DS211, DS211+, DS411slim, DS411, RS411, DS211j, DS411j.
I doubt it is worth the effort just for the ARMv5 models.

Thoughts:
- even with a patched  `native/go-no-libatomic` some manual steps are required to ignore `native/go` for armv5 builds of gitea
- it will be hard to maintain the patch when future versions of go will change the patched file
- all affected models are 10+ years old
- current go requires at least gcc 4.6 (see below) and the ARMv5 toolchain has gcc 4.6.4 (but no libatomic)

BTW:
The only reference I found that mentions a min. version of gcc is https://github.com/golang/go/issues/43605

**Pull request merged**
