### PR TITLE
CI: fix parallel builds. Add manual builds and print more details on error

### PR DESCRIPTION
**Pull request by publicarray**
_Motivation:_  Fixes `local.mk` with spaces. It makes it much easier to find the error line in a long log file. No more grepping or hunting for it. And this PR allows us to build any package on demand manually.

Here is an example build: https://github.com/publicarray/spksrc/runs/3432175214?check_suite_focus=true

And the output:

```
 BUILD STATUS

SUCCESS:
none.

UNSUPPORTED (skipped):
none.

Error: ERRORS:
2021.08.26 11:37:20 - squidguard: (x64-7.0) FAILED

See log file of the build job to analyze the error(s).

Last 15 lines of the build log:

$ make TCVERSION=7.0 ARCH=x64 -C ./spk/squidguard
make[2]: Leaving directory '/github/workspace/spk/squidguard/work-x64-7.0/unrar'
find /github/workspace/spk/squidguard/work-x64-7.0/install//usr/local/squidguard/ \! -type d -printf '%P\n' | sort | \
  diff /github/workspace/spk/squidguard/work-x64-7.0/unrar.plist.tmp -  | grep '>' | cut -d' ' -f2- > /github/workspace/spk/squidguard/work-x64-7.0/unrar.plist
# Generate unrar.plist.auto for newly added files (diff against .tmp)
comm -3 /github/workspace/spk/squidguard/work-x64-7.0/unrar.plist.tmp /github/workspace/spk/squidguard/work-x64-7.0/unrar.plist > /github/workspace/spk/squidguard/work-x64-7.0/unrar.plist.auto
make[1]: Leaving directory '/github/workspace/cross/unrar'
make[1]: Entering directory '/github/workspace/cross/squidclamav'
===>  Downloading files for squidclamav
===>    wget https://downloads.sourceforge.net/project/squidclamav/squidclamav/6.10/squidclamav-6.10.tar.gz
https://downloads.sourceforge.net/project/squidclamav/squidclamav/6.10/squidclamav-6.10.tar.gz:
2021-08-26 11:37:20 ERROR 404: Not Found.
make[1]: *** [../../mk/spksrc.download.mk:65: download_target] Error 8
make[1]: Leaving directory '/github/workspace/cross/squidclamav'
make: *** [../../mk/spksrc.depend.mk:51: depend_target] Error 2
make: Leaving directory '/github/workspace/spk/squidguard'
```

### CODE REVIEW

**Review by ymartin59 — APPROVED** [review]

**Comment by hgy59** [comment]
There are some warnings on github build action related to -j option:
```

 ---- initialize build
 ---- find dependent packages
  Building dependency list...
  make[3]: warning: -j2 forced in makefile: resetting jobserver mode.
  make[4]: warning: -j2 forced in makefile: resetting jobserver mode.
  make[4]: warning: -j2 forced in makefile: resetting jobserver mode.
  make[5]: warning: -j2 forced in makefile: resetting jobserver mode.
```

**Comment by publicarray** [comment]
@hgy59 was this before or after #4849 was merged?

**Comment by hgy59** [comment]
I found this log on https://github.com/SynoCommunity/spksrc/runs/3572260089?check_suite_focus=true
of #4851 that terminated 3 hours ago.

**Comment by publicarray** [comment]
Googling this, it just warning you that parallelism for cmake is one layer above. And it is stopping what would otherwise be a 2*n processes. cc/ @th0ma7

**Comment by publicarray** [comment]
`CMake Error: Unknown argument --parallel`

**Comment by hgy59** [comment]
we might turn off parallel builds for `dependency-list` target.

**Comment by publicarray** [comment]
Thanks for the find @hgy59

Here is what I found:
https://github.com/SynoCommunity/spksrc/commit/a442e16582503d6562605aedd7a2aa6b9d4e7165#diff-d36a885a35ee29c1ae39c8d2b3acb38b82cd30bd8ea297a445ae4282d2330723R42

https://gitlab.kitware.com/cmake/cmake/-/issues/21978#note_968161

so the command needs to be updated

**Comment by publicarray** [comment]
I think @th0ma7 might know more about the warning. I'm not sure how to stop a single target parallel build.

**Comment by th0ma7** [comment]
> we might turn off parallel builds for `dependency-list` target.

Agreed, will look into it.  already having a few fixes pending at https://github.com/SynoCommunity/spksrc/pull/4854 
I'll force a github action ffmpeg build to check out the full log output later and see what's still missing.
If you have a moment please have it a try.  I'll come back on it by tomorrow.

**Pull request merged**
