### PR TITLE
Update SABnzbd and SABnzbd-testing to 2.3.1

### PR DESCRIPTION
**Pull request by Safihre**
_Motivation:_ Update `sabnzbd` and `sabnzbd-testing` to SABnzbd 2.3.1.
_Linked issues:_ #2973

### Checklist
- [x] Build rule `all-supported` [completed successfully](https://travis-ci.org/Safihre/spksrc/builds/293561368)

### CODE REVIEW

**Comment by Safihre** [comment]
Not to sound ungrateful, but could this get published? It's been 2 weeks.
It's a simple update with no dependency update etc
Thanks 👍

**Comment by cytec** [comment]
@Safihre sorry! merged and running builds now ;)

**Comment by Safihre** [comment]
Thank you :+1: :+1:

**Comment by enigma2k** [comment]
thank you!!!

**Pull request merged**
