### PR TITLE
Gentoo Chroot

### PR DESCRIPTION
**Pull request by MasterRoot24**
I've created a package called Gentoo Chroot, which is based on the existing Debian Chroot package.

Builds succeed for all architectures defined in the `Makefile`. However, I only have a DS214play (evansport) available to test on, so I'm not sure if this installs/runs on other architectures.

I've squashed down all my commits to 7 major changes, which I hope helps.

### CODE REVIEW

**Comment by bolzerrr** [comment]
Is it possible that you provide the merge in your own repository. I´d like to test..

**Comment by MasterRoot24** [comment]
@bolzerrr Erm, just pull the branch from my fork: https://github.com/MasterRoot24/spksrc/tree/gentoo-chroot

**Comment by bolzerrr** [comment]
Ups jsut browsed your repo but didn´t see it, thanks!

**Comment by bolzerrr** [comment]
Can´t build: 

 make arch-evansport
===>  Building package for arch evansport
make[1]: Entering directory `/usr/local/src/spksrc2/spk/gentoo-chroot'
===>  Striping binaries and libraries of gentoo-chroot
wget -nv -c -O /usr/local/src/spksrc2/spk/gentoo-chroot/work-evansport/stage3-i686-20141209.tar.bz2 http://distfiles.gentoo.org/releases/x86/autobuilds/20141209/stage3-i686-20141209.tar.bz2 195643340
make[1]: *** [gentoo-chroot_extra_install] Error 4
make[1]: Leaving directory `/usr/local/src/spksrc2/spk/gentoo-chroot'
make: [arch-evansport] Error 2 (ignored)

**Comment by MasterRoot24** [comment]
@bolzerrr To save polluting this PR, please file an issue on my fork [here](https://github.com/MasterRoot24/spksrc/issues) and I'll try and take a look into it when I get chance.

FYI: I no longer own a Synology NAS, so I'm not guaranteeing I can sort it.

**Comment by MasterRoot24** [comment]
@Diaoul Please can you provide a reason as to why this was closed?

**Comment by Diaoul** [comment]
All PR were closed because I renamed the branch develop to master. I asked the support to fix it but you can reopen against master.

**Pull request closed without merging**
