### PR TITLE
python310: Update to version 3.10.2 and crossenv to 1.2.0

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

Special bugfix release ahead of schedule to address a memory leak that was happening on certain function calls when using Cython.  Upgrading existing Python 3.10 installations is highly recommended. Even though this is an expedited release, it still contains over 100 other bug fixes.

https://pythoninsider.blogspot.com/2022/01/python-3102-3910-and-3110a4-are-now.html

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Review by smaarn — APPROVED** [review]
Seems pretty simple for a PR 😊

**Review by Safihre — APPROVED** [review]

**Comment by th0ma7** [comment]
@Safihre yeah I'm glad it's now become simpler & simpler as PR continue to flow in.  Still, in this specific case, I stumbled on a build issue with the latest `setuptools` version 60.5.0.  That's why I wanted to update all the regular parts, confirm all lights are green and only re-try the setuptools update.

Waiting for the github-action to confirm merge OR open an issue on https://github.com/pypa/setuptools

**Comment by th0ma7** [comment]
Remaining build errors from github-action are irrelevant, merging.
```
ERROR: The certificate of ‘znc.in’ is not trusted.
ERROR: The certificate of ‘znc.in’ has expired.
```

**Comment by th0ma7** [comment]
@hgy59 where python 3.10.2 version deleted from server?  I can't find them anywhere (or have I simply forgot to release it?)

**Pull request merged**
