### PR TITLE
ownCloud: Update to v10.14.0

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This PR contains the following:

1. Update ownCloud to version 10.14.0
2. Enable `iconv` php module

Fixes # 

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by mreid-tt** [comment]
@hgy59 @th0ma7, I'm not sure what's going on here. I've built a new version of a very basic package (ownCloud) and then tried to publish it without success: https://github.com/mreid-tt/spksrc/actions/runs/9440376248. Any thoughts?

**Comment by hgy59** [comment]
Regarding the build log, the package is not even built, it is only supposed to be uploaded.

Probably related to #6002
There already have been attemps to fix publishing in #6038, #6064, #6066. #6067, ...

#6002 was merged on April 1st, 2024. Has no one published "noarch" packages recently.

**Comment by mreid-tt** [comment]
> #6002 was merged on April 1st, 2024. Has no one published "noarch" packages recently.

Hmm, I wouldn't say that is true since [AriaNg](https://github.com/SynoCommunity/spksrc/pull/5860) was published on 2024-04-07. However it may be the case that when this was done it was not re-based to include that PR.

**Comment by th0ma7** [comment]
I think you're right @hgy59.  Looking at the code the `publish` standalone call does not preclude calling building.

This either requires changes in mk or in `build.sh` we do first a build then publish:
```
make TCVERSION=${TCVERSION} ARCH= -C ./spk/${package}
make TCVERSION=${TCVERSION} ARCH= -C ./spk/${package} ${MAKE_ARGS%%-}
```

**Comment by th0ma7** [comment]
@mreid-tt  can you rebase against master and confirm if this is working out as expected https://github.com/SynoCommunity/spksrc/pull/6134 ?

**Comment by mreid-tt** [comment]
> @mreid-tt can you rebase against master and confirm if this is working out as expected #6134 ?

Yes it did. Thanks @th0ma7

**Comment by th0ma7** [comment]
Great!  Thnx for confirming, cheers!

**Pull request merged**
