### PR TITLE
BicBucStriim: Update to v3.5.2

### LINKED ISSUE #6289: [Package Update] BicBucStriim to 3.5.2
### Software Name

BicBucStriim

### Brief Description

Requesting BicBucStriim package update from 3.4.2 to 3.5.2

I'd be happy to help with testing.

Thanks!

### Website

https://github.com/mikespub-org/rvolz-BicBucStriim

### Documentation

_No response_

### Build/Installation documentation

https://github.com/mikespub-org/rvolz-BicBucStriim/releases/tag/v3.5.2

### Source code

https://github.com/mikespub-org/rvolz-BicBucStriim/tree/main

### OpenSource License

MIT

### Other License

_No response_

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This PR includes the update of BicBucStriim to v3.5.2.

Fixes #6289

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by mreid-tt** [comment]
@Borogroves you can go ahead and test this build and let me know if there are any issues.

**Comment by Borogroves** [comment]
@mreid-tt the new package works great, thanks for the update!

**Comment by sohanev** [comment]
Hi, When a book has no publication date, it displays the value (0101)

I would suggest this solution
title_entry
`{% if book.pubdate|date("Y") != "0101" %}
		<h3>
			{% if series %}{{book.series_index}} - {% endif %}
			{{ book.sort }} ({{ book.pubdate|date("Y") }})
		</h3>
		{% else %}
		<h3>
			{% if series %}{{book.series_index}} - {% endif %}
			{{ book.sort }}
		</h3>
		{% endif %}`
title_detail
`{% if book.pubdate|date("Y") != "0101" %}
			<p>					
				{{ book.pubdate | date("Y") }}	{{ language }}
			</p>
			{% else %}
			<p>					
				{{ language }}
			</p>
			{% endif %}`

I can't find how to do this on the main page. But I think you could)

**Comment by mreid-tt** [comment]
> Hi, when a book has no publication date, it displays the value (0101)
> 
> default template
> 
> I would suggest this solution

I would suggest that you propose this solution in the upstream repo so it can be included in the codebase: https://github.com/mikespub-org/rvolz-BicBucStriim/issues

**Pull request merged**
