### PR TITLE
ffmpeg 6.0.1 and tvheadend 4.3~366e562 update

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

ffmpeg 6.1 update

Follow-up to https://github.com/SynoCommunity/spksrc/pull/6118#issuecomment-2170428183
Fixes https://github.com/SynoCommunity/spksrc/issues/5729

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
just found that it does not download packages for ffmpeg6 in prepare job

```
   ===> Found: chromaprint  comskip  ffmpeg  ffmpeg5  ffmpeg6  imagemagick  tvheadend  
===> PACKAGES to download references for: ffmpeg5 ffmpeg4  chromaprint comskip imagemagick tvheadend   
```

will look at it... (may be in #6144)

**Comment by hgy59** [comment]
> just found that it does not download packages for ffmpeg6 in prepare job
> 
> ```
>    ===> Found: chromaprint  comskip  ffmpeg  ffmpeg5  ffmpeg6  imagemagick  tvheadend  
> ===> PACKAGES to download references for: ffmpeg5 ffmpeg4  chromaprint comskip imagemagick tvheadend   
> ```
> 
> will look at it... (may be in #6144)

fixed in ac435b09401925cda468a8e1232b95e2bc614f00

_in prepare.sh: when renaming ffmpeg to ffmpeg4 all already found ffmpeg* entries were deleted.
Only the ffmpeg versions that other packages depend on were added after this. Since currently no package depends on ffmpeg6 it was removed from the list..._

**Comment by hgy59** [comment]
@th0ma7 friendly reminder of #5729

**Comment by th0ma7** [comment]
>  friendly reminder of #5729

now fixed.

**Comment by hgy59** [comment]
> @hgy59 Where's that fix located? Can't find it anywhere...

see ac435b09401925cda468a8e1232b95e2bc614f00

**Comment by hgy59** [comment]
> > @hgy59 Where's that fix located? Can't find it anywhere...
> 
> see [ac435b0](https://github.com/SynoCommunity/spksrc/commit/ac435b09401925cda468a8e1232b95e2bc614f00)

And you need this, currently ffmpeg5 is not built for your PR.
_since tvheadend depends on ffmpeg6 now, there is no package depending on ffmpeg5, and ffmpeg5 will be removed from packages to build without the fix_

**Comment by th0ma7** [comment]
> > > @hgy59 Where's that fix located? Can't find it anywhere...
> > 
> > see [ac435b0](https://github.com/SynoCommunity/spksrc/commit/ac435b09401925cda468a8e1232b95e2bc614f00)
> 
> And you need this, currently ffmpeg5 is not built for your PR.
> _since tvheadend depends on ffmpeg6 now, there is no package depending on ffmpeg5, and ffmpeg5 will be removed from packages to build without the fix_
> 

And rebasing will suffice right?

**Comment by hgy59** [comment]
> And rebasing will suffice right?

yep..

**Comment by th0ma7** [comment]
@hgy59 in theory this should all build successfully (although this is soooo big that there is always a surprise somewhere).  Would you mind having a quick review as I may have overseen something.

Optional TODO: enable opencl on ffmpeg6 https://github.com/SynoCommunity/spksrc/pull/5620#issuecomment-1455047560

**Comment by hgy59** [comment]
@th0ma7 for ffmpeg5 the patches 2001-*, 2002-*, 2003-*, 2004-*, 2006-*, and 2007-* fail.

**Comment by th0ma7** [comment]
> @th0ma7 for ffmpeg5 the patches 2001-_, 2002-_, 2003-_, 2004-_, 2006-_, and 2007-_ fail.

weird, I had tested them locally yesterday... oh well.

**Comment by hgy59** [comment]
as mentioned in https://github.com/SynoCommunity/spksrc/pull/6118#issuecomment-2155303833 the `cross/intel-vaapi-driver` fails to bild with x64-7.2 toolchain.

@th0ma7 do you have a free cycle to look at it?

```
===>  Patching for intel-vaapi-driver
===>  Configuring for intel-vaapi-driver
===>  - Configure ARGS: --host=x86_64-pc-linux-gnu --build=i686-pc-linux --prefix=/var/packages/ffmpeg6/target --localstatedir=/var/packages/ffmpeg6/var
===>  - Install prefix: /var/packages/ffmpeg6/target
cd /spksrc/spk/ffmpeg6/work-x64-7.2/intel-vaapi-driver-2.4.1 && env PKG_CONFIG_LIBDIR=/spksrc/spk/ffmpeg6/work-x64-7.2/install//var/packages/ffmpeg6/target/lib/pkgconfig WORK_DIR=/spksrc/spk/ffmpeg6/work-x64-7.2 INSTALL_PREFIX=/var/packages/ffmpeg6/target TC_WORK_DIR=/spksrc/toolchain/syno-x64-7.2/work TC=syno-x64-7.2 SYSROOT="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root" LD="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld" LDSHARED="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc -shared" CPP="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-cpp" NM="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-nm" CC="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc" AS="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-as" RANLIB="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib" CXX="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-g++" AR="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ar" STRIP="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-strip" OBJDUMP="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-objdump" OBJCOPY="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-objcopy" READELF="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-readelf" CFLAGS="-I/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include -I/spksrc/spk/ffmpeg6/work-x64-7.2/install/var/packages/ffmpeg6/target/include " CPPFLAGS="-I/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include -I/spksrc/spk/ffmpeg6/work-x64-7.2/install/var/packages/ffmpeg6/target/include " CXXFLAGS="-I/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include -I/spksrc/spk/ffmpeg6/work-x64-7.2/install/var/packages/ffmpeg6/target/include " LDFLAGS="-L/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/lib -L/spksrc/spk/ffmpeg6/work-x64-7.2/install/var/packages/ffmpeg6/target/lib -Wl,--rpath-link,/spksrc/spk/ffmpeg6/work-x64-7.2/install/var/packages/ffmpeg6/target/lib -Wl,--rpath,/var/packages/ffmpeg6/target/lib " CARGO_HOME="/spksrc/distrib/cargo" RUSTUP_HOME="/spksrc/distrib/rustup" RUSTUP_TOOLCHAIN="stable" CARGO_BUILD_TARGET="x86_64-unknown-linux-gnu" CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_AR="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ar" CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc" CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS=" " TC_GCC=$(eval $(echo /spksrc/spk/ffmpeg6/work-x64-7.2/../../../toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc -dumpversion) 2>/dev/null || true) TC_GLIBC=2.36 TC_KERNEL=4.4.302+ LIBVA_DRIVERS_PATH=/var/packages/ffmpeg6/target/lib ./autogen.sh
ln: failed to create symbolic link '.git/hooks/pre-commit': No such file or directory
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal 
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
configure.ac:71: installing './compile'
configure.ac:71: installing './config.guess'
configure.ac:71: installing './config.sub'
configure.ac:29: installing './install-sh'
configure.ac:29: installing './missing'
src/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... /spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/spksrc/spk/ffmpeg6/work-x64-7.2/intel-vaapi-driver-2.4.1':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
make[4]: *** [Makefile:26: intel_vaapi_driver_configure] Error 1
make[4]: Leaving directory '/spksrc/cross/intel-vaapi-driver'
make[3]: *** [../../mk/spksrc.depend.mk:54: depend_target] Error 2
make[3]: Leaving directory '/spksrc/cross/ffmpeg6'
make[2]: *** [../../mk/spksrc.depend.mk:54: depend_target] Error 2
make[2]: Leaving directory '/spksrc/spk/ffmpeg6'
make[1]: Leaving directory '/spksrc/spk/ffmpeg6'
```

**Comment by th0ma7** [comment]
> as mentioned in https://github.com/SynoCommunity/spksrc/pull/6118#issuecomment-2155303833 the `cross/intel-vaapi-driver` fails to bild with x64-7.2 toolchain.
> 
> @th0ma7 do you have a free cycle to look at it?
> 
> ```
> ===>  Patching for intel-vaapi-driver
> ===>  Configuring for intel-vaapi-driver
> ===>  - Configure ARGS: --host=x86_64-pc-linux-gnu --build=i686-pc-linux --prefix=/var/packages/ffmpeg6/target --localstatedir=/var/packages/ffmpeg6/var
> ===>  - Install prefix: /var/packages/ffmpeg6/target
> cd /spksrc/spk/ffmpeg6/work-x64-7.2/intel-vaapi-driver-2.4.1 && env PKG_CONFIG_LIBDIR=/spksrc/spk/ffmpeg6/work-x64-7.2/install//var/packages/ffmpeg6/target/lib/pkgconfig WORK_DIR=/spksrc/spk/ffmpeg6/work-x64-7.2 INSTALL_PREFIX=/var/packages/ffmpeg6/target TC_WORK_DIR=/spksrc/toolchain/syno-x64-7.2/work TC=syno-x64-7.2 SYSROOT="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root" LD="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld" LDSHARED="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc -shared" CPP="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-cpp" NM="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-nm" CC="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc" AS="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-as" RANLIB="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib" CXX="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-g++" AR="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ar" STRIP="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-strip" OBJDUMP="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-objdump" OBJCOPY="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-objcopy" READELF="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-readelf" CFLAGS="-I/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include -I/spksrc/spk/ffmpeg6/work-x64-7.2/install/var/packages/ffmpeg6/target/include " CPPFLAGS="-I/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include -I/spksrc/spk/ffmpeg6/work-x64-7.2/install/var/packages/ffmpeg6/target/include " CXXFLAGS="-I/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include -I/spksrc/spk/ffmpeg6/work-x64-7.2/install/var/packages/ffmpeg6/target/include " LDFLAGS="-L/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/lib -L/spksrc/spk/ffmpeg6/work-x64-7.2/install/var/packages/ffmpeg6/target/lib -Wl,--rpath-link,/spksrc/spk/ffmpeg6/work-x64-7.2/install/var/packages/ffmpeg6/target/lib -Wl,--rpath,/var/packages/ffmpeg6/target/lib " CARGO_HOME="/spksrc/distrib/cargo" RUSTUP_HOME="/spksrc/distrib/rustup" RUSTUP_TOOLCHAIN="stable" CARGO_BUILD_TARGET="x86_64-unknown-linux-gnu" CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_AR="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ar" CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER="/spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc" CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS=" " TC_GCC=$(eval $(echo /spksrc/spk/ffmpeg6/work-x64-7.2/../../../toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc -dumpversion) 2>/dev/null || true) TC_GLIBC=2.36 TC_KERNEL=4.4.302+ LIBVA_DRIVERS_PATH=/var/packages/ffmpeg6/target/lib ./autogen.sh
> ln: failed to create symbolic link '.git/hooks/pre-commit': No such file or directory
> autoreconf: Entering directory `.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal 
> autoreconf: configure.ac: tracing
> autoreconf: running: libtoolize --copy
> libtoolize: putting auxiliary files in '.'.
> libtoolize: copying file './ltmain.sh'
> libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
> libtoolize: and rerunning libtoolize and aclocal.
> libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
> autoreconf: running: /usr/bin/autoconf
> autoreconf: running: /usr/bin/autoheader
> autoreconf: running: automake --add-missing --copy --no-force
> configure.ac:71: installing './compile'
> configure.ac:71: installing './config.guess'
> configure.ac:71: installing './config.sub'
> configure.ac:29: installing './install-sh'
> configure.ac:29: installing './missing'
> src/Makefile.am: installing './depcomp'
> autoreconf: Leaving directory `.'
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether UID '1000' is supported by ustar format... yes
> checking whether GID '1000' is supported by ustar format... yes
> checking how to create a ustar tar archive... gnutar
> checking whether make supports nested variables... (cached) yes
> checking build system type... x86_64-pc-linux-gnu
> checking host system type... x86_64-pc-linux-gnu
> checking how to print strings... printf
> checking whether make supports the include directive... yes (GNU style)
> checking for gcc... /spksrc/toolchain/syno-x64-7.2/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... configure: error: in `/spksrc/spk/ffmpeg6/work-x64-7.2/intel-vaapi-driver-2.4.1':
> configure: error: cannot run C compiled programs.
> If you meant to cross compile, use `--host'.
> See `config.log' for more details
> make[4]: *** [Makefile:26: intel_vaapi_driver_configure] Error 1
> make[4]: Leaving directory '/spksrc/cross/intel-vaapi-driver'
> make[3]: *** [../../mk/spksrc.depend.mk:54: depend_target] Error 2
> make[3]: Leaving directory '/spksrc/cross/ffmpeg6'
> make[2]: *** [../../mk/spksrc.depend.mk:54: depend_target] Error 2
> make[2]: Leaving directory '/spksrc/spk/ffmpeg6'
> make[1]: Leaving directory '/spksrc/spk/ffmpeg6'
> ```
> 

Was working all right during my testing.  And besides missing updated patches relatively to svtav1 for ffmpeg5, vaapi is in all ffmpeg builds.  But I'll double check and confirm.

**Comment by hgy59** [comment]
> Was working all right during my testing. And besides missing updated patches relatively to svtav1 for ffmpeg5, vaapi is in all ffmpeg builds. But I'll double check and confirm.

intel-vaapi-driver fails for all DSM-7.2. archs (x64, aarch64, armv7).
BUT when using meson build, it succeeds for x64-7.2 (aarch64 and armv7 fail with `"meson.build:29:19: ERROR: Dependency "libdrm_intel" not found, tried pkgconfig"`)

Anyway, it might be a cross compile issue, since it fails while `checking whether we are cross compiling... configure: ...`

**Comment by th0ma7** [comment]
> > Was working all right during my testing. And besides missing updated patches relatively to svtav1 for ffmpeg5, vaapi is in all ffmpeg builds. But I'll double check and confirm.
> 
> intel-vaapi-driver fails for all DSM-7.2. archs (x64, aarch64, armv7).
> BUT when using meson build, it succeeds for x64-7.2 (aarch64 and armv7 fail with `"meson.build:29:19: ERROR: Dependency "libdrm_intel" not found, tried pkgconfig"`)
> 
> Anyway, it might be a cross compile issue, since it fails while `checking whether we are cross compiling... configure: ...`
> 
> 

Will check but anyway this really is only needed for x64 as i doubt we'll see a arm based with intel gpu nas shortly.  And this should use meson when ever available instead of plain cmake, usually is more reliable.

**Comment by th0ma7** [comment]
@zyrill I wonder if you would be able to give this build a shot?   I've migrated `tvheadend` to depends on `ffmpeg6` which I also migrated to using newer intel VPL API instead of legacy MFX (but only for for ffmpeg6, leaving older versions unchanged).

Build artifacts from latest run are available here: https://github.com/SynoCommunity/spksrc/actions/runs/9587187128

As for the vaapi driver issue, I wasn't able to reproduce it.

**Comment by zyrill** [comment]
Hey @th0ma7 ! Only saw the comment now, apologies. I'm currently only intermittently available due to medical issues. Anyways, appreciate your work, thanks a lot!

**Pull request merged**
