### PR TITLE
Correct logging redirection

### PR DESCRIPTION
**Pull request by Safihre**
Due to #3138 I noticed not all packages have correct `LOG_FILE` set and as such users can't get the log from Package Center.
@ymartin59 This includes Transmission, maybe this can go in before you publish?

### CODE REVIEW

**Comment by Teryon** [comment]
NZBGET Logs in packages center crash DSM

**Comment by Safihre** [comment]
I added new code that will only show the last 100 lines in Package Center and the path to the full log. 
This makes more sense, as the main purpose is to identify start-up problems and not really to track full program-functioning.
What do you think @ymartin59 ?

**Comment by Teryon** [comment]
@Safihre When I click to show the log, it shows 'loading" nothing happens and it get stuck and sometime DSM reload itself.

**Comment by ymartin59** [comment]
As it is difficult to tune log verbosity for each application, I agree your code is a relevant work-around. And full log remains available too. Does Synology has documented some restriction about this package log file volume ?

**Pull request merged**
