### PR TITLE
Initial logstash package build in spksrc

### PR DESCRIPTION
**Pull request by AustinSaintAubin**
Logstash Package created in spksrc for the SynoCommunity.

### CODE REVIEW

**Comment by AustinSaintAubin** [comment]
So what is the next step?

**Comment by AustinSaintAubin** [comment]
So its been over a month sense this was last worked on, what now?
Is this ready for you to pull into the main repository?

**Comment by Diaoul** [comment]
I'll make a full review when the server will be restored, few things after a quick look:

* The start and install scripts are really big :(
* Is config consistent after package update?
* Maintainer should be SynoCommunity
* I don't think copyright stuff is necessary as spksrc is under 3-clause BSD license
* Setting up shares should be done by the user, I'm don't think any package should create or modify shares. Then user specify the share to use in the wizard (or config file). ACL manipulations make scripts awefully complex. I've challenged Synology about dedicated applications users months ago, I'll try to get some updates from them

Sorry for the little time available.

**Comment by kyub** [comment]
Any updates on this guys?

**Comment by AustinSaintAubin** [comment]
Not yet. I need to make minor changes. But that package seems stable and could be a first release candidate.

-- Austin St. Aubin

**Comment by AustinSaintAubin** [comment]
Found this Logstash package for Docker: https://registry.hub.docker.com/u/pblittle/docker-logstash/
This seems like a better option than trying to maintain a Logstash package for Synology.

**Comment by Diaoul** [comment]
It won't be available for ARM NASes with Docker. Please reopen the PR against master branch.

**Comment by rndmzed0815** [comment]
any news on this one? desperately waiting for a release :)

**Comment by AustinSaintAubin** [comment]
I will be working on it this week if I have time. 
I hope to test the package against DSM 5.2 before longs and make the suggested changes posted by @Diaoul

**Comment by rndmzed0815** [comment]
@AustinSaintAubin have you had the chance to continue working on the package?

**Pull request closed without merging**
