### PR TITLE
Fix file permissions

### PR DESCRIPTION
**Pull request by nliaudat**
File must have read/write access for everybody

### CODE REVIEW

**Comment by Dr-Bean** [comment]
Personally, I'd prefer to not merge this, for two reasons: I like the default permissions just fine, because that means I can override them as I wish. 
Secondly, this package will no longer be updated: 1.4.111 is the last package of the line, because Bittorrent is maintaining their own set of packages for 2.0 forwards.

Can you explain why this would be a good thing to implement for all package users, instead of just locally for yourself?

**Comment by nliaudat** [comment]
Hi, 
btsync sets it's permission through the custom user btsync, which is not linked to the synology users/groups. 

I mean the only way to sync the content of two or more synology nas with btsync is to set file permissions with umask as proposed.

Btsync is not only for home users, but can be used in a complex topology with more than one server and clients. 

The file access must be done with the common synology user/group (perhaps linked with AD /LDAP) interface and not be restricted with a shadow user (btsync in that case). 

Regards
Nicooas

**Comment by Dr-Bean** [comment]
The `btsync` user is member of Synology's `users` group, same as for all our packages. Synology uses ACL (Access Control Lists) internally, not Unix permissions.

**Comment by Dr-Bean** [comment]
Closing this PR: BTSync package will be removed from spksrc. See e.g. https://github.com/SynoCommunity/spksrc/issues/1492#issuecomment-112913138.

**Pull request closed without merging**
