### PR TITLE
bump git version to 1.8.5.2 to match current Apple

### PR DESCRIPTION
**Pull request by chickenandpork**
Apple current Xcode (pre WWDC) includes git-1.8.5.2; To avoid incompatibility issues, I tested a simple version-bump to a matching version.  Builds fine as arch-ppc853x for x09+ series PPC.

I chose to match Apple for both personal gain and for "there is a large company that redistributes a specific version that a number of users would use".

Also, a spelling typo was fixed; kick me if you want that split out

### CODE REVIEW

**Comment by chickenandpork** [comment]
was it ever pulled?

**Comment by Dr-Bean** [comment]
No, it was not, but that's not your fault. The PR was closed automatically because of the develop branch was renamed to master; you'll have to rebase your code against master and create a new PR. 

By the way, #1472 updates Git to the latest available version. Feel free to incorporate that in a new PR if you're still up for it, otherwise I'll create a new PR based off of that one when I get to it.

**Comment by chickenandpork** [comment]
Heya;

New job, new baby.  Dev env is toast...  Might have time next week but it would be a stretch.  You might get to it before me.  If I can resurrect my dev env, I'll make a noise to avoid us both doing it.

Thanks :)

Allan

**Comment by Dr-Bean** [comment]
@chickenandpork As an FYI, Git has been updated with https://github.com/SynoCommunity/spksrc/commit/fb11046731c0f1fb223ceaa865a17cc0c08ca640 (not published yet though). 
Note that Git-server has not been updated: I'll leave that to someone who uses it and can verify it works.

**Pull request closed without merging**
