### PR TITLE
ffmpeg extras

### LINKED ISSUE #5254: tvheadend cannot find libatomic
### Is this a new Bug?

- [X] I checkd that the bug hasn't been reported before

### Package Name

tvheadend

### Package Version

4.3.20220414-32

### Device Model

DS213+

### Device Architecture

PPC

### Firmware Version

DSM-6.2.4-25556 Update 5

### What happened?

After updating from previous version (4.3.20211121-31) tvheadend does not start anymore because it cannot find libatomic.so (see service log below). If I check installed libraries on the root file system there is only libatomic_ops:

```
ls -l /usr/lib/libatomic_ops*
lrwxrwxrwx 1 root root   26 Jul  2  2021 /usr/lib/libatomic_ops_gpl.so -> libatomic_ops_gpl.so.1.0.3
lrwxrwxrwx 1 root root   26 Jul  2  2021 /usr/lib/libatomic_ops_gpl.so.1 -> libatomic_ops_gpl.so.1.0.3
-rwxr-xr-x 1 root root 9492 Feb  1  2021 /usr/lib/libatomic_ops_gpl.so.1.0.3
lrwxrwxrwx 1 root root   22 Jul  2  2021 /usr/lib/libatomic_ops.so -> libatomic_ops.so.1.0.3
lrwxrwxrwx 1 root root   22 Jul  2  2021 /usr/lib/libatomic_ops.so.1 -> libatomic_ops.so.1.0.3
-rwxr-xr-x 1 root root 5348 Feb  1  2021 /usr/lib/libatomic_ops.so.1.0.3
```

### Reproduction steps

```bash
1. Update to 4.3.20220414-32
2. Autostart on boot or try to manually start tvheadend in DSM
3. Failure message in DSM, log entry missing libatomic.so
```

### Install Log

```log
Sat Aug 22 18:25:13 CEST 2020
===> Step preupgrade. USER=tvheadend GROUP=sc-media SHARE_PATH=
Invoke service_preupgrade
Save potential recordings from package root directory...
Move any recording directories from package root directory into var...
Sat Aug 22 18:26:10 CEST 2020
===> Step preuninst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Sat Aug 22 18:26:14 CEST 2020
===> Step postuninst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Sat Aug 22 18:26:15 CEST 2020
===> Step preinst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Sat Aug 22 18:26:17 CEST 2020
===> Step postinst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Installing service configuration /var/packages/tvheadend/conf/tvheadend.sc
Invoke service_postinst
Fixing fontconfig links
Granting 'sc-tvheadend' unix ownership on /volume1/@appstore/tvheadend/var
Sat Aug 22 18:26:20 CEST 2020
===> Step postupgrade. USER=tvheadend GROUP=sc-media SHARE_PATH=
Granting 'sc-tvheadend' unix ownership on /volume1/@appstore/tvheadend/var
Invoke service_postupgrade
Adding sc-media group permissions on recording directories:
Done: /volume1/data/tv
Granting 'sc-tvheadend' unix ownership on /volume1/data/tv
(synoacltool.c, 140)It's Linux mode
Granting 'sc-media' group permissions on /volume1/data/tv
(synoacltool.c, 140)It's Linux mode
(synoacltool.c, 140)It's Linux mode
Granting 'sc-media' group basic permissions on /volume1/data/tv
(synoacltool.c, 140)It's Linux mode
Restore 'sc-tvheadend' unix permissions on package system directories
Granting 'sc-tvheadend' unix ownership on /volume1/@appstore/tvheadend/var
Fri Nov 13 11:01:03 CET 2020
===> Step preupgrade. USER=tvheadend GROUP=sc-media SHARE_PATH=
Invoke service_preupgrade
Save potential recordings from package root directory...
Move any recording directories from package root directory into var...
Fri Nov 13 11:01:23 CET 2020
===> Step preuninst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Fri Nov 13 11:01:24 CET 2020
===> Step postuninst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Fri Nov 13 11:01:24 CET 2020
===> Step preinst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Fri Nov 13 11:01:25 CET 2020
===> Step postinst. USER=tvheadend GROUP=sc-media SHARE_PATH=
Installing service configuration /var/packages/tvheadend/conf/tvheadend.sc
Invoke service_postinst
Fixing fontconfig links
Granting 'sc-tvheadend' unix ownership on /volume1/@appstore/tvheadend/var
Fri Nov 13 11:01:26 CET 2020
===> Step postupgrade. USER=tvheadend GROUP=sc-media SHARE_PATH=
Granting 'sc-tvheadend' unix ownership on /volume1/@appstore/tvheadend/var
Invoke service_postupgrade
Adding sc-media group permissions on recording directories:
Done: /volume1/data/tv
Granting 'sc-tvheadend' unix ownership on /volume1/data/tv
(synoacltool.c, 140)It's Linux mode
Granting 'sc-media' group permissions on /volume1/data/tv
(synoacltool.c, 140)It's Linux mode
(synoacltool.c, 140)It's Linux mode
Granting 'sc-media' group basic permissions on /volume1/data/tv
(synoacltool.c, 140)It's Linux mode
Restore 'sc-tvheadend' unix permissions on package system directories
Granting 'sc-tvheadend' unix ownership on /volume1/@appstore/tvheadend/var
```

### Service Log

```log
Fri May  6 23:15:45 CEST 2022
Starting tvheadend command tvheadend -f -C -u sc-tvheadend -g tvheadend --http_port 9981 --htsp_port 9982 -c /volume1/@appstore/tvheadend/var -p /volume1/@appstore/tvheadend/var/tvheadend.pid -l /volume1/@appstore/tvheadend/var/tvheadend.log --debug ""
tvheadend: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```

### Other Logs

```log
2022/05/06 23:15:44     start tvheadend: begin to start version 4.3.20220414-32
2022/05/06 23:15:45     start tvheadend 4.3.20220414-32 Begin start-stop-status start
2022/05/06 23:16:05     start tvheadend 4.3.20220414-32 End start-stop-status start ret=[1]
2022/05/06 23:16:06     (system) trigger tvheadend 4.3.20220414-32 Begin start-stop-status stop
2022/05/06 23:16:06     (system) trigger tvheadend 4.3.20220414-32 End start-stop-status stop ret=[0]
2022/05/06 23:16:06     stop tvheadend: begin to stop version 4.3.20220414-32
2022/05/06 23:16:06     stop tvheadend: stop version 4.3.20220414-32 successfully, result 0
2022/05/06 23:16:06     start tvheadend: start version 4.3.20220414-32 failed, result 272
```

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

ffmpeg extras: Add extra version tag to easily identify running version along with encoders/decoders to ffmpeg

Includes a generic fix for packages that link to libatomic and must include this library from the toolchain in the package.

Fixes #5254

## Checklist

- [x] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [x] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
Issue found while trying to integrate `codec2` https://github.com/drowe67/codec2/issues/324

**Comment by hgy59** [comment]
@th0ma7 just identified redis package build for qoriq needs libatomic too.
But staging/lib folder does not exist here at time of libatomic installation.

**Comment by hgy59** [comment]
@th0ma7 thanks for triggering the failed (tvh timeouted) builds again.

**Comment by th0ma7** [comment]
> @th0ma7 just identified redis package build for qoriq needs libatomic too. But staging/lib folder does not exist here at time of libatomic installation.

Good catch!  We'll eventually get it right ;)  I've restarted failed jobs to confirm all is good then I'll merge.

**Comment by hgy59** [comment]
> we now have a good work-around for it!

Shame on synology, to have shared libraries in toolchains, that are not available on the devices.

**Review by hgy59 — APPROVED** [review]

**Pull request merged**
