### PR TITLE
Updated sabnzbd-testing to version 1.0.0

### PR DESCRIPTION
**Pull request by mhartvig**
Build-ed with all-supported.
Test upgraded from current version in channel to this without issues

Should beta be set to 0 or 1, since this is the beta channel?

### CODE REVIEW

**Comment by Dr-Bean** [comment]
All `-testing` packages should set `BETA = 1`, those packages will never move to stable.
 Other than that, LGTM.

**Comment by mhartvig** [comment]
Changed the makefile to have beta = 1.

**Comment by Dr-Bean** [comment]
Thanks for confirming that updating works, should be good to go.

**Comment by Safihre** [comment]
I don't have strong understanding how these packages are installed, but it seems to also be possible to compile stuff on installation?
Because CPU load and thus performance can be greatly increased if the C-version of yEnc decoder is installed.
There is a Python package that provides this on pip: https://pypi.python.org/pypi/yenc
But it needs to be (pre)compiled and then placed in the SABnzbd folder so it can be used.
Would this be possible?

**Comment by mhartvig** [comment]
I too isn't to familiar with how it's done, but it seems like it is possible to install yEnc. It's already located in https://github.com/SynoCommunity/spksrc/tree/master/cross/yenc. What folder does it have to be located in @Safihre?

**Comment by Safihre** [comment]
Aah interesting, seems somebody already took care of this!
You can see if SABnzbd can use it (after installing that package) by going into the Config in 1.0.0, on the first page you see yEnc and it should have a checkmark next to it.

**Comment by cytec** [comment]
i think inlcuding yEnc should be possible by adding it to depends

**Comment by mhartvig** [comment]
Without doing anything:
yenc
It might have been installed by some other package.

**Comment by Safihre** [comment]
Hahah, you just beat me to the punch ;-) 
Indeed already installed, that's great so this is looking good!

**Comment by cytec** [comment]
@SynoCommunity/developers i'm currently building those packages for `all-supported`

**Comment by cytec** [comment]
packages are up @Dr-Bean can you compile one for `armada38x` seems like i need to migrate to a 64bit machine to build with that toolchain :/

**Comment by Dr-Bean** [comment]
Done. Probably a good idea to remove older versions from the repo (keep `n` and `n-1`, remove the rest)

**Comment by cytec** [comment]
yeah... i've disabled everything below `0.8.0Beta5` for now.

**Pull request merged**
