### PR TITLE
Boost: Upgrade to 1.76

### PR DESCRIPTION
**Pull request by ohnoohweh**
Upgraded to Boost 1.76
Files from issue #4746

Motivation: Some programs require Boost 1.76. DSM7 comes with 1.68. SpkSrc has a repository for 1.66
Linked issues: SynoCommunity#4746

### Warning ####
I update the boost package to 1.76. However the programs using the boost lib may not compatible with this newer version

### Checklist
- [ ] Build rule `all-supported` completed successfully
make all-supported does not work on cross/boost
```
make all-supported
make: *** No rule to make target 'all-supported'.  Stop.

```

`make all-archs`

Seems like endless variants:

Ok means that libs are created. Compiling does not stop due to error.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
</head>

<body>

Arch/Version | 4.3 | 5.0 | 5.1 | 5.2 | 6.0.2 | 6.1 | 6.2 | 6.2.2 | 6.2.3 | 6.2.4 | 7.0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
88f6281 | nok | ok | ok | ok | ok | ok | ok | ok | ok | ok | '-
aarch64 | '- | '- | '- | '- | '- | ok | ok | ok | ok | ok | ok
alpine | '- | '- | ok | ok | ok | ok | ok | ok | ok | ok | ok
apollolake | '- | '- | '- | '- | '- | ok | ok | ok | ok | ok | ok
armada370 |   |   |   |   |   |   |   |   |   |   |  
armada375 | '- | '- |   |   |   |   |   |   |   |   |  
armada37xx | '- | '- | '- | '- | '- | '- | '- |   |   |   |  
armada38x | '- | '- | '- |   |   | ok |   |   |   | ok  | ok 
armadaxp |   |   |   |   |   |   |   |   |   |   |  
armv7 | '- | '- | '- |   | '- |   |   |   |   |   | ok  
avoton | '- |   |   |   |   |   |   |   |   |   |  
braswell | '- | '- | '- |   |   |   |   |   |   |   |  
broadwell | '- | '- | '- | '- |   |   |   |   |   |   |  
broadwellnk | '- | '- | '- | '- | '- | '- |   |   |   |   |  
bromolow |   |   |   |   |   |   |   |   |   |   |  
cedarview |   |   |   |   |   |   |   |   |   |   |  
comcerto2k | '- |   |   |   |   |   |   |   |   |   |  
dakota | '- | '- | '- | '- | '- | '- | '- | '- | '- | '- | '-
denverton | '- | '- | '- | '- | '- |   |   |   |   |   | ok  
dockerx64 | '- | '- | '- | '- | '- |   |   |   |   |   | '- 
evansport | '- |   |   |   |   |   |   |   |   |   | ok 
geminilake | '- | '- | '- | '- | '- | '- | '- |   |   |   |ok  
grantly | '- | '- | '- | '- |   |   |   |   |   |   | ok 
hi3535 | '- | '- | '- | '- | '- |   |   |   |   |   | '-
ipq806x | '- | '- | '- | '- | '- | '- | '- | '- | '- | '- | '-
kvmx86 | '- | '- | '- | '- | '- |   |   |   |   |   | ok 
monaco | '- | '- | '- |   |   |   |   |   |   |   | ok 
nothstarplus | '- | '- | '- | '- | '- | '- | '- | '- | '- | '- | '-
powerpc | '- | '- | '- | '- | '- | '- | '- | '- | '- | '- | '-
ppc824x | '- | '- | '- | '- | '- | '- | '- | '- | '- | '- | '-
ppc853x |   |   |   |   | '- | '- | '- | '- | '- | '- | '-
ppc854x | '- | '- | '- | '- | '- | '- | '- | '- | '- | '- | '-
purley | '- | '- | '- | '- | '- | '- | '- |   |   |   |  ok
qoriq |   |   |   |   |   |   |   |   |   |   | '-
rtd1296 | '- | '- | '- | '- | '- |   |   |   |   |   |  ok
v1000 | '- | '- | '- | '- | '- | '- | '- | '- |   |   | ok  
x64 |   |   |   |   |   |   |   |   |   |   | ok 
x86 |   |   |   |   |   |   |   |   |   |   | '-

</body>

</html>

- [ ] Package upgrade completed successfully

Sorry, don't understand what is required.

- [ ] New installation of package completed successfully

I created a package that uses Boost-1.76 and was able to install it on a DSM918+ (apollolake DSM 7.0)

### CODE REVIEW

**Comment by publicarray** [comment]
Impressive testing you have done. We are only interested with 6.1 and 7.0 at the moment. Did you test a dependent package such as `cross/mkvtoolnix` `cross/libtorrent` or `cross/domoticz`? According to the CI they fail to build.

**Comment by publicarray** [comment]
IMHO it's more important to get a working package out of this (`spk/mkvtoolnix`, `spk/deluge`,  `spk/rutorrent` and `spk/domoticz`) than updating dependencies that break other packages.

**Comment by ohnoohweh** [comment]
Well. I totally agree - what kind of benefit does a newer version bring in case the dependent packages are breaking ?

I am using Boost for my own package as it is requiring the newer version. Is it possible to have two versions of boost in the repository ?

**Comment by hgy59** [comment]
> Well. I totally agree - what kind of benefit does a newer version bring in case the dependent packages are breaking ?
> 
> I am using Boost for my own package as it is requiring the newer version. Is it possible to have two versions of boost in the repository ?

@ohnoohweh PR  #5187 answers some of your questions.
- cross/boost is now version 1.78.0
- cross/boost_1.68 is provided for domoticz 2020.2
- cross/boost_1.70 is for mkvtoolnix v22.0
- Those dedicated versions are needed to avoid breaking existing packages (mkvtoolnix 53.0 builds with boost 1.78, but needs at least DSM 7)

_@ohnoohweh probably this PR is obsolete now_

**Comment by hgy59** [comment]
for different situations we now have several boost versions implemented with #5187 a73ee99087efe492844c9683a19d87db9a2e2f2e
- cross/boost_1.68
- cross/boost_1.70
- cross/boost_1.78
- cross/boost (currently version 1.78)

**Pull request closed without merging**
