### PR TITLE
Update to flac 1.3.1

### PR DESCRIPTION
**Pull request by vkostas**
Set new download link.
Fix config file to avoid error (as per gihub flac).

### CODE REVIEW

**Comment by Dr-Bean** [comment]
This should be part of a larger PR, instead of on its own. Are you working on mpd? Maybe you can include it as part of that PR.

If you do, please add digests (`make digests`), update the PLIST, and minimize the patch size (don't comment out, just remove)

**Comment by vkostas** [comment]
Yes, I am working on mpd.
I will include icecast to mpd PR then.
Thx

**Comment by Dr-Bean** [comment]
`flac`, right? ;) Besides that typo, you might want to check that PPC arches actually compile with flac. They probably won't.

**Comment by vkostas** [comment]
Yes, FLAC
I mixed it up with icecast request :-).

**Comment by vkostas** [comment]
ah, I see...
To locate PPC, I had first:

>    ifeq ($(findstring $(ARCH),<b>powerpc ppc824x ppc853x ppc854x qoriq</b>),$(ARCH))
>      CONFIGURE_ARGS += --disable-altivec
>    endif*
>    include ../../mk/spksrc.cross-cc.mk

Then I went for "dynamic" logic
>    include ../../mk/spksrc.cross-cc.mk
>    ifeq ($(findstring $(ARCH),<b>$(PPC_ARCHES)</b>),$(ARCH))
>      CONFIGURE_ARGS += --disable-altivec
>    endif

I could set *CONFIGURE_ARGS* after the *cross-cc.mk* but it doesn't look good to me.

>    include ../../mk/spksrc.cross-cc.mk
>    ifeq ($(findstring $(ARCH),<b>$(PPC_ARCHES)</b>),$(ARCH))
>      CONFIGURE_ARGS += --disable-altivec
>    endif

I see node/Makefile and mono/Makefile use PPC_ARCHES before cross-cc.mk.
Any hint???

**Comment by Dr-Bean** [comment]
That functionality currently only works for spk Makefiles, not cross Makefiles. Just use the arches themselves, all the other cross packages do.

**Pull request closed without merging**
