### PR TITLE
Update package sickrage repo url and added wheel requirements 

### PR DESCRIPTION
**Pull request by echel0n**
_Motivation:_ Explain here what the reason for the pull request is.
_Linked issues:_ Optionally, add links to existing issues or other PR's

### Checklist
- [] Build rule `all-supported` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
Title is unclear: which "package" are you speaking about ?
You have submitted three "Update Makefile" commits. I invite you to learn about Git `commit --amend` and `rebase --interactive` commands - even if maintainer may squash all you commits in a single one at merge.

**Comment by ymartin59** [comment]
Python dependencies are installed as wheels based on version enforced requirements. That is good.

From my point of view, it sounds relevant to package application itself as wheel based on a release tag, reported in Synology package version too, instead of a "packaging-timestamp" used until now.

What do you think about this idea ?

**Comment by Diaoul** [comment]
From what I gather there are two conflicting team of devs for SickRage and this PR doesn't just change the URL but also the underlying software (SickRage). The DMCA that took down the current repo was issued by @echel0n. A counter notice has been issued and not processed yet afaik.

I'm not taking sides here, just don't want to change the users what they are used to.

/cc @fernandog

**Comment by ymartin59** [comment]
@Diaoul Thanks for noticing this "trouble". What is your opinion about creating an other package for "SiCKRAGE.ca" compared to existing "sickragetv" package ?

**Comment by echel0n** [comment]
um git.sickrage.ca and GitHub.com/sickragetv/sickrage are both the same as they are both operated by me except that git.sickrage.ca is my own gitlab server dedicated for sickrage

**Comment by echel0n** [comment]
There's I've squashed the commits as asked and changed the title for this PR to reflect the package name being updated

**Comment by cytec** [comment]
@Diaoul as far as i can see this looks good to me.
@echel0n just changed the url form his github repo to his main repo, so the underlying software (SickRage) isn't changed.

I've created the SPK for the original SickRage (by @echel0n) and if i recall that correctly we decided to stay with the "original" url for the SPK even if it was requested to change it. Also if i remember that correctly we suggested that the fork should use another name to not confuse everyone.

**Comment by Diaoul** [comment]
Thanks @cytec for the reminder and @echel0n for the clarification. In that case LGTM!

**Comment by echel0n** [comment]
Thanks guys for merging this

**Comment by echel0n** [comment]
@cytec will you be making a new spk to put up for others at https://synocommunity.com/packages ?

**Comment by cytec** [comment]
uh strange thought that'll be there already :/

**Comment by echel0n** [comment]
Just noticed your reply, I've opened a issue to track this via https://github.com/SynoCommunity/spksrc/issues/2840

Thanks!

**Pull request merged**
