### PR TITLE
Radarr: Update to 4.1.0.6175 and .NET6

### PR DESCRIPTION
**Pull request by bakerboy448**
## Description

- Updates Radarr base package to v4.1
- Updates Radarr base package to .NET6 from .net core
- Fixes users having to purge app data when reinstalling from v4

Fixes https://github.com/SynoCommunity/spksrc/issues/5114

## Checklist

- Unable to Test no mac or linux box; update is a straightforward bump however
- [ ] Needs a testing
- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [X] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by publicarray** [comment]
I just did a test and all user data is gone after the update from our previous (old) version.

Reproduction Steps:
1. Install package from https://synocommunity.com/package/radarr
2. add a few movies
3. Update the package from this PR: https://github.com/SynoCommunity/spksrc/actions/runs/2190231702
4. notice that the moves added earlier are now missing.

**Comment by publicarray** [comment]
@hgy59 @th0ma7 I don't have time to find out why at the moment sorry.

**Comment by publicarray** [comment]
It would be nice if people did could follow the checklist and test their PRs even for simple version bumps it would help me out a ton. You can still download and test the builds, e.g. by running DSM on the DSM visualised anyway. I just don't have the time anymore.

**Comment by bakerboy448** [comment]
@publicarray will work on it and see. Forgot the CI provides builds.  Any inkling for why that's the case?  Does the installer remove the appdata folder for updates/installs or something?   Can you provide a quick ls -lha of the appdata folder?

mom a tangential relation:
however we're and have been seeing multiple reports of users not being able to get the Oct 2021 package with the tmpdir fix? Any idea why the SynoComm site is providing old out of date packages as "latest".   Why would the site be providing incorrect packages for compatible DSM and NASes? These are for apps that have no issue updating internally to v4 or do but need the TMP DIR fix manual workaround.

**Comment by ta264** [comment]
Is there a way to get a virtual DSM install in hyper-v? We're trying our best to help out with the radarr packages but I at least don't have a Synology device to test with unfortunately

**Comment by bakerboy448** [comment]
Added on discord, but placing here for posterity

rev 16 (which doesn't even seem to appear available to many users; and is the base for this PR) https://github.com/SynoCommunity/spksrc/commit/5a174ae655388df9bbbf6d9bb19a8f16662a9fcb appears to fail to properly migrate the appdata / uses a different appdata folder and it would seem to be an existing bug in the package, not from the PR. 

```
About
Version
3.0.2.4552
Package Version
x64-7.0_20210708-15 by Team Radarr
.NET Core
Yes (3.1.10)
DB Migration
188
AppData directory
/volume1/@appstore/radarr/var/.config/Radarr
Startup directory
/volume1/@appstore/radarr/share/Radarr/bin
Mode
Console
Uptime
```

```
About
Version
4.1.0.6175
Package Version
x64-7.0_20220420-17 by Team Radarr
.NET
Yes (6.0.3)
DB Migration
206
AppData directory
/volume1/@appdata/radarr/.config/Radarr
Startup directory
/volume1/@appstore/radarr/share/Radarr/bin
Mode
Console
Uptime
```

**Pull request closed without merging**
