### PR TITLE
Syncthing SPK

### PR DESCRIPTION
**Pull request by cytec**
@Diaoul here we go :)

i've added the option STATIC_BINARIES to enable generation of static linked binaries

### CODE REVIEW

**Comment by cytec** [comment]
@Diaoul @Dr-Bean any progress on this? just saw that the SPK is already in the Package Repo...

**Comment by Diaoul** [comment]
Looks good to me

**Comment by G1zm0** [comment]
Any chance this can be made available for the avaton architecture?

**Comment by piwi82** [comment]
@G1zm0 : https://synocommunity.com/package/syncthing

**Comment by G1zm0** [comment]
@piwi82 It's not there yet.
```
Architectures
88f628x armada370 armadaxp bromolow cedarview evansport armada375

**Pull request merged**
