### PR TITLE
ffsync: Update syncstorage-rs to v0.17.15

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This PR includes the following:

1. Update syncstorage-rs to v0.17.15

Fixes # 

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by mreid-tt** [comment]
hey @hgy59, I was having another go at this further to the challenges of upgrading diesel in #6187. Looking deeper at the errors originally we had this:
```
error: failed to run custom build command for `mysqlclient-sys v0.4.1`

Caused by:
  process didn't exit successfully: `/github/workspace/spk/ffsync/work-aarch64-7.1/diesel-2.2.3/target/release/build/mysqlclient-sys-257caf6ec025a9da/build-script-build` (exit status: 101)
```
```
  --- stderr
  thread 'main' panicked at /github/workspace/distrib/cargo/registry/src/index.crates.io-6f17d22bba15001f/mysqlclient-sys-0.4.1/build.rs:91:5:
  Did not find a compatible version of libmysqlclient.
  Ensure that you installed one and teached mysqlclient-sys how to find it
  You have the following options for that:

  * Use `pkg_config` to automatically detect the right location
  * Use vcpkg to automatically detect the right location. 
  You also need to set `MYSQLCLIENT_VERSION` to specify which
  version of libmysqlclient you are using
  * Set the `MYSQLCLIENT_LIB_DIR` and `MYSQLCLIENT_VERSION` environment 
  variables to point the compiler to the right directory and specify 
  which version is used
  * Make the `mysql_config` binary avaible in the environment that invokes
  the compiler
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `diesel_cli v2.2.3 (/github/workspace/spk/ffsync/work-aarch64-7.1/diesel-2.2.3/diesel_cli)`, intermediate artifacts can be found at `/github/workspace/spk/ffsync/work-aarch64-7.1/diesel-2.2.3/target`.
```

If we focus on the `stderr` it provides some guidance on this. First there is the declaration of `MYSQLCLIENT_LIB_DIR` and `MYSQLCLIENT_VERSION` environment variables. Checking with our code for diesel we already have one of them set:
https://github.com/SynoCommunity/spksrc/blob/2af6c9cc435216944517db560b3ad25e46814773/cross/diesel/Makefile#L29

So the next thing I did was set the other one in https://github.com/SynoCommunity/spksrc/commit/f52e0eac320d4c2bac12dcbbce7a464a6b3faa6d and this revealed a new error:

```
  --- stderr
  thread 'main' panicked at /github/workspace/distrib/cargo/registry/src/index.crates.io-6f17d22bba15001f/mysqlclient-sys-0.4.1/build.rs:230:13:
  mysqlclient-sys does not provide bundled bindings for libmysqlclient `6.1.11` for the target `aarch64-unknown-linux-gnu`.
                   Consider using the `buildtime_bindgen` feature or contribute bindings to the crate
  Debug information: (version: None, target_arch: aarch64, ptr_size: 64)
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `diesel_cli v2.2.4 (/github/workspace/spk/ffsync/work-aarch64-7.1/diesel-2.2.4/diesel_cli)`, intermediate artifacts can be found at `/github/workspace/spk/ffsync/work-aarch64-7.1/diesel-2.2.4/target`.
```

This concurs with what I see in the [mysqlclient-sys](https://github.com/sgrif/mysqlclient-sys/blob/master/build.rs) build code. So the next strategy was to use the `buildtime_bindgen` feature which I implemented in https://github.com/SynoCommunity/spksrc/pull/6228/commits/7b0b20005e5a3cc0d7528d93d5b91f3250e3c8ac. This resulted in a very different error as follows:

```
  --- stderr
  thread 'main' panicked at /github/workspace/distrib/cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.69.4/lib.rs:622:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `diesel_cli v2.2.4 (/github/workspace/spk/ffsync/work-aarch64-7.1/diesel-2.2.4/diesel_cli)`, intermediate artifacts can be found at `/github/workspace/spk/ffsync/work-aarch64-7.1/diesel-2.2.4/target`.
```

So based on this it seems to be trying to dynamically create the bindings for libmysqlclient `6.1.11` but is missing `libclang`. I don't know if this is something you can possibly assist with?

Alternately, if `libclang` is only used to generate the binding we can perhaps upgrade to libmysqlclient `8.4` which already has a supported binding.

This is all a bit of guesswork on my part but let me know if I may be onto something.

**Comment by mreid-tt** [comment]
> Hoping not to muddy the water but is that libclang from an host or target perspective? i.e. using clang to build? or to link against its library at cross-compile time?

I really don't know how to answer that as this is a bit new for me. In the same readme for buildgen i do see this line:

> BINDGEN_EXTRA_CLANG_ARGS_<TARGET>: similar to BINDGEN_EXTRA_CLANG_ARGS, but used to set per-target arguments to pass to clang. Useful to set system include directories in a target-specific way in cross-compilation environments with multiple targets. Has precedence over BINDGEN_EXTRA_CLANG_ARGS.

Other than that, is there a specific command or something in the codebase which would suggest which use case?

**Comment by hgy59** [comment]
Just saw a comment in https://github.com/mozilla-services/syncstorage-rs/blob/master/syncstorage-mysql/Cargo.toml
```
# There appears to be a compilation error with diesel
```

**Comment by hgy59** [comment]
> If we focus on the `stderr` it provides some guidance on this. First there is the declaration of `MYSQLCLIENT_LIB_DIR` and `MYSQLCLIENT_VERSION` environment variables. Checking with our code for diesel we already have one of them set:
> 
> https://github.com/SynoCommunity/spksrc/blob/2af6c9cc435216944517db560b3ad25e46814773/cross/diesel/Makefile#L29

This is now obsolete with the bugfix for mysql_config in #6218 see [cross/mysql-connector-c/Makefile](https://github.com/SynoCommunity/spksrc/pull/6218/files#diff-a29335ae733917c15ea391777fbc8888f1365d19c70a854c32e7aa82f46435f5)

Instead of defining `MYSQLCLIENT_LIB_DIR` and `MYSQLCLIENT_VERSION` you have to add the path to mysql_config and it will evaluate the values for you:
```Makefile
# let it find mysql_config to find version and library path of libmysqlclient
ENV += PATH=$$PATH:$(STAGING_INSTALL_PREFIX)/bin 
```

**Comment by mreid-tt** [comment]
> Just saw a comment in https://github.com/mozilla-services/syncstorage-rs/blob/master/syncstorage-mysql/Cargo.toml
> 
> ```
> # There appears to be a compilation error with diesel
> ```

@hgy59, thanks for this. I looked a bit more into the codebase and saw in https://github.com/mozilla-services/syncstorage-rs/pull/1576/commits/eb02e835a80bfebe2a06ab34ad2891e13af8c2f8 that they are not actually requiring anything more than diesel 1.4:

From the commit comment:

> We're currenlty locked to diesel 1.4 due to some significant changes in the `diesel_logger` crate and how it expects `Connections` to be defined.

From the Cargo.toml:

> Updating to 2.* requires changes to the Connection code for logging. (Adding an `instrumentation()` and `set_instrumentation()` method.) More investigation required.

Based on this I am curious how come the diesel 2.1.6 that we use works at all?

**Comment by mreid-tt** [comment]
@hgy59 I believe this update is ready. Reviewing the source repository for [requirements.txt](https://github.com/mozilla-services/syncstorage-rs/blob/master/requirements.txt) and [tools/tokenserver/requirements.txt](https://github.com/mozilla-services/syncstorage-rs/blob/master/tools/tokenserver/requirements.txt), I didn’t notice any updates since the last version we merged. It seems no changes are needed to the existing requirements, but I’d appreciate it if you could double-check and confirm if everything is good to go.

**Pull request merged**
