### PR TITLE
Updated digests for MTProxy

### PR DESCRIPTION
**Pull request by Anonym-tsk**
Fix build for #3393

### CODE REVIEW

**Comment by m4tt075** [comment]
I've just tested your PR, but it seems the digests have changed again. Bad practice upstream and not sure what causes those changes. Do you want to check with them and update your PR once there is some hope they'll not touch the source for some time?

**Comment by Anonym-tsk** [comment]
I removed digests.
I don't know how to fix it.
```
git clone --no-checkout --quiet https://github.com/TelegramMessenger/MTProxy.git mtproxy
git --git-dir=mtproxy/.git --work-tree=mtproxy checkout --quiet f9158e3
tar --exclude-vcs -czf mtproxy-1.tar.gz mtproxy
tar --exclude-vcs -czf mtproxy-2.tar.gz mtproxy
tar --exclude-vcs -czf mtproxy-2.tar.gz mtproxy
sha1sum mtproxy-1.tar.gz
sha1sum mtproxy-2.tar.gz
sha1sum mtproxy-3.tar.gz
```
All sums are different and i don't know why.
@ymartin59 please merge this PR and build MTProxy package.

**Comment by m4tt075** [comment]
You don't want a source that is subject to change all the time. You don't know what you are downloading. All testing is meaningless and your package can potentially break. However, it seems a release was tagged a couple of days ago:
https://github.com/TelegramMessenger/MTProxy/releases/
You can try to use that as source and reintroduce the required digests. If the release package keeps changing, I'd definitely contact the upstream developer and ask what causes this.
Sorry for the hassle, but I'm sure @ymartin59 would not be able to consider merging and publishing it otherwise...

**Comment by Anonym-tsk** [comment]
@m4tt075 please read my comment again. Problem not with code, problem with tar.
However, thanks for information about release. Maybe better way is to use released version.

**Comment by m4tt075** [comment]
https://serverfault.com/questions/110208/different-md5sums-for-same-tar-contents
But in any case, you will need a reliable source with reproducible hash.

**Comment by Anonym-tsk** [comment]
But how it works with other packages? My tar command same as in spksrc.download.mk script and if it is normal tar behavior, I don't know how other packages built.

**Comment by m4tt075** [comment]
Well, usually you don't tar or gzip yourself, but just extract the tar.gz archive you are downloading. That does not change. Look at the `nano` Makefile for instance:
https://github.com/SynoCommunity/spksrc/blob/master/cross/nano/Makefile
When I update a standard package to a new release version, and therefore a new source, I use the following approach:
1. Upgrade the Makefile in `spksrc/spk/[package]` to the new versioning
2. Upgrade the Makefile in `sprksrc/cross/[package]` to the new versioning
3. Delete the old `digests` file in `cross/[package]`
4. Run a test build in `cross/[package]` (this is NO mistake, NOT in `spk/`). This will download the source file you have designated in the Makefile to your local `spksrc/distrib` folder.
5. If everything succeeded, just run `make digests` from within the `cross/[package]` folder and the hash file corresponding to the downloaded source in the `distribution/` folder is automatically created for you. 

Want to give it a go?

**Comment by m4tt075** [comment]
Fair question. Frankly, I don't know. I have PRed an update for `Comskip` some time ago (see #3417). There were problems with the download method, but - if I remember correctly - it was related with problems with package folder names, not hashtags. Have you verified that the current `Comskip` package in master does build reproducibly? Or does it exhibit the same problems you ran into?

**Comment by Anonym-tsk** [comment]
```
===>  Building package for arch apollolake
make[1]: Entering directory '/spksrc/spk/comskip'
===>  Set up toolchain
make[2]: Nothing to be done for 'default'.
===>  Processing dependencies of comskip
make[2]: Entering directory '/spksrc/cross/comskip'
===>  Downloading files for comskip
git clone https://github.com/erikkaashoek/Comskip.git/
===>  Verifying files for comskip
===>    Checking sha1sum of file comskip-git6f1a658.tar.gz
===>      Wrong sha1sum for file comskip-git6f1a658.tar.gz
===>      Renamed as comskip-git6f1a658.tar.gz.wrong
===>      Download cookie removed to trigger the download again
../../mk/spksrc.checksum.mk:42: recipe for target 'checksum_target' failed
make[2]: *** [checksum_target] Error 1
make[2]: Leaving directory '/spksrc/cross/comskip'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory '/spksrc/spk/comskip'
../../mk/spksrc.spk.mk:452: recipe for target 'arch-apollolake' failed
make: [arch-apollolake] Error 2 (ignored)
```
I created issue #3484

**Comment by Anonym-tsk** [comment]
However, now i use released version MTProxy here and, @ymartin59 please, merge this pull request and publish mtproxy package.

**Comment by Anonym-tsk** [comment]
@ymartin59 Is this project still alive or you are already bought QNAP? 🤨

**Comment by ymartin59** [comment]
@Anonym-tsk Have you ever tried to build that PR ??
```
===>  Extracting for mtproxy
tar -xzpf /spksrc/cross/mtproxy/../../distrib/mtproxy-v1.tar.gz -C /spksrc/spk/mtproxy/work-x64-5.2 
===>  Patching for mtproxy
patch -p0 < patches/100-makefile.patch
/bin/sh: 4: cd: can't cd to /spksrc/spk/mtproxy/work-x64-5.2/mtproxy-v1
../../mk/spksrc.patch.mk:49: recipe for target 'patch_target' failed
make[2]: *** [patch_target] Error 2
make[2]: Leaving directory '/spksrc/cross/mtproxy'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
```

**Comment by Anonym-tsk** [comment]
Sorry, it's my mistake. Fixed here #3463

**Pull request merged**
