### PR TITLE
tvheadend: fix path to ffmpeg(7)

### PR DESCRIPTION
**Pull request by hgy59**
## Description

Fix for tvheadend to find ffmpeg(7) in the path.
Might solve the issue #6301.

Fixes # 

## Checklist

- [x] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix

### CODE REVIEW

**Review by th0ma7 — APPROVED** [review]
LGTM

**Comment by hgy59** [comment]
just waiting for feedback https://github.com/SynoCommunity/spksrc/issues/6301#issuecomment-2453553433

**Comment by meeuuh92** [comment]
> just waiting for feedback [#6301 (comment)](https://github.com/SynoCommunity/spksrc/issues/6301#issuecomment-2453553433)

I've downloaded the test package. I will test tomorow

**Comment by hgy59** [comment]
> I'm sorry.. i don't know if i do something wrong (or if my DSM 6.2.4 is buggy but it doesn't work

regarding the logs, it seems that the _recording directory_ is not valid or not configured (`/`) but this can't be the reason for tvheadend to not start:
```
2024/11/10 10:41:12     ===> Step postupgrade. STATUS=UPGRADE USER=tvheadend GROUP=sc-media SHARE_PATH=
2024/11/10 10:41:25     Granting 'sc-tvheadend' unix ownership on /volume2/@appstore/tvheadend/var
2024/11/10 10:41:25     Begin service_postupgrade
2024/11/10 10:41:25     Adding sc-media group permissions on recording directories:
2024/11/10 10:41:25     Done: /
2024/11/10 10:41:25     Skip granting 'sc-media' group permissions on / as the directory does not reside in '/volumeX'. Set manually if needed.
2024/11/10 10:41:25     Restore 'sc-tvheadend' unix permissions on package system directories
2024/11/10 10:41:25     Granting 'sc-tvheadend' unix ownership on /volume2/@appstore/tvheadend/var
2024/11/10 10:41:25     End service_postupgrade
```

When tvheadend does not start, (`install tvheadend 4.3.20240928-40 End start-stop-status start ret=[1]`) we would have to look into the log file at `/var/packages/tvheadend/var/tvheadend.log`.
But this is not availble anymore, since you already installed revision 38 again.

Unfortunately I can't test tvheadend package on armv7 and DSM 6.2.4 (my ds-115j runs DSM 7.1.1).
And on DSM 7.1.1 the package runs as expected.

It might be an issue with your System, but I can't imagine what, since rev. 38 runs.
Alas it might be a problem with installation on `/volume2`.
Anyway, if someone has this issue, then can you please provide the tvheadend.log file from the var folder?

The output of `synopkg status tvheadend | jq` might provide additional information.

**Comment by hgy59** [comment]
Completed without solution/confirmation for #6301.

**Pull request merged**
