### PR TITLE
SickChill 20221013 - 5449 revival

### PR DESCRIPTION
**Pull request by BKSteve**
## SickChill redo

Fixes #5449 

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by BKSteve** [comment]
removal of \@appstore/sickchill working on both 6&7 
upgrading works on both 6&7

**Comment by BKSteve** [comment]
@th0ma7 this shows to have fixed user name and update issues of #5449. 
Please review.

**Review by th0ma7 — APPROVED** [review]

**Comment by th0ma7** [comment]
LGTM, now merged

**Comment by th0ma7** [comment]
And now published.  Again thnx a lot for your contribution!  Cheers!

**Comment by BKSteve** [comment]
Wouldn't have been possible without all the cryptography rust work

**Comment by th0ma7** [comment]
Thnx for mentioning but I'm not the only player here as I started off from where @hgy59 had already came with.  Again, thnx for your contribution.

**Pull request merged**
