### PR TITLE
Updated SABnzbd-Testing to 1.1.0 Beta 1

### PR DESCRIPTION
**Pull request by KaraokeStu**
Updated the testing package to 1.1.0 Beta 1.

Notes:

* @Dr-Bean has noted a problem with the wizard (This is a bug in SABnzbd itself, not our package) and a bug has been raised.
* New icon added, but inverted for the testing package
* A minor tweak has been needed to the download location of the source code, due to a naming inconsistency - hopefully it'll be fixed by the SABnzbd team on the next release and I can revert my fix

### CODE REVIEW

**Comment by Safihre** [comment]
What did you do to our logo?! Is this how it will look in their package managers?
Here are the SVG's for all our logo's:
https://github.com/sabnzbd/sabnzbd/files/213319/sabnzbd_assets_20160411.zip
Maybe you can combine the NZB-file logo (which is green) with the 'SAB' text from the smaller icon?

Yes, the ```a``` will not be there next time, only now because there was a bug in the first version.

**Comment by KaraokeStu** [comment]
Sorry @Safihre I didn't mean to mess up the logo! :)

I'll amend to use the sabnzbd_icon_nzb_v8_o file :)

**Comment by Safihre** [comment]
Great :)

**Comment by KaraokeStu** [comment]
Hi @Safihre how is that - updated as per your request :)

**Comment by Safihre** [comment]
Awesome! :bowtie:

**Comment by Dr-Bean** [comment]
LGTM :+1: 
Logo is probably a bit big (256*256 is what we're looking for), but its better to have a source which is too big than too small ;) @KaraokeStu Maybe you can resize the file?

**Comment by KaraokeStu** [comment]
@Dr-Bean done :)

**Comment by Dr-Bean** [comment]
That was quick ;) Additional changes with https://github.com/SynoCommunity/spksrc/commit/339720e77fabee8eea4f27307fda46f1f3ab668d. 
Building...

**Comment by Dr-Bean** [comment]
..and published sabnzbd-testing 1.1.0Beta1-6 on the repository. Thanks for creating the PR @KaraokeStu and thanks for the logo's @Safihre :)

**Comment by Safihre** [comment]
But now the logo says NZB while when it was still 600+ pixels it said SAB...

**Comment by KaraokeStu** [comment]
I'm really confused there too... My fork definitely shows the correct logo...

Do we need it fixing now, or can it wait until your next beta?

**Comment by Dr-Bean** [comment]
Huh...weird. The PR definitely shows `nzb`: https://github.com/KaraokeStu/spksrc/blob/6df37b9af9ad95543684e668b3edee4cf15fc538/spk/sabnzbd-testing/src/sabnzbd-testing.png.
I overlooked that when merging, I suppose.

@KaraokeStu, if you have the correct logo at hand, you can put it in a PR, and I'll re-release the package with the same version number (so just a PR for the logo switch would be fine). 
The people who upgraded already will have the wrong logo until the next package release, but people who will upgrade from then on will get the new one (and it'll apply to all future releases as well of course). Cool with that, @Safihre?

**Comment by Dr-Bean** [comment]
Deactivated the -testing package for now, so we stop distributing it until we have a version with a correct logo.

**Comment by Safihre** [comment]
Not such a big problem, the arrow is still correct and it downloads NZB's so can also wait for next beta :)

**Comment by KaraokeStu** [comment]
Fixed with PR https://github.com/SynoCommunity/spksrc/pull/2377 @Dr-Bean :+1:

**Comment by Dr-Bean** [comment]
Published a fresh set of packages. Due to caching and whatnot, https://synocommunity.com/package/sabnzbd-testing may not show the correct logo, but it's fixed in the packages at least.

**Comment by Safihre** [comment]
Awesome :+1:

**Pull request merged**
