### PR TITLE
update gitea to 1.22.3

### PR DESCRIPTION
**Pull request by GrandDuke1106**
## Description

Update gitea to 1.22.3

Fixes # 

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by GrandDuke1106** [comment]
and test successfully on ds920+

**Comment by mreid-tt** [comment]
Can you complete the other tests in the checklist? I'll merge once testing is completed.

**Comment by GrandDuke1106** [comment]
Checklist completed except the last item

**Comment by mreid-tt** [comment]
The package has been merged and published.

@hgy59, I noticed that the last version you published included an SRM build. I wasn’t sure if this was necessary for a router, but I'm happy to include it if you recommend. Could you advise on the criteria for determining when an SRM version should be published?

**Pull request merged**
