### PR TITLE
Fix for Lidarr internal updater and version bump to 1.0.2

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This request implements a fix for an alternate TMP directory in Lidarr to resolve the broken internal updater. It also bumps Lidarr to the latest release version 1.0.2.

Fixes # https://github.com/SynoCommunity/spksrc/issues/5303, https://github.com/SynoCommunity/spksrc/issues/5081

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [x] Package update

### CODE REVIEW

**Comment by bakerboy448** [comment]
Can you also touch update_required to the app data for as well for lidarr if it's not already there?

I think radarr or sonarr may finally have that logic

**Comment by mreid-tt** [comment]
> Can you also touch update_required to the app data for as well for lidarr if it's not already there?

Hey, can you give me more details on how to do this?

**Comment by bakerboy448** [comment]
https://github.com/SynoCommunity/spksrc/blob/daf28a86b18b4fec0d9df7ae84e514af23f5577c/spk/radarr/src/service-setup.sh#L29


also I believe both radarr and certainly sonarr need package bumps as well if you're willing

**Comment by mreid-tt** [comment]
Okay, so the current line is:
`touch ${CONFIG_DIR}/Lidarr/update_required`
Should I change it to:
`touch ${CONFIG_DIR}/Lidarr/update_required 2>&1`

**Comment by mreid-tt** [comment]
hey @hgy59, I believe this PR is ready to merge. It resolves a broken internal updater in Lidarr under DSM 7.1.

**Comment by mreid-tt** [comment]
> also I believe both radarr and certainly sonarr need package bumps as well if you're willing

@bakerboy448, my understanding from https://github.com/SynoCommunity/spksrc/pull/5400#issuecomment-1221540068 is that version bumps for packages which have functioning internal updaters are only accepted under particular circumstances. as such a version bump alone is not sufficient reason to be accepted.

**Comment by bakerboy448** [comment]
Due to the packages out of date synology users are unable to reinstall the packages without purging the appdata.

The existing packages - especially Sonarr - are comically out of date and providing old effectively unsupported versions.

**Comment by mreid-tt** [comment]
> Due to the packages out of date synology users are unable to reinstall the packages without purging the appdata.
> 
> The existing packages - especially Sonarr - are comically out of date and providing old effectively unsupported versions.

Yes, I experienced the issue of Sonarr being unable to smoothly reinstall because of the appdata not being purged (https://github.com/SynoCommunity/spksrc/issues/5133#issuecomment-1274710664). That can be the basis of a new issue and I will check if one has already been reported. From there a PR to fix that can be submitted which also includes a version bump (so it is compliant with https://github.com/SynoCommunity/spksrc/pull/5400#issuecomment-1221540068).

**Review by ymartin59 — APPROVED** [review]

**Comment by th0ma7** [comment]
@hgy59 and @ymartin59 is there anything left blocking this PR to be published?

**Pull request merged**
