### PR TITLE
patch.mk: Allow patching in non-spk|cross|diyspk

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_   Try to solve issue of patches for native and toolchain packages do not work 
_Linked issues:_  #4884 

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by th0ma7** [comment]
Using the following patches over `nasm` now works:
```
~spksrc/spksrc/nasm$ make | tee build.out
===>  Downloading files for nasm
===>    File nasm-2.15.05.tar.gz already downloaded
===>  Verifying files for nasm
===>    Checking sha1sum of file nasm-2.15.05.tar.gz
===>    Checking sha256sum of file nasm-2.15.05.tar.gz
===>    Checking md5sum of file nasm-2.15.05.tar.gz
/home/spksrc/fix-patch/spksrc/native/nasm/../../distrib/nasm-2.15.05.tar.gz
===>  Processing dependencies of nasm
===>  Extracting for nasm
tar -xzpf /home/spksrc/fix-patch/spksrc/native/nasm/../../distrib/nasm-2.15.05.tar.gz -C /home/spksrc/fix-patch/spksrc/native/nasm/work-native 
===>  Patching for nasm
===>  PATCHES: patches/001-remove-invalid-pure_func-qualifiers.patch
patch -p0 < patches/001-remove-invalid-pure_func-qualifiers.patch
patching file include/nasmlib.h
Hunk #1 succeeded at 201 (offset 51 lines).
Hunk #2 succeeded at 209 (offset 51 lines).
Hunk #3 succeeded at 221 with fuzz 1 (offset 51 lines).
Hunk #4 succeeded at 345 (offset 39 lines).
===>  Configuring for nasm
```

**Comment by th0ma7** [comment]
And it does also from `toolchain` directory (I simply put a bad patch to see it fail):
```
~spksrc/spksrc/toolchain$ make
===>    Downloading files for syno-x64
===>      wget https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%207.0.0%20Tool%20Chains/Intel%20x86%20Linux%204.4.180%20%28Apollolake%29/apollolake-gcc750_glibc226_x86_64-GPL.txz
2021-09-25 10:29:26 URL:https://cfhcable.dl.sourceforge.net/project/dsgpl/Tool%20Chain/DSM%207.0.0%20Tool%20Chains/Intel%20x86%20Linux%204.4.180%20%28Apollolake%29/apollolake-gcc750_glibc226_x86_64-GPL.txz [79940764/79940764] -> "apollolake-gcc750_glibc226_x86_64-GPL.txz.part" [1]
===>    Verifying files for syno-x64
===>      Checking sha1sum of file apollolake-gcc750_glibc226_x86_64-GPL.txz
===>      Checking sha256sum of file apollolake-gcc750_glibc226_x86_64-GPL.txz
===>      Checking md5sum of file apollolake-gcc750_glibc226_x86_64-GPL.txz
/home/spksrc/fix-patch/spksrc/toolchain/syno-x64-7.0/../../distrib/toolchain/7.0/apollolake-gcc750_glibc226_x86_64-GPL.txz
===>    Extracting for syno-x64
tar -xpf /home/spksrc/fix-patch/spksrc/toolchain/syno-x64-7.0/../../distrib/toolchain/7.0/apollolake-gcc750_glibc226_x86_64-GPL.txz -C /home/spksrc/fix-patch/spksrc/toolchain/syno-x64-7.0/work 
===>    Patching for syno-x64
patch -p0 < patches/001-remove-invalid-pure_func-qualifiers.patch
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- include/nasmlib.h.orig	2019-01-11 10:27:42.527098886 +0100
|+++ include/nasmlib.h	2019-01-11 10:30:53.731190121 +0100
--------------------------
File to patch: ^Cmake: *** [../../mk/spksrc.patch.mk:65: patch_target] Interrupt
```

**Review by hgy59 — APPROVED** [review]
LGTM
I will incorporate the fix for toolchain patching in #4852 (patching works with your changes and my reorder of the toolchain targets).

**Comment by th0ma7** [comment]
Closing as this is to be included in your PR.

**Pull request closed without merging**
