### PR TITLE
bazarr: update 1.4.2 => 1.4.5 and migrate to ffmpeg 7

### LINKED ISSUE #6257: [Package Request] Update Bazarr to latest and to use latest current available FFMPEG on the Synology (ffmpeg 6/7 as required by Media managers)
### Software Name

Bazarr

### Brief Description

Tracks Sonarr/Radarr subtitles and downloads them.

### Website

https://www.bazarr.media/

### Documentation

_No response_

### Build/Installation documentation

https://wiki.bazarr.media/Getting-Started/Installation/Windows/source/

### Source code

https://github.com/morpheus65535/bazarr

### OpenSource License

GPLv3

### Other License

_No response_

### PR DESCRIPTION
**Pull request by smaarn**
## Description

Update bazarr 1.4.2 => 1.4.5 and switch to ffmpeg 7

Fixes #6257 

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by smaarn** [comment]
Currently blocked by https://github.com/SynoCommunity/spksrc/pull/6197

**Comment by mreid-tt** [comment]
Hi @smaarn, sorry to hear that the rebase didn’t work on your end—it seemed to work fine for me in #6187. Also, @th0ma7 mentioned [here](https://github.com/SynoCommunity/spksrc/pull/6187#issuecomment-2332925364) that many of the errors could be ignored, but I understand your situation is different since your build isn’t completing.

**Comment by smaarn** [comment]
> Hi @smaarn, sorry to hear that the rebase didn’t work on your end—it seemed to work fine for me in #6187. Also, @th0ma7 mentioned [here](https://github.com/SynoCommunity/spksrc/pull/6187#issuecomment-2332925364) that many of the errors could be ignored, but I understand your situation is different since your build isn’t completing.

Actually the issue seems now to be related to https://numpy.org/devdocs/reference/distutils_status_migration.html

Essentially our way of installing numpy seems to be broken. Checking.

**Comment by hgy59** [comment]
> > Hi @smaarn, sorry to hear that the rebase didn’t work on your end—it seemed to work fine for me in #6187. Also, @th0ma7 mentioned [here](https://github.com/SynoCommunity/spksrc/pull/6187#issuecomment-2332925364) that many of the errors could be ignored, but I understand your situation is different since your build isn’t completing.
> 
> Actually the issue seems now to be related to the below:
> 
> ```
> lrm91yfb/numpy_50629a861b5a48619313acd3869dbdad/numpy/distutils/command/config.py", line 19, in <module>
>             from numpy.distutils.mingw32ccompiler import generate_manifest
>           File "/tmp/pip-wheel-lrm91yfb/numpy_50629a861b5a48619313acd3869dbdad/numpy/distutils/mingw32ccompiler.py", line 27, in <module>
>             from distutils.msvccompiler import get_build_version as get_build_msvc_version
>         ModuleNotFoundError: No module named 'distutils.msvccompiler'
> ```
> 
> Essentially our way of installing numpy seems to be broken by latest setuptools version. (see [pypa/setuptools#3505](https://github.com/pypa/setuptools/pull/3505))

I faced the same issue with numpy https://github.com/SynoCommunity/spksrc/pull/6200#issuecomment-2387114044
Tried to use setuptools 59.2.0 as proposed by numpy. It did not work after installation of setuptools 59.2.0 into the cross env.
And using setuptools 59.2.0 in native/python311 gave an error due version conflict with setuptools-rust.
I guess we have to use setuptools 59.2.0 and compatible setuptools-rust everywhere. The cross compilation of pyhton wheels is really a mess.

**Comment by th0ma7** [comment]
Actually its a combination of things, including pip.  That's why we need a per-wheel crossenv option.  I intend to continue having a default using latest versions, and have the possibility, such as with older numpy, to create per wheel as needed with the set of mandatory prerequisites.

Next on my todo list now that ffmpeg is done.

**Comment by hgy59** [comment]
@smaarn when  #6200 is merged, bazarr builds will work again, but you have to downgrade numpy to v1.24.4,

**Comment by smaarn** [comment]
> @smaarn when #6200 is merged, bazarr builds will work again, but you have to downgrade numpy to v1.24.4,

@hgy59 I managed to have everything build successfully after rebase. Why were you expecting me to need to downgrade numpy ?

**Comment by hgy59** [comment]
@smaarn in #6200 I already downgraded numpy for DSM 7 from 1.25.1 to 1.24.4 (requirements-crossenv-numpy.txt)

**Comment by hgy59** [comment]
@smaarn in preparation for #6255  can you please update the spk/bazarr/Makefile and replace `DEPENDS = cross/$(SPK_NAME)` by `DEPENDS = cross/bazarr`?

For #6255 it will be mandatory that none of the DEPENDS* definitions use makefile variables anymore.

BTW: update of bazarr LGTM

**Comment by smaarn** [comment]
> @smaarn in preparation for #6255 can you please update the spk/bazarr/Makefile and replace `DEPENDS = cross/$(SPK_NAME)` by `DEPENDS = cross/bazarr`?
> 
> For #6255 it will be mandatory that none of the DEPENDS* definitions use makefile variables anymore.
> 
> BTW: update of bazarr LGTM

@hgy59 done in https://github.com/SynoCommunity/spksrc/pull/6164/commits/50e80d1379b773fa38311484a82bc838356068db

**Review by hgy59 — APPROVED** [review]
LGTM

IMHO we can create the qoriq package later, when #6297 is fixed

**Comment by mreid-tt** [comment]
@smaarn, I've done a re-base for you which fixes the qoriq build. It should be good to merge now.

**Comment by hgy59** [comment]
@mreid-tt please never rebase a foreign branch!

It is always enough to merge the upstream master into such a branch.
Otherwise it is very hard for the owners to proceed with their unpushed changes.

**Pull request merged**
