### PR TITLE
Update Tvheadend to 4.2.1 (Release)

### PR DESCRIPTION
**Pull request by m4tt075**
## Motivation
`Tvheadend 4.2.1` has been released. It is a substantial improvement over our current stable 3.4 and beta 4.0 release versions in terms of stability, usability and feature set. This PR comprises:
- Update of the spksrc Tvheadend package to latest release version 4.2.1
- Addition of cross package for and utilization of `uriparser`
- Addition of cross package for `libdvbcsa`, enabling dvbcsa support
- Addition of cross package for `dvb_apps`, enabling dvben50221 support
- Cross package `libhdhomerun` is bumped to latest 
- Addition of cross package for `ffmpeg-3.2.4` to fix compilation issues 
- Compilation fixes for PowerPC architectures
- Potentially compatibility with DSM6.x systems (unconfirmed as I cannot test it)

The `ffmpeg-3.2.4` cross package had to be added as building against the existing `ffmpeg` cross package failed. However, PR #2620 fixes these issues. Once it is merged, the `ffmpeg-3.2.4` cross-package can be removed again. 

This PR replaces PR #2697, which prepared this update. 

## Of Note
This PR primarily just compiles ideas and solutions of others, most notably...
- @jdierkse: Many of the improvements and changes here actually stem from the `tvheadend-testing` work in [his spksrc fork](https://github.com/jdierkse/spksrc). 
- @GoodOmens83: His PR #2189 was the starting point for me
- @perexg: Solving and upstreaming PPC compilation fixes. By the way, he has also been the key developer for Tvheadend in the last couple of months. Thank You!
- @Dr-Bean: DSM6 compatibility and solving user privilege issues.

@cytec kindly provided useful advice in preparing this PR.

## Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully
- [x] Potentially fixing compatibility issues with DSM6 (untested)

## Outlook (beyond the scope of this PR)
- [ ] Remove `ffmpeg-3.2.4` cross package and link to available `ffmpeg` cross-package once #2620 is merged

### CODE REVIEW

**Comment by m4tt075** [comment]
I'm building `all-supported` now, but may take some time with Virtualbox on an outdated HSW laptop... ;-)

@Dr-Bean, @cytec, @KaraokeStu: Would appreciate your review and - if at all possible - some testing. I'm unfortunately limited to testing on one evansport-5.2 device...

**Comment by m4tt075** [comment]
Buildrule `all-supported` succeeded, but new install is not working well. Issues with user creation. *sigh*
Back to [WIP] status.

**Comment by m4tt075** [comment]
I have cherry-picked @Dr-Bean's commit updating tvheadend on the dsm6 branch. Looks better, as the user is correctly created and appearing in /etc/passwd (not in /etc/shadow though!). User priviliges seem ok. Still, the user credentials entered during the installation process, are not accepted as valid by the WebIF later. The problem can be circumvented by temporarily adding the `-C` option to the TVH start command in the start-stop-script, but definitely not a viable solution for end users. This needs to work properly. Any advice welcome!

**Comment by G1zm0** [comment]
Tracking this 👍

**Comment by m4tt075** [comment]
Closing in on the issue, but not yet solved:
- The accesscontrol system changed within TVH. @jdierkse has found a method to create valid accesscontrol and passwd file pairs in his published spks, which I resemble here. The method to create these files introduced in the latest commit works correctly (tested!).
- However, there are issues with file permissions. TVH rejects correct credentials because the file permissions of the accesscontrol and passwd files are not correct.  I know this, because when I ssh into the Synology and `chmod 777` those files manually, the credentials are accepted.
- Now the weird things: A manual `chmod 700` is NOT sufficient. Neither does it work if I replace the `chmod 700` (which actually should work) by a `chmod 777` in the `installer.sh`script. The only way is to ssh into the box again and `chmod 777` manually!

I believe there is something wrong with the busybox `adduser` command. Even if we add `users` as group via the `-G` option, the new user is not correctly added to that group or at least not inheriting standard group privileges.  

@Dr-Bean, @cytec, @KaraokeStu: Do you understand this and/or do you know a workaround? This is really weird. I'm not running DSM6.x. I'm still on the latest update of DSM5.2. Again, any help appreciated!

**Comment by m4tt075** [comment]
OK. I followed @maxrogers' approach in #2746, which fixes the user permission issue on my DSM 5.2 system. All the fixes might(!) well have the additional benefit of establishing DSM6.x compatible as well, but I cannot confirm as I cannot test it. 

[WIP] label removed again. PR description updated. From my perspective, ready for review. In the meantime, please test and report back. Positive as well as negative feedback will be appreciated.

**Comment by maxrogers** [comment]
@m4tt075 @Dr-Bean deserves the credit for solving DSM6 user permission issues. I just copied his work from the DSM6 branch here: https://github.com/SynoCommunity/spksrc/commit/c4e53f04ce0757c5ad565bb30dee026838da0475

**Comment by m4tt075** [comment]
Thank You, @maxrogers. 
👍 

Credits adapted...

**Comment by m4tt075** [comment]
Testbuilds for all architectures can be downloaded from [here](https://www.dropbox.com/sh/vpbt4l4j4x2rkzy/AABXF5HOBU359QJWKzRlPGgWa?dl=0).

**Comment by KaraokeStu** [comment]
Could you please remove the test builds, just to ensure that everyone gets the same versions? 

I'll get this merged now and built tomorrow.

**Comment by m4tt075** [comment]
Thanks, @KaraokeStu.

**Comment by m4tt075** [comment]
@KaraokeStu: Just realized that the repo still contains the old 4.0.9 beta version. Do you know when it will be replaced by 4.2.1?

**Comment by KaraokeStu** [comment]
Hi, I've just checked the logs and the publish failed with an error "Empty conf folder"

**Comment by m4tt075** [comment]
Hi @KaraokeStu:
Thanks for following up, but I cannot reproduce:
- The `privilege` file is contained in the `conf` folder in this PR. 
- I have justed fetched upstream (with the merged PR) and cross-compiled again. No problems with creating the spk package.
- I have also manually unpacked the resulting spk to double-check: `conf` folder exists and contains the `privilege` file. 
Any further hints from the logs or ideas about what could go wrong here?

**Comment by KaraokeStu** [comment]
I believe it may be just publishing the spk that is the problem, in which case we'll need the help of @drbean

**Comment by G1zm0** [comment]
@Dr-Bean or @Diaoul any news on the publication?
I would like to use the latest version.
Keep up the good work!

**Comment by m4tt075** [comment]
@G1zm0: Seems they are busy. But you can compile yourself. It's really easy. Feel free to PM me as M4tt0 via the Kodi forum if you need help...

**Comment by mastacheata** [comment]
@m4tt075 I don't use Kodi and when I register on the forums I can't send private messages there for unknown reasons (probably because I have no posts on the forums that would seem spammy)
Would you be available by any other means? (i.e. the synology forums for example or by email?)

Building from source fails at the openssl build step with lots (6000 lines or so) of undefined references. No idea why tvheadend needs it's own OpenSSL, though? It's not even a new OpenSSL 1.0.2k is the same that's already installed. I tried installing libssl-dev in my dev environment, but it's already there and up to date.

**Comment by m4tt075** [comment]
@mastacheata I'm on synology-forum.de (`m4tt0`). But before we continue spamming this PR, no further non-development-related requests here, please. Just open an issue instead, ok? Thanks.

**Pull request merged**
