### PR TITLE
ruby: Upgrade ruby to v3.1.0

### PR DESCRIPTION
**Pull request by miry**
## Description

Upgrade ruby to latest stable release v3.1.0.

https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

## Checklist

- [x] New installation of package completed successfully
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### Synology RS820+

DSM: 7.0
Arch: denverton

```shell
$ uname -a
Linux nas 4.4.180+ #42218 SMP Mon Oct 18 19:26:24 CST 2021 x86_64 GNU/Linux synology_denverton_rs820+

$ sudo synopkg install ~/work/ruby_denverton-7.0_3.1.0-10.spk 
Password: 
{"error":{"code":0},"results":[{"action":"upgrade","beta":false,"betaIncoming":false,"error":{"code":0},"finished":true,"installReboot":false,"installing":true,"language":"enu","last_stage":"started","package":"ruby","packageName":"Ruby","pid":2567,"scripts":[{"code":0,"message":"","type":"stop"},{"code":0,"message":"","type":"preupgrade"},{"code":0,"message":"","type":"preuninst"},{"code":0,"message":"","type":"postuninst"},{"code":0,"message":"","type":"preinst"},{"code":0,"message":"","type":"postinst"},{"code":0,"message":"","type":"postupgrade"},{"code":0,"message":"","type":"start"}],"spk":"/var/services/homes/user/work/ruby_denverton-7.0_3.1.0-10.spk","stage":"installed_and_started","status":"running","success":true,"username":""}],"success":true}

$ /usr/local/bin/ruby --version
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]

$ /usr/local/bin/irb 
> require "open-uri"; URI.open("https://www.ruby-lang.org/") {|f| f.each_line {|line| p line} }
```

### CODE REVIEW

**Review by th0ma7 — APPROVED** [review]
Looks good, lets wait for the github-action run to complete

**Comment by miry** [comment]
@th0ma7it seems ready to merge.

**Comment by th0ma7** [comment]
Indeed looking good!  Thnx for reminder and most importantly thnx for your contribution!  Merging then I'll be publishing in the coming day.

**Comment by th0ma7** [comment]
Now published, thnx again for your contribution!

**Pull request merged**
