### PR TITLE
mosquitto: update to 1.6.12

### LINKED ISSUE #4044: Mosquitto package not available through the package center
### Setup
_Package Name:_ Mosquitto
_Package Version:_  v1.4.14-9 

_NAS Model:_ DS720+
_NAS Architecture:_ x86-64
_DSM version:_ 6.2.3

### Expected behavior
Show the Mosquitto package as an available package

### Actual behavior
Mosquitto package not showing up in the package center
All other packages are showing up.
When checking my old DS215J the package is just showing up, is this maybe because of a different architecture (215J runs on ARM)?

### PR DESCRIPTION
**Pull request by ymartin59**
_Motivation:_  Update and publish for geminilake
_Linked issues:_  #4044, #3225

### Checklist
- [X] Build rule `all-supported` completed successfully
- [X] Package upgrade completed successfully
- [X] New installation of package completed successfully

### CODE REVIEW

**Comment by hgy59** [comment]
@ymaring maybe we should first build and publish mosquitto version 1.6.10 as this is the least one that supports ppc853x,

**Comment by ymartin59** [comment]
@hgy59 Thanks for your help. You did a great job... my draft was far not enough but I have been stopped in my testing.

**Comment by hgy59** [comment]
@ymartin59 do you benefit from the artifacts created by the github build actions?
For this we need a solution to skip packages that are expected to fail (ffsync in this PR).

**Comment by ymartin59** [comment]
@hgy59 No, I rebuild locally after merge and test on xpenology before uploading and activating version in repository.

**Comment by ymartin59** [comment]
@hgy59 Simply does not build:
```
-- Compiled with LWS_WITH_DIR and LWS_WITH_DIR
-- CMAKE_TOOLCHAIN_FILE=''
Git commit hash: pre-dsm6-550-gc8e9dda4
Compiling with SSL support
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "1.1.1d")
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.13/Modules/FindOpenSSL.cmake:412 (find_package_handle_standard_args)
  CMakeLists.txt:1723 (find_package)


-- Configuring incomplete, errors occurred!
See also "/spksrc/spk/mosquitto/work-x64-6.1/libwebsockets-3.2.2/build/CMakeFiles/CMakeOutput.log".
See also "/spksrc/spk/mosquitto/work-x64-6.1/libwebsockets-3.2.2/build/CMakeFiles/CMakeError.log".
```

**Comment by hgy59** [comment]
> -- Configuring incomplete, errors occurred!
> See also "/spksrc/spk/mosquitto/work-x64-6.1/libwebsockets-3.2.2/build/CMakeFiles/CMakeOutput.log".
> See also "/spksrc/spk/mosquitto/work-x64-6.1/libwebsockets-3.2.2/build/CMakeFiles/CMakeError.log".


But the gh build action succeeded to build (only ffsync failed). 

The same on my local clone. It builds successfully with this docker image:
`synocommunity/spksrc                    latest              73698c0751c0        3 months ago        877MB`

Something must be different in your build environment.

parts of configure libwebsockets:
```
-- Compiled with LWS_WITH_DIR and LWS_WITH_DIR
-- The C compiler identification is GNU 4.9.3
-- Check for working C compiler: /spksrc/toolchains/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /spksrc/toolchains/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_TOOLCHAIN_FILE=''
-- Found Git: /usr/bin/git
fatal: No names found, cannot describe anything.
Git commit hash:
-- Performing Test LWS_HAVE_inline
-- Performing Test LWS_HAVE_inline - Success

...

-- Performing Test LWS_GCC_HAS_TYPE_LIMITS - Success
Compiling with SSL support
-- Found OpenSSL: /spksrc/spk/mosquitto/work-x64-6.1/install/var/packages/mosquitto/target/lib/libcrypto.so (found version "1.0.2u")
OpenSSL include dir: /spksrc/spk/mosquitto/work-x64-6.1/install/var/packages/mosquitto/target/include
OpenSSL libraries: /spksrc/spk/mosquitto/work-x64-6.1/install/var/packages/mosquitto/target/lib/libssl.so;/spksrc/spk/mosquitto/work-x64-6.1/install/var/packages/mosquitto/target/lib/libcrypto.so
-- Looking for openssl/ecdh.h
-- Looking for openssl/ecdh.h - found
```

**Comment by ymartin59** [comment]
@hgy59 I probably have explanation: I have rebased branch to get "fixed" openssl but its install command fails to provide pkgconfig requires by CMake: https://github.com/SynoCommunity/spksrc/pull/4191/commits/cbda607efcccafc1781cf4a80a14316012426e21

**Comment by hgy59** [comment]
I hope this fixes #4210 , at least the compiler flags are now fixed with this small adjustment.
Error might be introduced by some framework changes...

**Comment by hgy59** [comment]
@ymartin59 as @arnebjarne has [confirmed](https://github.com/SynoCommunity/spksrc/issues/4210#issuecomment-706548959) that #4210 is fixed, I removed the respective labels here.

May a propose to merge this immediately to have a working version of openssl v1.0.1u on the master branch?

After that, we can rebase #4155 (and #4195, and maybe other PRs) and hopefully merge #4155 soon.

**Comment by arnebjarne** [comment]
Hi hgy59.

SPK_REV = 10

Since it is already released (I got the package via DSM). Itsnt it better to bump it to 11, so people who have installed v10 get an update?

Br,
Bjarne

________________________________
Fra: hgy59 <notifications@github.com>
Sendt: Sunday, October 11, 2020 12:45:19 AM
Til: SynoCommunity/spksrc <spksrc@noreply.github.com>
Cc: Bjarne Saltbaek <arnebjarne72@hotmail.com>; Mention <mention@noreply.github.com>
Emne: Re: [SynoCommunity/spksrc] mosquitto: update to 1.6.12 (#4191)


Merged #4191<https://github.com/SynoCommunity/spksrc/pull/4191> into master.

**Comment by hgy59** [comment]
@arnebjarne good catch, I didn't realize the version 1.6.12-10 was already pushed to the repo.

Anyway the current version is not ready to push, as the update shall include openssl 1.1.1with #4155 (and libwebsockets is currently failing to build there).

**Comment by hmueller01** [comment]
I installed 1.6.12-10 on my RS816 (Armada 385 CPU, DSM 6.2.3-25426 Update 2) and had same problem with websockets. Commenting out the use of Websockets in the config solves this problem (which is hopefully fixed with #4210) and mosquitto starts without errors. But unfortunately the daemon does not run in background. Switching back to 1.4.14-9 make mosquitto work again. Not sure if the fix #4210 helps something in my case ...

```
Starting mosquitto command /volume1/@appstore/mosquitto/sbin/mosquitto -d -c /volume1/@appstore/mosquitto/var/mosquitto.conf 
1602337331: Loading config file /usr/local/mosquitto/etc/mosquitto/conf.d/local.conf
```

`> ps aux|grep mosquitto` gives not result.

**Comment by arnebjarne** [comment]
> 
> 
> @arnebjarne good catch, I didn't realize the version 1.6.12-10 was already pushed to the repo.
> 
> Anyway the current version is not ready to push, as the update shall include openssl 1.1.1 with #4155 (update done on the branch with [46a7931](https://github.com/SynoCommunity/spksrc/commit/46a793173cd52f0a04dc208011333ed2f13e1f94)).

Hmm strange. I can compile mosquitto 1.6.12-11 with openssl 1.1.1.h.

How:
git clone https://github.com/SynoCommunity/spksrc.git
cd spksrc/
git remote add openssl https://github.com/th0ma7/spksrc.git
git merge openssl/openssl-102u
cd spk/mosquitto/
make arch-rtd1296

works for me :)

**Comment by hgy59** [comment]
> Hmm strange. I can compile mosquitto 1.6.12-11 with openssl 1.1.1.h.

@arnebjarne sorry, I removed the comment that libwebsocket fails to build (probably was an issue on another branch I am currently working).

**Pull request merged**
