### PR TITLE
Dotnet runtime: remove unsupported archs

### PR DESCRIPTION
**Pull request by hgy59**
## Description

Remove unsupported archs from ARMv7 archs.
This needs a small update in the INFO file creation.

Follow up of #5300

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [ ] New Package
- [ ] Package update
- [x] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
This update allows to remove unsupported from generic archs in the package INFO file.

@publicarray this is probably useful for jellyfin package, since all dotnet dependent packages do not support all ARMv7 archs.

**Comment by hgy59** [comment]
Considering #5283 armadaxp might be supported.

**Comment by publicarray** [comment]
Good find @ta264 please let us know how your build goes. looking forward to the results

@hgy59 Looks good to me.

**Comment by publicarray** [comment]
Since .net 6.0 raised the required system libs versions, you can basically drop all of DSM 6 support and comcerto, unfortunately. AFAIK, only DSM7.0 and above contains the libraries necessary. (@ta264 https://discord.com/channels/732558169863225384/905064261984845836/1004134443755241582)

**Comment by publicarray** [comment]
Thanks @hgy59, for compiling the unsupported arches, unfortunately I think this information is only valid for .NET 5.x and .NET 6.x has made it worse 😢

**Pull request merged**
