### PR TITLE
Transmission: Update to 4.0.4

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This PR is to update to the bugfix-only release of Transmission v4.0.4.

Fixes # 

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by hgy59** [comment]
oos, I am working on this, including the empty blocklist on ARMv7...

**Comment by mreid-tt** [comment]
> oops, I am working on this, including the empty blocklist on ARMv7...

sorry, I didn't see any other pull requests for this and there was a request from the community on Discord.

**Comment by hgy59** [comment]
@mreid-tt so far I didn't create any PR.
But soon I will. just found a solution for the ARMv7 blocklist issue ❗

**Comment by mreid-tt** [comment]
> @mreid-tt so far I didn't create any PR. But soon I will. just found a solution for the ARMv7 blocklist issue ❗

Oh! Nice! Would the plan be to push an update for the same version or should I un-publish this version?

**Comment by hgy59** [comment]
@mreid-tt it is always a bad idea to draw back published versions.

I will increase the SKP_REV and when the fix is published, we can remove the previous version.

**Comment by mreid-tt** [comment]
> @mreid-tt it is always a bad idea to draw back published versions.
> 
> I will increase the SKP_REV and when the fix is published, we can remove the previous version.

@hgy59, there is a new [version 4.0.5](https://github.com/transmission/transmission/releases/tag/4.0.5 ) which also resolves an issue raised in  https://github.com/SynoCommunity/spksrc/issues/5867. Shall I hold off making a PR for you to include your fix for the ARMv7 blocklist issue?

**Comment by hgy59** [comment]
@mreid-tt feel free to create an update PR for transmission 4.0.5. (currently offline of my dev env for a few days).

If you don't have a 32-bit arm device, you might get feedback by affected users of #5685 to ensure the fix is still working.

_I don't know whether the upstream issue https://github.com/transmission/transmission/issues/5966 is completely fixed and integrated in the current release, but it is worth testing anyway_

**Comment by mreid-tt** [comment]
> If you don't have a 32-bit arm device, you might get feedback by affected users of #5685 to ensure the fix is still working.
> 
> _I don't know whether the upstream issue [transmission/transmission#5966](https://github.com/transmission/transmission/issues/5966) is completely fixed and integrated in the current release, but it is worth testing anyway_

@hgy59, thanks for the guidance. I've opened PR #5956 which should include the updated version. I've removed the patches you introduced previously (I hope there is nothing else to remove). I'll also reach out to the previously affected users for feedback on the blocklist issue.

**Pull request merged**
