### PR TITLE
glib build fix with libiconv

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

MPD update+build fix and glib + libiconv fix

Relates to #6040

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
@th0ma7 I have #5652 in progress.

It already builds for DSM 7+ only.
Is there anything missing in #5652 beside the update from 0.23.12 to 0.23.15?

**Comment by th0ma7** [comment]
I wasn't intending to update `mpd` at first but focus was to solve `glib` use case.  It turned out that `mpd` needed attention to get it all to build properly.

Anyhow, I can certainly remove the mpd portion of this PR.  My focus is to fix glib for https://github.com/SynoCommunity/spksrc/pull/6040 to limiting massive rebuild time.  Are you ok with me merging only the glib bits then?

**Comment by hgy59** [comment]
> Anyhow, I can certainly remove the mpd portion of this PR. My focus is to fix glib for #6040 to limiting massive rebuild time. Are you ok with me merging only the glib bits then?

Yes that's ok. I will wait with #5652 until you merged the glib bits...

**Comment by th0ma7** [comment]
> Yes that's ok. I will wait with #5652 until you merged the glib bits...

@hgy59 done!

**Comment by hgy59** [comment]
@th0ma7 why does the build of mpd (without update) fail?

**Comment by th0ma7** [comment]
So in one case you get glib failing due to libiconv (issue that is resolved with newer glib).  In turn, on the faulty glib, when fixing build by enforcing external libiconv it ends up making mpd to fail as well.  Again fixed with newer mpd.

**Pull request merged**
