### PR TITLE
framework: fix TC_OS_MIN_VER declaration

### PR DESCRIPTION
**Pull request by ymartin59**

### CODE REVIEW

**Comment by ymartin59** [comment]
@Safihre Looks like it has expected result. INFO now contains only `os_min_ver` with 6.1 toolchains.

**Comment by ymartin59** [comment]
"os_min_ver" is not know yet by `spkrepo`... so even if PR fixes INFO content, I guess generated packages are no longer deliverable to DSM... @publicarray

**Comment by ymartin59** [comment]
Just confirmed:
```
===>  Creating /spksrc/spk/dante-sockd/work-rtd1296-6.1/scripts/start-stop-status
===>  Preparing DSM Wizards
src/wizard/install_uifile_fre
src/wizard/install_uifile
/spksrc/spk/dante-sockd/work-rtd1296-6.1/WIZARD_UIFILES/install_uifile_fre
/spksrc/spk/dante-sockd/work-rtd1296-6.1/WIZARD_UIFILES/install_uifile
(cd /spksrc/spk/dante-sockd/work-rtd1296-6.1 && tar cpf /spksrc/spk/dante-sockd/../../packages/dante-sockd_rtd1296-6.1_1.4.2-1.spk --group=root --owner=root package.tgz INFO scripts PACKAGE_ICON.PNG PACKAGE_ICON_256.PNG WIZARD_UIFILES)
http --verify=no --auth : POST https://api.synocommunity.com/packages @/spksrc/spk/dante-sockd/../../packages/dante-sockd_rtd1296-6.1_1.4.2-1.spk
HTTP/1.1 422 UNPROCESSABLE ENTITY
Connection: keep-alive
Content-Length: 37
Content-Type: application/json
Date: Thu, 05 Jul 2018 20:49:39 GMT
Server: nginx/1.4.6 (Ubuntu)

{
    "message": "Missing INFO: firmware"
}

make[1]: Leaving directory '/spksrc/spk/dante-sockd'
```

**Comment by ymartin59** [comment]
I try to fix before my vacations... but it will be really short. https://github.com/SynoCommunity/spkrepo/pull/20

**Comment by publicarray** [comment]
Oh I didn't realise how far this rabbit hole goes... Looks like you got a fix already. 👍

**Comment by Safihre** [comment]
Great work @ymartin59 !
Let me know if I can test something.

**Pull request merged**
