### PR TITLE
update jellyfin 10.8.8

### PR DESCRIPTION
**Pull request by stevenliuit**
## Description
update jellyfin version to 10.8.8

## Checklist

- [x] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by tvinhas** [comment]
What's missing for this to be merged?

**Comment by stevenliuit** [comment]
> What's missing for this to be merged?



> What's missing for this to be merged?

No shortage

**Comment by stevenliuit** [comment]
@hgy59 please help！

**Comment by hgy59** [comment]
Is this ready for merge? Did anybody test it?

**Comment by stevenliuit** [comment]
> merge

i merge this project and test success！

**Comment by hgy59** [comment]
> i merge this project and test success！

please update the check list at the top.

**Comment by CarstenG2** [comment]
How to configure it after the install? Need to connect it to my tvheadend for live TV, But te web-GUI has no config-section.

**Comment by stevenliuit** [comment]
> How to configure it after the install? Need to connect it to my tvheadend for live TV, But the web-GUI has no config-section.

By default, when you click Open in the APP in DSM, a URL with port 8096 will be opened.

**Comment by CarstenG2** [comment]
I dont have an admin-section in the web-Gui. Is that by design or just me?Von meinem iPhone gesendetAm 12.01.2023 um 16:00 schrieb Steven ***@***.***>:﻿

How to configure it after the install? Need to connect it to my tvheadend for live TV, But the web-GUI has no config-section.

By default, when you click Open in the APP in DSM, a URL with port 8096 will be opened.

**Comment by stevenliuit** [comment]
> I dont have an admin-section in the web-Gui. Is that by design or just me?Von meinem iPhone gesendetAm 12.01.2023 um 16:00 schrieb Steven ***@***.***>:﻿ How to configure it after the install? Need to connect it to my tvheadend for live TV, But the web-GUI has no config-section. By default, when you click Open in the APP in DSM, a URL with port 8096 will be opened. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

If the browser can open the application on port 8096 after the dsm installation is complete, then please ask the official how to do it when watching jellyfin on TV.

**Comment by anthonylavado** [comment]
@stevenliuit We've just released a 10.8.9 version today, but 10.8.8 is still good as an update. Could you update the checklist in your first post so that the admins can take a look at this?

thank you!

**Comment by mxwi** [comment]
Can someone merge the request?

**Comment by hgy59** [comment]
> Can someone merge the request?

Still waiting for update to 10.8.9

**Comment by mxwi** [comment]
Ok - I accept that, but I don't really understand it.
We have a finished and working build/pr for 10.8.8. Why not just merge it and wait for someone to update it to another version in a few days/weeks?

If one were to follow through with your method, there might never be an up-to-date version.

Maybe I am wrong. I would love to hear your thoughts on this.

greetz

**Comment by mxwi** [comment]
Why did you close the PR? And also the other two?

https://github.com/SynoCommunity/spksrc/pull/5468
https://github.com/SynoCommunity/spksrc/pull/5472

**Pull request closed without merging**
