### PR TITLE
native/yasm: use github release & cross/libsodium: update digests

### PR DESCRIPTION
**Pull request by publicarray**
See: https://github.com/SynoCommunity/spksrc/pull/4951#discussion_r746493700

Just in-case the cert expires again

### Checklist
- [x] native build

### CODE REVIEW

**Comment by th0ma7** [comment]
Why is it failing?  This seems like a trivial PR...

**Comment by th0ma7** [comment]
@publicarray I suggest we simply merge this and start using github by default.  Are you ok with this?

**Comment by publicarray** [comment]
I used minisign to verify the signature of libsodium :+1:

**Comment by publicarray** [comment]
@th0ma7 Thank you!

**Comment by publicarray** [comment]
Arch uses  `libsodium-1.0.18.tar.gz` not `libsodium-1.0.18-stable.tar.gz`. maybe that is part of the problem we are using the wrong file?. https://github.com/archlinux/svntogit-packages/blob/packages/libsodium/trunk/PKGBUILD

**Comment by th0ma7** [comment]
I've switched to `-stable` a few weeks ago due to build issues elsewhere in the python dreamworld :)

**Comment by publicarray** [comment]
https://github.com/jedisct1/libsodium/discussions/1124#discussioncomment-1628482

**Comment by publicarray** [comment]
Based on he's response I think be should be using `libsodium-1.0.18.tar.gz`

**Pull request merged**
