### PR TITLE
added dsm groups for various packages

### PR DESCRIPTION
**Pull request by cytec**
as discussed here: https://github.com/SynoCommunity/spksrc/pull/1618

affected packages:

`sc-media`:

	couchpotatoserver
	couchpotatoserver-custom
	flexget
	headphones
	headphones-custom
	lazylibrarian
	sickbeard
	sickbeard-custom
	sonarr

`sc-download`:

	deluge
	nzbget
	nzbget-testing
	transmission
	sabnzb
	rutorrent

@Dr-Bean @Diaoul any thoughts?

EDIT: Sickrage changes will come in SickRage PR :)

### CODE REVIEW

**Comment by Dr-Bean** [comment]
Seems to me the addition of `syno_group_create` to `preupgrade` isn't needed, right?

**Comment by Dr-Bean** [comment]
...and the descriptions still say `sync group` ;) Other than that, quick turnaround :)

**Comment by cytec** [comment]
@Dr-Bean idk if `postinst` is executed when the user updates an spk so i thought i'd put it in there as well

**Comment by Dr-Bean** [comment]
A package essentially is always uninstalled/reinstalled during an update. `preupgrade` allows you to do stuff before the uninstall, e.g. backup files.
Looked it up: page 35 on my copy of the developers guide shows which steps are done during a package upgrade.

**Comment by cytec** [comment]
so should i remove `syo_create_group` from `preupgrade` then? :)

**Comment by Dr-Bean** [comment]
Well, my experience would say yes, remove it. Otoh, the dev guide has been wrong before, so the best thing to do is test it :P 
I might give it a go during the week: reviewing code online is easy enough to do in between other things, testing stuff less so ;)

**Comment by cytec** [comment]
ok, so i'll leave it in there till you tested it, removing it if it's not needed is done quicker then readding it ;)

**Comment by Diaoul** [comment]
@Dr-Bean is right, *inst and *uninst are both executed during upgrade.

**Comment by hurik** [comment]
Can i also add this to btsync now?

**Comment by Dr-Bean** [comment]
@cytec It works without the `preupgrade` addition ;) 
In the interest of releasing new packages, it would need a version bump and changelog (`Group sc-xyz added to allow setting permissions via DSM GUI` or something to that effect)

Question: should we add an install wizard to explain how to use that group? We don't necessarily need an upgrade wizard imo, but that can have the same content if we do.

@hurik Yes, if you can reuse the code in this PR, go ahead and create a PR. Maybe wait until we've fleshed out the implementation details (or, if you have an answer to my question above, go ahead)

**Comment by Diaoul** [comment]
Applications users will be part of next major release of DSM from what I heard. :ear:

**Comment by Dr-Bean** [comment]
With the PR for NZBget (#1728) being ready to merge, I think I'll merge this PR in at the same time (and add a mention of it in the NZBget changelog). We can do the other packages little-by-little, depending on time etc.

When the application users are available in DSM6, I believe a working migration path is to add the newly created application users to the same group, preserving existing permissions for existing installations.

**Comment by Diaoul** [comment]
Seems good

**Pull request merged**
