### PR TITLE
Update domoticz to rev 2284.

### PR DESCRIPTION
**Pull request by tomy666x**

### CODE REVIEW

**Comment by Diaoul** [comment]
You tested this I assume?

**Comment by tomy666x** [comment]
I compiled it for my DS213j (armada370) and installed it.
I launched the package and everything seems to work correctly.

**Comment by LouiS22** [comment]
+1, works perfectly

**Comment by gkroone** [comment]
I have made some local changes to the openzwave branch of decypher in order to compile the latest revision of Domoticz, but I am new to programming and github. I'd like some guidance on how to publish my changes as what I read on github manuals it states to always branch off the master repository, but I actually started off from the openzwave branch due to the changes in there needed to compile later revisions of domoticz. I mainly need the latest revisions for the RFLink functionalilty so I compiled my own. up to r2362 the openzwave branch needed almost no adjustments other than updating the revision numbers in the MakeFiles, and I now managed to compile r2383 with python adjustments, and also added a udev rule file to set permissions on /dev/ttyACM* to 666.

**Comment by LouiS22** [comment]
@gkroone could you please send me them? I'm also struggling on the compile above 2362 :(

**Comment by gkroone** [comment]
I've manually updated the files on my fork of #1604 

My changes should be visible here:
https://github.com/gkroone/spksrc/commits/openzwave/

**Comment by LouiS22** [comment]
@gkroone not working, even after manually downloading your fork. It has something to do with the python support presented at 236x. It drives me crazy :(

**Comment by gkroone** [comment]
Sorry, i should have updated you on this. I've been testing my changes by compiling from scratch and hitting same issue over and over, making small changes to the domoticz makefile,  but it looks like i can't get it to work unless i change the makefile of cross/boost too. I've filed a separate issue on it here: #1648 you can find some more pointers there to get it compiled. My aim is to find a proper fix for the issue but assuming you're stuck on messages regarding missing pyconfig.h, getting it compiled is as simple as editting the file work-x86-5.1/boost_1_53_0/tools/build/v2/user-config.jam

As this is a bit off topic here, best we move this discussion to #1648

**Pull request merged**
