### PR TITLE
imagemagick: fix and update

### LINKED ISSUE #4729: [ImageMagick] identify: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/702.
### Setup
_Package Name:ImageMagick
_Package Version:7.0.11-5

_NAS Model:DS916+
_NAS Architecture:x86_64
_DSM version:_DSM 7.0-41890

```
$ /usr/local/bin/identify 2015-07-31_Blaireau_8389.jpg
identify: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/702.
identify: UnableToOpenModuleFile '/var/services/homes/bruno/.config/ImageMagick/jpeg.la': No such file or directory @ warning/module.c/GetMagickModulePath/823.
identify: NoDecodeDelegateForThisImageFormat `JPEG' @ error/constitute.c/ReadImage/572.
```

```
/usr/local/bin/identify IMG_0636.heic
identify: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/702.
identify: UnableToOpenModuleFile '/var/services/homes/bruno/.config/ImageMagick/heic.la': No such file or directory @ warning/module.c/GetMagickModulePath/823.
identify: NoDecodeDelegateForThisImageFormat `HEIC' @ error/constitute.c/ReadImage/572.

```

```
$ /usr/local/bin/identify -debug configure -list configure
2021-07-10T12:22:56+00:00 0:00.001 0.000u 7.0.11 Configure identify[4137]: utility.c/ExpandFilenames/971/Configure
  Command line: /usr/local/bin/identify {-debug} {configure} {-list} {configure}
2021-07-10T12:22:56+00:00 0:00.001 0.000u 7.0.11 Configure identify[4137]: configure.c/GetConfigureOptions/675/Configure
  Searching for configure file: "/usr/local/etc/ImageMagick-7/configure.xml"
2021-07-10T12:22:56+00:00 0:00.001 0.000u 7.0.11 Configure identify[4137]: configure.c/GetConfigureOptions/675/Configure
  Searching for configure file: "/usr/local/share/ImageMagick-7/configure.xml"
2021-07-10T12:22:56+00:00 0:00.001 0.000u 7.0.11 Configure identify[4137]: configure.c/GetConfigureOptions/675/Configure
  Searching for configure file: "/var/packages/imagemagick/target/lib/ImageMagick-7.0.11//config-Q16HDRI/configure.xml"
2021-07-10T12:22:56+00:00 0:00.001 0.000u 7.0.11 Configure identify[4137]: configure.c/GetConfigureOptions/675/Configure
  Searching for configure file: "configure.xml"
2021-07-10T12:22:56+00:00 0:00.001 0.000u 7.0.11 Configure identify[4137]: configure.c/GetConfigureOptions/675/Configure
  Searching for configure file: "/var/services/homes/bruno/.config/ImageMagick/configure.xml"

Path: [built-in]

Name                  Value
-------------------------------------------------------------------------------
DELEGATES             bzlib fontconfig freetype heic jng jp2 jpeg lcms ltdl lzma png tiff webp wmf xml zlib
FEATURES              Cipher DPC HDRI Modules OpenMP(4.5)
MAGICK_TEMPORARY_PATH /var/services/homes/bruno/tmp
NAME                  ImageMagick
QuantumDepth          Q16
identify: UnableToOpenConfigureFile `configure.xml' @ warning/configure.c/GetConfigureOptions/702.
```

### PR DESCRIPTION
**Pull request by hgy59**
_Motivation:_  fix imagemagic load modules and include configure.xml to provide build information
_Linked issues:_  closes #4729

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by miry** [comment]
Tested 7.0.11-6 version on RS820+:

```shell
$ /usr/local/bin/magick identify -verbose test.heic
....
Success!

$ /usr/local/bin/magick identify -format '%[EXIF:DateTimeOriginal]' test.heic
2020:04:29 12:51:08
```

**Comment by hgy59** [comment]
> Tested 7.0.11-14 version on RS820+: built for denverton-7.0

Thanks for testing!
would you mind to test the updated version 7.1.0?

The only issue i see, is that the packaged fonts are not listed in the configuration

```
magick -list font
```

does not find any font yet.
but it should list the packaged urw-base35 and windows fonts.

I can see a naming missmatch (urw-base35) and a format missmatch (ttf vs afm/pfb)
we probably need a script to update the type-{font}.xml files at build or installation time.
Do you have some knowledge about imagemagic fonts?

**Comment by miry** [comment]
>  Do you have some knowledge about imagemagic fonts?

Never used for fonts. 

>  would you mind to test the updated version 7.1.0?

run localy build process. it would take some time.

**Comment by miry** [comment]
Tested latest commit:

```shell
$ /usr/local/bin/identify --version
Version: ImageMagick 7.1.0-19 Q16-HDRI x86_64 2021-12-18 https://imagemagick.org

$ /usr/local/bin/identify -verbose /volume1/photo/test.heic 
Image:
  Filename: /volume1/photo/test.heic
  Format: HEIC (High Efficiency Image Format)
  Mime type: image/heic
  Class: DirectClass
  Geometry: 3088x2316+0+0
  Resolution: 72x72
...

$ /usr/local/bin/identify -format '%[EXIF:DateTimeOriginal]' /volume1/photo/test.heic 
2019:07:15 12:49:23
```

Looks good to me.

**Comment by hgy59** [comment]
@miry thanks for the feedback.
next I am trying to build librsvg to solve #3881.

**Comment by hgy59** [comment]
`librsvg` is a huge module with a lot of dependencies (glib, cairo, pango, gdk-pixbuf and more...)
This increases the imagemagick package by factor 2.5 
and librsvg is not prepared for cross compilation (only x86-64 arch is supported).

Finally svg to bitmap conversion works in this package without librsvg 😄 

So I will not integrate `cross/librsvg` for now and close #4729.

**Pull request merged**
