### PR TITLE
Fix cmake

### PR DESCRIPTION
**Pull request by publicarray**
_Motivation:_  fixes `CMake Error: Unknown argument --parallel`
_Linked issues:_  https://github.com/SynoCommunity/spksrc/pull/4810#issuecomment-917367288

https://gitlab.kitware.com/cmake/cmake/-/issues/21978#note_968161

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by publicarray** [comment]
Same for dependency-list

**Comment by th0ma7** [comment]
> @th0ma7 Is the most of the `cross-ninja.mk` file required if cmake can invoke the correct compiler (after the -G ninja) anyway?

not sure I fully follow?

**Comment by th0ma7** [comment]
> The `make[5]: warning: -j12 forced in makefile: resetting jobserver mode.` warning is created in `spksrc.copy.mk`
> 
> https://github.com/SynoCommunity/spksrc/blob/master/mk/spksrc.copy.mk#L69
> 
> @th0ma7 do you have any idea why?
> 
> FYI I've used `domoticz` to test/reproduce

In order to do follow both the PARALLEL_BUILD + the user provided -j (for multiple arch at one) it must reset the jobserver and force MAKEFLAGS... But looking into it currently.

I have another fix to push in, want me to include it in your PR directly?

**Comment by th0ma7** [comment]
found another way using from `spksrc.cross-cmake-env.mk`:
```
# Define parallel level
ifneq ($(PARALLEL_MAKE),nop)
CMAKE_ARGS += -DCMAKE_BUILD_PARALLEL_LEVEL=$(NCPUS)
endif
```

**Comment by th0ma7** [comment]
Looking into solving a few caveats on the parallel build process.
First draft of fixes available here: https://github.com/SynoCommunity/spksrc/pull/4854

**Pull request merged**
