### PR TITLE
SickChill update to fix v3 install errors

### PR DESCRIPTION
**Pull request by BKSteve**
Improved updating by clearing main core files for new one built in the spk.
Python 3.8.12-6 or greater check.

_Motivation:_  Fix v-3 installation issues on non x64 devices.

Edit
All builds install except `DSM 7.0` Build which gives `invalid file format` and seek additional testers or for somebody else to build the evansport 7.0 package to see if it is my build that causes the issue.

### CODE REVIEW

**Comment by BKSteve** [comment]
I see the builds failing with 

```
Error: ERRORS:
2021.11.11 15:47:00 - sickchill: (x64-7.0) FAILED

See log file of the build job to analyze the error(s).

Last 15 lines of the build log:

$ make TCVERSION=7.0 ARCH=x64 -C ./spk/sickchill
make[2]: Leaving directory '/github/workspace/cross/cffi'
make[2]: Entering directory '/github/workspace/cross/libsodium'
===>  Downloading files for libsodium
===>    File libsodium-1.0.18-stable.tar.gz already downloaded
===>  Verifying files for libsodium
===>    Checking sha1sum of file libsodium-1.0.18-stable.tar.gz
===>      Wrong sha1sum for file libsodium-1.0.18-stable.tar.gz
===>      Renamed as libsodium-1.0.18-stable.tar.gz.wrong
===>      Download cookie removed to trigger the download again
make[2]: *** [../../mk/spksrc.checksum.mk:42: checksum_target] Error 1
make[2]: Leaving directory '/github/workspace/cross/libsodium'
make[1]: *** [../../mk/spksrc.depend.mk:51: depend_target] Error 2
make[1]: Leaving directory '/github/workspace/cross/PyNaCl'
make: *** [../../mk/spksrc.depend.mk:51: depend_target] Error 2
make: Leaving directory '/github/workspace/spk/sickchill'
```

**Comment by BKSteve** [comment]
I went looking for changes in the build packages and note `Bazarr 1.0.0 (#4916)` updates `mk/spksrc.wheel.mk`
[Bazarr update](https://github.com/SynoCommunity/spksrc/commit/823fa14c61d96f938a46908b2c920ddcba5482c7)

```
post_wheel_target: $(WHEEL_TARGET)
	@if [ -d "$(WHEELHOUSE)" ] ; then \
		mkdir -p $(STAGING_INSTALL_WHEELHOUSE) ; \
		cd $(WHEELHOUSE) ; \
+		if stat -t requirements*.txt >/dev/null 2>&1; then \
        	cat requirements*.txt > $(STAGING_INSTALL_WHEELHOUSE)/$(WHEELS_PURE_PYTHON) ; \
+        fi ;\
		if [ "$(EXCLUDE_PURE_PYTHON_WHEELS)" = "yes" ] ; then \
			echo "Pure python wheels are excluded from the package wheelhouse." ; \
			for w in *.whl; do \
				if echo $${w} | grep -viq "-none-any\.whl" ; then \
					cp -f $$w $(STAGING_INSTALL_WHEELHOUSE)/`echo $$w | cut -d"-" -f -3`-none-any.whl; \
				fi ; \
			done ; \
		else \
			for w in *.whl; do \
				cp -f $$w $(STAGING_INSTALL_WHEELHOUSE)/`echo $$w | cut -d"-" -f -3`-none-any.whl; \
			done ; \
		fi ; \
	fi
```
Does this new end if cause the problem?

**Comment by th0ma7** [comment]
Feel free to give it a shot against #4951 as there are a few key fixes out there.

**Comment by BKSteve** [comment]
I was really hoping to get them all fixed up and then this DSM7 build issue for evansport and armv7 giving invalid file format.
Which is bazaar or bazarr?? :weight_lifting:

**Comment by publicarray** [comment]
libsodium changed their archives again.

**Comment by BKSteve** [comment]
Would this explain why the DSM 7 build are all giving the file format error?

**Comment by miigotu** [comment]
> I went looking for changes in the build packages and note `Bazarr 1.0.0 (#4916)` updates `mk/spksrc.wheel.mk` [Bazarr update](https://github.com/SynoCommunity/spksrc/commit/823fa14c61d96f938a46908b2c920ddcba5482c7)
> 
> start line 89
> 
> ```
> post_wheel_target: $(WHEEL_TARGET)
> 	@if [ -d "$(WHEELHOUSE)" ] ; then \
> 		mkdir -p $(STAGING_INSTALL_WHEELHOUSE) ; \
> 		cd $(WHEELHOUSE) ; \
> +		if stat -t requirements*.txt >/dev/null 2>&1; then \
>         	cat requirements*.txt > $(STAGING_INSTALL_WHEELHOUSE)/$(WHEELS_PURE_PYTHON) ; \
> +        fi ;\
> 		if [ "$(EXCLUDE_PURE_PYTHON_WHEELS)" = "yes" ] ; then \
> 			echo "Pure python wheels are excluded from the package wheelhouse." ; \
> 			for w in *.whl; do \
> 				if echo $${w} | grep -viq "-none-any\.whl" ; then \
> 					cp -f $$w $(STAGING_INSTALL_WHEELHOUSE)/`echo $$w | cut -d"-" -f -3`-none-any.whl; \
> 				fi ; \
> 			done ; \
> 		else \
> 			for w in *.whl; do \
> 				cp -f $$w $(STAGING_INSTALL_WHEELHOUSE)/`echo $$w | cut -d"-" -f -3`-none-any.whl; \
> 			done ; \
> 		fi ; \
> 	fi
> ```
> 
> Does this new end if cause the problem? Reversed this edit and am building now, will report if this resolves the issue on the DSM7 builds

That might do it, because there aren't supposed to be spaces for indents in a mk file. Change the spaces before the cat and the fi to tabs.

**Comment by BKSteve** [comment]
Some poor `Bazarr` editing to the mk file.
@publicarray

**Comment by BKSteve** [comment]
So how to resolve the DSM7 version build issue?

**Comment by th0ma7** [comment]
Just a thought... DSM6 `$HOME` is pointing under the `target` dir while with DSM7 `$HOME` is now located under:
```
/var/packages/<package>/home -> /volume1/@apphome/<package>
```
What I noticed is that with DSM7 the `virtualenv` now gets created in `$HOME/.local/share/virtualenv` which means that its not under `target` anymore like previously with DSM6.  So startup or service setup scripts might fail as still pointing to the previous virtual environment location.  I sort of noticed this with `tvheadend`.

Although note that there still is a `target/env/bin` containing `pip` and `python3` but it might get screwed-up when upgrading from DSM6 to DSM7 as `$HOME` changed between the two, thus not finding the background `virtualenv`.

**Review by ymartin59 — APPROVED** [review]

**Comment by publicarray** [comment]
Thanks for the find @BKSteve & @miigotu I missed it during review. Unfortunately I don't have my machine for the next few days. @th0ma7 you be able to push a fix?

**Comment by BKSteve** [comment]
#4970 cleans the 2 lines

**Comment by BKSteve** [comment]
OK, on my testing I was using 3.xx for all builds. DSM6 no issue with decimal build numbers but the DSM7 has issues any build number with a decimal would create **invalid file format**.
I never tested 4 as a whole number but now confirm the 4 as uploaded builds correctly and is loadable by my x64 DSM7. 

I will have the evansport, armv7 test it on their DSM7 machines and confirm clear to release.

**Comment by hgy59** [comment]
> DSM7 has issues any build number with a decimal would create **invalid file format**.

Your find the regex for DSM 7 version validation in #4524 footnote 9).
I hope that synology didn't change this with DSM 7.0.1. 
So make sure that the dash is - (ASCII 45dec) and dot is . (ASCII 46dec).

Anyway, as you speak of sickchill 3.x I hope you can change the version to that format instead of using a timestamp. 
We prefer official versions over timestamped or git-hash versions.

**Comment by BKSteve** [comment]
I will now use a different naming convention whilst building test version. As I was building on v-3 I was using 3.xx so anybody on a partial release of 3 would be able to upgrade to v-4 once it comes out. At least that was my thinking.
I will do a couple of tests but am thinking that the test numbering will be 3-xx and not 3.xx moving forward.

There's also now a pull request that links `invalid file format` to integer numbered releases and a standard 'full stop' hex 2e or ASCII 46 causes the error. I double checked it against the regex string [^\d+(\.\d+){0,5}(-\d+)?$] and the `dot` being the one between comma and / on my keyboard and not some special 'hard space' character is used. So this should be looked and others know this.

**Comment by miigotu** [comment]
> I will now use a different naming convention whilst building test version. As I was building on v-3 I was using 3.xx so anybody on a partial release of 3 would be able to upgrade to v-4 once it comes out. At least that was my thinking. I will do a couple of tests but am thinking that the test numbering will be 4-xx and not 4.xx moving forward as v-4 I believe is good to go.
> 
> There's also now a pull request that links `invalid file format` to integer numbered releases and a standard 'full stop' hex 2e or ASCII 46 causes the error. I double checked it against the regex string [^\d+(\.\d+){0,5}(-\d+)?$] and the `dot` being the one between comma and / on my keyboard and not some special 'hard dot' character is used. So this should be looked at and others know this.

Imho you should use the SickChill version tag as the spk version as well. So whenever you build the spk with a new version of SC, you know what version is in the spk very easily.

I know that doesn't help of you release multiple versions in one day, but sickchill is going to be modifying the release policy so that only one release is allowed per day, and hotfixes will not be versioned. The hotfix will be pushed to master and built into a proper release the next day.

This is nice then because for semver reasons there will be a 2021 tag (newest version for year 2021), a 2021.11 tag (the latest version for the month), and a daily tag 2021.11.15.

I would eventually like to remove the git and source based updater completely, and only use pip/poetry for upgrades, while improving stability of releases.

**Comment by BKSteve** [comment]
> Imho you should use the SickChill version tag as the spk version as well. So whenever you build the spk with a new version of SC, you know what version is in the spk very easily.

Yes, I've moved from v-3 using 20210729 [20210729-3 version name] to v-4 using 20211110 giving version 20211110-4. 
I agree that this way it's very clear what version is built inside the package. It's just I didn't put this number in the title of the pull but it's in all the code.

```
SPK_NAME = sickchill
- SPK_VERS = 20210729
- SPK_REV = 3
+ SPK_VERS = 20211110
+ SPK_REV = 4
```

**Comment by publicarray** [comment]
> 2021.11 

That is no longer possible as the version must always be increasing. The fist number before the first `.` must be larger than `20210729`

**Comment by publicarray** [comment]
Thanks @BKSteve That dot thing is a bit surprising for me too. I did know that DSM7 has tighter version checks but yea wow. 
Just a heads up I will be without my dev machine for at least a month. (Warranty takes that long)

**Comment by publicarray** [comment]
@th0ma7 or @hgy59 will have to do that when they can. I can't really do anything at the moment.

**Comment by th0ma7** [comment]
@publicarray in your absence I'll take care of it.
@BKSteve to confirm, this is good for a merge & publish?

**Comment by publicarray** [comment]
Thanks mate!

**Comment by BKSteve** [comment]
>  It's well tested now and ready.

@th0ma7 Yes, it's ready. All the testers confirm installed and working. 
I built it as v-4 and put in my share folder.
It's ready. And will resolve all v-3 issues that we know of.

**Comment by th0ma7** [comment]
Now meged and published.

**Pull request merged**
