### PR TITLE
Add Web Station/PHP5.6 as dependency

### PR DESCRIPTION
**Pull request by A----**
_Motivation:_ Add required dependencies to ruTorrent
_Linked issues:_ #2215 

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

Can't `make all` on a Windows host?
```
debootstrap --foreign --arch powerpc jessie /spksrc/spk/debian-chroot/work/staging/var/chroottarget "http://ftp.debian.org/debian"
mknod: '/spksrc/spk/debian-chroot/work/staging/var/chroottarget/test-dev-null': Operation not permitted
E: Cannot install into target '/spksrc/spk/debian-chroot/work/staging/var/chroottarget' mounted with noexec or nodev
Makefile:55: recipe for target 'debian-chroot_extra_install' failed
```

Sorry :(

### CODE REVIEW

**Comment by Dr-Bean** [comment]
> Can't make all on a Windows host?

I don't understand what this means. See the README for instructions on how to set up a development environment.

**Comment by Dr-Bean** [comment]
This also needs a change to the Makefile. See https://github.com/SynoCommunity/spksrc/blob/master/spk/cops/Makefile#L23, otherwise the dir won't be included. Hence the request to chekc of the package compiles and works correctly :)

**Comment by A----** [comment]
I tried, but doing a `make all` in the container tries to do a `mknod /spksrc/spk/debian-chroot/work/staging/var/chroottarget/test-dev-null`, which it cannot do since its a docker volume and the underlying FS does not support this (Windows, non-hyper-V).

At least that's my guess.

**Comment by Dr-Bean** [comment]
This is a PR for rutorrent, no? Why run a `make all` in the first place? It has a very specific use, and you'll generally have no need to run that command.
Enter the rutorrent dir, and run `make all-supported` instead.

**Comment by Dr-Bean** [comment]
After re-reading your comment, I think I understand the confusion. Take a look at this link for some information on how spksrc works: https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO

**Comment by A----** [comment]
Thanks, I did not find this doc. Currently downloading things!

**Comment by A----** [comment]
The docker method cannot work on a Windows host, when doing a `make all-supported` in the package folder. It tries to create sym and hard-links is the mounted volume `/spksrc`, which it does not know how to handle.
I copied `/spksrc` to another folder insisde the container and its now building.

I'll add the conf and rebuild if it all goes right.

**Comment by bamtan** [comment]
Do you know how to get ruTorrent running for DSM6?

**Comment by A----** [comment]
I'm sorry, but I can't make it work on my Docker environment. It's still the old Docker Toolbox, not the Docker for Windows. Sorry :man_shrugging: 

@bamtan check #2215 . I made it work

**Comment by Dr-Bean** [comment]
@A---- I'm not sure how to interpret your comment, but assuming you're talking about not getting (whatever flavor of) Docker on a Windows platform to work for compiling: Try using the VM approach instead: https://github.com/SynoCommunity/spksrc#virtual-machine. Imo, that's still the preferred method, because of the complete isolation of the host. Even using Docker on *nix has downsides for cross-compiling.

Also, if Docker for Windows doesn't work in general, then we should probably add that info to the README. I haven't a clue, I don't use Windows myself, so I'm going off of your issue description here ;)

**Comment by bamtan** [comment]
@A---- is there anywhere I can contact you? i'd love some help on setting ruTorrent up on a DS216j (no Docker support).

**Comment by A----** [comment]
@Dr-Bean I'm not sure that it does not work, someone would have to confirm that.
@bamtan Please check the issue #2215, it has all the information I have on the subject. Namely, install Webstation prior to ruTorrent and how to pass the PATH env variable for it to work.

**Comment by bamtan** [comment]
@A----  I still get Error 403 when trying to access ruTorrent, could you write a tutorial on setting this up? Reading through #2215 is quite confusing for me. I'd appreciate it a lot. Are you on IRC by any chance? Perhaps I can contact you on there for assistance?

**Pull request closed without merging**
