### PR TITLE
[comskip] Update to 0.82.003 Release

### PR DESCRIPTION
**Pull request by m4tt075**
_Motivation:_ New release available and platforms missing (although probably just a publication issue)
_Linked issues:_ #3410 

### Checklist
- [x] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

All packages compile (except Northstarplus): https://travis-ci.org/m4tt075/spksrc/builds/413315912
Test-builds here: https://github.com/m4tt075/spksrc/releases/tag/comskip-0.82.003

Currently untested.

### CODE REVIEW

**Comment by ymartin59** [comment]
Thanks. I would like to be able to do runtime dynamic linking against ffmpeg libraries, the same way I did for chromaprint... I also plan to upgrade to ffmpeg 4.0.2

**Comment by m4tt075** [comment]
@ymartin59 I have just looked at your `chromaprint` package. Looks interesting. I can follow how you did it, but don't know how to configure `comskip` to reuse `ffmpeg`. There don't seem to be configuration options in `comskip` to copy your approach 1:1. There are two environment variables (`ffmpeg_CFLAGS` and `ffmpeg_LIBS`), which override `pkg-config`. Not sure they can be utilized. I could not find any `rpath` related configuration options and/or environment variables in `comskip` manuals though. Happy to try but don't know how. Any advice how to approach it?

**Comment by m4tt075** [comment]
@ymartin59 Does not seem this package is meeting a lot of demand. Test-builds have been out for months, 19 downloads, no feedback (positive or negative) whatsoever. How do you want to proceed? Or do you want me to close this PR?

**Comment by ymartin59** [comment]
Hello. Please let PR open. I plan to publish it with fmpeg updates

**Comment by ymartin59** [comment]
@m4tt075 Sorry for my mistake, I have missed to re-use your PR before creating #3587 and I have selected latest git commit instead of a release version. Is there changes I should keep from your PR or can we just close it?

**Comment by m4tt075** [comment]
@ymartin59 No problem whatsoever. There was nothing of substance here. Don't waste time. Just keep going. Closing...

**Pull request closed without merging**
