### PR TITLE
Transmission: Update to 4.0.3

### LINKED ISSUE #5694: [Package Request] Bump Transmission to v4.0.3
### Software Name

Transmission 4.0.3

### Brief Description

Bump Transmission version from 4.0.2 to 4.0.3.

### Website

https://transmissionbt.com/

### Documentation

https://github.com/transmission/transmission/blob/main/docs/README.md

### Build/Installation documentation

https://github.com/transmission/transmission/blob/main/docs/Building-Transmission.md

### Source code

https://github.com/transmission/transmission

### OpenSource License

other (please specify below)

### Other License

https://github.com/transmission/transmission/blob/main/COPYING

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This PR is to update to the bugfix-only release of Transmission v4.0.3.

Fixes #5694

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Review by th0ma7 — APPROVED** [review]
LGTM

**Comment by vjayer** [comment]
Is transmission 4.x only for DSM7?

**Comment by mreid-tt** [comment]
> Is transmission 4.x only for DSM7?

Yes, unfortunately based on this original comment: https://github.com/SynoCommunity/spksrc/issues/5595#issuecomment-1424731289

**Comment by vjayer** [comment]
> > Is transmission 4.x only for DSM7?
> 
> Yes, unfortunately based on this original comment: [#5595 (comment)](https://github.com/SynoCommunity/spksrc/issues/5595#issuecomment-1424731289)

Ok thanks for confirming. If I update the OS to DSM7 can my current Transmission 3.0 installation also be updated to v. 4.0 with settings and everything in tact?

**Comment by mreid-tt** [comment]
> Ok thanks for confirming. If I update the OS to DSM7 can my current Transmission 3.0 installation also be updated to v. 4.0 with settings and everything in tact?

Yes, that is the way it is supposed to work.

**Pull request merged**
