### PR TITLE
fix ffsync build and wizard

### PR DESCRIPTION
**Pull request by hgy59**
_Motivation:_ ffsync does not build
_Linked issues:_ This PR does not fix install/uninstall ffsync (#3124, #2873). It maybe related to #2828

Before I will analyze the installation errors (apollolake-6.1) this fixes the build.

### CODE REVIEW

**Comment by hgy59** [comment]
In Makefile ffsync_extra_install the $(STAGING_DIR)/share/wheelhouse/requirements.txt is patched (this file was missing).
Since I don't understand the wheelhouse yet, can please someone check, whether the requirements.txt file in the staging dir is used for building the wheel...?

**Comment by hgy59** [comment]
And this is the solution for #2873
The src/wizard directory was removed from Makefile 2017/02/01. Therefore no wizard is displayed neither for install nor uninstall.
Without the wizard the mysql root password is always empty.

Update works without wizard, but a new install was not possible. To uninstall a ffsync that has no wizard, you can add the missing password in installer.sh like this:
`wizard_mysql_password_root=your_mysql_root_pw_here`

installer.sh is located in /var/packages/ffsync/scripts

OR  (not veryfied)
you can copy the missing wizard files to
/var/packages/ffsync/WIZARD_UIFILES

**Comment by Safihre** [comment]
@hgy59 thanks for this :) Will investigate the `requirements.txt` but pretty sure it's not used from staging but from the original file.

But I am pretty sure @ymartin59 won't accept it if it doesn't get converted to Generic Service package. But that's a relatively easy transition :)

**Comment by hgy59** [comment]
There is still an issue in ffsync.ini. The user for mysql is hard coded as ffsync, but installer.sh configures ffsync for build numbers < 7321 and sc-ffsync for newer.
Hope this will be easy with generic service implementation.

**Comment by Safihre** [comment]
@hgy59 Yes you can use `$EFF_USER` which contains the right user for the platform it's being installed on
 👍

**Comment by hgy59** [comment]
@Safihre already tried this, but `$(EFF_USER)` was empty

**Comment by Safihre** [comment]
It's not available in the `Makefile` no, only as part of the service-scripts in `src/service-setup.sh`.

**Comment by Safihre** [comment]
Can always push work-in-progress or link to working-branch and we can see what's going wrong :)

**Comment by Safihre** [comment]
@hgy59 how is this going? :)

**Comment by hgy59** [comment]
Installed the existing package some time ago, but it did not work.
And without a working installation it is boring to test migration (and it will still be some work to migrate to the new service approach)

**Comment by hgy59** [comment]
outdated due #3849

**Pull request closed without merging**
