### PR TITLE
updates with new location of certificate files for DSM 6

### PR DESCRIPTION
**Pull request by joshlawless**
_Motivation:_ DSM changed certificate location (and filenames?) in v.6
_Linked issues:_ This solves ticket 2340, I think
### Checklist
- [] Build rule `all-supported` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

### CODE REVIEW

**Comment by Dr-Bean** [comment]
While this may work for DSM6, it breaks the behavior for DSM5 and older, so that's no good. 

We need a better way to set the path for those two files. Maybe use the same approach we use elsewhere, see https://github.com/SynoCommunity/spksrc/blob/master/spk/tt-rss/src/dsm-control.sh#L12 for example.

**Comment by joshlawless** [comment]
What if you left in both copy commands, and suppressed any error message
from the one that didn't work?

**Comment by Dr-Bean** [comment]
Personally, don't like that :)

**Comment by hgy59** [comment]
DSM 6 critificate paths are fixed since update to gateone 20171125-7

**Pull request closed without merging**
