### PR TITLE
OpenSSL library update to version 1.0.2f

### PR DESCRIPTION
**Pull request by tedstriker**
version 1.0.2e is not available for download anymore

### CODE REVIEW

**Comment by gizmocuz** [comment]
Maybe the title is not clear ? update something to 1.0.2f

**Comment by tedstriker** [comment]
oh sorry, it's OpenSSL library

**Comment by Pimmetje** [comment]
@tedstriker Can u update the title?

**Comment by Dr-Bean** [comment]
Thanks for the PR. I'm closing this one, as I just merged the changes for openssl 1.0.2g.

**Pull request closed without merging**
