### PR TITLE
update mediainfo to 0.7.93

### PR DESCRIPTION
**Pull request by cytec**
_Motivation:_ https://github.com/SynoCommunity/spksrc/issues/2689
_Linked issues:_ https://github.com/SynoCommunity/spksrc/issues/2689

### Checklist
- [] Build rule `all-supported` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

### CODE REVIEW

**Comment by cytec** [comment]
@SynoCommunity/developers if someone wanna merge this and publish the new SPK go ahead. I don't know when i get time to fix my buildbox -.-

**Comment by KaraokeStu** [comment]
I'll get on this in about an hour!

**Comment by KaraokeStu** [comment]
Building now, just spun up a new VM on my home server for building (I've got one on my machine at work too)

**Comment by KaraokeStu** [comment]
@cytec I'm having some troubles building this - getting the following:

```
/bin/sh: 1: ./autogen: not found
Makefile:22: recipe for target 'myPreConfigure' failed
make[5]: *** [myPreConfigure] Error 127
make[5]: Leaving directory '/home/stuart/spksrc/cross/libzen'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[4]: *** [depend_target] Error 2
make[4]: Leaving directory '/home/stuart/spksrc/cross/libmediainfo'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[3]: *** [depend_target] Error 2
make[3]: Leaving directory '/home/stuart/spksrc/cross/mediainfo'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[2]: *** [depend_target] Error 2
make[2]: Leaving directory '/home/stuart/spksrc/spk/mediainfo'
../../mk/spksrc.spk.mk:392: recipe for target 'latest-arch-x64' failed
make[1]: [latest-arch-x64] Error 2 (ignored)
make[1]: Leaving directory '/home/stuart/spksrc/spk/mediainfo'
root@spksrc:/home/stuart/spksrc/spk/mediainfo# cd ../../cross/libzen/

```

**Comment by KaraokeStu** [comment]
Found the culprit - the Makefile should be calling ./autogen.sh not ./autogen

**Comment by cytec** [comment]
@KaraokeStu thanks! thought i've changed that... strange

**Comment by KaraokeStu** [comment]
I've updated it and am publishing now :)

**Pull request merged**
