### PR TITLE
synocli-devel update - Add libtool and strace

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

synocli-devel update:
- Add  `libtree` as `ldd` alternative
- Add `clang-tools-extra`
- Add `strace` (thnx @hgy59)

Fixes #

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
@hgy59 so relating to #5820 I've been trying to get `ldd` along with `llvm-readelf` available from our NAS.  This PR tries to address this so it is easier to confirm what's the status of the build shared libraries.

Still having issues with building `llvm-readelf` but `ldd` is now OK, at least on DSM-7.1

**Comment by hgy59** [comment]
@th0ma7 did you notice that the build of unsupported 88f6281 and qoriq had a long build time (1h 15m and  1h 55m) before the build was cancelled?

**Comment by hgy59** [comment]
@th0ma7 and I have prepared `strace` to be added (strace was already proposed in #3253)

**Comment by hgy59** [comment]
> Did you ever try to install llvm9.0.1 in native/llvm instead of building it from source?

Ok, found that lvm 9.0.1 installer for ubuntu is lacking the `clang-tblgen` tool 😞

**Comment by th0ma7** [comment]
> > Did you ever try to install llvm9.0.1 in native/llvm instead of building it from source?
> 
> Ok, found that lvm 9.0.1 installer for ubuntu is lacking the `clang-tblgen` tool 😞 

I actually whished i knew how to build a truly minimal llvm/clang with just the needed tools to limit wasted cycles in native.  Or better find it elsewhere and just dowloading it.   Unless it's available somehow in ppa or elsewhere and we just add it to the base image?

**Comment by th0ma7** [comment]
> @th0ma7 and I have prepared `strace` to be added (strace was already proposed in #3253)

@hgy59 Great addition! Would you mind adding symlinks entries in the synocli-devel Makefile?

**Comment by th0ma7** [comment]
@hgy59 BTW, while I got glibc to build correctly it ends-up colliding with gmp dependency from binutils when included in the synocli-devel build...  I've reached-out for assistance from the libc-help mailing list (https://sourceware.org/pipermail/libc-help/2023-July/006428.html), wait & see.

Otherwise the package would be mostly ready for release.

**Comment by th0ma7** [comment]
@hgy59 I've found an interesting `ldd` alternative called `libtree` ... seems to build just fine on evey arch.  Most importantly, it allows to confirm all libraries :rocket: 
```
root@th0ma7-nas:/var/packages/beets/target# find . -name "*.so" -exec libtree -p -v {} \;
./lib/libexslt.so 
├── /var/packages/beets/target/lib/libxslt.so.1 [rpath]
│   ├── /var/packages/beets/target/lib/libxml2.so.2 [rpath]
│   │   ├── /var/packages/beets/target/lib/libz.so.1 [rpath]
│   │   │   └── /lib/libc.so.6 [default path]
│   │   ├── /var/packages/python311/target/lib/liblzma.so.5 [rpath]
│   │   │   ├── /lib/libpthread.so.0 [default path]
│   │   │   │   ├── /lib/libc.so.6 [default path]
│   │   │   │   └── /lib/ld-linux-x86-64.so.2 [default path]
│   │   │   └── /lib/libc.so.6 [default path]
│   │   ├── /lib/libdl.so.2 [default path]
│   │   ├── /lib/libm.so.6 [default path]
│   │   ├── /lib/libpthread.so.0 [default path]
│   │   └── /lib/libc.so.6 [default path]
│   ├── /lib/libc.so.6 [default path]
│   ├── /lib/libpthread.so.0 [default path]
│   └── /lib/libm.so.6 [default path]
├── /var/packages/beets/target/lib/libxml2.so.2 [rpath]
├── /lib/libc.so.6 [default path]
├── /lib/libm.so.6 [default path]
└── /lib/libpthread.so.0 [default path]
```

**Comment by hgy59** [comment]
@th0ma7 binutils PLIST fix should finally fix the build...

**Comment by th0ma7** [comment]
> binutils PLIST fix should finally fix the build...

@hgy59 thnx, I had started a full build at home but this is taking so long to get all the results that I pushed it as-is knowing a fix would follow shortly thereafter.

With this I believe we're all set and this one can be merged (pending last roud of github-action builds).

**Comment by hgy59** [comment]
@th0ma7 just added a small update to libtree Makefile.

can you remember what the `ADDITIONAL_LDLAGS = -static` was for? I get binary identical targets without this option.

**Comment by th0ma7** [comment]
> can you remember what the `ADDITIONAL_LDLAGS = -static` was for? I get binary identical targets without this option.

It was the recommended build method from the project github page.  Guessing it can be removed?

**Comment by hgy59** [comment]
@th0ma7 another question: Is it worth to have `ARMv5_ARCH` specific builds when ARMv5 is not supported at all in `spk/synocli-devel/Makefile`?

I'll try to build for ARMv5 to find unsupported dependencies....

**Comment by th0ma7** [comment]
@hgy59 guessing armv5 could be supported probably as long as we remove LLVM ... along with perhaps a few others.  Having the ability to provide libtree and other tools on that old platform could be beneficial.

**Comment by hgy59** [comment]
> @hgy59 guessing armv5 could be supported probably as long as we remove LLVM ... along with perhaps a few others. Having the ability to provide libtree and other tools on that old platform could be beneficial.

yes llvm-9.0 is the first (and only?) dependency that fails to build for ARMv5 (Host GCC version must be at least 4.8, your version is 4.6.4.)

**Comment by hgy59** [comment]
@th0ma7 I tried to build llvm 3.3 for ARMv5 but gave up (there is no common target to build llvm and clang) or is there any benefit to include llvm without clang?

**Comment by th0ma7** [comment]
> @th0ma7 I tried to build llvm 3.3 for ARMv5 but gave up (there is no common target to build llvm and clang) or is there any benefit to include llvm without clang?

Wow, how couragous of you, respect! :bowing_man: 

Honestly, I wouldn't bother with that at all.  Having a few minimal tools for ARMv5 is already a success story, congrats!  And thnx for simplifying `libtree`, nice work.  Other than that, I believe it's now good for a merge?

**Review by hgy59 — APPROVED** [review]
LGTM

**Pull request merged**
