### PR TITLE
Bump bcrypt 3.1.4->3.1.5 to permit homeassistant-0.86.4 to install

### PR DESCRIPTION
**Pull request by chickenandpork**
_Motivation:_ HomeAssistant-0.86.4 needs bcrypt-3.1.5 as of home-assistant/home-assistant#19854 released as 0.85.0 (I think).
_Linked issues:_ None reported, but comments in https://community.home-assistant.io/t/python-3-5-3-on-synology/ mention the issue

Note: testing on `python3-3.5.6` because SynoCommunity/spksrc#3562 (python3-3.6.8) not yet merged.

### Checklist
- [x] Build rule `all-supported` completed successfully (well, it's used by `spk/python` and `spa/python3` and no other `cross` targets)
- [x] Package upgrade completed successfully (tested by myself on avoton, forum user "cyga" on arch-88f6281, will test with user "clappingmonkey"'s 88F6720 soonest
- [x] New installation of package completed successfully (python3-3.5.6 with bcrypt-3.1.5)

-- boilerplate -- (sorry)

I've been granted permission by my employer to contribute to spksrc without risk of IP confusion. I am required to explicitly write that my contribution to this project is solely in my personal capacity, and I am not conveying any rights to any intellectual property of any third parties.

### CODE REVIEW

**Comment by ymartin59** [comment]
@chickenandpork Thanks. FFmpeg 4.1 "project" is almost over, I can then come back to Python 3 and Home Assistant.

**Comment by chickenandpork** [comment]
There is a backlog; let’s discuss in offline email or some chat how we can make that more efficient.  If the gatekeepers are few, let’s make best use of your time!

**Comment by chickenandpork** [comment]
a clean rebuild with 'build-affected-spks' is failing similar to:

```
make[6]: Leaving directory '/spksrc/spk/python/work-aarch64-6.1/jpeg-9c'
find /spksrc/spk/python/work-aarch64-6.1/install//var/packages/python/target/ \! -type d -printf '%P\n' | sort | \
  diff /spksrc/spk/python/work-aarch64-6.1/libjpeg.plist.tmp -  | grep '>' | cut -d' ' -f2- > /spksrc/spk/python/work-aarch64-6.1/libjpeg.plist
===>  Correcting pkg-config file lib/pkgconfig/libjpeg.pc
===>  Correcting libtool file lib/libjpeg.la
make[5]: Leaving directory '/spksrc/cross/libjpeg'
make[5]: Entering directory '/spksrc/cross/zlib'
make[5]: Nothing to be done for 'default'.
make[5]: Leaving directory '/spksrc/cross/zlib'
===>  Extracting for Pillow
tar -xzpf /spksrc/cross/pillow/../../distrib/Pillow-5.3.0.tar.gz -C /spksrc/spk/python/work-aarch64-6.1 
===>  Patching for Pillow
patch -p0 < patches/001-fix-paths.patch
patching file setup.py
Hunk #1 FAILED at 107.
Hunk #2 FAILED at 302.
Hunk #3 succeeded at 414 (offset 35 lines).
2 out of 3 hunks FAILED -- saving rejects to file setup.py.rej
../../mk/spksrc.patch.mk:49: recipe for target 'patch_target' failed
make[4]: *** [patch_target] Error 1
make[4]: Leaving directory '/spksrc/cross/pillow'
```

Need to verify whether the patch is broken or my build env needs to be trashed and rebuilt.

**Comment by m4tt075** [comment]
Yes. Looks like the patch is broken to me. Hopefully they have just been merged upstream...

**Comment by chickenandpork** [comment]
If #3618 builds, we can retest this build on top.  I might have been doing the same in my testing: building `python3` but not `python`.  It was an automated dependency-checking script that caught this for me, so it's a bit embarrassing for me, but the fix should resolve the tree and this PR.

**Comment by chickenandpork** [comment]
#3618 resolves #3617 and looks good; thing patch should unblock but I cannot complete a clean build without #3618

**Pull request merged**
