### PR TITLE
Jackett - update to latest version

### PR DESCRIPTION
**Pull request by jdeluyck**
_Motivation:_ Update Jackett to latest version and fix several issues

- Kept flagging back offline due to errors in dsm-control.sh
- Installed package wasn't able to configure any trackers (atleast with me)

_Linked issues:_ _possibly_ #1995 

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully (on DS916+)
- [x] New installation of package completed successfully (on DS916+)

### CODE REVIEW

**Comment by m4tt075** [comment]
@jdeluyck: I think this needs a rebase. Also, looking at the file changes there are no changes in any dsm-control file. Maybe something got lost?

**Comment by jdeluyck** [comment]
I rebased to master. No idea what went on there.

**Comment by jdeluyck** [comment]
I was wondering, if anything is keeping this pull?

**Comment by m4tt075** [comment]
@jdeluyck I guess you should drop the syncthing commits and the one where you merge upstream, rebase again to be sure, squash the dsm-control fix into the actual update commit, and finally force push those changes to origin. Otherwise, one of the maintainers (probably @KaraokeStu) needs to review, approve and merge.

**Comment by KaraokeStu** [comment]
Unfortunately, this does need its commit history cleaning up before we can merge

**Comment by Stanzilla** [comment]
You can just use the "Squash and rebase" button GitHub offers.

**Comment by KaraokeStu** [comment]
@Stanzilla Back when I was creating PRs, I was always requested to squash the commits myself first - that's what I'm sticking to ;)

**Comment by jdeluyck** [comment]
I believe this looks better.

**Comment by KaraokeStu** [comment]
Almost there!

**Comment by KaraokeStu** [comment]
I'll try to get this built tomorrow

**Pull request merged**
