### PR TITLE
SickChill 20230627 Python 3.11

### PR DESCRIPTION
**Pull request by BKSteve**
## SickChill

Package Update to use Python 3.10 to 3.11 

Follows on from  #5766

### CODE REVIEW

**Comment by hgy59** [comment]
@BKSteve you must adjust the path for python 311 in service-setup.sh
```
PYTHON_DIR="/var/packages/python311/target/bin"
```

Almost always I have the same issue when migrating a package to Python 3.11 😉

**Review by th0ma7 — APPROVED** [review]
LGTM

**Comment by BKSteve** [comment]
Expecting an update to SickChill in a day or two. 
So once that's out I'll request a merge. 
Thanks

**Comment by BKSteve** [comment]
@th0ma7 latest update is out. Time for a merge.
Thanks

**Comment by th0ma7** [comment]
Excellent! Need assistance for publishing?

**Comment by mreid-tt** [comment]
> Excellent! Need assistance for publishing?

I have a job running for that... https://github.com/mreid-tt/spksrc/actions/runs/5421437452

**Pull request merged**
