### PR TITLE
cross/gevent: disable build of libev and cares (it's in the dependencies)

### PR DESCRIPTION
**Pull request by smaarn**
_Motivation:_ Cross compilation was failing on depending packages.

### Checklist
- [x] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
You apply change to ffsync whereas package has work in #3849

**Comment by smaarn** [comment]
> You apply change to ffsync whereas package has work in #3849

@ymartin59 Seems indeed a little bit redundant. Should I create a PR targeting the branch which that PR is based upon ?

**Comment by ymartin59** [comment]
@smaarn I will cherry-pick your commit into my own PR when testing and publishing (soon I hope so)

**Comment by hgy59** [comment]
> @smaarn I will cherry-pick your commit into my own PR when testing and publishing (soon I hope so)

@ymartin59 I have rebased your PR #3849 and cherry picked 7ebd1f26b1bb1e08adeeeb87b9a4da4988e4f1db .
I left 23d2a808128565464b31d79867f1ba2afb3cc514 due to out of sync merge conflicts.

As the requirement venusian==3.0.0 depends on python 3 we might move ffsync to Python 3.
_my investigations started with #4406 as all python2 packages are broken since pip 21.0 is out.

**Comment by smaarn** [comment]
Superseded by #3849 work.

**Comment by ymartin59** [comment]
@hgy59 Before you rebase, I thought there was still a chance to build and publish a package with latest Python 2... My branch was building and service seems to run in my last trial.

**Pull request closed without merging**
