### PR TITLE
tvheadend (TVH) OSCam support

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

tvheadend (TVH) OSCam support

Fixes https://github.com/SynoCommunity/spksrc/pull/5495#issuecomment-1327515133

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
@iHaveAstream I now have a version ready for testing.  It's using v1 of the patch for `libdvbcsa` but that should do the trick.  Can you test it out?  https://github.com/SynoCommunity/spksrc/actions/runs/3558875715

**Comment by th0ma7** [comment]
@hgy59 FYI, I've Downgraded `harfbuzz_3` to use v2.9.1 instead (this renamed to `harfbuzz_2`).  It appears that v3 didn't played out well with `libass` although it runs OK with `pango` & `libraqm` for hi3535-6.1

**Comment by iHaveAstream** [comment]
> @iHaveAstream I now have a version ready for testing. It's using v1 of the patch for `libdvbcsa` but that should do the trick. Can you test it out? https://github.com/SynoCommunity/spksrc/actions/runs/3558875715

@th0ma7 
many thanks! I'll try to test today.
Just to make sure: I suppose it's recommended to uninstall any other version of TVH before testing with this one here?
No not just to update an existing installation?

**Comment by hgy59** [comment]
> @hgy59 FYI, I've Downgraded `harfbuzz_3` to use v2.9.1 instead (thus renamed to `harfbuzz_2`). It appears that v3 didn't played out well with `libass` although it runs OK with `pango` & `libraqm` for hi3535-6.1

ok, but you have to update the PLIST file...

**Comment by th0ma7** [comment]
> many thanks! I'll try to test today. Just to make sure: I suppose it's recommended to uninstall any other version of TVH before testing with this one here? No not just to update an existing installation?

Nope, you should normally just upgrade and that should work.  Although I always suggest making a backup first, just in case.

**Comment by th0ma7** [comment]
> ok, but you have to update the PLIST file...

Such a classic, thnx.

**Comment by iHaveAstream** [comment]
> > many thanks! I'll try to test today. Just to make sure: I suppose it's recommended to uninstall any other version of TVH before testing with this one here? No not just to update an existing installation?
> 
> Nope, you should normally just upgrade and that should work. Although I always suggest making a backup first, just in case.

@th0ma7 
Awesome! Many thanks - it works!
Nevertheless, for some other reasons, I decided to start from scratch with a fresh installation of TVH on DSM 6.2.

**Comment by th0ma7** [comment]
> Awesome! Many thanks - it works! Nevertheless, for some other reasons, I decided to start from scratch with a fresh installation of TVH on DSM 6.2.

I'm really glad to hear that this works out all right.  Can you give it one more shot as I've updated the `libdvbcsa` patchset to v2 which shouldn't have any impacts but in any case.  Packages available here : https://github.com/SynoCommunity/spksrc/actions/runs/3564613625

**Comment by iHaveAstream** [comment]
> @iHaveAstream actually, please use the next build output based on the latest TVH commit (once builds finishes): https://github.com/SynoCommunity/spksrc/actions/runs/3570200278

@th0ma7 
alright, of course I'm happy to test this latest build incl. v2 libdvbcsa patch. keep you posted.

**Comment by th0ma7** [comment]
Thnx for your time to test, now merging, cheers!

**Pull request merged**
