### PR TITLE
update sabnzbd-testing (DSM6 branch) to v2.2.1 + update dependencies

### PR DESCRIPTION
**Pull request by maxrogers**
_Motivation:_ Update to v2.2.1 on DSM6 branch

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by Safihre** [comment]
@maxrogers Just released 2.2.1 😉

**Comment by ymartin59** [comment]
Your PR title is confusing. Have you apply a full `master` to `dsm6` merge ? If so, please just entitled your PR with that information.

May you list explicitely which packages have you built with target `all-supported` ?

**Comment by maxrogers** [comment]
@ymartin59 
1. This PR updates only sabnzbd-testing on DSM6 branch to v2.2.1. It also updates needed dependencies (ignore confusing reference to master.)
2. Only sanbznbd-testing package has been tested

**Comment by ymartin59** [comment]
So same explanation as in #2692 
<<
Please please do not submit PR to dsm6 branch which does not concern specifically DSM 6.x support.

Procedure consists in regularly merging from master to dsm6. So to avoid conflicts, packages have to be submitted only to master.
>>

I will try to do a PR with `master` to `dsm6` merge, so that this branch receives packages updates.

**Comment by maxrogers** [comment]
@ymartin59 Roger that! Noted and that makes sense. I did this so I could update my DSM6 package personally and thought I would share.

**Comment by ymartin59** [comment]
I will refer to your PR to resolve conflicts I expect to produce with that merge. So it is still a good idea to share...

**Comment by maxrogers** [comment]
This should be the only thing from this PR that you will need to fix in master: https://github.com/SynoCommunity/spksrc/pull/2887/files#diff-4b089689ff77f9ccfd4b9e97da8aaeb4

**Comment by ymartin59** [comment]
OK so we have to wait for #2898 to be merged, and then I will update #2900 with this additional commit. So you could use my branch to compile for DSM 6.1: https://github.com/ymartin59/spksrc/tree/dsm6-merge-from-master-20170830

**Comment by ymartin59** [comment]
@maxrogers May you confirm current content of `dsm6` allows to build sabnzb-testing. If so please close this PR

**Comment by maxrogers** [comment]
Confirmed

**Pull request closed without merging**
