### PR TITLE
Cross cleanup

### PR DESCRIPTION
**Pull request by hgy59**
_Motivation:_ When I checked all the source downloads of cross Makefiles, I found that some modules are outdated and not referenced by any spk and therefore can be removed from the repository.
_Linked issues:_ Just one year ago there was a cleanup proposed in PR #2658. 

The PR #2658 deleted 157 files and some are still in use or under development. It was too much for me to review all the dependencies there, so I deleted only cross modules after manual checking that no dependency exists anymore.

- cross/serf, cross/apr-util and cross/apr
should have been removed when subversion spk was removed.
- cross/dbus, cross/libcap2, cross/iksemel and cross/libical
where never used
- cross/tinyproxy
should have been removed when when spk was removed

### CODE REVIEW

**Comment by ymartin59** [comment]
Thanks a lot for reviewing this cleanup PR. At least it is a first step forward.

**Comment by Safihre** [comment]
I do not understand the `status/ready-to-merge`, why not just.. merge?

**Comment by ymartin59** [comment]
@Safihre I like to have some time to think about it before doing fast mistakes... Either I merge before other PR merges or when useful to be on `master` to build packages.

**Comment by Safihre** [comment]
@hgy59 Did you see this script by @GuillaumeSmaha?
https://github.com/SynoCommunity/spksrc/issues/2656#issuecomment-283201724

**Comment by ymartin59** [comment]
@Safihre I asked @GuillaumeSmaha if it is possible to move repository to SynoCommunity organization but did not receive answer yet. I use it "my own way" to check dependencies when working on a package.

**Pull request merged**
