### PR TITLE
Mise à jour vers ImageMagick 7.0.7

### PR DESCRIPTION
**Pull request by digitalbox94**
_Motivation: Use Image Magick last version 7.0.7
_Linked issues: 

### Checklist
- [] Build rule `all-supported` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
Thanks for contributing but...
first contribution are expected to be submitted in English
then a millisecond search would have pointed you my pending PR with update #3304

**Comment by digitalbox94** [comment]
Yes I've seen it by after submitting. 
One remark concerning your PR : I don't see "bin:bin/magick" in the PLIST. Maybe to double check (many link to this binary with ImageMagick 7).

Another question : I would like to submit DKB Trace new package, but when I'm doing a "pull request" it also include my changes for Image Magick 7. Any idea how to only do a pull request with a limited list of commits ?

**Comment by ymartin59** [comment]
@digitalbox94 You have to create a dedicated branch for commits you plan to submit in a specific PR (with master as base). I invite you to read some Git and GitHub tutorials.

You're right, some binaries have been replaced by wrapper script and are lacking in original package. Thanks for the hint, I will fix that.

**Comment by digitalbox94** [comment]
Ok thanks for the hint on the branch, I will check how to do in details. And maybe how to remove the ImageMagick changes I've done on my repo forked from the original spksrc repo (which should be fine I hope regarding ImageMagick 7).

DKB Trace is an "old" package I've created one year ago to understand how to port and create a package + web interface via SPKSRC on a Synology. It was working fine and GIT was not on my priority list on that moment :)
 
For the tools : I've just compared SPKSRC and the original Synology tools (I've used the Synology tools recently to compare...) : there's definitively a huge gap and I think SPKSRC is a really must have compared to the Synology tools.

**Comment by ymartin59** [comment]
Really Git is a complex beast and GitHub adds again concepts and advanced features... It took me long (and a 500 pages book reading) before I can say I know/master it. Sorry but I cannot help commenting here. Even if that set of tutorials is based on GitHub desktop, you should easily adapt process to your tooling: https://services.github.com/on-demand/github-desktop/create-branches-github-desktop

What is important: preserve upstream "master" branch unmodified, so that you can regularly update your personal fork: https://help.github.com/articles/syncing-a-fork/

**Comment by ymartin59** [comment]
Package published.

**Pull request closed without merging**
