### PR TITLE
update nano to 2.9.5

### PR DESCRIPTION
**Pull request by publicarray**
_Motivation:_ I needed to start somewhere to learn the how build process works... 

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
Thanks. I was not aware our nano version was so old. It is worth for an update and publish.

**Comment by ymartin59** [comment]
@publicarray  Please run "make all-supported" and confirm it passes without error in check list. I will then merge and publish.

**Comment by publicarray** [comment]
Well I've kicked off the build process. You might hear from me sometime next year ⏳

**Comment by publicarray** [comment]
So I've gotten 10 arch toolchains + nanos compiled in 8 hours in the Docker container. I think it's fair to say it works. As for the remainder, sorry but your are on your own.
xkcd

**Comment by publicarray** [comment]
Thank you! I'm building on TravisCI now: https://travis-ci.org/publicarray/spksrc/builds/363925966

**Pull request merged**
