### PR TITLE
[Mono] Update to 5.8.0.108 (fixes #2808)

### LINKED ISSUE #2808: [Update Request] Mono
Requesting an update to Mono 5 as per https://github.com/Jackett/Jackett/issues/1454#issuecomment-310906029

### PR DESCRIPTION
**Pull request by m4tt075**
### Motivation
Update Mono to 5.8.0.108 (latest release). Potentially fixes issues with Radarr and Sonarr.

### Linked issues
#2808 

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by Safihre** [comment]
@m4tt075 do you have a build somewhere that I can link in my packages list? :)

**Comment by m4tt075** [comment]
@Safihre Sorry, not yet. Just returned home and had to kick travis' behind to finalize those ffmpeg builds I started this morning. But I will add the relevant links here, once I have got them...   :-)

**Comment by Safihre** [comment]
@m4tt075 would you maybe also want to try my new Travis setup that doesn't use Docker?
It's faster and 100x more reliable, but want to make sure it behaves the same as the Docker one. For example for Python I found slight differences because it uses Ubuntu instead of Debian.
https://github.com/SynoCommunity/spksrc/issues/2990#issuecomment-356956997

**Comment by m4tt075** [comment]
@Safihre Thanks for your advice. Yes,, I have tried it some days ago. It worked fine for simple packages but I ran into problems building TVH. When I realized I spent more time with trying to fix the build system as compared to working on spksrc, I have eventually reverted to the docker method. Might try again at a later stage.

**Comment by DamienGZ** [comment]
This pre-release version wouldn't by any chance with the cert issue I'm having with Mono would it?

Whenever I try to run Jackett with the lastest avaliable version of Mono from the SynoCommunity I get this error, 

"The mono certificate store is not initialized.
Please run the following command as root:
cert-sync /etc/ssl/certs/ca-certificates.crt"

I've seen some posts saying to run some terminal lines to re-download certs but have no idea how to run Terminal within Synology.

**Comment by m4tt075** [comment]
Yes, the pre-release version should fix this.

**Comment by ymartin59** [comment]
@m4tt075 Are you sure ? In my opinion, published mono 5.4 contains same scripts as this PR basis in `master`

**Comment by m4tt075** [comment]
Hmh, if mono 5.4 is used, you are right. I did not know it was published in the meantime. @DamienGZ Which version are you running?

**Comment by Stanzilla** [comment]
need some testbuilds @m4tt075 @Safihre

**Comment by DamienGZ** [comment]
@ymartin59 I'm running version 5.4.1.6-9, the latest version available to me from the SynoCommunity.

**Comment by ymartin59** [comment]
@m4tt075 May you please update to 5.8.0.108 release

**Comment by m4tt075** [comment]
@ymartin59 I have forced-pushed the update to 108. Test builds are [here](https://github.com/m4tt075/spksrc/releases/tag/Mono-5.8.0). But I still don't know why `cert-sync` is apparently not correctly executed for some. I will do some more testing, but will need others to test this too. Please keep this PR open for the time being.
@Safihre , @Stanzilla , @DamienGZ : FYI.

**Comment by ymartin59** [comment]
I propose to remove "beta" flag on package...

**Comment by Stanzilla** [comment]
That did not go so well so far, installed mono_88f6281-6.1_5.8.0.108-10.spk and Sonarr and Jackett are no longer starting up, already rebooted the NAS. Logs show nothing. Investigating...

**Comment by m4tt075** [comment]
Yes, I can reproduce now. It seems to be a corlib issue. I get `corlib not in sync with this runtime` errors running `cert-sync`. Somebody reported this error in the context of `transmission` too. Just don't know whether this is us or upstream. I'm AFK now, but will keep investigating later this week.

**Comment by m4tt075** [comment]
I think I have found the culprit. Had to update and rebuilt natively too. I have removed the `Mono-5.8.0` and `Mono-5.8.0` testing packages from github, and triggered travis to build new ones. Will link them here as soon as they are done.

**Comment by DamienGZ** [comment]
Thank you @m4tt075, eagerly awaiting.

**Comment by m4tt075** [comment]
New 6.1 test builds can be found [here](https://github.com/m4tt075/spksrc/releases/tag/Mono-5.8.0-fixed).

**Comment by DamienGZ** [comment]
Thank you @m4tt075, good work :). This is probably a really noob question, you wouldn't happen to know which of those builds I'd use for a Synology 1815+ would you? I'm thinking mono_x86-6.1_5.8.0.108-10.spk, but am not 100% sure.

**Comment by DamienGZ** [comment]
Noticed that after installing this latest version of Mono, Radarr now seems to be broken. When trying to start Radarr it immediately shuts down. Sonarr is fine though, I'll look into Radarr and update if I find anything.

**Comment by m4tt075** [comment]
@Safihre Please see above. Any idea about Radarr? Can you reproduce this?

**Comment by piejanssens** [comment]
Radarr running fine here.

**Comment by Stanzilla** [comment]
Sonarr and Jackett are running well so far.

**Comment by Safihre** [comment]
@m4tt075 Only have a small XPEnology system so can't really test Radarr in production, just basic functions.

**Comment by DamienGZ** [comment]
@m4tt075 @Safihre So just reporting back on what I'm seeing, it may be a Radarr issue not a Mono thing, though maybe it's a mixture.

I've used Radarr on my Synology since it was released on the SynoCommunity (months...maybe a year, whatever), never had an issue with it before where it wouldn't start.

After installing this latest version of Mono  I restarted Radarr from within Radar and then this is what started happening, I'd go to the packages screen on Synology and click Run, it would say it was running however if I refreshed the packages folder it would instantly show as not running, basically it would shutdown (or not start, wasn't sure) instantly. This would persist past rebooting the Synology.

I uninstalled Radarr and re-installed, and then Radarr booted up and worked just fine and continued to work fine until I restarted Radarr from within Radarr, since then running and even rebooting the Synology would again no longer run with the same symptoms as above.

I uninstalled and reinstalled again, restarted Radarr by stoping then starting the package in the packages screen in Synology and it continued to work fine. Then I restarted Radarr from within Radarr and again same issue as before, no longer could I get Radarr to work at all.

I've since reinstalled again and it has been working fine all day, am I'm just making sure not to restart within Radarr.

Maybe something with this Mono update has locked Radarr from not somehow restarting? Or maybe it's Radarr, not really sure, just posting the info in case it rings any bells with anyone, or someone else is having the same problem.

Thanks for fixing the cert issue again :)

**Comment by Stanzilla** [comment]
I switched to the 6.1 Sonarr package from @Safihre and it now has permission problems importing media, is there anything I need to change?

```
Couldn't import episode /volume1/downloads/x.mkv: Access to the path "/volume1/downloads/x.mkv" or "/volumeUSB2/usbshare/TV Shows/x~" is denied.
```

**Comment by Safihre** [comment]
@Stanzilla could you check if the `sc-sonarr` user is in the `sc-media` group and if the `sc-media` group has permissions for `/volume1/downloads` and `/volumeUSB2/usbshare`?

**Comment by Stanzilla** [comment]
@Safihre `sc-media` has no members and `sc-download` doesn't either. I also don't see a `sc-sonarr` user in the GUI

**Comment by Safihre** [comment]
Yes I forgot that these are hidden users.
But the `sc-media` group does have permissions for your folders?

**Comment by Safihre** [comment]
@DamienGZ Just tested and for me it restarts normally. Maybe you can open the log to see what's going wrong?

**Comment by Stanzilla** [comment]
@Safihre did not, does now :)

**Comment by Stanzilla** [comment]
@Safihre did not, does now, still says access denied though. the file itself is user transmission, group users

**Comment by DamienGZ** [comment]
@Stanzilla Try restarting your Synology, permission problems for me in the past with Sonarr have been resolved with a simple restart.

**Comment by Safihre** [comment]
@ymartin59 Another proof that these tools should all be `sc-download`, the downloaders and the processors.

**Comment by Stanzilla** [comment]
@DamienGZ I did reboot, didn't fix it. @Safihre anything else I can try?

**Comment by Safihre** [comment]
@Stanzilla Maybe use the propagate-option of applying permissions in File station? It should add the `sc-media` group also to the files.

**Comment by Stanzilla** [comment]
@Safihre no dice :(

**Comment by ymartin59** [comment]
Please stop commenting about specific application troubles in that PR for Mono.

@m4tt075 Concerning `cert-sync` trouble, would it be possible it generates Mono certificate store in a "volatile" location like `/tmp` and does not survive a reboot - for instance ?

**Comment by m4tt075** [comment]
@ymartin59 I think the `cert-sync` troubles have been fixed with the last versionI posted 4 days ago. At least I'm not aware of any reports indicating otherwise since. I have checked for the storage place anyways. Took me some time to figure out, but it is in `/usr/share/.mono/` which should survive reboots. 

But let's keep tracking the tests for some more time. Mono-5.8.0-fixed just has been downloaded 44 times. I really have to rely on users here as I don't use any applications depending on mono myself.

**Comment by m4tt075** [comment]
@ymartin59 I removed the beta flag, as requested (latest commit). Again, I have not been able to personally test mono, as I have no usecase for it, but the fixed mono version has been downloaded 53 times in the meantime. No reports on `cert-sync` issues since. I will adapt the PR description now. We can wait some more, but squash-merge whenever you feel comfortable.

**Pull request merged**
