### PR TITLE
Upgrade node to v4.2.1 (LTS) - no architectures supported?

### PR DESCRIPTION
**Pull request by hmalphettes**
As requested here: https://github.com/SynoCommunity/spksrc/issues/1872

### CODE REVIEW

**Comment by hmalphettes** [comment]
I would need some help with compilation:
```
vagrant@localhost:~/spksrc/cross/node$ make arch-88f6281
===>  Building package for arch 88f6281
...
error: invalid floating point option: -mfpu=vfpv2
```
I am a newbie with arm but documentation matches 88f6281 with fully ARMv5TE-compliant 
I cannot determine if that implies that the floating point instructions set vfpv2 are available or not.

**Comment by hmalphettes** [comment]
I found out that V8 has dropped arm support for chips that don't have vfpv2: https://groups.google.com/forum/#!topic/v8-users/aSOFbaAQvMk

So this new version of node wont work with 88f6281.

The other new constraint is the requirement for gcc4.8 as V8 requires C++11.
It looks like none of the architectures have a toolchain that meets this requirement: at best we get gcc4.7

Someone knows what to do?

**Comment by Dr-Bean** [comment]
Nothing we can do about it, unless Synology releases new toolchains with an updated GCC version. Maybe the next toolchain release will cover it, we'll have to wait and see.

As for 88f628x: Since Node v0.12, ARMv5 wasn't supported anymore, which is why this line exists: https://github.com/SynoCommunity/spksrc/blob/master/cross/node/Makefile#L9.

**Comment by hmalphettes** [comment]
@Dr-Bean thanks for the explanation. Closing then.

**Pull request closed without merging**
