### PR TITLE
Update Gitea to v1.21.7

### PR DESCRIPTION
**Pull request by wkobiela**
## Description

Upgrade to newest version

## Checklist

- [x] Build rule `all-supported` completed successfully
- [] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

Tested on virtual dsm7

### CODE REVIEW

**Comment by wkobiela** [comment]
@hgy59 can you take a look?

**Comment by hgy59** [comment]
@wkobiela v1.21.8 is availale (sorry, I am offline for some days).

**Comment by hgy59** [comment]
@wkobiela BTW you are more flexible when not using specific version in your branch names.

**Comment by wkobiela** [comment]
@hgy59 I have automation script to prepare changes and PR, all I do is test package. Closing this PR in favor of #6036

**Pull request closed without merging**
