### PR TITLE
tvheadend trivial dependencies version update - July 2019

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  I noticed that many dependencies to tvheadend where using older versions.  Updated all of the really straightforward ones.
_Linked issues:_  None although it's tied into my other project of creating a tvheadend 4.3-dev package

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by th0ma7** [comment]
recompiled `tvheadend` successfully against all the new libraries AND ffmpeg 4.1.4 from other pull request:
```
packages$ ls -1 tvheadend_*
tvheadend_88f6281-6.1_4.2.8-16.spk
tvheadend_aarch64-6.1_4.2.8-16.spk
tvheadend_alpine-6.1_4.2.8-16.spk
tvheadend_armada370-6.1_4.2.8-16.spk
tvheadend_armada375-6.1_4.2.8-16.spk
tvheadend_armada38x-6.1_4.2.8-16.spk
tvheadend_armadaxp-6.1_4.2.8-16.spk
tvheadend_comcerto2k-6.1_4.2.8-16.spk
tvheadend_evansport-6.1_4.2.8-16.spk
tvheadend_hi3535-6.1_4.2.8-16.spk
tvheadend_ipq806x-1.2_4.2.8-16.spk
tvheadend_monaco-6.1_4.2.8-16.spk
tvheadend_ppc853x-5.2_4.2.8-16.spk
tvheadend_qoriq-6.1_4.2.8-16.spk
tvheadend_x64-6.1_4.2.8-16.spk
```

**Comment by th0ma7** [comment]
Package update successful using original `tvheadend` as frontend to all the libraries under `arch-apollolake`.  Note that package was built over `ffmpeg` pull request #3751 .

**Comment by th0ma7** [comment]
Manage to create proper backups of all my `tvheadend` configurations.
Did a full uninstall & manual reinstall (and restored all my configs) and all is running really well.
Conclusion: all trivial dependencies are working well using `tvheadend`.

**Comment by ymartin59** [comment]
Hello @th0ma7 Are you interested to take over maintenance of tvheadend package as @m4tt075 left?

**Comment by th0ma7** [comment]
Bonjour @ymartin59 , yes, I'd be interested.  Although I would need advices and guidance on how to do that.  Is there a way I can reach out to you to have a chat/talk so I better understand how the community is working things out?

**Pull request merged**
