### PR TITLE
rustc: Install compiler with toolchain at spksrc.tc.mk time

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

rustc: Install compiler with toolchain at spksrc.tc.mk time

Related to #5527 and #5475

## Checklist

- [x] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [x] Includes small framework changes
- [x] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
@hgy59 your pair of eye would be needed for this rust toolchain change.  You can test the docker side of things from the documentation I added at the end of https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO

**Comment by th0ma7** [comment]
@hgy59 friendly reminder if cycles allow for it to test this to significantly reduce our docker image size.  Testing on my end looked good.

**Comment by th0ma7** [comment]
@hgy59 while I had tested this throughout it seems something isn't right with the rustup initial setup... I'll investigate tonight and if I can't find where the issue is I'll revert the change from master.

**Comment by hgy59** [comment]
@th0ma7 sorry for not providing feedback to this PR, so many WIP...

**Comment by th0ma7** [comment]
I may have found the issue... in docker using priviledge mode it requires:
```
# Setup the rustc environment
ENV CARGO_HOME=/spksrc/distrib/cargo
ENV RUSTUP_HOME=/spksrc/distrib/rustup
ENV PATH="$VENV_PATH/bin:$RUSTUP_HOME/bin:$CARGO_HOME/bin:$PATH"
```
It seems I had forgotten to force rebuilding my local docker environment... build currently in progress to confirm rust environment works as expected...

**Comment by th0ma7** [comment]
@hgy59 so while this now works in priviledge Docker mode with the added fix, there is now something else in non-priviledge.  There probably isn't much missing...  Main issue is that everytime you install rustup it pokes your default `.profile` and `.bashrc` which in turns makes you believe things are great and all settled... but a fresh re-install shows it isn't.  In the meantime, docker on github seems all good at least and I'm probably inches away from fully fixing this.

Expect me to rework that last bit... Although feel free to chim-in and figure out it doesn't work in non-priv mode.

**Comment by th0ma7** [comment]
@hgy59 I believe it's now solved on master, hopefully permanently.

**Pull request merged**
