### PR TITLE
update gnupg

### LINKED ISSUE #3502: [Update Request] GnuPG to 2.2.*
The current packaged version of GnuPG is 2.1.6 which was released on July 1st, 2015. The most recent version is 2.2.10, released August 30th, 2018.

### PR DESCRIPTION
**Pull request by hgy59**
_Motivation:_  Finalize gnupg update (_some updates of gnupg are already on the master but not published yet_).
_Linked issues:_  closes #3502, #4180 (to close after publish), #4010, #4211

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### Remarks
- #3439 and #3449 introduced the solution, but not all of the fixes are needed anymore.
- #4010 contains updates of some packages (but not all)
- revert unsupported archs introduced with #4010

### CODE REVIEW

**Comment by th0ma7** [comment]
Nice work and thnx for taking this one out.
There is an odd failure onto `tvheadend` over x64 worth checking.  Might just be a false-positive?  Similar with `synocli-file` on both `aarc64` and `ppc853x`

**Review by th0ma7 — APPROVED** [review]

**Comment by th0ma7** [comment]
Looking at the affected packages it would have been nice to have this PR done as well for #4211 prior to publishing `python*` & `ffmpeg*`.  I don't believe its worth republishing but would it be worth adding a comment in them for next releases?

**Comment by hgy59** [comment]
> 
> 
> Nice work and thnx for taking this one out.
> There is an odd failure onto `tvheadend` over x64 worth checking. Might just be a false-positive? Similar with `synocli-file` on both `aarc64` and `ppc853x`

All three packages build locally without any problem.

Just analized the `synocli-file` errors. There is a download problem with `ftp://ftp.astron.com/pub/file/file-5.35.tar.gz`.

```
2020-10-24T14:53:38.7117127Z wget ftp://ftp.astron.com/pub/file//file-5.35.tar.gz
2020-10-24T14:53:38.8259283Z Login incorrect.
2020-10-24T14:53:38.8273258Z make[1]: *** [../../mk/spksrc.download.mk:59: download_target] Error 6
```

@th0ma7 didn't you add retries for downloads shortly?

Another solution would be to use an alternate download location.

-----

The thvheadend x64 error is not so obvious:
```
2020-10-24T16:26:44.8863550Z ===>  Compiling for tvheadend
2020-10-24T16:26:45.0286582Z make[2]: Entering directory '/github/workspace/spk/tvheadend/work-x64-6.1/tvheadend-git9ed76c0a176b055a57b6e8bd2e0b6e29409269a9'
2020-10-24T16:26:45.0293757Z make -f Makefile.webui LANGUAGES="ach ady ar bg cs da de en_US en_GB es et fa fi fr he hr hu it ko lv lt nl no pl pt ro ru sl sk sq sv tr uk zh zh-Hans" all
2020-10-24T16:26:45.0301960Z Receiving data/dvb-scan from https://github.com/tvheadend/dtv-scan-tables.git#tvheadend
2020-10-24T16:26:45.0353334Z make[3]: Entering directory '/github/workspace/spk/tvheadend/work-x64-6.1/tvheadend-git9ed76c0a176b055a57b6e8bd2e0b6e29409269a9'
2020-10-24T16:26:45.0354701Z make -f Makefile.webui WEBUI=std   compile-std
2020-10-24T16:26:45.0506832Z make[4]: Entering directory '/github/workspace/spk/tvheadend/work-x64-6.1/tvheadend-git9ed76c0a176b055a57b6e8bd2e0b6e29409269a9'
2020-10-24T16:26:45.0570054Z CC              src/uuid.o
2020-10-24T16:26:45.0576074Z CC              src/main.o
2020-10-24T16:26:45.1995719Z make[2]: *** [Makefile:888: /github/workspace/spk/tvheadend/work-x64-6.1/tvheadend-git9ed76c0a176b055a57b6e8bd2e0b6e29409269a9/data/dvb-scan/.stamp] Error 1
2020-10-24T16:26:45.1997128Z make[2]: *** Waiting for unfinished jobs....
```

❓ ❓ ❓

**Comment by hgy59** [comment]
The previous errors are gone with a second run of the build actions. But for several packages homeassistant failed to build...
It is painful that these builds are not reliable...

**Comment by th0ma7** [comment]
> @th0ma7 didn't you add retries for downloads shortly?

No I did not.  The `for` loop is really only to manage parallel build where multiple `wget` instances get ran at the same time so I'm using `flock` to circumvent that along with a preliminary wait delay in case another process did downloaded the file already.

But certainly something to look at... Added to my TODO bucket list.

**Pull request merged**
