### PR TITLE
Update SABnzbd to 4.3.2

### PR DESCRIPTION
**Pull request by Safihre**
## Description

Update SABnzbd to 4.3.2

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by Safihre** [comment]
@th0ma7 I was a bit surprised it tries to build Python for `88f6281` (which fails), even though SABnzbd specifies `UNSUPPORTED_ARCHS = $(ARMv5_ARCHS) $(OLD_PPC_ARCHS)`.

**Comment by th0ma7** [comment]
> I was a bit surprised it tries to build Python for `88f6281` (which fails), even though SABnzbd specifies `UNSUPPORTED_ARCHS = $(ARMv5_ARCHS) $(OLD_PPC_ARCHS)`.

Actually there's two totally different problems:
1. I thought @hgy59 had solve buildig py311 for armv5, I've re-started the github build as it may just be a "one of"
2. in the `.github/action/*` directory there's a use-case missing where if there isn't any package to be built for this arch, then don't even bother to build the perequisite package that where included in the build list (such as python or ffmpeg)... Unless it has to be managed at the matrix step from the `.github/workflows/build.yml`.  I believe it's @publicarray who wrote that part of the code, he may be able to provide hints on that?

**Comment by hgy59** [comment]
@th0ma7 in #6094 I found that ARMv5 fails to build some rust binaries. This is caused by rust >= 1.78 that has a hard dependency on libatomic.
It fails to build meson too, required by python (crossenv).

What shall we do? Should we nail rust to the latest 1.77.* version for all ARMv5 builds?

**Comment by th0ma7** [comment]
> in #6094 I found that ARMv5 fails to build some rust binaries. This is caused by rust >= 1.78 that has a hard dependency on libatomic. It fails to build meson too, required by python (crossenv).
> 
> What shall we do? Should we nail rust to the latest 1.77.* version for all ARMv5 builds?

Nice catch!  Indeed in `spksrc.cross-rust-env.mk` exists `RUSTUP_DEFAULT_TOOLCHAIN = stable` which could be set to a version specific under the ARMv5 definition.

Further looking at the code the `spksrc.tc-rust.mk` needs to make usage of that variable (current hardcoded as `rustup override set stable`).

That should be relatively easy to do.  I can try to create a quick PR for testing.

**Comment by Safihre** [comment]
Well, ARM v5 won't work for Sab anyway because unrar doesn't support it anymore. It needs C++11 minimum.

**Comment by th0ma7** [comment]
Indeed but ideally we can still resolve the py311 build issue for it so
checks are all green.  My new pr should solve that hopefully.

**Comment by th0ma7** [comment]
@Safihre would you mind rebasing against master now that my PR python311 fix is merged for armv5 no-atomic?  much thnx in advance.

**Comment by Safihre** [comment]
@th0ma7 worked!

**Review by th0ma7 — APPROVED** [review]

**Comment by Safihre** [comment]
Strange, when I rand the build to publish it suddenly failed for `qoriq` even though here it succeeded?!
https://github.com/Safihre/spksrc/actions/runs/9320470672

**Comment by th0ma7** [comment]
Sometimes it is just because it completed at the same time as another one and parallel uploading fails on our package server.  Just re-run failed ones.

**Comment by mreid-tt** [comment]
@th0ma7 I don't think the issue is the same as a failed upload. The build fails to complete in the first place:
```
2024.05.31 15:40:17 - python311: (qoriq-6.2.4) FAILED
2024.05.31 15:44:29 - sabnzbd: (qoriq-6.2.4) FAILED
```
Based on the logs I see this:
```
2024-05-31T15:44:29.3013483Z ===>  Extracting for cryptography
2024-05-31T15:44:29.3034629Z tar -xzpf /github/workspace/cross/cryptography/../../distrib/cryptography-41.0.3.tar.gz -C /github/workspace/spk/sabnzbd/work-qoriq-6.2.4 
2024-05-31T15:44:29.3376656Z ===>  Patching for cryptography
2024-05-31T15:44:29.3427929Z ===>  Configuring for cryptography
2024-05-31T15:44:29.3435266Z ===>  - Configure ARGS:
2024-05-31T15:44:29.3442999Z ===>  - Install prefix: /var/packages/sabnzbd/target
2024-05-31T15:44:29.3453374Z ===>  Installing for cryptography
2024-05-31T15:44:29.3503350Z find /github/workspace/spk/sabnzbd/work-qoriq-6.2.4/install//var/packages/sabnzbd/target/ \! -type d -printf '%P\n' | sed 's?^target/??g' | sort > /github/workspace/spk/sabnzbd/work-qoriq-6.2.4/cryptography.plist.tmp
2024-05-31T15:44:29.3616952Z ===>  Compiling for cryptography
2024-05-31T15:44:29.5675686Z Traceback (most recent call last):
2024-05-31T15:44:29.5677753Z   File "/github/workspace/native/python311/work-native/install/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
2024-05-31T15:44:29.5679382Z     return next(cls.discover(name=name))
2024-05-31T15:44:29.5680212Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31T15:44:29.5680765Z StopIteration
2024-05-31T15:44:29.5681020Z 
2024-05-31T15:44:29.5681698Z During handling of the above exception, another exception occurred:
2024-05-31T15:44:29.5682391Z 
2024-05-31T15:44:29.5682606Z Traceback (most recent call last):
2024-05-31T15:44:29.5684425Z   File "/github/workspace/spk/python311/work-qoriq-6.2.4/crossenv/build/lib/python3.11/site-packages/semantic_version/__init__.py", line 14, in <module>
2024-05-31T15:44:29.5686283Z     __version__ = version("semantic_version")
2024-05-31T15:44:29.5686966Z                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31T15:44:29.5688737Z   File "/github/workspace/native/python311/work-native/install/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 1008, in version
2024-05-31T15:44:29.5690387Z     return distribution(distribution_name).version
2024-05-31T15:44:29.5691091Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31T15:44:29.5692934Z   File "/github/workspace/native/python311/work-native/install/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
2024-05-31T15:44:29.5694627Z     return Distribution.from_name(distribution_name)
2024-05-31T15:44:29.5695363Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31T15:44:29.5697105Z   File "/github/workspace/native/python311/work-native/install/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
2024-05-31T15:44:29.5698555Z     raise PackageNotFoundError(name)
2024-05-31T15:44:29.5699544Z importlib.metadata.PackageNotFoundError: No package metadata was found for semantic_version
2024-05-31T15:44:29.5700345Z 
2024-05-31T15:44:29.5700709Z During handling of the above exception, another exception occurred:
2024-05-31T15:44:29.5701472Z 
2024-05-31T15:44:29.5701666Z Traceback (most recent call last):
2024-05-31T15:44:29.5702856Z   File "/github/workspace/spk/sabnzbd/work-qoriq-6.2.4/cryptography-41.0.3/setup.py", line 18, in <module>
2024-05-31T15:44:29.5703957Z     from setuptools_rust import RustExtension
2024-05-31T15:44:29.5705559Z   File "/github/workspace/spk/python311/work-qoriq-6.2.4/crossenv/build/lib/python3.11/site-packages/setuptools_rust/__init__.py", line 1, in <module>
2024-05-31T15:44:29.5706941Z     from .build import build_rust
2024-05-31T15:44:29.5708405Z   File "/github/workspace/spk/python311/work-qoriq-6.2.4/crossenv/build/lib/python3.11/site-packages/setuptools_rust/build.py", line 22, in <module>
2024-05-31T15:44:29.5709768Z     from semantic_version import Version
2024-05-31T15:44:29.5711258Z   File "/github/workspace/spk/python311/work-qoriq-6.2.4/crossenv/build/lib/python3.11/site-packages/semantic_version/__init__.py", line 18, in <module>
2024-05-31T15:44:29.5712823Z     __version__ = pkg_resources.get_distribution("semantic_version").version
2024-05-31T15:44:29.5713755Z                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31T15:44:29.5715321Z   File "/github/workspace/spk/python311/work-qoriq-6.2.4/crossenv/build/lib/python3.11/site-packages/pkg_resources/__init__.py", line 478, in get_distribution
2024-05-31T15:44:29.5717374Z     dist = get_provider(dist)
2024-05-31T15:44:29.5717849Z            ^^^^^^^^^^^^^^^^^^
2024-05-31T15:44:29.5719312Z   File "/github/workspace/spk/python311/work-qoriq-6.2.4/crossenv/build/lib/python3.11/site-packages/pkg_resources/__init__.py", line 354, in get_provider
2024-05-31T15:44:29.5721116Z     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
2024-05-31T15:44:29.5721919Z                                             ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31T15:44:29.5723562Z   File "/github/workspace/spk/python311/work-qoriq-6.2.4/crossenv/build/lib/python3.11/site-packages/pkg_resources/__init__.py", line 909, in require
2024-05-31T15:44:29.5725081Z     needed = self.resolve(parse_requirements(requirements))
2024-05-31T15:44:29.5725805Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31T15:44:29.5727451Z   File "/github/workspace/spk/python311/work-qoriq-6.2.4/crossenv/build/lib/python3.11/site-packages/pkg_resources/__init__.py", line 795, in resolve
2024-05-31T15:44:29.5729144Z     raise DistributionNotFound(req, requirers)
2024-05-31T15:44:29.5730536Z pkg_resources.DistributionNotFound: The 'semantic_version' distribution was not found and is required by the application
2024-05-31T15:44:29.5970446Z make[3]: *** [../../mk/spksrc.python-wheel.mk:47: build_python_wheel_target] Error 1
2024-05-31T15:44:29.5971568Z make[3]: Leaving directory '/github/workspace/cross/cryptography'
2024-05-31T15:44:29.5974262Z make[2]: *** [../../mk/spksrc.depend.mk:54: depend_target] Error 2
2024-05-31T15:44:29.5975259Z make[2]: Leaving directory '/github/workspace/spk/sabnzbd'
2024-05-31T15:44:29.5995572Z make[1]: *** [../../mk/spksrc.supported.mk:75: build-arch-qoriq-6.2.4] Error 1
2024-05-31T15:44:29.5996714Z make[1]: Leaving directory '/github/workspace/spk/sabnzbd'
2024-05-31T15:44:29.5999934Z make: *** [../../mk/spksrc.publish.mk:40: publish-arch-qoriq-6.2.4] Error 2
2024-05-31T15:44:29.6000995Z make: Leaving directory '/github/workspace/spk/sabnzbd'
2024-05-31T15:44:29.6126726Z make: Entering directory '/github/workspace/spk/sabnzbd'
2024-05-31T15:44:29.6488042Z rm -fr work work-* build-*.log publish-*.log status-*.log
2024-05-31T15:44:29.9106217Z make: Leaving directory '/github/workspace/spk/sabnzbd'
```

**Comment by th0ma7** [comment]
This is odd, further as it worked initially on two pr.  @Safihre can you re-run failed build?

**Comment by Safihre** [comment]
Unfortunately, same result 
https://github.com/Safihre/spksrc/actions/runs/9320470672/job/25684361784#step:7:20

**Comment by th0ma7** [comment]
I'll try to have a look at it over the weekend.

**Comment by th0ma7** [comment]
This is odd, looking at the github-action build logs, this should normally be the trigger for `qoriq` toolchain:
```
===>  Target powerpc-unknown-linux-gnuspe unavailable...
```
When this is seen normally shortly thereafter it should trigger the dependency processing for the toolchain such as:
```
===>  Processing dependencies of syno-qoriq
===>  Downloading files for rust-qoriq
===>    wget --secure-protocol=TLSv1_2 --timeout=30 --waitretry=0 --tries=5 -nv https://github.com/SynoCommunity/spksrc/releases/download/toolchains%2Frust%2F1.77.0-nightly/stage2_powerpc-unknown-linux-gnuspe.txz
2024-06-03 19:33:44 URL:https://objects.githubusercontent.com/github-production-release-asset-2e65be/2565137/e6d63626-804a-429a-a5a1-414e20a13e00?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240603%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240603T193336Z&X-Amz-Expires=300&X-Amz-Signature=08a21a1b5afca29fd056be433666d6d970f2e710e144875e0788abbcb5071952&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=2565137&response-content-disposition=attachment%3B%20filename%3Dstage2_powerpc-unknown-linux-gnuspe.txz&response-content-type=application%2Foctet-stream [102497448/102497448] -> "stage2_powerpc-unknown-linux-gnuspe.txz.part" [1]
===>  Verifying files for rust-qoriq
===>    Checking sha1sum of file stage2_powerpc-unknown-linux-gnuspe.txz
===>    Checking sha256sum of file stage2_powerpc-unknown-linux-gnuspe.txz
===>    Checking md5sum of file stage2_powerpc-unknown-linux-gnuspe.txz
/home/spksrc/armv5-rust/spksrc/native/rust-qoriq/../../distrib/stage2_powerpc-unknown-linux-gnuspe.txz
===>  Processing dependencies of rust-qoriq
===>  Extracting for rust-qoriq
tar -xpf /home/spksrc/armv5-rust/spksrc/native/rust-qoriq/../../distrib/stage2_powerpc-unknown-linux-gnuspe.txz -C /home/spksrc/armv5-rust/spksrc/native/rust-qoriq/work-native/install//usr/local
===>  Patching for rust-qoriq
===>  Installing for rust-qoriq
find /home/spksrc/armv5-rust/spksrc/native/rust-qoriq/work-native/install//usr/local/ \! -type d -printf '%P\n' | sed 's?^target/??g' | sort > /home/spksrc/armv5-rust/spksrc/native/rust-qoriq/work-native/rust-qoriq.plist.tmp
export PATH="/home/spksrc/armv5-rust/spksrc/distrib/cargo/bin:${PATH}" ; \
export RUSTUP_HOME="/home/spksrc/armv5-rust/spksrc/distrib/rustup" ; \
which rustup ; \
rustup toolchain link stage2-powerpc-unknown-linux-gnuspe /home/spksrc/armv5-rust/spksrc/native/rust-qoriq/work-native/install/usr/local ; \
rustup show
/home/spksrc/armv5-rust/spksrc/distrib/cargo/bin/rustup
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/spksrc/armv5-rust/spksrc/distrib/rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
1.77.2-x86_64-unknown-linux-gnu
stage2-powerpc-unknown-linux-gnuspe

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.78.0 (9b00956e5 2024-04-29)

find /home/spksrc/armv5-rust/spksrc/native/rust-qoriq/work-native/install//usr/local// \! -type d -printf '%P\n' | sed 's?^target/??g' | sort | \
  diff /home/spksrc/armv5-rust/spksrc/native/rust-qoriq/work-native/rust-qoriq.plist.tmp -  | grep '>' | sed 's?> ??g' > /home/spksrc/armv5-rust/spksrc/native/rust-qoriq/work-native/rust-qoriq.plist
```

But that is entirely skipped somehow... I will have to figure out how to replicated this.

@hgy59 I'm running LXC/LXD on my end, are you runing docker and may be able to replicated this?  which may be, again, related to the `/spksrc` or `/worspace` root directory?  Easy way to tell is, from the master branch, just run `make arch-qoriq-6.2.4` from for `spk/python311` directory (or using -C argument)

**Comment by hgy59** [comment]
> EDIT: I may have found where the issue may be ... IF the `native/rust-qoriq` is being cached, it won't reprocess it again, therefore not re-installing the rust toolchain ... Fix could be:

related to #6054 ?

**Comment by th0ma7** [comment]
@hgy59 yup, i believe this is the case...

**Comment by th0ma7** [comment]
@Safihre potential fix now merged on master https://github.com/SynoCommunity/spksrc/pull/6123

Can you update your branch and re-launch a build and see how things turns out for `qoriq`?

**Comment by Safihre** [comment]
Worked!
https://github.com/Safihre/spksrc/actions/runs/9373704014

Thanks a lot for your help every time! 👍👍

**Comment by th0ma7** [comment]
Awesome!  :rocket: Now let's hope it suffice for all github-action caching scenarios...

**Comment by mreid-tt** [comment]
@Safihre will you be publishing the `qoriq` package to the repo now that it's working?

**Comment by Safihre** [comment]
Oh thought it was an unsupported arch 😱

**Comment by Safihre** [comment]
Oh now that I trigger a build with publishing it failed again:
https://github.com/Safihre/spksrc/actions/runs/9141936527/job/25136968455
Cache? I can try to run it from master instead of the branch, since the code is in there.

**Comment by mreid-tt** [comment]
@Safihre, I've triggered a run on your behalf and it built and published successfully: https://github.com/mreid-tt/spksrc/actions/runs/9381360715/job/25830726706

**Comment by th0ma7** [comment]
That's something to keep an eye on wetter it fixes things for good or not for qoriq building.  Ping me if you notice this again.

**Comment by Safihre** [comment]
> @Safihre, I've triggered a run on your behalf and it built and published successfully: https://github.com/mreid-tt/spksrc/actions/runs/9381360715/job/25830726706

Sounds like a cache problem. Thanks!

**Pull request merged**
