### PR TITLE
Update ntopng to version 4.2

### LINKED ISSUE #3984: [Package Request] ntopng
Name: ntopng
Description: ntopng is the next generation version of the orginal ntop, a network traffic probe that monitors network usage.
Websites: https://www.ntop.org/ https://github.com/ntop/ntopng
Software documentation: https://www.ntop.org/guides/ntopng/
Build/Installation documentation: https://www.ntop.org/guides/ntopng/what_is_ntopng.html#installation
Source code: https://github.com/ntop/ntopng
License: GPL3, Community Edition

In this thread https://github.com/ntop/ntopng/issues/2118 I asked howto update the Synology package from 3.8.1.1 to 4.0 (stable version), because there's an issue of seeing the Top HTTP Sites. 

**So a package request for ntopng version 4.0.**
Version 3.8.1.1 is made by contributor hgy59. (many thanks to him!)

Another question: Do I need **nprobe** for using ntopng on a Synology DS216+II?
**If so, how to do?**

Thanks in advance!!

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  Update was needed part of #4211 so now trying to update to latest version available.
_Linked Items:_  #4254 (zeromq duplicate removal). Closes #3984

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### TODO
- [x] Update `CHANGELOG` to better reflect all the sub-package changes
- [x] Update `lua` package version
- [x] ~Update src/GeoLite2.mmdb.zip~
- [x] review `rw_locks` to enable them on [x64](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/Documentation/features/locking/queued-rwlocks/arch-support.txt?h=v4.4.59)
- [x] review `-Wno-address-of-packed-member` compiler removal
- [x] Find issue with `qoriq` arch
- [x] Find issue with `88f6281` arch

### CODE REVIEW

**Comment by th0ma7** [comment]
@hgy59 as you are the maintainer, heads-up on this PR.
It now build properly on `x64`.  Will require rework on `rw_locks` potentially.
At first glance it looks like installing & upgrading OK but it fails to login so can't really test functionality for now.
Haven't investigated the issue yet but now happy it does build!

**Comment by th0ma7** [comment]
It actually run really well.  Clearly was needed some sleep, the issue was my password change that I had forgotten.
It looks like running really well and is actually much more user friendly than 3.x branch.  Looks promising.

**Comment by hgy59** [comment]
@th0ma7 thanks for setting this up. I never succeeded to build this version until now.

regarding your TODO: Update src/GeoLite2.mmdb.zip
I bundled the latest public available db GeoLite2.mmdb.zip. Since 2020 you cannot download updated db without a login.
So there is nothing to do here.

**Comment by th0ma7** [comment]
@hgy59 give it a shot, it runs surprisingly well...

**Comment by th0ma7** [comment]
@hgy59 is there a way I can provide a link from the build artifacts of github-action so a user can test it out (e.g. #3984)

**Comment by hgy59** [comment]
> 
> 
> @hgy59 is there a way I can provide a link from the build artifacts of github-action so a user can test it out (e.g. #3984)

You find a "packages" link on the github action page.
Example for [`Build #679`](https://github.com/SynoCommunity/spksrc/suites/1446984597/artifacts/24608604)

There is always a single artifact file containing all spk files of all successfully built archs.

**Comment by hgy59** [comment]
> 
> @hgy59 give it a shot, it runs surprisingly well...

Yes, surprising 🥇. I tested on a very limited DS115j. The interaction is slow, but just works.

The version 4.2 is really new (just 2 days off). With version 4.0 I never succeeded to build (nDPI vs. ntopng).

Thanks for your good work.

**Review by hgy59 — CHANGES_REQUESTED** [review]
LGTM
just needs a rebase to include #4254

**Comment by th0ma7** [comment]
> LGTM
> just needs a rebase to include #4254

My nvme just died... lacking a PC for a few days.

**Review by hgy59 — APPROVED** [review]

**Comment by th0ma7** [comment]
@hgy59 I just noticed you had updated `lua` to latest in background, good call and thnx.
Now merged.  Package release will have to wait a bit until my RMA comes in unless you want to take it off the #4211 list yourself.

**Comment by khashashin** [comment]
@th0ma7 and @hgy59 Thanks guys for the great work.
Can I refer to the official documentation when configuring the Synology version of ntopng?

I have a Fritz!Box router on my home network and I want to use this script [(ntopng fritzdump.sh docs)](https://github.com/ntop/ntopng/blob/dev/doc/README.fritzbox) to monitor the WAN interface. I tested this script on my Mac OS and to achieve the successful run, I had to do the following:
1. stop the currently running ntopng: `sudo launchctl unload /Library/LaunchDaemons/org.ntop.ntopng.plist`.
2. start the script `fritzdump.sh`: `sudo ntopng/tools/fritzdump.sh <username> <password>`
3. launch ntopng: `sudo launchctl load /Library/LaunchDaemons/org.ntop.ntopng.plist`

After that I was able to see the traffic in the stdin interface:
image

So, my question is, could I login to my Synology 920+ through SSH (or using Task Scheduler) and do the steps above which I've done for Mac OS?

**Comment by hgy59** [comment]
@khashashin I don't know wheter the fritzdump.sh will run on your diskstation, but you can try...
To stop/start ntopng you can use the stop/start button in the package center of your diskstation.
Or on the command line use `sudo synopkg stop ntopng` and `sudo synopkg start ntopng`.

But please consider: there will be no ntopng package available in DSM 7, as starting ntopng needs root access.

**Comment by khashashin** [comment]
@hgy59 Thank you for your reply! I already have an upgrade to DSM 7 :(
I think the only way to me is to look at ntopng Docker version.

**Pull request merged**
