### PR TITLE
toolchains: added DSM 6.2 toolchains and updated digests

### PR DESCRIPTION
**Pull request by march42**
_Motivation:_ added new toolchains for DSM 6.2
_Linked issues:_ Optionally, add links to existing issues or other PR's

### Checklist
- [] Build rule `all-supported` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
@Safihre If you compare with DSM 5.x toolchains, you will find that it often refers to first "retrocompatible" firmware version for which corresponding arch has been delivered.
For completeness, I do agree to include DSM 6.2 toolchains as far as packages built with them are announced as DSM 6.1 compatible (firmware version) - I intentionally forgot DSM 6.0 because "spksrc" missed it and there is no reason (I am aware of) why a DSM 6.0 system has not been upgraded to DSM 6.1 now.

**Comment by Safihre** [comment]
Oke sounds good!

**Comment by Safihre** [comment]
So should we merge this?

**Comment by ymartin59** [comment]
I have not check firmware versions declared in toolchains yet...

**Comment by th0ma7** [comment]
I noticed that a new toolchain was made available online for 6.2.2.

It happen that I have hope to port the media tree over to spksrc based/using b-rad-NDi/Embedded-MediaDrivers project.  In order to have that fully functional it needs latest DSM kernel verison and to be built against the latest toolchain (or be built against multiple kernels+toolchains versions to have a variety of offering).

Also, while the toolchain looks the same, is it really?  I'm actually guessing that fixes for various recent flaws where backported to the gcc4 compiler used by synology in order to properly mitigate them.  If that's the case (and I believe it is, correct me if I'm wrong), using latest toolchain would make even more sense.

**Comment by RafaelKa** [comment]
Hello folks,
could somebody explain why closed without merging?

**Pull request closed without merging**
