### PR TITLE
add plexpy

### PR DESCRIPTION
**Pull request by cytec**
_Linked issues:_ cleanup and squash of https://github.com/SynoCommunity/spksrc/pull/2263

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

Edit: @SynoCommunity/developers any changes?

### CODE REVIEW

**Comment by Dr-Bean** [comment]
If you really want to make changes: There's one empty line too many in `postinst`, and maybe the config file should contain the full path to Git, just to make sure it's available (I think we do that for other packages, e.g. Headphones, SB, Couch), not sure that plexpy supports setting a path for it though.
Nothing that should keep you from merging, so get on with it ;)

**Comment by Dr-Bean** [comment]
...and probably add the firewall entry in the wiki.

**Comment by Dr-Bean** [comment]
FYI, package should be on the repo, not active yet though.

**Comment by cytec** [comment]
yup i already uploaded it but didn't activate it

**Comment by kevindelaney** [comment]
@cytec Any idea when you plan to activate this? Eager to start using it :)

**Comment by cytec** [comment]
@kevindelaney just published it ;)

**Comment by kevindelaney** [comment]
Thanks @cytec but it doesn't work on my ds214 - it says Failed to Run Package Service and the logs are empty. Not familiar with how to debug/log collect for syno packages, but I imagine you'll want to track this in a separate issue. Do you have a repo for this package or should I post an issue in this one?

Cheers

**Comment by cytec** [comment]
@kevindelaney DSM6? see: https://github.com/SynoCommunity/spksrc/issues/2216

**Comment by mrsorbate** [comment]
Hey,

i´m on DSM 5.2 and same problem. Every time when I start the app its already stop but without error. On DSM 6 the error shows "failed to run package service".

**Pull request merged**
