### PR TITLE
Tvheadend 4.3 dev

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  Having issues with current 4.2.x version of tvheadend which is quite behind current development branch.  In lack of having an official 4.4 version yet I thought I'd be creating a 4.3-dev package in the meantime.  Hopefully I'll be able to confirm if my issue is now solved.
_Linked issues:_  I'll re-edit and enter my relevant bugs entry.

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### Notes:
- This is mainly for review and comments.
- I'm not satisfied with the git version schema I'm using, proposals welcome
- Package was created using 4.2.8 skeleton which overall applied quite well with a few changes
- Usage of 4.3-dev branch is now compatible with latest version of `libhdhomerun` which is also included as part of this pull request
- Upgrade from 4.2.8 to 4.3 did actually worked out

Thnx in advance.

### CODE REVIEW

**Comment by th0ma7** [comment]
After quite a bit of testing I recommend releasing a first set of packages using provided patchset, perhaps tagged as beta?

**Comment by th0ma7** [comment]
For interested, temporary testing packages available here:
https://github.com/th0ma7/synology/tree/master/packages

**Comment by ymartin59** [comment]
As tvheadend package depends on dynamic linking to ffmpeg libraries, upgrading ffmpeg requires also tvheadend publishment... and I am still relunctant to publish "non released" application version.

**Comment by th0ma7** [comment]
From the look of things TVH 4.2 was released more than two years ago while 4.3 dev branch keeps moving along and, from what I can see, there isn't any announcement for a 4.4 release soon.
https://tvheadend.org/versions/60

Recent 4.3 snapshots tends to be so much more reliable than 4.2 official release.  I think the SynoCommunity would much appreciate having monthly/quarterly "beta" snapshots provided considering the long delay at getting a new official version out.

**Comment by ymartin59** [comment]
@th0ma7 Rebase was almost impossible because of multiple crossed merge between master, ffmpeg and tvheadend branches... I have to play with "merge --squash", cherry-pick and rebase to create this single commit with your own authorship.
I have also replaced version, revision and package location to consider it as an upgrade. I hope I did not make too big mistake.
I am currently building and testing.

**Comment by m4tt075** [comment]
It is really, really nice to see all the advancements and improvements you guys have introduced in the last couple of months! Very well done, indeed!

**Comment by th0ma7** [comment]
@m4tt075 thnx!  you are very welcomed to join back the effort :)

> I have also replaced version, revision and package location to consider it as an upgrade. I hope I did not make too big mistake.

@ymartin59 Do you want me to have a second look at what was pushed to master before releasing?

**Comment by ymartin59** [comment]
@th0ma7 I agree for a quick last review before merging. But I am quite confident now and have decided to publish.

**Pull request merged**
