### PR TITLE
Bazarr: Initial release (0.9.6)

### LINKED ISSUE #3535: [Package Request] Bazarr
Name: Bazarr
Description: Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements. You define your preferences by TV show or movies and Bazarr takes care of everything for you.

Website: https://github.com/morpheus65535/bazarr
Source code: https://github.com/morpheus65535/bazarr
License: GNU GPL v3

### PR DESCRIPTION
**Pull request by smaarn**
_Motivation:_  Creating initial bazarr spk
_Linked issues:_  Fixes #3535. Supersedes #4629 , #4453, #4547

Includes:

* New version of `gevent` (21.x)
* New version of `greenlet` (1.x)
* New version of `libev` (4.33 as opposed to current 4.22 used by `ffsync`)
* `zope.event`: 4.5.0
* `gevent-websocket`: 0.10.1

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by altanir84** [comment]
Thanks for doing this! I tried installing on my DS418 (DSM 7) the aarch64 7.0 but it did not work. The app option to repair it did not work.  Is this a bug or the DSM 7 isn't compatible?

**Comment by smaarn** [comment]
> Thanks for doing this! I tried installing on my DS418 (rtd1296, DSM 7) the aarch64 7.0 but it did not work. The app option to repair it did not work.  Is this a bug or the DSM 7 isn't compatible? 

Actually I didn't have DSM 7 installed so I couldn't test it. It has only be available on my NAS last week and I haven't had the time to install (and migrate existing apps).
Would you be able to send out the failing logs so I try investigating ?

**Comment by altanir84** [comment]
> > Thanks for doing this! I tried installing on my DS418 (rtd1296, DSM 7) the aarch64 7.0 but it did not work. The app option to repair it did not work.  Is this a bug or the DSM 7 isn't compatible?
> 
> Actually I didn't have DSM 7 installed so I couldn't test it. It has only be available on my NAS last week and I haven't had the time to install (and migrate existing apps).
> Would you be able to send out the failing logs so I try investigating ?

I'll gladly do it, once I figure out how to get such detailed logs. The log center only displays 'System failed to start [Bazarr].'

**Comment by smaarn** [comment]
Superseded by #4896

**Pull request closed without merging**
