### PR TITLE
readme update

### PR DESCRIPTION
**Pull request by Dr-Bean**
As per https://github.com/SynoCommunity/spksrc/issues/1727, a proposal for the README.

~~Setup-Development-Environment~~ Part of README
~~User FAQ~~ Done, see https://github.com/SynoCommunity/spksrc/wiki/Frequently-Asked-Questions
~~Probably a separate `Contribute` article (maybe merge with Developers HOW-TO)~~ Added CONTRIBUTING.md
~~https://github.com/SynoCommunity/spksrc/wiki/spksrc-example~~ Added. More or less a placeholder, that article is probably a separate project in terms of effort...

Todo, but non-blocking at this point:
- Permissions (in time, link to a new wiki with all the sc-* groups)

### CODE REVIEW

**Comment by Dr-Bean** [comment]
Live example here: https://github.com/Dr-Bean/spksrc/tree/readme_update btw.

**Comment by Diaoul** [comment]
GitHub as a nice feature which is a CONTRIBUTING file. It displays a warning for any user opening an issue inviting them to check this file before opening the issue. I think this is great for anything related to contributions.
Live example: https://github.com/Diaoul/subliminal/issues/new
Maybe we can put contribution instructions in the CONTRIBUTING file and install/setup instructions in the README? (or links to the wiki)

**Comment by Dr-Bean** [comment]
Sure, as long as its effective ;) You'll have more experience with that. I moved the `Issues` and `Package Requests` sections to the top of the README hoping that it would at least help in setting some standards.

So we move the complete sections of `Issues`, `Package Requests` and `Contribute` from README to CONTRIBUTING.md, and move the to-be-created `Setup Development Environment` back to the README. Maybe add a small section referring to CONTRIBUTING for issues and requests at the end of the README.

**Comment by Diaoul** [comment]
Yes, I'd say a big reference for CONTRIBUTING is required at the top of the  :)

**Comment by Dr-Bean** [comment]
Added CONTRIBUTING.md and moved some stuff around. I did refer to it at the bottom of the README, hadn't seen your comment yet ;)

**Comment by Dr-Bean** [comment]
Corrections for Docker:
* Clone spksrc:
`git clone https://github.com/synocommunity/spksrc ~/spksrc`
* Start:
`docker run -it -v ~/spksrc:/spksrc synocommunity/spksrc /bin/bash`

**Comment by Dr-Bean** [comment]
@Diaoul @cytec Maybe you two could take a look, see if there's no glaring errors or o
ther comments.
Otherwise, I think this is good to go. If need be, we can discuss additional documentation/changes via #1727.

**Comment by cytec** [comment]
looks good to me

**Comment by Diaoul** [comment]
LGTM, we'll amend if needed.

**Pull request merged**
