### PR TITLE
framework: fix busybox start-stop-daemon support for service

### PR DESCRIPTION
**Pull request by ymartin59**
- discard non relevant options, add pid file
- run as root in conf/privilege for DSM 6
- fix status return codes

_Linked issues:_ #3387 #3094

### CODE REVIEW

**Comment by Safihre** [comment]
So I understand correctly that the problem was that it doesn't run as root?

**Comment by ymartin59** [comment]
Not only. `HOME` environment variable was not set even with use of `env`. So my usage of `export` in `service_prestart`.

**Comment by Safihre** [comment]
:+1:

**Comment by ymartin59** [comment]
Sorry. I tried to publish two PRs at the same time and one has just "vanished" (don't know where/why) and explain why you cannot understand what was behind. So I now have to rebase your branch from #3094 with my changes for review...

**Pull request merged**
