### PR TITLE
Switch nzbget spk to nzbgetcom version

### PR DESCRIPTION
**Pull request by phnzb**
## Description

Switch package to nzbgetcom (https://nzbget.com) version

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [X] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by Safihre** [comment]
The current nzbget package has been abandoned and development has been taken over by nzbgetcom. This new version automatically picks up the Config from the old one, since it's basically the same program.
@mreid-tt does this one also need the Share refactor like you did for SABnzbd? Probably right?  we'd probably need to help them a little bit then.

**Comment by hgy59** [comment]
> The current nzbget package has been abandoned and development has been taken over by nzbgetcom. This new version automatically picks up the Config from the old one, since it's basically the same program.

Thanks @Safihre for explaining the need of the switch.

**Comment by Safihre** [comment]
@luckedea @phnzb just to be sure: you still support Linux kernel 2.6+ with the installer, like previous nzbget, right? Synology systems run on ancient software..
Then I can just merge and publish this so Synology users get their much needed update.

**Comment by Safihre** [comment]
Then I'll merge and publish!

**Comment by Herozen1** [comment]
NZBget is failed to start on DSM 6.2.4-25556 Update 7 on 213+ after installation. The older version was working well. Please give some solution. Or put the old NZBget back on thed repository.

Greetz Hennie

**Comment by hgy59** [comment]
> Or put the old NZBget back on thed repository.

The former version (20220406-29) is still available for manual download in our repository (https://synocommunity.com/package/nzbget)

For a manual downgrade without uninstall, you find guidance in the FAQ of our wiki.

**Comment by phnzb** [comment]
@hgy59 @Herozen1
We don't yet build some architectures for our nzbget installer (v22+): mipsel / mipseb / ppc6xx / ppc500 - due to lack of real devices to test it and DS213+ is a PPC device. Support for required architectures will be added soon.
I will post update when it is ready for test.

**Comment by Herozen1** [comment]
@hgy59 @phnzb 
Thanks. Version Version 20220406-29 installed and its work as a charm.

**Comment by Herozen1** [comment]
@phnzb Where can I find the test build?

**Comment by phnzb** [comment]
@Herozen1  When installing or updating to `20240115-30`, select `Latest testing (beta) NZBGet version`

**Pull request merged**
