### PR TITLE
fix syncthing arm compile issues

### PR DESCRIPTION
**Pull request by cytec**
this should fix https://github.com/SynoCommunity/spksrc/issues/1628

### CODE REVIEW

**Comment by Dr-Bean** [comment]
With this patch, I get an `illegal instruction [core dump]` when running `/usr/local/syncthing/bin/syncthing`.

If I'm not mistaken, the environment variable should be used when compiling go for linux/arm, not for Syncthing itself (although it wouldn't hurt)
The approach used by syncthing itself might be helpful: https://github.com/syncthing/build/blob/master/Dockerfile. The Syncthing issue tracker has had some discussions on ARM arches as well.

**Comment by cytec** [comment]
so if i got everything right we'll have to set `GOARM=5` in `native/go` to support armv5... that should work on armv6 and armv7 too but will use softfloat instead of the supported hardware floating point (at least for armv6 and armv7)

**Comment by cytec** [comment]
@Dr-Bean i've reverted the `cross/syncthing` changes and patched native go instead, can you test if it is working now?

**Comment by Dr-Bean** [comment]
Ok, did a bit of testing. It looks like both the previous patch and this one need to be combined, as well as not stripping the binary file.

My suggestion: add `ENV += GOARM=5` to the cross package near L52 : it should not affect non-ARM arches anyway. We can't use `GOARM=7` for other ARM arches right now, because that would mean setting up a new linux/arm build, and the current approach does not support more than one.

Two notes on that: 
- Maybe there's a way around that, by setting up a cross/go package and building go per arch, or something like that. If not, we'd be limiting all go packages for ARM arches to ARMv5. Since Syncthing is the only package using go atm, we're not in a rush with that, but still, that would be nice to have.
- The native build needs a fix somewhere to specify the host/default arch, because you can't build native/go from the SPK when starting off with an ARM arch. Probably passing on an environment variable for x86 would help with that.

As for not stripping the binary, use `rsc:` instead of `bin:` for the PLIST.

**Comment by Dr-Bean** [comment]
...although, the web interface doesn't seem to want to work for some weird reason. I'll come back to this later.

**Comment by Dr-Bean** [comment]
Ok, that's on my end: If you manually start Syncthing without the proper arguments, it'll overwrite the predefined config.xml with the defaults.
So, my earlier comments should fix the arm build.

**Comment by cytec** [comment]
@Dr-Bean so... revert the reverted patch again? (include `ENV += GOARM=5` in `cross/syncthing`) and change `bin:` to `rsc:`?

**Comment by Dr-Bean** [comment]
The thing is, the package (for ARMv5 that is) is still broken with those changes. I haven't looked at it further after discovering it's stuck in a loop of stopping/starting over and over. 
There's an error log, but I assume that the issue occurs due to the way we compile Go and Syncthing, so the log wouldn't seem very helpful.

I was considering copying the whole process syncthing uses (use https://github.com/calmh/gonative for starters, and compare their Docker repo with your approach), but I'll probably won't get to that very soon.

As for the 2nd note, what I mean is this: do a `make clean` on `native/go`, then go to `spk/syncthing` and compile a non-x86 arch, e.g. `make arch-88f6281-5.1`. 
You'll see `make` attempt to build `native/go` (which it should) but that does not succeed. Usually that occurs when incorrect makeflags are passed on. A fix in a similar vein has recently been made to the `mono` package: https://github.com/SynoCommunity/spksrc/commit/e8a9af782dc0699ec841b3fac52427fad90ff676, although Go would probably use environment variables.
We should probably clean all flags when starting a native build or something like that, but that's very low prio.

**Comment by Diaoul** [comment]
So this is still broken right? Does it at least work for some archs?

**Comment by Dr-Bean** [comment]
Works for all but ARMv5 arches. Note that Syncthing does provide a working binary for ARMv5, so it's something on our side.

**Comment by Dr-Bean** [comment]
This PR does seem to work in combination with Syncthing 0.11.10 on ARMv5, so I think we'll go ahead and merge this while updating Syncthing too.

**Pull request merged**
