### PR TITLE
navidrome: initial package release

### LINKED ISSUE #4973: [Package Request] Navidrome
* Name: Navidrome
* Description: Open source music server
* Website: https://www.navidrome.org/
* Software documentation: https://www.navidrome.org/docs/
* Build/Installation documentation: https://www.navidrome.org/docs/installation/
* Source code:  https://github.com/navidrome/navidrome/
* License: GPL-3.0 License

### PR DESCRIPTION
**Pull request by hgy59**
## Description

- add navidrome 0.47.5
- patch taglib wrapper c++ code for DSM 6

Closes #4973

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] New Package

### CODE REVIEW

**Comment by hgy59** [comment]
@rfporter when you're still interested in navidrom on synology diskstations you can download the package built by github action.

_navigate: Checks / Build / Artifacts_ 
and download for the arch of your diskstation.
see [Package-Archs](https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures) to find the arch of your diskstation.

**Comment by lews-therin** [comment]
is there a blocker for this MR to be merged? would be great to have this by default on the package manager

**Comment by yabisiktir** [comment]
Hey hgy59! I was using the 0.47-3 previously, once I upgraded the package to the 0.51-1 version, i am not able to use the web interface anymore, giving me a "404 page not found" instead (restarting the application did not work) I'm on DS215j on DSM 7.1. Is this a known issue, or a misconfiguration/misfortune from my setup side?

**Comment by hgy59** [comment]
> Hey hgy59! I was using the 0.47-3 previously, once I upgraded the package to the 0.51-1 version, i am not able to use the web interface anymore, giving me a "404 page not found" instead (restarting the application did not work) I'm on DS215j on DSM 7.1. Is this a known issue, or a misconfiguration/misfortune from my setup side?

There was never a Version 0.47-3 by this PR. It started at 0.47.5-1 and is now updated to 0.52.5-1.
@yabisiktir are you still looking for navidrome package?
The current build is 0.52.5-1 and is built with nodejs v20.
If the update does not bring back the web interface, you could try to uninstall and do a new installation of the package.

**Pull request merged**
