### PR TITLE
[Mono] Update to 5.4.1.6 (fixes #2808)

### LINKED ISSUE #2808: [Update Request] Mono
Requesting an update to Mono 5 as per https://github.com/Jackett/Jackett/issues/1454#issuecomment-310906029

### PR DESCRIPTION
**Pull request by m4tt075**
_Motivation:_ Requested update to fix compatibility issues with packages that depend on mono (Jackett in this case)
_Linked issues:_ #2808 

_Notes:_ 
- PowerPC architectures not supported (as prior to the update)
- Thanks to @freddy36 and @kaso17 for various fixes and improvements
- Thanks to @Safihre for building and testing 
- I don't use `mono` myself so cannot test it. See #2808 for testing reports.

### Checklist
- [ ] Build rule `all-supported` completed successfully (5.2)
- [ ] Build rule `all-supported` completed successfully (6.1)
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by m4tt075** [comment]
@ymartin59 @cytec @KaraokeStu Technically, this PR is pretty straightforward (see changes). The testing results are not 100% clear though (see #2808). Not sure how you want to deal with this. We could wait for more feedback reports, or publish as beta and have it tested as such. Whatever you think makes sense. Just let me know how you want to proceed...

**Comment by m4tt075** [comment]
New commit added to fix btls support, based on user feedback. The fix breaks `88f6281` (apparently a known problem). Surprisingly `hi3535` does build. Edits above. I propose to wait for more user feedback  in #2808 before proceeding. Will check back in a couple of days to see where this goes...

**Comment by ymartin59** [comment]
@m4tt075 May you please propose a PR with stable release 5.4.1 http://www.mono-project.com/docs/about-mono/releases/5.4.1/ and contact users to test with this "downgraded" version.
I really prefer to avoid to deliver too much bug fixes...

**Comment by m4tt075** [comment]
@ymartin59 Downgraded to latest release as requested. Testing is needed. Tracking of testing feedback via #2808. Will squash once tests are successful.

**Comment by kianrafiee** [comment]
Hello m4tt075. By chance is it possible for you to create a jackett package for rtd1269 even though its not supported yet? I tried to compile one but it wont start in package center even with a mono 5.x compiled package that works with radarr and sonarr.

**Comment by kianrafiee** [comment]
Hello m4tt075. By chance is it possible for you to create a jackett package for rtd1269 even though its not supported yet? I tried to compile one but it wont start in package center even with a mono 5.x compiled package that works with radarr and sonarr.

**Comment by Safihre** [comment]
@kianrafiee 
Have you tried https://github.com/Safihre/spksrc/releases/tag/mono-4-dsm61 and
https://github.com/Safihre/spksrc/releases/tag/jackett-1-dsm61?

This DSM6 stuff even gets people to compile packages themselves.. Should get things up and running soon!

**Comment by kianrafiee** [comment]
@Safihre I haven't tried either because even though you have an rtd1269 version of jackett, you don't have an rtd1269 version of that mono 4.x listed.

**Comment by Safihre** [comment]
Ah yes, I see how that @m4tt075 [already tried](https://github.com/SynoCommunity/spksrc/issues/2808#issuecomment-346548993) for rtd1269 but is having problems with a different part of the library.

**Comment by kianrafiee** [comment]
I compiled a mono 5.x version yesterday that seems to work. Sonarr and radarr seem to work fine with it. Only thing is when I installed it in package center I got a big dialog box about CA Certificate that I couldnt find scroll all the way down on nor find the close/Done button for. But once I found the right tab/enter combo I got it to dissapear and it showed it as running. Maybe I actually have a borked version?

**Comment by kianrafiee** [comment]
Also, I actually got kaso17 from Jackett repo to assist me yesterday. He had me run jackett in debug mode and it actually was operational and could be updated to latest version. However, I cannot start it from package center, only run in debug mode which wont be of much use to me. Seems he was going to elaborate on what to do next(talking about changing a variable) but I think he was busy last night. Here is the issue: [Issue #1985](https://github.com/Jackett/Jackett/issues/1985)

**Comment by m4tt075** [comment]
@kianrafiee @Safihre Could you please continue these discussions in the Issues section? The PR section is for development and immediate discussions of the code contained in the PR only. Thank you.

**Comment by ymartin59** [comment]
@m4tt075 To avoid pop message in DSM, please redirect `cert-sync` command output to `/dev/null` (will be log file with new installer script later)

**Comment by m4tt075** [comment]
@ymartin59 Done. Not tested, but should be ok...

**Comment by m4tt075** [comment]
@ymartin59 Compilation fixes for `88f6281` and `rtd1296`, thanks to @freddy36 and @kaso17. I ran some compile tests, which succeeded. Should go through community testing again...

**Comment by ymartin59** [comment]
@m4tt075 Mono now supports PowerPC, so it may be worth giving it another trial: http://www.mono-project.com/docs/about-mono/supported-platforms/powerpc/

**Comment by Safihre** [comment]
@kaso17 Is there a way to get BTLS support for PowerPC archs? 
I tried building `mono` for it but it fails: https://travis-ci.org/Safihre/spksrc/builds/310501365#L5162

**Comment by kaso17** [comment]
@Safihre the official boringssl repo only seems to support 64bit PPC, not the old ones.
I don't thing mono is going to happen for old 32 PPC platforms.
mono has been supporting PPC for a long time, I'm wondering why the 4.8 release already wasn't supported for syno. There might be more issues besides just BTLS support.

**Comment by kaso17** [comment]
How long does it usually take until PRs get accepted?
I've a PR ready for jackett but it depends on this PR.

**Comment by Safihre** [comment]
@m4tt075 @ymartin59 This one is now good to go, with `qoriq` not being supported all other platforms work!

**Comment by m4tt075** [comment]
@kaso17 Agreed. There is probably not much value in starting to support old PPC platforms now, when they have not been supported in the past. And many thanks for all your inquiries and fixes! 
@Safihre Thanks for all the builds and your support.
@ymartin59 I have squashed all commits. Please take a last look at the squashed changes, #2808 for the test results and merge if you consider this PR sufficiently mature. If you want me to include a beta flag for the time being to be on the safe side, fine as well. Please just let me know...

**Pull request merged**
