### PR TITLE
Bump Gitea to v1.18.0

### PR DESCRIPTION
**Pull request by cweagans**
## Description

Keep gitea up to date - v1.18.0

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by cweagans** [comment]
I'm not sure how to do the things in the README + I'm not 100% sure that I have time to take that on, but hopefully this is helpful. I based the changes on the [previous Gitea PR](https://github.com/SynoCommunity/spksrc/pull/5454).

**Comment by wkobiela** [comment]
Hey @cweagans you could bump to 1.18.1 https://github.com/go-gitea/gitea/releases/tag/v1.18.1 since this PR was not merged yet :)

**Comment by wkobiela** [comment]
Or even 1.18.2 :) https://github.com/go-gitea/gitea/releases/tag/v1.18.2

**Comment by hgy59** [comment]
> but we will need to update dependencies (git >= 2.39.1)

git 2.39.1-26 is now published.

**Comment by wkobiela** [comment]
I think I cannot update this PR but I tested this https://github.com/wkobiela/spksrc/commits/v1.18.2 changes and it works fine on DSM7

**Comment by hgy59** [comment]
superseeded by #5624

**Pull request closed without merging**
