### PR TITLE
Update bitlbee to 3.4.1

### PR DESCRIPTION
**Pull request by CondormanFr**
For  issue #1863

### CODE REVIEW

**Comment by Dr-Bean** [comment]
One commit would be preferred. Have you tested it?

**Comment by CondormanFr** [comment]
Sorry for the multiple commit. I'm a new user of Github.

**Comment by CondormanFr** [comment]
Test seems OK. See #1863

**Comment by FoUStep** [comment]
Tested it on my DS212J without any troubles so far.

**Pull request merged**
