### PR TITLE
update curl to fix usage of ca certificates

### LINKED ISSUE #4032: Transmission 3.0 "Could not connect to tracker" and remote port is closed
Something is wrong with transmission 3.0. I always geyt " Could not connect to tracker" and remote port is closed (but is forwarded i my router). This version couldnt use proper network connection from my DSM. Version 2.94 works just fine. This is not file permission issue (torrents are adding to transmission and preallocate properly)

_Originally posted by @qubabos in https://github.com/SynoCommunity/spksrc/issues/3996#issuecomment-642884549_

### LINKED ISSUE #4084: SSL library compilation for Transmission 3.0
Transmission 3.0 - seems in the last package for Synology the ssl library is not compiled so the https announce is not working
Some trackers are require this so for them connection is not working 
Is possible a new compilation with ssl included?

### PR DESCRIPTION
**Pull request by hgy59**
_Motivation:_  As fixed for git with #4012 this is a general issue with cross/curl
_Linked issues:_  closes #4032, fixes #4084

### Checklist
_for checked packages: see list below Remarks._
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### Remarks
The target of this PR is to update all related packages to use the DSM bundled ca certificates.
- [x] domoticz
- [x] git
- [x] icecast
- [ ] jackett
- [x] lidarr
- [x] ntopng
- [x] nzbdrone (sonarr)
- [x] python
- [x] python3
- [x] radarr
- [ ] rutorrent (configures cert.pem in .rtorrent.rc)
- [x] transmission

### CODE REVIEW

**Comment by hgy59** [comment]
@ymartin59 this is ready to merge.
jacket and rutorrent are out of scope of this PR.

**Comment by ymartin59** [comment]
@hgy59 I propose to merge even if GH builds fail after timeout... I guess there are too many large packages to build at the same time.

**Comment by ymartin59** [comment]
Publish CheckList:
- [ ] domoticz
- [x] git
- [ ] icecast
- [ ] jackett
- [ ] lidarr
- [ ] ntopng
- [ ] nzbdrone (sonarr)
- [ ] python
- [ ] python3
- [ ] radarr
- [ ] rutorrent (configures cert.pem in .rtorrent.rc)
- [x] transmission

**Comment by ymartin59** [comment]
@hgy59 I have merged but GH has not appreciated: https://github.com/SynoCommunity/spksrc/actions/runs/191975314

**Pull request merged**
