### PR TITLE
Jackett: add libstdc++ to .NET builds and curl to mono builds

### PR DESCRIPTION
**Pull request by publicarray**
_Motivation:_  Fix .NET builds where the Synology DSM has an older libstdc++
_Linked issues:_  #4446 #4207

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

@Wuszek would you be willing to test this package?

(I copied `ldd` from my host system)

<details>
<summary>ldd output</summary>

```bash
root@dsm6 ~# LD_LIBRARY_PATH=/var/packages/jackett/target/lib/ ldd /var/packages/jackett/target/share/jackett
	linux-vdso.so.1 (0x00007fff7e91f000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x00007f2b867f7000)
	libdl.so.2 => /lib/libdl.so.2 (0x00007f2b865f3000)
	libstdc++.so.6 => /var/packages/jackett/target/lib/libstdc++.so.6 (0x00007f2b86270000)
	libm.so.6 => /lib/libm.so.6 (0x00007f2b85f6b000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x00007f2b85d5a000)
	libc.so.6 => /lib/libc.so.6 (0x00007f2b859b4000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x0000562870a13000)
root@dsm6 ~# ldd /var/packages/jackett/target/share/jackett
/var/packages/jackett/target/share/jackett: /lib/libstdc++.so.6: no version information available (required by /var/packages/jackett/target/share/jackett)
/var/packages/jackett/target/share/jackett: /lib/libstdc++.so.6: no version information available (required by /var/packages/jackett/target/share/jackett)
/var/packages/jackett/target/share/jackett: /lib/libstdc++.so.6: no version information available (required by /var/packages/jackett/target/share/jackett)
/var/packages/jackett/target/share/jackett: /lib/libstdc++.so.6: no version information available (required by /var/packages/jackett/target/share/jackett)
	linux-vdso.so.1 (0x00007ffcae51e000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x00007f821ba78000)
	libdl.so.2 => /lib/libdl.so.2 (0x00007f821b874000)
	libstdc++.so.6 => /lib/libstdc++.so.6 (0x00007f821b582000)
	libm.so.6 => /lib/libm.so.6 (0x00007f821b27d000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x00007f821b06c000)
	libc.so.6 => /lib/libc.so.6 (0x00007f821acc6000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x000056391dd43000)
```
</details>

### CODE REVIEW

**Comment by publicarray** [comment]
You can find a test build here: https://github.com/publicarray/spksrc/releases/tag/jackett-0.17.668

**Comment by Wuszek** [comment]
@publicarray just upgraded from previous package using aarch64.spk. Everything looks to work fine. 


<details><summary>Part of jackett_install.log</summary>

```
Thu Mar 11 08:25:56 CET 2021
===> Step preupgrade. USER=jackett GROUP= SHARE_PATH=
Thu Mar 11 08:25:57 CET 2021
===> Step preuninst. USER=jackett GROUP= SHARE_PATH=
Thu Mar 11 08:25:59 CET 2021
===> Step postuninst. USER=jackett GROUP= SHARE_PATH=
Thu Mar 11 08:26:00 CET 2021
===> Step preinst. USER=jackett GROUP= SHARE_PATH=
Thu Mar 11 08:26:02 CET 2021
===> Step postinst. USER=jackett GROUP= SHARE_PATH=
Installing service configuration /var/packages/jackett/conf/jackett.sc
Granting 'sc-jackett' unix ownership on /volume1/@appstore/jackett/var
Thu Mar 11 08:26:02 CET 2021
===> Step postupgrade. USER=jackett GROUP= SHARE_PATH=
Granting 'sc-jackett' unix ownership on /volume1/@appstore/jackett/var
```
</details>


<details><summary>Part of jackett.log</summary>

```
Thu Mar 11 08:26:09 CET 2021
Starting jackett command env HOME=/volume1/@appstore/jackett/var PATH=/volume1/@appstore/jackett/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin LD_LIBRARY_PATH=/volume1/@appstore/jackett/lib /volume1/@appstore/jackett/share/jackett --PIDFile /volume1/@appstore/jackett/var/jackett.pid 
03-11 08:26:11 Info Starting Jackett v0.17.668 
03-11 08:26:14 Info Environment version: 5.0.4 (/volume1/@appstore/jackett/share/) 
03-11 08:26:14 Info OS version: Unix 4.4.59.0 (64bit OS) (64bit process) 
03-11 08:26:14 Info Jackett variant: CoreLinuxArm64 
03-11 08:26:14 Info Running in Docker: No 
03-11 08:26:14 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
03-11 08:26:14 Info App config/log directory: /volume1/@appstore/jackett/var/.config/Jackett 
03-11 08:26:14 Info Using proxy: Disabled 
03-11 08:26:14 Info Using FlareSolverr: No 
03-11 08:26:14 Info Using HTTP Client: HttpWebClient2 
03-11 08:26:14 Info Loading Native indexers ... 
03-11 08:26:16 Info Loaded 96 Native indexers: abnormal, alpharatio, anidex, anidub, AniLibria, animebytes, Animedia, animetorrents, anthelion, avistaz, bakabt, bb, bitcityreloaded, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, darmowetorenty, dicmusic, digitalcore, divxtotal, elitetracker, epublibre, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, internetarchive, iptorrents, libble, lostfilm, magnetico, mejortorrent, milkie, morethantv, myanonamouse, ncore, nebulance, newpct, norbits, notwhatcd, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, secretcinema, shazbat, ShizaProject, showrss, solidtorrents, speedapp, speedcd, subsplease, superbits, thepiratebay, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentleech, torrentmafya, torrentnetwork, torrent-paradise-ml, torrentscsv, torrentseeds, torrentsyndikat, tvstore, tvvault, xspeeds, xthor, yts, zonaq, animetosho 
03-11 08:26:16 Info Loading Cardigann indexers from: /volume1/@appstore/jackett/var/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /volume1/@appstore/jackett/share/Definitions 
03-11 08:26:33 Info Loaded 443 Cardigann indexers: torrentparadise, metaltracker, mnv, magnet4you, uniondht, extratorrent-cd, torrentland, mixtapetorrent, galeriens, hdolimpo, vsttorrents, gaytorrentru, lemonhd, acrossthetasman, teracod, rintornet, turkseed, byrutor, extremlymtorrents, idope, gtorrentpro, asylumshare, myspleen, animeclipse, firebit, proporno, sktorrent-org, hdbitscom, torrent-turk, magico, Bittorrentfiles, mypornclub, anisource, cpasbienclone, rainbowtracker, torrenthr, datascene, beitai, mteamtp, pier720, beyond-hd-oneurl, romanianmetaltorrents, mma-torrents, torrentdb, ilcorsaroblu, hdme, ttsweb, hon3yhd, torrentlt, haidan, kinozal, arenabg, shellife, vsthouse, underverse, xwtorrents, hqsource, filebase, libranet, boxingtorrents, bitru, torrentsectorcrew, newstudio, hamsterstudio, desitorrents, rutor, mononokebt, casatorrent, 52pt, oxtorrent, zelkaorg, marinetracker, torrent9clone, pwtorrents, hdcity, pussytorrents, aniRena, thefallingangels, piratbit, bit-titan, linkomanija, montorrent, insanetracker, jpopsuki, ebookparadijs, 0daykiev, racing4everyone, pornforall, witchhunter, 3changtrai, torrentqq, ourbits, pornorip, sporthd, muziekfabriek, divteam, tjupt, booktracker, aither, torrent4you, iv-torrents, puntotorrent, puurhollands, hdzone, hdtime, arabp2p, piratadigital, thevault, borgzelle, lepornoinfo, tasmanit, carpathians, 2fast4you, desireleasers, snowpt, thehorrorcharnel, r3vwtf, yggcookie, p2pbg, bluebirdhd, hdhome, pornotor, hdturk, acgrip, legittorrents, piratbitl, dimeadozen, netcosmo, tellytorrent, unionfansub, scenepalace, btnext, noname-club, torrentccf, exkinoray, animeworld, ptsbao, tokyotosho, madsrevolution, lesaloon, portugas, springsunday, hdatmos, beyond-hd, totheglory, crazyhd, siambit, nethd, ccfbits, pornleech, lastfiles, hdchina, gktorrent, scenerush, isohunt2, btsow, hd4fans, chilebt, torrentsurf, dragonworldreloaded, cilipro, thegeeks, ilcorsaronero, fanoin, gamestorrents, xiteme, limetorrents, theleachzone, anaschcc, greekteam, sdbits, rus-media, xwtclassics, zooqle, torrentmax, bootytape, totheglorycookie, kinorun, torrentleech-pl, vizuk, bwtorrents, bitturk, yggtorrent, pctorrent, torrentz2k, uhdbits, extremetorrents, moviesdvdr, theempire, twilightszoom, erzsebetpl, legacyhd, hdroute, onejav, xxxtorrents, sexypics, rptorrents, bt4g, ehentai, ibit, pixelcove, audionews, gay-torrentsorg, hddolby, onlineselfeducation, torrentproject, xxxadulttorrent, acgsou, shareisland, newretro, sharewood, frozenlayer, anime-free, hdforever, trackeros, danishbytes, hdbits, tvchaosuk, eztv, tjangto, cpasbien, pornbay, newstudiol, speedmasterhd, mactorrents, soulvoice, pornolive, generationfree, rustorka, btdigg, torrentoyunindir, learnflakes, rapidzona, bithorlo, sukebeinyaasi, btetree, empornium, teamos, sdkino, yourbittorrent, microbit, greekdiamond, kickasstorrents-ws, selezen, torrentdownload, racingforme, ebooks-shares, keepfriends, dariustracker, sukebei-pantsu, pttime, broadcity, rintor, abtorrents, ettv, hdu, exttorrents, nntt, freetorrent, focusx, majomparade, losslessclub, theshinning, hdspain, aftershock, nbtorrents, catorrent, lechaudron, finelite, gfxpeers, yingk, bithumen, 3dtorrents, Das-Unerwartete, pterclub, proaudiotorrents, itorrent, hdonly, speedtorrentreloaded, epizod, hush, torrentv, torrentview, torrentfactory, diablotorrent, btschool, film-paleis, ptfiles, extremebits, classix, xbytesv2, sportscult, audiobookbay, 7torrents, crazyspirits, esharenet, coastalcrew, pthome, rutracker-ru, nitro, hdcenter, prostylex, linuxtracker, zetorrents, tapochek, asiancinema, immortuos, theshow, amigosshare, torrent-explosiv, kickasstorrents-to, torrenting, oncesearch, baibako, genesismovement, cinemamovies, oshenpt, xxxtor, gigatorrents, trezzor, RockBox, acidlounge, u2, sugoimusic, riperam, bitspyder, tekno3d, crnaberza, erzsebet, uniongang, mesevilag, concen, femdomcult, omgwtftrackr, bigfangroup, parnuxi, 1ptbar, dark-shadow, trupornolabs, 1337x, teamhd, cinemageddon, seedfile, trancetraffic, carphunter, emtrek, hdtorrentsit, tribalmixes, wdt, torrentwhiz, hdsky, skytorrents-to, girotorrent, peersfm, pirateiro, torrent9, torlock, ztracker, netlab, pleasuredome, purovicio, hdc, turktorrent, pornbits, chdbits, hdarea, deildu, mteamtp2fa, extratorrent-it, mvgroupforum, glodls, demonoid, theplace, horrorsite, 4thd, bibliotik, fouducinema, ydypt, tlfbits, polishsource, zamundanet, twilight, underversel, sktorrent, finvip, sosulki, funreleases, eniahd, kinonavse100, feedurneed, aidoruonline, p2pelite, dmhy, cinematik, concertos, torrent-pirat, unlimitz, efectodoppler, backups, spiritofrevolution, redstartorrent, btdb, torrentslocal, nyaasi, mvgroupmain, toros, woot, ptmsg, theaudioscene, dxp, torrentgalaxy, estone, torrentdownloads, arabafenice, karagarga, dxdhd, shokweb, gtorrent, hdhouse, totallykids, funkytorrents, fantasticheaven, jptv, hellastz, latinop2p, casstudiotv, darktracker, theoccult, blutopia, brasiltracker, empornium2fa, torrentfunk, nyaa-pantsu, gay-torrents, wihd, torrentkitty, torrentsir, torrentproject2, cartoonchaos, bigtorrent, torrentbd, noname-clubl, torrentz2 
03-11 08:26:33 Info Loaded 539 indexers in total 
03-11 08:26:33 Info Adding aggregate indexer ('all' indexer) ... 
03-11 08:26:34 Info Jackett startup finished in 25.053 s 
Hosting environment: Production
Content root path: /volume1/@appstore/jackett/share/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
```
</details>

Do you need anything else?

**Comment by publicarray** [comment]
Thanks @Wuszek! I just wanted to confirm that the libstdc++ fix works for you. :partying_face:

**Comment by pandavova** [comment]
Didn't work on my DS415play (evansport), this system also doesn't have ldd. 
(Is there btw an easy way to downgrade or is copying the configs, uninstalling, installing the working version, copying the configs back, the only way?)

jackett.log
```
Fri Mar 12 19:53:41 CET 2021
Starting jackett command
```

jackett_install.log
```
Fri Mar 12 19:46:09 CET 2021
===> Step preupgrade. USER=jackett GROUP= SHARE_PATH=
Fri Mar 12 19:46:11 CET 2021
===> Step preuninst. USER=jackett GROUP= SHARE_PATH=
Fri Mar 12 19:46:13 CET 2021
===> Step postuninst. USER=jackett GROUP= SHARE_PATH=
Fri Mar 12 19:46:13 CET 2021
===> Step preinst. USER=jackett GROUP= SHARE_PATH=
Fri Mar 12 19:46:15 CET 2021
===> Step postinst. USER=jackett GROUP= SHARE_PATH=
Installing service configuration /var/packages/jackett/conf/jackett.sc
Granting 'sc-jackett' unix ownership on /volume1/@appstore/jackett/var
Fri Mar 12 19:46:15 CET 2021
===> Step postupgrade. USER=jackett GROUP= SHARE_PATH=
Granting 'sc-jackett' unix ownership on /volume1/@appstore/jackett/var
```

**Comment by Wuszek** [comment]
@pandavova unfortunatelly you have to backup settings manually, uninstall package and install again, then upload old settings.

backup ServerConfig.json file and DataProtection and Indexers folders, which are in:
`/volume/@appstore/jackett/var/.config/Jackett/`

Remember, owner of this files/folder should be sc-jackett:jackett, and probably should have 644 permission (at least ServerConfig.json) so:
`chmod 664 ServerConfig`
`chown sc-jackett:jackett files`

**Comment by publicarray** [comment]
Thanks @pandavova for testing, `ldd` doesn't exist on any DSM, I just used to prove that the correct library was loaded because when I tested the package earlier I did not have an error with the older libstdc++ to begin with. Since you are on evensport none of .NET is relevant, you will still be on the mono version until there are no more updates. 

I've just pushed a commit that fixes the startup issue. I made a mistake while moving the script to our new generic startup script.

**Comment by pandavova** [comment]
The new .spk worked! Thank you. 

jacket.log
```
Sun Mar 14 00:50:32 CET 2021
Starting jackett command env HOME=/volume1/@appstore/jackett/var PATH=/volume1/@appstore/jackett/bin:/var/packages/mono/target/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin LD_LIBRARY_PATH=/volume1/@appstore/jackett/lib /var/packages/mono/target/bin/mono /volume1/@appstore/jackett/share/JackettConsole.exe --PIDFile /volume1/@appstore/jackett/var/jackett.pid
03-14 00:50:40 Info Starting Jackett v0.17.668
03-14 00:50:55 Info Environment version: 4.0.30319.42000 (/volume1/@appstore/mono/lib/mono/4.5)
03-14 00:50:55 Info OS version: Unix 3.2.40.0
03-14 00:50:55 Info Jackett variant: Mono
03-14 00:50:55 Info Running in Docker: No
03-14 00:50:55 Info ThreadPool MaxThreads: 400 workerThreads, 200 completionPortThreads
03-14 00:50:55 Info App config/log directory: /volume1/@appstore/jackett/var/.config/Jackett
03-14 00:50:55 Info Using proxy: Disabled
03-14 00:50:55 Info Using FlareSolverr: No
03-14 00:50:55 Info Mono version: 5.20.1.34 (tarball Wed Oct 14 10:29:55 UTC 2020)
03-14 00:50:56 Info TrustedRootCertificates count: 173
03-14 00:50:56 Info Using HTTP Client: HttpWebClient
03-14 00:50:56 Info Loading Native indexers ...
03-14 00:51:00 Info Loaded 96 Native indexers: abnormal, alpharatio, anidex, anidub, AniLibria, animebytes, Animedia, animetorrents, anthelion, avistaz, bakabt, bb, bitcityreloaded, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, darmowetorenty, dicmusic, digitalcore, divxtotal, elitetracker, epublibre, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, internetarchive, iptorrents, libble, lostfilm, magnetico, mejortorrent, milkie, morethantv, myanonamouse, ncore, nebulance, newpct, norbits, notwhatcd, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, secretcinema, shazbat, ShizaProject, showrss, solidtorrents, speedapp, speedcd, subsplease, superbits, thepiratebay, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentleech, torrentmafya, torrentnetwork, torrent-paradise-ml, torrentscsv, torrentseeds, torrentsyndikat, tvstore, tvvault, xspeeds, xthor, yts, zonaq, animetosho
03-14 00:51:00 Info Loading Cardigann indexers from: /volume1/@appstore/jackett/var/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /volume1/@appstore/jackett/share/Definitions
```

jacket_install.log 
```
Sun Mar 14 00:50:23 CET 2021
===> Step preupgrade. USER=jackett GROUP= SHARE_PATH=
Sun Mar 14 00:50:24 CET 2021
===> Step preuninst. USER=jackett GROUP= SHARE_PATH=
Sun Mar 14 00:50:25 CET 2021
===> Step postuninst. USER=jackett GROUP= SHARE_PATH=
Sun Mar 14 00:50:25 CET 2021
===> Step preinst. USER=jackett GROUP= SHARE_PATH=
Sun Mar 14 00:50:27 CET 2021
===> Step postinst. USER=jackett GROUP= SHARE_PATH=
Installing service configuration /var/packages/jackett/conf/jackett.sc
Granting 'sc-jackett' unix ownership on /volume1/@appstore/jackett/var
Sun Mar 14 00:50:27 CET 2021
===> Step postupgrade. USER=jackett GROUP= SHARE_PATH=
Granting 'sc-jackett' unix ownership on /volume1/@appstore/jackett/var
```

**Review by ymartin59 — APPROVED** [review]

**Pull request merged**
