### PR TITLE
Update go2rtc icon

### PR DESCRIPTION
**Pull request by AlexxIT**
## Description

Fixes # https://github.com/AlexxIT/go2rtc/blob/master/assets/logo.png

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Review by skrashevich — COMMENTED** [review]
You need to increment SPK_REV in Makefile

**Comment by skrashevich** [comment]
👍

**Comment by hgy59** [comment]
@AlexxIT please regard [CONTRIBUTING](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md) in our wiki.
You must create a dedicated branch for each pull request and not use the master branch of your repository. Otherwise your fork will get out of sync and you will get troubles on further development.

And IMHO it is not worth a package update just for the icon. We should wait for an updated release.

**Comment by AlexxIT** [comment]
Closing in favour of #6093

**Pull request closed without merging**
