### PR TITLE
Update SABnzbd to 3.3.1. Update Unrar to 6.0.1.

### PR DESCRIPTION
**Pull request by Safihre**
The build on GA fails due to `squidguard` being unable to fetch a dependency from Sourceforge.

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by Safihre** [comment]
@hgy59 Could you maybe review? 
The build on GA fails due to `squidguard` being unable to fetch a dependency from Sourceforge.

**Review by ymartin59 — APPROVED** [review]

**Comment by Safihre** [comment]
@hgy59 @th0ma7 how do I make this DSM 7 ready?
Is it only the folders? 
Is there some examples of using resource files for the shares? And how do I get the paths to those resources in the ini file so Sab wil use it?

**Comment by th0ma7** [comment]
@Safihre Actually there are a few.. details are in the remarks section of this PR https://github.com/SynoCommunity/spksrc/issues/4524 where you'll be able to find many examples from the check marks.

Main ones to check first check for are: the usual build fix for dsm7 due to gcc 7.3 compiler bug (not all packages needs it):
```
ifeq ($(call version_ge, ${TCVERSION}, 7.0),1)
CMAKE_ARGS += -DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_C99_MATH
endif
```
and the usual `${SYNOPKG_PKGVAR}` in `src/service-setup.sh` which points to `/var/packages/<package>/var` which previously was `${SYNOPKG_PKGDEST}/var` which was pointing to `/var/packages/<package>/target/var`

**Comment by hgy59** [comment]
> 
> 
> @hgy59 @th0ma7 how do I make this DSM 7 ready?
> Is it only the folders?
> Is there some examples of using resource files for the shares? And how do I get the paths to those resources in the ini file so Sab wil use it?

My work so far:
```
# parameters:
# $1 name of a share
# result:
# prints the path of the share (if exists)
get_path_of_share_name ()
{
    synoshare --get ${1} | grep "Path" | sed 's|.*Path.*\[\(.*\)\]|\1|g'
}

```

**Comment by Safihre** [comment]
@hgy59 Would it be possible to merge this and just publish it for DSM 6? It seems also from the recent discussions in #4524 that the shared resources approach we want to take for downloaders and Sonarr/Radarr/etc isn't ready yet.
And I would still like to get this to the end-users.

**Comment by Safihre** [comment]
@SynoCommunity/developers Can anyone please tell me what to do with this PR to get it merged and published? It's been open for 1.5 month and it's just a small update.

**Comment by publicarray** [comment]
Sorry I was away for a bit and there is so much to do with DSM7. I took this PR and made some changes on my branch to make it DSM7 compatible. Would you mind having a look? https://github.com/publicarray/spksrc/tree/sabnzbd330 I tried pushing it onto here but since I rebased from master I would need to force push.

**Comment by Safihre** [comment]
Superseded by #4748

**Pull request closed without merging**
