### PR TITLE
borgbackup: Bump borgmatic to 1.7.5 and solve pure-python msgpack problem

### LINKED ISSUE #5436: [Package Request]  Update borgbackup to borg version 1.2.2
### Software Name

borgbackup

### Brief Description

Borg version 1.2.1 is available as community package. This is only an update request. Thanks for making this package available.

### Website

https://github.com/borgbackup/borg/releases

### Documentation

https://borgbackup.readthedocs.io/en/stable/changes.html#change-log

### Build/Installation documentation

https://borgbackup.readthedocs.io/en/stable/

### Source code

https://github.com/borgbackup/borg

### OpenSource License

other (please specify below)

### Other License

BSD-3-clause

### PR DESCRIPTION
**Pull request by christophehenry**
## Description

Update borgbackup to 1.2.2. 
Also solves the pure-python msgpack problem which greatly reduces performance.
Update borgmatic to v1.7.5 and emborg to v1.34.

Closes #5436

## Checklist

- [x] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
@christophehenry we should also add msgpack to requirements-crossenv.txt as mentioned in https://github.com/SynoCommunity/spksrc/issues/5436#issuecomment-1272281406

**Comment by hgy59** [comment]
@christophehenry I have already worked on this, and will update your branch

**Review by hgy59 — APPROVED** [review]
@christophehenry thanks for contributing.

made just some minor adjustments.
the SPK_REV must be incremented for each package published (it must be greater than the last published package on https://synocommunity.com/packages)
I removed the obsolete pyrsistent module and updated the description on how to evaluate python module requirements
And meanwhile a newer borgmatic version is available

Can you please test the current build? _(I will be absent for about a week)_

**Comment by christophehenry** [comment]
Looks fine. Installation ok. Archive created without trouble.

**Comment by christophehenry** [comment]
I noticed a problem since yesterday: I performed a `borg prune` on the remote repo. Since then, every operation is so long that I can't let it run. The longest was a backup, it lasted 24h and ended with `MemoryError`. Not sure it's related to this update but I prefer to mention. I will reinstall the last stabled version to see if that solved the problem.

**Comment by bdr99** [comment]
Borg 1.2.3 is now released. Would it make sense to update this PR to use the new version 1.2.3 instead?

**Comment by christophehenry** [comment]
@hgy59 Any news on merging this?

**Pull request merged**
