### PR TITLE
Update to 4.8.22

### PR DESCRIPTION
**Pull request by 4sag**
_Motivation:_ Explain here what the reason for the pull request is.
_Linked issues:_ Optionally, add links to existing issues or other PR's

### Checklist
- [] Build rule `all-supported` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

### CODE REVIEW

**Comment by 4sag** [comment]
Update to 4.8.22

**Comment by 4sag** [comment]
update nano, mc, adminer.

**Comment by m4tt075** [comment]
@4sag I appreciate your contributions, but this is difficult to follow and to handle. It is unclear which compilations you have tried and which pacakges you have tested. In addition, I'm currently integrating `mc` and `nano` into our `SynoCLI-file`package (see PR #3250 for details), so the corresponding spks will go away anyways. 

Could you please do the following:
1) Close your PRs again.
2) Create a new branch, where you just update `adminer` (this is not being worked on to my knowledge)
3) Conduct the requested tests, in terms of cross-compiling for all platforms
4) Conduct a proper test whether the resulting package works, when it is installed cleanly and when you upgrade from an older version
5) Create a proper PR with description, where you detail all the information requested in the PR template?

**Comment by ymartin59** [comment]
@4sag I propose you to create a dedicated PR for "adminer" update. Thank you in advance for your help. Regards. Yves

**Pull request closed without merging**
