### PR TITLE
[WIP] WebGrab++ v2.1 - Initial release 

### PR DESCRIPTION
**Pull request by m4tt075**
_Motivation:_ I haven't been satisfied with EIT grabbers for Tvheadend on German and UK satellites and started looking for xmltv alternatives. Found WebGrab++, but no ready-made Synology package and no straightforward integration with Tvheadend for Synology systems. Played around and thought this might benefit others.
_Linked issues:_ None, than my own...

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by kekukui** [comment]
Yes I would like to test this.  Can we get it in the beta repo please?  I did not even notice this pull request, so I opened an issue 6 weeks ago. # https://github.com/SynoCommunity/spkrepo/issues/33

**Comment by m4tt075** [comment]
Sorry, this is not ready for beta. But you can download it from the link above. It works for me. It does require manual configuration though.

**Comment by kekukui** [comment]
```
admin@DiskStation:/volume1/@appstore/webgrabplus/bin$ ./run.sh

             WebGrab+Plus/w MDB & REX Postprocess -- version  V2.1

                                Jan van Straaten
                             Francis De Paemeleere

            thanks to Paul Weterings and all the contributing users
--------------------------------------------------------------------------------

Unhandled Exception

Access to the path "/var/packages/webgrabplus/target/var/WebGrab++.log.txt" is denied.

  at System.IO.File.Delete (System.String path) [0x00073] in <cb410c64c7fa4e8d9841a0cbe4173d66>:0
  at WGconsole.Program.ConsoleApplication (System.String[] args) [0x0025e] in <274ad6f9740e441a95b86a1d1148edca>:0
  at WGconsole.Program.Main (System.String[] args) [0x00016] in <274ad6f9740e441a95b86a1d1148edca>:0
For detailed info, see log file
Execution stopped
```

**Comment by m4tt075** [comment]
@kekukui I stopped developing this months ago and won't develop it further. As such, I'll close this PR. Sorry. If you (or somebody else) wants to revive this work, please fell free to do so... 

If your NAS supports Docker, there are webgrabplus and easyepg versions available, which work really well...

**Comment by kekukui** [comment]
@m4tt075 

> **there are webgrabplus and easyepg versions available**

1.  Thanks for this information, I am sure I will use one of them for something.
_______

2.  Here is the Docker compatibility list in case anyone needs it:

https://www.synology.com/en-us/dsm/packages/Docker
https://www.synology.com/en-us/dsm/feature/docker

How to install Docker on an unsupported Synology NAS (works on some models)
https://tylermade.net/2017/09/28/how-to-install-docker-on-an-unsupported-synology-nas/
_______

3.  If you want to grab XMLTV files, TV Headend requires this dependency -- can it be added to the Synology TVheadend package?
http://wiki.xmltv.org/index.php/XMLTVProjectDownload

grabber

`[Grabber Modules]` XMLTV :
_"This is an Internet-based suite of scripts that grab and manage television listings (see xmltv.org for more information). To make use of the internal XMLTV grabber you typically require the xmltv-utils package to be installed. If you install new grabbers you will need to restart Tvheadend._ **If you see no XMLTV grabbers listed then probably XMLTV is not properly installed** _and in the PATH."_
https://docs.tvheadend.org/webui/config_epggrab/

Related example
https://github.com/rocky4546/script.xmltv.tvheadend/wiki/Guide:-How-to-Setup-XMLTV-for-TVHeadEnd

**Pull request closed without merging**
