### PR TITLE
Fix compilation of native/go and update syncthing (includes #3412 and #3557)

### PR DESCRIPTION
**Pull request by hgy59**
_Motivation:_ Native go-1.4 does not build with newer compilers (like debian stretch on my build chain).
_Linked issues:_ https://github.com/golang/go/issues/16906

### Checks
- [x] Build rule `natives` completed successfully
- [x] Package syncthing build rule `all-supported` completed successfully
- [x] Package dnscrypt-proxy build rule `all-supported` completed successfully (except qoriq and ppc853x)
- [x] Package synocli-net build rule `all-supported` completed successfully (includes fritzctl except for qoriq and ppc853x, and ppc853x failed to build due /cross/fuse)
- [x] Syncthing firewall ports are configurable withing DMS control panel

### Remarks
- go version 1.4.x is still required for bootstrapping go
- update native/go-1.4 to go1.4-bootstrap-20171003 regarding [build go from source](https://golang.org/doc/install/source)
- update go to version 1.12
- update syncthing to version 1.1.0 (despite that syncthing may be updated within the syncthing app, the installed version is now built with go 1.12)
- ppc archs are not supported by go (dnscrypt-proxy should mark as unsupported)
- includes syncthing firewall port configuration provided by @acolomb

### CODE REVIEW

**Comment by acolomb** [comment]
Please also have a look at my long standing PR #3412. It also contains the most recent Syncthing release btw.

**Comment by hgy59** [comment]
@acolomb just added your first commit of #3412.
How can one verify the installation works as expected?
I do not have a productive syncthing config by now, so I could test a clean installation.

I assume your work on certificates is not finished yet (#3436) and you still propose to merge this "firwall port definition" part first.

**Comment by acolomb** [comment]
Thank you @hgy59.  After installation, the service should be able to start and the Web GUI reachable on port TCP/8384 via HTTPS.  A package upgrade is mostly a no-op really, because Syncthing itself keeps its binary up to date.  So when upgrading via SynoCommunity, the backed up config and database should just work because the same binary gets used after all.  Actually that makes me wonder if the Syncthing compilation step is really worth it, when the binary gets replaced by one from Syncthing's release page regularly?

Let's keep the certificate config stuff (#3436) separate.  I'm still waiting on Synology to update their developer information.  Opened a support ticket, but they're still busy catching up after Chinese New Year it seems.

**Comment by hgy59** [comment]
@acolomb need some instructions to verify the changes merged from you branch ("the firewall port definition" changes).

**Comment by acolomb** [comment]
Sorry, I misunderstood that point.  Go to `Control Panel -> Security -> Firewall -> Edit Rules -> Create -> Select from a list of built-in applications` and verify that there are three different Syncthing settings listed.

**Comment by hgy59** [comment]
no problem, made a new installation on DS-918+ (apollolake, x64) and DS-115j (armada370). Synchronisation between the two devices works like a charm.
Firewall settings are available (but I do not use the firewall on the diskstations).

**Comment by ymartin59** [comment]
@hgy59 Seems good to me. Minor fix: please do not make build fail when arch is not supported - but set variable UNSUPPORTED_ARCHS - typically as  $(PPC_ARCHS) - Ref https://github.com/SynoCommunity/spksrc/wiki/Makefile-variables

**Comment by ymartin59** [comment]
@hgy59 It includes #3557 without keeping author commit...
@alexanderharm Do you mind if your authorship is not kept after merge?

**Comment by alexanderharm** [comment]
@ymartin59 not at all

**Comment by hgy59** [comment]
@ymartin59 sorry, thought that UNSUPPORTED_ARCHS is for spk Makefile only. It's alway good to remember the documentation available ;-)
Just added the UNSUPPORTED_ARCHS and intentionally left the error reporting, for situations where new archs are defined (remember the introduction of ARMv8).

**Comment by ymartin59** [comment]
@hgy59 From my point of view, this can to be built and published. Any objection?

**Comment by hgy59** [comment]
@ymartin59 no objection, let it go...

**Pull request merged**
