### PR TITLE
Update Tvheadend to 4.2.3 (Release)

### PR DESCRIPTION
**Pull request by m4tt075**
### Motivation
Updates Tvheadend to latest maintenance release.

### Details
- Tvheadend updated to 4.2.3
- Obsolete `atomic32` and `iov-max` patches removed as upstreamed (Thanks, @perexg!)
- Shared ffmpeg cross package bumped to 3.3.2 in line with statically linked version within TVH
- `pngquant` option enabled via cross package (required adaption of PLIST file in libpng cross package)

### Notes
- This package contains a privilege file for DSM6 compatibility. It will therefore run into the same SynoCommunity publication issues as TVH 4.2.1 and TVH 4.2.2. See #2749 for related discussions.
- PR #2801 might resolve this issue but awaits review and testing. It is not affected by this update.
- After this upgrade, there are only two TVH-specific patches left: One fixing the version number in the TVH webinterface and one compatibility patch for old PPC platforms, which probably can be removed once these platforms run out of support. 

### Checklist
- [x] Build rule `all-supported` completed successfully with 5.2 toolchains
- [x] Build rule `all-supported` completed successfully with 6.1 toolchains (cherry-picked from @ymartin59, but dropped again for this commit)
- [x] Package upgrade completed successfully on `evansport-6.1`
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
@m4tt075 Sorry to disturb but `make arch-x64-5.2` fails for me with latest `master`. May you please check and confirm ?

```
CC              src/input/mpegts/linuxdvb/linuxdvb_ca.o
CC              src/descrambler/dvbcam.o
CC              src/descrambler/libaesdec/libaesdec.o
MKBUNDLE        bundle.c
Traceback (most recent call last):
  File "/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 201, in <module>
    idx = add_entry(ents)
  File "/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 180, in add_entry
    tmp = add_entry(ents[k], d, k, idx, p)
  File "/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 180, in add_entry
    tmp = add_entry(ents[k], d, k, idx, p)
  File "/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 180, in add_entry
    tmp = add_entry(ents[k], d, k, idx, p)
  File "/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 180, in add_entry
    tmp = add_entry(ents[k], d, k, idx, p)
  File "/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 174, in add_entry
    output_file(d, k, idx+1, p)
  File "/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 92, in output_file
    stdin=fd, stdout=fd, stderr=fd)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Makefile:744: recipe for target '/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/build.linux/bundle.c' failed
make[3]: *** [/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/build.linux/bundle.c] Error 1
make[3]: Leaving directory '/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3'
../../mk/spksrc.compile.mk:36: recipe for target 'compile_target' failed
make[2]: *** [compile_target] Error 2
make[2]: Leaving directory '/spksrc/cross/tvheadend'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory '/spksrc/spk/tvheadend'
../../mk/spksrc.spk.mk:418: recipe for target 'arch-x64-5.2' failed
make: [arch-x64-5.2] Error 2 (ignored)
```

**Comment by m4tt075** [comment]
@ymartin59: By all means, please _do_ disturb me if you find any issues. Unfortunately, I cannot reproduce though: I have just pulled master to be sure and `arch-x64-5.2` compiles without any issues:
> CC              src/descrambler/tvhcsa.o
 CC              src/descrambler/cwc.o
CC              src/descrambler/emm_reass.o
CC              src/descrambler/capmt.o
CC              src/descrambler/constcw.o
CC              src/input/mpegts/linuxdvb/linuxdvb_ca.o
CC              src/descrambler/dvbcam.o
CC              src/descrambler/libaesdec/libaesdec.o
MKBUNDLE        bundle.c
CC              bundle.o
Markdown: docs/markdown/markdown_cribsheet.md
Markdown: docs/markdown/status_service_mapper.md
Markdown: docs/markdown/configure_tvheadend.md
Markdown: docs/markdown/epg.md
Markdown: docs/markdown/features.md

[...]

> ===>  Preparing conf
src/conf/privilege
src/conf/PKG_CONX
/home/myvm/builds/spksrc/spk/tvheadend/work-x64-5.2/conf/privilege
/home/myvm/builds/spksrc/spk/tvheadend/work-x64-5.2/conf/PKG_CONX
(cd /home/myvm/builds/spksrc/spk/tvheadend/work-x64-5.2 && tar cpf /home/myvm/builds/spksrc/spk/tvheadend/../../packages/tvheadend_x64-5.2_4.2.3-10.spk --group=root --owner=root package.tgz INFO PACKAGE_ICON.PNG PACKAGE_ICON_256.PNG scripts WIZARD_UIFILES conf)
make[1]: Leaving directory '/home/myvm/builds/spksrc/spk/tvheadend'

I cross-compile in a Virtualbox environment `Linux ubuntu 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`. Please let me know if there is anything else I can do to help or support.

**Comment by manuelrn** [comment]
@m4tt075 I have the same problem that @ymartin59 comments. My console:

```
make[5]: se sale del directorio '/home/manuel/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3'
MKBUNDLE        bundle.c
Traceback (most recent call last):
  File "/home/manuel/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 201, in <module>
    idx = add_entry(ents)
  File "/home/manuel/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 180, in add_entry
    tmp = add_entry(ents[k], d, k, idx, p)
  File "/home/manuel/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 180, in add_entry
    tmp = add_entry(ents[k], d, k, idx, p)
  File "/home/manuel/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 180, in add_entry
    tmp = add_entry(ents[k], d, k, idx, p)
  File "/home/manuel/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 180, in add_entry
    tmp = add_entry(ents[k], d, k, idx, p)
  File "/home/manuel/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 174, in add_entry
    output_file(d, k, idx+1, p)
  File "/home/manuel/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/support/mkbundle", line 92, in output_file
    stdin=fd, stdout=fd, stderr=fd)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Makefile:744: fallo en las instrucciones para el objetivo '/home/manuel/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/build.linux/bundle.c'
make[4]: *** [/home/manuel/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3/build.linux/bundle.c] Error 1
make[4]: se sale del directorio '/home/manuel/spksrc/spk/tvheadend/work-x64-5.2/tvheadend-4.2.3'
../../mk/spksrc.compile.mk:36: fallo en las instrucciones para el objetivo 'compile_target'
make[3]: *** [compile_target] Error 2
make[3]: se sale del directorio '/home/manuel/spksrc/cross/tvheadend'
../../mk/spksrc.depend.mk:44: fallo en las instrucciones para el objetivo 'depend_target'
make[2]: *** [depend_target] Error 2
make[2]: se sale del directorio '/home/manuel/spksrc/spk/tvheadend'
../../mk/spksrc.spk.mk:392: fallo en las instrucciones para el objetivo 'latest-arch-x64'
make[1]: [latest-arch-x64] Error 2 (no tiene efecto)
make[1]: se sale del directorio '/home/manuel/spksrc/spk/tvheadend'
```

The last time I compiled tvheadend it worked fine, it was in this commit: https://github.com/SynoCommunity/spksrc/commit/ecc62722af6cc45722900a732bfe19a8be781db8


@m4tt075 if you can, try to make a new git clone in a new clean folder and then try to see if the compilation fails, cloning the repository cleanly today and then compile.

Thank you and sorry for my bad english!

**Comment by m4tt075** [comment]
@manuelrn : I have done what you suggested and created a new git clone in a clean folder. I still cannot reproduce the issue. It compiles fine for me. What build environment are you using? And you @ymartin59 ?

**Comment by manuelrn** [comment]
@m4tt075 I use Lubuntu 17.04 in VirtualBox.
uname -a
`Linux manuel-VirtualBox 4.10.0-28-generic #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Thank you!

**Comment by m4tt075** [comment]
@manuelrn : Hmh, strange. I don't think the openssl update caused the issue. Could you test the following, please?
1) Edit `cross/tvheadend/Makefile`
- Remove `cross/pngquant` from the second `DEPENDS` line
- Remove `--enable-pngquant` from the first `CONFIGURE_ARGS` line
- Save and exit
2) `make clean` and try again

**Comment by m4tt075** [comment]
@manuelrn: And another test (if you don't mind):

1. Check whether `/usr/bin/pngquant` is installed on your system
2. If not, please install pngquant
3. Undo the changes from the previous test and try again

**Comment by manuelrn** [comment]
@m4tt075 You misunderstand me, in this commit (openssl) to me it worked fine. What I wanted to say is that the last time I compiled tvheadend was when the last commit was for openssl, and everything worked fine.

I have tried both methods and both work!!
So it did not work because we did not have pngquant installed. @ymartin59 installs "pngquant" and it will work.

Thank you again ;)

**Comment by m4tt075** [comment]
@manuelrn : Great! Thanks a lot for testing and reporting!
@ymartin59 : I will do some more tests. Even if you install it and we can use it for the published versions here, it will still break compilation for those who cross-compile themselves and do not have pngquant installed (like for you guys). On the other hand, the only thing pngquant is used for, is to reduce the size of the bundle (this is why your compilations broke there). It does not change functionality of the package itself. I will test what we actually gain for the introduction of all these dependencies and see whether it is really worthwhile to keep them. Otherwise, I will just remove the option again.

**Pull request merged**
