### PR TITLE
headphones translation and permission doc

### PR DESCRIPTION
**Pull request by ymartin59**
Register service account as "users" member for transition

_Motivation:_ Get it ready to publish
_Linked issues:_ 

### Checklist
- [X] Build rule `all-supported` completed successfully
- [ KO ] Package upgrade completed successfully
- [ KO ] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
@Safihre I have built and tested package with hope it may run even with previous Python 2.7.13
But service fails to start with
```
Full log: /volume1/@appstore/headphones/var/logs/headphones.log
Sun Mar 18 11:34:25 CET 2018
Starting headphones command /volume1/@appstore/headphones/env/bin/python /volume1/@appstore/headphones/share/Headphones/Headphones.py --daemon --pidfile /volume1/@appstore/headphones/var/headphones.pid --config /volume1/@appstore/headphones/var/config.ini --datadir /volume1/@appstore/headphones/var/ 
18-Mar-2018 11:34:27 - INFO    :: MainThread : Checking to see if the database has all tables....
18-Mar-2018 11:34:27 - INFO    :: MainThread : Retrieving latest version information from GitHub
18-Mar-2018 11:34:28 - INFO    :: MainThread : Headphones is up to date
18-Mar-2018 11:34:28 - INFO    :: MainThread : Daemonized to PID: 20492
18-Mar-2018 11:34:28 - INFO    :: MainThread : Writing PID 20492 to /volume1/@appstore/headphones/var/headphones.pid
18-Mar-2018 11:34:28 - INFO    :: MainThread : Starting Headphones web server on http://0.0.0.0:8181/
Sun Mar 18 11:34:29 CET 2018
Stopping headphones service 20492 
18-Mar-2018 11:34:29 - INFO    :: MainThread : Signal 15 caught, saving and exiting...
18-Mar-2018 11:34:29 - ERROR   :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "/volume1/@appstore/headphones/share/Headphones/Headphones.py", line 235, in <module>
    main()
  File "/volume1/@appstore/headphones/share/Headphones/Headphones.py", line 207, in main
    headphones.start()
  File "/volume1/@appstore/headphones/share/Headphones/headphones/__init__.py", line 352, in start
    initialize_scheduler()
  File "/volume1/@appstore/headphones/share/Headphones/headphones/__init__.py", line 278, in initialize_scheduler
    from headphones import updater, searcher, librarysync, postprocessor, \
  File "/volume1/@appstore/headphones/share/Headphones/headphones/postprocessor.py", line 29, in <module>
    from beetsplug import lyrics as beetslyrics
  File "/volume1/@appstore/headphones/share/Headphones/lib/beetsplug/lyrics.py", line 30, in <module>
    from beets import config, ui
  File "/volume1/@appstore/headphones/share/Headphones/lib/beets/ui/__init__.py", line 36, in <module>
    from beets import library
  File "/volume1/@appstore/headphones/share/Headphones/lib/beets/library.py", line 32, in <module>
    from beets.util.functemplate import Template
  File "/volume1/@appstore/headphones/share/Headphones/lib/beets/util/functemplate.py", line 28, in <module>
    """
  File "/volume1/@appstore/headphones/share/Headphones/headphones/__init__.py", line 359, in sig_handler
    shutdown()
  File "/volume1/@appstore/headphones/share/Headphones/headphones/__init__.py", line 637, in shutdown
    SCHED.shutdown(wait=False)
  File "/volume1/@appstore/headphones/share/Headphones/lib/apscheduler/schedulers/background.py", line 37, in shutdown
    super(BackgroundScheduler, self).shutdown(wait)
  File "/volume1/@appstore/headphones/share/Headphones/lib/apscheduler/schedulers/blocking.py", line 22, in shutdown
    super(BlockingScheduler, self).shutdown(wait)
  File "/volume1/@appstore/headphones/share/Headphones/lib/apscheduler/schedulers/base.py", line 147, in shutdown
    raise SchedulerNotRunningError
SchedulerNotRunningError: Scheduler is not running
```
I really wonder why... but I guess it will have to wait for Python upgrade

**Comment by Safihre** [comment]
That's a weird error.. If you then upgrade the python package, the same headphone package suddenly does work?

**Comment by ymartin59** [comment]
@Safihre I confirm it runs properly with latest Python 2.7.14-18 on DSM 5.2. So it confirms I have to stack all applications in repository and enable everything at the same time... Probably when Python troubles are understood and fixed

**Comment by Safihre** [comment]
Unfortunate the problems are a complete mystery to me.
It's not clear to me if it's in `cross/cryptography` or in `cross/openssl`.
The compilation of `cross/cryptography` is supposed to pick-up the same flags as Python (for example `-pthread`), but for some reason it doesn't.

**Comment by ymartin59** [comment]
Superseed by #3316

**Pull request closed without merging**
