### PR TITLE
Update SABnzbd to 3.5.0

### PR DESCRIPTION
**Pull request by Safihre**
## Description

Fixes # 

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Review by th0ma7 — APPROVED** [review]
Looks good to me and thnx for your help on the python310 migration!
python 3.10 release had not occurred yet, I'll edit #5043 accordingly.
Cheers!

**Comment by Safihre** [comment]
@th0ma7 great. Will you merge and publish some time this week?

**Comment by th0ma7** [comment]
now published https://synocommunity.com/package/sabnzbd
Thnx again!

**Comment by Safihre** [comment]
Thank you! 👍

**Pull request merged**
