### PR TITLE
up PKG_DIST_SITE

### PR DESCRIPTION
**Pull request by icemanpro**

### CODE REVIEW

**Comment by KaraokeStu** [comment]
Hi, is there a particular reason we're not simply moving to a later version?

**Comment by KaraokeStu** [comment]
Also, please include more details about why you want to create the pull request and your reasons for doing so

**Comment by cytec** [comment]
@KaraokeStu i guess he changed the URL because openssl only hosts the latest version on the root directory. don't know what's speaking against an update though

**Comment by ymartin59** [comment]
Updating `openssl` version has impact on `ffmpeg` and `chromaprint` because `rtmpdump` has to be adapted to new API. I gave it a try and it was no easy.
By the way, I am interested in changing to a HTTP download location as FTP is closed on a network I use (https://github.com/ymartin59/spksrc/issues/1). Please switch to https://www.openssl.org/source/openssl-1.0.2l.tar.gz !

**Pull request closed without merging**
