### PR TITLE
Update setuptools and use `get-pip` correctly to fix Cryptography build

### PR DESCRIPTION
**Pull request by Safihre**
As discussed in #5307 and #4153.
Turns out we need to update `setuptools`.
I also found that our usage of `get-pip.py` was wrong: it can't be used to specify the pip version, it always installs whatever they have update the script to. 
But by skipping `setuptools` and `wheel` in `get-pip.py`, we can make sure we fix those versions at least.

Successful build of SABnzbd (setup and runs):
https://github.com/Safihre/spksrc/actions/runs/2514098758

### CODE REVIEW

**Comment by th0ma7** [comment]
@Safihre now I get it, great catch!  I recall seing messages that it was replacing a version with another on the subsequent install of wheel and setuptools and that explains it now.  Good job!

**Review by th0ma7 — APPROVED** [review]
I've restarted the github-action checks to confirm all is good but at first glance this LGTM.

**Comment by publicarray** [comment]
While it might look good (I'm no python wizard) it breaks building python3 and python38, so something is probably dependent on the old / possibly wrong /behaviour / version and needs fixing, These are important packages that should not fail.


```
Error: ERRORS:
2022.06.17 11:12:58 - domoticz: (armv7-7.0) FAILED
2022.06.17 12:27:14 - python3: (armv7-7.0) FAILED
2022.06.17 13:05:11 - python38: (armv7-7.0) FAILED
2022.06.17 14:09:02 - vim: (armv7-7.0) FAILED
See log file of the build job to analyze the error(s).
Last 15 lines of the build log:
$ make arch-armv7-7.0 -C ./spk/domoticz
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
make[4]: *** [Makefile:144: python38_post_install] Error 1
make[4]: Leaving directory '/github/workspace/cross/python38'
make[3]: *** [../../mk/spksrc.depend.mk:54: depend_target] Error 2
make[3]: Leaving directory '/github/workspace/cross/domoticz'
make[2]: *** [../../mk/spksrc.depend.mk:54: depend_target] Error 2
make[2]: Leaving directory '/github/workspace/spk/domoticz'
make[1]: *** [../../mk/spksrc.spk.mk:565: build-arch-armv7-7.0] Error 1
make[1]: Leaving directory '/github/workspace/spk/domoticz'
make: *** [../../mk/spksrc.spk.mk:559: arch-armv7-7.0] Error 2
make: Leaving directory '/github/workspace/spk/domoticz'
$ make arch-armv7-7.0 -C ./spk/python3
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
make[3]: *** [Makefile:103: python3_post_install] Error 1
make[3]: Leaving directory '/github/workspace/cross/python3'
make[2]: *** [../../mk/spksrc.depend.mk:54: depend_target] Error 2
make[2]: Leaving directory '/github/workspace/spk/python3'
make[1]: *** [../../mk/spksrc.spk.mk:565: build-arch-armv7-7.0] Error 1
make[1]: Leaving directory '/github/workspace/spk/python3'
make: *** [../../mk/spksrc.spk.mk:559: arch-armv7-7.0] Error 2
make: Leaving directory '/github/workspace/spk/python3'
$ make arch-armv7-7.0 -C ./spk/python38
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
make[3]: *** [Makefile:144: python38_post_install] Error 1
make[3]: Leaving directory '/github/workspace/cross/python38'
make[2]: *** [../../mk/spksrc.depend.mk:54: depend_target] Error 2
make[2]: Leaving directory '/github/workspace/spk/python38'
make[1]: *** [../../mk/spksrc.spk.mk:565: build-arch-armv7-7.0] Error 1
make[1]: Leaving directory '/github/workspace/spk/python38'
make: *** [../../mk/spksrc.spk.mk:559: arch-armv7-7.0] Error 2
make: Leaving directory '/github/workspace/spk/python38'
$ make arch-armv7-7.0 -C ./spk/vim
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
make[4]: *** [Makefile:144: python38_post_install] Error 1
make[4]: Leaving directory '/github/workspace/cross/python38'
Makefile:53: /github/workspace/spk/vim/work-armv7-7.0/python-cc.mk: No such file or directory
make[3]: *** [../../mk/spksrc.depend.mk:54: depend_target] Error 2
make[3]: Leaving directory '/github/workspace/cross/vim'
make[2]: *** [../../mk/spksrc.depend.mk:54: depend_target] Error 2
make[2]: Leaving directory '/github/workspace/spk/vim'
make[1]: *** [../../mk/spksrc.spk.mk:565: build-arch-armv7-7.0] Error 1
make[1]: Leaving directory '/github/workspace/spk/vim'
make: *** [../../mk/spksrc.spk.mk:559: arch-armv7-7.0] Error 2
make: Leaving directory '/github/workspace/spk/vim'
```

**Review by publicarray — CHANGES_REQUESTED** [review]
Good work! However, I would like the builds for python to succeed.

**Comment by Safihre** [comment]
I saw 😢 , making changes in a separate branch to fix. Will push when fixed :)

**Comment by Safihre** [comment]
@hgy59 @publicarray @th0ma7 I fixed `python38`, but `python3` kept failing. I checked and no `native`/`cross`/`spk` uses `python3` so I just.. removed it?
Any objections?

**Comment by th0ma7** [comment]
> but `python3` kept failing. I checked and no `native`/`cross`/`spk` uses `python3` so I just.. removed it? Any objections?

I double checked and indeed it doesn't looked used anymore.  So no objection at all besides updating python310 status page #5043

**Comment by Safihre** [comment]
Build succeeded:
https://github.com/Safihre/spksrc/actions/runs/2519752159

**Comment by hgy59** [comment]
@Safihre sorry, as I am too late for the show.
There is nothing wrong with `get-pip.py "pip==22.0.4"`

I have reintroduced this with #5318.

**Comment by hgy59** [comment]
> I also found that our usage of `get-pip.py` was wrong: it can't be used to specify the pip version, it always installs whatever they have update the script to.

Additional parameters to pip-get.py are documented https://github.com/pypa/get-pip

> Upon execution, `get-pip.py` will install `pip`, `setuptools` and `wheel` in the current Python environment.
>
>  It is possible to provide additional arguments to the underlying script. These are passed through to the underlying `pip install` command, and can thus be used to constraint the versions of the packages, or to pass other pip options such as `--no-index`.
>
>  ```console
>  $ python get-pip.py "pip < 21.0" "setuptools < 50.0" "wheel < 1.0"
>  $ python get-pip.py --no-index --find-links=/local/copies
>  ```

**Comment by Safihre** [comment]
Hmm, strange that I saw in the logs that it wasn't installing the version we specify. I must have misunderstood the logging.

**Comment by hgy59** [comment]
> Hmm, strange that I saw in the logs that it wasn't installing the version we specify. I must have misunderstood the logging.

AFAICR there was "pip = 20.0.4" (single eq) once in your PR...

**Pull request merged**
