### PR TITLE
Package synocli-net

### PR DESCRIPTION
**Pull request by ymartin59**
_Linked issues:_ #3254 #3267 #3526 #3489 

### Checklist
- [X] Build rule `all-supported` completed successfully
- [X] Package upgrade completed successfully
- [N/A] New installation of package completed successfully

### CODE REVIEW

**Comment by m4tt075** [comment]
@ymartin59 Very nice implementation! Great stuff, including @publicarray 's icon!  👍 
Only part I don't understand is: Why do you keep the "spk/tmux/*" files, allowing separate installation of the `tmux` package AND include it in the `synocli-net` bundle? I would have guessed it to be one "xor" the other. Is there a particular reason for this?

**Comment by ymartin59** [comment]
@m4tt075 You're right - I have decided to remove "spk/mosh" from proposed PR but kept "spk/tmux" - in case anyone may want to build its own and so get a lighter package that synocli-net which is already 12 MiB heavy.
Another idea I have is to replace "spk/tmux" soon to publish a wizard only package and dependency to synocli-net to notify users about replacement.

**Comment by nbarrientos** [comment]
Sorry for the noise, but have you by any chance removed `tmux` standalone in view of adding this bundle? Can't find it now in the list of available packages to install on my DS418 (rtd1296) running 6.2 latest. Thanks :)

**Comment by nbarrientos** [comment]
Sorry, didn't have beta packages enabled.

**Pull request merged**
