### PR TITLE
OpenZWave support for Domoticz

### PR DESCRIPTION
**Pull request by Decipher**
As per #1488

### CODE REVIEW

**Comment by Decipher** [comment]
Possible something went wrong, this may not be ready for Pull yet. Tried compiling but patch fails. Should have tested more before I re-did the PR against Master.

Will look more at it ASAP.

**Comment by Decipher** [comment]
So the only issue is the line endings in the patch (cross/domoticz/patches/CMakeLists.txt.patch). It could be related to me squashing the commits on my local OS X environment rather than my SPKSRC Vagrant box.

Git doesn't want to deal with the issue, just wants to convert it to the non-working version. Thoughts?

**Comment by Diaoul** [comment]
What should be the line ending or the patch?

**Comment by Decipher** [comment]
Honestly I don't know. I don't really live in a world where I need to worry about line endings very often. Is there an easy way to find out?

**Comment by gkroone** [comment]
Domoticz uses crlf (msdos) line endings. If i have issues with it i run unix2dos to correct them.

In linux, the line endings appear with an additional ^M at the end. Not sure how mac shows it.

In one of the Domoticz versions i noticed that it accidentally switched to unix line endings,  which was then corrected again in a later version.

**Comment by KaraokeStu** [comment]
Hi, please could you rebase and confirm this all still works ok - I'm trying to clean up old pull requests.

If I don't hear anything by 31st July 2017, I will close the PR.

Thanks,

Stuart

**Pull request closed without merging**
