### PR TITLE
Lidarr: update with .NET support and mono fallback

### PR DESCRIPTION
**Pull request by publicarray**
_Motivation:_  Update to .NET
_Linked issues:_  

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by Wuszek** [comment]
@publicarray just installed from scratch, package aarch64 for DSM6.1, looks and works OK

lidarr

**Comment by publicarray** [comment]
@Qstick Hi, I looked at https://wiki.servarr.com/Lidarr_Installation#.NET_Core_Install and compiled chromaprint but in the extracted tar (https://github.com/lidarr/Lidarr/releases/download/v0.8.0.2042/Lidarr.develop.0.8.0.2042.linux-core-x64.tar.gz) fpcalc is already included. What are the requirements from the distributed tar? Does Lidarr still require libmediainfo, libcurl and sqlite? What about the mono version?

**Review by ymartin59 — APPROVED** [review]

**Comment by Qstick** [comment]
No libmediainfo for Lidarr, @ta264 can confirm the other requirements and such for mono version

**Comment by ta264** [comment]
Mono version needs sqlite3 and chromaprint, no need for mediainfo or libcurl. The .net version bundles fpcalc as you say but still needs sqlite3.

**Comment by ta264** [comment]
PS thanks for doing this, I'd been meaning to make a PR

**Comment by publicarray** [comment]
Thanks @Qstick and @ta264!  Not cross compiling curl and mediainfo speeds up builds considerably.

Force pushed to get the newer SQLite from https://github.com/SynoCommunity/spksrc/commit/f100ca0ecea5867dfb3dc725e9d718eccafca5ad.

**Comment by ta264** [comment]
Removing the dependency of sqlite on speex would improve it even more :D not sure why the build failed (#4465)

**Review by ymartin59 — APPROVED** [review]

**Comment by houndtt** [comment]
Great work guys! Just updated to this .Net Core build and it was a smooth upgrade just like the one for Radarr

**Pull request merged**
