### PR TITLE
Update DSM6 default version from 6.1 to 6.2.4 due to toolchain removals

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

Update DSM6 default version from 6.1 to 6.2.4 due to toolchain removals

Fixes n/a

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [ ] Package update
- [x] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
@th0ma7 at first sight, we need to add all patches we created for 6.1 toolchains to the 6.2.4 toolchains.

So far this are
- toolchain/syno-aarch64-6.1/patches/define_scsi_ioctl_tagged_enable_disable.patch
- toolchain/syno-evansport-6.1/patches/define_scsi_ioctl_tagged_enable_disable.patch
- toolchain/syno-x64-6.1/patches/define_scsi_ioctl_tagged_enable_disable.patch

**Comment by th0ma7** [comment]
Thnx for the review and good catch.  I should find cycles by the weekend to undo umurmur and merge.  Feel free to take it over if there is a rush to merge to fix things.

@hgy59 One thing that cones to mind, is the web publishing portion able to handle 3 digit versions?  If i recall that had been fixed but that was a while back either by @ymartin59 or @publicarray , unsure.

Anyhow, well know soon enough...

**Comment by hgy59** [comment]
> @hgy59 One thing that cones to mind, is the web publishing portion able to handle 3 digit versions? If i recall that had been fixed but that was a while back either by @ymartin59 or @publicarray , unsure.

@th0ma7 a very good catch.
I tried with umurmur to publish 6.2.4 and it fails with "Unknown firmware".
I only had to add firmware 6.2 with build number 25556 in the repo DB for the publish to work.
The `os__min_ver` is already `"6.2-25556"` in the INFO file, so the repo still works with two digit TC-Versions.

**Comment by th0ma7** [comment]
Awesome.  I now recall a change in the code to adapt the version number to always be using two digit with the corresponding 3 digit firmware build number.

**Comment by hgy59** [comment]
> Awesome. I now recall a change in the code to adapt the version number to always be using two digit with the corresponding 3 digit firmware build number.

@th0ma7 this code is already there (in spksrc.tc-flags.mk)
```
ifeq ($(strip $(TC_OS_MIN_VER)),)
TC_OS_MIN_VER = $(word 1,$(subst ., ,$(TC_VERS))).$(word 2,$(subst ., ,$(TC_VERS)))-$(TC_BUILD)
endif
```

or did I miss something?

**Comment by th0ma7** [comment]
> this code is already there (in spksrc.tc-flags.mk)
> ```
> ifeq ($(strip $(TC_OS_MIN_VER)),)
> TC_OS_MIN_VER = $(word 1,$(subst ., ,$(TC_VERS))).$(word 2,$(subst ., ,$(TC_VERS)))-$(TC_BUILD)
> endif
> ```
> 
> or did I miss something?
> 

@hgy59 nope, didn't miss anything.  It may even be actually me who wrote that... :)

**Comment by hgy59** [comment]
@th0ma7 can we merge this?

**Comment by th0ma7** [comment]
@hgy59 now merged, thnx for the reminder.

**Pull request merged**
