### PR TITLE
Radarr: Update to v5.1.3.8246

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This includes the following fixes:
1. Update to v5.1.3.8246.

Fixes # 

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by mreid-tt** [comment]
In testing this the update to v5.0.3.8127 (whether new install from this PR or in-app update from existing deployment) results in the following intermittent errors:

```
[Error] EventAggregator: QualityProfileService failed while processing [ApplicationStartedEvent] 

[v5.0.3.8127] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x87AF00AA): database is locked
database is locked
```
```
[Error] CommandExecutor: Error occurred while executing task RefreshMonitoredDownloads 

[v5.0.3.8127] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x87AF00AA): database is locked
database is locked
```

In discussing with the repo owners, this was reported to be a known issue "_related to threading changes in most cases we've seen_". The repo owners are working on a fix under https://github.com/Radarr/Radarr/pull/9173. It is recommended to update the version of Radarr that includes that fix before merging this PR.

**Comment by mreid-tt** [comment]
With the new release of Radarr, the SQL issue seems to be resolved.

**Comment by mreid-tt** [comment]
@hgy59, I ran into a problem publishing this [build](https://github.com/mreid-tt/spksrc/actions/runs/6904140494). I suspect it ran into the race condition on the backend where two packages tried to be published at the same time. Can you clean up all instances of radarr 20231117-21 for me so I can push them one at a time?

**Comment by hgy59** [comment]
> @hgy59, I ran into a problem publishing this [build](https://github.com/mreid-tt/spksrc/actions/runs/6904140494). I suspect it ran into the race condition on the backend where two files tried to be published at the same time. Can you clean up all instances of radarr 20231117-21 for me so I can push them one at a time?

done (there was only one package published for `armada37xx, rtd1296, rtd1619b` (i.e. aarch64)

**Comment by mreid-tt** [comment]
@hgy59, unfortunately, you also need to clean up the version which is still present. With any remnants the create process will fail -- I am still getting a "Internal Server Error" message.

**Comment by hgy59** [comment]
@mreid-tt done.

**Pull request merged**
