### PR TITLE
spk.mk: Fix all-supported and other parallel-build calls

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

When parallel building do not stop on failures but continue on next arch.

Fixes #5156

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [ ] New Package
- [ ] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
@th0ma7 another bug that is fixed with this, occurres on building `cross/<package>`.

e.g. `cd cross/openssl; make arch-x64-7.0` fails with:
```
make[2]: Leaving directory '/spksrc/cross/openssl'
/bin/sh: 2: Bad substitution
make[1]: *** [../../mk/spksrc.cross-cc.mk:108: build-arch-x64-7.0] Error 2
make[1]: Leaving directory '/spksrc/cross/openssl'
make: *** [../../mk/spksrc.cross-cc.mk:104: arch-x64-7.0] Error 2
```

**Comment by th0ma7** [comment]
Does it still build under github while capturing errors?  (Btw, disconnected atm)

**Comment by hgy59** [comment]
As you can see in https://github.com/SynoCommunity/spksrc/runs/5636365391?check_suite_focus=true
The github action does now handle UNSUPPORTED_ARCHS as error, so it never will create packages that have UNSUPPORTED_ARCHS.
So my proposal: undo your changes and just leave it as it was...

**Comment by th0ma7** [comment]
Btw, i had noticed something wrong with pre-check.mk as shell calls in it cannot work as theses are not "recipes".  Simply changing error to info or warning shows the underneath code issue.  The only reason it works is because the error forces exit.

Worst case you can revert the change for now until i can find cycles to review that further again.  But in the end i'll absolutely be needing it for kernel modules package builds (and good thing i broke it in little pieces to find issues before hand).

On the other hand if your added revert do work, you may have to do the same on other cross-*.mk, i'm not sure.

On that note, i communicated with Synology over the past few days and 6.2.4 kernels should appear starting today.  This is really the final missing piece to tie it all.

**Comment by th0ma7** [comment]
> As you can see in https://github.com/SynoCommunity/spksrc/runs/5636365391?check_suite_focus=true The github action does now handle UNSUPPORTED_ARCHS as error, so it never will create packages that have UNSUPPORTED_ARCHS. So my proposal: undo your changes of #5156 and just leave it as it was...

@hgy59 while everything else seems fixed I just hit this issue myself... indeed `UNSUPPORTED_ARCHS` exit 2 as it should but make github-action to appear as failed.  Although that's probably the last remaining item I guess.  I'll see what can be done to circumvent this (as the exit status is actually ok).

**Pull request merged**
