### PR TITLE
Update sslh to version 1.17

### PR DESCRIPTION
**Pull request by GaetanCambier**
Update sslh to version 1.17
Add digests file

### CODE REVIEW

**Comment by Diaoul** [comment]
No need for PLIST update?

**Comment by GaetanCambier** [comment]
no, just sslh binary in the plist --> no change

**Comment by Diaoul** [comment]
I don't understand all the VERSION variables. Please use only one without the `v` and add the `v` in other variables such as PKG_DIR and PKG_DIST_NAME.

**Comment by GaetanCambier** [comment]
done

**Comment by Dr-Bean** [comment]
#1212 might have some interesting stuff in it. That PR was just about complete (well, a few things I wanted to take care of after merging the PR)

**Comment by GaetanCambier** [comment]
i have merge work from : update sslh to v1.16 #1212

**Comment by Dr-Bean** [comment]
Could use a rebase though, this rewrites all kinds of previous commits, and I can't tell if it's up to date or not. :)

**Comment by GaetanCambier** [comment]
it's the first time i use rebase
i hope thats it's ok ;)

**Comment by Dr-Bean** [comment]
A lot better, thanks :) 
The package does need some additional changes before being fit to publish an updated version though: In the cross package, I'd remove the `v` in `PKG_VERS`, `SPK_VERS` is still 1.16, and the start-stop-status script could use some attention for instance.
I might grab your PR and add those changes when I get to it.

**Comment by GaetanCambier** [comment]
I'd remove the v in PKG_VERS

the version package is named with a 'v' (sslh-v1.17.tar.gz)
if i delete de 'v' in the PKG_VERS, i need modify some line to add the 'v'

**Comment by cytec** [comment]
@GaetanCambier change this line `PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)` to this `PKG_DIST_NAME = $(PKG_NAME)-v$(PKG_VERS).$(PKG_EXT)` then you can delete `v` in `PKG_VERSION`

**Comment by GaetanCambier** [comment]
done

**Pull request closed without merging**
