### PR TITLE
Added borgbackup package with acl and lz4 dependencies

### PR DESCRIPTION
**Pull request by yuroller**
_Motivation:_ Need help for [borgbackup ](https://borgbackup.readthedocs.io) package
_Linked issues:_ https://github.com/SynoCommunity/spksrc/issues/2351

### Checklist
- [] Build rule `all-supported` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

This is my first attempt at building a synology package: the package and its dependencies seems to build correctly, but I am unable to construct a proper spk: can anybody help?
Thank you.

### CODE REVIEW

**Comment by yuroller** [comment]
I have a new version that builds correctly for all architectures and installs correctly on DS-212+ DSM6.0.
I will make the final touches, test a bit and do another pull request.

**Comment by larsimmisch** [comment]
Whatever happened to this? I did something similar for `attic` a while back, but development of attic basically stopped and the borg took over. Is there anything I can help with?

**Comment by yuroller** [comment]
I am running an updated borg backup 1.1.0 on my arm processor synology nas.
I now see that there is v 1.1.2 available.
I will update, make some tests and propose a new pull request

**Comment by larsimmisch** [comment]
Cool, thank you.

**Pull request closed without merging**
