### PR TITLE
Roundcube Webmail: Update to v1.6.9

### LINKED ISSUE #3549: Roundcube not accessible after fresh install
### Setup
_Package Name:_ Roundcube Webmail
_Package Version:_ 1.1.4-4

_NAS Model:_ DS918+
_NAS Architecture:_
_DSM version:_ DSM 6.2.1-23824 Update 2

### Expected behavior
The Roundcube app is accessible after installing the package with Package Center.

### Actual behavior
During the install process I got few questions asked about mariadb and answered that. The installation went further and finally seemed fine. No error messages.  But after the click on the newly created Roundcube icon my box redirects me from http://diskstation/roundcube back to http://diskstation:5000.

I than thought Webstation is a missing dependency nowadays and installed it. But I'm unable to set /volume1/@appstore/roundcube/share/roundcube as a document root in Webstation. I guess it's  because it's not a shared folder. 

How I'm supposed to reach my installed roundcube app for initial configuration? 

I'm on a vanilla DSM with no additional packages installed.

### Steps to reproduce
_1._ Install Roundcube Webmail from SynoCommunity
_2._ Click at the roundcube icon
_3._ get redirect to http://diskstation:5000

#### Package log
_Check Package Center or `/usr/local/{package}/var/`_
```
unfortunately there are none
```

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This PR contains the following:

1. Upgrade Roundcube Webmail to version 1.6.9
2. Modernise package scripts
3. Add PHP profiles for DSM 6
4. Add full backup and restore

Fixes #3549

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by mreid-tt** [comment]
@hgy59, I’ve updated another legacy package to support MariaDB and added new script features, including dynamic PHP profiles for DSM6 and a full backup and restore function. Looking forward to your review and approval.

**Comment by hgy59** [comment]
@mreid-tt there is a copy/paste error in the description of this PR (mantisbt)

**Comment by mreid-tt** [comment]
> @mreid-tt there is a copy/paste error in the description of this PR (mantisbt)

Apologies for the oversight... corrected.

**Comment by Eagle3386** [comment]
Sorry for being late to the party, but can the RoundCube package be built _without_ a dependency on Apache, please?
I really want to avoid any Apache & use NGinX instead - preferably the same one that runs DSM or at least run RoundCube via WebStation?

**Pull request merged**
