### PR TITLE
ntopng: update to v6.2

### PR DESCRIPTION
**Pull request by hgy59**
## Description
- update ntopng and dependencies
- update libpcap from v1.10.4 to v1.10.5
- update ndpi from v3.4 to v4.10
- update libcap from v2.66 to v2.70
- update json-c from v0.16-20220414 to v0.17-20230812
- add hiredis v1.2.0
- add native/nodejs_16 required to build the web ui

Fixes # 

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by hgy59** [comment]
This PR superseeds #6216

**Comment by hgy59** [comment]
@th0ma7 currently the build of ntopng fails for native libmysqlclient when building mysqlconnector-c. Both fail, the former ntopng on the master branch (seen with merged #6231 https://github.com/SynoCommunity/spksrc/actions/runs/10875221744) and this PR with updated ntopng after merging in the current master.
The former build succeeded (only homeasistant faild, see https://github.com/SynoCommunity/spksrc/actions/runs/10690439769?pr=6220)

The build fails with
```
make[6]: Entering directory '/github/workspace/native/libmysqlclient/work-native/mysql-connector-c-6.1.11-src/build'
make[6]: *** No rule to make target 'install'.  Stop.
```

First I thought it was broken by #6212, but #6212 was already merged before. 
The next candidate is #6198
I guess it must be related to a cmake/ninja mk file (missing target `install`)

Unfortunately I am offline for a few weeks and can't dig into it...
Can you have a look?

**Comment by th0ma7** [comment]
10-4, Will do.

**Comment by th0ma7** [comment]
@hgy59 now fixed with https://github.com/SynoCommunity/spksrc/pull/6235

**Pull request merged**
