### PR TITLE
Remove unused cross/* python wheels

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

Remove all unused cross/* python wheels.  They either got lost/forgotten or migrated over to `requirements-crossenv.txt`.

Part of #5043 cleanups

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by smaarn** [comment]
Sorry for reacting this late but isn't webrtcvad causing issues with the bazarr build for ppc architectures? (late at the battle...)

**Comment by smaarn** [comment]
My bad I had totally forgotten about the requirements refactoring.

**Comment by th0ma7** [comment]
Just to confirm, is it all looking good for you @smaarn?  As with the refactoring theses are all trivial removals and totally unused code.

**Comment by smaarn** [comment]
> Just to confirm, is it all looking good for you @smaarn?  As with the refactoring theses are all trivial removals and totally unused code.

It does sound very good @th0ma7! Actually I'm not sure I can thank you enough for the job you're doing. I feel like a teenage boy realizing the job done to cleanup the room 😂

**Pull request merged**
