### PR TITLE
Update Gitea to v1.19.3

### PR DESCRIPTION
**Pull request by wkobiela**
## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by Safihre** [comment]
@hgy59 any reason not to update this package? There's 2 PRs open for it so seems it's wanted and not much work? I could also do it.

**Comment by hgy59** [comment]
> @hgy59 any reason not to update this package? There's 2 PRs open for it so seems it's wanted and not much work? I could also do it.

there are multiple PRs for different versions of gitea. One has an additional language for the wizard, this should be taken into account.

But the real blocker is #5649

**Comment by efussi** [comment]
@hgy59 with https://github.com/SynoCommunity/spksrc/pull/5649 merged, can we please update Gitea now?

**Comment by efussi** [comment]
> there are multiple PRs for different versions of gitea. One has an additional language for the wizard, this should be taken into account.

I assume this is referring to https://github.com/SynoCommunity/spksrc/pull/5700?

**Comment by wkobiela** [comment]
Closing in favor of https://github.com/SynoCommunity/spksrc/pull/5929

**Pull request closed without merging**
