### PR TITLE
Update SABnzbd (+Testing) to 2.0.0 Final

### PR DESCRIPTION
**Pull request by Safihre**
Updated both to the Final.
Integrated all changes from `testing` required to run the pip install.
Hope you have time to test this @KaraokeStu, just to be sure I did it 100% correctly for both packages :)

### CODE REVIEW

**Comment by KaraokeStu** [comment]
I'll get this tested later today :)

**Comment by levijay** [comment]
Installs as 1.2.3 [d34e143] not 2.0.23

**Comment by Safihre** [comment]
@KaraokeStu we had some other reports of people where the update still kept them on 1.2.3 instead of 2.0.0, the other poster here (I got an email)  seems to have removed his post, so this issue is resolved or could it be some cache?

**Comment by MostDefiantly** [comment]
I am still reporting 1.2.3 [d34e143] after updating the package.

**Comment by KaraokeStu** [comment]
Very strange, it is showing as the correct version in the repo. 

I'll have a further test later and republish if necessary. I can confirm the testing branch correctly identified as 2.0.0

I'll test it on my dsm 5 and 6 vms

**Comment by byronmccollum** [comment]
I can also confirm mine is reporting 1.2.3 [d34e143] as well..

**Comment by byronmccollum** [comment]
Just to clarity, Synology reports the package installed as being version 2.0.0-23, but SAB is definitely still running the 1.2.3 code base, as reported under its config screen, and by inspecting things on disk under `/usr/local/sabnzbd/share/SABnzbd/PKG-INFO`.

```
Metadata-Version: 1.0
Name: SABnzbd
Version: 1.2.3
Summary: SABnzbd-1.2.3
Home-page: http://sabnzbd.org
Author: The SABnzbd Team
Author-email: team@sabnzbd.org
License: GNU General Public License 2 (GPL2 or later)
Description: Fully automated Usenet Binary Downloader
Platform: posix
```

**Comment by byronmccollum** [comment]
I think this line was missed when updating the version numbers...

https://github.com/SynoCommunity/spksrc/blob/master/cross/sabnzbd/Makefile#L2

**Comment by KaraokeStu** [comment]
Nice spot, thanks! I'll get that amended tomorrow if I get a chance and will republish to the repo.

**Comment by Safihre** [comment]
Dammit, I compared everything line by line.. How did I miss this :(

**Comment by KaraokeStu** [comment]
Because you're human!

**Pull request merged**
