### PR TITLE
[dsm6] merge from master 20170831

### PR DESCRIPTION
**Pull request by ymartin59**
_Motivation:_ Update `dsm6` branch with packages additions and updates

- Replaces #2887 #2692

### CODE REVIEW

**Comment by ymartin59** [comment]
I request for help. @maxrogers @cytec @m4tt075 @Safihre @echel0n @KaraokeStu 
May some of you please at least build packages of your interest with DSM 6.1 toolchains from "pending future" `dsm6` I have merged at https://github.com/ymartin59/spksrc/tree/dsm6-merge-from-master-20170830 (sorry branch name is already outdated !)
Thank you in advance

**Comment by maxrogers** [comment]
@ymartin59 I successfully built bromolow-6.1 packages for sabnzbd-testing, sonarr, and radarr with no errors. I did not test the packages by installing and running however as I do not currently have a DSM 6.1 device (6.0.)

NOTE: The arch-bromolow-6.1 toolchain digests did not match. Do the digests for 6.1 toolchains need updating?

**Comment by ymartin59** [comment]
@maxrogers you may build with 6.0.2 toolchain to test installer script and check that background process properly runs
I will check digests... they may have been "re-published" by Synology along side with new arch additions.

**Comment by m4tt075** [comment]
@ymartin59 : The TVH package in master has been DSM6 compatible for months now (this is also the reason why the 5.2 version is still not published). I had adapted it according to @Dr-Bean's example implementations then. I have compiled `all-supported` with 6.1 toolchains for all recent pull requests. I only did it cherry-picking the 6.1 toolchains to my development branch (based on master). Is this sufficient for you or do you want me to test something else?

**Comment by ymartin59** [comment]
@m4tt075 Because of my merge, it is possible that some troubles have been introduced... By the way, I do not remember having resolved conflicts on TVH files. So no, not worth to test again.

**Comment by maxrogers** [comment]
@ymartin59 radarr, sonarr, and sabnzbd-testing tested just fine for install and upgrades!

Also, those three packages have the same DSM6 compatibility from @Dr-Bean that @m4tt075 used for the TVH packages in master. That means that they should be compatible with both DSM5 & DSM6 also. If I have time I will try to build a virtual DSM5 system to test DSM5 compatibility with these packages for install and especially upgrades.

**Comment by ymartin59** [comment]
For a DSM 5.2 as virtual machine, here are some "raw" notes about how I built my XPEnology which is really convenient for testing.

From http://xpenology.me/downloads/  and  https://download.xpenology.xyz/
Get XPEnoboot_DS3615xs_5.2-5967.1

Setup virtual machine in VMware Player:
- 8 GiB disk image
- NAT network address
- Use `bios.forceSetupOnce = "TRUE"`  to boot on BIOS and change boot order to use ISO image systematically
After setup, remove bios option but leave ISO image connected.

**Comment by m4tt075** [comment]
@ymartin59 : If you are fine with the approach @maxrogers and I took for "our" packages, I could take @Dr-Bean's list and start adapting other packages with the same problem accordingly. I'd just need testers. Would be package by package and take time, but still. Just let me know if you are interested...

**Comment by ymartin59** [comment]
@m4tt075 it would be great to review packages which still require fixes in `installer.sh` or in descriptors to run in DSM 6... (skip squidguard... I am on it)

**Comment by m4tt075** [comment]
@ymartin59 : OK. There is one caveat though: All these specific fixes will require introducing `/conf/privilege` files. If we eventually merge those fixes into master, the packages cannot be pusblished for 5.2 with our current `spkrepo` anymore, even if they are 5.2 compatible (like the TVH package now). I know you are working on the repo fixes, but understand this might take some more time. Therefore,  should I develop and PR against your `ymartin59:dsm6-merge-from-master-20170830` branch in the meantime?

**Comment by ymartin59** [comment]
@m4tt075 for this non-compatible aspects, my proposal is to branch `master` as `dsm5` to maintain "some" packages for DSM 5.2 publishing and merge one day `dsm6` to `master` when "everything" is ready for DSM 6... I just hope it will come before next major release of DSM introduces new compatibility break.

**Comment by ymartin59** [comment]
@m4tt075 you may prepare PR against my branch... so that you just have to rebase when merged.
I wonder it is really worth testing that merge PR...

@KaraokeStu What do you think about this PR ? I propose to merge it and do additional PR if we found some packages are broken in `dsm6` later ?

**Comment by ymartin59** [comment]
@m4tt075 please do not use that merge PR as branch source. It conflicts and new commits have to be included... I discard it.

**Pull request closed without merging**
