### PR TITLE
Update git

### PR DESCRIPTION
**Pull request by publicarray**
_Motivation:_  Update Git
_Linked issues:_  #3821
### Checklist
- [x] Build rule `all-supported` completed successfully
     https://github.com/publicarray/spksrc/runs/359756429
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by hgy59** [comment]
@publicarray please use current version 24.1 in /cross/git/Makefile too ;-)

**Comment by hgy59** [comment]
@publicarray did you build with the original docker image `synocommunity/spksrc:latest`?
I had to add the following to avoid the error `make[2]: curl-config: Command not found` on compiling for git

```
# compiling needs access to curl-config from cross/curl
ENV += PATH=$$PATH:$(STAGING_INSTALL_PREFIX)/bin
```

**Comment by publicarray** [comment]
Hi @hgy59!

Ha Thanks!, I have bit of an issue with extracting the tarball on circleCI but extracting works on my local machine 🤷‍♂️ 🤯 `gtar -xJpf git-2.24.1.tar.xz -C /tmp/`

https://app.circleci.com/jobs/github/publicarray/spksrc/1467

```
===>  Extracting for git
tar -xJpf /spksrc/cross/git/../../distrib/git-2.24.1.tar.xz -C /spksrc/spk/git/work-x64-6.1 
tar: git-2.24.1/configure: Cannot change ownership to uid 110493, gid 5000: Invalid argument
tar: git-2.24.1/version: Cannot change ownership to uid 110493, gid 5000: Invalid argument
tar: git-2.24.1/git-gui/version: Cannot change ownership to uid 110493, gid 5000: Invalid argument
tar: Exiting with failure status due to previous errors
```

**Comment by publicarray** [comment]
Hi @ ymartin59 and Happy New Year! 🎉 Thanks for fixing & merging it.

**Pull request merged**
