### PR TITLE
Update & fix build of ruTorrent

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  Fed-up of seeing this package fail to build under github-action so this is a first trial at fixing things up and while at it updating the code base.

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

## IMPORTANT NOTES
- This PR applies on top of #4155 and #4010.
- Current github-action build failures should normally disappear once other PR are merged.

### CODE REVIEW

**Comment by ymartin59** [comment]
@th0ma7 You may inspire from this closed PR #3175 from @Safihre

**Comment by ymartin59** [comment]
I do not agree to include "cppunit" just to get source code application built. Please find a switch to disable test cases compilation/exection, or if lacking, create one.

**Comment by ymartin59** [comment]
I propose to submit our "cross-compiling" patches upstream if relevant to ease future maintenance/update

**Comment by th0ma7** [comment]
> I propose to submit our "cross-compiling" patches upstream if relevant to ease future maintenance/update

Excellent point, done.

> I do not agree to include "cppunit" just to get source code application built. Please find a switch to disable test cases compilation/exection, or if lacking, create one.

I'll see what I can do but really this was an easy no maintenance workaround... I'd rather just sticking to that solution as it may be useful elsewhere as well.

**Comment by th0ma7** [comment]
> I do not agree to include "cppunit" just to get source code application built. Please find a switch to disable test cases compilation/exection, or if lacking, create one.

@ymartin59 I've quickly check and to my understanding `cppunit` checks are mandatory to get the `rtorrent` to build 
* https://github.com/rakshasa/libtorrent/issues/182

I suggest we merge as-is for now until another solution is found.

**Review by ymartin59 — APPROVED** [review]
OK so you can merge with cppunit

**Pull request merged**
