### PR TITLE
Make package icon SPK_ICON variable optional

### PR DESCRIPTION
**Pull request by ymartin59**

### CODE REVIEW

**Comment by fredrike** [comment]
You forgot this part:

```diff
diff --git a/mk/spksrc.spk.mk b/mk/spksrc.spk.mk
index 161c246..ffb4aa1 100644
--- a/mk/spksrc.spk.mk
+++ b/mk/spksrc.spk.mk
@@ -52,7 +52,9 @@ strip: copy
 include ../../mk/spksrc.strip.mk
 
 icon: strip
-include ../../mk/spksrc.icon.mk
+ifneq ($(strip $(SPK_ICON)),)
+  include ../../mk/spksrc.icon.mk
+endif
 
 ### Packaging rules
 $(WORK_DIR)/package.tgz: icon
```

**Comment by fredrike** [comment]
Also, if `SPK_ICON` is set the generated `PACKAGE_ICON_256.PNG` does not exist

**Comment by ymartin59** [comment]
@fredrike With that patch, if `SPK_ICON` is not set, neither `PACKAGE_ICON.PNG` nor `PACKAGE_ICON_256.PNG` are generated (`spksrc.spk.mk:247`)...
`spksrc.icon.mk` behavior is controlled thanks to `DSM_UI_DIR`, without it, no additional thumbnails (often in `app/` value). Those are used for menu links to service URL in DSM if I guess right.

**Comment by m4tt075** [comment]
@ymartin59 Have just been cross-compiling some packages and receiving (non-fatal) errors which might be related to this commit:

```
[...]
===>  Preparing conf
src/conf/privilege
src/conf/PKG_CONX
/home/me/builds/spksrc/spk/tvheadend/work-x86-5.2/conf/privilege
/home/me/builds/spksrc/spk/tvheadend/work-x86-5.2/conf/PKG_CONX
(cd /home/me/builds/spksrc/spk/tvheadend/work-x86-5.2 && tar cpf /home/me/builds/spksrc/spk/tvheadend/../../packages/tvheadend_x86-5.2_4.2.4-11.spk --group=root --owner=root package.tgz INFO scripts PACKAGE_ICON.PNG PACKAGE_ICON_256.PNG WIZARD_UIFILES conf)
tar: PACKAGE_ICON.PNG: Cannot stat: No such file or directory
tar: PACKAGE_ICON_256.PNG: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
../../mk/spksrc.spk.mk:282: recipe for target '/home/me/builds/spksrc/spk/tvheadend/../../packages/tvheadend_x86-5.2_4.2.4-11.spk' failed
make[1]: *** [/home/me/builds/spksrc/spk/tvheadend/../../packages/tvheadend_x86-5.2_4.2.4-11.spk] Error 2
make[1]: Leaving directory '/home/me/builds/spksrc/spk/tvheadend'
../../mk/spksrc.spk.mk:418: recipe for target 'arch-x86-5.2' failed
make: [arch-x86-5.2] Error 2 (ignored)
```

**Comment by ymartin59** [comment]
Right. I will fix it ASAP.

**Comment by ymartin59** [comment]
@m4tt075 I propose #2965 as a quick fix

**Comment by m4tt075** [comment]
@ymartin59 Cherry-picked #2965 but did not fix the issue. `SPK_ICON` and `DSM_UI_DIR` are actually both defined. Here the excerpt from the `spk/tvheadend/Makefile`:
```
SPK_NAME = tvheadend
SPK_VERS = 4.2.4
SPK_REV = 11
SPK_ICON = src/tvheadend.png
DSM_UI_DIR = app
BETA = 1
```
Could it be that things screw up because `SPK_ICON` contains a directory? After the compilation finishes I find a binary `icons` file in the `spk/tvheadend` directory which does not belong there. If you want, you should be able to reproduce this with the existing tvheadend package in master as well. The updates to 4.2.4 I'm working on are completely trivial and should not affect the issue in any way.

**Comment by ymartin59** [comment]
OK. Badly tested refactoring. I updated PR with better tested code... it really processes icon now.

**Pull request merged**
