### PR TITLE
Remove duplicate zeromq (libzmq)

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  Exists two version of `zeromq` also called `libzmq`.  Keep only the latest version, update to use the latest version available online (4.3.3) and use the `zeromq` naming to limit dependency changes over other packages.
_Linked issues:_  N/A

### Checklist
- [x] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by hgy59** [comment]
@th0ma7 please keep the package name for the folder (use `cross/libzmq`).

**Comment by th0ma7** [comment]
> @th0ma7 please keep the package name for the folder (use `cross/libzmq`) dispite of the dependency changes.

done, pending action build to confirm all ok.
Indirectly relates to #4255 where I noticed the duplication of `zeromq` and `libzmq`.

**Comment by hgy59** [comment]
@th0ma7 you might remove `cross/libsodium` as it was referenced only by `cross/zeromq`.

**Comment by th0ma7** [comment]
> @th0ma7 you might remove `cross/libsodium` as it was referenced only by `cross/zeromq`.

@hgy59 good catch but to the contrary I've re-enabled encryption support through `libsodium` to keep previous behavior, now using `cmake` instead.

**Review by hgy59 — APPROVED** [review]

**Pull request merged**
