### PR TITLE
fish: Update fish to 3.7.1

### PR DESCRIPTION
**Pull request by reishoku**
## Description

Update fish-shell from v3.6.1 to v3.7.1

## Checklist
- [x] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change
- [x] Package update

### CODE REVIEW

**Review by hgy59 — APPROVED** [review]
LGTM

**Comment by publicarray** [comment]
@hgy59 @reishoku FYI this fish version is not compatible with SRM 1.2 (probably because of old glibc), it *may* work with 1.3, but I'm not keen to upgrade yet as the upgrade removes the Wi-Fi repeater feature.

Before:
```
root@10.0.0.2's password: 


BusyBox v1.16.1 (2021-05-20 11:05:33 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

SynologyRouter> fish
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
root@SynologyRouter ~# 
```

After:
```
root@10.0.0.2's password: 


BusyBox v1.16.1 (2021-05-20 11:05:33 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

SynologyRouter> fish -v
fish, version 3.7.1
SynologyRouter> fish
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
Bus error (core dumped)
SynologyRouter> Connection to 10.0.0.2 closed.
```

**Comment by hgy59** [comment]
@publicarray thanks for reporting...

What version is running on which router model?

Just found that both published versions (3.3.1-4 and 3.7.1-7) fail with a core dump on my RT1900ac with SRM 1.2.5-8227 Update 11.

**Comment by publicarray** [comment]
@hgy59 thanks I have the RT2600ac and you are right both published versions fail to run. Unfortunately I forgot wich version I had previously installed.

**Pull request merged**
