### PR TITLE
cross-rust.mk: Fix regular build post PR #5435

### LINKED ISSUE #5463: build with rust fails
It is not possible to build packages with rust anymore.

This must be related to #5441

example output of `make arch-x64-6.1`  to build dua.

```
===>  Compiling for dua
  ==> Cargo build rust package dua
PKG_CONFIG_LIBDIR=/spksrc/diyspk/dua/work-x64-6.1/install//var/packages/dua/target/lib/pkgconfig WORK_DIR=/spksrc/diyspk/dua/work-x64-6.1 INSTALL_PREFIX=/var/packages/dua/target TC=syno-x64-6.1 SYSROOT="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root" LD="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld" LDSHARED="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc -shared" CPP="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-cpp" NM="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-nm" CC="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc" AS="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-as" RANLIB="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib" CXX="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-g++" AR="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ar" STRIP="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-strip" OBJDUMP="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-objdump" READELF="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-readelf" CFLAGS="-I/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include -I/spksrc/diyspk/dua/work-x64-6.1/install//var/packages/dua/target/include " CPPFLAGS="-I/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include -I/spksrc/diyspk/dua/work-x64-6.1/install//var/packages/dua/target/include " CXXFLAGS="-I/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include -I/spksrc/diyspk/dua/work-x64-6.1/install//var/packages/dua/target/include " LDFLAGS="-L/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/lib -L/spksrc/diyspk/dua/work-x64-6.1/install//var/packages/dua/target/lib -Wl,--rpath-link,/spksrc/diyspk/dua/work-x64-6.1/install//var/packages/dua/target/lib -Wl,--rpath,/var/packages/dua/target/lib " CARGO_HOME="/opt/cargo" RUSTUP_HOME="/opt/rustup" CARGO_BUILD_TARGET="x86_64-unknown-linux-gnu" CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_AR="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ar" CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER="/spksrc/toolchain/syno-x64-6.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc" cargo build --target=x86_64-unknown-linux-gnu --path /spksrc/diyspk/dua/work-x64-6.1/dua-cli-2.17.2 --root /spksrc/diyspk/dua/work-x64-6.1/install/var/packages/dua/target
error: Found argument '--path' which wasn't expected, or isn't valid in this context

	If you tried to supply `--path` as a value rather than a flag, use `-- --path`
```

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

Fix regular build post PR #5435

Fixes #5463

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [ ] New Package
- [ ] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
@hgy59 I'm getting a weird bug when calling `cargo build` that does not occur when calling `cargo install` which also does the build.  Anyhow, I've kept comments for potential follow-ups.  Let me know if this solves your issue.

**Comment by hgy59** [comment]
> Anyhow, I've kept comments for potential follow-ups. Let me know if this solves your issue.

Yes it builds now, but only when I use the build container with the root user (and sudo cargo ... does not work, as it does not find cargo).

I do not really understand, why rust was added to the build environment (i.e. to the Dockerfile)
- The docker image was increased from < 1GB to > 3GB
- cargo install works only with root user, as regular user dependencies are not found and crates is not updated
- how can a package use a different version of rust? (i.e. nightly vs stable)

With the previous rust integration none of the problems above occurred.

**Review by hgy59 — APPROVED** [review]
> Anyhow, I've kept comments for potential follow-ups. Let me know if this solves your issue.

We can use the git history for any follow-ups, but I don't think we need those...

It solved the build of synocli-file package (including most tools built with rust)
:heart:

**Comment by th0ma7** [comment]
> > Anyhow, I've kept comments for potential follow-ups. Let me know if this solves your issue.
> 
> Yes it builds now, but only when I use the build container with the root user (and sudo cargo ... does not work, as it does not find cargo).

Indeed this is what I noticed.  `cargo` cannot really be installed in "shared" mode whereas multiple users simply make use of and as needed enhance it from their user-profile (or I didn't found the right method yet).  For my lxc install I end-up installing it as `spksrc` user to alleviate this (whereas docker is in priviledge mode thus as root).  In the best of world I'd really much like to always install default cargo & rust for all users, then allowing it to be per user defined (e.g. downloading per arch toolchains and other bits such as switching to nightly vs stable).

> I do not really understand, why rust was added to the build environment (i.e. to the Dockerfile)

I thought of, well, we also do it for meson for instance, why not for rust.  Also I needed something "fixed" to finally get a hold on why it kept failing always.  Now that this is solved it can certainly be revisited.  And on the other hand, per-arch toolchains aren't in the Dockerfile neither.

> * The docker image was increased from < 1GB to > 3GB
> * cargo install works only with root user, as regular user dependencies are not found and crates is not updated
> * how can a package use a different version of rust? (i.e. nightly vs stable)
> 
> With the previous rust integration none of the problems above occurred.

Now that we have a working environment for both regular cross-rustc & python rust wheel I'll be more than happy to revisit this and re-use (and perhaps enhanced) previous integration method.

**Comment by hgy59** [comment]
I propose to go with this for now.
Can you merge please?

**Comment by th0ma7** [comment]
Yeah, that's what I was thinking too, lets merge this to complete the fixing part then later in another PR find ways to optimize this furtner.  merging :)

**Comment by hgy59** [comment]
@th0ma7, I finally found that _crates_ are downloaded to the `/opt/cargo/registry` folder.
Initially this folder does not exist, and only root can create it.

As a first atempt I created the `/opt/cargo/registry` folder with world access (777).
This fixed the build of rust targets as regular user.

But a better solution would be to use a sub folder of  `/spksrc/distrib/` as we do for downloaded sources, go packages, nuget packages, pip wheels, etc.

Unfortunately I couldn't find out how to configure the rust `registry` folder (aka crates-io)

Error message before:
```
  ==> Cargo install rust package bat
  Installing bat v0.22.1 (/spksrc/spk/synocli-file/work-x64-6.1/bat-0.22.1)
error: failed to compile `bat v0.22.1 (/spksrc/spk/synocli-file/work-x64-6.1/bat-0.22.1)`, intermediate artifacts can be found at `/spksrc/spk/synocli-file/work-x64-6.1/bat-0.22.1/target`

Caused by:
  failed to get `ansi_colours` as a dependency of package `bat v0.22.1 (/spksrc/spk/synocli-file/work-x64-6.1/bat-0.22.1)`

Caused by:
  failed to load source for dependency `ansi_colours`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to create directory `/opt/cargo/registry/index/github.com-1ecc6299db9ec823`
```


BTW: for all my containers (except the one to create packages to publish, where I use the root user), I mount a docker volume to `/spksrc/distrib` to share all the downloaded files between my (~2-20 running containers, switching between >200 clones)

**Comment by hgy59** [comment]
@th0ma7 after reading this (https://github.com/rust-lang/cargo/issues/10252) I think there is no way to configure a different folder for the registry.

I propose to use `CARGO_HOME = /spksrc/distrib/cargo` (as we did before) and create `$(CARGO_HOME)/bin` as link to `/opt/cargo/bin` on demand somewhere in `spksrc.cross-rust.mk`.

**Comment by th0ma7** [comment]
> after reading this (https://github.com/rust-lang/cargo/issues/10252) I think there is no way to configure a different folder for the registry.

@hgy59 This is exactly the roadblock I had hit which made me go the other way around so we at least get a first implementation fully working until we find something better.  On that note, I thought of a slightly different approach (e.g. making mileage on your proposal).  Untested so unsure how things would pan-out:
- I propose to leave only the `rustup` setup in the Dockerfile (thus leaving `RUSTUP_HOME` as is in `/opt`)
- At toolchain time invoke the `rustup target add <toolchain>` - this in turn will run as the "user" being used.  Therefore we could then indeed move `CARGO_HOME` to `/spksrc/distrib/cargo` folder.  There may be a need to add a `spksrc.tc-rustc.mk` file to be included by default in `spksrc.tc.mk` or something similar.

I believe the changes are relatively minimal and would allow:
1. freing-up tons of space on the Docker image
2. allow both priviledge and unpriviledge containers to function properly

As I side note, I migrated entirely to LXC/LXD a while back.  This allows me to "share" a `spksrc` user between my container and my favorite linux distribution.  As such I'm always using it in unpriviledged mode but I can always switch back to `root` and easily dive into it natively from the `~spksrc/.` path.

**Pull request merged**
