### PR TITLE
ps3netsrv upadated

### LINKED ISSUE #5751: ps3netsrv default port conflicts with Synology Calendar CalDAV port
### Is this a new Bug?

- [X] I checked that the bug hasn't been reported before

### Package Name

ps3netsrv

### Package Version

v1.47.37-7

### Device Model

DS220+

### Device Architecture

x86_64

### Firmware Version

DSM 7.1.1-42962 Update 5

### What happened?

With ps3netsrv installed, the Synology Calendar package does not run correctly. It starts but is not fully functional, and cannot bind to a port or alias.

If the Synology Calendar package is started first, then ps3netsrv stops immediately after being started.

I worked with Synology support and determined that Synology Calendar internally uses ports 38008 and 38443. ps3netsrv uses port 38008 by default.

https://consolemods.org/wiki/PS3:PS3netsrv
image

It would be nice if there was an option to change the port for ps3netsrv, or at least an indication of the port used and the conflict with Synology Calendar.

### Reproduction steps

1. Install both Synology Calendar and ps3netsrv packages
2. Start Synology Calendar
3. Attempt to start ps3netsrv
4. ps3netsrv will stop, showing "Manually stopped"
...

### Install Log

```log
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin preinst
2023/03/17 19:40:03     Begin reload_inst_variables
2023/03/17 19:40:03     End reload_inst_variables
2023/03/17 19:40:03     Begin initialize_variables
2023/03/17 19:40:03     End initialize_variables
2023/03/17 19:40:03     ===> Step preinst. USER=sc-ps3netsrv GROUP= SHARE_PATH=PS3
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End preinst ret=[0]
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin /bin/mkdir -p /volume1/@appstore/ps3netsrv -m 755
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End /bin/mkdir -p /volume1/@appstore/ps3netsrv -m 755 ret=[0]
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin /bin/rm -rf /volume1/@appstore/ps3netsrv
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End /bin/rm -rf /volume1/@appstore/ps3netsrv ret=[0]
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin /bin/mv -f /volume1/@tmp/synopkg/install.PwCixH/package /volume1/@appstore/ps3netsrv
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End /bin/mv -f /volume1/@tmp/synopkg/install.PwCixH/package /volume1/@appstore/ps3netsrv ret=[0]
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin /bin/rm -rf /var/packages/ps3netsrv
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End /bin/rm -rf /var/packages/ps3netsrv ret=[0]
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin /bin/mkdir -p /var/packages/ps3netsrv -m 755
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End /bin/mkdir -p /var/packages/ps3netsrv -m 755 ret=[0]
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin /bin/touch /var/packages/ps3netsrv/installing
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End /bin/touch /var/packages/ps3netsrv/installing ret=[0]
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin /bin/mv -f /volume1/@tmp/synopkg/install.PwCixH/INFO /var/packages/ps3netsrv/INFO
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End /bin/mv -f /volume1/@tmp/synopkg/install.PwCixH/INFO /var/packages/ps3netsrv/INFO ret=[0]
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin /bin/rm -rf /var/packages/ps3netsrv/scripts
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End /bin/rm -rf /var/packages/ps3netsrv/scripts ret=[0]
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin /bin/mv -f /volume1/@tmp/synopkg/install.PwCixH/scripts /var/packages/ps3netsrv/scripts
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End /bin/mv -f /volume1/@tmp/synopkg/install.PwCixH/scripts /var/packages/ps3netsrv/scripts ret=[0]
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin /bin/rm -rf /var/packages/ps3netsrv/WIZARD_UIFILES
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End /bin/rm -rf /var/packages/ps3netsrv/WIZARD_UIFILES ret=[0]
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin /bin/mv -f /volume1/@tmp/synopkg/install.PwCixH/WIZARD_UIFILES /var/packages/ps3netsrv/WIZARD_UIFILES
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End /bin/mv -f /volume1/@tmp/synopkg/install.PwCixH/WIZARD_UIFILES /var/packages/ps3netsrv/WIZARD_UIFILES ret=[0]
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin /bin/rm -rf /var/packages/ps3netsrv/conf
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End /bin/rm -rf /var/packages/ps3netsrv/conf ret=[0]
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 Begin /bin/mv -f /volume1/@tmp/synopkg/install.PwCixH/conf /var/packages/ps3netsrv/conf
2023/03/17 19:40:03     install ps3netsrv 1.47.37-7 End /bin/mv -f /volume1/@tmp/synopkg/install.PwCixH/conf /var/packages/ps3netsrv/conf ret=[0]
2023/03/17 19:40:10     install ps3netsrv 1.47.37-7 Begin postinst
2023/03/17 19:40:10     Begin reload_inst_variables
2023/03/17 19:40:10     End reload_inst_variables
2023/03/17 19:40:10     Begin initialize_variables
2023/03/17 19:40:10     End initialize_variables
2023/03/17 19:40:10     ===> Step postinst. USER=sc-ps3netsrv GROUP= SHARE_PATH=PS3
2023/03/17 19:40:10     Begin save_wizard_variables
2023/03/17 19:40:10     End save_wizard_variables
2023/03/17 19:40:10     Begin service_postinst
2023/03/17 19:40:10     End service_postinst
2023/03/17 19:40:10     install ps3netsrv 1.47.37-7 End postinst ret=[0]
2023/03/17 19:40:10     install ps3netsrv 1.47.37-7 Begin start-stop-status start
2023/03/17 19:40:10     install ps3netsrv 1.47.37-7 End start-stop-status start ret=[0]
2023/04/07 17:57:10     (system) trigger ps3netsrv 1.47.37-7 Begin start-stop-status start
2023/04/07 17:57:11     (system) trigger ps3netsrv 1.47.37-7 End start-stop-status start ret=[0]
2023/05/18 19:09:07     (system) trigger ps3netsrv 1.47.37-7 Begin start-stop-status stop
2023/05/18 19:09:09     (system) trigger ps3netsrv 1.47.37-7 End start-stop-status stop ret=[0]
2023/05/18 19:13:03     (system) trigger ps3netsrv 1.47.37-7 Begin start-stop-status start
2023/05/18 19:13:04     (system) trigger ps3netsrv 1.47.37-7 End start-stop-status start ret=[0]
2023/05/18 23:51:39     (system) trigger ps3netsrv 1.47.37-7 Begin start-stop-status stop
2023/05/18 23:51:39     (system) trigger ps3netsrv 1.47.37-7 End start-stop-status stop ret=[0]
2023/05/18 23:54:17     (system) trigger ps3netsrv 1.47.37-7 Begin start-stop-status start
2023/05/18 23:54:17     (system) trigger ps3netsrv 1.47.37-7 End start-stop-status start ret=[0]
2023/05/19 01:35:30     (system) trigger ps3netsrv 1.47.37-7 Begin start-stop-status stop
2023/05/19 01:35:30     (system) trigger ps3netsrv 1.47.37-7 End start-stop-status stop ret=[0]
2023/05/19 01:38:03     (system) trigger ps3netsrv 1.47.37-7 Begin start-stop-status start
2023/05/19 01:38:04     (system) trigger ps3netsrv 1.47.37-7 End start-stop-status start ret=[0]
2023/05/26 09:56:15     stop ps3netsrv 1.47.37-7 Begin start-stop-status stop
2023/05/26 09:56:15     stop ps3netsrv 1.47.37-7 End start-stop-status stop ret=[0]
2023/05/26 09:56:22     uninstall ps3netsrv 1.47.37-7 Begin preuninst
2023/05/26 09:56:22     Begin reload_inst_variables
2023/05/26 09:56:22     End reload_inst_variables
2023/05/26 09:56:22     Begin initialize_variables
2023/05/26 09:56:22     End initialize_variables
2023/05/26 09:56:22     ===> Step preuninst. USER=sc-ps3netsrv GROUP= SHARE_PATH=
2023/05/26 09:56:22     uninstall ps3netsrv 1.47.37-7 End preuninst ret=[0]
2023/05/26 09:56:22     uninstall ps3netsrv 1.47.37-7 Begin /bin/rm -rf /volume1/@appstore/ps3netsrv
2023/05/26 09:56:22     uninstall ps3netsrv 1.47.37-7 End /bin/rm -rf /volume1/@appstore/ps3netsrv ret=[0]
2023/05/26 09:56:22     uninstall ps3netsrv 1.47.37-7 Begin /bin/rm -rf /volume1/@apptemp/ps3netsrv
2023/05/26 09:56:22     uninstall ps3netsrv 1.47.37-7 End /bin/rm -rf /volume1/@apptemp/ps3netsrv ret=[0]
2023/05/26 09:56:22     uninstall ps3netsrv 1.47.37-7 Begin postuninst
2023/05/26 09:56:22     Begin reload_inst_variables
2023/05/26 09:56:22     End reload_inst_variables
2023/05/26 09:56:22     Begin initialize_variables
2023/05/26 09:56:23     End initialize_variables
2023/05/26 09:56:23     ===> Step postuninst. USER=sc-ps3netsrv GROUP= SHARE_PATH=
2023/05/26 09:56:23     Removing files...
2023/05/26 09:56:23     /volume1/@appdata/ps3netsrv/ps3netsrv.conf
2023/05/26 09:56:23     /volume1/@appdata/ps3netsrv/ps3netsrv.log
2023/05/26 09:56:23     uninstall ps3netsrv 1.47.37-7 End postuninst ret=[0]
2023/05/26 10:11:44     install ps3netsrv 1.47.37-7 Begin preinst
2023/05/26 10:11:44     Begin reload_inst_variables
2023/05/26 10:11:44     End reload_inst_variables
2023/05/26 10:11:44     Begin initialize_variables
2023/05/26 10:11:44     End initialize_variables
2023/05/26 10:11:44     ===> Step preinst. USER=sc-ps3netsrv GROUP= SHARE_PATH=PS3
2023/05/26 10:11:44     install ps3netsrv 1.47.37-7 End preinst ret=[0]
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 Begin /bin/mkdir -p /volume1/@appstore/ps3netsrv -m 755
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 End /bin/mkdir -p /volume1/@appstore/ps3netsrv -m 755 ret=[0]
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 Begin /bin/rm -rf /volume1/@appstore/ps3netsrv
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 End /bin/rm -rf /volume1/@appstore/ps3netsrv ret=[0]
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 Begin /bin/mv -f /volume1/@tmp/synopkg/install.Mt1GKE/package /volume1/@appstore/ps3netsrv
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 End /bin/mv -f /volume1/@tmp/synopkg/install.Mt1GKE/package /volume1/@appstore/ps3netsrv ret=[0]
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 Begin /bin/rm -rf /var/packages/ps3netsrv
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 End /bin/rm -rf /var/packages/ps3netsrv ret=[0]
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 Begin /bin/mkdir -p /var/packages/ps3netsrv -m 755
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 End /bin/mkdir -p /var/packages/ps3netsrv -m 755 ret=[0]
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 Begin /bin/touch /var/packages/ps3netsrv/installing
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 End /bin/touch /var/packages/ps3netsrv/installing ret=[0]
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 Begin /bin/mv -f /volume1/@tmp/synopkg/install.Mt1GKE/INFO /var/packages/ps3netsrv/INFO
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 End /bin/mv -f /volume1/@tmp/synopkg/install.Mt1GKE/INFO /var/packages/ps3netsrv/INFO ret=[0]
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 Begin /bin/rm -rf /var/packages/ps3netsrv/scripts
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 End /bin/rm -rf /var/packages/ps3netsrv/scripts ret=[0]
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 Begin /bin/mv -f /volume1/@tmp/synopkg/install.Mt1GKE/scripts /var/packages/ps3netsrv/scripts
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 End /bin/mv -f /volume1/@tmp/synopkg/install.Mt1GKE/scripts /var/packages/ps3netsrv/scripts ret=[0]
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 Begin /bin/rm -rf /var/packages/ps3netsrv/WIZARD_UIFILES
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 End /bin/rm -rf /var/packages/ps3netsrv/WIZARD_UIFILES ret=[0]
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 Begin /bin/mv -f /volume1/@tmp/synopkg/install.Mt1GKE/WIZARD_UIFILES /var/packages/ps3netsrv/WIZARD_UIFILES
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 End /bin/mv -f /volume1/@tmp/synopkg/install.Mt1GKE/WIZARD_UIFILES /var/packages/ps3netsrv/WIZARD_UIFILES ret=[0]
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 Begin /bin/rm -rf /var/packages/ps3netsrv/conf
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 End /bin/rm -rf /var/packages/ps3netsrv/conf ret=[0]
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 Begin /bin/mv -f /volume1/@tmp/synopkg/install.Mt1GKE/conf /var/packages/ps3netsrv/conf
2023/05/26 10:11:45     install ps3netsrv 1.47.37-7 End /bin/mv -f /volume1/@tmp/synopkg/install.Mt1GKE/conf /var/packages/ps3netsrv/conf ret=[0]
2023/05/26 10:11:49     install ps3netsrv 1.47.37-7 Begin postinst
2023/05/26 10:11:49     Begin reload_inst_variables
2023/05/26 10:11:49     End reload_inst_variables
2023/05/26 10:11:49     Begin initialize_variables
2023/05/26 10:11:49     End initialize_variables
2023/05/26 10:11:49     ===> Step postinst. USER=sc-ps3netsrv GROUP= SHARE_PATH=PS3
2023/05/26 10:11:49     Begin save_wizard_variables
2023/05/26 10:11:49     End save_wizard_variables
2023/05/26 10:11:49     Begin service_postinst
2023/05/26 10:11:49     End service_postinst
2023/05/26 10:11:49     install ps3netsrv 1.47.37-7 End postinst ret=[0]
2023/05/26 10:11:49     install ps3netsrv 1.47.37-7 Begin start-stop-status start
2023/05/26 10:11:49     install ps3netsrv 1.47.37-7 End start-stop-status start ret=[0]
2023/05/26 10:12:06     start ps3netsrv 1.47.37-7 Begin start-stop-status stop
2023/05/26 10:12:06     start ps3netsrv 1.47.37-7 End start-stop-status stop ret=[0]
2023/05/26 10:12:08     start ps3netsrv 1.47.37-7 Begin start-stop-status start
2023/05/26 10:12:08     start ps3netsrv 1.47.37-7 End start-stop-status start ret=[0]
```

### Service Log

```log
Fri May 26 10:12:08 EDT 2023
Starting ps3netsrv command /volume1/@appstore/ps3netsrv/ps3netsrv-starter.sh
ps3netsrv build 20200708 (mod by aldostools)
Path: /volume1/PS3

Error in port initialization.


Press ENTER to continue...
```

### Other Logs

_No response_

### PR DESCRIPTION
**Pull request by Hirador**
Updated to v1.47.45 with ps3netsrv 20220813 for DSM's versions:  DSM-6.2.4 -> DSM-7.1

## Description

1 - Updated the variables found on "spksrc/spk/ps3netsrv" and " spksrc/cross/ps3netsrv" to match the current version (v1.47.45 with ps3netsrv 20220813) of aldostools's ps3netsrv

2 - made "make all-supported", 

3 - created .spk for my Architecture (arch-armada370)

4 - Made some tests with the updated version of the ps3netsrv

5 - Cleaned everything up for the pull request (make clean on both spksrc/spk/ps3netsrv and spksrc/cross/ps3netsrv)

Closes #5751

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
@Hirador thanks for providing this update.

What do you think about changing the port for this package? (see #5751)

**Comment by hgy59** [comment]
@Hirador please have a look at the file `/spksrc/cross/p3netsrv/digests`

It is not a valid digests file.

you should be able to create the correct file with `make clean && make digests` in cross/ps3netsrv folder

**Comment by Hirador** [comment]
> @Hirador thanks for providing this update.
> 
> What do you think about changing the port for this package? (see #5751)

Hey I’ve thought about giving the chance to the user to set a custom port to the server, with a disclaimer where they can check which port is used in other Synocommunity’s packages (I know that this package has a port conflict with the Synology Calendar CalDAV). The fact is, the default port that the clients use to connect to this server is 38008, but can be changed with a custom one, so I’m planning to do it in the near future but for this update, I’m just leaving the default one set

**Comment by Hirador** [comment]
> @Hirador please have a look at the file `/spksrc/cross/p3netsrv/digests`
> 
> It is not a valid digests file.
> 
> you should be able to create the correct file with `make clean && make digests` in cross/ps3netsrv folder

My fault, I’ve actually made the make digest command but something may have got wrong in the process

**Comment by Hirador** [comment]
> @Hirador please have a look at the file `/spksrc/cross/p3netsrv/digests`
> 
> It is not a valid digests file.
> 
> you should be able to create the correct file with `make clean && make digests` in cross/ps3netsrv folder

Fixed the issue with the digests file

**Comment by hgy59** [comment]
> Hey I’ve thought about giving the chance to the user to set a custom port to the server, with a disclaimer where they can check which port is used in other Synocommunity’s packages (I know that this package has a port conflict with the Synology Calendar CalDAV). The fact is, the default port that the clients use to connect to this server is 38008, but can be changed with a custom one, so I’m planning to do it in the near future but for this update, I’m just leaving the default one set

It is not possible to make the port configurable. Each package has to use exclusive ports. As port 38008 conflicts with the synology calendar package, we should change this port now.

**Comment by Hirador** [comment]
> > Hey I’ve thought about giving the chance to the user to set a custom port to the server, with a disclaimer where they can check which port is used in other Synocommunity’s packages (I know that this package has a port conflict with the Synology Calendar CalDAV). The fact is, the default port that the clients use to connect to this server is 38008, but can be changed with a custom one, so I’m planning to do it in the near future but for this update, I’m just leaving the default one set
> 
> It is not possible to make the port configurable. Each package has to use exclusive ports. As port 38008 conflicts with the synology calendar package, we should change this port now.

If it is strictly necessary, I agree with the port changing even if I would really prefer to leave the default one, just because the clients need to be modified so is no more “plug and play”. 

Confirm to me that the port 14167 is usable and I’m going to edit the package in few minutes setting the default port to 14167

**Comment by Hirador** [comment]
> > Hey I’ve thought about giving the chance to the user to set a custom port to the server, with a disclaimer where they can check which port is used in other Synocommunity’s packages (I know that this package has a port conflict with the Synology Calendar CalDAV). The fact is, the default port that the clients use to connect to this server is 38008, but can be changed with a custom one, so I’m planning to do it in the near future but for this update, I’m just leaving the default one set
> 
> It is not possible to make the port configurable. Each package has to use exclusive ports. As port 38008 conflicts with the synology calendar package, we should change this port now.

Please confirm me what I’ve said so tha we can go live as soon as possible

**Comment by Hirador** [comment]
> > Hey I’ve thought about giving the chance to the user to set a custom port to the server, with a disclaimer where they can check which port is used in other Synocommunity’s packages (I know that this package has a port conflict with the Synology Calendar CalDAV). The fact is, the default port that the clients use to connect to this server is 38008, but can be changed with a custom one, so I’m planning to do it in the near future but for this update, I’m just leaving the default one set
> 
> It is not possible to make the port configurable. Each package has to use exclusive ports. As port 38008 conflicts with the synology calendar package, we should change this port now.

Changed the port, please continue the check

**Review by hgy59 — APPROVED** [review]
LGTM

**Pull request merged**
