### PR TITLE
Update Jackett (v0.11.43), Sonarr (v2.0.0.5301), Radarr (v0.2.0.1293) and Lidarr (v.0.5.0583)

### PR DESCRIPTION
**Pull request by m4tt075**
### Motivation
- `Jackett` requires a version upgrade (see issue #3653)
- `Sonarr` and `Radarr` leak memory (see issue #3470, #3474)
- Fixing the issues above requires a `mono` upgrade (see issue #3561)
- `Lidarr` depends on `mono` as well and is updated to avoid (possible) incompatibilities with an upgraded `mono` 

### Comments
- All of the above packages have been tested successfully by at least 1 user (see #3470 for details)

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by m4tt075** [comment]
To be merged in conjunction with #3561. Please refer to #3470 for test builds and non-code related discussions.

**Comment by m4tt075** [comment]
@maxrogers I've rebased this PR on #3518, to keep credits with you and so that people can benefit from the additional improvements your PR contained. Again, sorry for the oversight...

**Comment by ymartin59** [comment]
@m4tt075 Let me know when you are confident for merge and publish. Have you got anything needed for you to publish on your own?

**Comment by maxrogers** [comment]
@m4tt075 thanks for doing all this work to get everything updated! :D

**Comment by ymartin59** [comment]
@m4tt075 OK... Build in progress...

**Comment by m4tt075** [comment]
@ymartin59 Thank You very much, Yves!

**Comment by ymartin59** [comment]
@m4tt075 I cannot wait to see these application packages as "non arch"... is that really impossible?

**Pull request merged**
