### PR TITLE
Update nzbget to 16.0.

### PR DESCRIPTION
**Pull request by cxhamilton**

### CODE REVIEW

**Comment by cytec** [comment]
Seems like you just copy&pased stuff from the testing package but forgot the new config template ;)
\cc @Dr-Bean

**Comment by cxhamilton** [comment]
Indeed. I have updated the config templates.

**Comment by Dr-Bean** [comment]
I had already prepared the same changes while updating the -testing package. I didn't push it yet, because I wanted to test what happens with active downloads and content in the queue. I seem to remember the queue should be emptied between 15.x and 16.x but I can't recall where that came from or find a reference for it right now.
So, did or can you test that?

**Comment by cxhamilton** [comment]
I have made changes, based on @Dr-Bean 's comments. I also tested upgrading from 15.x to 16.x during an active download. The queue was preserved and the download continued to completion without issue.

**Comment by Dr-Bean** [comment]
Cool, thanks :)

**Pull request merged**
