### PR TITLE
Fix build of sshfs for ppc853x (#3652) and itools

### PR DESCRIPTION
**Pull request by hgy59**
_Motivation:_ It started with the missing `synocli-net` package for `ppc853x`
_Linked issues:_ #3652

An update of `fuse` from version 2.9.4 to 2.9.9 (and disabling the build of the examples code that failed for ppx853x) was required to fix the build of the `sshfs` package that is part of `synocli-net`.
So I verified the packages depending on cross/fuse
- sshfs
- synocli-net
- itools

The `itools` package did not compile for any arch without the fix of `cross/fuse`.
The build of itools for armv5 (88f9621) failed due a bug that was fixed about 5 months ago in the repo of [usbmuxd](https://github.com/libimobiledevice/usbmuxd/commit/96e4aabe0b9a46ea9da4955a10c774a8e58fe677#diff-67e997bcfdac55191033d57a16d1408a).

Finally the package `sshfs` was updated with correct version information.
And the /cross/libusb uses now the source from github with the same version as the former sf.net repo.

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully (tested with synocli-net only)
- [x] New installation of package completed successfully

The only impediment found, is for DSM 6.x. To use the updated fusermount command, the path must be specified (/usr/local/bin), otherwise /usr/bin/fusermount used that is already installed by synology in the former version.

### Proposals
1. As the build of `synocli-net` is fixed with this PR, I propose to remove the dedicated `sshfs` and `tmux` packages that are contained in synocli-net.
2. Since `itools` depends on `fuse` it could be integrated into `synocli-net` (**or** both `itools` and `sshfs` may be moved to synocli-file).

### CODE REVIEW

**Comment by ymartin59** [comment]
@hgy59 Well done ! What do you think about my proposal to move "spk/xxx" to a new "diyspk/" folder where we keep per-application package for advanced users which expects to create a dedicated package?

**Comment by hgy59** [comment]
I think we can freely delete such spk-definitions. By moving them to a special folder they will not be maintained anymore (as spk/sshfs was). Anyone interested in such sources can find them after deletion in the history of the repo.
May be it is worth to tag the master branch with special labels before the deletion of such spk definitions, to make it easy to retrieve it for interested developpers.

**Comment by ymartin59** [comment]
@hgy59 It is not a so great effort to maintain "diyspk/xxx" Makefile variables consistent with "cross/xxx"... I doubt any "interested developper" will really have interest in building a dedicated package for an old version...
May you please fix your "root" Git commit author here too.

**Comment by hgy59** [comment]
@ymartin59 sorry for the wrong user, may be I made the commits from within the docker container ;-(

**Comment by ymartin59** [comment]
@hgy59 Do you recommend/expect some packages to be published again? (lacking architectures in repository for instance)

**Comment by hgy59** [comment]
@ymartin59 yes the ppc853x arch is still missing in the repository.
And with synocli-net published for ppc853x you may close #3652.
itools (iOS Access) in the current version is not yet published for 6.1 88f8621, 1.1 northstarplus and 1.1 ipq806x.

**Pull request merged**
