### PR TITLE
Update sabnzbd-testing to 2.3.0

### PR DESCRIPTION
**Pull request by Safihre**
I used Travis to test building all of the toolchains that have a 5.2 toolchain (just to save time), based on the work by @torrentalle.
https://travis-ci.org/Safihre/spksrc
I had to limit output to errors/warnings because otherwise it exceeds the Travis limit of 10.000 lines.
Success is checked by at the end checking if a `.spk` package is generated.

Again, I don't have a Synology so cannot check install or upgrade of packages.

### CODE REVIEW

**Comment by Safihre** [comment]
@KaraokeStu I can edit the Travis build to also save the `spk` files and add all the archs, would that help so you don't have to build them anymore?

**Comment by Safihre** [comment]
Added update of par2cmdline that also boosts performance.
Packages are building correctly: https://travis-ci.org/Safihre/spksrc/builds/273465599

**Comment by Safihre** [comment]
Release me please?
This way the updated par2 package can be tested in `sabnzbd-testing` before it also comes in `sabnzbd` with the release of SABnzbd 2.3.0.

**Comment by ymartin59** [comment]
Is it really worth to package and publish every RC ?

**Comment by ymartin59** [comment]
Please submit single commit PR for such update.

**Comment by Safihre** [comment]
Just remove the `sabnzbd-testing` package if it's too much work for you.

**Comment by ymartin59** [comment]
... well I think there are higher priorities for SynoCommunity ... You can have a look at projects.

**Pull request closed without merging**
