### PR TITLE
Add Vagrant config to automate the "Virtual Machine" setup.

### PR DESCRIPTION
**Pull request by fabacab**
_Motivation:_  Make it easy for people on, e.g., a macOS machine to have a build environment with Vagrant. This is just a start but the idea is to simplify the experience for contributors.
_Linked issues:_  For example, #1340, #788.

I'm not sure the following checklist applies, but leaving it as it was part of the `.github/ISSUE_TEMPLATE.md` template.

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by hgy59** [comment]
@fabacab thanks for your contribution.
I tried vagrant with a debian-buster environment.
The only thing I am missing is the folder sharing between the vagrant box and the host system.
I was expecting that the /vagrant folder within the box is shared with the host folder and so the created packages under /vagrant/packages would be accessible on the host - but it is not.

IMHO it is essential to have a VM with the development environment but the /spksrc folder shared with the host file-system.

I even tried to share folders with `rsync` but this did't work either.

Anybody can help to get shared folders working?

**Comment by fabacab** [comment]
> I even tried to share folders with `rsync` but this did't work either.

Hmm, `rsync` worked for me. What was the issue you experienced with it?

**Comment by hgy59** [comment]
> Hmm, `rsync` worked for me. What was the issue you experienced with it?

I have tested now again with rsync, and indeed changes on the host are updated in the vagrant box with running `vagrant rsync` or `vagrant rsync-auto` on the host.

But rsync does not work bidirectional, i.e. the packages built inside the box are not syncronized to the host.

So it would be better to use shared folders IMHO.

**Comment by fabacab** [comment]
> it would be better to use shared folders IMHO.

I'm confident I can get shared folders working. I'll try to update this PR with another commit that enables shared/sync folders.

**Comment by fabacab** [comment]
@hgy59 Please see commit df6ab3ea9b1aff0e797cd30412ca815c99cf6a2f which includes the changes to the `Vagrantfile` configuration that enable VirtualBox's Shared Folders feature, as requested.

In my testing this results in the experience you're after: anything created in the Vagrant VM's `/vagrant` directory is "shared" (mirrored/written) back to the host machine's Vagrant project root. This means the `packages` directory is accessible to the host even if it's built in the guest.

**Comment by hgy59** [comment]
I tested too, but found issues with toolchain builds, as it is not possible to create hard-links.

Example building package in /vargrant/diyspk/tree:
```
vagrant@buster:/vagrant/diyspk/tree$ make arch-x64
===>  Building package for arch x64
make[1]: Entering directory '/vagrant/diyspk/tree'
===>  Set up toolchain
===>    Downloading files for syno-x64
===>      File x64-gcc493_glibc220_linaro_x86_64-GPL.txz already downloaded
===>    Verifying files for syno-x64
===>      Checking sha1sum of file x64-gcc493_glibc220_linaro_x86_64-GPL.txz
===>      Checking sha256sum of file x64-gcc493_glibc220_linaro_x86_64-GPL.txz
===>      Checking md5sum of file x64-gcc493_glibc220_linaro_x86_64-GPL.txz
/vagrant/toolchain/syno-x64-6.1/../../distrib/toolchain/6.1/x64-gcc493_glibc220_linaro_x86_64-GPL.txz
===>    Extracting for syno-x64
tar -xpf /vagrant/toolchain/syno-x64-6.1/../../distrib/toolchain/6.1/x64-gcc493_glibc220_linaro_x86_64-GPL.txz -C /vagrant/toolchain/syno-x64-6.1/work
tar: x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/libexec/getconf/XBS5_LP64_OFF64: Cannot hard link to ‘x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/libexec/getconf/POSIX_V7_LP64_OFF64’: Operation not permitted
tar: x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/libexec/getconf/POSIX_V6_LP64_OFF64: Cannot hard link to ‘x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/libexec/getconf/POSIX_V7_LP64_OFF64’: Operation not permitted
tar: x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/bin/getconf: Cannot hard link to ‘x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/libexec/getconf/POSIX_V7_LP64_OFF64’: Operation not permitted
tar: x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/bin/ld.bfd: Cannot hard link to ‘x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/bin/ld’: Operation not permitted
tar: x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld.bfd: Cannot hard link to ‘x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/bin/ld’: Operation not permitted
tar: x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-as: Cannot hard link to ‘x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/bin/as’: Operation not permitted
tar: x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-objdump: Cannot hard link to ‘x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/bin/objdump’: Operation not permitted
tar: x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-strip: Cannot hard link to ‘x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/bin/strip’: Operation not permitted
tar: x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ar: Cannot hard link to ‘x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/bin/ar’: Operation not permitted
tar: x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ranlib: Cannot hard link to ‘x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/bin/ranlib’: Operation not permitted
tar: x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: Cannot hard link to ‘x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/bin/ld’: Operation not permitted
tar: x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-nm: Cannot hard link to ‘x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/bin/nm’: Operation not permitted
tar: x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-c++: Cannot hard link to ‘x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-g++’: Operation not permitted
tar: x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-objcopy: Cannot hard link to ‘x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/bin/objcopy’: Operation not permitted
tar: x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc-4.9.3: Cannot hard link to ‘x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-gcc’: Operation not permitted
tar: Exiting with failure status due to previous errors
make[2]: *** [../../mk/spksrc.extract.mk:58: extract_target] Error 2
/vagrant/diyspk/tree/work-x64-6.1/tc_vars.mk:1: *** An error occured while setting up the toolchain, please check the messages above.  Stop.
make[1]: Leaving directory '/vagrant/diyspk/tree'
make: [../../mk/spksrc.spk.mk:508: arch-x64] Error 2 (ignored)
vagrant@buster:/vagrant/diyspk/tree$
```

**Comment by hgy59** [comment]
regarding this [virtualbox forum entry](https://forums.virtualbox.org/viewtopic.php?f=3&t=91596) hard links are not supported with shared folders.

**Comment by fabacab** [comment]
> I tested too, but found issues with toolchain builds, as it is not possible to create hard-links.

Hmm, I'm not aware of a way to make VirtualBox Shared Folders support hard links. Does the `./packages` folder have to be in the same location on the host as the guest? (It didn't seem to when I was trying out the toolchain.)

Another option might be to use [a plugin such as `vagrant-rsync-back`](https://github.com/smerrill/vagrant-rsync-back) that will allow you to `rsync` and sync changes made in the guest back to the host.

**Comment by hgy59** [comment]
@fabacab does the solution with docker container as build environment not work on MacOS?
I thought that with the introduction of fakeroot it is now possible to use the docker image on MacOS without restrictions.

The intension is to have the development environment inside the VM (or docker container) and the spksrc repository clone on the host and shared into the VM (or docker container). 

With docker bind mounts, this works perfectly. Every (manual or automated) synchronization gives unwanted overhead.

**Comment by fabacab** [comment]
> does the solution with docker container as build environment not work on MacOS?

I haven't tried with Docker.

> Every (manual or automated) synchronization gives unwanted overhead.

Sure, I understand that.

I didn't try with Docker *because* of the requirement to set up `fakeroot` on my host first. So I went for the VM. But the VM setup could have been more automated. Once I'm in the VM, I don't really have a need to return to the macOS host, so I just thought I'd submit the easy Vagrant setup. 🤷 I do understand how sync'ing back to the host would be useful, it just isn't something I need (at least not yet).

**Comment by hgy59** [comment]
> I didn't try with Docker _because_ of the requirement to set up `fakeroot` on my host first. S

You don't need fakeroot on the host, we have added fakeroot to the docker image. You only have to define the environment variable `TAR_CMD="fakeroot tar"` for the docker container, so that tar is used with fakeroot inside the container, especially for extracting the toolchains provided by synology.

**Comment by fabacab** [comment]
> You don't need fakeroot on the host, we have added fakeroot to the docker image.

Oh, I misread that. Thanks for clarifying. I'll give that a shot and see if it makes the Vagrant setup here unnecessary. If so I might just convert this PR into a docs update to make the process for the Docker builds easier for a newbie like me to understand.

**Comment by fabacab** [comment]
> I'll give that a shot

I'm not able to achieve the same results by using the documented Docker setup as I was able to achieve in the Virtual Machine. Here is a full transcript of my terminal session:

```
willis:spksrc demouser$ cd /tmp
willis:tmp demouser$ git clone https://github.com/fabacab/spksrc /tmp/spksrc
Cloning into '/tmp/spksrc'...
remote: Enumerating objects: 40026, done.
remote: Counting objects: 100% (964/964), done.
remote: Compressing objects: 100% (772/772), done.
remote: Total 40026 (delta 283), reused 797 (delta 176), pack-reused 39062
Receiving objects: 100% (40026/40026), 49.37 MiB | 1.46 MiB/s, done.
Resolving deltas: 100% (19565/19565), done.
willis:tmp demouser$ docker pull synocommunity/spksrc
Using default tag: latest
latest: Pulling from synocommunity/spksrc
Digest: sha256:31014fa8b45ab7bcf460961fbf2eaa5c9cc7f765e61852ef28060df6f206039d
Status: Image is up to date for synocommunity/spksrc:latest
docker.io/synocommunity/spksrc:latest
willis:tmp demouser$ docker run -it -v /tmp/spksrc:/spksrc -e TAR_CMD="fakeroot tar" synocommunity/spksrc /bin/bash
root@d2f65bb23359:/spksrc# make setup
Creating local configuration "local.mk"...
Setting default toolchain version to DSM-6.1
Setting default toolchain version to DSM-7.0
root@d2f65bb23359:/spksrc# cd spk/transmission
root@d2f65bb23359:/spksrc/spk/transmission# make arch-88f6281
===>  Building package for arch 88f6281
make[1]: Entering directory '/spksrc/spk/transmission'
===>  Set up toolchain 
===>    Downloading files for syno-88f6281
===>      wget https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.1%20Tool%20Chains/Marvell%2088F628x%20Linux%202.6.32/6281-gcc464_glibc215_88f6281-GPL.txz
2021-07-13 00:27:13 URL:https://pilotfiber.dl.sourceforge.net/project/dsgpl/Tool%20Chain/DSM%206.1%20Tool%20Chains/Marvell%2088F628x%20Linux%202.6.32/6281-gcc464_glibc215_88f6281-GPL.txz [35293008/35293008] -> "6281-gcc464_glibc215_88f6281-GPL.txz.part" [1]
===>    Verifying files for syno-88f6281
===>      Checking sha1sum of file 6281-gcc464_glibc215_88f6281-GPL.txz
===>      Checking sha256sum of file 6281-gcc464_glibc215_88f6281-GPL.txz
===>      Checking md5sum of file 6281-gcc464_glibc215_88f6281-GPL.txz
/spksrc/toolchain/syno-88f6281-6.1/../../distrib/toolchain/6.1/6281-gcc464_glibc215_88f6281-GPL.txz
===>    Extracting for syno-88f6281
fakeroot tar -xpf /spksrc/toolchain/syno-88f6281-6.1/../../distrib/toolchain/6.1/6281-gcc464_glibc215_88f6281-GPL.txz -C /spksrc/toolchain/syno-88f6281-6.1/work 
===>    Patching for syno-88f6281
===>    Fixing libtool files for syno-88f6281
chmod -R u+w /spksrc/toolchain/syno-88f6281-6.1/work
env make --no-print-directory tc_vars > /spksrc/toolchain/syno-88f6281-6.1/work/tc_vars.mk 2>/dev/null;
make[1]: *** No rule to make target '7.0'.  Stop.
make[1]: Leaving directory '/spksrc/spk/transmission'
make: [../../mk/spksrc.spk.mk:508: arch-88f6281] Error 2 (ignored)
root@d2f65bb23359:/spksrc/spk/transmission# cd /spksrc/
root@d2f65bb23359:/spksrc# ls
CONTRIBUTING.md  LICENSE.md  README.rst  distrib  kernel    mk      spk        toolkit
Dockerfile       Makefile    cross       diyspk   local.mk  native  toolchain
```

Note that the final `ls` command shows that no `packages` directory was created. The same exact procedure inside the VM prepared with the Vagrant configuration (before trying to use Shared Folders) did successfully create the package.

Am I doing something wrong? (This is why my initial instinct was to use the virtual machine in the first place….) :\

**Comment by hgy59** [comment]
> Edited to add: Yeah, I was doing something wrong, and I figured it out. Sorry for the noise. The correct procedure is actually something like this:
> 
> ```
> make setup
> cd spk/transmission
> make arch-armada370-6.2.4 # <-- Notice the full name of an architecture, with version of DSM software.
> ```
> 
> The architectures are listed, as the wiki page describes, in the `toolchain` directory, replacing `syno-` with `arch-` as the Makefile targets.

@th0ma7 your PR #4689 broke the ability to run `make setup` to set the default toolchain version to 6.1 (or whatever). And there where other caveats, probably all fixed with #4717. `DEFAULT_TC` must define only one TCVERSION to act as default for `make arch-{arch}` in every spk/package folder. 
_We might enhance this to set a default ARCH too, to simply run only `make` in a package folder to do the same as `make ARCH={arch} TCVERSION={tcversion}`._

We should revert to the previous behaviour (only one DEFAULT_TC) and find another solution to define what is built with `all-supported`.
I propose to use a dedicated list of {arch}-{tcversion} (in local.mk set by /spk/Makefile or in a /spk/mk/spksrc-*.mk file like *archs.mk) to define what is built with `all-supported`. This would be the only solution, to build for example `arch-armv7-7.0` and `arch-armv7-6.1` and `arch-armv7-1.2` with `all-supported`.
We already use such a list to define what is built by the github build action (.github/build.yml), and we should use the same for `all-supported` target.

### Just to remember:

`make -C spk/{mypackage} arch-{myarch}-{mytcversion}`
is equivalent to:
`make -C spk/{mypackage} ARCH={myarch} TCVERSION={mytcversion}`

after running `make dsm-6.1` you can run
`make -C spk/{mypackage} arch-{myarch1} arch-{myarch2} arch-{myarch3}`
to build {mypackage} for {myarch1} {myarch2} and {myarch3} with one call of make.
but this is broken after calling `make setup` as  `make dsm-6.1`  does not remove `7.0` from DEFAULT_TC in `local.mk`.

**Comment by fabacab** [comment]
With #4736 merged I no longer have need of this PR so I'll be closing it. I still feel like a Vagrant setup, even a basic one, might be useful as a way to help bring Windows users who cannot use the recommended Docker development environment setup along, but that's not my situation so I cannot commit to improving this beyond what I've already suggested.

Thanks again for your prompt feedback and help and I hope my other now-merger PR is useful for others as well. I want to try to contribute a whole new package so given a bit of time you might see me return here with more questions and/or a new package contribution.

**Pull request closed without merging**
