### PR TITLE
Updated SABnzbd-Testing to 1.1.1 Final

### PR DESCRIPTION
**Pull request by KaraokeStu**
As there is currently no testing version and the 1.1.1 final is ahead of 1.1.1 RC3, I've updated this to final

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by Safihre** [comment]
@Dr-Bean / @KaraokeStu  
First wanted to say great to see so much activity again on the repo :)
For SABnzbd 1.3.0 that's coming after the 1.2.0 releases (beta's for that should start within the week), we will introduce a new Python C-extension that dramatically increases performance.
Is it possible to install pip packages for the SynoCommunity users? 
The extension is available on pip (`pip install sabyenc`) and only requires a basic C-compiler, no other extensions.

**Comment by KaraokeStu** [comment]
I think we should be able to, @Dr-Bean can you confirm?

**Comment by Dr-Bean** [comment]
It's possible, but it means we need to cross-compile Python to be able to create the extension.

So we can add `sabyenc` to `spk/sabnzbd/src/requirements.txt`, and add the string of Python stuff to `spk/sabnzbd/Makefile`, like this: `BUILD_DEPENDS = cross/python cross/setuptools cross/pip cross/wheel`
Rest should be handled by the framework :)

**Comment by Dr-Bean** [comment]
Oh, and add `rsc:share/wheelhouse` to `spk/sabnzbd/PLIST`, we haven't got that in yet.

**Comment by Safihre** [comment]
Great! And this also means that when users update, it also gets installed?

It's still a few months away I guess, but just wanted to make sure!

**Comment by Dr-Bean** [comment]
Yep. It only adds to the build time of the package...which is unfortunate, but otherwise, 'meh' ;)

**Comment by Dr-Bean** [comment]
@KaraokeStu While you're about, mind if I edit the sabnzbd-testing package to add DSM6 compatibility and release a set of packages in a day or two?

**Comment by KaraokeStu** [comment]
Oh absolutely, please do - I'm running DSM 6 so can test it for you too :)

**Comment by Dr-Bean** [comment]
Well, I'm actually hoping to find someone with a vanilla setup to test if the upgrade path works somewhat (package installed on DSM5, upgrade to DSM6, 'my' upgrade). I'm guessing you're not the right person for that :P
I'm reasonably sure we're going to end up recommending reinstalling packages in a lot of cases...

**Comment by cytec** [comment]
so we have a DSM6 "default/support" approach now? yeah!

**Comment by Dr-Bean** [comment]
Cool. Is the new bootloader able to work with DSM5, or do you have to switch over to upgrade? I still need to rebuild my VM's and my physical device, none of them are representative of an average device with the amount of times I bricked and revived them...

Anyway, can you try this: https://www.dropbox.com/s/7wzdtucopidahdj/sabnzbd-testing_x64-5.2_1.1.1-11.spk.
I brought it back to bare minimum wrt code changes, but if it survives an upgrade, then that's all we need. One thing's for sure. Synology's changes, besides being backwards incompatible have...quirks.

**Comment by Safihre** [comment]
@Dr-Bean doesn't Synology work with you guys at all? Or are there projects like yours to install external things on a Synology NAS?

**Comment by KaraokeStu** [comment]
BTW guys, just tried a new kernel and bricked my DSM box - trying to get it back now! :(

**Comment by Dr-Bean** [comment]
@KaraokeStu No rush. I was thinking of adding an upgrade wizard and a step to the install wizard to explain to use `sc-download` for permissions handling, but I'm not finishing it today regardless.

@Safihre Well, at least from my point of view, Synology, as an organization, _tolerates_ third party package developers. I won't say I never see any response or results, because I have, but Synology certainly won't go out of their way to help us out. That applies to the whole chain: from DSM development, kernel files and toolchains to documentation and support.
I can't speak for other developers though, including other members of SynoCommunity, they may have different experiences altogether. /rant ;)

**Comment by KaraokeStu** [comment]
Just so you know that, although my system is broken, I have spun up both a DSM 5.2 and DSM 6 instance for testing. The spk you supplied works correctly.

**Comment by Dr-Bean** [comment]
Thanks. One more question: Can you provide the following from both instances (I had wanted to add the questions earlier, but it slipped my mind):
- Content of /etc/passwd wrt `sabnzbd-testing` and `sc-sabnzbd-testing`
- Content of /etc/shadow wrt `sabnzbd-testing` and `sc-sabnzbd-testing`
- Content of /etc/group wrt `sabnzbd-testing` and `sc-sabnzbd-testing`

Output of the following set of commands (some should not output anything or spit out an error):
```
synouser --get sabnzbd-testing
synouser --get sc-sabnzbd-testing
synogroup --get sabnzbd-testing
synouser --enum all | grep sabnzbd-testing
synogroup --get sc-sabnzbd-testing
synogroup --enum all | grep sabnzbd-testing
synogroup --enum all | grep sc-download
```

**Comment by Safihre** [comment]
@KaraokeStu We just released 1.2.0Beta1. We don't use the pyOpenSSL anymore but cryptography, dunno if that makes a lot of difference :P

**Pull request merged**
