### PR TITLE
Allow arch-specific level patch to mk build

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  Allow arch specific patches to be applied automatically.
_Linked issues:_  Relates to multi-patches on ffmpeg where some of them are arch specific

### Checklist
@hgy59 : To be sure about existing packages I propose to test the following:
- [x] Buildrule make all-supported completed successfully for `mono` (has patch in native module)
- [x] Buildrule make all-supported completed successfully for `redis` (regular patches)
- [x] Buildrule make all-supported completed successfully for `minio` (without any patch file)
- [x] Buildrule make all-supported completed successfully for `ffmpeg` #3873 (regular + subarch patches)
- [x] Buildrule make all-supported completed successfully for `tvheadend` on top of #3873

### CODE REVIEW

**Comment by th0ma7** [comment]
I need to rework my regex for arm & x64 as no shell compliant.

**Comment by hgy59** [comment]
Just wonder, why use regex? As we have x64_ARCHES etc. we could define the specific patch folders must match exactly the prefix of `_ARCHES` (i.e. x64, x86, ARM5, ARM7, ARM8, PPC). Or do I miss the background?

**Comment by th0ma7** [comment]
@hgy59 agreed and coffee must have been missing this morning.  I guess it's because everytime I look for ARM specific searches it always refers to ARMvX and same for x86_64.  On the other hand, the simpler the better.

Additional suggestion I just pushed is to dig this a little further in order to have another level for sub-arch specific patches.  I currently have a case where I have a patch to apply only on `alpine`, another on `qoriq` and a last one that I really absolutely only want applied on `evansport`.  I guess a for loop against each $(ARCH) would be more efficient than the quick patch proposal I just uploaded, but this is for discussion...

**Comment by hgy59** [comment]
Is it worth to add such specific patching to the framework?
You always have custom PATCH_TARGET (incl. PRE_ and POST_) available in the package Makefile.
This way you can override the whole patch process or add specific steps.

And you have a variable `PATCHES` that can be used to define specific patchfiles to apply (e.g. depending on arch...)

**Comment by th0ma7** [comment]
I tried the `PATCHES` variable but with already a few patches to deal with it really become cumbersome to add them all individually for a single extra.
I haven't looked into `PATCH_TARGET`, any doc on it so I have a quick look at that option?  I've looked into the code and haven't quite understood that.
Still, something automated eliminate the extra oops and special cases, additional code and would simplify things.

**Comment by th0ma7** [comment]
Found a much simpler approach using nested `foreach`... 
Does all I needed by sorting all patches from:
* `patches/*.patch`
* `patches/arch/*.patch`
* `patches/subarch/*.patch`

**Comment by th0ma7** [comment]
@hgy59 thnx!  And you are absolutely right!

**Comment by th0ma7** [comment]
@hgy59 as this is framework related does it require additional approvals before merging or can I proceed as is?

**Comment by hgy59** [comment]
@th0ma7 I suppose you have tested this with the tvheadend package and the ppc specific patches. 

To be shure about existing packages I propose to test the following:
- [ ] Buildrule make all-supported completed successfully for tvheadend 
- [ ] Buildrule make all-supported completed successfully for mono (has patch in native module)
- [ ] Buildrule make all-supported completed successfully for e.g. redis (regular patches)
- [ ] Buildrule make all-supported completed successfully for e.g. minio (without any patch file)

Feel free to add this list to the PR Checklist

**Comment by th0ma7** [comment]
@hgy59 , theses are good set of tests.
I've added the new PR for ffmpeg as there are subarch patches in it.

It allowed me to find an issue with `x64` arch where there are multiple matches due to other subarches containing `x64` string.  The usage of `filter` instead of `findstring` allowed to solve that.
Test-builds undergoing.

**Comment by th0ma7** [comment]
@hgy59 I believe it's now ready for merging.

**Pull request merged**
