### PR TITLE
Fix cross/micro buildvcs usage

### PR DESCRIPTION
**Pull request by jisakiel**
## Description

Found while trying to rebuild packages...

## Checklist

- [ ] Build rule `all-supported` completed successfully - can't exactly issue that on a cross/ directly I believe. Still the change is quite self contained. 
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [ ] New Package
- [ ] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
@jisakiel I cannot reproduce this error with the current dev env.

But if this is a problem under debian 12 (i.e. bookworm), you should try to fix this the same way, as we do in cross/gitea with
```
export EXTRA_GOFLAGS=-buildvcs=false
```

we should always try to avoid patches, as those are annoying to maintain...

**Comment by jisakiel** [comment]
I've found this both under bookworm and under the current docker env, when building arch-apollolake for 7.1 and 7.2. It's not impossible that I have a newer go (from 7.2) if the tooling doesn't enforce per platform native tools?

I tried exporting flags to no avail, I suspect because I'd need GOVARS instead (https://github.com/zyedidia/micro/blob/0859f4aa36d69e5cdb92b868dfc08498fd8a1d70/Makefile#L19).

**Comment by jisakiel** [comment]
On my bookworm debian I've just tried removing this patch and replacing it with:
```
 INSTALL_TARGET = micro_install

+export GOVARS=-buildvcs=false
+
 include ../../mk/spksrc.cross-go.mk
```

And I get, for a 7.2 apollolake build:
```
root@9d94521c089f:/spksrc# make -C cross/micro arch-apollolake
make: Entering directory '/spksrc/cross/micro'
===>  Building package for arch apollolake
make[1]: Entering directory '/spksrc/cross/micro'
===>  Setting-up toolchain
env make --no-print-directory cmake_vars > /spksrc/toolchain/syno-apollolake-7.2/work/tc_vars.cmake 2>/dev/null;
env make --no-print-directory meson_vars > /spksrc/toolchain/syno-apollolake-7.2/work/tc_vars.meson 2>/dev/null;
env make --no-print-directory tc_vars > /spksrc/toolchain/syno-apollolake-7.2/work/tc_vars.mk 2>/dev/null;
===>  Downloading files for micro
===>    File micro-2.0.11.tar.gz already downloaded
===>  Verifying files for micro
===>    Checking sha1sum of file micro-2.0.11.tar.gz
===>    Checking sha256sum of file micro-2.0.11.tar.gz
===>    Checking md5sum of file micro-2.0.11.tar.gz
/spksrc/cross/micro/../../distrib/micro-2.0.11.tar.gz
===>  Processing dependencies of micro
make[2]: Entering directory '/spksrc/native/go'
make[2]: Nothing to be done for 'default'.
make[2]: Leaving directory '/spksrc/native/go'
===>  Extracting for micro
tar -xzpf /spksrc/cross/micro/../../distrib/micro-2.0.11.tar.gz -C /spksrc/cross/micro/work-apollolake-7.2
===>  Patching for micro
===>  Configuring for micro
===>  - Configure ARGS:
===>  - Install prefix: /usr/local/micro
===>  - Install prefix [var]: /usr/local/micro/var
===>  Compiling for micro
make[2]: Entering directory '/spksrc/cross/micro/work-apollolake-7.2/micro-2.0.11'
GOOS=linux GOARCH=amd64 go generate ./runtime
go: downloading gopkg.in/yaml.v2 v2.2.8
go build -trimpath -ldflags "-s -w -X github.com/zyedidia/micro/v2/internal/util.Version=2.0.11 -X github.com/zyedidia/micro/v2/internal/util.CommitHash=225927b -X 'github.com/zyedidia/micro/v2/internal/util.CompileDate=June 14, 2023' " ./cmd/micro
go: downloading github.com/yuin/gopher-lua v0.0.0-20191220021717-ab39c6098bdb
go: downloading github.com/go-errors/errors v1.0.1
go: downloading github.com/mattn/go-isatty v0.0.11
go: downloading github.com/zyedidia/tcell/v2 v2.0.9
go: downloading github.com/layeh/gopher-luar v1.0.7
go: downloading github.com/zyedidia/go-runewidth v0.0.12
go: downloading github.com/zyedidia/terminal v0.0.0-20180726154117-533c623e2415
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/zyedidia/go-shellquote v0.0.0-20200613203517-eccd813c0655
go: downloading github.com/zyedidia/clipper v0.1.0
go: downloading github.com/blang/semver v3.5.1+incompatible
go: downloading github.com/sergi/go-diff v1.1.0
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/zyedidia/glob v0.0.0-20170209203856-dd4023a66dc3
go: downloading github.com/zyedidia/json5 v0.0.0-20200102012142-2da050b1a98d
go: downloading golang.org/x/sys v0.0.0-20191026070338-33540a1f6037
go: downloading github.com/rivo/uniseg v0.1.0
go: downloading github.com/zyedidia/pty v1.1.20
go: downloading github.com/gdamore/encoding v1.0.0
go: downloading github.com/lucasb-eyer/go-colorful v1.0.3
go: downloading github.com/xo/terminfo v0.0.0-20200218205459-454e5b68f9e8
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
make[2]: *** [Makefile:19: build-quick] Error 1
make[2]: Leaving directory '/spksrc/cross/micro/work-apollolake-7.2/micro-2.0.11'
make[1]: *** [../../mk/spksrc.compile.mk:46: compile_target] Error 2
make[1]: Leaving directory '/spksrc/cross/micro'
make: Leaving directory '/spksrc/cross/micro'
```

FWIW:
```
root@9d94521c089f:/spksrc# native/go/work-native/go/bin/go version
go version go1.20.4 linux/amd64
``

**Comment by jisakiel** [comment]
Build failures seem on 32 bit 6.2.4 architectures (i.e. aarch64 is OK but arm7 isn't). Rebasing my branches and trying without the cross/micro just to verify, but I struggle to see how it woudl be related being that it fails on nnn, which doesn't have build dependencies to cross/micro (besides the simplicity of my patch!).

**Comment by hgy59** [comment]
fixed with 205c366de2433c55873ba748dcd92713d8ce6922

**Pull request closed without merging**
