### PR TITLE
Add missing link to Architecture wiki

### PR DESCRIPTION
**Pull request by sectioneight**
Motivation: Make the link work as expected. Readme change only, no tests run.

### CODE REVIEW

**Comment by sectioneight** [comment]
Preview here: https://github.com/sectioneight/spksrc/blob/87acd6c6711e4508e80109d8fc17f2b0179e15c5/README.rst

**Comment by sectioneight** [comment]
This is what it currently looks like:

image

The `#id2` goes nowhere.

**Comment by Dr-Bean** [comment]
That section of text will likely be removed (again ;)) when I get to it. See also https://github.com/SynoCommunity/spksrc/issues/2503.

**Comment by Dr-Bean** [comment]
Done.
See https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO, the example stuff is integrated into that. The README refers to it via [Usage](https://github.com/SynoCommunity/spksrc#usage). Also CONTRIBUTING refers to it, here: [Pull Requests](https://github.com/SynoCommunity/spksrc/blob/master/CONTRIBUTING.md#pull-requests)

**Pull request closed without merging**
