### PR TITLE
Update master to DSM6 only

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  Remove all non-DSM6 files from master.
_Linked issues:_  Relates to discussion from PR #3908 and #3917 

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by th0ma7** [comment]
I just noticed that there where an existing dsm6 branch as such my pull request tries to update the existing up to current master.

Anyway at this stage, this is just to startup the discussion.

**Comment by ymartin59** [comment]
@th0ma7 "dsm6" branch was there to prepare application ports to new version. That branch must be discarded now, most work has been merged into master years ago.

**Comment by th0ma7** [comment]
> @th0ma7 "dsm6" branch was there to prepare application ports to new version. That branch must be discarded now, most work has been merged into master years ago.

@ymartin59 then could it be possible to delete deprecated `master/dsm6`?  I'll redo my work (literally a 5 min `git rm -r` work) along with a new PR so it become in a shape for merging to master (or at least leading to discussions on next steps)

**Comment by hgy59** [comment]
I think this PR is not about to create a DSM 6 branch. It is about to remove the pre-DSM6 code from the master branch.
And as we supported migration from DSM 5 to DSM 6 (on the master branch until now) there will come a time, when we will support DSM 6, DSM 7 and migration from DSM 6 to DSM 7 on the master branch.

**Comment by th0ma7** [comment]
@ymartin59 is the intent to also delete the dsm6 branch from spksrc?

**Comment by ymartin59** [comment]
@th0ma7 I have deleted it. Its content is old and contain pre-dsm6 package with framework upgrades to support 5-to-6 package migration.

**Pull request closed without merging**
