### PR TITLE
Update syncthing to 0.14.3

### PR DESCRIPTION
**Pull request by ivlis**

### CODE REVIEW

**Comment by christofdamian** [comment]
yes please, they changed the protocol again. 0.13 can't connect to 0.14 .

**Comment by RockingRolli** [comment]
+1

**Comment by dj-plx** [comment]
+1

**Comment by cytec** [comment]
afaik you can update using syncthing's internal updater...

**Comment by Dr-Bean** [comment]
+ needs SPK_REV update. @ivlis Still working on this?

**Comment by Dr-Bean** [comment]
Closing: this PR is outdated. #2553 is more up-to-date.

**Pull request closed without merging**
