### PR TITLE
Update SABnzbd to 2.2.1

### PR DESCRIPTION
**Pull request by Safihre**

### CODE REVIEW

**Comment by Safihre** [comment]
Something wrong with this one? I even build it, but I don't have a Synology so can't test the install.

- [x] Build rule `all-supported` completed successfully

**Comment by KaraokeStu** [comment]
To be honest, I missed it.

One issue I'm having is with unrar though, so I'll need to check that out

**Comment by Safihre** [comment]
Issues with unrar? When using it?

Also that `all-supported` build takes forever, my god. This should really be ported to Travis.

**Comment by ignoremenow** [comment]
If you happened to build it for all :) could you send me a link to the armada375 package? I have 
 a DS215j to test on. I have 2.2.1 running on my computer with unrar 5.5.8 installed and all it's been looking ok.

**Comment by Safihre** [comment]
I deleted them all after building, the VM grew so large.. Like 9GB for 1 build of all-supported..

**Comment by ignoremenow** [comment]
Ok I will build off your branch and see if I can reproduce.

**Comment by maxrogers** [comment]
@KaraokeStu @Safihre 
I had the same issue with unrar. Here is the fix: https://github.com/SynoCommunity/spksrc/pull/2887/files#diff-4b089689ff77f9ccfd4b9e97da8aaeb4

**Comment by ignoremenow** [comment]
So is the fix to back port the unrar patch from dsm6 to master? Or is it more complicated then that?

**Comment by maxrogers** [comment]
@ignoremenow that fix will not be merged into DSM6. It can be used as a reference to fix unrar in master. After master is fixed and updated then those fixes and updates can merge to DSM6 (per @ymartin59)

**Comment by ignoremenow** [comment]
Yeah in master I updated 001-remove-defaul-env-flags.patch for unrar and was able to properly build it.

**Comment by KaraokeStu** [comment]
Could you possibly open that as a new PR for me? 

I'll get both merged same day and get it built and released.

Cheers,

Stu

**Comment by ignoremenow** [comment]
Just to be clear I only tested the updated unrar patch on one device, and currently testing the updated sab package now.

**Comment by maxrogers** [comment]
@KaraokeStu https://github.com/SynoCommunity/spksrc/pull/2898

**Comment by ymartin59** [comment]
About `unrar`, it no longer compiles since PR #2878 has been merged without tests.

I am working on SquidGuard update which depends on `unrar` since 12 days now #2883

And I decided to discard that useless patch completely: https://github.com/SynoCommunity/spksrc/pull/2883/files#diff-4b089689ff77f9ccfd4b9e97da8aaeb4

**Comment by ymartin59** [comment]
@ignoremenow May you please test sab package simply removing that patch on unrar ?

**Comment by ignoremenow** [comment]
sure I can give it a shot.

**Comment by ignoremenow** [comment]
Ok deleted the patches directory in the unrar folder and doing a clean build.

**Comment by ignoremenow** [comment]
testing the sabnzbd build with the unrar patches went well.

**Comment by ignoremenow** [comment]
Looks like it fails without the patch

```
make[2]: Entering directory '/home/ignoreme/Build/spksrc/cross/unrar'
===>  Downloading files for unrar
wget ftp://ftp.rarlab.com/rar/unrarsrc-5.5.8.tar.gz
2017-08-30 14:05:16 URL: ftp://ftp.rarlab.com/rar/unrarsrc-5.5.8.tar.gz [222285] -> "unrarsrc-5.5.8.tar.gz.part" [1]
===>  Verifying files for unrar
===>    Checking sha1sum of file unrarsrc-5.5.8.tar.gz
===>    Checking sha256sum of file unrarsrc-5.5.8.tar.gz
===>    Checking md5sum of file unrarsrc-5.5.8.tar.gz
/home/ignoreme/Build/spksrc/cross/unrar/../../distrib/unrarsrc-5.5.8.tar.gz
===>  Processing dependencies of unrar
===>  Extracting for unrar
tar -xzpf /home/ignoreme/Build/spksrc/cross/unrar/../../distrib/unrarsrc-5.5.8.tar.gz -C /home/ignoreme/Build/spksrc/spk/sabnzbd/work-armada375-5.2 
===>  Patching for unrar
===>  Configuring for unrar
===>  Compiling for unrar
make[3]: Entering directory '/home/ignoreme/Build/spksrc/spk/sabnzbd/work-armada375-5.2/unrar'
c++ -I/home/ignoreme/Build/spksrc/toolchains/syno-armada375-5.2/work/arm-marvell-linux-gnueabi/arm-marvell-linux-gnueabi/libc/usr/include -mhard-float -mfpu=vfpv3 -I/home/ignoreme/Build/spksrc/spk/sabnzbd/work-armada375-5.2/install//usr/local/sabnzbd/include  -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DRAR_SMP -DUNRAR -c rar.cpp
c++: error: unrecognized command line option ‘-mfpu=vfpv3’
makefile:132: recipe for target 'rar.o' failed
make[3]: *** [rar.o] Error 1
make[3]: Leaving directory '/home/ignoreme/Build/spksrc/spk/sabnzbd/work-armada375-5.2/unrar'
../../mk/spksrc.compile.mk:36: recipe for target 'compile_target' failed
make[2]: *** [compile_target] Error 2
make[2]: Leaving directory '/home/ignoreme/Build/spksrc/cross/unrar'
../../mk/spksrc.depend.mk:44: recipe for target 'depend_target' failed
make[1]: *** [depend_target] Error 2
make[1]: Leaving directory '/home/ignoreme/Build/spksrc/spk/sabnzbd'
../../mk/spksrc.spk.mk:418: recipe for target 'arch-armada375' failed
make: [arch-armada375] Error 2 (ignored)
```

**Comment by ymartin59** [comment]
@ignoremenow Sure I was wrong. Cross-compiling to ARM or PPC requires that patch. Thank you.

**Comment by ignoremenow** [comment]
no worries. happy to help.

**Comment by Safihre** [comment]
@ignoremenow could you test something? Because a user reported that as soon as sabnzbd calls unrar, the memory usage of the package spikes and never goes down again (#2856). Do you also see that?

**Comment by ignoremenow** [comment]
Sure I can take a look. I think there has been a memory issue with it for a bit I had a scheduled task that did a stop then start every day on it. I disabled it with this upgrade thinking it was fixed but haven't looked at it lately.

**Comment by Safihre** [comment]
Indeed the latest versions of Sabnzbd cannot just be blamed for being memory hog, it doesn't happen on other platforms but they don't want to believe me in #2856.

**Comment by ignoremenow** [comment]
Yep I read that. I've even tried using the pickle option and that never worked.

**Comment by Safihre** [comment]
The user noticed that if only Download (so not +Unpack etc)  is selected memory stays normal.

**Comment by ignoremenow** [comment]
Yeah i've already proven that incorrect. Going to try a different nzb to test against. Just realized The one I am using just has a join, unrar. ALso I noticed that the 2.2.1 have on my computer not nas I can't use the -t0 option anymore in the par2 options and had to delete them to get it to work. which was weird.

**Comment by ignoremenow** [comment]
Also this could be a arch specific issue. What model does he have?

**Comment by ignoremenow** [comment]
oh i think your aware of the -t0 I see some forum posts about it. I am going to try it manually with these tests to see whats up. Since I have to try all the different types of downloading.

**Comment by ignoremenow** [comment]
yeah -t0 only tbb not par2cmdline

**Comment by ignoremenow** [comment]
Stop then start and going to the main page - 21MB
Clicking around config then going back to main page - 34MB
Add a nzb and just download it, when completed - 60MB
Add a nzb download/verify/unrar/delete - 63MB

**Comment by ignoremenow** [comment]
Gonna try out pickle

**Comment by ignoremenow** [comment]
with pickle
Add a nzb download/verify/unrar/delete - 60MB

**Comment by ignoremenow** [comment]
If I justs top start and then add and do nothing with the interface and just add the nzb

with pickle
Add a nzb download/verify/unrar/delete - 56MB
withput pickle
Add a nzb download/verify/unrar/delete - 60MB

**Comment by ignoremenow** [comment]
So that's what I got need anything else?

**Comment by Safihre** [comment]
Thanks! :) I will ask him to do the same steps and which arch he has.

**Comment by ymartin59** [comment]
@ignoremenow  @Safihre  May you please report your measures and finding in #2856 for tracking. This PR is already merged, this conversation will soon be forgotten.

**Comment by ignoremenow** [comment]
Done.

**Pull request merged**
