### PR TITLE
Update ffmpeg to 3.4.2 with vaapi support for intel x64

### PR DESCRIPTION
**Pull request by hgy59**
_Motivation:_ Support video accelleration API for intel chips
_Linked issues:_ #3207

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### Features
- ffmpeg is built with --enable-vaapi (for x64 archs only)
- libva-utils is included (vainfo and other tools)
- i965 video driver is included
- tested with DS918+ (build for arch-apollolake-6.1 and arch-x64-6.1)

### CODE REVIEW

**Comment by ymartin59** [comment]
OK interesting. But why not implement my proposal to link against Video Station shared libraries already available ?

**Comment by ymartin59** [comment]
@hgy59 My idea https://github.com/SynoCommunity/spksrc/issues/3207#issuecomment-371965875 was to build ffmpeg thanks to "libva*.so" libraries from VideoStation to avoid to rebuild them including kernel modules.
I would try following sequence:
- download VideoStation package from Synology
- extract it into `install` so that `ffmeg` CMake finds `libva*.so`
- add RPATH to CMake options to get binaries able to load VAAPI libraries from `/var/packages/VideoStation/target/lib`

Just an idea, it may not be successful... Your trial may face troubles to have libraries matching kernel modules.

**Comment by hgy59** [comment]
@ymartin59 I presume that linking to *.so will not be possible without *.la file (not sure for linux, but on Windows you need the *.def file to link to *.dll)
any linux c/c++ link/libtool guru here?

**Comment by hgy59** [comment]
@ymartin59 and how to download spk from synology from the build environment?

**Comment by m4tt075** [comment]
@hgy59 Just googled, but maybe from here?
https://usdl.synology.com/download/Package/spk/VideoStation/?C=M;O=D

**Comment by ymartin59** [comment]
@hgy59 About libraries, C compiler only requires `.h` file and `.so` to link dynamically: https://stackoverflow.com/questions/12237282/whats-the-difference-between-so-la-and-a-library-files
(`.a` and `.la` are for static linking)

**Comment by MrSpoocy** [comment]
I think (if we can) we are avoid to use any lib from Synology. We can see that they use often old lib (ffmpeg, php 5.6) as core. Its better to create own "same" lib, to get the fresh version and newest bugfix.

**Comment by ymartin59** [comment]
@MrSpoocy I can only agree with you, but concerning hardware-related libraries like "libva*" and "drm" kernel drivers, it sounds wiser to keep in-line with what Synology provides in DSM.

**Comment by m4tt075** [comment]
@ymartin59 Have you ever had a chance to look into this PR? I think it could be a stepping stone for further updates. Obvisouly biased, benefitting from vapi integration...  ;-)

**Comment by m4tt075** [comment]
@ymartin59 This PR looks very logical to me, but I'm also aware that you looked into an alternative implemenation method. From what you know now, would you still advocate an alternative approach?

**Comment by ymartin59** [comment]
I still consider that if version provided in DSM "works", there is no need to rebuild or to update - I faced it recently with fuse for sshfs.
If lacking libva headers and so files to compile ffmpeg, spksrc may build same version from sources but no include them in package - so that binaries runs over libraries provided by DSM.

**Comment by m4tt075** [comment]
@ymartin59 It takes character to arrive at conclusions like this, and even more so to state them publically. I enjoy being part of this project!
I fully agree with including this PR in our update.

@hgy59 Many thanks for your contributions and your patience!

**Comment by ymartin59** [comment]
@hgy59 Thanks for your work. It will be included with FFmpeg 4.1 PR #3575 I will take care to keep your author in commits after merge. So I close this one.

**Pull request closed without merging**
