### PR TITLE
Updated sabNZBd Testing to 0.8.0 Beta 1

### PR DESCRIPTION
**Pull request by KaraokeStu**

### CODE REVIEW

**Comment by Dr-Bean** [comment]
For next time, please combine these three changes into one commit :)

**Comment by KaraokeStu** [comment]
Sorry about that, edited manually via the site




"Dr-Bean" <notifications@github.com> wrote:
For next time, please combine these three changes into one commit :)

**Comment by Dr-Bean** [comment]
Needs digests fixing too.

**Comment by KaraokeStu** [comment]
Fixed the digests file too :)

**Comment by Dr-Bean** [comment]
Done with 887d2acdcd118b352f766f67e246aa02bfd22c5a. I didn't use your PR, because it needed additional work (old digest entries were not removed), and I made some additional changes to the package. 
Thanks for the effort though.

**Comment by Dr-Bean** [comment]
A bit late, but SABnzbd-testing-0.8.0Beta1-2 has been published on the repository.

**Pull request closed without merging**
