### PR TITLE
build a native file to avoid version conflicts

### PR DESCRIPTION
**Pull request by jisakiel**
This makes newer files (i.e. that of bookworm) still allow compiling older file versions.

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [ ] New Package
- [ ] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
Can you further elaborate on the requirement here?  Isn't file command already available within the debian container image?

**Comment by hgy59** [comment]
@jisakiel thanks for contributing.
AFAICR at the time of writing __ it was not possible to build a different version of file, not even by using a native/file of the same version.
But since you show that this is possible, we can now update file to the latest version (i.e. 5,44).

**Comment by jisakiel** [comment]
> Can you further elaborate on the requirement here? Isn't file command already available within the debian container image?

root@9d94521c089f:/spksrc# file --version
file-5.44

I'm trying a bookworm based debian dockerfile I'll share as well.

**Comment by hgy59** [comment]
> I had deliberately done this independently of a bump, so that I could verify it working and it's easier to revert if needed :)

I tried to verify this, but it does not work with file v5.45.
Still get the error:
```
Making all in magic
make[5]: Entering directory '/spksrc/cross/file/work-x64-6.2.4/file-5.45/magic'
Cannot use the installed version of file (5.39) to
cross-compile file 5.45
Please install file 5.45 locally first
```

The requirement _the build environment must have file installed of the same version_ is still mandatory.

It is not enough to have a native file in the path.

**Comment by hgy59** [comment]
@jisakiel I found a solution to use native/file in #5897. It needs a patch to create the magic.mgc file with the native version.

**Comment by hgy59** [comment]
@jisakiel thank you for triggering this. It is now integrated with #5897

**Pull request closed without merging**
