### PR TITLE
Tvheadend 4.2.3 fixes

### PR DESCRIPTION
**Pull request by m4tt075**
_Motivation:_
The current TVH package shows two distinct issues: 
1) The URL in the DSM Web GUI is not set correctly (c.f. issue #2764)
2) The enabling of the `pngquant` option and cross-package in the most recent maintenance update breaks compilation on platforms where `pngquant` is not installed (c.f. discussion after merging of #2815)

_Description:_
This PR fixes both issues. To address 2), the `pngquant` option is disabled, the corresponding cross package removed. This slightly increases the size of the packages again, but does not affect functionality by any means.

### Checklist
- [x] Build rule `all-supported` completed successfully with 5.2. toolchains
- [x] Package upgrade completed successfully
- [ ] New installation of package completed successfully

### CODE REVIEW

**Comment by m4tt075** [comment]
@ymartin59, @manuelrn : This should be it. Again, many thanks for your support!

**Comment by manuelrn** [comment]
Thanks to you @m4tt075 for your good work ;)

**Comment by ymartin59** [comment]
@m4tt075 As a possible future improvement, do not hesitate to refer to GitHub issues' number in your commit message, so that to notify it about work in progress on  it.

**Comment by G1zm0** [comment]
@KaraokeStu 
Any news on the publishing of this package?
The repository is still stuck on 4.0.9
Thnx

**Comment by ymartin59** [comment]
I tried to publish but still fails #2910. Bad luck !

**Comment by G1zm0** [comment]
@ymartin59 , any change you have an Avaton package available for me so I can manually update?

**Comment by m4tt075** [comment]
@G1zm0 : 
https://www.tvheadend.org/boards/5/topics/27780
Post #1. Don't forget to back up your installation and please report back how it goes...

**Comment by G1zm0** [comment]
It's not working.
I did a manual upgrade, this looked OK, but the webinterface is not responding. Also the CPU is peaked at 99%. Restart of the package and reboot did not work.
I did a clean install, but the package cannot be installed. The wizard shows a "Not Available" response.

I'm reverting back

**Comment by m4tt075** [comment]
@G1zm0 : When the CPU peaks, TVH is still running an internal backup and converting configuration files. This takes about 10 min on my system. Only afterwards, the actual upgrade takes place, CPU goes back to normal and the WebIF should be accessible.

No idea why the clean install failed though. You'd still have to install manually. The only difference is that you deinstall your old TVH version first. Assuming you did that, which wizard showed "Not Available"? Was it within DSM / the package center or TVH's wizard after it has started?

**Comment by G1zm0** [comment]
After your tips I gave it another try.
I had to wait for more than one hour for the package was done.

After that the WebIF was accessible. 
Maybe a warning about the converting taking time should be in place to prevent people, like me, from killing the upgrade

**Comment by m4tt075** [comment]
@G1zm0 : An hour? Gee! That's a new record I guess...  :-)
But glad it is working now! Thanks for retrying and reporting back!

**Comment by ymartin59** [comment]
I have just published package for DSM 5.2 https://synocommunity.com/package/tvheadend

**Pull request merged**
