### PR TITLE
ffmpeg7 + tvheadend and chromaprint migration to newest

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

- `ffmpeg7` initial release
- `tvheadend` update to commit from Sept. 20th 2024 + migrate to `ffmpeg7`
- `chromaprint` migrate to `ffmpeg7`

Fixes # 

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [x] New Package
- [ ] Package update
- [ ] Includes small framework changes
- [x] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
@WesSouza, @reykjalin and @jmqm now that the background work to get an individual videodriver package with opencl is completed, I am finally able to work on getting ffmpeg 7.0.2 up and running.

Feel free to test this upcoming update - will become from the Check tab under the build summary.  Build process normally takes a few hours but if all goes well packages should be available by tomorrow.

**Comment by nyanmisaka** [comment]
- https://github.com/FFmpeg/FFmpeg/commit/c31d2326560087b80f8523b27060ad6388369cac

- https://github.com/search?q=repo%3AFFmpeg%2FFFmpeg+%22%24%28ARCH%29%22&type=code

- https://github.com/SynoCommunity/spksrc/blob/8c4a64df7e8aab4d4a4a0e83d636fce538bc9d33/cross/ffmpeg7/patches/0001-replace-arch-env-by-ffmpeg_arch.patch

**Comment by th0ma7** [comment]
> * [FFmpeg/FFmpeg@c31d232](https://github.com/FFmpeg/FFmpeg/commit/c31d2326560087b80f8523b27060ad6388369cac)
> * https://github.com/search?q=repo%3AFFmpeg%2FFFmpeg+%22%24%28ARCH%29%22&type=code
> * https://github.com/SynoCommunity/spksrc/blob/8c4a64df7e8aab4d4a4a0e83d636fce538bc9d33/cross/ffmpeg7/patches/0001-replace-arch-env-by-ffmpeg_arch.patch

@nyanmisaka thnx for the tips, with this I was able to update our ARCH renaming patch and things now works out! :rocket:

@WesSouza, @reykjalin and @jmqm package should now build succesfullly if your interested at testing.

**Comment by WesSouza** [comment]
@th0ma7 what can I do to help with testing? I don't know how to change Jellyfin's ffmpeg path, the input on admin that points to `/var/packages/ffmpeg6/target/bin/ffmpeg` is not editable.

I was able to install it, but the only manual use case I have is transcoding mkv -> mp4, which does work but probably doesn't test it thoroughly.

**Comment by th0ma7** [comment]
That's interesting, I haven't thought of this as I'm not to involved with the jellyfin package.

@mreid-tt or @hgy59 would it be worth it that i change jellyfin's ffmpeg path and bump package revision to start using ffmpeg7 within this PR?  That would allow pre-testing.

**Comment by mreid-tt** [comment]
> @mreid-tt or @hgy59 would it be worth it that i change jellyfin's ffmpeg path and bump package revision to start using ffmpeg7 within this PR? That would allow pre-testing.

hey @th0ma7, when I worked on Jellyfin 10.8.x the path to the ffmpeg library was editable and I would have experimented with changing ffmpeg4 to ffmpeg6 but it seems that the codebase has changed. I suspect this would be something upstream at the Jellyfin repo since there were no major changes for Jellyfin 10.9.x in the PR other than updating the service-setup to point to the ffmpeg6 folder.

If you guys feel adventurous you can manually change the ffmpeg path with these steps:

1. Stop Jellyfin in the DSM Package Center
2. Enable SSH (if required) and SSH into your DiskStation
3. Navigate to the Jellyfin scripts folder (`cd /var/packages/jellyfin/scripts/`)
4. Make a backup of your script (`sudo cp -p service-setup service-setup.bak`)
5. Edit the service-setup file (`sudo vi service-setup`)
6. Edit line 37 to point to the new binary file (check online for guidance on using vi editor)
7. Save the change and exit `vi`
8. Exit SSH and disable SSH (if desired)
9. Start Jellyfin in the DSM Package Center

**Comment by nyanmisaka** [comment]
For security reasons, Jellyfin no longer allows updating the ffmpeg path in the WebUI.

https://jellyfin.org/posts/jellyfin-security-and-you/

**Comment by mreid-tt** [comment]
hey @th0ma7, with the work you did for ffmpeg6, you mentioned in this https://github.com/SynoCommunity/spksrc/issues/6174#issuecomment-2366942509 that you only enabled iHD for Apollolake and above. Based on the Wiki on [Intel Quick Sync Video](https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video), my Braswell architecture does support a fair mix of basic QSV functions. Would you consider extending QSV support to my older CPU in ffmpeg7?

**Comment by th0ma7** [comment]
@mreid-tt from my reading you may not have vaapi but still have qsv (although not entirely sure...)

I was able to compile `intel_gpu_top` and hoped to get more on the device info, details and usage from there which could be usfeul for your usecase.  Although it ain't working on my DS918+ (with or without `sudo`, same error, maybe due to older kernel version?).  I'll investigate a bit further to figure out things.
```
$ sudo ./intel_gpu_top
Failed to initialize PMU! (Invalid argument)
```

**Comment by nyanmisaka** [comment]
The easiest way to determine if an intel GPU is supported by iHD and/or i965 is to search in both github repos using the PCIe device ID, e.g. `8086:<DEVICE_ID>`.

**Comment by mreid-tt** [comment]
> @mreid-tt from my reading you may not have vaapi but still have qsv (although not entirely sure...)

Based on my Jellyfin experience I don't have QSV enabled (it crashes on playback when transcoding) but I do have VAAPI. I can test the latter by playing a stream and then constraining the bitrate so it transcodes. The media info shows it's transcoding and the log shows this:
```
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_vaapi))
  Stream #0:1 -> #0:1 (eac3 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
```

**Comment by th0ma7** [comment]
> with the work you did for ffmpeg6, you mentioned in [#6174 (comment)](https://github.com/SynoCommunity/spksrc/issues/6174#issuecomment-2366942509) that you only enabled iHD for Apollolake and above. Based on the Wiki on [Intel Quick Sync Video](https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video), my Braswell architecture does support a fair mix of basic QSV functions. Would you consider extending QSV support to my older CPU in ffmpeg7? Happy to test if this is possible.

I am not blocking `iHD` anymore with `ffmpeg7`.  What does your `vainfo` and `clinfo` show up?  Ref.: https://github.com/SynoCommunity/spksrc/wiki/FAQ-FFmpeg

**Comment by mreid-tt** [comment]
> I am not blocking `iHD` anymore with `ffmpeg7`. What does your `vainfo` and `clinfo` show up? Ref.: https://github.com/SynoCommunity/spksrc/wiki/FAQ-FFmpeg

This is great! Do I need to wait for the [current](https://github.com/SynoCommunity/spksrc/actions/runs/11108111605) build process to complete and install that one or would the one [built](https://github.com/SynoCommunity/spksrc/actions/runs/11062030499) a few days ago be fine to test with?

Also, I presume I'd need to update the `synocli-videodriver` along with installing `ffmpeg7` to test this?

**Comment by th0ma7** [comment]
> > I am not blocking `iHD` anymore with `ffmpeg7`. What does your `vainfo` and `clinfo` show up? Ref.: https://github.com/SynoCommunity/spksrc/wiki/FAQ-FFmpeg
> 
> This is great! Do I need to wait for the [current](https://github.com/SynoCommunity/spksrc/actions/runs/11108111605) build process to complete and install that one or would the one [built](https://github.com/SynoCommunity/spksrc/actions/runs/11062030499) a few days ago be fine to test with?
> 
> Also, I presume I'd need to update the `synocli-videodriver` along with installing `ffmpeg7` to test this?

In theory the older build should do.  Although as I rebased against master with force push the history got lost (although you seem to have found one :)

So yeah, you can definitively install that and see what output it gives.

**Comment by th0ma7** [comment]
@mreid-tt note that I temporarely enabled `x64-7.2` and `aarch64-7.2` in order to get `jellyfin` builds using `ffmpeg7`.

@hgy59 i don't have the intention to keep them enabled as this will chew up a lot of resources, although on the other hand it could be usefull for the few cases that only builds on DSM-7.2...

**Comment by mreid-tt** [comment]
> In theory the older build should do. Although as I rebased against master with force push the history got lost (although you seem to have found one :)
> 
> So yeah, you can definitively install that and see what output it gives.

Downloading from that build the `synocli-videodriver` didn't seem to include an update (even though the Makefile for this PR says it should change). I've installed both packages from the build but the output fails:

```
$ sudo su -s /bin/bash sc-ffmpeg7 -c '/var/packages/synocli-videodriver/target/bin/vainfo'
Trying display: drm
error: failed to initialize display
```

If I change the pointer to `ffmpeg6` the output is the same as in this: https://github.com/SynoCommunity/spksrc/issues/6174#issuecomment-2366933625. I suspect I'll need for your rebase build to complete and then upgrade it again to test.

**Comment by th0ma7** [comment]
@mreid-tt just found the issue, rather simple fix.  Now lets wait for the github-action run to complete to test things up.

**Comment by mreid-tt** [comment]
> @mreid-tt just found the issue, rather simple fix. Now lets wait for the github-action run to complete to test things up.

I've installed the packages from your last build. Unfortunately, the output from the command hasn't changed by much:

```
$ sudo su -s /bin/bash sc-ffmpeg7 -c '/var/packages/synocli-videodriver/target/bin/vainfo'
Trying display: drm
libva info: VA-API version 1.22.0
libva info: Trying to open /var/packages/synocli-videodriver/target/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva error: /var/packages/synocli-videodriver/target/lib/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /var/packages/synocli-videodriver/target/lib/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.22 (libva 2.22.0)
vainfo: Driver version: Intel i965 driver for Intel(R) CherryView - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
```

**Comment by th0ma7** [comment]
Note: procps-ng build issue on DSM-7.2 https://gitlab.com/procps-ng/procps/-/issues/352

**Comment by th0ma7** [comment]
> I've installed the packages from your last build. Unfortunately, the output from the command hasn't changed by much:

@mreid-tt one thing that did: it now works using `sc-ffmpeg7` user.

Now, considering `iHD` driver doesn't load, it really looks like your GPU isn't supported by this driver, which ends-up blocking access to the mediasdk, thus qsv.

It appears you have a DS916+ which uses a braswell CPU (ref: https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model)

Document relatively to `iHD` is here: https://github.com/intel/media-driver
In particular the Supported Platforms section.
Braswell is nowhere to be found.  Thus you fallback to `i965` with vaapi only (unless there's a way to deploy qsv over `i965`?)

**Comment by mreid-tt** [comment]
> Document relatively to `iHD` is here: https://github.com/intel/media-driver
> In particular the Supported Platforms section.
> Braswell is nowhere to be found. Thus you fallback to `i965` with vaapi only (unless there's a way to deploy qsv over `i965`?)

Thank you for checking. Although the wiki mentions QSV support in the hardware, you're correct that the software support appears lacking. I came across a related issue in the same project, where attempts to implement it have been unstable (https://github.com/intel/media-driver/issues/1844). Given this, it may not be practical to pursue support for it.

**Comment by th0ma7** [comment]
@hgy59 based on the download build failure I wonder if the "`download`" isn't actually faulty atm.  Something I'll check later on (or feel free to if you have spare cycles, which I believe you don't currently).

**Comment by mreid-tt** [comment]
> @hgy59 based on the download build failure I wonder if the "`download`" isn't actually faulty atm. Something I'll check later on (or feel free to if you have spare cycles, which I believe you don't currently).

From the logs the source repo does seem to be genuinely down:
```
===>    wget --secure-protocol=TLSv1_2 --timeout=30 --waitretry=0 --tries=5 -nv https://ftp.gnu.org/gnu/libunistring/libunistring-1.1.tar.xz
failed: Connection timed out.
failed: Network is unreachable.
```

This can be confirmed by a number of external sites like:
https://www.isitdownrightnow.com/ftp.gnu.org.html
https://www.freshworks.com/website-monitoring/is-it-down/ftp.gnu.org
https://downforeveryoneorjustme.com/ftp.gnu.org

It appears that switching to mirrors using https://ftpmirror.gnu.org/ is not an option at the moment, as the site is down (possibly all sites behind this domain as well). Based on a cached version of the [GNU Mirror List](https://web.archive.org/web/20240929011450/https://www.gnu.org/prep/ftp.en.html), there are several alternative mirrors available. However, we currently have 34 code files that reference this URL, making the switch a tedious task.

To avoid this kind of issue in the future, we could implement a centralised download mechanism with a fallback system. This would automatically switch to alternative mirrors if the primary one fails, creating a more resilient setup. While this would take significant effort to implement, the alternative is simply waiting for the main repository to come back online.

**Comment by mreid-tt** [comment]
@th0ma7, with the GNU repo up I restarted the jobs for you. All but one completed successfully.

**Comment by th0ma7** [comment]
> @th0ma7, with the GNU repo up I restarted the jobs for you. All but one completed successfully.

Yeah, there a x64 DSM-7.2 specific build error on systemd dependency for udev library.  Finally got a fix for that, now testing that it doesn't have any side effects against other archs.

**Comment by th0ma7** [comment]
Ok, take no. 2, this is now ready for rumble! https://github.com/SynoCommunity/spksrc/actions/runs/11135259226

I strongly advise you to use DSM-7.1 packages, with exception of Jellyfin which is only built for DSM-7.2.  (hopefuly sucesful) feedback welcomed :)

**Comment by th0ma7** [comment]
I did one last round of testing on my end, migrated my TVH environment sucessfully.  Wrapping up and merging.  Thnx.

**Comment by mreid-tt** [comment]
@th0ma7, all packages have been successfully uploaded to the server. Please feel free to publish when ready. I recommend a staggered release, starting with `synocli-videodriver` and `ffmpeg7` before proceeding with the dependent packages.

**Comment by th0ma7** [comment]
I didn't had time to publish anything before leaving this morning.  If you have a moment to do so would be much appreciated.

**Comment by mreid-tt** [comment]
> I didn't had time to publish anything before leaving this morning. If you have a moment to do so would be much appreciated.

Ok, here's a track of the publish status:

- [ ] chromaprint
- [x] ffmpeg5
- [x] ffmpeg7
- [ ] jellyfin
- [x] synocli-net
- [x] synocli-videodriver
- [ ] tvheadend

**Comment by Yod4z** [comment]
hello, i have added ffmpeg7 and removed ffmpeg6 and after this i cant' play video with DTS or EAC3 on videostation.
Do i need to do something?

**Comment by mreid-tt** [comment]
> hello, i have added ffmpeg7, removed ffmpeg6, updated synocli-videodriver and after this i cant' play video with DTS or EAC3 on videostation. Do i need to do something? it play on jellyfin My setup DS916+ DSM 7.2

Hi @Yod4z, playing DTS or EAC3 in VideoStation likely requires patching the built-in `ffmpeg`, which is typically based on FFmpeg 4. This should work independently of any installed versions like `ffmpeg6` or `ffmpeg7`. I recommend reapplying the FFmpeg 4 patch. Please open a separate issue if you'd like to troubleshoot further.

**Comment by th0ma7** [comment]
Indeed, you may be relying to https://github.com/darknebular/Wrapper_VideoStation or other similar patcher.  I suggest you reach out for them for support.

**Comment by Yod4z** [comment]
yes than you both for support it's the warpper not compatible with ffmpeg7 i created an issu
https://github.com/darknebular/Wrapper_VideoStation/issues/65

**Pull request merged**
