### PR TITLE
[DSM 6] Add support for rtd1296

### PR DESCRIPTION
**Pull request by bidorffOL**
_Motivation:_ Initial support for the new rtd1296 toolchain.
_Linked issues:_ This should resolve [#2886](https://github.com/SynoCommunity/spksrc/issues/2886)

### Checklist
- [] Build rule `all-supported` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
@KaraokeStu this PR seems correct

**Comment by m4tt075** [comment]
@ymartin59 Just wondering whether you want to add this into the Projects list, maybe under something like "New platform requests". We do have the toolchain now, but the new ARM8 architecture will probably require further adaptations in several packages. Might thus be more complex than further x64 platforms. But just a thought...

**Comment by Francis2b** [comment]
Any news for making Sonarr and its dependencies work on rtd1296 (DS418)?

**Comment by ymartin59** [comment]
At the moment, online repository reject built packages for this new arch... investigating...

**Pull request merged**
