### PR TITLE
[libev] Fixed base dist site URL

### PR DESCRIPTION
**Pull request by smaarn**
_Motivation:_  Impossible to build libev cross package
_Linked issues:_  None seen so far

### Checklist
- [x] Check that digests still match
- ~~[ ] Build rule `all-supported` completed successfully~~
- ~~[ ] Package upgrade completed successfully~~
- ~~[ ] New installation of package completed successfully~~

### CODE REVIEW

**Comment by ymartin59** [comment]
@hgy59 Thanks. Notice that to reduce commit volume in Git history, I often prefer "rebase and merge" or "squash and merge" actions on PR.

**Comment by hgy59** [comment]
@ymartin59 what do you prefere - "rebase and merge" or "squash and merge"?

**Comment by chickenandpork** [comment]
@ymartin59 did you know it's possible to govern this with the repository settings?  (settings -> options -> bottom, just before the "delete this" part).  By deselecting the other two options, we make it difficult to make the wrong choice.

Screen Shot 2019-10-20 at 15 12 32

**Comment by ymartin59** [comment]
In fact, I often do "squash and merge" which allows me to "normalize" content into a single commit messages (I try to apply always same pattern at least for first line)
I do not disable other merge options because a standard "rebase and merge" would make sense to preserve authorship when commits come from multiple contributors.

**Comment by Diaoul** [comment]
I prefer rebase over merge as it makes the history cleaner. I sometimes squash when I do a lot of intermediate low-quality commits (like small fixes, wip commits, etc.).

**Pull request merged**
