### PR TITLE
Update bazarr 1.0.2 => 1.0.3

### PR DESCRIPTION
**Pull request by smaarn**
## Description

Update bazarr 1.0.2 to 1.0.3

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by smaarn** [comment]
Rebased at head (for followups if required)

**Comment by smaarn** [comment]
One last rebase "for the road".

Quick (and open question): is there anything preventing from releasing this (tiny) PR ? I am asking because the 1.0.4 version has just been released and was planning to prepare another PR (to make sure to not compromise this one in case other issue arises) but if there's anything I need to do to ease review / merge process...

**Comment by th0ma7** [comment]
I don't see any blocker with this "tiny" and trivial PR.  All good with me.

**Comment by smaarn** [comment]
Just checked and it seems that there is an issue with the PLIST.auto feature.
Will be checking.

**Comment by th0ma7** [comment]
There is an issue that I opened on this (and completely forgot to follow-up). https://github.com/SynoCommunity/spksrc/issues/5233

**Comment by smaarn** [comment]
> There is an issue that I opened on this (and completely forgot to follow-up). #5233

@th0ma7 I think I found a fix here: https://github.com/SynoCommunity/spksrc/pull/5244

**Comment by smaarn** [comment]
Rebased at head.

**Comment by smaarn** [comment]
Closing PR as superseded by #5259

**Pull request closed without merging**
