### PR TITLE
New package - fritzctl-1.4.23

### PR DESCRIPTION
**Pull request by bpicode**
_Motivation:_ Add a new package providing a CLI for Fritz!Boxes.
_Linked issues:_ 

### Checklist
- [x] Build rule `all-supported` completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
I would not create a dedicated package for such a small tool but include it in synocli-net #3544

**Comment by ymartin59** [comment]
Please wait for synocli-net - I often amend or rebase my commits...

**Comment by ymartin59** [comment]
@bpicode synocli-net is now available in master. Please rebase to include fritzctl there

**Comment by bpicode** [comment]
@ymartin59 Software written in go would break the build for ppc32 arches, see https://github.com/golang/go/issues/22885. I guess, declaring `UNSUPPORTED_ARCHES = $(PPC_ARCHES)` is a deal-breaker for synocli-net, right?

**Comment by bpicode** [comment]
@ymartin59 yeah, I thought so. PTAL.

**Pull request merged**
