### PR TITLE
Python 3.11.8 update

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

Python 3.11.8 update

Fixes # 

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
@th0ma7 in my local homeassistant work, I have some pending issues.

---

1. Additional wheels for crossenv

   Some wheels require expandvars and one requires pybind11 in the crossenv 
   I temporary added the following lines in cross/python311/Makefile to solve this.

   ```
   # stdc++ bindings for webrtc_noise_gain
   CROSSENV_WHEELS += pybind11==2.11.1
   # for building frozenlist, yarl, ...
   CROSSENV_WHEELS += expandvars==0.12.0
   ```

   wouldn't it be possible to define additional dependencies to install into crossenv

   for example:
   define the following in spk/homeassistant/Makefile
   ```
   ADD_CROSSENV_WHEELS = pybind11==2.11.1 expandvars==0.12.0
   ```
   Than before cross-compiling wheels for a package, all wheels in `ADD_CROSSENV_WHEELS` are added to crossenv.

---

2. cross compile pandas wheel
   pandas==2.1.4 cannot be cross compiled, because it is lacking numpy
   Is is possible, to install cross built numpy into crossenv to solve this?

**Comment by th0ma7** [comment]
> 1. Additional wheels for crossenv
>    Some wheels require expandvars and one requires pybind11 in the crossenv
>    I temporary added the following lines in cross/python311/Makefile to solve this.
>    ```
>    # stdc++ bindings for webrtc_noise_gain
>    CROSSENV_WHEELS += pybind11==2.11.1
>    # for building frozenlist, yarl, ...
>    CROSSENV_WHEELS += expandvars==0.12.0
>    ```

Feature now added.  Quite of a nice addition I must say :rocket: 

> 2. cross compile pandas wheel
>    pandas==2.1.4 cannot be cross compiled, because it is lacking numpy
>    Is is possible, to install cross built numpy into crossenv to solve this?

Wow I tried quite a bit and no luck.  The crossenv does have all the minimal requirements whereas numpy was already included by default from `cross/python311` and remaining using the new functionality:
```
# for pandas
ADDITIONAL_CROSSENV_WHEELS += python-dateutil==2.9.0.post0
ADDITIONAL_CROSSENV_WHEELS += pytz==2024.1
ADDITIONAL_CROSSENV_WHEELS += tzdata==2024.1
```
No luck.  I ended-up creating a bug entry on https://github.com/pandas-dev/pandas/issues/57945

Wait and see what comes next.

**Comment by th0ma7** [comment]
@hgy59 I do have an almost working solution for `pandas` in my local branch.  Issue becomes that updating `Cython` to >= 3.0 https://github.com/pandas-dev/pandas/issues/57945#issuecomment-2016512581 cause `Pyyaml` to fail to build, something I had already documented in the code but that still exist to this day https://github.com/yaml/pyyaml/issues/601.

With the new functionality to allow adding wheels to the `crossenv`, my thinking is now the following:
1. Move the `crossenv` creation to a call into `spksrc.wheel.mk`
2. When `ADDITIONAL_CROSSENV_WHEELS` is captured for a specific wheel, generate a "new" crossenv specific for that wheel in particular

This bescomes way more intrusive but it would allow potentially all worlds to work out properly, what ever is needed (besides gcc version limitations).

That i don't have code for yet and I'd need to get https://github.com/SynoCommunity/spksrc/pull/6002 merged first.

**Comment by th0ma7** [comment]
Now rebased against master, time to confirm status hasn't changed between the two (i.e. still fails at the same places).

**Comment by hgy59** [comment]
@th0ma7 it is not worth any effort for the home assistant package.

Homeassistant dropped Python 3.11 support with v2024.4 and now requires Python 3.12.

If version 2023.12 or 2024.1 works with Python 3.11.8 out of the box, I'll probably take the time to build one of these. Otherwise I'd rather wait for a Python 3.12 package.

**Comment by th0ma7** [comment]
Been lacking cycles lately but i intend to include py312 as well.  But most importantly is the ability to generate as needed a crossenv for wheels that requires specific dependencies that may be an issue to be added in the default build (like panda).  I got prototype code working locally, I'll let you know once i have something to play with.

**Comment by hgy59** [comment]
@th0ma7 BTW they released Python 3.11.9 on April 2, 2024

**Pull request closed without merging**
