### PR TITLE
Update SABnzbd to 3.5.2

### PR DESCRIPTION
**Pull request by Safihre**
Bugfix release of SABnzbd.

### CODE REVIEW

**Comment by Safihre** [comment]
@th0ma7 @hgy Is it already possible to release a package from GitHub Actions or it still needs a compile on a local system?
If it's possible from GitHub Actions I could push updates like this myself.

**Comment by th0ma7** [comment]
You can simply push using github directly.  @publicarray made an awesome documentation on that: https://github.com/SynoCommunity/spksrc/wiki/Publish-a-package-from-Github

**Comment by Safihre** [comment]
Ah, my account at SynoCommunity.com is disabled (didn't need it for many years). So either you'll have to give me access again, or you have to do it 😇

**Comment by Safihre** [comment]
@th0ma7 Realized I want to add some other stuff in this update, so will be back when I figured that out.
Thanks for the help so far :)

**Pull request closed without merging**
