### PR TITLE
Wheel small fixes

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

Small fixes to wheel building
1. non-critical shell error
2. additional messaging when skipping steps
3. simplify and standardize pure-python wheel copying
4. fix code issue with pure-python
5. fix pure-python build from Docker on github-action

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [ ] New Package
- [ ] Package update
- [x] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Review by Safihre — APPROVED** [review]

**Comment by th0ma7** [comment]
@Safihre thnx!

**Comment by Safihre** [comment]
@th0ma7 Could you maybe document somewhere how to use `WHEELS_BUILD_ARGS`? It took me a while to figure out you need to use `[package] args`.

**Comment by th0ma7** [comment]
It is https://github.com/SynoCommunity/spksrc/wiki/Using-wheels-to-distribute-Python-packages in the advanced options section.  Feel free to add if it lacks clarity (or let me know what's missing so I can beef-it-up a bit).

**Comment by Safihre** [comment]
Clear, missed that page before!

**Pull request merged**
