### PR TITLE
syncthing: Upgrade to v1.15.1 and ignore folder permissions by default.

### PR DESCRIPTION
**Pull request by acolomb**
_Motivation:_  Upstream v1.14.0 was released on 2021-03-02.  Some option defaults are changed in this PR, which only applies for new installations, because `config.xml` is (and must be) kept during updates.

The new version introduces a "folder defaults" section in the configuration, which is used to preset the `ignorePerms` option to `true`.  This will not touch any existing folders, but set the option when configuring a new folder to be synced.  Specifically on DSM, the `ignorePerms` option should definitely be used with every Syncthing folder.  Otherwise, it will possibly try to override the UNIX permissions on synced files, which will reset the ACL-based permissions.  Possibly making them unusable for the rest of the DSM services.

Change the default for the `cacheIgnoredFiles` option to `false` (which is the upstream default). Many DiskStations are rather tight on RAM, so deviating from Syncthing's default here is probably a bad idea for most users.  It only matters when many (or very complex) ignore patterns are used in a folder, so usually for power users.  Those will certainly be able to change the option manually.

Drop the obsolete `symlinksEnabled` and `weakHashSelectionMethod` entries.  Switch from `minHomeDiskFreePct` to the new syntax `minHomeDiskFree unit="%"`.

Note that the previous package version should have already self-updated an installed Syncthing binary when the service was running long enough.  So this PR should not really change anything for users updating the SPK.

_Linked issues:_  
Configurable folder defaults: https://github.com/syncthing/syncthing/pull/7131
`symlinksEnabled`: https://github.com/syncthing/docs/commit/392dbd0b
`weakHashSelectionMethod`: https://github.com/syncthing/syncthing/pull/4767

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

(Sorry, I have no DSM installation to spare where Syncthing is not used in production, so testing is limited. Should be low impact though as mentioned above.)

### CODE REVIEW

**Comment by acolomb** [comment]
*A side note about my work on spksrc:* I've been involved with the last few updates to the Syncthing package here and tried to answer any related support requests.  For that purpose, I have been following the spksrc repository on GitHub and received every notification.  That is just becoming too much to handle, just for trying to filter what's related to this package.

So I'm planning to stop those notifications.  If there are any further questions regarding Syncthing on DSM beyond this PR, feel free to mention me (@acolomb) on the issue and I will look into it.  I want to stay involved with future PRs and support, just not get spammed with tens of e-mails a day about packages I never use.

**Comment by publicarray** [comment]
@acolomb Looks good, I would remove busybox from this package and start preparing for DSM7, https://github.com/SynoCommunity/spksrc/wiki/DSM-7.0-Beta 

DSM 7 Build logs:

```
  ERROR: SERVICE_EXE (start-stop-daemon) is unsupported in DSM7
  Please migrate to SERVICE_COMMAND=
  SVC_BACKGROUND=y
  SVC_WRITE_PID=y
```

Please let me know if you need guidance.

Regarding too many messages, Thanks for supporting the package and understand I do the same thing. I visit and filter issue tracker on occasion as well. I hope I remember to ping you on related packages. Maybe add yourself as the package `MAINTAINER` in the makefile ? I don't think @Safihre would mind.

**Comment by Safihre** [comment]
I don't mind 🥳

**Comment by acolomb** [comment]
> Please let me know if you need guidance.

I saw the warning about `SERVICE_EXE`, but decided not to touch this yet.  I'd rather get this update out the door quickly, then focus on the DSM7 stuff in a separate effort.  Are there any similar packages I could use as reference for the transition?  Or a Wiki page describing the different requirements?  Given my limited time and testing capacity right now, I'd rather not delay this update by a quest to make the DSM7 stuff work.

**Comment by publicarray** [comment]
I understand the desire for a seperate PR and that's fine. It's just from my understanding that every release eats up diskspace on our server. So we don't like releases in quick sucession at the moment. I still leave it up to you though.

There are sample packages in https://github.com/SynoCommunity/spksrc/commits/dsm7-packages (I suggest to look at the Transmission package). I posted the [wiki link](https://github.com/SynoCommunity/spksrc/wiki/DSM-7.0-Beta) [above](https://github.com/SynoCommunity/spksrc/pull/4527#issuecomment-809330091). you may find https://github.com/SynoCommunity/spksrc/wiki/Service-Support and https://github.com/SynoCommunity/spksrc/wiki/Makefile-variables#available-variables-in-spk-makefiles helpful too.

I would help test for DSM7 but my NAS died (won't turn on anymore), waiting to get it replaced :cry:

**Comment by acolomb** [comment]
I really don't see a chance on my end to test anything related to DSM7 at the moment.  It will be some time before I even think about upgrading one of my NASes to that.

So I can investigate the needed changes, but not really go through with it.  On the other hand, this PR fixes a common pitfall with the Syncthing package on DSM (not enabling `ignorePerms` for a folder), which is only made possible with the recent upstream release.  So please accept this fix and update first.  I'll look into the DSM7 stuff it no one beats me to it as part of a larger package DSM7 refactoring.

**Comment by publicarray** [comment]
Ok no problem. Would you still consider removing busybox in this update?

**Comment by acolomb** [comment]
> Ok no problem. Would you still consider removing busybox in this update?

I thought it was still needed for DSM6?

**Comment by publicarray** [comment]
No it was needed for DSM5 but since then we have a [generic script](https://github.com/SynoCommunity/spksrc/wiki/Service-Support) that should work for all 3 versions or at least better in DSM6 and DSM7

**Comment by publicarray** [comment]
@acolomb I've made some changes would you mind telling me if you think they are OK?

**Comment by acolomb** [comment]
Sorry I tried to build with your changes applied, but cannot even get the build to start anymore :-(

```make
root@barnov:/spksrc/spk/syncthing# make all-supported
===>  Pre-build native dependencies for parallel build
make supported-arch-88f6281 supported-arch-aarch64 supported-arch-armv7 supported-arch-evansport supported-arch-hi3535 supported-arch-qoriq supported-arch-x64
make[1]: Entering directory '/spksrc/spk/syncthing'
===>  BUILDING package for arch 88f6281 with SynoCommunity toolchain
make[2]: Entering directory '/spksrc/spk/syncthing'
/spksrc/spk/syncthing/work-88f6281-6.1/tc_vars.mk:1: *** An error occured while setting up the toolchain, please check the messages above.  Stop.
make[2]: Leaving directory '/spksrc/spk/syncthing'
make[1]: [../../mk/spksrc.spk.mk:430: supported-arch-88f6281] Error 2 (ignored)
===>  BUILDING package for arch aarch64 with SynoCommunity toolchain
make[2]: Entering directory '/spksrc/spk/syncthing'
/spksrc/spk/syncthing/work-aarch64-6.1/tc_vars.mk:1: *** An error occured while setting up the toolchain, please check the messages above.  Stop.
make[2]: Leaving directory '/spksrc/spk/syncthing'
make[1]: [../../mk/spksrc.spk.mk:430: supported-arch-aarch64] Error 2 (ignored)
```
... and so on for all supported archs.

I've pulled the latest Docker image, but still no luck.

**Comment by acolomb** [comment]
Sorry, a manual `rm -rf work-*` solved the build problems.

**Comment by acolomb** [comment]
Installation and upgrade worked on my DS418j (rtd1296 / aarch64) with DSM 6.2.3-25426 Update 3.  Sorry I can't help test any DSM7 changes yet.

**Comment by publicarray** [comment]
Thanks @acolomb! FYI the `make clean` command that does the same thing (usually good idea to rebuild when there are changes in Makefiles or cross/{package}).

I'm waiting on #4539 and #4539 before I merge any PRs at the moment, since they fix issues with the framework that where introduced when the DSM7 branch was merged.

**Comment by acolomb** [comment]
Syncthing v1.15.1 was released in the meantime, so I updated this PR.  Otherwise it would have updated itself right after installation anyway.  Regarding the packaging, nothing else changed.

**Comment by hgy59** [comment]
as #4539 is now on the master branch, you have to remove ` >> ${INST_LOG}`  in `service-setup.sh` for service_postinst to work.

**Comment by publicarray** [comment]
Thanks @acolomb :+1:  you should see it in the package center soon!

**Comment by guidorb79** [comment]
syncthing 1.15.1-21 installed right now on dsm7 from synocommunity repo thank you all!!!!

**Comment by DigitalBox98** [comment]
Well done :)

**Pull request merged**
