### PR TITLE
syncthing: fix SERVICE_CERT_RELOAD

### PR DESCRIPTION
**Pull request by hgy59**
## Description

follow up of #5117
- revert to use SERVICE_CERT_RELOAD

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [ ] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Review by acolomb — APPROVED** [review]
Very nice now.  LGTM from my side.

**Comment by hgy59** [comment]
@acolomb any need to test certificates with DSM 6?

**Comment by acolomb** [comment]
Let me just try to install on my DSM 6 box and see whether the certificate management GUI still works.

**Comment by acolomb** [comment]
Just where do I find the build artifacts again?

**Comment by acolomb** [comment]
There is an unrelated error, which resulted from our naming discussion in #4930 about underscore vs. dash to delimit the service name.

The ca_reloader.sh script still uses the name `syncthing-webui` while the service definition is installed as `syncthing_webui`.  See this line:
https://github.com/hgy59/spksrc/blob/revert_syncthing_cert_reload/spk/syncthing/src/ca_reloader.sh#L3

It needs to be changed to refer to `syncthing_webui` as well.

**Comment by hgy59** [comment]
nice, it works to switch the certificate on my DS-218 with DSM 6.2.4.

**Pull request merged**
