### PR TITLE
Transmission: Update to 4.0.5

### LINKED ISSUE #5867: Transmission download speed have decreased since update to 4.0.4-23
Since updating to 4.0.4, download speeds have decreased significantly.
I downgraded to the previous version 4.0.3, and it works fine now.

### PR DESCRIPTION
**Pull request by mreid-tt**
## Description

This pull request includes the following:

1. Update to Transmission v4.0.5 (bugfix-only release)
2. Migrate to new shared folder handling
3. Remove patch for empty blocklist files on 32-bit ARM (resolved upstream)

Fixes #5867

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

### CODE REVIEW

**Comment by mreid-tt** [comment]
Hello @d4niel-P and @dwardor, a recent update, Transmission 4.0.5, has been released. It is expected that the upstream source repository now incorporates the corrections we implemented for blocklists on ARMv7 architectures (#5956). If you have a moment, could you please test the ARMv7 package generated by the GitHub build action?

To do so, navigate to Checks -> Build -> Artifacts, and download the `Packages for armv7-7.1`. Your assistance in validating this version would be greatly appreciated.

**Comment by mreid-tt** [comment]
@fixsssator, we're pleased to inform you that Transmission 4.0.5, aimed at resolving the download speed concern you brought to our attention, is now available. We value your feedback and would appreciate it if you could take a moment to test this release before it undergoes official publication. To facilitate this, kindly navigate to Checks -> Build -> Artifacts, and proceed to download the `Packages for x64-7.1`. Thank you for your assistance.

**Comment by d4niel-P** [comment]
> Hello @d4niel-P and @dwardor, a recent update, Transmission 4.0.5, has been released.
Everything seems to be fine. Blocklist dl works, speeds are all right.

**Comment by fixsssator** [comment]
> @fixsssator, we're pleased to inform you that Transmission 4.0.5, aimed at resolving the download speed concern you brought to our attention, is now available. We value your feedback and would appreciate it if you could take a moment to test this release before it undergoes official publication. To facilitate this, kindly navigate to Checks -> Build -> Artifacts, and proceed to download the `Packages for x64-7.1`. Thank you for your assistance.

Thank you so much.

Speeds are all right. Everything seems to be fine now.

**Comment by dwardor** [comment]
> Hello @d4niel-P and @dwardor, a recent update, Transmission 4.0.5, has been released. It is expected that the upstream source repository now incorporates the corrections we implemented for blocklists on ARMv7 architectures (#5956). If you have a moment, could you please test the ARMv7 package generated by the GitHub build action?
> 
> To do so, navigate to Checks -> Build -> Artifacts, and download the `Packages for armv7-7.1`. Your assistance in validating this version would be greatly appreciated.

Just installed and tested without issue.

**Pull request merged**
