### PR TITLE
Updated git to 2.8.1/ Updated patch for fast hash and X64 hosts

### PR DESCRIPTION
**Pull request by GoodOmens83**
Updated git to the latest stable: 2.8.1

Changed the patch file to allow for fast hash for x64 hosts.  Make all-supported ran fine.

### CODE REVIEW

**Comment by Dr-Bean** [comment]
The patch file needs to have the extension `.patch`, it won't be applied otherwise ;)

Could you also take a look at fixing the offset for the  `git-less-hardlinks` patch? Otherwise we'll pick that up separately.

**Comment by GoodOmens83** [comment]
Fixed and squashed.

Also good catch.

**Comment by Dr-Bean** [comment]
@GoodOmens83 I've merged your changes wrt the xdl hash/x64 while updating to git 2.8.2 separately with https://github.com/SynoCommunity/spksrc/commit/796519090ae9b29384de5f1afc6c6d08cc7d8188.
Thanks for the PR :)

**Comment by GoodOmens83** [comment]
@Dr-Bean: You did?  I see you removed the old patch but didn't add in the change.

**Comment by Dr-Bean** [comment]
Yup, my bad. It's part of the released packages, I just didn't push all the changes to Github (yet).

**Comment by Dr-Bean** [comment]
Here we go: https://github.com/SynoCommunity/spksrc/commit/7de6c3c0ae25914152e4a8f55415ba5eb63e0913

**Pull request closed without merging**
