### PR TITLE
Update cloudflared to 2024.10.1

### PR DESCRIPTION
**Pull request by IngmarStein**
## Description

Changelog: https://raw.githubusercontent.com/cloudflare/cloudflared/master/RELEASE_NOTES

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by IngmarStein** [comment]
CC @karasevm as the package maintainer

**Comment by hgy59** [comment]
@IngmarStein I can't see relevant changes since 2024.8.2 - is it worth the update?

**Comment by IngmarStein** [comment]
@hgy59 Tbh, it's mostly to get rid of the "update your tunnel" nag on the Zero Trust dashboard and I hope it's aligned with SynoCommunity's mission "Bleeding Edge: We provide frequent updates to our packages so you can enjoy new features of your favorite softwares.".

**Comment by IngmarStein** [comment]
I've updated this PR to 2024.9.0 which comes with a number of fixes:

```
2024.9.0
- 2024-09-10 TUN-8621: Fix cloudflared version in change notes.
- 2024-09-06 PPIP-2310: Update quick tunnel disclaimer
- 2024-08-30 TUN-8621: Prevent QUIC connection from closing before grace period after unregistering
- 2024-08-09 TUN-8592: Use metadata from the edge to determine if request body is empty for QUIC transport
- 2024-06-26 TUN-8484: Print response when QuickTunnel can't be unmarshalled
```

**Comment by hgy59** [comment]
just missed to write a note "never trust a `.0` version" ... 😆

**Comment by IngmarStein** [comment]
Too late :)

**Comment by hgy59** [comment]
So with 2024.9.1 they reverted 2024.9.0. Doesn't this mean that 2024.9.1 is the same as 2024.8.3?

**Comment by IngmarStein** [comment]
That's also how I read it.

**Comment by IngmarStein** [comment]
This PR was updated for 2024.10.0.

**Comment by luckman212** [comment]
Today we have 2024.10.1 @IngmarStein 

Any idea if your PR will be merged? I hope so!

**Comment by IngmarStein** [comment]
@luckman212, I'll update the PR to 2024.10.1 later today. The changelog was already up yesterday, but the GitHub release only appeared later due to https://github.com/cloudflare/cloudflared/commit/6ba0c25a9293c488be6fab4540cfee4d519e5326.

**Comment by IngmarStein** [comment]
@luckman212 Done.

I'm not a maintainer, so have no idea if or when this will be merged.

**Comment by IngmarStein** [comment]
@mreid-tt in case you're processing the backlog of version bumps: this is also ready to go.

**Comment by lmerega** [comment]
You're totally righe. I moved to docker too. Thx

**Comment by luckman212** [comment]
@lmerega If you want, I can compile an .spk for version 2025.1.0 for your model, if you tell me which one you have. I just did this for my DS1621+ (V1000). I have a build environment set up for it.

screenshot_p4eNq834

**Comment by mreid-tt** [comment]
> @lmerega If you want, I can compile an .spk for version 2025.1.0 for your model, if you tell me which one you have. I just did this for my DS1621+ (V1000). I have a build environment set up for it.

Feel free to submit a PR for a new release and it can be published for everyone.

**Comment by luckman212** [comment]
Ok.... https://github.com/SynoCommunity/spksrc/pull/6390

**Pull request merged**
