### PR TITLE
fishnet: Removal as rewriten in Rust and require a new package

### LINKED ISSUE #5043: META: Python 3.10 / 3.11 package status
# Python 3.10 package status

## High-level python PR
- [x] python310 (3.10.1) #5044
- [ ] pre-download wheels #4971
- [x] mysqlclient wheel #5068
- [x] avoid error for package without wheel #5092
- [x] python310 (3.10.2) #5101
- [x] #5169
- [x] python310 (3.10.4) #5171
- [x] #5175
- [x] Refactor crossenv spksrc.wheel.mk #5180
- [x] rust wheel support & update to python 3.10.8 #5435

## Packages formally using python 3.x
| PACKAGE | Python 3.10 migration | Published | Python 3.11 migration | Published 3.11 |COMMENT |
|----------------|-------------------------------|--------------|--------------|--------------|-----------------|
| bazarr | ✔️ | ✔️ | | | Follow-up update #5139 (@smaarn) | 
| beets | ✔️ | ✔️ | | | #4946 |
| borgbackup | ✔️ | ✔️ | | | #5048 (co-author @sunlei)<br>Fixed: https://github.com/borgbackup/borg/issues/6105 |
| domoticz |     |      | | |  Version online uses `python38` | 
| duplicity | ✔️ | ✔️ | | | #5054 |
| fishnet | ❌️ | ❌️ | | | @mayweed Rewritten in Rust (removal #5216) |
| flexget | ✔️ | ✔️ | | | #5176 |
| homeassistant | ✔️ | ✔️ | | | #5579, #5096, ARMv5 support pending: https://github.com/numpy/numpy/issues/20664<br>Looks like working based on testing https://github.com/SynoCommunity/spksrc/pull/5095/commits/fbd98191653d2138140c697454d41e82edbd64ab<br>Confirmed, fixed https://github.com/SynoCommunity/spksrc/pull/5155|
| mercurial | ✔️ | ✔️ | | | #5045 |
| octoprint | ✔️ | ✔️ | | | #5217 |
| plexpy-custom | ✔️ |  | | | Ready for migration but BUG with the package install, to remove? |
| rdiff-backup | ✔️ | ✔️ |  | | #5447 |
| rutorrent | ✔️ | ✔️ | | | Migration to DSM7 #5455, #5669, #5617 |
| sabnzbd | ✔️ | ✔️ | ✔️ |✔️ | #5109 (@Safihre)<br>#5137<br>#5527 |
| sickchill | ✔️ | ✔️ | | |  #5431 @miigotu |
| salt-master | ✔️ | ✔️ | | | #5017 co-author: @arnebjarne  |
| salt-minion | ✔️ | ✔️ | | | #5017 co-author: @arnebjarne, #5145 |
| tvheadend | ✔️ | ✔️ | | |  |
| znc | ✔️ | ✔️ | | | #4951, #5091|

## Packages formally using python 2.x (#4524)

| PACKAGE | python 3.10 migration | DSM7 migration | Python 3.10 Published | Python 3.11 migration | Published 3.11 |COMMENT |
|----------------|-------------------------------|-----------------------|---------------|----------------|------|-------|
| deluge | ✔️  | ✔️  |  ✔️ |  #5728 |   | #4153, #5202, #5398 |
| ffsync |  |  |  | ✔️  | ✔️  |  #5942  |
| haproxy |   |   |   |   |  |  | 
| salt-master | ✔️ | ✔️ | ✔️ | |  | #5017 co-author: @arnebjarne  |

## Framework clean-up
| apps | dependent packages | Removed | COMMENT |
|--------|------------------------------|---------------|-----------------|
| python3 (cross, spk, native) | none |  ✔️ | #5316 |
| python38 (cross, spk, native) | none |  TODO | to remove once all python3.x packages published |
| `cross/asyncstdlib` | none |  ✔️ | #5175 |
| `cross/borgbackup` | `borgbackup`  | ✔️ | #5048 |
| `cross/cryptography` |  `duplicity` | n/a | Mandatory to build `abi3` wheels
| `cross/cryptography-legacy` | `python2` | TODO | to remove once all python3.x packages published |
| `cross/deluge` | `deluge`  | ✔️ | #5398 |
| `cross/dtlssocket` | `homeassistant`  |  N/A | Unable to migrate to `pip` |
| `cross/duplicity` | `duplicity`  | ✔️ | #5054 |
| `cross/gevent` | `ffsync` |   |   |
| `cross/greenlet` | `ffsync`, `python38`  |   |   |
| `cross/immutables` | <s>`python3`</s>, `python38`  |  TODO | to remove once all python3.x packages published |
| `cross/libtorrent` | `deluge`  | ✔️ | #5398  |
| `cross/lxml` | `python2`, <s>`python3`</s>, `python38`  |   |   |
| `cross/m2crypto` | `python2`  |   |   |
| `cross/mercurial` | `mercurial` |  ✔️ | #5045  |
| `cross/msgpack-python` |  `python2`, <s>`python3`</s>, `python38` |   |   |
| `cross/numpy` | `homeassistant` | ✔️ | #5096, ARMv5 support pending: https://github.com/numpy/numpy/issues/20664<br>Fixed https://github.com/SynoCommunity/spksrc/pull/5155 |
| `cross/octoprint` | `octoprint` | ✔️ | #5217 |
| `cross/pillow` | none | ✔️ | #5175 |
| `cross/pillow_py2` | `python2` |   |   |
| `cross/pocketsphinx` | none | ✔️ | #5175 |
| `cross/poetry` | none | ✔️ | #5508 |
| `cross/pyalsa` | `python2` |   |   |
| `cross/pyaudio` | `python2`  |   |   |
| `cross/pycryptodome` | none | ✔️ | #5175 |
| `cross/pycryptodomex` | none | ✔️ | #5175 |
| `cross/pycurl` | `python2`, <s>`python3`</s>, `python38` |   |   |
| `cross/PyNaCl` | none | ✔️ | #5175 |
| `cross/pyyaml` | `python2`, <s>`python3`</s>, `python38` |   |   |
| `cross/pyzmq` | `python2` |   |   |
| `cross/rencode` | `deluge`  | ✔️ | #5398 |
| `cross/ruamel.yaml` | <s>`python3`</s>, `python38` |  TODO | to remove once all python3.x packages published |
| `cross/sphinxbase` | `cross/pocketsphinx`  | ✔️ | #5175  |
| `cross/stockfish-niklasf` | `spk/fishnet`  | ✔️ | @mayweed Rewritten in Rust (removal #5216)  |
| `cross/ujson` | `homeassistant` |  ✔️ | #5096, Solved: https://github.com/ultrajson/ultrajson/issues/496 |
| `cross/umemcache` | none |  ✔️ | #5175  |
| `cross/uwsgi` | `python2` |   |   |
| `cross/webrtcvad` | none | ✔️ | #5175  |

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

Removal of `fishnet` package and dependency as it will require a totally new package since code was migrated to rust https://github.com/SynoCommunity/spksrc/issues/5043#issuecomment-1080393655

Fixes #5043

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by th0ma7** [comment]
@mayweed are you good with its removal?  Until a newer rust package gets created (if ever)?

**Comment by hgy59** [comment]
I prefere not to remove packages for such a reason.
If the build fails, you could declare the package BROKEN and add respective information to the BROKEN file.
Otherwise it would be difficult to migrate to the rust version as former implementation is not visible anymore.

**Comment by th0ma7** [comment]
@hgy59 I've looked at the current setup and if I get this right it is not even usable as it stands.  This is even worst than broken.

A totally new package is needed to replace this one.  In the meantime this is useless obsolete code for my standpoint.

**Comment by Safihre** [comment]
I agree, let's remove this dead code.

**Pull request merged**
