### PR TITLE
FFmpeg update to version 4.1.4

### PR DESCRIPTION
**Pull request by th0ma7**
_Motivation:_  While preparing updated tvheadend package I noticed a newer version of FFMPEG
_Linked issues:_  None.

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by th0ma7** [comment]
Ended-up building `all-supported` 
```
$ ll
total 273956
drwxr-xr-x  2 th0ma7 th0ma7     4096 aoû  1 18:36 .
drwxr-xr-x 12 th0ma7 th0ma7     4096 jui 31 22:46 ..
-rw-r--r--  1 th0ma7 th0ma7 19220480 aoû  1 05:58 ffmpeg_88f6281-6.1_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 17571840 aoû  1 05:58 ffmpeg_aarch64-6.1_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 17377280 aoû  1 05:58 ffmpeg_alpine-6.1_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 17838080 aoû  1 05:58 ffmpeg_armada370-6.1_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 17838080 aoû  1 05:58 ffmpeg_armada375-6.1_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 17848320 aoû  1 05:58 ffmpeg_armada38x-6.1_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 17838080 aoû  1 06:31 ffmpeg_armadaxp-6.1_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 17459200 aoû  1 07:57 ffmpeg_comcerto2k-6.1_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 19077120 aoû  1 09:22 ffmpeg_evansport-6.1_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 18298880 aoû  1 10:45 ffmpeg_hi3535-6.1_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 17756160 aoû  1 12:05 ffmpeg_ipq806x-1.2_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 18329600 aoû  1 13:31 ffmpeg_monaco-6.1_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 19015680 aoû  1 14:37 ffmpeg_ppc853x-5.2_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 21534720 aoû  1 16:02 ffmpeg_qoriq-6.1_4.1.4-12.spk
-rw-r--r--  1 th0ma7 th0ma7 23500800 aoû  1 18:36 ffmpeg_x64-6.1_4.1.4-12.spk
```
All is looking goof.

**Comment by th0ma7** [comment]
BTW, ffmpeg 4.2 just got out today...

**Comment by ymartin59** [comment]
@th0ma7 May you please try to update to 4.2.x

**Comment by th0ma7** [comment]
Opened a new pull request #3778 for FFMPEG 4.2.1.
Closing this one.

**Pull request closed without merging**
