### PR TITLE
Update openssl to 1.0.2q

### PR DESCRIPTION
**Pull request by STemplar**
Motivation: update OpenSSL 1.0.2 branch to version q.
Linked issues:

### Checklist
- [] Build rule `all-supported` completed successfully
- [] Package upgrade completed successfully
- [] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
Why not, but this requires to validate all application/packages that depends on openssl... I would not create a "1.1" branch until an application really requires it.

**Comment by STemplar** [comment]
> 
> 
> Why not, but this requires to validate all application/packages that depends on openssl... I would not create a "1.1" branch until an application really requires it.

Oops, noob error. I didn't want to add the "OpenSSL 1.1.0 series" commit to this Pull request.

**Comment by Cnp-ghprb** [comment]
I have a dupe PR that was a simple bump before I saw yours (which predates mine).  Sorry, I’ll cancel my dupe

**Comment by hgy59** [comment]
Do we need openssl 1.0.x package anymore?
Just found that on my DS-218+ with DSM 6.2.2-24922 Update 3 there is already a newer version included as `/bin/openssl`:  `OpenSSL 1.0.2r-fips  26 Feb 2019`

``` bash
$ uname -a
Linux ******* 4.4.59+ #24922 SMP PREEMPT Mon Aug 19 12:13:37 CST 2019 x86_64 GNU/Linux synology_apollolake_218+
```

So we could focus to update the openssl community package to version 1.1.x ?

**Comment by hgy59** [comment]
as openssl is updated to 1.0.1.u this PR got obsolete.

**Pull request closed without merging**
