### PR TITLE
[WIP] ffmpeg: Update to version 4.4.1

### PR DESCRIPTION
**Pull request by th0ma7**
## Description

Update to version 4.4.1

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by hgy59** [comment]
@th0ma7 while cleaning up the `BUILD_DEPENDS` for native dependencies I found, that cross/x265 has warnings regarding numa and nasm dependencies:
```
-- Could NOT find NUMA (missing: NUMA_ROOT_DIR NUMA_INCLUDE_DIR NUMA_LIBRARY)
-- Could NOT find nasm (missing: NASM_EXECUTABLE)
```

When I fixed this with:
```
CMAKE_ARGS += -DNUMA_ROOT_DIR=$(STAGING_INSTALL_PREFIX) -DNUMA_LIBRARY=$(STAGING_INSTALL_PREFIX)/lib
CMAKE_ARGS += -DNASM_EXECUTABLE=$(NASM_PATH)/nasm
```

I get build errors like:
```
/spksrc/cross/x265_update/work-evansport-6.1/x265_3.5/source/common/param.cpp: In function ‘char* strtok_r(char*, const char*, char**)’:
/spksrc/cross/x265_update/work-evansport-6.1/x265_3.5/source/common/param.cpp:57:65: error: ‘char* strtok_r(char*, const char*, char**)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static char* strtok_r(char* str, const char* delim, char** nextp)
```

So may be this could be fixed in the ffmpeg update here.

**Comment by th0ma7** [comment]
> So may be this could be fixed in the ffmpeg update here.

@hgy59 I'm ok at taking that over from here once your PR is merged.

**Comment by hgy59** [comment]
> @hgy59 I'm ok at taking that over from here once your PR is merged.
> 
> EDIT: Bug already exists https://bitbucket.org/multicoreware/x265_git/issues/614/compile-error-in-x265-snapshot-20220209

I figured out that this error occurres only when libnuma is really found and used. 
Than I tried to update libnuma to v2.0.14, but this version fails to build due to embedded asm instructions.

After reading [this article](https://mailman.videolan.org/pipermail/x265-devel/2017-May/011023.html), I vote for completly removing libnuma from x265 dependencies.

**Comment by th0ma7** [comment]
> After reading [this article](https://mailman.videolan.org/pipermail/x265-devel/2017-May/011023.html), I vote for completly removing libnuma from x265 dependencies.

@hgy59 Done.  I've also included changes from your PR directly into this one for x265.

**Comment by hgy59** [comment]
> @hgy59 Done. I've also included changes from your PR directly into this one for x265.

just updated my PR to remove libnuma dependency and to activate assembler code for evansport (8 bit library only).

**Comment by th0ma7** [comment]
@hgy59 there is something odd, I did a rebase but your changes do not appear, netiher there weren`t any conflicts while there should have been?!?  I`ll revisit tomorrow with a pair of fresh eye.

**Pull request merged**
