### PR TITLE
Move deluge2.0.3 to python3

### PR DESCRIPTION
**Pull request by favoretti**
_Motivation:_  DSM7 support for Deluge 2.0.3
_Linked issues:_  #4429

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by hgy59** [comment]
@favoretti we do not want to make such package updates on the dsm7 branch.
Please create a PR to for this on the master branch as it must compile and run at least for DSM 6.1 too.
When this is possible, works and is merged to master you might ask @publicarray to rebase the dsm7 branch to create packages for DSM7.

Otherwise it will be almost impossible to merge the dsm7 branch back to master without breaking packages for DSM < 7.0.

If it is not possible to build or run this update for DSM < 7.0 we probably need to create additional dsm7 compatible cross-packages (for example, when an updated package like boost needs compiler or libraries that are available only in the DSM 7 toolchains we must support two different versions of cross/boost for DSM >= 7.0 and DSM < 7.0)

**Comment by favoretti** [comment]
Ah, I see. I'll rebase this on master then first.

**Comment by mesquitafmr** [comment]
Hello guys. @favoretti any updates? Thanks!

**Comment by publicarray** [comment]
@hgy59 FYI the `dsm7` branch no longer exists on GitHub as everything has already been merged into master. https://github.com/SynoCommunity/spksrc/branches/all `dsm7-packages` is only useful for the wallabag package.

**Pull request closed without merging**
