### PR TITLE
Update SABnzbd to 3.7.1 and Python 3.11

### PR DESCRIPTION
**Pull request by Safihre**
## Description

Update SABnzbd to 3.7.1.

## Checklist

- [x] Build rule `all-supported` completed successfully
- [x] New installation of package completed successfully
- [x] Package upgrade completed successfully (Manually install the package again)
- [x] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [x] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by Safihre** [comment]
@th0ma7 You mentioned on Discord you were working on Python 3.11.1, is this something I should wait for with the SABnzbd update?

**Comment by th0ma7** [comment]
If it mandatory requires 3.11 then yes.

**Comment by hgy59** [comment]
@Safihre just activated this version

**Comment by th0ma7** [comment]
I thought i had activated version juat a few days ago 3.11.1 ?  And isn't 3.7 deprecated at this point as no other package depends on it?

**Comment by Safihre** [comment]
> @Safihre just activated this version

Thanks! I tried it 2 days ago but server was giving me 503's so couldn't do it.

**Pull request merged**
