### PR TITLE
Set of package translations for publish

### PR DESCRIPTION
**Pull request by ymartin59**
_Motivation:_ Add link to permissions FAQ and wizard french translations to publish

### Checklist
- [X] Build rule `all-supported` completed successfully
- [X] Package upgrade completed successfully
- [X] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
I documented escaping for DESCRIPTION{_xxx} variables in https://github.com/SynoCommunity/spksrc/wiki/Makefile-variables

**Comment by Safihre** [comment]
This works, I managed to [build SABnzbd again now](https://travis-ci.org/Safihre/spksrc/builds/400121037).
But we should also do a full search-and-replace of `\\\` -> `\` throughout the projects because there are just so many, also with the `sabnzbd` package I was trying to build, it failed initially due to this.
Just leaving it everywhere would cause confusion for people trying to build packages locally, since the errors are unexpected.

**Comment by ymartin59** [comment]
I agree. I will process Makefile for that replacement.

**Comment by ymartin59** [comment]
@Safihre Here are escapes replacement

**Pull request merged**
