### PR TITLE
Update pngquant

### PR DESCRIPTION
**Pull request by hgy59**
## Description

- add cross/pngquant3 built with rust
- keep pngquant v2 in cross/pngquant2
- add cross/libimagequant-source to be used by cross/pngquant3
- adjust build order in diyspk/image-optim

minor adustments in tvheadend:
- update to openssl3
- add remarks for pngquant

Closes #6118

## Checklist

- [x] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Library/Tool update

### CODE REVIEW

**Comment by hgy59** [comment]
@th0ma7 we never published (current) tvheadend 4.3.20230408-37 (latest published is v4.3.20230408-36)

rev -36 still depends on python310

with this PR tvheadend openssl dependency is updated to openssl3

I propose to finally publish rev -37 with the updates of this PR.
- it will remove potential issue by mixing openssl and openssl3 (from python311)
- it will have the pngquant update
- other update candidates
  - libhdhomerun to v 20231214
  -

**Comment by th0ma7** [comment]
@hgy59 Don't bother with `tvheadend`.  I'll migrate it to newer python along with ffmpeg6 with #6148

**Comment by th0ma7** [comment]
@hgy59 I guess we are colliding for a bit with the tvheadend changes with my #6148, we'll have to sync for the merge.  I'd rather sync of your changes if you're ready to merge before I am.

**Comment by hgy59** [comment]
> @hgy59 I guess we are colliding for a bit with the tvheadend changes with my #6148, we'll have to sync for the merge. I'd rather sync of your changes if you're ready to merge before I am.

Ok, didn't expect your work on tvheadend so soon, ...

**Pull request merged**
