### PR TITLE
Update SABnzbd to 2.3.4

### PR DESCRIPTION
**Pull request by Safihre**
### Checklist
- [x] Build rule `all-supported` [completed successfully](https://travis-ci.org/Safihre/spksrc/builds/385533764)
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

### CODE REVIEW

**Comment by ymartin59** [comment]
@Safihre Is there a way to get sabnzbd "no-arch" package? If "sabyenc" is the only native dependency, why not move its wheel to python 2 package too?

**Comment by Safihre** [comment]
@ymartin59 There is also `unrar`, `7zip` and `par2` that need native, so not really possible to make `no-arch`.

**Comment by ymartin59** [comment]
@Safihre OK. So maybe when these tools will be delivered in a common dedicated "files" package...

**Comment by Safihre** [comment]
@ymartin59 We discussed that before, but didn't do that because the only package that uses these dependencies is SAB and NZBGet (only `unrar` and `p7zip`), so not really worth the effort it seems.
Plus we want to update `sabyenc` from time to time (few minor releases in past months), which would then require updates of the whole Python package.

**Pull request merged**
