### PR TITLE
gitea fix ssh

### PR DESCRIPTION
**Pull request by publicarray**
## Description

This is just a followup to https://github.com/SynoCommunity/spksrc/pull/5028#issuecomment-1004382549

## Checklist

- [x] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Bug fix
- [ ] New Package
- [ ] Package update
- [ ] Includes small framework changes
- [x] This change requires a documentation update (e.g. Wiki)

### CODE REVIEW

**Comment by publicarray** [comment]
Thanks @Libbum for your help

**Comment by publicarray** [comment]
I think this leaves the following done by the user as root

> in `/etc/group`, `sc-gitea` to be added to `ssh-user`
> in `/etc/passwd`, change `sc-gitea`

**Comment by publicarray** [comment]
Sigh

Build fails becaurse the binaries have been updated. I'm tempted to just build the frontend from source again.

```
===>    Checking sha1sum of file gitea-src-1.15.9.tar.gz
===>      Wrong sha1sum for file gitea-src-1.15.9.tar.gz
```

**Comment by Wuszek** [comment]
@publicarray All checks passed, is this PR ready to merge? :)

**Comment by publicarray** [comment]
@Wuszek in theory yes, but I still haven't been able to test this with DSM 6 yet.

**Comment by Wuszek** [comment]
@publicarray we should update gitea to 1.16.0 -> https://github.com/go-gitea/gitea/releases

**Comment by publicarray** [comment]
Thanks, yea that update does have some nice changes 👍

**Comment by hgy59** [comment]
@publicarray is there anything to do?
I cannot see what really fixes the ssh login - is there only some documentation missing?

**Comment by publicarray** [comment]
Yea basically. However I did not get it to work fully (I still can't clone from git cli on DSM7 as the user (sc-gitea) doesn't have the right permissions or something) I was hoping more people would test this first.

**Comment by publicarray** [comment]
@hgy59 this should be safe to merge though

**Comment by Wuszek** [comment]
> @hgy59 this should be safe to merge though

Tested artifact yesterday on DSM6, updated from 1.15.0 and works OK.

**Pull request merged**
