### PR TITLE
cross/nmap: fix build

### PR DESCRIPTION
**Pull request by smaarn**
_Motivation:_  `cross/nmap` was no longer compiling

### Checklist
- ~~[ ] Build rule `all-supported` completed successfully~~
- ~~[ ] Package upgrade completed successfully~~
- ~~[ ] New installation of package completed successfully~~

### CODE REVIEW

**Comment by hgy59** [comment]
@smaarn on #4195 I have updated nmap and recognized that `CFLAGS="$(TC_EXTRA_CFLAGS)"` is not required at all.

**Comment by smaarn** [comment]
> @smaarn on #4195 I have updated nmap and recognized that `CFLAGS="$(TC_EXTRA_CFLAGS)"` is not required at all.

I guess the least amount of code there is, the better :)

**Comment by smaarn** [comment]
Closing since it's redundant with parts of #4195

**Comment by smaarn** [comment]
@hgy59 following your feedback I removed the customization. At this stage I don't know what's your timeline in terms of delivery of #4195  so I'll let you decide whether or not to close this PR !

**Review by hgy59 — APPROVED** [review]

**Pull request merged**
